#!/bin/sh
export WORKING_DIR=`pwd`

export CFLAGS="-O3 -I$WORKING_DIR/local/include"
export CPPFLAGS=-I$WORKING_DIR/local/include
export CXXFLAGS="-O3 -I$WORKING_DIR/local/include"
export LDFLAGS=-L$WORKING_DIR/local/lib
export PATH=$WORKING_DIR/local/bin:$PATH

export TEXMACS_PATH=$WORKING_DIR/texmacs/src/TeXmacs

export PATH=$(echo "$PATH" | sed 's/c:/\/c/g')
export PATH=$(echo "$PATH" | sed 's/\\/\//g')
export PATH=$PATH:"/c/Program Files (x86)/Inno Setup 6/"

export MAKE=mingw32-make
export PKG_CONFIG_PATH=$WORKING_DIR/local/lib/pkgconfig
