@c -*-texinfo-*-
@c This is part of the GNU Guile Reference Manual.
@c Copyright (C)  1996, 1997, 2000, 2001, 2002, 2003, 2004
@c   Free Software Foundation, Inc.
@c See the file guile.texi for copying conditions.

@page
@node Concept Index
@unnumbered Concept Index

This index contains concepts, keywords and non-Schemey names for several
features, to make it easier to locate the desired sections.

@printindex cp


@page
@node Procedure Index
@unnumbered Procedure Index

@c FIXME::martin: Review me!

This is an alphabetical list of all the procedures and macros in Guile.

When looking for a particular procedure, please look under its Scheme
name as well as under its C name.  The C name can be constructed from
the Scheme names by a simple transformation described in the section
@xref{API Overview}.

@printindex fn


@page
@node Variable Index
@unnumbered Variable Index

@c FIXME::martin: Review me!

This is an alphabetical list of all the important variables and
constants in Guile.

When looking for a particular variable or constant, please look under
its Scheme name as well as under its C name.  The C name can be
constructed from the Scheme names by a simple transformation described
in the section @xref{API Overview}.

@printindex vr


@page
@node Type Index
@unnumbered Type Index

This is an alphabetical list of all the important data types defined in
the Guile Programmers Manual.

@printindex tp

