
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : kbd-text.scm
;; DESCRIPTION : setup key combinations for frequently used commands
;; COPYRIGHT   : (C) 1999  Joris van der Hoeven
;;
;; This software falls under the GNU general public license and comes WITHOUT
;; ANY WARRANTY WHATSOEVER. See the file $TEXMACS_PATH/LICENSE for details.
;; If you don't have this file, write to the Free Software Foundation, Inc.,
;; 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (keyboard kbd-text)
  (:use (texmacs edit edit-text)))

(kbd-map in-text?
  ("text" "" "Insert structural markup")
  ("text:symbol" "" "Insert a TeXmacs symbol")

  ("$" (if (inside? "hybrid") (insert-string "$") (make-with "mode" "math")))
  ("text $" (make 'equation*) (temp-proof-fix))
  ("text &" (make 'eqnarray*) (temp-proof-fix))
  ("text *" (toggle-section-number))

  ("text a" (make 'abbr))
  ("text d" (make-tmlist 'description))
  ("text e" (make-tmlist 'enumerate))
  ("text i" (make-tmlist 'itemize))
  ("text m" (make 'em))
  ("text n" (make 'name))
  ("text p" (make 'samp))
  ("text s" (make 'strong))
  ("text v" (make 'verbatim))
  ("text ;" (make-item))
  ("text 0" (make-section 'chapter))
  ("text 1" (make-section 'section))
  ("text 2" (make-section 'subsection))
  ("text 3" (make-section 'subsubsection))
  ("text 4" (make-section 'paragraph))
  ("text 5" (make-section 'subparagraph))

  ("F5" (make 'em))
  ("F6" (make 'strong))
  ("F7" (make 'verbatim))
  ("F8" (make 'samp))
  ("S-F6" (make 'name))

  ("font ^" (make-script #t #f))
  ("font hat" (make-script #t #f))
  ("font _" (make-script #t #t))
  ("font s" (make-with "font family" "ss"))
  ("font t" (make-with "font family" "tt"))
  ("font b" (make-with "font series" "bold"))
  ("font m" (make-with "font series" "medium"))
  ("font r" (make-with "font shape" "right"))
  ("font i" (make-with "font shape" "italic"))
  ("font l" (make-with "font shape" "slanted"))
  ("font o" (make 'overline))
  ("font p" (make-with "font shape" "small-caps"))
  ("font u" (make 'underline))

  ("<" "<less>")
  (">" "<gtr>")
  (", ," "")
  ("sz" "ˇ")
  ("- - -" (make 'emdash))
  ;;("- -" "")
  ;;("' '" "")
  ;;("` `" "")

  ("text:symbol s" "ˇ")
  ("text:symbol S" "ﬂ")
  ("text:symbol a" "Ê")
  ("text:symbol a e" "Ê")
  ("text:symbol o" "¯")
  ("text:symbol o e" "˜")
  ("text:symbol A" "∆")
  ("text:symbol A E" "∆")
  ("text:symbol O" "ÿ")
  ("text:symbol O E" "◊")
  ("text:symbol !" "Ω")
  ("text:symbol ?" "æ")
  ("text:symbol p" "ü")
  ("text:symbol P" "ø")

  ("accent:tilde" "~")
  ("accent:tilde space" "~")
  ("accent:tilde A" "√")
  ("accent:tilde N" "—")
  ("accent:tilde O" "’")
  ("accent:tilde a" "„")
  ("accent:tilde n" "Ò")
  ("accent:tilde o" "ı")

  ("accent:hat" "^")
  ("accent:hat space" "^")
  ("accent:hat A" "¬")
  ("accent:hat E" " ")
  ("accent:hat I" "Œ")
  ("accent:hat O" "‘")
  ("accent:hat U" "€")
  ("accent:hat a" "‚")
  ("accent:hat e" "Í")
  ("accent:hat i" "Ó")
  ("accent:hat o" "Ù")
  ("accent:hat u" "˚")
  ("accent:deadhat" "^")
  ("accent:deadhat space" "^")
  ("accent:deadhat A" "¬")
  ("accent:deadhat E" " ")
  ("accent:deadhat I" "Œ")
  ("accent:deadhat O" "‘")
  ("accent:deadhat U" "€")
  ("accent:deadhat a" "‚")
  ("accent:deadhat e" "Í")
  ("accent:deadhat i" "Ó")
  ("accent:deadhat o" "Ù")
  ("accent:deadhat u" "˚")

  ("accent:umlaut" "")
  ("accent:umlaut space" "")
  ("accent:umlaut A" "ƒ")
  ("accent:umlaut E" "À")
  ("accent:umlaut I" "œ")
  ("accent:umlaut O" "÷")
  ("accent:umlaut U" "‹")
  ("accent:umlaut Y" "ò")
  ("accent:umlaut a" "‰")
  ("accent:umlaut e" "Î")
  ("accent:umlaut i" "Ô")
  ("accent:umlaut o" "ˆ")
  ("accent:umlaut u" "¸")
  ("accent:umlaut y" "∏")

  ("accent:acute" "'")
  ("accent:acute space" "'")
  ("accent:acute A" "¡")
  ("accent:acute C" "Ç")
  ("accent:acute E" "…")
  ("accent:acute I" "Õ")
  ("accent:acute L" "à")
  ("accent:acute N" "å")
  ("accent:acute O" "”")
  ("accent:acute R" "è")
  ("accent:acute S" "ë")
  ("accent:acute U" "⁄")
  ("accent:acute Y" "›")
  ("accent:acute Z" "ô")
  ("accent:acute a" "·")
  ("accent:acute c" "¢")
  ("accent:acute e" "È")
  ("accent:acute i" "Ì")
  ("accent:acute l" "®")
  ("accent:acute n" "¨")
  ("accent:acute o" "Û")
  ("accent:acute r" "Ø")
  ("accent:acute s" "±")
  ("accent:acute u" "˙")
  ("accent:acute y" "˝")
  ("accent:acute z" "π")

  ("accent:grave" "`")
  ("accent:grave space" "`")
  ("accent:grave A" "¿")
  ("accent:grave E" "»")
  ("accent:grave I" "Ã")
  ("accent:grave O" "“")
  ("accent:grave U" "Ÿ")
  ("accent:grave a" "‡")
  ("accent:grave e" "Ë")
  ("accent:grave i" "Ï")
  ("accent:grave o" "Ú")
  ("accent:grave u" "˘")

  ("accent:cedilla" "")
  ("accent:cedilla space" "")
  ("accent:cedilla C" "«")
  ("accent:cedilla S" "ì")
  ("accent:cedilla T" "ï")
  ("accent:cedilla c" "Á")
  ("accent:cedilla s" "≥")
  ("accent:cedilla t" "µ")

  ("accent:breve" "")
  ("accent:breve space" "")
  ("accent:breve A" "Ä")
  ("accent:breve G" "á")
  ("accent:breve a" "†")
  ("accent:breve g" "ß")

  ("accent:check" "")
  ("accent:check space" "")
  ("accent:check C" "É")
  ("accent:check D" "Ñ")
  ("accent:check E" "Ö")
  ("accent:check N" "å")
  ("accent:check R" "ê")
  ("accent:check S" "í")
  ("accent:check T" "î")
  ("accent:check U" "ó")
  ("accent:check Z" "ö")
  ("accent:check c" "£")
  ("accent:check d" "§")
  ("accent:check e" "•")
  ("accent:check n" "¨")
  ("accent:check r" "∞")
  ("accent:check s" "≤")
  ("accent:check t" "¥")
  ("accent:check u" "∑")
  ("accent:check z" "∫")

  ("accent:doubleacute" "")
  ("accent:doubleacute space" "")
  ("accent:doubleacute O" "é")
  ("accent:doubleacute U" "ñ")
  ("accent:doubleacute o" "Æ")
  ("accent:doubleacute u" "∂")

  ("accent:abovering" "")
  ("accent:abovering space" "")
  ("accent:abovering A" "≈")
  ("accent:abovering U" "ó")
  ("accent:abovering a" "Â")
  ("accent:abovering u" "∑")

  ("accent:abovedot" "
")
  ("accent:abovedot space" "
")
  ("accent:abovedot Z" "õ")
  ("accent:abovedot I" "ù")
  ("accent:abovedot z" "ª")

  ("accent:ogonek" "")
  ("accent:ogonek space" "")
  ("accent:ogonek a" "°")
  ("accent:ogonek A" "Å")
  ("accent:ogonek e" "¶")
  ("accent:ogonek E" "Ü")

  ("exclamdown" "Ω")
  ("cent" (make 'cent))
  ("sterling" "ø")
  ("currency" (make 'currency))
  ("yen" (make 'yen))
  ("section" "ü")
  ("copyright" (make 'copyright))
  ("copyright var" (make 'copyleft))
  ("guillemotleft" "")
  ("registered" (make 'registered))
  ("degree" (make 'degreesign))
  ("twosuperior" (make 'twosuperior))
  ("threesuperior" (make 'threesuperior))
  ("mu" (make 'mu))
  ("paragraph" (make 'paragraphsign))
  ("onesuperior" (make 'onesuperior))
  ("guillemotright" "")
  ("onequarter" (make 'onequarter))
  ("onehalf" (make 'onehalf))
  ("threequarters" (make 'threequarters))
  ("questiondown" "æ")
  ("euro" (make 'euro)))

(kbd-map like-old-text?
  ("cmd I" (make-tmlist 'itemize))
  ("cmd E" (make-tmlist 'enumerate))
  ("cmd D" (make-tmlist 'description))
  ("cmd N" (make-item))
  ("cmd S" (make-session "scheme")))

(kbd-map in-french?
  ("<" "<less>")
  (">" "<gtr>")
  ("< var" "")
  ("> var" "")
  ("< <" "")
  ("> >" ""))

(kbd-map in-german?
  ("ﬂ" "ˇ")
  ("ˇ" "∏")
  ("<" "<less>")
  (">" "<gtr>")
  ("< var" "")
  ("> var" "")
  ("< <" "")
  ("> >" ""))

(kbd-map in-hungarian?
  ("text:symbol O" "é")
  ("text:symbol U" "ñ")
  ("text:symbol o" "Æ")
  ("text:symbol u" "∂")
  ("<" "<less>")
  (">" "<gtr>")
  ("< <" "")
  ("> >" ""))

(kbd-map in-spanish?
  ("°" "Ω")
  ("ø" "æ")
  ("! var" "Ω")
  ("? var" "æ")
  ("! `" "Ω")
  ("? `" "æ")
  ("! accent:grave" "Ω")
  ("? accent:grave" "æ"))

(kbd-map in-polish?
  ("text:symbol a" "°")
  ("text:symbol A" "Å")
  ("text:symbol c" "¢")
  ("text:symbol C" "Ç")
  ("text:symbol e" "¶")
  ("text:symbol E" "Ü")
  ("text:symbol l" "™")
  ("text:symbol L" "ä")
  ("text:symbol n" "´")
  ("text:symbol N" "ã")
  ("text:symbol o" "Û")
  ("text:symbol O" "”")
  ("text:symbol s" "±")
  ("text:symbol S" "ë")
  ("text:symbol x" "π")
  ("text:symbol X" "ô")
  ("text:symbol z" "ª")
  ("text:symbol Z" "õ")
  ("text:symbol z var" "π")
  ("text:symbol Z var" "ô"))

(kbd-map in-cyrillic?
  ("modeswitch" (make-with "language" "english") (make-with "font" "roman")))
