((Al\ Bayan Bold) (AlBayanBold.ttf))
((Al\ Bayan Normal) (AlBayan.ttf))
((American\ Typewriter Bold) (AmericanTypewriter.ttc))
((American\ Typewriter Normal) (AmericanTypewriter.ttc))
((Andale\ Mono Normal) (Andale\ Mono.ttf))
((Apple\ Braille Normal) (Apple\ Braille.ttf))
((Apple\ Chancery Bold\ Italic) (Apple\ Chancery.ttf))
((Apple\ LiGothic Bold) (Apple\ LiGothic\ Medium.ttf))
((Apple\ LiSung Normal) (Apple\ LiSung\ Light.ttf))
((Apple\ Symbols Normal) (Apple\ Symbols.ttf))
((AppleGothic Normal) (AppleGothic.ttf))
((AppleMyungjo Normal) (AppleMyungjo.ttf))
((Arial Bold) (Arial\ Bold.ttf))
((Arial Bold\ Italic) (Arial\ Bold\ Italic.ttf))
((Arial Italic) (Arial\ Italic.ttf))
((Arial\ Black Bold) (Arial\ Black.ttf))
((Arial\ Hebrew Bold) (ArialHBBold.ttf))
((Arial\ Hebrew Normal) (ArialHB.ttf))
((Arial\ Narrow Bold) (Arial\ Narrow\ Bold.ttf))
((Arial\ Narrow Bold\ Italic) (Arial\ Narrow\ Bold\ Italic.ttf))
((Arial\ Narrow Italic) (Arial\ Narrow\ Italic.ttf))
((Arial\ Narrow Normal) (Arial\ Narrow.ttf))
((Arial\ Rounded\ MT\ Bold Bold) (Arial\ Rounded\ Bold.ttf))
((Arial\ Unicode\ MS Normal) (Arial\ Unicode.ttf))
((Ayuthaya Normal) (Ayuthaya.ttf))
((Baghdad Normal) (Baghdad.ttf))
((Baskerville Bold) (Baskerville.ttc))
((Baskerville Bold\ Italic) (Baskerville.ttc))
((Baskerville Italic) (Baskerville.ttc))
((Baskerville Normal) (Baskerville.ttc))
((BiauKai Normal) (BiauKai.ttf))
((Big\ Caslon Bold) (BigCaslon.ttf))
((Brush\ Script\ MT Italic) (Brush\ Script.ttf))
((CMU\ Bright Bold) (cmunbbx.otf))
((CMU\ Bright Bold\ Italic) (cmunbxo.otf))
((CMU\ Bright Italic) (cmunbso.otf))
((CMU\ Bright Normal) (cmunbmr.otf))
((CMU\ Classical\ Serif Bold\ Italic) (cmunci.otf))
((CMU\ Concrete Bold) (cmunobx.otf))
((CMU\ Concrete Bold\ Italic) (cmunobi.otf))
((CMU\ Concrete Italic) (cmunoti.otf))
((CMU\ Concrete Normal) (cmunorm.otf))
((CMU\ Sans\ Serif Bold) (cmunso.otf))
((CMU\ Sans\ Serif Bold\ Italic) (cmunsx.otf))
((CMU\ Sans\ Serif Italic) (cmunsi.otf))
((CMU\ Sans\ Serif Normal) (cmunss.otf))
((CMU\ Sans\ Serif\ Demi\ Condensed Bold) (cmunssdc.otf))
((CMU\ Serif Bold) (cmunbx.otf))
((CMU\ Serif Bold\ Italic) (cmunbi.otf))
((CMU\ Serif Italic) (cmunti.otf))
((CMU\ Serif Normal) (cmunrm.otf))
((CMU\ Serif\ Extra Bold) (cmunbl.otf))
((CMU\ Serif\ Extra Bold\ Italic) (cmunsl.otf))
((CMU\ Serif\ Upright\ Italic Bold) (cmunui.otf))
((CMU\ Typewriter\ Text Bold) (cmuntb.otf))
((CMU\ Typewriter\ Text Bold\ Italic) (cmunbto.otf))
((CMU\ Typewriter\ Text Italic) (cmunit.otf))
((CMU\ Typewriter\ Text Normal) (cmuntt.otf))
((CMU\ Typewriter\ Text\ Variable\ Width Bold) (cmunvt.otf))
((CMU\ Typewriter\ Text\ Variable\ Width Bold\ Italic) (cmunvi.otf))
((Chalkboard Bold) (Chalkboard.ttc))
((Chalkboard Normal) (Chalkboard.ttc))
((Chalkduster Normal) (Chalkduster.ttf))
((Cochin Bold) (Cochin.ttc))
((Cochin Bold\ Italic) (Cochin.ttc))
((Comic\ Sans\ MS Bold) (Comic\ Sans\ MS\ Bold.ttf))
((Comic\ Sans\ MS Normal) (Comic\ Sans\ MS.ttf))
((Copperplate Bold) (Copperplate.ttc))
((Copperplate Normal) (Copperplate.ttc))
((Corsiva\ Hebrew Bold) (CorsivaBold.ttf))
((Corsiva\ Hebrew Bold\ Italic) (Corsiva.ttf))
((Corsiva\ Hebrew Italic) (CorsivaBold.ttf))
((Corsiva\ Hebrew Normal) (Corsiva.ttf))
((Courier\ New Bold) (Courier\ New\ Bold.ttf))
((Courier\ New Bold\ Italic) (Courier\ New\ Bold\ Italic.ttf))
((Courier\ New Italic) (Courier\ New\ Italic.ttf))
((Courier\ New Normal) (Courier\ New.ttf))
((DecoType\ Naskh Normal) (DecoTypeNaskh.ttf))
((Devanagari\ MT Bold) (DevanagariMTBold.ttf))
((Devanagari\ MT Normal) (DevanagariMT.ttf))
((Didot Bold) (Didot.ttc))
((Didot Italic) (Didot.ttc))
((Didot Normal) (Didot.ttc))
((Euphemia\ UCAS Bold) (EuphemiaCASBold.ttf))
((Euphemia\ UCAS Italic) (EuphemiaCASItalic.ttf))
((Euphemia\ UCAS Normal) (EuphemiaCASRegular.ttf))
((Futura Bold) (Futura.ttc))
((Futura Bold\ Italic) (Futura.ttc))
((GB18030\ Bitmap Normal) (NISC18030.ttf))
((Geeza\ Pro Bold) (Geeza\ Pro\ Bold.ttf))
((Geeza\ Pro Normal) (Geeza\ Pro.ttf))
((Georgia Bold) (Georgia\ Bold.ttf))
((Georgia Bold\ Italic) (Georgia\ Bold\ Italic.ttf))
((Georgia Italic) (Georgia\ Italic.ttf))
((Georgia Normal) (Georgia.ttf))
((Gill\ Sans Bold) (GillSans.ttc))
((Gill\ Sans Bold\ Italic) (GillSans.ttc))
((Gill\ Sans Italic) (GillSans.ttc))
((Gill\ Sans Normal) (GillSans.ttc))
((Gujarati\ MT Bold) (GujaratiMTBold.ttf))
((Gujarati\ MT Normal) (GujaratiMT.ttf))
((GungSeo Normal) (Gungseouche.ttf))
((Gurmukhi\ MT Bold) (Gurmukhi.ttf))
((HeadLineA Normal) (HeadlineA.ttf))
((Hei Normal) (Hei.ttf))
((Heiti\ SC Bold) (STHeiti\ Medium.ttc STHeiti\ Light.ttc))
((Heiti\ SC Normal) (STHeiti\ Medium.ttc STHeiti\ Light.ttc))
((Heiti\ TC Bold) (STHeiti\ Medium.ttc STHeiti\ Light.ttc))
((Heiti\ TC Normal) (STHeiti\ Medium.ttc STHeiti\ Light.ttc))
((Herculanum Normal) (Herculanum.ttf))
((Hiragino\ Sans\ GB Bold) (Hiragino\ Sans\ GB\ W3.otf Hiragino\ Sans\ GB\ W6.otf))
((Hiragino\ Sans\ GB Normal) (Hiragino\ Sans\ GB\ W3.otf Hiragino\ Sans\ GB\ W6.otf))
((Hoefler\ Text Bold) (Hoefler\ Text\ Ornaments.ttf Hoefler\ Text.ttc))
((Hoefler\ Text Bold\ Italic) (Hoefler\ Text\ Ornaments.ttf Hoefler\ Text.ttc))
((Hoefler\ Text Italic) (Hoefler\ Text\ Ornaments.ttf))
((Hoefler\ Text Normal) (Hoefler\ Text.ttc))
((Impact Normal) (Impact.ttf))
((InaiMathi Normal) (InaiMathi.ttf))
((Kai Normal) (Kai.ttf))
((Kailasa Normal) (Kailasa.ttf))
((Kokonor Normal) (Kokonor.ttf))
((Krungthep Normal) (Krungthep.ttf))
((KufiStandardGK Normal) (KufiStandardGK.ttf))
((Latin\ Modern\ Math Normal) (LMMATH-v0903.otf))
((Latin\ Modern\ Roman Normal) (lmroman10-regular.otf))
((Lucida\ Grande Bold) (LucidaGrande.ttc))
((Lucida\ Grande Normal) (LucidaGrande.ttc))
((Marker\ Felt Bold) (MarkerFelt.ttc))
((Marker\ Felt Normal) (MarkerFelt.ttc))
((Menlo Bold) (Menlo.ttc))
((Menlo Bold\ Italic) (Menlo.ttc))
((Menlo Italic) (Menlo.ttc))
((Menlo Normal) (Menlo.ttc))
((Microsoft\ Sans\ Serif Normal) (Microsoft\ Sans\ Serif.ttf))
((Mshtakan Bold) (MshtakanBold.ttf))
((Mshtakan Bold\ Italic) (MshtakanBoldOblique.ttf))
((Mshtakan Italic) (MshtakanOblique.ttf))
((Mshtakan Normal) (MshtakanRegular.ttf))
((Nadeem Normal) (Nadeem.ttf))
((New\ Peninim\ MT Bold) (NewPeninimMTBold.ttf))
((New\ Peninim\ MT Bold\ Italic) (NewPeninimMTBoldInclined.ttf))
((New\ Peninim\ MT Italic) (NewPeninimMTInclined.ttf))
((New\ Peninim\ MT Normal) (NewPeninimMT.ttf))
((Optima Bold) (Optima.ttc))
((Optima Bold\ Italic) (Optima.ttc))
((Optima Italic) (Optima.ttc))
((Optima Normal) (Optima.ttc))
((Osaka Normal) (Osaka.ttf))
((PCMyungjo Normal) (PCmyoungjo.ttf))
((Papyrus Normal) (Papyrus.ttc))
((PilGi Normal) (Pilgiche.ttf))
((Plantagenet\ Cherokee Normal) (PlantagenetCherokee.ttf))
((Raanana Bold) (RaananaBold.ttf))
((Raanana Normal) (Raanana.ttf))
((STIXGeneral Bold) (STIXGeneralBol.ttf))
((STIXGeneral Bold\ Italic) (STIXGeneralBolIta.ttf))
((STIXGeneral Italic) (STIXGeneralItalic.ttf))
((STIXGeneral Normal) (STIXGeneral.ttf))
((STIXIntegrals Bold) (STIXIntDisBol.ttf STIXIntSmaBol.ttf STIXIntUpBol.ttf STIXIntUpDisBol.ttf STIXIntUpSmaBol.ttf))
((STIXIntegrals Normal) (STIXIntDis.ttf STIXIntSma.ttf STIXIntUp.ttf STIXIntUpDis.ttf STIXIntUpSma.ttf))
((STIXNonUnicode Bold) (STIXNonUniBol.ttf))
((STIXNonUnicode Bold\ Italic) (STIXNonUniBolIta.ttf))
((STIXNonUnicode Italic) (STIXNonUniIta.ttf))
((STIXNonUnicode Normal) (STIXNonUni.ttf))
((STIXSize1 Bold) (STIXSiz1SymBol.ttf))
((STIXSize1 Normal) (STIXSiz1Sym.ttf))
((STIXSize2 Bold) (STIXSiz2SymBol.ttf))
((STIXSize2 Normal) (STIXSiz2Sym.ttf))
((STIXSize3 Bold) (STIXSiz3SymBol.ttf))
((STIXSize3 Normal) (STIXSiz3Sym.ttf))
((STIXSize4 Bold) (STIXSiz4SymBol.ttf))
((STIXSize4 Normal) (STIXSiz4Sym.ttf))
((STIXSize5 Normal) (STIXSiz5Sym.ttf))
((STIXVariants Bold) (STIXVarBol.ttf))
((STIXVariants Normal) (STIXVar.ttf))
((Sathu Normal) (Sathu.ttf))
((Silom Normal) (Silom.ttf))
((Skia Normal) (Skia.ttf))
((Symbol Normal) (Symbol.ttf))
((Tahoma Bold) (Tahoma\ Bold.ttf))
((Tahoma Normal) (Tahoma.ttf))
((Thonburi Bold) (ThonburiBold.ttf))
((Thonburi Normal) (Thonburi.ttf))
((Times\ New\ Roman Bold) (Times\ New\ Roman\ Bold.ttf))
((Times\ New\ Roman Bold\ Italic) (Times\ New\ Roman\ Bold\ Italic.ttf))
((Times\ New\ Roman Italic) (Times\ New\ Roman\ Italic.ttf))
((Times\ New\ Roman Normal) (Times\ New\ Roman.ttf))
((Trebuchet\ MS Bold) (Trebuchet\ MS\ Bold.ttf))
((Trebuchet\ MS Bold\ Italic) (Trebuchet\ MS\ Bold\ Italic.ttf))
((Trebuchet\ MS Italic) (Trebuchet\ MS\ Italic.ttf))
((Trebuchet\ MS Normal) (Trebuchet\ MS.ttf))
((Verdana Bold) (Verdana\ Bold.ttf))
((Verdana Bold\ Italic) (Verdana\ Bold\ Italic.ttf))
((Verdana Italic) (Verdana\ Italic.ttf))
((Verdana Normal) (Verdana.ttf))
((Webdings Normal) (Webdings.ttf))
((Wingdings Normal) (Wingdings.ttf))
((Wingdings\ 2 Normal) (Wingdings\ 2.ttf))
((Wingdings\ 3 Normal) (Wingdings\ 3.ttf))
((Zapf\ Dingbats Normal) (ZapfDingbats.ttf))
((Zapfino Italic) (Zapfino.ttf))
