((Al\ Bayan Bold) (AlBayanBold.ttf))
((Al\ Bayan Normal) (AlBayan.ttf))
((Andale\ Mono Normal) (Andale\ Mono.ttf))
((Apple\ Chancery Bold\ Italic) (Apple\ Chancery.ttf))
((Apple\ LiGothic Bold) (Apple\ LiGothic\ Medium.ttf))
((Apple\ LiSung Normal) (Apple\ LiSung\ Light.ttf))
((AppleMyungjo Normal) (AppleMyungjo.ttf))
((Arial Bold) (Arial\ Bold.ttf))
((Arial Bold\ Italic) (Arial\ Bold\ Italic.ttf))
((Arial Italic) (Arial\ Italic.ttf))
((Arial\ Black Bold) (Arial\ Black.ttf))
((Arial\ Hebrew Bold) (ArialHBBold.ttf))
((Arial\ Hebrew Normal) (ArialHB.ttf))
((Arial\ Narrow Bold) (Arial\ Narrow\ Bold.ttf))
((Arial\ Narrow Bold\ Italic) (Arial\ Narrow\ Bold\ Italic.ttf))
((Arial\ Narrow Italic) (Arial\ Narrow\ Italic.ttf))
((Arial\ Narrow Normal) (Arial\ Narrow.ttf))
((Arial\ Rounded\ MT\ Bold Bold) (Arial\ Rounded\ Bold.ttf))
((Arial\ Unicode\ MS Normal) (Arial\ Unicode.ttf))
((Ayuthaya Normal) (Ayuthaya.ttf))
((Baghdad Normal) (Baghdad.ttf))
((BiauKai Normal) (BiauKai.ttf))
((Big\ Caslon Bold) (BigCaslon.ttf))
((Brush\ Script\ MT Italic) (Brush\ Script.ttf))
((Chalkduster Normal) (Chalkduster.ttf))
((Comic\ Sans\ MS Bold) (Comic\ Sans\ MS\ Bold.ttf))
((Comic\ Sans\ MS Normal) (Comic\ Sans\ MS.ttf))
((Corsiva\ Hebrew Bold) (CorsivaBold.ttf))
((Corsiva\ Hebrew Bold\ Italic) (Corsiva.ttf))
((Corsiva\ Hebrew Italic) (CorsivaBold.ttf))
((Corsiva\ Hebrew Normal) (Corsiva.ttf))
((Courier\ New Bold) (Courier\ New\ Bold.ttf))
((Courier\ New Bold\ Italic) (Courier\ New\ Bold\ Italic.ttf))
((Courier\ New Italic) (Courier\ New\ Italic.ttf))
((Courier\ New Normal) (Courier\ New.ttf))
((DecoType\ Naskh Normal) (DecoTypeNaskh.ttf))
((Devanagari\ MT Bold) (DevanagariMTBold.ttf))
((Devanagari\ MT Normal) (DevanagariMT.ttf))
((Euphemia\ UCAS Bold) (EuphemiaCASBold.ttf))
((Euphemia\ UCAS Italic) (EuphemiaCASItalic.ttf))
((Euphemia\ UCAS Normal) (EuphemiaCASRegular.ttf))
((GB18030\ Bitmap Normal) (NISC18030.ttf))
((Georgia Bold) (Georgia\ Bold.ttf))
((Georgia Bold\ Italic) (Georgia\ Bold\ Italic.ttf))
((Georgia Italic) (Georgia\ Italic.ttf))
((Georgia Normal) (Georgia.ttf))
((Gujarati\ MT Bold) (GujaratiMTBold.ttf))
((Gujarati\ MT Normal) (GujaratiMT.ttf))
((GungSeo Normal) (Gungseouche.ttf))
((Gurmukhi\ MT Bold) (Gurmukhi.ttf))
((HeadLineA Normal) (HeadlineA.ttf))
((Hei Normal) (Hei.ttf))
((Herculanum Normal) (Herculanum.ttf))
((Hoefler\ Text Bold) (Hoefler\ Text\ Ornaments.ttf))
((Hoefler\ Text Bold\ Italic) (Hoefler\ Text\ Ornaments.ttf))
((Hoefler\ Text Italic) (Hoefler\ Text\ Ornaments.ttf))
((Hoefler\ Text Normal) (Hoefler\ Text\ Ornaments.ttf))
((Impact Normal) (Impact.ttf))
((InaiMathi Normal) (InaiMathi.ttf))
((Kai Normal) (Kai.ttf))
((Kailasa Normal) (Kailasa.ttf))
((Kokonor Normal) (Kokonor.ttf))
((Krungthep Normal) (Krungthep.ttf))
((KufiStandardGK Normal) (KufiStandardGK.ttf))
((Microsoft\ Sans\ Serif Normal) (Microsoft\ Sans\ Serif.ttf))
((Mshtakan Bold) (MshtakanBold.ttf))
((Mshtakan Bold\ Italic) (MshtakanBoldOblique.ttf))
((Mshtakan Italic) (MshtakanOblique.ttf))
((Mshtakan Normal) (MshtakanRegular.ttf))
((Nadeem Normal) (Nadeem.ttf))
((New\ Peninim\ MT Bold) (NewPeninimMTBold.ttf))
((New\ Peninim\ MT Bold\ Italic) (NewPeninimMTBoldInclined.ttf))
((New\ Peninim\ MT Italic) (NewPeninimMTInclined.ttf))
((New\ Peninim\ MT Normal) (NewPeninimMT.ttf))
((Osaka Normal) (Osaka.ttf))
((PCMyungjo Normal) (PCmyoungjo.ttf))
((PilGi Normal) (Pilgiche.ttf))
((Plantagenet\ Cherokee Normal) (PlantagenetCherokee.ttf))
((Raanana Bold) (RaananaBold.ttf))
((Raanana Normal) (Raanana.ttf))
((Sathu Normal) (Sathu.ttf))
((Silom Normal) (Silom.ttf))
((Skia Normal) (Skia.ttf))
((Tahoma Bold) (Tahoma\ Bold.ttf))
((Tahoma Normal) (Tahoma.ttf))
((Times\ New\ Roman Bold) (Times\ New\ Roman\ Bold.ttf))
((Times\ New\ Roman Bold\ Italic) (Times\ New\ Roman\ Bold\ Italic.ttf))
((Times\ New\ Roman Italic) (Times\ New\ Roman\ Italic.ttf))
((Times\ New\ Roman Normal) (Times\ New\ Roman.ttf))
((Trebuchet\ MS Bold) (Trebuchet\ MS\ Bold.ttf))
((Trebuchet\ MS Bold\ Italic) (Trebuchet\ MS\ Bold\ Italic.ttf))
((Trebuchet\ MS Italic) (Trebuchet\ MS\ Italic.ttf))
((Trebuchet\ MS Normal) (Trebuchet\ MS.ttf))
((Verdana Bold) (Verdana\ Bold.ttf))
((Verdana Bold\ Italic) (Verdana\ Bold\ Italic.ttf))
((Verdana Italic) (Verdana\ Italic.ttf))
((Verdana Normal) (Verdana.ttf))
((Webdings Normal) (Webdings.ttf))
((Wingdings Normal) (Wingdings.ttf))
((Wingdings\ 2 Normal) (Wingdings\ 2.ttf))
((Wingdings\ 3 Normal) (Wingdings\ 3.ttf))
((Zapfino Italic) (Zapfino.ttf))
