("case-insensitive search" "hoofdlettergevoelig zoeken")
("categories" "categorieën")
("category" "categorie")
("cc" "cc")
("cell properties" "celeigenschappen")
("center baseline" "centrale basislijn")
("chalk" "krijt")
("change default unit" "standaardeenheid wijzigen")
("change passphrase" "wachtwoordzin wijzigen")
("change permissions" "machtigingen wijzigen")
("change step-size" "stapgrootte wijzigen")
("change tags" "tags wijzigen")
("change the TeXmacs preferences" "de TeXmacs-voorkeuren wijzigen")
("change the style of mathematical formulas" "verander de stijl van wiskundige formules")
("change wallet passphrase" "wachtwoordzin voor portemonnee wijzigen")
("character contraction" "tekencontractie")
("character encoding" "tekencodering")
("character expansion" "karakteruitbreiding")
("check exported Pdf files for correctness" "geëxporteerde PDF-bestanden op juistheid controleren")
("check for automatic updates" "controleren op automatische updates")
("check for updates" "controleren op updates")
("checkable field" "controleerbaar veld")
("choose background" "achtergrond kiezen")
("choose color" "kleur kiezen")
("cipher algorithm for passphrase encryption" "coderingsalgoritme voor wachtwoordzincodering")
("circle" "cirkel")
("classification" "classificatie")
("clean slate" "schone lei")
("clear all fields" "alle velden wissen")
("clear local information" "duidelijke lokale informatie")
("clear menu" "menu wissen")
("clear undo history" "geschiedenis ongedaan maken wissen")
("click Ok button twice to discard this warning" "klik tweemaal op OK om deze waarschuwing te negeren")
("clip" "clip")
("clipboard image format" "klembord beeldformaat")
("close animation tool" "animatietool sluiten")
("close program" "programma afsluiten")
("close replace tool" "hulpmiddel voor vervangen vervangen")
("close search tool" "zoekhulpmiddel sluiten")
("close spell tool" "close spell tool")
("close translations to rebuild" "vertalingen sluiten om opnieuw te bouwen")
("closed bezier" "gesloten bezier")
("closed curve" "gesloten curve")
("closed smooth" "gesloten glad")
("closed spline" "gesloten spline")
("cluster by affiliation" "cluster op basis van aansluiting")
("collect garbage" "Afval verzamelen")
("collected keys" "verzamelde sleutels")
("color of the axes" "kleur van de assen")
("color of the subunits" "kleur van de subeenheden")
("color of the units" "kleur van de eenheden")
("colors" "kleuren")
("column separation" "kolomscheiding")
("commit" "vastleggen")
("commit file" "bestand vastleggen")
("common" "gemeenschappelijk")
("commutative diagram" "commutatief diagram")
("compare" "vergelijken")
("compare with" "vergelijken met")
("complete bibliographic reference" "volledige bibliografische referentie")
("complex actions" "complexe acties")
("compose" "componeren")
("compound" "verbinding")
("compress" "comprimeren")
("compress into toolbar" "comprimeren in werkbalk")
("compressed" "gecomprimeerd")
("conceal" "verbergen")
("configure look and feel" "uiterlijk configureren")
("confirm collected public key deletion" "bevestigde verwijdering van verzamelde openbare sleutel")
("confirm database entry" "bevestig database-invoer")
("confirm entry" "invoer bevestigen")
("confirm public key deletion" "bevestiging van verwijdering van openbare sleutel")
("confirm secret key deletion" "bevestiging geheime sleutel bevestigen")
("confirm selected database entries" "bevestig geselecteerde database-ingangen")
("confirm selected entries" "bevestig geselecteerde invoer")
("confirm wallet destruction" "vernietiging portemonnee bevestigen")
("conservative conversion options" "conservatieve conversie-opties")
("consoles" "consoles")
("constellation" "constellatie")
("context aids" "contexthulpmiddelen")
("contextual hints" "contextuele hints")
("continue" "doorgaan")
("continued fraction" "voortgezette fractie")
("contour" "contour")
("control flow" "besturingsstroom")
("convert" "converteren")
("convertible" "converteerbaar")
("copy new objects to all frames" "nieuwe objecten naar alle frames kopiëren")
("copy new objects to previous frames" "nieuwe objecten naar vorige frames kopiëren")
("copy new objects to subsequent frames" "nieuwe objecten naar volgende frames kopiëren")
("copy to all frames after" "kopiëren naar alle frames na")
("copy to all frames before" "eerder naar alle frames kopiëren")
("copy to all other frames" "kopiëren naar alle andere frames")
("copyright" "auteursrechten")
("cork charset with TeX catcode definition in preamble" "kurk tekenset met TeX catcode definitie in preambule")
("cork with catcodes" "kurk met catcodes")
("correct" "correct")
("correct all" "alles corrigeren")
("correct formula" "juiste formule")
("correct manually" "handmatig corrigeren")
("correct mathematical formulas" "juiste wiskundige formules")
("correction" "correctie")
("count characters" "tekens tellen")
("count lines" "telregels")
("count words" "woorden tellen")
("create link" "link maken")
("create preamble" "preambule maken")
("create remote account" "extern account maken")
("create remote directory" "externe map maken")
("create remote file" "extern bestand maken")
("create subprogram" "subprogramma maken")
("create subsession" "subsessie maken")
("create table macro" "tabelmacro maken")
("creating new account" "nieuw account aanmaken")
("creating technical pictures" "technische afbeeldingen maken")
("crop" "bijsnijden")
("crop marks" "snijtekens")
("cross" "kruis")
("crossed boxes" "gekruiste dozen")
("crossed circles" "gekruiste cirkels")
("current user version" "huidige gebruikersversie")
("current version" "huidige versie")
("cursor" "cursor")
("curve intersections" "kromme kruispunten")
("curve points" "curve-punten")
("customizations" "aanpassingen")
("customizing and extending the user interface" "aanpassen en uitbreiden van de gebruikersinterface")
("cyan" "cyaan")
("data" "data")
("database entry" "database-invoer")
("database tool" "database-tool")
("database toolbar" "database-werkbalk")
("debug" "debug")
("debugging console" "foutopsporingsconsole")
("debugging tool" "hulpprogramma voor foutopsporing")
("decomposed" "ontleed")
("decorated" "gedecoreerd")
("decorated wood" "gedecoreerd hout")
("decorative" "decoratief")
("decrease size" "verkleinen")
("decrypt" "decoderen")
("decrypted" "ontsleuteld")
("decryption" "decodering")
("default size" "standaardgrootte")
("degrade" "degraderen")
("degraded" "aangetast")
("delete documentation cache" "documentatiecache verwijderen")
("delete entries" "vermeldingen verwijderen")
("delete link" "link verwijderen")
("delete selected entries in wallet" "geselecteerde items in portefeuille verwijderen")
("delete user identity" "gebruikersidentiteit verwijderen")
("deleted" "verwijderd")
("describe" "beschrijven")
("describe tag" "tag beschrijven")
("destroy" "vernietigen")
("detach master" "meester loskoppelen")
("determine margins from text width" "marges bepalen uit tekstbreedte")
("developer" "ontwikkelaar")
("developer tool" "ontwikkelaarstool")
("device" "apparaat")
("diamond" "diamant")
("digital" "digitaal")
("dilate" "verwijden")
("direction of progression" "voortgangsrichting")
("direction of translation" "richting van vertaling")
("disable coloring on paper" "kleuren op papier uitschakelen")
("disable encryption" "codering uitschakelen")
("disabled" "uitgeschakeld")
("disappear" "verdwijnen")
("disk" "schijf")
("display style" "weergavestijl")
("displayed formula" "weergegeven formule")
("dissociate joined cells" "dissociëren verbonden cellen")
("distill encapsulated Pdf files" "ingekapselde PDF-bestanden destilleren")
("distort" "vervormen")
("distorted" "vervormd")
("division" "divisie")
("document colors" "documentkleuren")
("document font selector" "documentlettertype-selector")
("document language" "documenttaal")
("document metadata" "document metadata")
("document page format" "documentpagina-indeling")
("document paragraph format" "documentalinea-indeling")
("document source tree preferences" "voorkeuren voor documentbronstructuur")
("document updates run" "documentupdates worden uitgevoerd")
("documents in separate windows" "documenten in afzonderlijke vensters")
("download file or directory" "download bestand of map")
("downwards" "naar beneden")
("dragging" "slepen")
("draw" "gelijkspel")
("draw graphics" "afbeeldingen tekenen")
("draw over" "gelijkspel")
("drop" "drop")
("due to" "vanwege")
("dynamic" "dynamisch")
("eRROR" "eRROR")
("edit animation" "animatie bewerken")
("edit groups of objects" "groepen objecten bewerken")
("edit macro" "macro bewerken")
("edit macros" "macro's bewerken")
("edit object properties" "objecteigenschappen bewerken")
("edit preamble" "preambule bewerken")
("edit source" "bron bewerken")
("edit style" "bewerkstijl")
("edit translations file" "vertaalbestand bewerken")
("education" "onderwijs")
("effect pen" "effectpen")
("eighth" "achtste")
("embold" "embold")
("emboss" "reliëf")
("enable page breaking" "Pagina-einde inschakelen")
("enabled" "ingeschakeld")
("encl" "encl")
("encrypt" "coderen")
("encrypted" "gecodeerd")
("encrypted buffer" "gecodeerde buffer")
("encryption" "codering")
("encryption error" "coderingsfout")
("encryption facilities are not currently available" "versleutelingsfaciliteiten zijn momenteel niet beschikbaar")
("encryption facilities have not been enabled for TeXmacs" "versleutelingsfaciliteiten zijn niet ingeschakeld voor TeXmacs")
("enforce brackets to match" "overeenkomende haakjes afdwingen")
("engrave" "graveren")
("enter graphics" "afbeeldingen invoeren")
("enter graphics mode" "naar grafische modus")
("enter new passphrase for encryption" "voer een nieuwe wachtwoordzin in voor codering")
("enter passphrase for decryption" "wachtwoordzin invoeren voor decodering")
("enter passphrase for identity" "wachtwoordzin invoeren voor identiteit")
("enter title information" "titelinformatie invoeren")
("entry up to date in database" "invoer up-to-date in database")
("enunciation" "uitspraak")
("environment variable" "omgevingsvariabele")
("environments" "omgevingen")
("erode" "eroderen")
("error messages" "foutmeldingen")
("error output" "foutuitvoer")
("error status report" "foutstatusrapport")
("error: bracket does not match" "fout: bracket komt niet overeen")
("error: cyclic or missing chunks detected" "fout: cyclische of ontbrekende stukken gedetecteerd")
("error: file not found" "fout: bestand niet gevonden")
("error: ghostview does not seem to be installed on your system" "fout: ghostview lijkt niet op uw systeem te zijn geïnstalleerd")
("error: one of the alternatives should be filled out" "fout: een van de alternatieven moet worden ingevuld")
("error: only one alternatives should be filled out" "fout: slechts één alternatief moet worden ingevuld")
("error: should fill out name for referencing" "fout: moet naam invullen voor verwijzing")
("error: should fill out required field" "fout: moet verplicht veld invullen")
("escape" "ontsnapping")
("evaluable field" "evalueerbaar veld")
("evaluate above" "hierboven evalueren")
("evaluate all" "evalueer alles")
("evaluate below" "evalueer hieronder")
("evaluate fields" "velden evalueren")
("evaluate fields in order" "velden op volgorde evalueren")
("evaluate script" "script evalueren")
("evaluation" "evaluatie")
("even page" "even pagina")
("even pages" "even pagina's")
("events" "evenementen")
("exact" "exact")
("execution of scripts" "uitvoering van scripts")
("exit graphics" "afbeeldingen afsluiten")
("exit graphics mode" "grafische modus afsluiten")
("exit left" "afslag links")
("exit right" "afslag rechts")
("exit tag on the left" "exit-tag links")
("exit tag on the right" "exit-tag rechts")
("expand TeXmacs macros with no LaTeX equivalents" "TeXmacs-macro's uitbreiden zonder LaTeX-equivalenten")
("expand beamer slides" "expand beamer slides")
("expand inclusions" "insluitsels uitbreiden")
("expanded" "uitgebreid")
("experimental features (to be used with care)" "experimentele functies (voorzichtig te gebruiken)")
("explain" "uitleggen")
("explanatory item" "verklarend item")
("explicit keystroke" "expliciete toetsaanslag")
("explicit margins" "expliciete marges")
("export bibliography" "exportbibliografie")
("export entries in buffer" "exportitems in buffer")
("export file" "exportbestand")
("export mathematical formulas as MathML" "wiskundige formules exporteren als MathML")
("export mathematical formulas as images" "wiskundige formules exporteren als afbeeldingen")
("export selected entries" "exporteer geselecteerde items")
("export selection" "export selectie")
("export selection as image" "selectie exporteren als afbeelding")
("export selections as" "export selecties als")
("export sessions" "exportsessies")
("exported bibliographic entries" "geëxporteerde bibliografische gegevens")
("exported bibliographic references" "geëxporteerde bibliografische referenties")
("extend" "uitbreiden")
("extend table to full paragraph width" "tabel uitbreiden tot volledige alineabreedte")
("extended" "verlengd")
("extensible left arrow" "uitbreidbare linkerpijl")
("extensible right arrow" "uitbreidbare rechterpijl")
("extern" "extern")
("external" "extern")
("extra branch" "extra tak")
("extra interline space" "extra tussenlijnruimte")
("extra name" "extra naam")
("extract" "extract")
("extract style file" "extract stijlbestand")
("extract style package" "pakket met extractstijl")
("fade" "vervagen")
("fade in" "infaden")
("fade out" "vervagen")
("fast" "snel")
("fast decrease" "snelle afname")
("fast environments" "snelle omgevingen")
("fast increase" "snelle toename")
("field reference" "veldreferentie")
("fifth" "vijfde")
("file saved" "bestand opgeslagen")
("fill color" "vulkleur")
("fill out" "invullen")
("filter" "filter")
("find file" "bestand zoeken")
("finished collecting symbols documentation" "documentatie voor het verzamelen van symbolen voltooid")
("first" "eerste")
("first chunk" "eerste stuk")
("first difference" "eerste verschil")
("first error" "eerste fout")
("first field" "eerste veld")
("first occurrence" "eerste keer")
("first similar" "eerste soortgelijke")
("fit" "fit")
("fit to height" "op hoogte passen")
("fit to screen" "passend voor scherm")
("fit to screen width" "passend voor schermbreedte")
("fit to width" "passend voor de breedte")
("five columns" "vijf kolommen")
("fixed" "vast")
("flag is off" "vlag is uit")
("flag is on" "vlag is aan")
("flatten" "plat")
("floating algorithm" "zwevend algoritme")
("floating phantom" "zwevend fantoom")
("focus" "focus")
("focus dependent icons" "focusafhankelijke pictogrammen")
("fold all" "alles vouwen")
("fold all fields" "vouw alle velden")
("fold back" "terug te vouwen")
("follow external links" "volg externe links")
("follow inverse links" "volg omgekeerde links")
("font customization" "lettertypeaanpassing")
("font effects" "lettertype-effecten")
("font selector" "lettertypekiezer")
("for each" "voor elk")
("force reloading of translations" "gedwongen herladen van vertalingen")
("forward" "vooruit")
("four columns" "vier kolommen")
("four dots" "vier punten")
("fourth" "vierde")
("fraktur" "fraktur")
("framed" "ingelijst")
("framed theorems" "ingelijste stellingen")
("from" "van")
("from center" "vanuit het midden")
("front matter" "voorkant")
("full" "volledig")
("full author list" "volledige auteurslijst")
("full screen mode" "volledig scherm")
("gap" "kloof")
("garbage collection" "garbage collection")
("gaussian" "gaussiaans")
("general" "algemeen")
("generate GnuPG key" "Genereer GnuPG-sleutel")
("generated LaTeX document contains no errors" "gegenereerd LaTeX-document bevat geen fouten")
("generated field" "gegenereerd veld")
("geometry" "geometrie")
("get arity" "krijg arity")
("get label" "label krijgen")
("get list with remote versions" "krijg lijst met versies op afstand")
("global log" "globaal logboek")
("global status" "globale status")
("glue multiple spaces" "lijm meerdere spaties")
("glyphs" "glyphs")
("gnaw" "knagen")
("gnawed" "geknaagd")
("gnuPG command" "gnuPG-commando")
("gnuPG decryption error" "gnuPG-decryptiefout")
("gnuPG error: buffer encryption failed" "gnuPG-fout: bufferversleuteling mislukt")
("gnuPG error: cannot find suitable secret key to decrypt" "gnuPG-fout: kan geen geschikte geheime sleutel vinden om te decoderen")
("gnuPG requires name and email to have at least 5 characters" "gnuPG vereist naam en e-mailadres van minimaal 5 tekens")
("go to anchor" "ga voor anker")
("go to anchor or float" "ga voor anker of drijven")
("go to anchor or footnote" "ga naar anker of voetnoot")
("go to first similar tag" "ga naar eerste soortgelijke tag")
("go to float" "gaan zweven")
("go to footnote" "naar voetnoot")
("go to last similar tag" "ga naar laatste soortgelijke tag")
("go to next similar tag" "ga naar volgende soortgelijke tag")
("go to previous similar tag" "ga naar vorige soortgelijke tag")
("go to section" "ga naar sectie")
("grain" "korrel")
("granite" "graniet")
("graphical effects" "grafische effecten")
("graphical interface font scale" "grafische interface lettertypeschaal")
("graphical overlays" "grafische overlays")
("graphical slides and overlays" "grafische dia's en overlays")
("graphics" "grafische weergave")
("graphics geometry" "grafische geometrie")
("graphics grids" "grafische rasters")
("greyed" "grijs")
("grid" "rooster")
("grid curves" "rastercurven")
("grid points" "rasterpunten")
("grid-curve intersections" "raster-kromme kruispunten")
("group of objects" "groep objecten")
("group/ungroup" "groep / degroep")
("group/ungroup objects" "objecten groeperen / degroeperen")
("grouped" "gegroepeerd")
("guarantee transparent source tracking" "garanderen transparante brontracering")
("half wide" "half breed")
("hand drawn" "hand getrokken")
("handwritten" "handgeschreven")
("hangul" "hangul")
("headers" "headers")
("high resolution settings" "hoge resolutie-instellingen")
("history" "geschiedenis")
("homoglyph substitutions" "homoglyph-substituties")
("horizontal collapse distance" "horizontale instortafstand")
("horizontal margins" "horizontale marges")
("hyphenate as" "afbreekstreepje als")
("icon" "pictogram")
("ignore" "negeren")
("impact" "impact")
("import bibliography" "importbibliografie")
("import database entry" "invoer database-invoer")
("import entries in buffer" "invoer in buffer importeren")
("import entry" "invoer bij invoer")
("import file" "importbestand")
("import public keys from buffer" "openbare sleutels importeren uit buffer")
("import selected database entries" "importeer geselecteerde database-ingangen")
("import selected entries" "importeer geselecteerde items")
("import selections as" "selecties importeren als")
("import sessions" "importsessies")
("import sophisticated objects as pictures" "geavanceerde objecten als afbeeldingen importeren")
("imported bibliographic entries" "geïmporteerde bibliografische gegevens")
("inanimated" "geanimeerd")
("inch" "inch")
("incomplete entries found to be filled out" "onvolledige gegevens die zijn ingevuld")
("increase size" "grootte vergroten")
("indent paragraphs" "alinea's inspringen")
("indentation" "inspringen")
("indication" "indicatie")
("initialize" "initialiseren")
("initialize wallet" "portemonnee initialiseren")
("initials" "initialen")
("ink here" "inkt hier")
("ink in" "inkt in")
("ink out" "inkt op")
("inline" "inline")
("inline args" "inline args")
("inline code" "inline code")
("inline content" "inline content")
("inline formula" "inline-formule")
("inner bottom" "binnenbodem")
("inner left" "binnen links")
("inner right" "binnenrecht")
("inner top" "binnentop")
("input command" "invoeropdracht")
("input field" "invoerveld")
("input options" "invoeropties")
("insert a computer program" "een computerprogramma invoegen")
("insert a gap" "voeg een opening in")
("insert a list" "lijst invoegen")
("insert a multiple choice" "meerdere keuzes invoegen")
("insert a negation" "een ontkenning invoegen")
("insert a new entry" "nieuwe invoer invoegen")
("insert a note or a floating object" "een notitie of een zwevend object invoegen")
("insert a prominent piece of text" "een opvallend stuk tekst invoegen")
("insert a question" "vraag invoegen")
("insert a root" "voeg een wortel in")
("insert a script" "script invoegen")
("insert a section block" "een sectieblok invoegen")
("insert a textual operator" "tekstuele operator invoegen")
("insert above" "hierboven invoegen")
("insert abstract" "abstract invoegen")
("insert an answer" "antwoord invoegen")
("insert an enunciation" "een uitspraak invoegen")
("insert annotation" "annotatie invoegen")
("insert arcs" "inzetbogen")
("insert argument after" "argument invoegen na")
("insert argument before" "argument vóór invoegen")
("insert below" "hieronder invoegen")
("insert bibliography" "bibliografie invoegen")
("insert circles" "cirkels invoegen")
("insert closed splines" "gesloten splines invoegen")
("insert copyright and license information" "copyright- en licentie-informatie invoegen")
("insert explanatory item" "verklarend item invoegen")
("insert field above" "veld hierboven invoegen")
("insert field below" "veld hieronder invoegen")
("insert hand drawn curves" "handgetekende curven invoegen")
("insert large delimiters" "grote scheidingstekens invoegen")
("insert last name" "achternaam invoeren")
("insert left" "links invoegen")
("insert lines" "regels invoegen")
("insert missing invisible operators" "voeg ontbrekende onzichtbare operatoren in")
("insert more names" "meer namen invoegen")
("insert multiple paragraphs" "meerdere alinea's invoegen")
("insert overlay after" "overlay invoegen na")
("insert overlay before" "overlay invoegen")
("insert particle" "deeltje invoegen")
("insert plain text" "tekst zonder opmaak")
("insert points" "punten invoegen")
("insert polygons" "polygonen invoegen")
("insert right" "rechts invoegen")
("insert similar above" "invoegen vergelijkbaar hierboven")
("insert similar below" "invoegen vergelijkbaar hieronder")
("insert similar block above" "voeg gelijkaardig blok hierboven in")
("insert similar block below" "invoegen vergelijkbaar blok hieronder")
("insert slide after" "dia invoegen na")
("insert slide before" "dia vóór invoegen")
("insert splines" "splines invoegen")
("insert subscript" "subscript invoegen")
("insert subtable" "subtabel invoegen")
("insert superscript" "superscript invoegen")
("insert symbol documentation" "documentatie voor symbool invoegen")
("insert template" "sjabloon invoegen")
("insert text" "tekst invoegen")
("insert text field above" "tekstveld hierboven invoegen")
("insert text field below" "tekstveld hieronder invoegen")
("insert title after name" "titel na naam invoegen")
("insert user interface related markup" "markeringen voor gebruikersinterface invoegen")
("inserting control points" "controlepunten invoegen")
("inside mathematics" "binnen wiskunde")
("intercharacter compression" "compressie tussen tekens")
("intercharacter stretching" "intercharacter stretching")
("invalid multi-paragraph selection" "ongeldige selectie van meerdere alinea's")
("invalid renaming" "ongeldige hernoemen")
("inverted breve" "geïnverteerde breve")
("invisible ending" "onzichtbaar einde")
("invisible newline" "onzichtbare newline")
("invisible opening" "onzichtbare opening")
("inwards" "naar binnen")
("join selected cells" "voeg geselecteerde cellen samen")
("jump in" "instappen")
("junior" "junior")
("justify" "rechtvaardigen")
("keep local" "lokaal houden")
("keep remote" "op afstand houden")
("keep track of source code" "broncode bijhouden")
("keep unfolded" "opengevouwen")
("key manager" "key manager")
("keyboard configuration" "toetsenbordconfiguratie")
("laTeX errors" "laTeX-fouten")
("laptop presentations" "laptoppresentaties")
("large brackets" "grote beugels")
("large cells" "grote cellen")
("large displayed" "groot weergegeven")
("large displayed fraction" "grote weergegeven fractie")
("large tables" "grote tafels")
("last" "laatste")
("last check" "laatste controle")
("last difference" "laatste verschil")
("last error" "laatste fout")
("last field" "laatste veld")
("last name" "achternaam")
("last occurrence" "laatste keer")
("last similar" "laatste vergelijkbare")
("left axis" "linkeras")
("left baseline" "linker basislijn")
("left bottom" "links onderaan")
("left center" "links midden")
("left click: add point; Right click: undo" "linker muisklik: punt toevoegen; rechter muisklik: ongedaan maken")
("left click: finish; Right click: undo" "linker muisklik: voltooien; rechter muisklik: ongedaan maken")
("left click: new object" "linkermuisknop: nieuw object")
("left click: operate" "linkermuisknop: bedienen")
("left down" "naar links")
("left on even pages" "nog op even pagina's")
("left top" "links bovenaan")
("left up" "links boven")
("left-right arrow" "pijl links-rechts")
("leftwards" "naar links")
("let the environment float" "laat de omgeving zweven")
("line arrows" "lijnpijlen")
("line breaking" "regeleinde")
("line dashes" "lijnstrepen")
("line portion" "lijngedeelte")
("line style" "lijnstijl")
("line width" "lijnbreedte")
("line wrapping" "lijnverpakking")
("line wrapping inside cell" "regelomloop binnen cel")
("linear 2D" "lineaire 2D")
("lines around" "lijnen rondom")
("link image and copies as" "link afbeelding en kopieën als")
("link image as" "link afbeelding als")
("link mode" "koppelingsmodus")
("link to URL" "link naar URL")
("linking tool" "linktool")
("live" "live")
("live input-output" "live invoer-uitvoer")
("load help file" "helpbestand laden")
("load remote file" "extern bestand laden")
("loading" "laden")
("local entries" "lokale vermeldingen")
("loci" "loci")
("locus" "locus")
("locus rendering" "locus rendering")
("logarithmic" "logaritmisch")
("logarithmic base" "logaritmische basis")
("logging in" "inloggen")
("logical and" "logisch en")
("logical implication" "logische implicatie")
("logical not" "logisch niet")
("logical or" "logisch of")
("login" "inloggen")
("logout" "uitloggen")
("long macro" "lange macro")
("long text" "lange tekst")
("look for more fonts" "zoek naar meer lettertypen")
("loops" "lussen")
("macro argument" "macro-argument")
("macro definition" "macrodefinitie")
("macro editor" "macro-editor")
("macro name" "macronaam")
("macros" "macro's")
("macros editor" "macro-editor")
("magnify horizontally" "horizontaal vergroten")
("magnify vertically" "verticaal vergroten")
("main presentation style" "hoofdpresentatiestijl")
("make a letter environment" "een briefomgeving maken")
("make a multi-slide presentation" "maak een presentatie met meerdere dia's")
("make block wide" "blok breed maken")
("make float wide" "maak zwevend breed")
("make floating" "zwevend maken")
("make footnote wide" "voetnoot breed maken")
("make link" "link maken")
("make non floating" "niet-zwevend maken")
("make wide" "breed maken")
("manila paper" "manilla-papier")
("map arguments" "kaartargumenten")
("marginal note" "kanttekening")
("margins from width" "marges vanaf breedte")
("margins on paper" "marges op papier")
("margins on screen" "marges op scherm")
("marked" "gemarkeerd")
("marker" "marker")
("material" "materiaal")
("math Extra" "wiskunde Extra")
("math Letters" "wiskundige letters")
("math Symbols" "wiskundige symbolen")
("mathematical output" "wiskundige output")
("maximal clustering" "maximale clustering")
("maximum" "maximum")
("meander" "meander")
("medieval" "middeleeuws")
("memory" "geheugen")
("memory usage" "geheugengebruik")
("menu" "menu")
("merge lines into paragraphs unless separated by blank lines" "regels samenvoegen in alinea's tenzij gescheiden door lege regels")
("messages" "berichten")
("meta data" "metagegevens")
("metadata" "metadata")
("metal" "metaal")
("middle baseline" "middelste basislijn")
("minimal line separation" "minimale lijnscheiding")
("minimum" "minimum")
("mirror" "spiegel")
("miscellanous" "overige")
("mixed" "gemengd")
("mode dependent icons" "modusafhankelijke pictogrammen")
("modify bibliography" "bibliografie wijzigen")
("modify remote live document" "live document op afstand wijzigen")
("module" "module")
("module browser" "modulebrowser")
("monospaced" "monospaced")
("more information about GNU TeXmacs can be found in the Help->About menu" "meer informatie over GNU TeXmacs is te vinden in het menu Help-> Info")
("more information about GNU TeXmacs can be found in the help" "meer informatie over GNU TeXmacs is te vinden in de help")
("motion" "beweging")
("mouse over object" "muis over object")
("move" "zet")
("move objects" "objecten verplaatsen")
("move over object on which to operate" "Beweeg over object waarop moet worden gewerkt")
("multiline" "multiline")
("multiple choice" "meerkeuze")
("multiple documents share window" "venster voor het delen van meerdere documenten")
("multiple root" "multiple root")
("multiplication" "vermenigvuldiging")
("named" "benoemd")
("navigation options" "navigatie-opties")
("new account" "nieuw account")
("new bibliography dialogue" "nieuwe bibliografie dialoog")
("new entry" "nieuwe invoer")
("new identity" "nieuwe identiteit")
("new locus" "nieuwe locus")
("new macro" "nieuwe macro")
("new passphrase" "nieuwe wachtwoordzin")
("new remote directory" "nieuwe externe map")
("new remote file" "nieuw extern bestand")
("new style fonts" "nieuwe stijllettertypen")
("new style page breaking" "pagina-einde nieuwe stijl")
("new version" "nieuwe versie")
("new window" "nieuw venster")
("newer version" "nieuwere versie")
("next chunk" "volgende stuk")
("next difference" "volgend verschil")
("next error" "volgende fout")
("next field" "volgend veld")
("next occurrence" "volgende keer")
("next screen" "volgend scherm")
("next similar" "volgende soortgelijke")
("no animation" "geen animatie")
("no clustering" "geen clustering")
("no completions" "geen voltooiingen")
("no errors have been corrected" "er zijn geen fouten gecorrigeerd")
("no grid" "geen rooster")
("no multiple spaces" "geen meerdere spaties")
("no new public key in document" "geen nieuwe openbare sleutel in document")
("no page break" "geen pagina-einde")
("no page numbers" "geen paginanummers")
("no parent" "geen ouder")
("no selection" "geen selectie")
("no spelling errors" "geen spelfouten")
("no spurious spaces" "geen valse spaties")
("normal loci" "normale loci")
("not allowed to remove home directory" "mag hoofdmap niet verwijderen")
("not connected to server" "niet verbonden met server")
("not yet implemented" "nog niet geïmplementeerd")
("notebook" "notebook")
("number of polar steps" "aantal polaire stappen")
("number of subunit steps" "aantal stappen subeenheid")
("numbered" "genummerd")
("numbering" "nummering")
("numeric spreadsheet" "numerieke spreadsheet")
("oblique" "schuin")
("odd page" "oneven pagina")
("odd pages" "oneven pagina's")
("of fingerprint" "of fingerprint")
("old version" "oude versie")
("older version" "oudere versie")
("on your system and set it up from the \"Security\" tab" "op uw systeem en stel dit in vanaf het tabblad \"Beveiliging \"")
("once" "eenmalig")
("one column" "één kolom")
("one error has been corrected" "één fout is gecorrigeerd")
("one lower case letter, one non alpha-numeric symbol" "één kleine letter, één niet-alfanumeriek symbool")
("one numeric character, one upper case letter" "één numeriek teken, één hoofdletter")
("only convert changes when re-importing" "wijzigingen alleen converteren bij opnieuw importeren")
("only convert changes with respect to imported version" "alleen wijzigingen converteren met betrekking tot geïmporteerde versie")
("only convert changes with respect to tracked version" "converteer alleen wijzigingen met betrekking tot de bijgehouden versie")
("only implemented for complete subtrees" "alleen geïmplementeerd voor volledige substructuren")
("only keep folded" "houd alleen gevouwen")
("only keep unfolded" "alleen opengevouwen")
("only show paragraphs with hits" "toon alleen paragrafen met hits")
("only show semantic focus" "toon alleen semantische focus")
("opacity" "dekking")
("open bibliography" "open bibliografie")
("open identities" "open identiteiten")
("open in new window" "openen in nieuw venster")
("open key manager" "open key manager")
("open licence agreement" "open licentieovereenkomst")
("open mailbox" "open mailbox")
("open module browser" "open module browser")
("open symbol browser" "open symboolbrowser")
("open tool in separate window" "open tool in apart venster")
("or give the complete path to the \"gpg\" or \"gpg2\" command" "of geef het volledige pad naar het commando \"gpg\" of \"gpg2\"")
("order" "bestelling")
("ordinary symbol" "gewoon symbool")
("ornamented" "versierd")
("other login" "andere login")
("other package" "ander pakket")
("outer bottom" "buitenste bodem")
("outer left" "buiten links")
("outer right" "buiten rechts")
("outer top" "buitenste top")
("outline" "overzicht")
("outlined" "geschetst")
("outlined emboss" "omlijnd reliëf")
("outlined engrave" "geschetst graveren")
("output options" "uitvoeropties")
("outwards" "naar buiten")
("oval" "ovaal")
("overlap" "overlapping")
("overlay" "overlay")
("overlay mode" "overlay-modus")
("overlays" "overlays")
("overlined" "onderstreept")
("overview of the scheme extension language" "overzicht van de taal van de schema-extensie")
("padded" "gevoerd")
("page background" "pagina-achtergrond")
("page break after" "pagina-einde na")
("page breaking algorithm" "algoritme voor pagina-einde")
("page format" "pagina-indeling")
("page number" "paginanummer")
("page number rendering" "weergave van paginanummer")
("page rendering" "paginaweergave")
("pagedown" "terugspoelen")
("pageup" "pageup")
("palette" "palet")
("panorama" "panorama")
("paragraph format" "alinea-indeling")
("paragraphs" "alinea's")
("parenthesis" "haakjes")
("parenthesized" "haakjes")
("particle" "deeltje")
("passphrase decryption" "decodering van wachtwoordzin")
("passphrase encryption" "wachtwoordzin-codering")
("passphrase wallet facilities are not currently available" "faciliteiten voor wachtwoordzin-portemonnee zijn momenteel niet beschikbaar")
("passphrases are expected to have at least: 8 characters" "wachtzinnen moeten ten minste: 8 tekens bevatten")
("passphrases mismatch" "mismatch passphrases")
("pastel" "pastel")
("pattern" "patroon")
("pattern selector" "patroonkiezer")
("pause" "pauze")
("pdf version number" "pdf-versienummer")
("pen" "pen")
("pen width" "penbreedte")
("permanent footer" "permanente voettekst")
("permanent header" "permanente koptekst")
("permanently add to dictionary" "permanent toevoegen aan woordenboek")
("permanently insert into dictionary" "permanent invoegen in woordenboek")
("permissions" "machtigingen")
("phantom" "fantoom")
("phantoms" "fantomen")
("physics and astronomy class" "fysica- en astronomieklasse")
("picture" "afbeelding")
("pine" "grenen")
("plain" "gewoon")
("plain boxes" "gewone dozen")
("plain circles" "gewone cirkels")
("play" "spelen")
("play all animations" "speel alle animaties")
("play animation" "animatie afspelen")
("please install GnuPG software from https://www.gnupg.org" "installeer GnuPG-software van https://www.gnupg.org")
("plug-ins" "plug-ins")
("plugin" "plug-in")
("plugins" "plug-ins")
("plural" "meervoud")
("point" "punt")
("point border" "puntgrens")
("point size" "puntgrootte")
("point style" "puntstijl")
("polar" "polair")
("polygon" "polygoon")
("pop server settings" "pop-serverinstellingen")
("portion" "portie")
("position of marginal note" "positie van kanttekening")
("poster formats" "posterformaten")
("poster theme" "poster thema")
("postfix" "postfix")
("preferences for editing mathematical formulas" "voorkeuren voor het bewerken van wiskundige formules")
("preferences for tag" "voorkeuren voor tag")
("prefix" "voorvoegsel")
("presentation tool" "presentatietool")
("preserve" "bewaren")
("preserve tags" "tags behouden")
("pretty" "mooi")
("pretty tree output" "mooie boomuitvoer")
("preview" "voorbeeld")
("previous difference" "vorig verschil")
("previous error" "vorige fout")
("previous field" "vorig veld")
("previous occurrence" "vorige keer")
("previous screen" "vorig scherm")
("previous similar" "vorige vergelijkbaar")
("primitive or macro" "primitief of macro")
("print buffer" "afdrukbuffer")
("print buffer to file" "afdrukbuffer naar bestand")
("print document" "document afdrukken")
("print to file" "afdrukken naar bestand")
("printer setup" "printerinstellingen")
("produce Pdf using native export filter" "PDF produceren met native exportfilter")
("produce Postscript using native export filter" "PostScript produceren met native exportfilter")
("program bracket matching" "programma bracket matching")
("program bracket selections" "programmabeugel selecties")
("program commands" "programma-opdrachten")
("program interface for buffer management" "programma-interface voor bufferbeheer")
("programming routines for editing documents" "programmeerroutines voor het bewerken van documenten")
("prominent" "prominent")
("provoke C++ error" "veroorzaakt C ++ -fout")
("provoke menu error" "veroorzaakt menufout")
("provoke scheme error" "veroorzaakt schemafout")
("pseudo code" "pseudocode")
("public key encryption" "openbare sleutelcodering")
("public keys" "openbare sleutels")
("pulse" "puls")
("qt GUI only, sorry. Use \"Export selection\"" "Alleen qt GUI, sorry. Gebruik \"Selectie exporteren\"")
("qt-widgets" "qt-widgets")
("quantifier" "kwantificeerder")
("quasi" "quasi")
("questions only" "alleen vragen")
("questions with answers" "vragen met antwoorden")
("quick evaluation of formulas" "snelle evaluatie van formules")
("raw" "onbewerkt")
("really delete user identity" "gebruikersidentiteit echt verwijderen")
("rebuild translations file" "vertaalbestand opnieuw opbouwen")
("recent documents" "recente documenten")
("recipients" "ontvangers")
("recognize" "herkennen")
("recolor" "opnieuw kleuren")
("rectangular" "rechthoekig")
("reduce" "verkleinen")
("reduced margins" "verkleinde marges")
("regenerate" "regenereren")
("register" "aanmelden")
("register file" "registerbestand")
("relate" "hebben betrekking")
("relation" "relatie")
("release left button: finish editing" "linkerknop loslaten: bewerking voltooien")
("remote" "afstandsbediening")
("remote connections" "externe verbindingen")
("remote control" "afstandsbediening")
("remote controllers with keyboard simulation" "afstandsbedieningen met toetsenbordsimulatie")
("remote directory" "externe map")
("remote login" "inloggen op afstand")
("remote servers" "externe servers")
("remote tool" "externe tool")
("remove animation" "animatie verwijderen")
("remove argument after" "argument verwijderen na")
("remove argument before" "argument eerder verwijderen")
("remove banner" "banner verwijderen")
("remove database entry" "verwijder database-invoer")
("remove downwards" "naar beneden verwijderen")
("remove entries" "vermeldingen verwijderen")
("remove entry" "invoer verwijderen")
("remove field above" "veld hierboven verwijderen")
("remove field below" "veld hieronder verwijderen")
("remove folded" "verwijder gevouwen")
("remove from previous frames" "verwijderen uit vorige frames")
("remove from subsequent frames" "verwijderen uit volgende frames")
("remove last field" "laatste veld verwijderen")
("remove leftwards" "naar links verwijderen")
("remove link" "link verwijderen")
("remove next field" "verwijder volgend veld")
("remove overlay after" "overlay verwijderen na")
("remove overlay before" "overlay eerder verwijderen")
("remove previous field" "vorig veld verwijderen")
("remove rightwards" "naar rechts verwijderen")
("remove selected database entries" "verwijder geselecteerde database-ingangen")
("remove selected entries" "geselecteerde items verwijderen")
("remove slide after" "dia verwijderen na")
("remove slide before" "dia eerder verwijderen")
("remove superfluous invisible operators" "overbodige onzichtbare operatoren verwijderen")
("remove tag" "tag verwijderen")
("remove this branch" "verwijder deze tak")
("remove this frame" "dit frame verwijderen")
("remove unfolded" "opengevouwen verwijderen")
("remove upwards" "naar boven verwijderen")
("removed entries from database" "verwijderde gegevens uit database")
("removed entry from database" "item uit database verwijderd")
("rename" "hernoemen")
("rename section" "sectie hernoemen")
("rendering" "weergave")
("rendering options for tag" "weergaveopties voor tag")
("replace TeXmacs styles with no LaTeX equivalents" "vervang TeXmacs-stijlen zonder LaTeX-equivalenten")
("replace all further occurrences" "alle nieuwe gebeurtenissen vervangen")
("replace one occurrence" "één exemplaar vervangen")
("replace toolbar" "werkbalk vervangen")
("reset error counters" "reset foutentellers")
("resize" "formaat wijzigen")
("resize objects" "formaat van objecten wijzigen")
("restart TeXmacs in order to let changes take effect" "herstart TeXmacs om wijzigingen van kracht te laten worden")
("restart in order to let the new look and feel take effect" "herstart om de nieuwe look and feel van kracht te laten worden")
("retain" "behouden")
("retime" "retime")
("retina settings" "retina-instellingen")
("retrieve email" "e-mail ophalen")
("retrieve remote live document" "extern document ophalen")
("retrieved contents" "opgehaalde inhoud")
("retro" "retro")
("reverse" "achteruit")
("reverse ordering" "omgekeerde bestelling")
("ridged paper" "geribbeld papier")
("right baseline" "juiste basislijn")
("right down" "rechts beneden")
("right on even pages" "recht op even pagina's")
("right up" "recht omhoog")
("rightwards" "naar rechts")
("rigid box" "stijve doos")
("rotate" "roteren")
("rotate objects" "objecten roteren")
("rough" "ruw")
("rough paper" "ruw papier")
("round" "rond")
("round overbrace" "ronde overbrace")
("round underbrace" "rond onderstel")
("run" "uitvoeren")
("run current file" "huidig   bestand uitvoeren")
("same names" "dezelfde namen")
("same screen margins as on paper" "dezelfde schermmarges als op papier")
("sample text" "voorbeeldtekst")
("save auxiliary data" "hulpgegevens opslaan")
("save entries" "vermeldingen opslaan")
("save entry" "vermelding opslaan")
("save image as" "afbeelding opslaan als")
("save position" "positie opslaan")
("save remote file" "extern bestand opslaan")
("saved modifications in database" "opgeslagen wijzigingen in database")
("scheme developers guide" "gids voor schema-ontwikkelaars")
("scheme extensions" "schema-uitbreidingen")
("scheme interface for the graphical mode" "schema-interface voor de grafische modus")
("screen" "scherm")
("screen rendering" "schermweergave")
("screens" "schermen")
("screenshot" "screenshot")
("scripting language" "scripttaal")
("scripts" "scripts")
("search and replace" "zoeken en vervangen")
("search in database" "zoeken in database")
("search toolbar" "zoekwerkbalk")
("second" "tweede")
("secret keys" "geheime sleutels")
("sections" "secties")
("see documentation" "zie documentatie")
("select GnuPG recipients" "selecteer GnuPG-ontvangers")
("select background picture" "achtergrondafbeelding selecteren")
("select document style" "documentstijl selecteren")
("select pen" "selecteer pen")
("select the action to be undertaken for each conflict" "selecteer de actie die moet worden ondernomen voor elk conflict")
("select view mode" "selecteer weergavemodus")
("semantic correctness" "semantische correctheid")
("semantic editing" "semantische bewerking")
("semantic selections" "semantische selecties")
("semantics" "semantiek")
("senior" "senior")
("serif" "serif")
("server" "server")
("server licence agreement" "serverlicentieovereenkomst")
("session commands" "sessiecommando's")
("set default" "standaardinstelling")
("set difference" "ingesteld verschil")
("set intersection" "kruispunt instellen")
("set number of columns" "aantal kolommen instellen")
("set number of rows" "aantal rijen instellen")
("set properties" "eigenschappen instellen")
("set union" "set union")
("set user information" "gebruikersinformatie instellen")
("seventh" "zevende")
("several equations" "meerdere vergelijkingen")
("shadow" "schaduw")
("shadowed" "in de schaduw")
("shadowed raise" "schaduwverhoging")
("shift" "shift")
("show all parts" "toon alle onderdelen")
("show current focus" "toon huidige focus")
("show full context" "volledige context weergeven")
("show key presses" "toetsaanslagen weergeven")
("show main document" "hoofddocument weergeven")
("show memory usage" "geheugengebruik weergeven")
("show one part" "toon één deel")
("show panorama" "panorama weergeven")
("show preamble" "show preambule")
("show several parts" "meerdere delen weergeven")
("show subunits" "subeenheden weergeven")
("show table cells" "tabelcellen weergeven")
("show timings" "toon timings")
("side tools" "zijgereedschap")
("simple" "eenvoudig")
("simple form" "eenvoudige vorm")
("simple widget" "eenvoudige widget")
("sixth" "zesde")
("skew" "scheef")
("skin" "skin")
("skip all" "alles overslaan")
("slant" "schuin")
("slashed fraction" "gesneden fractie")
("slides" "dia's")
("slow" "langzaam")
("slow decrease" "langzame afname")
("slow increase" "langzame toename")
("small Capitals" "kleine hoofdsteden")
("small capitals" "kleine hoofdsteden")
("small environment box" "kleine omgevingsbox")
("small focus" "kleine focus")
("small inline" "kleine inline")
("small inline fraction" "kleine inline fractie")
("smash" "smash")
("smooth" "soepel")
("smooth end" "glad einde")
("smooth extremities" "gladde ledematen")
("smooth start" "soepele start")
("snap" "snap")
("snap distance" "snapafstand")
("snap to curves" "uitlijnen op curven")
("snap to grid" "snap to grid")
("snap to grid curve" "snap to grid curve")
("snap to intersections of curves" "uitlijnen op kruispunten van curven")
("snap to text borders" "snappen naar tekstranden")
("snap to text corners" "uitlijnen op teksthoeken")
("solution" "oplossing")
("solution to exercise" "oplossing om te oefenen")
("solution to problem" "oplossing voor probleem")
("solutions" "oplossingen")
("sound" "geluid")
("source" "bron")
("source macros tool" "hulpmiddel voor bronmacro's")
("south" "zuiden")
("south east" "zuidoost")
("space bar in math mode" "spatiebalk in wiskundemodus")
("space bar in text mode" "spatiebalk in tekstmodus")
("space stretchability" "ruimte-rekbaarheid")
("span" "span")
("span over all columns" "overspanning over alle kolommen")
("specific baseline" "specifieke basislijn")
("specified" "gespecificeerd")
("specify color alternation" "kleurafwisseling opgeven")
("specify how to traverse the manual" "specificeren hoe de handleiding moet worden doorlopen")
("specify semantics of a symbol or formula" "semantiek van een symbool of formule opgeven")
("specify user identity" "gebruikersidentiteit opgeven")
("spell check" "spellingcontrole")
("spline" "spline")
("split program" "gesplitst programma")
("square" "vierkant")
("square overbrace" "vierkante overbrace")
("square underbrace" "vierkante onderlaag")
("stack" "stapel")
("standard" "standaard")
("standard Output" "standaarduitvoer")
("standard fraction" "standaardfractie")
("star" "ster")
("start server" "start server")
("statement" "verklaring")
("statistics" "statistieken")
("status" "status")
("stop server" "stop-server")
("storage" "opslag")
("store tracking information in LaTeX files" "trackinginformatie opslaan in LaTeX-bestanden")
("stretch factor" "rekfactor")
("strict Ascii" "strikte Ascii")
("strike through" "doorhalen")
("structured insert above" "gestructureerde invoeging hierboven")
("structured insert at the left" "gestructureerd inzetstuk links")
("structured insert at the right" "gestructureerd inzetstuk rechts")
("structured insert below" "gestructureerde invoeging hieronder")
("structured remove downwards" "gestructureerd naar beneden verwijderen")
("structured remove leftwards" "gestructureerd links verwijderen")
("structured remove rightwards" "gestructureerd rechts verwijderen")
("structured remove upwards" "gestructureerd naar boven verwijderen")
("structured variant" "gestructureerde variant")
("style options" "stijlopties")
("style parameters" "stijlparameters")
("subject" "onderwerp")
("submenu" "submenu")
("subscript below" "subscript hieronder")
("subsubmenu" "subsubmenu")
("subsubsubmenu" "subsubsubmenu")
("subsubsubsubmenu" "subsubsubsubmenu")
("subtraction" "aftrekken")
("summarized" "samengevat")
("superscript above" "superscript hierboven")
("supported plug-ins" "ondersteunde plug-ins")
("swell" "zwelling")
("switch to buffer" "overschakelen naar buffer")
("symbol browser" "symboolbrowser")
("symbol properties not found" "symbooleigenschappen niet gevonden")
("symbols" "symbolen")
("synchronization status" "synchronisatiestatus")
("synchronize" "synchroniseren")
("synchronize bibliographic references" "bibliografische referenties synchroniseren")
("synchronize file or directory" "bestand of map synchroniseren")
("synchronize with remote server" "synchroniseren met externe server")
("synopsis" "synopsis")
("tab-completion" "tabaanvulling")
("tabbed" "met tabs")
("table breaking" "tafel breken")
("table properties" "tabeleigenschappen")
("tags with special rendering" "tags met speciale rendering")
("teXmacs DTD" "teXmacs DTD")
("teXmacs buffer expected" "teXmacs buffer verwacht")
("teXmacs buffer on disk expected" "teXmacs buffer op schijf verwacht")
("teXmacs database preferences" "teXmacs database voorkeuren")
("teXmacs extensions to scheme and utilities" "teXmacs-uitbreidingen voor schema en hulpprogramma's")
("teXmacs macro" "teXmacs macro")
("teXmacs package" "teXmacs-pakket")
("teXmacs plugins" "teXmacs-plug-ins")
("teXmacs primitives" "teXmacs primitieven")
("teXmacs style" "teXmacs-stijl")
("test routine" "testroutine")
("testing tree-view" "boomstructuur testen")
("text borders" "tekstranden")
("text box style" "tekstvakstijl")
("text corners" "teksthoeken")
("text padding" "tekstopvulling")
("textual" "tekstueel")
("textual operator" "tekstuele operator")
("textual spreadsheet" "tekstuele spreadsheet")
("the TeXmacs plug-in system" "het TeXmacs plug-in systeem")
("theme parameters" "themaparameters")
("these collected public keys will be definitely lost" "deze verzamelde openbare sleutels zullen zeker verloren gaan")
("these public keys will be definitely lost" "deze openbare sleutels zullen zeker verloren gaan")
("these secret keys will be definitely lost" "deze geheime sleutels zullen zeker verloren gaan")
("thicken" "dikker")
("thin" "dun")
("third" "derde")
("this" "dit")
("this page number" "dit paginanummer")
("this style specifies page margins in the TeX way" "deze stijl specificeert paginamarges op de TeX-manier")
("three columns" "drie kolommen")
("three dots" "drie puntjes")
("three times" "drie keer")
("through popup windows" "via pop-upvensters")
("through the menus" "via de menu's")
("time evolution" "tijdevolutie")
("timings" "timings")
("title presentation options" "titel presentatie opties")
("title style" "titelstijl")
("title suffix" "titel-achtervoegsel")
("titled block" "getiteld block")
("toggle cell wrapping mode" "modus voor celverpakking schakelen")
("toggle here" "hier schakelen")
("toggle name" "naam schakelen")
("toggle numbering" "schakelen tussen nummering")
("toggle off" "uitschakelen")
("toggle on" "aanzetten")
("toggle specification" "toggle-specificatie")
("toggle titled" "met de titel schakelen")
("tolerant" "tolerant")
("top baseline" "topbasislijn")
("transform" "transformatie")
("transform cell into subtable" "cel omzetten in subtabel")
("translations" "vertalingen")
("translations loaded" "vertalingen geladen")
("traversal" "traversaal")
("traverse" "doorkruisen")
("triangle" "driehoek")
("turn off" "uitschakelen")
("turn on" "inschakelen")
("turn on wallet" "portemonnee inschakelen")
("twice" "tweemaal")
("two columns" "twee kolommen")
("two dots" "twee punten")
("type a latex command followed by return" "typ een latexcommando gevolgd door retour")
("unchanged" "ongewijzigd")
("underlined" "onderstreept")
("unevaluated argument" "niet-geëvalueerd argument")
("unevaluated value" "niet-geëvalueerde waarde")
("unextended" "niet-uitgebreid")
("unfold" "ontvouwen")
("unfold all" "alles ontvouwen")
("unfold all fields" "ontvouw alle velden")
("unfolded" "uitgevouwen")
("unit" "eenheid")
("unit length" "lengte van eenheid")
("unknown secret key fingerprint" "onbekende geheime sleutel vingerafdruk")
("unregistered file" "niet-geregistreerd bestand")
("unroll" "uitrollen")
("unsecure script refused" "onveilig script geweigerd")
("unsupported link mode" "niet-ondersteunde koppelingsmodus")
("until" "tot")
("untitled block" "naamloos blok")
("up to date" "actueel")
("update buffer" "update buffer")
("update this buffer" "update deze buffer")
("update web site" "website bijwerken")
("upight" "rechtop")
("upload" "upload")
("upload file or directory" "bestand of map uploaden")
("upwards" "omhoog")
("url" "url")
("use CSS for more advanced formatting" "CSS gebruiken voor meer geavanceerde opmaak")
("use as master" "gebruik als master")
("use extensible brackets" "gebruik uitschuifbare beugels")
("use high resolution fonts" "gebruik hoge resolutie lettertypen")
("use high resolution icons" "gebruik pictogrammen met hoge resolutie")
("use line wrapping for lines which are longer than 80 characters" "gebruik regelomloop voor regels die langer zijn dan 80 tekens")
("use margin kerning (protrusion)" "gebruik marge kerning (uitsteeksel)")
("use print dialogue" "printdialoog gebruiken")
("use protrusion" "gebruik uitsteeksel")
("use relative path" "gebruik relatief pad")
("use retina fonts" "gebruik retina-lettertypen")
("use retina icons" "gebruik retina-pictogrammen")
("use unified toolbars" "gebruik uniforme werkbalken")
("user interface" "gebruikersinterface")
("user interface language" "taal gebruikersinterface")
("user preferences" "gebruikersvoorkeuren")
("users of oriental languages" "gebruikers van oosterse talen")
("utf-8 with inputenc" "utf-8 met inputenc")
("utf-8 with inputenc LaTeX package" "utf-8 met inputenc LaTeX-pakket")
("utilities" "hulpprogramma's")
("vanish" "verdwijnen")
("verbose" "uitgebreid")
("version" "versie")
("versioning tool" "versie-tool")
("vertical margins" "verticale marges")
("vertical space after" "verticale ruimte na")
("vertical space before" "verticale ruimte ervoor")
("vertical space stretchability" "verticale ruimte-rekbaarheid")
("visible except here" "zichtbaar behalve hier")
("visible from here on" "vanaf hier zichtbaar")
("visible only here" "alleen hier zichtbaar")
("visible until here" "zichtbaar tot hier")
("visited loci" "bezocht loci")
("wallet" "portemonnee")
("wave" "golf")
("weight" "gewicht")
("when line wrapping" "wanneer lijnomloop")
("when wrapping" "bij verpakking")
("whitespace" "witruimte")
("wide" "breed")
("wide block" "breed blok")
("wide colored" "breed gekleurd")
("wide float" "wide float")
("wide footnote" "brede voetnoot")
("wide tabular" "brede tabel")
("widescreen" "breedbeeld")
("with newer version" "met nieuwere versie")
("with older version" "met oudere versie")
("writing TeXmacs bibliography styles" "TeXmacs bibliografische stijlen schrijven")
("writing documentation" "documentatie schrijven")
("wrong empty passphrase" "verkeerde lege wachtwoordzin")
("wrong passphrase" "verkeerde wachtwoordzin")
("year" "jaar")
("year, Name" "jaar, naam")
("you are attempting to open an encrypted file while" "u probeert een gecodeerd bestand te openen terwijl")
("you might consider enabling the experimental" "je zou kunnen overwegen het experimentele in te schakelen")
("you must add a bibliography file" "u moet een bibliografiebestand toevoegen")
("you should also make sure that GnuPG is installed" "je moet er ook voor zorgen dat GnuPG is geïnstalleerd")
("your personal dictionary has been modified" "uw persoonlijke woordenboek is aangepast")
("zebra" "zebra")
("zoom" "zoom")
("zoom in" "inzoomen")
("zoom out" "uitzoomen")
("zoom/unzoom objects" "objecten zoomen / uitpakken")
