("link image and copies as" "link afbeelding en kopieën als")
("only convert changes with respect to imported version" "alleen wijzigingen converteren met betrekking tot geïmporteerde versie")
("only implemented for complete subtrees" "alleen geïmplementeerd voor volledige substructuren")
("outlined emboss" "omlijnd reliëf")
("outlined engrave" "geschetst graveren")
("padded" "gevoerd")
("quantifier" "kwantificeerder")
("relate" "hebben betrekking")
("replace one occurrence" "één exemplaar vervangen")
("reset error counters" "reset foutentellers")
("show one part" "toon één deel")
("show timings" "toon timings")
("small inline" "kleine inline")
("small inline fraction" "kleine inline fractie")
("span" "span")
("span over all columns" "overspanning over alle kolommen")
("store tracking information in LaTeX files" "trackinginformatie opslaan in LaTeX-bestanden")
("timings" "timings")
("title suffix" "titel-achtervoegsel")
("traversal" "traversaal")
("unevaluated argument" "niet-geëvalueerd argument")
("unevaluated value" "niet-geëvalueerde waarde")
("use margin kerning (protrusion)" "gebruik marge kerning (uitsteeksel)")
("use protrusion" "gebruik uitsteeksel")
