("fixed" "vast")
("flag is off" "vlag is uit")
("flag is on" "vlag is aan")
("flatten" "plat")
("focus dependent icons" "focusafhankelijke pictogrammen")
("fraktur" "fraktur")
("front matter" "voorkant")
("full screen mode" "volledig scherm")
("gap" "kloof")
("garbage collection" "garbage collection")
("gaussian" "gaussiaans")
("geometry" "geometrie")
("get arity" "krijg arity")
("get label" "label krijgen")
("get list with remote versions" "krijg lijst met versies op afstand")
("glyphs" "glyphs")
("gnuPG decryption error" "gnuPG-decryptiefout")
("gnuPG error: buffer encryption failed" "gnuPG-fout: bufferversleuteling mislukt")
("go to anchor" "ga voor anker")
("go to anchor or float" "ga voor anker of drijven")
("go to float" "gaan zweven")
("grain" "korrel")
("graphical slides and overlays" "grafische dia's en overlays")
("graphics" "grafische weergave")
("graphics geometry" "grafische geometrie")
("group/ungroup" "groep / degroep")
("group/ungroup objects" "objecten groeperen / degroeperen")
("grouped" "gegroepeerd")
("guarantee transparent source tracking" "garanderen transparante brontracering")
("hand drawn" "hand getrokken")
("headers" "headers")
("homoglyph substitutions" "homoglyph-substituties")
("horizontal collapse distance" "horizontale instortafstand")
("icon" "pictogram")
("inanimated" "geanimeerd")
("inch" "inch")
("incomplete entries found to be filled out" "onvolledige gegevens die zijn ingevuld")
("ink here" "inkt hier")
("ink in" "inkt in")
("ink out" "inkt op")
("inline" "inline")
("inline args" "inline args")
("inline code" "inline code")
("inline content" "inline content")
("inline formula" "inline-formule")
("insert an enunciation" "een uitspraak invoegen")
("insert large delimiters" "grote scheidingstekens invoegen")
("insert overlay after" "overlay invoegen na")
("insert overlay before" "overlay invoegen")
("insert particle" "deeltje invoegen")
("insert plain text" "tekst zonder opmaak")
("insert right" "rechts invoegen")
("insert similar above" "invoegen vergelijkbaar hierboven")
("insert similar below" "invoegen vergelijkbaar hieronder")
("insert similar block above" "voeg gelijkaardig blok hierboven in")
("insert similar block below" "invoegen vergelijkbaar blok hieronder")
("insert slide after" "dia invoegen na")
("insert slide before" "dia vóór invoegen")
("insert subscript" "subscript invoegen")
("insert superscript" "superscript invoegen")
("insert template" "sjabloon invoegen")
("intercharacter compression" "compressie tussen tekens")
("intercharacter stretching" "intercharacter stretching")
("invalid renaming" "ongeldige hernoemen")
("inverted breve" "geïnverteerde breve")
("jump in" "instappen")
("justify" "rechtvaardigen")
("keep local" "lokaal houden")
("keep remote" "op afstand houden")
("keep unfolded" "opengevouwen")
("key manager" "key manager")
("last occurrence" "laatste keer")
("left click: operate" "linkermuisknop: bedienen")
("left on even pages" "nog op even pagina's")
("left-right arrow" "pijl links-rechts")
("line arrows" "lijnpijlen")
("line breaking" "regeleinde")
("line dashes" "lijnstrepen")
("line portion" "lijngedeelte")
("line style" "lijnstijl")
("line width" "lijnbreedte")
("line wrapping" "lijnverpakking")
("line wrapping inside cell" "regelomloop binnen cel")
("linear 2D" "lineaire 2D")
("lines around" "lijnen rondom")
("link image and copies as" "link afbeelding en kopieën als")
("link image as" "link afbeelding als")
("link mode" "koppelingsmodus")
("link to URL" "link naar URL")
("linking tool" "linktool")
("live input-output" "live invoer-uitvoer")
("loading" "laden")
("local entries" "lokale vermeldingen")
("locus rendering" "locus rendering")
("logging in" "inloggen")
("logical and" "logisch en")
("logical not" "logisch niet")
("logical or" "logisch of")
("macro argument" "macro-argument")
("macro definition" "macrodefinitie")
("macro editor" "macro-editor")
("macro name" "macronaam")
("macros" "macro's")
("macros editor" "macro-editor")
("make a letter environment" "een briefomgeving maken")
("make a multi-slide presentation" "maak een presentatie met meerdere dia's")
("make float wide" "maak zwevend breed")
("map arguments" "kaartargumenten")
("margins from width" "marges vanaf breedte")
("marked" "gemarkeerd")
("marker" "marker")
("menu" "menu")
("merge lines into paragraphs unless separated by blank lines" "regels samenvoegen in alinea's tenzij gescheiden door lege regels")
("meta data" "metagegevens")
("metadata" "metadata")
("mode dependent icons" "modusafhankelijke pictogrammen")
("modify remote live document" "live document op afstand wijzigen")
("module browser" "modulebrowser")
("monospaced" "monospaced")
("more information about GNU TeXmacs can be found in the help" "meer informatie over GNU TeXmacs is te vinden in de help")
("motion" "beweging")
("mouse over object" "muis over object")
("move" "zet")
("move over object on which to operate" "Beweeg over object waarop moet worden gewerkt")
("multiline" "multiline")
("multiple choice" "meerkeuze")
("multiple documents share window" "venster voor het delen van meerdere documenten")
("multiple root" "multiple root")
("named" "benoemd")
("new account" "nieuw account")
("new bibliography dialogue" "nieuwe bibliografie dialoog")
("new entry" "nieuwe invoer")
("new remote directory" "nieuwe externe map")
("new style fonts" "nieuwe stijllettertypen")
("new style page breaking" "pagina-einde nieuwe stijl")
("next occurrence" "volgende keer")
("next similar" "volgende soortgelijke")
("no multiple spaces" "geen meerdere spaties")
("no page break" "geen pagina-einde")
("no parent" "geen ouder")
("notebook" "notebook")
("number of subunit steps" "aantal stappen subeenheid")
("of fingerprint" "of fingerprint")
("only convert changes with respect to imported version" "alleen wijzigingen converteren met betrekking tot geïmporteerde versie")
("only convert changes with respect to tracked version" "converteer alleen wijzigingen met betrekking tot de bijgehouden versie")
("only implemented for complete subtrees" "alleen geïmplementeerd voor volledige substructuren")
("only keep folded" "houd alleen gevouwen")
("only keep unfolded" "alleen opengevouwen")
("opacity" "dekking")
("open key manager" "open key manager")
("open licence agreement" "open licentieovereenkomst")
("open tool in separate window" "open tool in apart venster")
("order" "bestelling")
("outline" "overzicht")
("outlined" "geschetst")
("outlined emboss" "omlijnd reliëf")
("outlined engrave" "geschetst graveren")
("overlap" "overlapping")
("overlay" "overlay")
("overlay mode" "overlay-modus")
("overlays" "overlays")
("overlined" "onderstreept")
("overview of the scheme extension language" "overzicht van de taal van de schema-extensie")
("padded" "gevoerd")
("page break after" "pagina-einde na")
("page breaking algorithm" "algoritme voor pagina-einde")
("pagedown" "terugspoelen")
("pageup" "pageup")
("parenthesized" "haakjes")
("particle" "deeltje")
("passphrase wallet facilities are not currently available" "faciliteiten voor wachtwoordzin-portemonnee zijn momenteel niet beschikbaar")
("passphrases mismatch" "mismatch passphrases")
("permissions" "machtigingen")
("physics and astronomy class" "fysica- en astronomieklasse")
("pine" "grenen")
("plain" "gewoon")
("plain boxes" "gewone dozen")
("plain circles" "gewone cirkels")
("plug-ins" "plug-ins")
("plugin" "plug-in")
("plugins" "plug-ins")
("plural" "meervoud")
("point border" "puntgrens")
("prefix" "voorvoegsel")
("presentation tool" "presentatietool")
("preserve" "bewaren")
("preserve tags" "tags behouden")
("pretty" "mooi")
("pretty tree output" "mooie boomuitvoer")
("preview" "voorbeeld")
("previous occurrence" "vorige keer")
("previous similar" "vorige vergelijkbaar")
("primitive or macro" "primitief of macro")
("print buffer" "afdrukbuffer")
("print buffer to file" "afdrukbuffer naar bestand")
("program bracket matching" "programma bracket matching")
("program bracket selections" "programmabeugel selecties")
("program commands" "programma-opdrachten")
("program interface for buffer management" "programma-interface voor bufferbeheer")
("programming routines for editing documents" "programmeerroutines voor het bewerken van documenten")
("prominent" "prominent")
("provoke C++ error" "veroorzaakt C ++ -fout")
("provoke menu error" "veroorzaakt menufout")
("provoke scheme error" "veroorzaakt schemafout")
("pseudo code" "pseudocode")
("public key encryption" "openbare sleutelcodering")
("quantifier" "kwantificeerder")
("quasi" "quasi")
("quick evaluation of formulas" "snelle evaluatie van formules")
("raw" "onbewerkt")
("rebuild translations file" "vertaalbestand opnieuw opbouwen")
("regenerate" "regenereren")
("relate" "hebben betrekking")
("relation" "relatie")
("remote" "afstandsbediening")
("remote login" "inloggen op afstand")
("remote tool" "externe tool")
("remove banner" "banner verwijderen")
("remove folded" "verwijder gevouwen")
("remove overlay after" "overlay verwijderen na")
("remove overlay before" "overlay eerder verwijderen")
("remove slide after" "dia verwijderen na")
("remove slide before" "dia eerder verwijderen")
("remove unfolded" "opengevouwen verwijderen")
("removed entries from database" "verwijderde gegevens uit database")
("removed entry from database" "item uit database verwijderd")
("rename" "hernoemen")
("rename section" "sectie hernoemen")
("replace all further occurrences" "alle nieuwe gebeurtenissen vervangen")
("replace one occurrence" "één exemplaar vervangen")
("replace toolbar" "werkbalk vervangen")
("reset error counters" "reset foutentellers")
("resize" "formaat wijzigen")
("resize objects" "formaat van objecten wijzigen")
("retime" "retime")
("retrieve email" "e-mail ophalen")
("retrieve remote live document" "extern document ophalen")
("retrieved contents" "opgehaalde inhoud")
("reverse" "achteruit")
("reverse ordering" "omgekeerde bestelling")
("round overbrace" "ronde overbrace")
("round underbrace" "rond onderstel")
("same screen margins as on paper" "dezelfde schermmarges als op papier")
("save auxiliary data" "hulpgegevens opslaan")
("save entries" "vermeldingen opslaan")
("save entry" "vermelding opslaan")
("saved modifications in database" "opgeslagen wijzigingen in database")
("scheme interface for the graphical mode" "schema-interface voor de grafische modus")
("screenshot" "screenshot")
("scripting language" "scripttaal")
("scripts" "scripts")
("search toolbar" "zoekwerkbalk")
("select view mode" "selecteer weergavemodus")
("serif" "serif")
("server" "server")
("server licence agreement" "serverlicentieovereenkomst")
("session commands" "sessiecommando's")
("set default" "standaardinstelling")
("set difference" "ingesteld verschil")
("set intersection" "kruispunt instellen")
("set union" "set union")
("shadowed" "in de schaduw")
("shadowed raise" "schaduwverhoging")
("shift" "shift")
("show one part" "toon één deel")
("show panorama" "panorama weergeven")
("show preamble" "show preambule")
("show timings" "toon timings")
("side tools" "zijgereedschap")
("simple form" "eenvoudige vorm")
("simple widget" "eenvoudige widget")
("skin" "skin")
("slashed fraction" "gesneden fractie")
("slides" "dia's")
("small Capitals" "kleine hoofdsteden")
("small capitals" "kleine hoofdsteden")
("small environment box" "kleine omgevingsbox")
("small inline" "kleine inline")
("small inline fraction" "kleine inline fractie")
("smash" "smash")
("smooth" "soepel")
("smooth extremities" "gladde ledematen")
("snap" "snap")
("snap distance" "snapafstand")
("snap to curves" "uitlijnen op curven")
("snap to grid" "snap to grid")
("snap to grid curve" "snap to grid curve")
("snap to intersections of curves" "uitlijnen op kruispunten van curven")
("snap to text borders" "snappen naar tekstranden")
("snap to text corners" "uitlijnen op teksthoeken")
("source macros tool" "hulpmiddel voor bronmacro's")
("space bar in math mode" "spatiebalk in wiskundemodus")
("space bar in text mode" "spatiebalk in tekstmodus")
("space stretchability" "ruimte-rekbaarheid")
("span" "span")
("span over all columns" "overspanning over alle kolommen")
("specified" "gespecificeerd")
("specify color alternation" "kleurafwisseling opgeven")
("specify how to traverse the manual" "specificeren hoe de handleiding moet worden doorlopen")
("specify semantics of a symbol or formula" "semantiek van een symbool of formule opgeven")
("specify user identity" "gebruikersidentiteit opgeven")
("square overbrace" "vierkante overbrace")
("square underbrace" "vierkante onderlaag")
("stack" "stapel")
("statement" "verklaring")
("statistics" "statistieken")
("store tracking information in LaTeX files" "trackinginformatie opslaan in LaTeX-bestanden")
("strict Ascii" "strikte Ascii")
("structured insert above" "gestructureerde invoeging hierboven")
("structured insert at the left" "gestructureerd inzetstuk links")
("structured insert at the right" "gestructureerd inzetstuk rechts")
("structured insert below" "gestructureerde invoeging hieronder")
("subscript below" "subscript hieronder")
("subtraction" "aftrekken")
("superscript above" "superscript hierboven")
("supported plug-ins" "ondersteunde plug-ins")
("swell" "zwelling")
("tab-completion" "tabaanvulling")
("tabbed" "met tabs")
("table breaking" "tafel breken")
("table properties" "tabeleigenschappen")
("text borders" "tekstranden")
("text box style" "tekstvakstijl")
("text corners" "teksthoeken")
("text padding" "tekstopvulling")
("the TeXmacs plug-in system" "het TeXmacs plug-in systeem")
("theme parameters" "themaparameters")
("through popup windows" "via pop-upvensters")
("through the menus" "via de menu's")
("time evolution" "tijdevolutie")
("timings" "timings")
("title presentation options" "titel presentatie opties")
("title style" "titelstijl")
("title suffix" "titel-achtervoegsel")
("titled block" "getiteld block")
("toggle cell wrapping mode" "modus voor celverpakking schakelen")
("toggle specification" "toggle-specificatie")
("top baseline" "topbasislijn")
("transform" "transformatie")
("traversal" "traversaal")
("unevaluated argument" "niet-geëvalueerd argument")
("unevaluated value" "niet-geëvalueerde waarde")
("unextended" "niet-uitgebreid")
("unroll" "uitrollen")
("unsupported link mode" "niet-ondersteunde koppelingsmodus")
("update buffer" "update buffer")
("update this buffer" "update deze buffer")
("update web site" "website bijwerken")
("use high resolution icons" "gebruik pictogrammen met hoge resolutie")
("use line wrapping for lines which are longer than 80 characters" "gebruik regelomloop voor regels die langer zijn dan 80 tekens")
("use margin kerning (protrusion)" "gebruik marge kerning (uitsteeksel)")
("use protrusion" "gebruik uitsteeksel")
("use relative path" "gebruik relatief pad")
("use retina fonts" "gebruik retina-lettertypen")
("use retina icons" "gebruik retina-pictogrammen")
("use unified toolbars" "gebruik uniforme werkbalken")
("verbose" "uitgebreid")
("versioning tool" "versie-tool")
("weight" "gewicht")
("when line wrapping" "wanneer lijnomloop")
("when wrapping" "bij verpakking")
("whitespace" "witruimte")
("wide float" "wide float")
("writing TeXmacs bibliography styles" "TeXmacs bibliografische stijlen schrijven")
("you might consider enabling the experimental" "je zou kunnen overwegen het experimentele in te schakelen")
