("\"encryption\" features from the preference panel" "")
("(Re)Build autocompletion index" "")
("a modifier" "")
("a series" "")
("a.C.M. computing class" "")
("a.M.S. subject class" "")
("abbreviated authors" "")
("abbreviation" "")
("about menu" "")
("abreviated authors" "")
("accent above" "")
("accent below" "")
("accept" "")
("accept all scripts" "")
("accept during this pass" "")
("accept no scripts" "")
("accept script" "")
("acknowledgment" "")
("acknowledgments" "")
("acronym" "")
("action" "")
("activate hidden" "")
("activate once" "")
("activation" "")
("active link types" "")
("add" "")
("add abstract information" "")
("add author information" "")
("add branch after" "")
("add branch before" "")
("add other package" "")
("add package" "")
("add style package" "")
("add switch after" "")
("add switch before" "")
("add title information" "")
("addition" "")
("address block" "")
("adjust" "")
("adjust limits" "")
("advanced font customization" "")
("advanced layout features" "")
("affiliation" "")
("albanian" "")
("algorithm" "")
("align cell to the bottom" "")
("align cell to the decimal comma" "")
("align cell to the decimal dot" "")
("align cell to the left" "")
("align cell to the right" "")
("align cell to the top" "")
("align table at axis" "")
("align table at base of left column" "")
("align table at base of middle column" "")
("align table at base of origin column" "")
("align table at base of right column" "")
("align table at fraction bar height" "")
("align table at the base of bottom row" "")
("align table at the base of middle row" "")
("align table at the base of origin row" "")
("align table at the base of top row" "")
("align table at the bottom" "")
("align table at the center" "")
("align table at the horizontal center" "")
("align table at the left" "")
("align table at the top" "")
("align table to the right" "")
("align text to the left" "")
("align text to the right" "")
("aligned" "")
("alignment" "")
("alignment of balloon" "")
("all cells" "")
("all data attached to this identity will be lost" "")
("all saved passphrases will be lost forever" "")
("allow" "")
("allow for macro definitions in preamble" "")
("allowed extension" "")
("allowed page height extension" "")
("allowed page height reduction" "")
("allowed positions" "")
("allowed positions of floating object" "")
("allowed reduction" "")
("alpha transparency" "")
("also on paper" "")
("alt key" "")
("alter" "")
("alternate" "")
("alternate except here" "")
("alternate from here on" "")
("alternate only here" "")
("alternate until here" "")
("alternative specification" "")
("always" "")
("american" "")
("amplified" "")
("and" "")
("and perform casual settings from the \"Encryption\" tab" "")
("angular" "")
("animate" "")
("animate folding" "")
("animate unfolding" "")
("animated" "")
("animation" "")
("animation toolbar" "")
("annotate" "")
("answer" "")
("answer field" "")
("answer to question" "")
("answers only" "")
("any" "")
("appear" "")
("apply macro" "")
("apply macro once" "")
("approximate" "")
("arc" "")
("arc cosine" "")
("arc sine" "")
("arc tangent" "")
("arch series" "")
("are you sure you want to delete collected public keys" "")
("are you sure you want to delete selected public keys" "")
("are you sure you want to delete selected secret keys" "")
("are you sure you want to destroy the wallet" "")
("argument" "")
("arithmetic" "")
("arrows" "")
("art frame" "")
("arxiv category" "")
("as visual grid" "")
("aspect" "")
("at fraction bar height" "")
("at the baseline" "")
("at the bottom" "")
("at the left" "")
("at the middle" "")
("at the right" "")
("at the top" "")
("attach master" "")
("authorize" "")
("auto" "")
("auto-save file" "")
("automatic brackets" "")
("automatic content generation" "")
("automatic program brackets" "")
("automatic quotes" "")
("automatically close brackets" "")
("automatically generated content" "")
("automatically import bibliographies when opening files" "")
("automatically remember all passphrases in the wallet" "")
("automatically save" "")
("autosave" "")
("axis" "")
("b series" "")
("back" "")
("background" "")
("background evaluations" "")
("backtrace errors" "")
("backward replace" "")
("backward search" "")
("base" "")
("baseline" "")
("basic communication using pipes" "")
("basic data types" "")
("beamer" "")
("beamer formats" "")
("beamer theme" "")
("become a TeXmacs developer" "")
("bench" "")
("bend bottom" "")
("bend corner" "")
("bend diagonal" "")
("bend in" "")
("bend out" "")
("bezier" "")
("bibTeX command" "")
("bidirectional" "")
("big" "")
("big environment box" "")
("big figure" "")
("big focus" "")
("big table" "")
("binary operator" "")
("bitmap resolution (dpi)" "")
("black floral I" "")
("black floral II" "")
("blackboard embold" "")
("blank column" "")
("blank row" "")
("block" "")
("block content" "")
("block of code" "")
("blur" "")
("border" "")
("both" "")
("both versions" "")
("bottom baseline" "")
("bottom border" "")
("bottom cell border" "")
("bottom cell padding" "")
("bottom padding" "")
("bottom table border" "")
("bottom table padding" "")
("bottom tools" "")
("box" "")
("breaking" "")
("british" "")
("broken white" "")
("browse" "")
("browse back" "")
("browse forward" "")
("browse modules documentation" "")
("browse web" "")
("browser" "")
("buffer management" "")
("buffer must be on disk" "")
("buffer must have a name" "")
("build buffer" "")
("build buffer in" "")
("build directory" "")
("build directory in" "")
("build link pages" "")
("build-all" "")
("bulgarian" "")
("bullet" "")
("bullets" "")
("bump" "")
("busy" "")
("cJK" "")
("cJK spacing" "")
("calculus" "")
("cancel" "")
("cancelled" "")
("cannot download directory to file" "")
("cannot rename across different servers" "")
("cannot upload directory to file" "")
("caps-lock key" "")
("cartesian" "")
("carved wood" "")
("case" "")
("case-insensitive search" "")
("categories" "")
("category" "")
("cc" "")
("cell" "")
("cell background color" "")
("cell border" "")
("cell height" "")
("cell operation mode" "")
("cell properties" "")
("cell width" "")
("cells" "")
("center text" "")
("centered block" "")
("centered tabular" "")
("change border of cell" "")
("change cell operation mode" "")
("change default unit" "")
("change log" "")
("change passphrase" "")
("change step-size" "")
("change tags" "")
("change the TeXmacs preferences" "")
("change the border of the table" "")
("change the style of mathematical formulas" "")
("character contraction" "")
("character encoding" "")
("character expansion" "")
("check for updates" "")
("check text for spelling errors" "")
("checkable field" "")
("chinese" "")
("choice" "")
("cipher algorithm for passphrase encryption" "")
("circle" "")
("cite" "")
("classification" "")
("clean slate" "")
("clear all fields" "")
("clear local information" "")
("clear menu" "")
("clear selection" "")
("clear undo history" "")
("click Ok button twice to discard this warning" "")
("clip" "")
("clipboard image format" "")
("close animation tool" "")
("close document" "")
("close program" "")
("close replace tool" "")
("close search tool" "")
("close session" "")
("close spell tool" "")
("close translations to rebuild" "")
("closed bezier" "")
("closed curve" "")
("closed smooth" "")
("closed spline" "")
("closing" "")
("closing style" "")
("cluster by affiliation" "")
("code" "")
("collect garbage" "")
("collected keys" "")
("color of the axes" "")
("color of the subunits" "")
("color of the units" "")
("colors" "")
("column to the left" "")
("column to the right" "")
("columns" "")
("columns separation" "")
("commit file" "")
("common" "")
("common formats" "")
("commutative diagram" "")
("compact" "")
("compactification" "")
("compactify" "")
("compatibility with other formats" "")
("compile article" "")
("compile book" "")
("complete bibliographic reference" "")
("completion" "")
("complex" "")
("complex actions" "")
("compose" "")
("compound" "")
("compress" "")
("compress into toolbar" "")
("compressed" "")
("conceal" "")
("condition" "")
("configuration" "")
("configure look and feel" "")
("confirm database entry" "")
("confirm entry" "")
("confirm selected database entries" "")
("confirm selected entries" "")
("conservative conversion options" "")
("consoles" "")
("constellation" "")
("contact" "")
("content" "")
("content tag" "")
("context aids" "")
("context dependent icons" "")
("contextual hints" "")
("continuation of" "")
("continue" "")
("continued fraction" "")
("contour" "")
("contract logarithms" "")
("contribute" "")
("control flow" "")
("control the evaluation of expressions" "")
("convention" "")
("convert" "")
("converters" "")
("converters to other data formats" "")
("convertible" "")
("copy text" "")
("copy to" "")
("copyright" "")
("cork charset with TeX catcode definition in preamble" "")
("correct" "")
("correct all" "")
("correct formula" "")
("correct manually" "")
("correct mathematical formulas" "")
("correct text" "")
("correction" "")
("cosine" "")
("count characters" "")
("count lines" "")
("count words" "")
("create a new document" "")
("create link" "")
("create preamble" "")
("create remote directory" "")
("create remote file" "")
("create subprogram" "")
("create subsession" "")
("create table macro" "")
("create web site" "")
("creating new account" "")
("creating technical pictures" "")
("crop" "")
("crop marks" "")
("cross" "")
("crossed boxes" "")
("crossed circles" "")
("current user version" "")
("current version" "")
("cursor" "")
("curve" "")
("curve intersections" "")
("curve points" "")
("custom tab" "")
("customizations" "")
("customizing TeXmacs" "")
("customizing and extending the user interface" "")
("customizing the TeXmacs styles" "")
("custum tab" "")
("cut text" "")
("cut to" "")
("cyrillic input method" "")
("czech" "")
("danish" "")
("dark grey" "")
("dash" "")
("dashes" "")
("data" "")
("data conversion" "")
("data format" "")
("database entry" "")
("database tool" "")
("database toolbar" "")
("date" "")
("deactivate" "")
("deactivate once" "")
("deactivate table" "")
("dead" "")
("debug" "")
("debugging console" "")
("debugging tool" "")
("decimal comma" "")
("decimal dot" "")
("decomposed" "")
("decorate atoms" "")
("decorated" "")
("decorated wood" "")
("decrease size" "")
("decrypt" "")
("default padding" "")
("default size" "")
("degrade" "")
("degraded" "")
("delete column" "")
("delete documentation cache" "")
("delete entries" "")
("delete link" "")
("delete row" "")
("deleted" "")
("describe" "")
("describe tag" "")
("destination" "")
("destroy" "")
("detach master" "")
("detailed" "")
("detailed menus" "")
("details in menus" "")
("determinant" "")
("determine margins from text width" "")
("developer" "")
("developer tool" "")
("developers guide" "")
("device" "")
("diamond" "")
("differentiate" "")
("dilate" "")
("direction of progression" "")
("direction of translation" "")
("directory" "")
("disable" "")
("disable coloring on paper" "")
("disable encryption" "")
("disable first indentation" "")
("disable first indentation after" "")
("disable first indentation before" "")
("disallow" "")
("disappear" "")
("disk" "")
("display style" "")
("displayed formula" "")
("dissociate joined cells" "")
("distort" "")
("distorted" "")
("distribute unused space" "")
("div" "")
("division" "")
("do not remap" "")
("document font selector" "")
("document format" "")
("document language" "")
("document page format" "")
("document paragraph format" "")
("document updates run" "")
("documentation" "")
("documents are trees" "")
("dots" "")
("download" "")
("downwards" "")
("dragging" "")
("draw image" "")
("draw over" "")
("draw over selection" "")
("drop" "")
("due to" "")
("duplicate" "")
("dynamic" "")
("dynamic libraries" "")
("eRROR" "")
("edit animation" "")
("edit groups of objects" "")
("edit macro" "")
("edit macros" "")
("edit preamble" "")
("edit source" "")
("edit source tree" "")
("edit style" "")
("edit translations file" "")
("editing tools" "")
("education" "")
("effect pen" "")
("eigenvalues" "")
("eighth" "")
("email" "")
("embold" "")
("emboss" "")
("emphasize" "")
("emphasize text" "")
("enable first indentation" "")
("enable first indentation after" "")
("enable first indentation before" "")
("enable page breaking" "")
("encl" "")
("encoding" "")
("encrypt" "")
("encryption" "")
("encryption facilities are not currently available" "")
("encryption facilities have not been enabled for TeXmacs" "")
("enforce brackets to match" "")
("engrave" "")
("enter a title" "")
("enter data" "")
("enter graphics" "")
("enter graphics mode" "")
("enter new passphrase for encryption" "")
("enter passphrase for decryption" "")
("enter passphrase for identity" "")
("enter title information" "")
("entire table" "")
("entry up to date in database" "")
("enunciation" "")
("environment variable" "")
("environments" "")
("equal" "")
("equivalent for" "")
("erode" "")
("error messages" "")
("error output" "")
("error status report" "")
("error: bracket does not match" "")
("error: cyclic or missing chunks detected" "")
("error: file not found" "")
("error: ghostview does not seem to be installed on your system" "")
("error: one of the alternatives should be filled out" "")
("error: only one alternatives should be filled out" "")
("error: should fill out name for referencing" "")
("error: should fill out required field" "")
("esperanto" "")
("evaluable field" "")
("evaluate" "")
("evaluate above" "")
("evaluate all" "")
("evaluate below" "")
("evaluate fields" "")
("evaluate fields in order" "")
("evaluate script" "")
("evaluation" "")
("evaluation switch" "")
("evaluation tag" "")
("even page" "")
("even page footer" "")
("even page header" "")
("even page left margin" "")
("even page shift" "")
("even page text" "")
("even pages" "")
("events" "")
("exact" "")
("exact mode" "")
("exam" "")
("exclusive" "")
("exclusive or" "")
("executable" "")
("execution of scripts" "")
("exit graphics" "")
("exit graphics mode" "")
("exit left" "")
("exit right" "")
("exit tag on the left" "")
("exit tag on the right" "")
("expand" "")
("expand TeXmacs macros with no LaTeX equivalents" "")
("expand beamer slides" "")
("expand inclusions" "")
("expand logarithms" "")
("expand trigonometric functions" "")
("expand unrecognized macros" "")
("expand user-defined macros" "")
("expanded" "")
("experimental features (to be used with care)" "")
("explain" "")
("explained" "")
("explanatory item" "")
("explicit keystroke" "")
("explicit margins" "")
("exponential" "")
("export as" "")
("export bibliographies as links" "")
("export bibliography" "")
("export entries in buffer" "")
("export file" "")
("export formulas as images" "")
("export mathematical formulas as MathML" "")
("export mathematical formulas as images" "")
("export selected entries" "")
("export selection" "")
("export selection as image" "")
("export selections as" "")
("export sessions" "")
("exported bibliographic entries" "")
("exported bibliographic references" "")
("extend" "")
("extended" "")
("extensible left arrow" "")
("extensible right arrow" "")
("extern" "")
("extern " "")
("external" "")
("extra" "")
("extra branch" "")
("extra interline space" "")
("extra name" "")
("extract" "")
("extract format" "")
("extract style file" "")
("extract style package" "")
("factor" "")
("fade" "")
("fade in" "")
("fade out" "")
("fast" "")
("fast decrease" "")
("fast environments" "")
("fast increase" "")
("field reference" "")
("fifth" "")
("file saved" "")
("fill color" "")
("fill out" "")
("filter" "")
("find file" "")
("find next match" "")
("find text" "")
("finished collecting symbols documentation" "")
("finnish" "")
("first" "")
("first chunk" "")
("first contact" "")
("first difference" "")
("first error" "")
("first field" "")
("first occurrence" "")
("first similar" "")
("first start" "")
("fit to screen" "")
("fit to screen width" "")
("five columns" "")
("fixed" "")
("flag is off" "")
("flag is on" "")
("flatten" "")
("flexibility" "")
("flexibility factor for vertical spacing" "")
("floating algorithm" "")
("floating figure" "")
("floating object" "")
("floating phantom" "")
("floating table" "")
("focus" "")
("focus dependent icons" "")
("fold" "")
("fold all" "")
("fold all fields" "")
("fold back" "")
("fold input field" "")
("folded" "")
("follow external links" "")
("follow inverse links" "")
("font effects" "")
("font name" "")
("font selector" "")
("font type" "")
("font variant" "")
("fonts" "")
("footer" "")
("footnote" "")
("for" "")
("for each" "")
("force reloading of translations" "")
("foreground" "")
("format" "")
("formatted and structured output" "")
("formatted date" "")
("formatting" "")
("forward" "")
("forward replace" "")
("forward search" "")
("four columns" "")
("four dots" "")
("fourth" "")
("fraktur" "")
("framed" "")
("from" "")
("from center" "")
("front matter" "")
("full" "")
("full author list" "")
("full manuals" "")
("full screen mode" "")
("functional" "")
("further customization" "")
("gNU TeXmacs comes without any form of legal warranty" "")
("gNU TeXmacs falls under the GNU general public license" "")
("gap" "")
("garbage collection" "")
("gaussian" "")
("gcd" "")
("general" "")
("general architecture of TeXmacs" "")
("general note" "")
("generated LaTeX document contains no errors" "")
("generated field" "")
("generating font file" "")
("generic" "")
("geometry" "")
("get arity" "")
("get label" "")
("get list with remote versions" "")
("glossary entry" "")
("glue decorations" "")
("glyphs" "")
("gnaw" "")
("gnawed" "")
("gnuPG command" "")
("gnuPG error: buffer encryption failed" "")
("gnuPG error: cannot find suitable secret key to decrypt" "")
("gnuPG requires name and email to have at least 5 characters" "")
("go" "")
("go to anchor" "")
("go to anchor or float" "")
("go to anchor or footnote" "")
("go to first similar tag" "")
("go to float" "")
("go to footnote" "")
("go to last similar tag" "")
("go to next similar tag" "")
("go to previous similar tag" "")
("go to section" "")
("grain" "")
("granite" "")
("graphical effects" "")
("graphical interface font scale" "")
("graphics" "")
("graphics geometry" "")
("graphics grids" "")
("greater" "")
("greater or equal" "")
("greyed" "")
("grid" "")
("grid curves" "")
("grid points" "")
("grid-curve intersections" "")
("group of objects" "")
("group/ungroup" "")
("grouped" "")
("guarantee transparent source tracking" "")
("h modifier" "")
("half wide" "")
("hand drawn" "")
("happy typing" "")
("has been aborted" "")
("has completed its task" "")
("header" "")
("header and footer" "")
("headers" "")
("height is exactly the specified height" "")
("height is maximum of specified height and box height" "")
("height is minimum of specified height and box height" "")
("help us" "")
("here" "")
("hidden" "")
("history" "")
("home" "")
("homepage" "")
("homoglyph substitutions" "")
("horizontal" "")
("horizontal alignment" "")
("horizontal cell alignment" "")
("horizontal collapse distance" "")
("horizontal margins" "")
("horizontal part" "")
("horizontal table alignment" "")
("horizontally align cell to the base" "")
("horizontally center the cell" "")
("how much longer may pages become" "")
("how much shorter may pages become" "")
("hungarian" "")
("hybrid command" "")
("hyphenate as" "")
("icon" "")
("if" "")
("if hyphenated" "")
("ignore" "")
("image links" "")
("impact" "")
("import bibliography" "")
("import database entry" "")
("import entries in buffer" "")
("import entry" "")
("import file" "")
("import selected database entries" "")
("import selected entries" "")
("import selections as" "")
("import sessions" "")
("import sophisticated objects as pictures" "")
("imported bibliographic entries" "")
("improving the current implementation" "")
("in popup windows" "")
("inanimated" "")
("inch" "")
("include" "")
("include a document" "")
("include file" "")
("inclusion into TeXmacs" "")
("inclusions" "")
("incomplete entries found to be filled out" "")
("increase size" "")
("indent paragraphs" "")
("indentation" "")
("index entry" "")
("indication" "")
("informative flags" "")
("initialize" "")
("ink here" "")
("ink in" "")
("ink out" "")
("inline" "")
("inline arguments" "")
("inline code" "")
("inline content" "")
("inline formula" "")
("inner bottom" "")
("inner left" "")
("inner right" "")
("inner top" "")
("input command" "")
("input field" "")
("input mode" "")
("input options" "")
("insert a big operator" "")
("insert a binary operation" "")
("insert a binary relation" "")
("insert a blackboard bold character" "")
("insert a bold calligraphic character" "")
("insert a bold character" "")
("insert a calligraphic character" "")
("insert a computer program" "")
("insert a condition" "")
("insert a control flow instruction" "")
("insert a fraction" "")
("insert a fraktur character" "")
("insert a gap" "")
("insert a greek character" "")
("insert a large left delimiter" "")
("insert a large right delimiter" "")
("insert a large separator" "")
("insert a link" "")
("insert a list" "")
("insert a miscellaneous symbol" "")
("insert a multiple choice" "")
("insert a negation" "")
("insert a new entry" "")
("insert a new item" "")
("insert a note or a floating object" "")
("insert a numerical operation" "")
("insert a picture" "")
("insert a prominent piece of text" "")
("insert a question" "")
("insert a root" "")
("insert a script" "")
("insert a section block" "")
("insert a square root" "")
("insert a table" "")
("insert a table or a matrix" "")
("insert a textual operation" "")
("insert a textual operator" "")
("insert a wide symbol above" "")
("insert a wide symbol below" "")
("insert above" "")
("insert abstract" "")
("insert an" "")
("insert an accent" "")
("insert an answer" "")
("insert an arrow" "")
("insert an enunciation" "")
("insert an environment" "")
("insert an n" "")
("insert an operation on tuples" "")
("insert annotation" "")
("insert author" "")
("insert automatically generated content" "")
("insert below" "")
("insert column" "")
("insert column to the left" "")
("insert column to the right" "")
("insert copyright and license information" "")
("insert executable markup" "")
("insert explanatory item" "")
("insert field above" "")
("insert field below" "")
("insert fields" "")
("insert footnote" "")
("insert image" "")
("insert inactive markup" "")
("insert input field above" "")
("insert input field below" "")
("insert large delimiters" "")
("insert last name" "")
("insert left" "")
("insert macro" "")
("insert mathematics" "")
("insert missing invisible operators" "")
("insert more names" "")
("insert new rows or columns" "")
("insert or delete rows or columns" "")
("insert particle" "")
("insert plain text" "")
("insert right" "")
("insert row" "")
("insert row above" "")
("insert row below" "")
("insert similar above" "")
("insert similar below" "")
("insert similar block above" "")
("insert similar block below" "")
("insert structural markup" "")
("insert subtable" "")
("insert symbol documentation" "")
("insert template" "")
("insert text field" "")
("insert text field above" "")
("insert text field below" "")
("insert title" "")
("insert title after name" "")
("insert user interface related markup" "")
("insert value" "")
("inserting control points" "")
("integrate" "")
("interactive command" "")
("interactive questions" "")
("intercharacter compression" "")
("intercharacter stretching" "")
("interfacing" "")
("interfacing TeXmacs with other systems" "")
("interjection" "")
("interline separation" "")
("internationalization" "")
("interrupt execution" "")
("interrupted" "")
("invalid multi-paragraph selection" "")
("invalid renaming" "")
("invert" "")
("inverted breve" "")
("invisible" "")
("invisible ending" "")
("invisible newline" "")
("invisible opening" "")
("is running" "")
("is tuple" "")
("ispell does not respond" "")
("ispell is already busy" "")
("italian" "")
("japanese" "")
("join selected cells" "")
("jump in" "")
("junior" "")
("justify text" "")
("keep evaluated expressions" "")
("keep local" "")
("keep remote" "")
("keep track of source code" "")
("keep unfolded" "")
("key" "")
("keyboard configuration" "")
("keyboard equivalent" "")
("keyboard modifiers" "")
("keyboard shortcut" "")
("keyword" "")
("keywords" "")
("laptop presentations" "")
("large cells" "")
("large displayed" "")
("large displayed fraction" "")
("large tables" "")
("last" "")
("last difference" "")
("last error" "")
("last field" "")
("last name" "")
("last occurrence" "")
("last similar" "")
("lcm" "")
("left arrow" "")
("left axis" "")
("left baseline" "")
("left bottom" "")
("left cell border" "")
("left cell padding" "")
("left center" "")
("left click: add point; Right click: undo" "")
("left click: finish; Right click: undo" "")
("left click: new object" "")
("left click: operate" "")
("left down" "")
("left on even pages" "")
("left padding" "")
("left prime" "")
("left surrounding" "")
("left table border" "")
("left table padding" "")
("left top" "")
("left up" "")
("left-right arrow" "")
("leftwards" "")
("length" "")
("less" "")
("less or equal" "")
("let the environment float" "")
("light grey" "")
("limits" "")
("line breaking" "")
("line wrapping" "")
("linear 2D" "")
("linear algebra" "")
("lines around" "")
("link image" "")
("link image and copies as" "")
("link image as" "")
("link mode" "")
("link to URL" "")
("linking tool" "")
("live" "")
("live input-output" "")
("load a file" "")
("load buffer" "")
("load file" "")
("load help file" "")
("load image" "")
("load remote file" "")
("loading" "")
("local entries" "")
("loci" "")
("locus" "")
("locus rendering" "")
("logarithm" "")
("logarithmic" "")
("logarithmic base" "")
("logarithms" "")
("logging in" "")
("logical and" "")
("logical implication" "")
("logical not" "")
("logical or" "")
("login" "")
("logout" "")
("long macro" "")
("long text" "")
("look and feel" "")
("look for more fonts" "")
("look up" "")
("loops" "")
("m modifier" "")
("macro" "")
("macro argument" "")
("macro definition" "")
("macro name" "")
("macros" "")
("magnify horizontally" "")
("magnify vertically" "")
("main" "")
("main icon bar" "")
("main presentation style" "")
("major changes" "")
("make a letter environment" "")
("make a multi-slide presentation" "")
("make a page insertion" "")
("make a subscript" "")
("make a superscript" "")
("make floating" "")
("make link" "")
("make non floating" "")
("make page reference" "")
("making donations" "")
("manila paper" "")
("manual" "")
("map arguments" "")
("map to" "")
("marginal note" "")
("margins as on paper" "")
("margins from width" "")
("margins on paper" "")
("margins on screen" "")
("marked" "")
("master" "")
("master file" "")
("material" "")
("mathematical and customized input" "")
("mathematical font" "")
("mathematical formulas" "")
("mathematical input" "")
("mathematical output" "")
("mathematical typesetting" "")
("matrices" "")
("maximal" "")
("maximal cell height" "")
("maximal clustering" "")
("maximal number of columns" "")
("maximal number of rows" "")
("maximal table height" "")
("maximal table width" "")
("maximum" "")
("maximum mode" "")
("meander" "")
("memory" "")
("memory usage" "")
("menu" "")
("merge" "")
("merge lines into paragraphs unless separated by blank lines" "")
("messages" "")
("meta data" "")
("meta key" "")
("metadata" "")
("metal" "")
("middle baseline" "")
("minimal" "")
("minimal cell height" "")
("minimal cell width" "")
("minimal line separation" "")
("minimal number of columns" "")
("minimal number of rows" "")
("minimal table height" "")
("minimal table width" "")
("minimum" "")
("minimum mode" "")
("mirror" "")
("miscellaneous features" "")
("miscellanous" "")
("mod" "")
("mode dependent icons" "")
("modifier" "")
("modify cell alignment" "")
("modify cell border" "")
("modify cell padding" "")
("modify cell size" "")
("modify remote live document" "")
("modify table border" "")
("modify table padding" "")
("module" "")
("monospaced" "")
("more information about GNU TeXmacs can be found in the Help" "")
("more information about GNU TeXmacs can be found in the Help->About menu" "")
("more information about GNU TeXmacs can be found in the help" "")
("motion" "")
("mouse over object" "")
("move" "")
("move objects" "")
("move over object on which to operate" "")
("multiline" "")
("multiline input" "")
("multiple choice" "")
("multiple root" "")
("multiplication" "")
("mutator tags" "")
("my documents" "")
("navigation options" "")
("never" "")
("new account" "")
("new bibliography dialogue" "")
("new buffer" "")
("new document" "")
("new double page" "")
("new double page before" "")
("new entry" "")
("new identity" "")
("new locus" "")
("new macro" "")
("new page before" "")
("new passphrase" "")
("new remote directory" "")
("new remote file" "")
("new style fonts" "")
("new style page breaking" "")
("new version" "")
("new window" "")
("newer version" "")
("next" "")
("next chunk" "")
("next difference" "")
("next error" "")
("next field" "")
("next occurrence" "")
("next screen" "")
("next similar" "")
("no clustering" "")
("no completions" "")
("no dictionary for" "")
("no errors have been corrected" "")
("no grid" "")
("no indentation" "")
("no matches found" "")
("no matches found for" "")
("no more matches for" "")
("no more redo information available" "")
("no more undo information available" "")
("no new public key in document" "")
("no page break" "")
("no page numbers" "")
("no parent" "")
("no selection" "")
("no spelling errors" "")
("no spelling errors found in text" "")
("no style" "")
("normal loci" "")
("norwegian" "")
("not" "")
("not allowed to remove home directory" "")
("not connected to server" "")
("not equal" "")
("not yet implemented" "")
("notation" "")
("notebook" "")
("number" "")
("number equation" "")
("number of columns" "")
("number of polar steps" "")
("number of subunit steps" "")
("numbering" "")
("numeric spreadsheet" "")
("occurrences" "")
("odd page" "")
("odd page footer" "")
("odd page header" "")
("odd page left margin" "")
("odd page right margin" "")
("odd page shift" "")
("odd page text" "")
("odd pages" "")
("of fingerprint" "")
("ok" "")
("old style" "")
("old version" "")
("older version" "")
("on cells" "")
("on columns" "")
("on entire table" "")
("on rows" "")
("on the footer" "")
("on your system and set it up from the \"Security\" tab" "")
("one column" "")
("one error has been corrected" "")
("one lower case letter, one non alpha-numeric symbol" "")
("one numeric character, one upper case letter" "")
("one spelling error has been corrected" "")
("online documentation" "")
("online help" "")
("only convert changes when re-importing" "")
("only convert changes with respect to imported version" "")
("only convert changes with respect to tracked version" "")
("only implemented for complete subtrees" "")
("only inline tags" "")
("only keep folded" "")
("only keep unfolded" "")
("only show semantic focus" "")
("opacity" "")
("open" "")
("open a new buffer" "")
("open bibliography" "")
("open identities" "")
("open in new window" "")
("open key manager" "")
("open licence agreement" "")
("open mailbox" "")
("open module browser" "")
("open symbol browser" "")
("open tool in separate window" "")
("opening" "")
("operation mode" "")
("operation on named selection" "")
("operation on primary selection" "")
("operation on secondary selection" "")
("operation on ternary selection" "")
("or" "")
("or give the complete path to the \"gpg\" or \"gpg2\" command" "")
("order" "")
("ordinary symbol" "")
("origin" "")
("original welcome message" "")
("ornamented" "")
("other login" "")
("other package" "")
("other pages" "")
("other style" "")
("outer bottom" "")
("outer left" "")
("outer right" "")
("outer top" "")
("outline" "")
("outlined" "")
("outlined emboss" "")
("outlined engrave" "")
("output options" "")
("oval" "")
("over" "")
("overbrace" "")
("overlap" "")
("overlay" "")
("overlays" "")
("overline" "")
("overlined" "")
("overview of the scheme extension language" "")
("padded" "")
("padding" "")
("page background" "")
("page break after" "")
("page break before" "")
("page breaking algorithm" "")
("page insertion" "")
("page number" "")
("page number rendering" "")
("page number text" "")
("page numbering" "")
("page reference" "")
("page rendering" "")
("page setup" "")
("palette" "")
("panorama" "")
("paragraphs" "")
("parametric curve" "")
("parametric surface" "")
("parenthesis" "")
("parenthesized" "")
("particle" "")
("passphrase encryption" "")
("passphrase wallet facilities are not currently available" "")
("passphrases are expected to have at least: 8 characters" "")
("passphrases mismatch" "")
("paste from" "")
("paste text" "")
("pastel" "")
("pattern" "")
("pause" "")
("pen width" "")
("perform operations on cells" "")
("perform operations on columns" "")
("perform operations on entire table" "")
("perform operations on rows" "")
("permanent" "")
("permanent footer" "")
("permanent header" "")
("permanently add to dictionary" "")
("permanently insert into dictionary" "")
("permissions" "")
("person" "")
("personal dictionary has been modified" "")
("phantom" "")
("phantoms" "")
("philosophy" "")
("physics and astronomy class" "")
("picture" "")
("pine" "")
("plain" "")
("plain block" "")
("plain boxes" "")
("plain circles" "")
("plain tabular" "")
("planned changes" "")
("plans for the future" "")
("play" "")
("play animation" "")
("please install GnuPG software from https://www.gnupg.org" "")
("please wait" "")
("plot" "")
("plug-ins" "")
("plugin" "")
("plugins" "")
("plural" "")
("plus" "")
("point" "")
("polar" "")
("polish" "")
("polygon" "")
("pop server settings" "")
("porting TeXmacs to other platforms" "")
("portuguese" "")
("position float" "")
("position floating object" "")
("position of marginal note" "")
("position the table" "")
("poster formats" "")
("poster theme" "")
("postfix" "")
("preamble mode" "")
("preferences" "")
("preferences for editing mathematical formulas" "")
("preferences for tag" "")
("prefix" "")
("presentation" "")
("presentation mode" "")
("presentation tag" "")
("presentation tool" "")
("preserve" "")
("preserve tags" "")
("pretty tree output" "")
("preview" "")
("preview command" "")
("previous" "")
("previous difference" "")
("previous error" "")
("previous field" "")
("previous occurrence" "")
("previous screen" "")
("previous similar" "")
("primary" "")
("prime" "")
("primitive or macro" "")
("print buffer" "")
("print buffer to file" "")
("print to file" "")
("printer" "")
("printer setup" "")
("problem" "")
("program bracket matching" "")
("program bracket selections" "")
("program commands" "")
("program font" "")
("program interface for buffer management" "")
("programming" "")
("programming routines for editing documents" "")
("progressive" "")
("prominent" "")
("prompt on scripts" "")
("prompts and default input" "")
("proportional" "")
("provoke C++ error" "")
("provoke menu error" "")
("provoke scheme error" "")
("pseudo code" "")
("public key encryption" "")
("public keys" "")
("pulse" "")
("qt GUI only, sorry. Use \"Export selection\"" "")
("qt-widgets" "")
("quantifier" "")
("quasi" "")
("query replace" "")
("question" "")
("questions only" "")
("questions with answers" "")
("quick evaluation of formulas" "")
("range" "")
("rank" "")
("raw" "")
("really close it" "")
("really delete user identity" "")
("really tiny" "")
("rebuild translations file" "")
("recent" "")
("recent documents" "")
("recipients" "")
("recognize" "")
("recover autosave file" "")
("rectangular" "")
("redo" "")
("redo undone changes" "")
("reduce" "")
("reduce trigonometric functions" "")
("reduced margins" "")
("reference guide" "")
("reference guide for the TeXmacs primitives" "")
("reference guide for the standard TeXmacs styles" "")
("regenerate" "")
("register file" "")
("regular" "")
("relate" "")
("relation" "")
("release left button: finish editing" "")
("reload" "")
("remote" "")
("remote connections" "")
("remote control" "")
("remote controllers with keyboard simulation" "")
("remote directory" "")
("remote servers" "")
("remote tool" "")
("remove" "")
("remove all output fields" "")
("remove banner" "")
("remove database entry" "")
("remove downwards" "")
("remove entries" "")
("remove entry" "")
("remove field above" "")
("remove field below" "")
("remove fields" "")
("remove folded" "")
("remove input field" "")
("remove input field above" "")
("remove last field" "")
("remove leftwards" "")
("remove link" "")
("remove next field" "")
("remove number" "")
("remove package" "")
("remove previous field" "")
("remove rightwards" "")
("remove selected database entries" "")
("remove selected entries" "")
("remove superfluous invisible operators" "")
("remove tag" "")
("remove this branch" "")
("remove this switch" "")
("remove unfolded" "")
("remove upwards" "")
("removed entries from database" "")
("removed entry from database" "")
("rename" "")
("rename section" "")
("renumber this page" "")
("repeat" "")
("repeat object" "")
("replace" "")
("replace TeXmacs styles with no LaTeX equivalents" "")
("replace all further occurrences" "")
("replace by" "")
("replace one occurrence" "")
("replace toolbar" "")
("replace unrecognized styles" "")
("replaced" "")
("replaced one occurrence" "")
("reset error counters" "")
("resize" "")
("resize objects" "")
("restart TeXmacs in order to let changes take effect" "")
("restart in order to let the new look and feel take effect" "")
("retain" "")
("retime" "")
("retina settings" "")
("retrieve email" "")
("retrieve remote live document" "")
("retrieved contents" "")
("reverse" "")
("reverse ordering" "")
("revert" "")
("ridged paper" "")
("right arrow" "")
("right baseline" "")
("right cell border" "")
("right cell padding" "")
("right down" "")
("right on even pages" "")
("right padding" "")
("right surrounding" "")
("right table border" "")
("right table padding" "")
("right up" "")
("rightwards" "")
("rigid box" "")
("rotate" "")
("rotate backward" "")
("rotate forward" "")
("rotate objects" "")
("rough" "")
("rough paper" "")
("round" "")
("round overbrace" "")
("round underbrace" "")
("row above" "")
("row below" "")
("rows" "")
("run" "")
("run current file" "")
("running author" "")
("running title" "")
("russian" "")
("same names" "")
("same screen margins as on paper" "")
("sample" "")
("sample text" "")
("save auxiliary data" "")
("save buffer" "")
("save buffer as" "")
("save entries" "")
("save entry" "")
("save file" "")
("save image" "")
("save image as" "")
("save position" "")
("save remote file" "")
("save this buffer" "")
("saved modifications in database" "")
("scheme command" "")
("scheme developers guide" "")
("scheme extensions" "")
("scheme interface for the graphical mode" "")
("screen" "")
("screen rendering" "")
("screens" "")
("screenshot" "")
("scripting language" "")
("scripts" "")
("scripts not accepted" "")
("search" "")
("search and replace" "")
("search results for" "")
("search toolbar" "")
("search words in my documents" "")
("search words in the documentation" "")
("search words in the source code" "")
("searching" "")
("second" "")
("secondary" "")
("secret keys" "")
("sections" "")
("security" "")
("see" "")
("see documentation" "")
("select a document style" "")
("select a foreground color" "")
("select a language" "")
("select pen" "")
("select the action to be undertaken for each conflict" "")
("select view mode" "")
("selections" "")
("semantic correctness" "")
("semantic editing" "")
("semantic selections" "")
("semantics" "")
("sending commands to TeXmacs" "")
("senior" "")
("serb" "")
("serif" "")
("server" "")
("session commands" "")
("session name" "")
("session type" "")
("sessions" "")
("set background color of cell" "")
("set cell mode" "")
("set default" "")
("set difference" "")
("set extension center" "")
("set height" "")
("set height of cell" "")
("set intersection" "")
("set number of columns" "")
("set number of rows" "")
("set or get environment variables" "")
("set paragraph margins" "")
("set paragraph mode" "")
("set properties" "")
("set span" "")
("set special cell properties" "")
("set special table properties" "")
("set union" "")
("set user information" "")
("set width" "")
("set width of cell" "")
("settings" "")
("seventh" "")
("several equations" "")
("shadow" "")
("shadowed" "")
("shadowed raise" "")
("shift" "")
("short" "")
("show" "")
("show all parts" "")
("show current focus" "")
("show full context" "")
("show hidden" "")
("show key presses" "")
("show main document" "")
("show memory usage" "")
("show on screen" "")
("show one part" "")
("show panorama" "")
("show preamble" "")
("show several parts" "")
("show subunits" "")
("show table cells" "")
("show timings" "")
("side tools" "")
("signature" "")
("simple" "")
("simplification" "")
("simplified evaluation of formulas" "")
("simplified menus" "")
("simplify" "")
("sine" "")
("sixth" "")
("size limits" "")
("size tag" "")
("skew" "")
("skip all" "")
("slant" "")
("slashed fraction" "")
("slides" "")
("sloppy" "")
("slovene" "")
("slow" "")
("slow decrease" "")
("slow increase" "")
("small capitals" "")
("small environment box" "")
("small figure" "")
("small focus" "")
("small inline" "")
("small inline fraction" "")
("small table" "")
("smash" "")
("smooth" "")
("smooth end" "")
("smooth extremities" "")
("smooth start" "")
("snap" "")
("snap distance" "")
("snap to curves" "")
("snap to grid" "")
("snap to grid curve" "")
("snap to intersections of curves" "")
("snap to text borders" "")
("snap to text corners" "")
("solution" "")
("solution to exercise" "")
("solution to problem" "")
("solutions" "")
("sound" "")
("source" "")
("source code" "")
("source macros tool" "")
("source tags" "")
("south" "")
("south east" "")
("space bar in math mode" "")
("space bar in text mode" "")
("space between lines" "")
("space between paragraphs" "")
("space stretchability" "")
("span" "")
("span over all columns" "")
("spanish" "")
("special cell properties" "")
("special functions" "")
("special properties" "")
("special table properties" "")
("specific baseline" "")
("specify color alternation" "")
("specify how to traverse the manual" "")
("specify semantics of a symbol or formula" "")
("specify the size of the table" "")
("spell" "")
("spell check" "")
("spell checking complete" "")
("spelling error" "")
("spelling errors have been corrected" "")
("spline" "")
("split program" "")
("split session" "")
("square" "")
("square overbrace" "")
("square underbrace" "")
("stack" "")
("standard" "")
("standard Output" "")
("standard TeXmacs styles" "")
("standard environment variables" "")
("standard formats" "")
("standard fraction" "")
("star" "")
("start a new chapter" "")
("start a new section" "")
("start an interactive session" "")
("start server" "")
("statement" "")
("statistics" "")
("status" "")
("status bar" "")
("stop server" "")
("storage" "")
("store tracking information in LaTeX files" "")
("stretch" "")
("stretch factor" "")
("stretched" "")
("strict Ascii" "")
("strike through" "")
("stroke" "")
("strokes" "")
("strong" "")
("structural" "")
("structured insert above" "")
("structured insert at the left" "")
("structured insert at the right" "")
("structured insert below" "")
("structured remove downwards" "")
("structured remove leftwards" "")
("structured remove rightwards" "")
("structured remove upwards" "")
("structured variant" "")
("style options" "")
("style parameters" "")
("stylesheet language" "")
("sub" "")
("subject" "")
("submenu" "")
("subparagraph" "")
("subscript below" "")
("subsub" "")
("subsubmenu" "")
("subsubsubmenu" "")
("subsubsubsubmenu" "")
("subtable" "")
("subtitle" "")
("subtraction" "")
("summarized" "")
("summary" "")
("summary of the principal TeXmacs tags" "")
("superpose" "")
("superposed" "")
("superscript above" "")
("supported plug-ins" "")
("surface" "")
("swell" "")
("swiss" "")
("switch" "")
("switch to buffer" "")
("switch to first" "")
("switch to last" "")
("switch to next" "")
("switch to previous" "")
("switching and folding" "")
("symbol properties not found" "")
("symbols" "")
("synchronize" "")
("synchronize bibliographic references" "")
("synchronize with remote server" "")
("synopsis" "")
("system command" "")
("system environment variables" "")
("tab-completion" "")
("tabbed" "")
("table breaking" "")
("table command" "")
("table height" "")
("table properties" "")
("table width" "")
("tables" "")
("tabular material" "")
("tags with special rendering" "")
("tangent" "")
("teXmacs DTD" "")
("teXmacs as an interface" "")
("teXmacs buffer expected" "")
("teXmacs buffer on disk expected" "")
("teXmacs extensions to scheme and utilities" "")
("teXmacs fonts" "")
("teXmacs macro" "")
("teXmacs notice" "")
("teXmacs package" "")
("teXmacs plugins" "")
("teXmacs primitives" "")
("teXmacs style" "")
("teXmacs style files" "")
("ternary" "")
("test routine" "")
("testing tree-view" "")
("text borders" "")
("text box style" "")
("text corners" "")
("text height correction" "")
("texts" "")
("textual" "")
("textual operator" "")
("textual spreadsheet" "")
("the TeXmacs authors" "")
("the TeXmacs format" "")
("the TeXmacs plug-in system" "")
("the application did not send its usual startup banner" "")
("the application does not reply" "")
("the application is already running" "")
("the boxes produced by the typesetter" "")
("the document has not been saved" "")
("the graphical user interface" "")
("the leaves of TeXmacs trees" "")
("the mycas example" "")
("the primitive TeXmacs constructs" "")
("the standard TeXmacs styles" "")
("theme parameters" "")
("these collected public keys will be definitely lost" "")
("these public keys will be definitely lost" "")
("these secret keys will be definitely lost" "")
("thicken" "")
("third" "")
("this" "")
("this column" "")
("this document has been produced using" "")
("this document has not been saved" "")
("this page" "")
("this page footer" "")
("this page header" "")
("this page number" "")
("this row" "")
("this style specifies page margins in the TeX way" "")
("three columns" "")
("three dots" "")
("through popup windows" "")
("through the menus" "")
("thumbnails" "")
("time evolution" "")
("times" "")
("timings" "")
("title presentation options" "")
("title style" "")
("title suffix" "")
("titled block" "")
("to the left" "")
("to the right" "")
("today" "")
("toggle cell wrapping mode" "")
("toggle here" "")
("toggle off" "")
("toggle on" "")
("tolerant" "")
("tools" "")
("top baseline" "")
("top border" "")
("top cell border" "")
("top cell padding" "")
("top padding" "")
("top table border" "")
("top table padding" "")
("transform" "")
("transform cell into subtable" "")
("translate" "")
("translations" "")
("translations loaded" "")
("transpose" "")
("traversal" "")
("traverse" "")
("triangle" "")
("triangularize" "")
("trigonometric" "")
("trigonometry" "")
("tuple" "")
("turn off" "")
("turn on" "")
("tutorial" "")
("two columns" "")
("two dots" "")
("type a latex command followed by return" "")
("typesetted boxes" "")
("typing a simple text" "")
("typing simple texts" "")
("ukrainian" "")
("underbrace" "")
("underline" "")
("underlined" "")
("undo last changes" "")
("unevaluated argument" "")
("unevaluated value" "")
("unfold" "")
("unfold all" "")
("unfold all fields" "")
("unit" "")
("unit length" "")
("unknown secret key fingerprint" "")
("unregistered file" "")
("unroll" "")
("unsecure script refused" "")
("unsupported link mode" "")
("until" "")
("untitled block" "")
("up to date" "")
("update buffer" "")
("update from web" "")
("update image links" "")
("update this buffer" "")
("update web site" "")
("upight" "")
("upload" "")
("upright" "")
("upwards" "")
("use CSS for more advanced formatting" "")
("use MathML" "")
("use TeXmacs" "")
("use a bold font" "")
("use a calligraphic font" "")
("use a sans serif font" "")
("use a typewriter font" "")
("use as master" "")
("use calligraphical font" "")
("use extensible brackets" "")
("use left hand column as border" "")
("use line wrapping for lines which are longer than 80 characters" "")
("use margin kerning (protrusion)" "")
("use paragraph width" "")
("use protrusion" "")
("use relative path" "")
("use right hand column as border" "")
("use row above as border" "")
("use row below as border" "")
("use small capitals" "")
("use the blackboard bold font" "")
("use the fraktur font" "")
("user interface" "")
("user interface language" "")
("user manual" "")
("user preferences" "")
("user provided icons" "")
("users of Cyrillic languages" "")
("users of oriental languages" "")
("utf-8 with inputenc LaTeX package" "")
("utilities" "")
("value" "")
("vanish" "")
("variable" "")
("variant" "")
("verbose" "")
("version" "")
("versioning tool" "")
("vertical" "")
("vertical alignment" "")
("vertical cell alignment" "")
("vertical margins" "")
("vertical part" "")
("vertical space after" "")
("vertical space before" "")
("vertical space stretchability" "")
("vertical table alignment" "")
("vertically align cell to the base" "")
("vertically center the cell" "")
("view" "")
("visible" "")
("visible except here" "")
("visible from here on" "")
("visible only here" "")
("visible until here" "")
("visited loci" "")
("wallet" "")
("wave" "")
("web" "")
("weight" "")
("welcome to GNU TeXmacs" "")
("what is new" "")
("when line wrapping" "")
("while" "")
("whitespace" "")
("wide" "")
("wide bar" "")
("wide block" "")
("wide colored" "")
("wide float" "")
("wide footnote" "")
("wide tabular" "")
("widescreen" "")
("width is exactly the specified width" "")
("width is maximum of specified width and box width" "")
("width is minimum of specified width and box width" "")
("window" "")
("windows key" "")
("with" "")
("wrap lines" "")
("write a macro" "")
("write a name" "")
("write bold mathematics" "")
("write bold text" "")
("write italic text" "")
("write sample text" "")
("write strong text" "")
("write typewriter text" "")
("write verbatim text" "")
("writing TeXmacs bibliography styles" "")
("writing data converters" "")
("writing documentation" "")
("writing your own style files" "")
("written with TeXmacs" "")
("wrong empty passphrase" "")
("wrong passphrase" "")
("year" "")
("you are attempting to open an encrypted file while" "")
("you might consider enabling the experimental" "")
("you must add a bibliography file" "")
("you should also make sure that GnuPG is installed" "")
("your document is back in its original state" "")
("your first interface" "")
("your language" "")
("your personal dictionary has been modified" "")
("zoom" "")
("zoom in" "")
("zoom out" "")
