("\"encryption\" features from the preference panel" "\"crittografia\" funzioni dal pannello delle preferenze")
("(Re)Build autocompletion index" "(Ri) Crea indice di completamento automatico")
("a modifier" "un modificatore")
("a series" "una serie")
("a.C.M. computing class" "classe informatica a.C.M.")
("a.M.S. subject class" "a.M.S. class class")
("abbreviated authors" "autori abbreviati")
("abreviated authors" "autori abbreviati")
("accent above" "accento sopra")
("accent below" "accento sotto")
("accept during this pass" "accetta durante questo passaggio")
("acknowledgments" "riconoscimenti")
("activate hidden" "attiva nascosto")
("activate once" "attiva una volta")
("activation" "attivazione")
("active link types" "tipi di link attivi")
("add" "aggiungi")
("add abstract information" "aggiungi informazioni astratte")
("add author information" "aggiungi informazioni sull'autore")
("add branch after" "aggiungi ramo dopo")
("add branch before" "aggiungi ramo prima")
("add other package" "aggiungi altro pacchetto")
("add package" "aggiungi pacchetto")
("add style package" "aggiungi pacchetto stile")
("add title information" "aggiungi informazioni sul titolo")
("addition" "aggiunta")
("adjust" "regola")
("adjust limits" "regola i limiti")
("advanced font customization" "personalizzazione avanzata dei caratteri")
("affiliation" "affiliazione")
("align cell to the decimal comma" "allinea la cella alla virgola decimale")
("align cell to the decimal dot" "allinea la cella al punto decimale")
("align table at axis" "allinea tabella all'asse")
("aligned" "allineato")
("alignment of balloon" "allineamento del palloncino")
("all cells" "tutte le celle")
("all data attached to this identity will be lost" "Tutti i dati allegati a questa identità andranno persi")
("all saved passphrases will be lost forever" "Tutte le passphrase salvate andranno perse per sempre")
("allow for macro definitions in preamble" "consenti macro definizioni nel preambolo")
("allow multiple spaces" "consenti più spazi")
("allow spurious spaces" "consenti spazi spuri")
("allowed page height extension" "estensione altezza pagina consentita")
("allowed page height reduction" "riduzione altezza pagina consentita")
("allowed positions" "posizioni consentite")
("allowed positions of floating object" "posizioni consentite dell'oggetto galleggiante")
("alpha transparency" "trasparenza alfa")
("also on paper" "anche su carta")
("alter" "alter")
("alternate" "alternativo")
("alternate except here" "alternativo tranne qui")
("alternate from here on" "alternato da qui in poi")
("alternate only here" "alterna solo qui")
("alternate until here" "alterna fino a qui")
("alternative colors" "colori alternativi")
("alternative specification" "specifica alternativa")
("always" "sempre")
("american" "americano")
("amplified" "amplificato")
("ancient" "antico")
("and perform casual settings from the \"Encryption\" tab" "ed esegui impostazioni casuali dalla scheda \"Crittografia\"")
("angular" "angolare")
("animate" "animare")
("animate folding" "piega animata")
("animate object" "oggetto animato")
("animate objects" "oggetti animati")
("animate unfolding" "spiegazione animata")
("animated" "animato")
("animation" "animazione")
("animation toolbar" "barra degli strumenti animazione")
("annotate" "annota")
("answer" "risposta")
("answer field" "campo di risposta")
("answer to question" "risposta alla domanda")
("answers only" "solo risposte")
("any" "qualsiasi")
("appear" "appaiono")
("apply macro" "applica macro")
("apply macro once" "applica macro una volta")
("approximate" "approssimativo")
("arc" "arco")
("arc cosine" "arco coseno")
("arc sine" "arc sine")
("arc tangent" "arco tangente")
("arch series" "serie ad arco")
("are you sure you want to delete collected public keys" "sei sicuro di voler eliminare le chiavi pubbliche raccolte")
("are you sure you want to delete selected public keys" "sei sicuro di voler eliminare le chiavi pubbliche selezionate")
("are you sure you want to delete selected secret keys" "sei sicuro di voler eliminare le chiavi segrete selezionate")
("are you sure you want to destroy the wallet" "sei sicuro di voler distruggere il portafoglio")
("art Pen" "art pen")
("art frame" "cornice d'arte")
("arxiv category" "categoria arxiv")
("as visual grid" "come griglia visiva")
("aspect" "aspetto")
("attach master" "attach master")
("attached" "allegato")
("auto" "auto")
("auto-save file" "file di salvataggio automatico")
("automatic brackets" "parentesi automatiche")
("automatic content generation" "generazione automatica di contenuti")
("automatic program brackets" "parentesi di programma automatiche")
("automatic quotes" "virgolette automatiche")
("automatically close brackets" "chiude automaticamente le parentesi")
("automatically import bibliographies when opening files" "importa automaticamente le bibliografie all'apertura dei file")
("automatically remember all passphrases in the wallet" "ricorda automaticamente tutte le passphrase nel portafoglio")
("automatically save" "salva automaticamente")
("autosave" "salvataggio automatico")
("avoid spurious spaces" "evitare spazi spuri")
("axis" "asse")
("b series" "serie b")
("back" "indietro")
("background evaluations" "valutazioni di base")
("background picture selector" "selettore di immagini di sfondo")
("backtrace errors" "errori di backtrace")
("base" "base")
("baseline" "baseline")
("basic communication using pipes" "comunicazione di base tramite pipe")
("beamer" "beamer")
("beamer formats" "formati beamer")
("beamer theme" "tema del proiettore")
("bench" "panca")
("bend bottom" "piega fondo")
("bend corner" "angolo piega")
("bend diagonal" "piega diagonale")
("bend in" "piega")
("bend out" "piega")
("bezier" "bezier")
("bibTeX command" "comando bibTeX")
("bidirectional" "bidirezionale")
("big environment box" "big environment box")
("big focus" "grande attenzione")
("binary operator" "operatore binario")
("bitmap resolution (dpi)" "risoluzione bitmap (dpi)")
("black floral I" "nero floreale I")
("black floral II" "nero floreale II")
("blackboard embold" "embold lavagna")
("blank column" "colonna vuota")
("blank row" "riga vuota")
("block" "blocco")
("block content" "blocco del contenuto")
("block of code" "blocco di codice")
("blur" "sfocatura")
("both versions" "entrambe le versioni")
("bottom baseline" "linea di base inferiore")
("bottom cell border" "bordo inferiore della cella")
("bottom cell padding" "imbottitura cella inferiore")
("bottom table border" "bordo del tavolo inferiore")
("bottom table padding" "imbottitura del tavolo inferiore")
("bottom tools" "strumenti inferiori")
("box" "scatola")
("broken white" "bianco rotto")
("browse back" "sfoglia indietro")
("browse forward" "sfoglia in avanti")
("browse modules documentation" "sfoglia documentazione moduli")
("buffer management" "gestione buffer")
("buffer must be on disk" "buffer deve essere su disco")
("buffer must have a name" "il buffer deve avere un nome")
("build buffer" "build buffer")
("build buffer in" "build buffer in")
("build directory" "directory di costruzione")
("build directory in" "build directory in")
("build link pages" "crea pagine di link")
("build-all" "build-all")
("bump" "bump")
("busy" "occupato")
("cJK" "cJK")
("cJK spacing" "spaziatura cJK")
("calculus" "calcolo")
("cancelled" "cancellato")
("cannot download directory to file" "impossibile scaricare la directory nel file")
("cannot rename across different servers" "impossibile rinominare tra server diversi")
("cannot upload directory to file" "impossibile caricare la directory nel file")
("cartesian" "cartesiano")
("carved wood" "legno intagliato")
("case-insensitive search" "ricerca senza distinzione tra maiuscole e minuscole")
("categories" "categorie")
("category" "categoria")
("cell properties" "proprietà della cella")
("cells" "celle")
("center baseline" "linea di base centrale")
("chalk" "gesso")
("change default unit" "cambia unità predefinita")
("change passphrase" "cambia passphrase")
("change permissions" "modifica autorizzazioni")
("change step-size" "modifica dimensioni del gradino")
("change tags" "cambia tag")
("change the TeXmacs preferences" "modifica le preferenze di TeXmacs")
("change the border of the table" "cambia il bordo della tabella")
("change the style of mathematical formulas" "cambia lo stile delle formule matematiche")
("change wallet passphrase" "cambia passphrase del portafoglio")
("character contraction" "contrazione del personaggio")
("character encoding" "codifica caratteri")
("character expansion" "espansione del personaggio")
("check exported Pdf files for correctness" "controlla la correttezza dei file Pdf esportati")
("check for automatic updates" "verifica aggiornamenti automatici")
("check for updates" "controlla aggiornamenti")
("checkable field" "campo selezionabile")
("choose background" "scegli sfondo")
("choose color" "scegli il colore")
("cipher algorithm for passphrase encryption" "algoritmo di cifratura per crittografia passphrase")
("circle" "cerchio")
("classification" "classificazione")
("clean slate" "tabula rasa")
("clear all fields" "cancella tutti i campi")
("clear local information" "chiare informazioni locali")
("clear menu" "cancella menu")
("clear undo history" "cancella cronologia annullamenti")
("click Ok button twice to discard this warning" "fai clic due volte sul pulsante OK per eliminare questo avviso")
("clip" "clip")
("clipboard image format" "formato immagine degli appunti")
("close animation tool" "chiudi strumento di animazione")
("close document" "chiudi documento")
("close program" "programma chiuso")
("close replace tool" "chiudi strumento di sostituzione")
("close search tool" "chiudi strumento di ricerca")
("close spell tool" "strumento per chiudere gli incantesimi")
("close translations to rebuild" "chiudi le traduzioni per ricostruire")
("closed bezier" "bezier chiuso")
("closed curve" "curva chiusa")
("closed smooth" "chiuso liscio")
("closed spline" "spline chiusa")
("closing style" "stile di chiusura")
("cluster by affiliation" "cluster per affiliazione")
("collect garbage" "raccolta rifiuti")
("collected keys" "chiavi raccolte")
("color of the axes" "colore degli assi")
("color of the subunits" "colore delle subunità")
("color of the units" "colore delle unità")
("colors" "colori")
("column to the left" "colonna a sinistra")
("column to the right" "colonna a destra")
("columns" "colonne")
("column separation" "separazione delle colonne")
("commit" "commit")
("commit file" "file di commit")
("common" "comune")
("common formats" "formati comuni")
("commutative diagram" "diagramma commutativo")
("compact" "compatto")
("compactification" "compactificazione")
("compactify" "compatta")
("compare" "confronta")
("compare with" "confronta con")
("complete bibliographic reference" "riferimento bibliografico completo")
("completion" "completamento")
("complex actions" "azioni complesse")
("compose" "componi")
("compound" "composto")
("compress" "comprimi")
("compress into toolbar" "comprimi nella barra degli strumenti")
("compressed" "compresso")
("conceal" "nascondere")
("configure look and feel" "configura aspetto grafico")
("confirm collected public key deletion" "conferma l'eliminazione della chiave pubblica raccolta")
("confirm database entry" "conferma immissione database")
("confirm entry" "conferma immissione")
("confirm public key deletion" "conferma l'eliminazione della chiave pubblica")
("confirm secret key deletion" "conferma cancellazione chiave segreta")
("confirm selected database entries" "conferma voci di database selezionate")
("confirm selected entries" "conferma voci selezionate")
("confirm wallet destruction" "conferma la distruzione del portafoglio")
("conservative conversion options" "opzioni di conversione conservativa")
("consoles" "console")
("constellation" "costellazione")
("contact" "contatto")
("content" "contenuto")
("context aids" "aiuti contestuali")
("contextual hints" "suggerimenti contestuali")
("continue" "continua")
("continued fraction" "frazione continua")
("contour" "contorno")
("contract logarithms" "logaritmi di contratto")
("contribute" "contributo")
("control flow" "flusso di controllo")
("control the evaluation of expressions" "controlla la valutazione delle espressioni")
("convert" "converti")
("converters" "convertitori")
("convertible" "convertibile")
("copy new objects to all frames" "copia nuovi oggetti in tutti i frame")
("copy new objects to previous frames" "copia nuovi oggetti nei frame precedenti")
("copy new objects to subsequent frames" "copia nuovi oggetti nei frame successivi")
("copy to all frames after" "copia su tutti i frame dopo")
("copy to all frames before" "copia su tutti i frame prima")
("copy to all other frames" "copia su tutti gli altri frame")
("copyright" "copyright")
("cork charset with TeX catcode definition in preamble" "set di caratteri in sughero con definizione del codice cat TeX nel preambolo")
("cork with catcodes" "tappo con codici cat")
("correct" "corretto")
("correct all" "correggi tutto")
("correct formula" "formula corretta")
("correct manually" "correggi manualmente")
("correct mathematical formulas" "formule matematiche corrette")
("correction" "correzione")
("cosine" "coseno")
("count characters" "contare i caratteri")
("count lines" "linee di conteggio")
("count words" "conta parole")
("create a new document" "crea un nuovo documento")
("create link" "crea collegamento")
("create preamble" "crea preambolo")
("create remote account" "crea account remoto")
("create remote directory" "crea directory remota")
("create remote file" "crea file remoto")
("create subprogram" "crea sottoprogramma")
("create subsession" "crea sottosessione")
("create table macro" "crea macro tabella")
("create web site" "crea sito")
("creating new account" "creazione di un nuovo account")
("creating technical pictures" "creazione di immagini tecniche")
("crop" "ritaglio")
("crop marks" "crocini di registro")
("cross" "croce")
("crossed boxes" "scatole incrociate")
("crossed circles" "cerchi incrociati")
("current user version" "versione attuale dell'utente")
("current version" "versione attuale")
("cursor" "cursore")
("curve" "curva")
("curve intersections" "intersezioni di curve")
("curve points" "punti curva")
("customizations" "personalizzazioni")
("customizing and extending the user interface" "personalizzazione ed estensione dell'interfaccia utente")
("cyan" "ciano")
("dark grey" "grigio scuro")
("data" "dati")
("database entry" "voce di database")
("database tool" "strumento database")
("database toolbar" "barra degli strumenti del database")
("deactivate once" "disattivare una volta")
("dead" "morto")
("debug" "debug")
("debugging console" "console di debug")
("debugging tool" "strumento di debug")
("decimal comma" "virgola decimale")
("decimal dot" "punto decimale")
("decomposed" "decomposto")
("decorated" "decorato")
("decorated wood" "legno decorato")
("decorative" "decorativo")
("decrease size" "Riduci dimensioni")
("decrypt" "decifrare")
("decrypted" "decrittografato")
("decryption" "decodifica")
("default size" "dimensione predefinita")
("degrade" "degradare")
("degraded" "degradato")
("delete documentation cache" "elimina cache documentazione")
("delete entries" "elimina voci")
("delete link" "elimina collegamento")
("delete selected entries in wallet" "elimina le voci selezionate nel portafoglio")
("delete user identity" "elimina identità utente")
("deleted" "cancellato")
("describe" "descrivi")
("describe tag" "descrivi tag")
("destroy" "distruggere")
("detach master" "distacco maestro")
("detailed" "dettagliato")
("detailed menus" "menu dettagliati")
("details in menus" "dettagli nei menu")
("determine margins from text width" "determina i margini dalla larghezza del testo")
("developer" "sviluppatore")
("developer tool" "strumento per sviluppatori")
("device" "dispositivo")
("diamond" "diamante")
("differentiate" "differenziare")
("digital" "digitale")
("dilate" "dilatare")
("direction of progression" "direzione della progressione")
("direction of translation" "direzione della traduzione")
("disable" "disabilita")
("disable coloring on paper" "disabilita colorazione su carta")
("disable encryption" "disabilita crittografia")
("disabled" "disabilitato")
("disappear" "sparisci")
("disk" "disco")
("display style" "stile di visualizzazione")
("displayed formula" "formula visualizzata")
("dissociate joined cells" "dissociate cellule unite")
("distill encapsulated Pdf files" "file Pdf incapsulati da distill")
("distort" "distorcere")
("distorted" "distorto")
("division" "divisione")
("do not remap" "non rimappare")
("document colors" "colori del documento")
("document font selector" "selettore font documento")
("document language" "lingua del documento")
("document metadata" "metadati del documento")
("document page format" "formato pagina documento")
("document paragraph format" "formato paragrafo del documento")
("document source tree preferences" "Preferenze dell'albero dei sorgenti del documento")
("document updates run" "Esegui aggiornamenti documenti")
("documents in separate windows" "documenti in finestre separate")
("download" "scarica")
("download file or directory" "scarica file o directory")
("downwards" "verso il basso")
("dragging" "trascinamento")
("draw" "disegna")
("draw graphics" "disegna grafica")
("draw image" "disegna immagine")
("draw over" "disegnare")
("draw over selection" "disegna sopra la selezione")
("drop" "drop")
("due to" "dovuto a")
("dynamic" "dinamico")
("eRROR" "eRROR")
("edit animation" "modifica animazione")
("edit groups of objects" "modifica gruppi di oggetti")
("edit macro" "modifica macro")
("edit macros" "modifica macro")
("edit object properties" "modifica proprietà oggetto")
("edit preamble" "modifica preambolo")
("edit source" "modifica sorgente")
("edit source tree" "modifica dell'albero dei sorgenti")
("edit style" "modifica stile")
("edit translations file" "modifica file traduzioni")
("education" "istruzione")
("effect pen" "penna effetto")
("eigenvalues" "autovalori")
("eighth" "ottavo")
("embold" "embold")
("emboss" "rilievo")
("enable page breaking" "abilita interruzione di pagina")
("enabled" "abilitato")
("encoding" "codifica")
("encrypt" "crittografare")
("encrypted" "crittografato")
("encrypted buffer" "buffer crittografato")
("encryption" "crittografia")
("encryption error" "errore di crittografia")
("encryption facilities are not currently available" "Le funzionalità di crittografia non sono attualmente disponibili")
("encryption facilities have not been enabled for TeXmacs" "Le funzionalità di crittografia non sono state abilitate per TeXmacs")
("enforce brackets to match" "applica parentesi corrispondenti")
("engrave" "incidere")
("enter data" "inserisci dati")
("enter graphics" "inserisci grafica")
("enter graphics mode" "entra in modalità grafica")
("enter new passphrase for encryption" "inserisci una nuova passphrase per la crittografia")
("enter passphrase for decryption" "inserisci passphrase per la decrittazione")
("enter passphrase for identity" "inserisci passphrase per identità")
("enter title information" "inserisci informazioni sul titolo")
("entire table" "tabella intera")
("entry up to date in database" "iscrizione aggiornata nel database")
("enunciation" "enunciazione")
("environment variable" "variabile d'ambiente")
("environments" "ambienti")
("erode" "erode")
("error messages" "messaggi di errore")
("error output" "uscita errore")
("error status report" "rapporto sullo stato dell'errore")
("error: bracket does not match" "errore: la parentesi non corrisponde")
("error: cyclic or missing chunks detected" "errore: rilevati blocchi ciclici o mancanti")
("error: file not found" "errore: file non trovato")
("error: ghostview does not seem to be installed on your system" "errore: ghostview non sembra essere installato sul tuo sistema")
("error: one of the alternatives should be filled out" "errore: una delle alternative dovrebbe essere compilata")
("error: only one alternatives should be filled out" "errore: compilare solo una alternativa")
("error: should fill out name for referencing" "errore: inserire il nome per il riferimento")
("error: should fill out required field" "errore: deve compilare il campo richiesto")
("escape" "fuga")
("evaluable field" "campo valutabile")
("evaluate above" "valuta sopra")
("evaluate all" "valuta tutto")
("evaluate below" "valuta sotto")
("evaluate fields" "valutazione campi")
("evaluate fields in order" "valuta i campi in ordine")
("evaluate script" "valuta lo script")
("evaluation" "valutazione")
("evaluation switch" "interruttore di valutazione")
("evaluation tag" "tag di valutazione")
("even page" "pagina pari")
("even page left margin" "margine sinistro della pagina pari")
("even page shift" "spostamento pagina uniforme")
("even pages" "pagine pari")
("events" "eventi")
("exact" "esatto")
("execution of scripts" "esecuzione di script")
("exit graphics" "uscita grafica")
("exit graphics mode" "esci dalla modalità grafica")
("exit left" "esci a sinistra")
("exit right" "esci a destra")
("exit tag on the left" "tag di uscita a sinistra")
("exit tag on the right" "tag di uscita a destra")
("expand TeXmacs macros with no LaTeX equivalents" "espandi macro TeXmacs senza equivalenti LaTeX")
("expand beamer slides" "espandere le diapositive del proiettore")
("expand inclusions" "espandi inclusioni")
("expand logarithms" "espandi logaritmi")
("expand trigonometric functions" "espandi funzioni trigonometriche")
("expand unrecognized macros" "espandi macro non riconosciute")
("expand user-defined macros" "espandi macro definite dall'utente")
("expanded" "espanso")
("experimental features (to be used with care)" "caratteristiche sperimentali (da usare con cura)")
("explain" "spiega")
("explanatory item" "punto esplicativo")
("explicit keystroke" "battitura esplicita")
("explicit margins" "margini espliciti")
("exponential" "esponenziale")
("export bibliographies as links" "esportazione bibliografie come link")
("export bibliography" "bibliografia di esportazione")
("export entries in buffer" "esporta voci nel buffer")
("export file" "file di esportazione")
("export formulas as images" "formule di esportazione come immagini")
("export mathematical formulas as MathML" "esporta formule matematiche come MathML")
("export mathematical formulas as images" "esporta formule matematiche come immagini")
("export selected entries" "esporta voci selezionate")
("export selection" "selezione esportazione")
("export selection as image" "esporta selezione come immagine")
("export selections as" "esporta selezioni come")
("export sessions" "sessioni di esportazione")
("exported bibliographic entries" "voci bibliografiche esportate")
("exported bibliographic references" "riferimenti bibliografici esportati")
("extend" "estendi")
("extend table to full paragraph width" "estendi la tabella alla larghezza completa del paragrafo")
("extended" "esteso")
("extensible left arrow" "freccia sinistra estensibile")
("extensible right arrow" "freccia destra estensibile")
("extern" "esterno")
("external" "esterno")
("extra branch" "ramo extra")
("extra interline space" "spazio interlinea extra")
("extra name" "nome extra")
("extract" "estratto")
("extract style file" "Estrai file di stile")
("extract style package" "pacchetto stile estratto")
("factor" "fattore")
("fade" "dissolvenza")
("fade in" "dissolvenza in")
("fade out" "dissolvenza")
("fast" "veloce")
("fast decrease" "riduzione rapida")
("fast environments" "ambienti veloci")
("fast increase" "aumento rapido")
("field reference" "riferimento campo")
("fifth" "quinto")
("file saved" "file salvato")
("fill color" "colore di riempimento")
("fill out" "compila")
("filter" "filtro")
("find file" "trova file")
("finished collecting symbols documentation" "documentazione sulla raccolta dei simboli completata")
("first" "primo")
("first chunk" "primo pezzo")
("first difference" "prima differenza")
("first error" "primo errore")
("first field" "primo campo")
("first occurrence" "prima occorrenza")
("first similar" "primo simile")
("fit" "in forma")
("fit to height" "adatta all'altezza")
("fit to screen" "adatta allo schermo")
("fit to screen width" "adatta alla larghezza dello schermo")
("fit to width" "adatta alla larghezza")
("five columns" "cinque colonne")
("fixed" "fisso")
("flag is off" "flag is off")
("flag is on" "flag is on")
("flatten" "appiattire")
("floating algorithm" "algoritmo mobile")
("floating phantom" "fantasma galleggiante")
("focus" "focus")
("focus dependent icons" "icone dipendenti dalla messa a fuoco")
("fold all" "piega tutto")
("fold all fields" "piega tutti i campi")
("fold back" "fold back")
("fold input field" "piega campo di input")
("follow external links" "segui link esterni")
("follow inverse links" "segui collegamenti inversi")
("font customization" "personalizzazione del carattere")
("font effects" "effetti carattere")
("font selector" "selettore font")
("font type" "tipo di carattere")
("for each" "per ciascuno")
("force reloading of translations" "Ricarica forzata delle traduzioni")
("formatted and structured output" "output formattato e strutturato")
("formatting" "formattazione")
("forward" "avanti")
("four columns" "quattro colonne")
("four dots" "quattro punti")
("fourth" "quarto")
("fraktur" "fraktur")
("framed" "incorniciato")
("framed theorems" "teoremi con cornice")
("from" "da")
("from center" "dal centro")
("front matter" "argomento")
("full" "pieno")
("full author list" "elenco completo degli autori")
("full screen mode" "modalità schermo intero")
("functional" "funzionale")
("gap" "gap")
("garbage collection" "raccolta dei rifiuti")
("gaussian" "gaussiano")
("gcd" "gcd")
("general" "generale")
("general note" "nota generale")
("generate GnuPG key" "genera chiave GnuPG")
("generated LaTeX document contains no errors" "il documento LaTeX generato non contiene errori")
("generated field" "campo generato")
("geometry" "geometria")
("get arity" "get arity")
("get label" "ottieni etichetta")
("get list with remote versions" "ottieni elenco con versioni remote")
("global log" "registro globale")
("global status" "stato globale")
("glue multiple spaces" "incollare più spazi")
("glyphs" "glifi")
("gnaw" "rosicchiare")
("gnawed" "rosicchiato")
("gnuPG command" "comando gnuPG")
("gnuPG decryption error" "errore di decrittazione gnuPG")
("gnuPG error: buffer encryption failed" "Errore gnuPG: crittografia buffer non riuscita")
("gnuPG error: cannot find suitable secret key to decrypt" "errore gnuPG: impossibile trovare la chiave segreta adatta per decrittografare")
("gnuPG requires name and email to have at least 5 characters" "gnuPG richiede che il nome e l'e-mail contengano almeno 5 caratteri")
("go to anchor" "vai all'ancoraggio")
("go to anchor or float" "vai all'ancoraggio o al galleggiante")
("go to anchor or footnote" "vai all'ancoraggio o alla nota")
("go to first similar tag" "vai al primo tag simile")
("go to float" "go to float")
("go to footnote" "vai alla nota")
("go to last similar tag" "vai all'ultimo tag simile")
("go to next similar tag" "vai al prossimo tag simile")
("go to previous similar tag" "vai al precedente tag simile")
("go to section" "vai alla sezione")
("grain" "grano")
("granite" "granito")
("graphical effects" "effetti grafici")
("graphical interface font scale" "scala dei caratteri dell'interfaccia grafica")
("graphical overlays" "overlay grafici")
("graphical slides and overlays" "diapositive e sovrapposizioni grafiche")
("graphics" "grafica")
("graphics geometry" "geometria grafica")
("graphics grids" "griglie grafiche")
("greyed" "grigio")
("grid" "griglia")
("grid curves" "curve della griglia")
("grid points" "punti griglia")
("grid-curve intersections" "intersezioni griglia-curva")
("group of objects" "gruppo di oggetti")
("group/ungroup" "raggruppa / separa")
("group/ungroup objects" "raggruppa / separa oggetti")
("grouped" "raggruppati")
("guarantee transparent source tracking" "garanzia di tracciamento sorgente trasparente")
("h modifier" "modificatore h")
("half wide" "mezzo largo")
("hand drawn" "disegnati a mano")
("handwritten" "scritto a mano")
("hangul" "hangul")
("headers" "intestazioni")
("hidden" "nascosto")
("high resolution settings" "impostazioni ad alta risoluzione")
("history" "storia")
("homepage" "homepage")
("homoglyph substitutions" "sostituzioni di omogenei")
("horizontal alignment" "allineamento orizzontale")
("horizontal collapse distance" "distanza di collasso orizzontale")
("horizontal margins" "margini orizzontali")
("hybrid command" "comando ibrido")
("hyphenate as" "trattino come")
("icon" "icona")
("if hyphenated" "se sillabato")
("ignore" "ignora")
("impact" "impatto")
("import bibliography" "bibliografia di importazione")
("import database entry" "voce del database di importazione")
("import entries in buffer" "voci di importazione nel buffer")
("import entry" "voce di importazione")
("import file" "file di importazione")
("import public keys from buffer" "importa chiavi pubbliche dal buffer")
("import selected database entries" "importa voci di database selezionate")
("import selected entries" "importa voci selezionate")
("import selections as" "importa selezioni come")
("import sessions" "sessioni di importazione")
("import sophisticated objects as pictures" "importa oggetti sofisticati come immagini")
("imported bibliographic entries" "voci bibliografiche importate")
("in popup windows" "nelle finestre popup")
("inanimated" "inanimato")
("inch" "pollici")
("incomplete entries found to be filled out" "voci incomplete trovate da compilare")
("increase size" "aumenta dimensioni")
("indent paragraphs" "trattini")
("indentation" "rientro")
("indication" "indicazione")
("informative flags" "bandiere informative")
("initialize" "inizializza")
("initialize wallet" "inizializza portafoglio")
("initials" "iniziali")
("ink here" "inchiostro qui")
("ink in" "inchiostro in")
("ink out" "inchiostro esaurito")
("inline" "in linea")
("inline args" "inline args")
("inline arguments" "argomenti inline")
("inline code" "codice inline")
("inline content" "contenuto incorporato")
("inline formula" "formula in linea")
("inner bottom" "fondo interno")
("inner left" "interno sinistro")
("inner right" "interno destro")
("inner top" "interno superiore")
("input command" "comando di input")
("input field" "campo di input")
("input mode" "modalità input")
("input options" "opzioni di input")
("insert a computer program" "inserire un programma per computer")
("insert a condition" "inserire una condizione")
("insert a control flow instruction" "inserire un'istruzione di flusso di controllo")
("insert a gap" "inserire uno spazio")
("insert a list" "inserisci un elenco")
("insert a multiple choice" "inserire una scelta multipla")
("insert a negation" "inserire una negazione")
("insert a new entry" "inserisci una nuova voce")
("insert a note or a floating object" "inserisci una nota o un oggetto fluttuante")
("insert a numerical operation" "inserire un'operazione numerica")
("insert a prominent piece of text" "inserire un pezzo di testo prominente")
("insert a question" "inserisci una domanda")
("insert a root" "inserisci una radice")
("insert a script" "inserisci uno script")
("insert a section block" "inserire un blocco di sezione")
("insert a textual operation" "inserire un'operazione testuale")
("insert a textual operator" "inserire un operatore testuale")
("insert a wide symbol above" "inserisci un simbolo largo sopra")
("insert a wide symbol below" "inserisci un simbolo largo sotto")
("insert above" "inserisci sopra")
("insert abstract" "inserisci abstract")
("insert an answer" "inserisci una risposta")
("insert an enunciation" "inserire un'enunciazione")
("insert an operation on tuples" "inserire un'operazione su tuple")
("insert annotation" "inserisci annotazione")
("insert arcs" "inserire archi")
("insert argument after" "inserisci argomento dopo")
("insert argument before" "inserisci argomento prima")
("insert author" "inserisci autore")
("insert below" "inserisci sotto")
("insert bibliography" "inserisci bibliografia")
("insert circles" "inserisci cerchi")
("insert closed splines" "inserire spline chiuse")
("insert copyright and license information" "inserire informazioni sul copyright e sulla licenza")
("insert explanatory item" "inserire la voce esplicativa")
("insert field above" "inserisci campo sopra")
("insert field below" "inserisci campo sotto")
("insert fields" "inserisci campi")
("insert hand drawn curves" "inserisci curve disegnate a mano")
("insert input field above" "inserisci campo di input sopra")
("insert input field below" "inserisci campo di input sotto")
("insert large delimiters" "inserisci delimitatori grandi")
("insert last name" "inserisci cognome")
("insert left" "inserisci a sinistra")
("insert lines" "inserisci righe")
("insert macro" "Inserisci macro")
("insert missing invisible operators" "inserire operatori invisibili mancanti")
("insert more names" "inserisci più nomi")
("insert multiple paragraphs" "inserisci più paragrafi")
("insert overlay after" "inserisci overlay dopo")
("insert overlay before" "inserisci overlay prima")
("insert particle" "Inserisci particella")
("insert plain text" "inserisci testo semplice")
("insert points" "inserire punti")
("insert polygons" "inserisci poligoni")
("insert right" "inserisci a destra")
("insert similar above" "inserisci simile sopra")
("insert similar below" "inserisci simile sotto")
("insert similar block above" "inserisci blocco simile sopra")
("insert similar block below" "inserisci blocco simile sotto")
("insert slide after" "inserisci slide dopo")
("insert slide before" "inserisci la diapositiva prima")
("insert splines" "Inserisci spline")
("insert subscript" "inserisci pedice")
("insert subtable" "Inserisci sottotabella")
("insert superscript" "inserisci apice")
("insert symbol documentation" "inserire la documentazione dei simboli")
("insert template" "Inserisci modello")
("insert text" "inserisci testo")
("insert text field" "Inserisci campo di testo")
("insert text field above" "inserisci il campo di testo sopra")
("insert text field below" "inserisci il campo di testo sotto")
("insert title" "inserisci titolo")
("insert title after name" "inserisci titolo dopo nome")
("insert user interface related markup" "inserisci markup relativo all'interfaccia utente")
("insert value" "inserisci valore")
("inserting control points" "inserimento punti di controllo")
("inside mathematics" "dentro la matematica")
("integrate" "integra")
("interactive command" "comando interattivo")
("interactive questions" "domande interattive")
("intercharacter compression" "compressione intercharacter")
("intercharacter stretching" "intercharacter stretching")
("interrupted" "interrotto")
("invalid multi-paragraph selection" "Selezione multiparagrafo non valida")
("invalid renaming" "ridenominazione non valida")
("invert" "invert")
("inverted breve" "breve inverso")
("invisible ending" "finale invisibile")
("invisible newline" "newline invisibile")
("invisible opening" "apertura invisibile")
("inwards" "verso l'interno")
("join selected cells" "Unisci celle selezionate")
("jump in" "salta dentro")
("junior" "junior")
("justify" "giustificare")
("keep evaluated expressions" "mantieni le espressioni valutate")
("keep local" "mantieni locale")
("keep remote" "mantieni remoto")
("keep track of source code" "tenere traccia del codice sorgente")
("keep unfolded" "mantieni aperto")
("key manager" "gestore chiavi")
("keyboard configuration" "configurazione tastiera")
("laTeX errors" "errori laTeX")
("laptop presentations" "presentazioni per laptop")
("large brackets" "parentesi grandi")
("large cells" "celle grandi")
("large displayed" "display grande")
("large displayed fraction" "frazione visualizzata grande")
("large tables" "tavoli di grandi dimensioni")
("last" "ultimo")
("last check" "ultimo controllo")
("last difference" "ultima differenza")
("last error" "ultimo errore")
("last field" "ultimo campo")
("last name" "cognome")
("last occurrence" "ultima occorrenza")
("last similar" "last similar")
("lcm" "mcm")
("left arrow" "freccia sinistra")
("left axis" "asse sinistro")
("left baseline" "linea di base sinistra")
("left bottom" "in basso a sinistra")
("left cell border" "bordo cella sinistro")
("left cell padding" "imbottitura per cella sinistra")
("left center" "centro a sinistra")
("left click: add point; Right click: undo" "clic sinistro: aggiungi punto; Clic destro: annulla")
("left click: finish; Right click: undo" "clic sinistro: fine; clic destro: annulla")
("left click: new object" "clic sinistro: nuovo oggetto")
("left click: operate" "click sinistro: operare")
("left down" "left down")
("left on even pages" "lasciato su pagine pari")
("left table border" "bordo sinistro della tabella")
("left table padding" "imbottitura tavolo sinistro")
("left top" "in alto a sinistra")
("left up" "left up")
("left-right arrow" "freccia sinistra-destra")
("leftwards" "verso sinistra")
("let the environment float" "lascia fluttuare l'ambiente")
("light grey" "grigio chiaro")
("line arrows" "frecce linea")
("line breaking" "interruzione di riga")
("line dashes" "trattini di linea")
("line portion" "porzione di linea")
("line style" "stile linea")
("line width" "larghezza della linea")
("line wrapping" "linea a capo")
("line wrapping inside cell" "linea che avvolge la cella")
("linear 2D" "2D lineare")
("linear algebra" "algebra lineare")
("lines around" "linee intorno")
("link image and copies as" "link immagine e copie come")
("link image as" "link immagine come")
("link mode" "modalità collegamento")
("link to URL" "link all'URL")
("linking tool" "strumento di collegamento")
("live" "live")
("live input-output" "live input-output")
("load help file" "carica file di aiuto")
("load remote file" "carica file remoto")
("loading" "caricamento")
("local entries" "voci locali")
("loci" "loci")
("locus" "locus")
("locus rendering" "rendering del locus")
("logarithm" "logaritmo")
("logarithmic" "logaritmico")
("logarithmic base" "base logaritmica")
("logarithms" "logaritmi")
("logging in" "accesso")
("logical and" "logico e")
("logical implication" "implicazione logica")
("logical not" "Non logico")
("logical or" "logico o")
("login" "accedi")
("logout" "logout")
("long macro" "macro lunga")
("long text" "testo lungo")
("look for more fonts" "cerca più caratteri")
("loops" "loop")
("m modifier" "modificatore m")
("macro argument" "argomento macro")
("macro definition" "definizione macro")
("macro editor" "macro editor")
("macro name" "nome macro")
("macros" "macro")
("macros editor" "editor di macro")
("magnify horizontally" "ingrandisci orizzontalmente")
("magnify vertically" "ingrandisci verticalmente")
("main presentation style" "stile di presentazione principale")
("make a letter environment" "crea un ambiente lettera")
("make a multi-slide presentation" "crea una presentazione multi-slide")
("make block wide" "allarga blocco")
("make float wide" "make float wide")
("make floating" "make floating")
("make footnote wide" "amplia la nota a piè di pagina")
("make link" "crea collegamento")
("make non floating" "make non floating")
("make wide" "fai largo")
("manila paper" "carta manila")
("map arguments" "argomenti della mappa")
("marginal note" "nota marginale")
("margins from width" "margini dalla larghezza")
("margins on paper" "margini sulla carta")
("margins on screen" "margini sullo schermo")
("marked" "contrassegnato")
("marker" "marker")
("material" "materiale")
("math Extra" "matematica extra")
("math Letters" "Lettere matematiche")
("math Symbols" "Simboli matematici")
("mathematical and customized input" "input matematici e personalizzati")
("mathematical font" "carattere matematico")
("mathematical input" "input matematici")
("mathematical output" "output matematico")
("matrices" "matrici")
("maximal" "massimo")
("maximal cell height" "altezza massima della cella")
("maximal clustering" "clustering massimo")
("maximal table height" "altezza massima della tabella")
("maximal table width" "larghezza massima della tabella")
("maximum" "massimo")
("meander" "meandro")
("medieval" "medievale")
("memory" "memoria")
("memory usage" "utilizzo della memoria")
("menu" "menu")
("merge lines into paragraphs unless separated by blank lines" "Unisci righe in paragrafi se non separati da righe vuote")
("messages" "messaggi")
("meta data" "metadati")
("metadata" "metadati")
("metal" "metallo")
("middle baseline" "baseline centrale")
("minimal" "minimo")
("minimal cell height" "altezza minima della cella")
("minimal cell width" "larghezza minima della cella")
("minimal line separation" "separazione minima delle linee")
("minimal table height" "altezza minima del tavolo")
("minimal table width" "larghezza minima del tavolo")
("minimum" "minimo")
("mirror" "specchio")
("miscellaneous features" "caratteristiche varie")
("miscellanous" "miscellaneo")
("mixed" "misto")
("mode dependent icons" "icone dipendenti dalla modalità")
("modify bibliography" "modifica bibliografia")
("modify remote live document" "modifica documento live remoto")
("module" "modulo")
("module browser" "browser del modulo")
("monospaced" "monospaziato")
("more information about GNU TeXmacs can be found in the Help" "ulteriori informazioni su GNU TeXmacs sono disponibili nella Guida")
("more information about GNU TeXmacs can be found in the Help-<gtr>About menu" "maggiori informazioni su GNU TeXmacs sono disponibili nel menu Aiuto-<gtr> Informazioni")
("motion" "movimento")
("mouse over object" "mouse sull'oggetto")
("move" "sposta")
("move objects" "sposta oggetti")
("move over object on which to operate" "sposta sopra l'oggetto su cui operare")
("multiline" "multilinea")
("multiline input" "input multilinea")
("multiple choice" "scelta multipla")
("multiple documents share window" "finestra di condivisione di più documenti")
("multiple root" "radice multipla")
("multiplication" "moltiplicazione")
("mutator tags" "tag mutatore")
("my documents" "i miei documenti")
("named" "nominato")
("navigation options" "opzioni di navigazione")
("never" "mai")
("new account" "nuovo account")
("new bibliography dialogue" "nuovo dialogo bibliografico")
("new document" "nuovo documento")
("new double page" "nuova doppia pagina")
("new double page before" "nuova doppia pagina prima")
("new entry" "new entry")
("new identity" "nuova identità")
("new locus" "nuovo locus")
("new macro" "nuova macro")
("new passphrase" "nuova passphrase")
("new remote directory" "nuova directory remota")
("new remote file" "nuovo file remoto")
("new style fonts" "nuovi caratteri di stile")
("new style page breaking" "nuova interruzione di pagina di stile")
("new version" "nuova versione")
("new window" "nuova finestra")
("newer version" "versione più recente")
("next" "successivo")
("next chunk" "prossimo pezzo")
("next difference" "prossima differenza")
("next error" "prossimo errore")
("next field" "campo successivo")
("next occurrence" "prossima occorrenza")
("next screen" "schermata successiva")
("next similar" "prossimo simile")
("no animation" "nessuna animazione")
("no clustering" "nessun raggruppamento")
("no completions" "nessun completamento")
("no errors have been corrected" "nessun errore è stato corretto")
("no grid" "nessuna griglia")
("no matches found for" "nessuna corrispondenza trovata per")
("no multiple spaces" "nessuno spazio multiplo")
("no new public key in document" "nessuna nuova chiave pubblica nel documento")
("no page break" "nessuna interruzione di pagina")
("no page numbers" "nessun numero di pagina")
("no parent" "nessun genitore")
("no selection" "nessuna selezione")
("no spelling errors" "nessun errore di ortografia")
("no spurious spaces" "nessuno spazio spurio")
("normal loci" "loci normali")
("not allowed to remove home directory" "non autorizzato a rimuovere home directory")
("not connected to server" "non connesso al server")
("not yet implemented" "non ancora implementato")
("notebook" "notebook")
("number of polar steps" "numero di passi polari")
("number of subunit steps" "numero di passaggi della subunità")
("numbered" "numerato")
("numbering" "numerazione")
("numeric spreadsheet" "foglio di calcolo numerico")
("oblique" "obliquo")
("odd page" "pagina dispari")
("odd page left margin" "margine sinistro pagina dispari")
("odd page right margin" "margine destro pagina dispari")
("odd page shift" "spostamento pagina dispari")
("odd pages" "pagine dispari")
("of fingerprint" "di impronta digitale")
("old version" "versione precedente")
("older version" "versione precedente")
("on the footer" "a piè di pagina")
("on your system and set it up from the \"Security\" tab" "sul tuo sistema e configuralo dalla scheda \"Sicurezza\"")
("once" "una volta")
("one column" "una colonna")
("one error has been corrected" "un errore è stato corretto")
("one lower case letter, one non alpha-numeric symbol" "una lettera minuscola, un simbolo non alfanumerico")
("one numeric character, one upper case letter" "un carattere numerico, una lettera maiuscola")
("only convert changes when re-importing" "Converti le modifiche solo durante la reimportazione")
("only convert changes with respect to imported version" "converti solo le modifiche rispetto alla versione importata")
("only convert changes with respect to tracked version" "converti solo le modifiche rispetto alla versione tracciata")
("only implemented for complete subtrees" "implementato solo per sottotitoli completi")
("only inline tags" "solo tag incorporati")
("only keep folded" "tenere solo piegato")
("only keep unfolded" "solo aperto aperto")
("only show paragraphs with hits" "mostra solo i paragrafi con risultati")
("only show semantic focus" "mostra solo focus semantico")
("opacity" "opacità")
("open bibliography" "bibliografia aperta")
("open identities" "identità aperte")
("open in new window" "Apri in una nuova finestra")
("open key manager" "apri gestore chiavi")
("open licence agreement" "contratto di licenza aperto")
("open mailbox" "Apri casella di posta")
("open module browser" "browser modulo aperto")
("open symbol browser" "apri il browser dei simboli")
("open tool in separate window" "strumento aperto in una finestra separata")
("operation mode" "modalità operativa")
("or give the complete path to the \"gpg\" or \"gpg2\" command" "o indica il percorso completo del comando \"gpg\" o \"gpg2\"")
("order" "ordine")
("ordinary symbol" "simbolo ordinario")
("ornamented" "ornato")
("other login" "altro accesso")
("other package" "altro pacchetto")
("outer bottom" "fondo esterno")
("outer left" "esterno sinistro")
("outer right" "esterno destro")
("outer top" "parte superiore esterna")
("outline" "contorni")
("outlined" "delineato")
("outlined emboss" "rilievo delineato")
("outlined engrave" "incisione delineata")
("output options" "opzioni di output")
("outwards" "verso l'esterno")
("oval" "ovale")
("overbrace" "overbrace")
("overlap" "sovrapposizione")
("overlay" "overlay")
("overlay mode" "modalità overlay")
("overlays" "overlay")
("overline" "overline")
("overlined" "sottolineato")
("overview of the scheme extension language" "panoramica della lingua di estensione del regime")
("padded" "imbottito")
("page background" "sfondo pagina")
("page break after" "interruzione di pagina dopo")
("page breaking algorithm" "algoritmo di interruzione di pagina")
("page format" "formato pagina")
("page number" "numero di pagina")
("page number rendering" "rendering del numero di pagina")
("page rendering" "rendering della pagina")
("page setup" "impostazione pagina")
("pagedown" "pagedown")
("pageup" "pageup")
("palette" "palette")
("panorama" "panorama")
("paragraph format" "formato paragrafo")
("paragraphs" "paragrafi")
("parametric curve" "curva parametrica")
("parametric surface" "superficie parametrica")
("parenthesis" "parentesi")
("parenthesized" "tra parentesi")
("particle" "particella")
("passphrase decryption" "decodifica passphrase")
("passphrase encryption" "crittografia passphrase")
("passphrase wallet facilities are not currently available" "I servizi di portafoglio passphrase non sono attualmente disponibili")
("passphrases are expected to have at least: 8 characters" "le passphrase dovrebbero contenere almeno: 8 caratteri")
("passphrases mismatch" "mancata corrispondenza delle passphrase")
("pastel" "pastello")
("pattern" "modello")
("pattern selector" "selettore di motivi")
("pause" "pausa")
("pdf version number" "numero versione pdf")
("pen" "penna")
("pen width" "larghezza penna")
("permanent footer" "piè di pagina permanente")
("permanent header" "intestazione permanente")
("permanently add to dictionary" "aggiungi permanentemente al dizionario")
("permanently insert into dictionary" "inserimento permanente nel dizionario")
("permissions" "autorizzazioni")
("phantom" "fantasma")
("phantoms" "fantasmi")
("physics and astronomy class" "classe di fisica e astronomia")
("picture" "immagine")
("pine" "pino")
("plain" "semplice")
("plain boxes" "scatole semplici")
("plain circles" "cerchi semplici")
("play" "gioca")
("play all animations" "Riproduci tutte le animazioni")
("play animation" "Riproduci animazione")
("please install GnuPG software from https://www.gnupg.org" "installa il software GnuPG da https://www.gnupg.org")
("plot" "trama")
("plug-ins" "plug-in")
("plugin" "plugin")
("plugins" "plugin")
("plural" "plurale")
("point" "punto")
("point border" "bordo del punto")
("point size" "dimensione punto")
("point style" "stile punto")
("polar" "polare")
("polygon" "poligono")
("pop server settings" "impostazioni del server pop")
("portion" "porzione")
("position of marginal note" "posizione della nota marginale")
("poster formats" "formati di poster")
("poster theme" "tema poster")
("postfix" "postfix")
("preferences for editing mathematical formulas" "preferenze per la modifica di formule matematiche")
("preferences for tag" "preferenze per tag")
("prefix" "prefisso")
("presentation" "presentazione")
("presentation tag" "tag presentazione")
("presentation tool" "strumento di presentazione")
("preserve" "conserva")
("preserve tags" "preserva tag")
("pretty" "carino")
("pretty tree output" "output albero grazioso")
("preview" "anteprima")
("preview command" "comando di anteprima")
("previous" "precedente")
("previous difference" "differenza precedente")
("previous error" "errore precedente")
("previous field" "campo precedente")
("previous occurrence" "occorrenza precedente")
("previous screen" "schermata precedente")
("previous similar" "precedente simile")
("primitive or macro" "primitivo o macro")
("print buffer" "buffer di stampa")
("print buffer to file" "stampa buffer su file")
("print document" "stampa documento")
("print to file" "stampa su file")
("printer setup" "impostazione stampante")
("produce Pdf using native export filter" "produce Pdf usando il filtro di esportazione nativo")
("produce Postscript using native export filter" "produce Postscript usando il filtro di esportazione nativo")
("program bracket matching" "corrispondenza parentesi di programma")
("program bracket selections" "Selezioni parentesi programma")
("program commands" "comandi del programma")
("program font" "font del programma")
("program interface for buffer management" "interfaccia del programma per la gestione del buffer")
("programming routines for editing documents" "routine di programmazione per la modifica di documenti")
("prominent" "prominente")
("prompts and default input" "prompt e input predefinito")
("provoke C++ error" "provoca errore C ++")
("provoke menu error" "provoca errore di menu")
("provoke scheme error" "errore schema provocato")
("pseudo code" "pseudo codice")
("public key encryption" "crittografia a chiave pubblica")
("public keys" "chiavi pubbliche")
("pulse" "impulso")
("qt GUI only, sorry. Use \"Export selection\"" "solo qt GUI, scusa. Usa \"Esporta selezione\"")
("qt-widgets" "widget qt")
("quantifier" "quantificatore")
("quasi" "quasi")
("question" "domanda")
("questions only" "solo domande")
("questions with answers" "domande con risposte")
("quick evaluation of formulas" "valutazione rapida delle formule")
("rank" "rango")
("raw" "grezzo")
("really delete user identity" "elimina davvero l'identità dell'utente")
("really tiny" "davvero minuscolo")
("rebuild translations file" "ricostruisci file traduzioni")
("recent" "recente")
("recent documents" "documenti recenti")
("recipients" "destinatari")
("recognize" "riconoscere")
("recolor" "ricolorare")
("recover autosave file" "recupera file di salvataggio automatico")
("rectangular" "rettangolare")
("reduce" "riduci")
("reduce trigonometric functions" "Riduci funzioni trigonometriche")
("reduced margins" "margini ridotti")
("reference guide" "guida di riferimento")
("reference guide for the TeXmacs primitives" "guida di riferimento per le primitive TeXmacs")
("reference guide for the standard TeXmacs styles" "guida di riferimento per gli stili TeXmacs standard")
("regenerate" "rigenerare")
("register" "registra")
("register file" "file di registro")
("relate" "relate")
("relation" "relazione")
("release left button: finish editing" "rilascia pulsante sinistro: termina modifica")
("remote" "remoto")
("remote connections" "connessioni remote")
("remote control" "telecomando")
("remote controllers with keyboard simulation" "telecomandi con simulazione tastiera")
("remote directory" "directory remota")
("remote login" "accesso remoto")
("remote servers" "server remoti")
("remote tool" "strumento remoto")
("remove" "rimuovi")
("remove all output fields" "rimuovi tutti i campi di output")
("remove animation" "rimuovi animazione")
("remove argument after" "rimuovi argomento dopo")
("remove argument before" "rimuovi argomento prima")
("remove banner" "rimuovi banner")
("remove database entry" "rimuovi la voce del database")
("remove downwards" "rimuovi verso il basso")
("remove entries" "rimuovi voci")
("remove entry" "rimuovi voce")
("remove field above" "rimuovi campo sopra")
("remove field below" "rimuovi campo sotto")
("remove fields" "rimuovi campi")
("remove folded" "rimuovi piegato")
("remove from previous frames" "rimuovi dai frame precedenti")
("remove from subsequent frames" "rimuovi dai frame successivi")
("remove input field" "rimuovi campo di input")
("remove input field above" "rimuovi il campo di input sopra")
("remove last field" "rimuovi ultimo campo")
("remove leftwards" "rimuovi a sinistra")
("remove link" "rimuovi collegamento")
("remove next field" "rimuovi campo successivo")
("remove overlay after" "rimuovi overlay dopo")
("remove overlay before" "rimuovi overlay prima")
("remove package" "rimuovi pacchetto")
("remove previous field" "rimuovi campo precedente")
("remove rightwards" "rimuovi a destra")
("remove selected database entries" "rimuovi voci di database selezionate")
("remove selected entries" "rimuovi voci selezionate")
("remove slide after" "rimuovi diapositiva dopo")
("remove slide before" "rimuovi diapositiva prima")
("remove superfluous invisible operators" "rimuovi operatori invisibili superflui")
("remove tag" "rimuovi tag")
("remove this branch" "rimuovi questo ramo")
("remove this frame" "rimuovi questo frame")
("remove unfolded" "rimuovi non spiegato")
("remove upwards" "rimuovi verso l'alto")
("removed entries from database" "voci rimosse dal database")
("removed entry from database" "voce rimossa dal database")
("rename" "rinomina")
("rename section" "rinomina sezione")
("rendering" "rendering")
("rendering options for tag" "opzioni di rendering per tag")
("repeat" "ripeti")
("replace TeXmacs styles with no LaTeX equivalents" "sostituisci gli stili TeXmacs senza equivalenti LaTeX")
("replace all further occurrences" "sostituisci tutte le altre occorrenze")
("replace one occurrence" "Sostituisci un'occorrenza")
("replace toolbar" "Sostituisci barra degli strumenti")
("replace unrecognized styles" "sostituisci stili non riconosciuti")
("reset error counters" "ripristina contatori errori")
("resize" "ridimensiona")
("resize objects" "ridimensiona oggetti")
("restart TeXmacs in order to let changes take effect" "riavvia TeXmacs per rendere effettive le modifiche")
("restart in order to let the new look and feel take effect" "riavvia per rendere effettivo il nuovo aspetto")
("retain" "conserva")
("retime" "retime")
("retina settings" "impostazioni della retina")
("retrieve email" "recupera email")
("retrieve remote live document" "recupera documento live remoto")
("retrieved contents" "contenuti recuperati")
("retro" "retro")
("reverse" "reverse")
("reverse ordering" "ordine inverso")
("ridged paper" "carta increspata")
("right arrow" "freccia destra")
("right baseline" "baseline destra")
("right cell border" "bordo destro della cella")
("right cell padding" "imbottitura per cella destra")
("right down" "a destra")
("right on even pages" "proprio su pagine pari")
("right table border" "bordo destro del tavolo")
("right table padding" "imbottitura del tavolo a destra")
("right up" "a destra")
("rightwards" "verso destra")
("rigid box" "scatola rigida")
("rotate" "ruota")
("rotate objects" "ruota oggetti")
("rough" "grezzo")
("rough paper" "carta ruvida")
("round" "rotondo")
("round overbrace" "overbrace tondo")
("round underbrace" "sottotazza rotonda")
("row above" "riga sopra")
("row below" "riga sotto")
("rows" "righe")
("run" "corsa")
("run current file" "esegui file corrente")
("same names" "stessi nomi")
("same screen margins as on paper" "stessi margini dello schermo della carta")
("sample text" "testo di esempio")
("save auxiliary data" "salva dati ausiliari")
("save entries" "salva voci")
("save entry" "salva voce")
("save image as" "salva immagine come")
("save position" "salva posizione")
("save remote file" "salva file remoto")
("saved modifications in database" "modifiche salvate nel database")
("scheme command" "comando schema")
("scheme developers guide" "guida per sviluppatori di schemi")
("scheme extensions" "estensioni di schema")
("scheme interface for the graphical mode" "interfaccia schema per la modalità grafica")
("screen" "schermo")
("screen rendering" "rendering dello schermo")
("screens" "schermi")
("screenshot" "screenshot")
("scripting language" "linguaggio di scripting")
("scripts" "script")
("search and replace" "cerca e sostituisci")
("search in database" "cerca nel database")
("search results for" "risultati della ricerca per")
("search toolbar" "barra degli strumenti di ricerca")
("search words in my documents" "cerca parole nei miei documenti")
("search words in the documentation" "cerca parole nella documentazione")
("search words in the source code" "cerca parole nel codice sorgente")
("second" "secondo")
("secret keys" "chiavi segrete")
("sections" "sezioni")
("see documentation" "vedi documentazione")
("select GnuPG recipients" "seleziona destinatari GnuPG")
("select background picture" "seleziona immagine di sfondo")
("select document style" "seleziona stile documento")
("select pen" "seleziona penna")
("select the action to be undertaken for each conflict" "seleziona l'azione da intraprendere per ogni conflitto")
("select view mode" "seleziona modalità di visualizzazione")
("semantic correctness" "correttezza semantica")
("semantic editing" "editing semantico")
("semantic selections" "selezioni semantiche")
("semantics" "semantica")
("sending commands to TeXmacs" "invio comandi a TeXmacs")
("senior" "senior")
("serif" "serif")
("server" "server")
("server licence agreement" "accordo di licenza del server")
("session commands" "comandi di sessione")
("set default" "imposta predefinito")
("set difference" "imposta differenza")
("set intersection" "imposta incrocio")
("set number of columns" "imposta il numero di colonne")
("set number of rows" "imposta il numero di righe")
("set or get environment variables" "imposta o ottieni variabili d'ambiente")
("set properties" "imposta proprietà")
("set union" "set union")
("set user information" "imposta informazioni utente")
("seventh" "settimo")
("several equations" "diverse equazioni")
("shadow" "ombra")
("shadowed" "ombreggiato")
("shadowed raise" "rilancio ombreggiato")
("shift" "shift")
("short" "corto")
("show all parts" "mostra tutte le parti")
("show current focus" "mostra lo stato attuale")
("show full context" "mostra contesto completo")
("show hidden" "mostra nascosta")
("show key presses" "mostra pressione dei tasti")
("show main document" "mostra documento principale")
("show memory usage" "mostra utilizzo memoria")
("show one part" "mostra una parte")
("show panorama" "mostra panorama")
("show preamble" "mostra il preambolo")
("show several parts" "mostra più parti")
("show subunits" "mostra subunità")
("show table cells" "mostra celle della tabella")
("show timings" "mostra tempi")
("side tools" "utensili laterali")
("simple" "semplice")
("simple form" "forma semplice")
("simple widget" "widget semplice")
("simplification" "semplificazione")
("simplified evaluation of formulas" "valutazione semplificata delle formule")
("simplified menus" "menu semplificati")
("simplify" "semplificare")
("sine" "seno")
("sixth" "sesto")
("size tag" "tag taglia")
("skew" "inclinazione")
("skin" "pelle")
("skip all" "salta tutto")
("slant" "inclinato")
("slashed fraction" "frazione ridotta")
("slides" "diapositive")
("slovene" "sloveno")
("slow" "lento")
("slow decrease" "diminuzione lenta")
("slow increase" "aumento lento")
("small Capitals" "piccoli capitali")
("small capitals" "piccole capitali")
("small environment box" "piccola scatola ambientale")
("small focus" "messa a fuoco piccola")
("small inline" "piccolo in linea")
("small inline fraction" "piccola frazione in linea")
("smash" "smash")
("smooth" "liscio")
("smooth end" "estremità liscia")
("smooth extremities" "estremità lisce")
("smooth start" "avvio regolare")
("snap" "snap")
("snap distance" "distanza di scatto")
("snap to curves" "aggancio alle curve")
("snap to grid" "aggancia alla griglia")
("snap to grid curve" "aggancia alla curva della griglia")
("snap to intersections of curves" "snap alle intersezioni di curve")
("snap to text borders" "aggancia ai bordi del testo")
("snap to text corners" "aggancia agli angoli del testo")
("solution" "soluzione")
("solution to exercise" "soluzione per l'esercizio")
("solution to problem" "soluzione al problema")
("solutions" "soluzioni")
("sound" "suono")
("source" "fonte")
("source macros tool" "strumento macro di origine")
("source tags" "tag di origine")
("south" "sud")
("south east" "sud-est")
("space bar in math mode" "barra spaziatrice in modalità matematica")
("space bar in text mode" "barra spaziatrice in modalità testo")
("space stretchability" "estensibilità dello spazio")
("span" "span")
("span over all columns" "si estendono su tutte le colonne")
("special functions" "funzioni speciali")
("special properties" "proprietà speciali")
("specific baseline" "linea di base specifica")
("specified" "specificato")
("specify color alternation" "specifica alternanza di colore")
("specify how to traverse the manual" "specifica come attraversare il manuale")
("specify semantics of a symbol or formula" "specifica la semantica di un simbolo o formula")
("specify the size of the table" "specifica la dimensione della tabella")
("specify user identity" "specifica l'identità dell'utente")
("spell check" "controllo ortografico")
("spline" "spline")
("split program" "programma diviso")
("split session" "sessione divisa")
("square" "quadrato")
("square overbrace" "quadrato overbrace")
("square underbrace" "sottosella quadrato")
("stack" "pila")
("standard" "standard")
("standard Output" "Uscita standard")
("standard TeXmacs styles" "stili TeXmacs standard")
("standard environment variables" "variabili di ambiente standard")
("standard formats" "formati standard")
("standard fraction" "frazione standard")
("star" "stella")
("start server" "start server")
("statement" "dichiarazione")
("statistics" "statistiche")
("status" "status")
("stop server" "stop server")
("storage" "archiviazione")
("store tracking information in LaTeX files" "Memorizza le informazioni di tracciamento nei file LaTeX")
("stretch" "tratto")
("stretch factor" "fattore di allungamento")
("stretched" "allungato")
("strict Ascii" "Ascii rigoroso")
("strike through" "barrato")
("structured insert above" "inserto strutturato sopra")
("structured insert at the left" "inserto strutturato a sinistra")
("structured insert at the right" "inserto strutturato a destra")
("structured insert below" "inserto strutturato sotto")
("structured remove downwards" "rimuovi strutturato verso il basso")
("structured remove leftwards" "strutturato rimuovi a sinistra")
("structured remove rightwards" "rimuovi strutturato verso destra")
("structured remove upwards" "rimuovi strutturato verso l'alto")
("structured variant" "variante strutturata")
("style options" "opzioni di stile")
("style parameters" "parametri di stile")
("stylesheet language" "lingua del foglio di stile")
("subject" "soggetto")
("submenu" "sottomenu")
("subscript below" "pedice in basso")
("subsubmenu" "sottomenu")
("subsubsubmenu" "subsubsubmenu")
("subsubsubsubmenu" "subsubsubsubmenu")
("subtable" "sottotabella")
("subtitle" "sottotitoli")
("subtraction" "sottrazione")
("summarized" "riassunto")
("superscript above" "apice sopra")
("supported plug-ins" "plug-in supportati")
("surface" "superficie")
("inflate" "rigonfiamento")
("swiss" "svizzero")
("switch to buffer" "passa al buffer")
("symbol browser" "browser dei simboli")
("symbol properties not found" "proprietà simbolo non trovato")
("symbols" "simboli")
("synchronization status" "stato della sincronizzazione")
("synchronize" "sincronizza")
("synchronize bibliographic references" "sincronizza i riferimenti bibliografici")
("synchronize file or directory" "sincronizza file o directory")
("synchronize with remote server" "sincronizza con server remoto")
("synopsis" "sinossi")
("system command" "comando di sistema")
("tab-completion" "completamento scheda")
("tabbed" "a schede")
("table breaking" "rottura della tabella")
("table height" "altezza tavolo")
("table properties" "proprietà della tabella")
("table width" "larghezza tavolo")
("tags with special rendering" "tag con rendering speciale")
("tangent" "tangente")
("teXmacs DTD" "teXmacs DTD")
("teXmacs buffer expected" "buffer TeXmacs previsto")
("teXmacs buffer on disk expected" "buffer TeXmacs su disco previsto")
("teXmacs database preferences" "Preferenze del database teXmacs")
("teXmacs extensions to scheme and utilities" "estensioni di TeXmacs allo schema e alle utilità")
("teXmacs macro" "macro TeXmacs")
("teXmacs package" "pacchetto TeXmacs")
("teXmacs plugins" "plugin TeXmacs")
("teXmacs primitives" "primitivi TeXmacs")
("teXmacs style" "stile TeXmacs")
("test routine" "routine di test")
("testing tree-view" "test ad albero")
("text borders" "bordi del testo")
("text box style" "stile casella di testo")
("text corners" "angoli del testo")
("text padding" "imbottitura di testo")
("textual" "testuale")
("textual operator" "operatore testuale")
("textual spreadsheet" "foglio di calcolo testuale")
("the TeXmacs format" "il formato TeXmacs")
("the TeXmacs plug-in system" "il sistema plug-in TeXmacs")
("the document has not been saved" "il documento non è stato salvato")
("theme parameters" "parametri del tema")
("these collected public keys will be definitely lost" "queste chiavi pubbliche raccolte andranno sicuramente perse")
("these public keys will be definitely lost" "queste chiavi pubbliche andranno sicuramente perse")
("these secret keys will be definitely lost" "queste chiavi segrete andranno sicuramente perse")
("thicken" "addensare")
("thin" "sottile")
("third" "terzo")
("this" "questo")
("this column" "questa colonna")
("this page footer" "piè di pagina")
("this page header" "intestazione di questa pagina")
("this page number" "questo numero di pagina")
("this row" "questa riga")
("this style specifies page margins in the TeX way" "questo stile specifica i margini della pagina nel modo TeX")
("three columns" "tre colonne")
("three dots" "tre punti")
("three times" "tre volte")
("through popup windows" "attraverso le finestre popup")
("through the menus" "attraverso i menu")
("thumbnails" "miniature")
("time evolution" "evoluzione del tempo")
("timings" "tempi")
("title presentation options" "opzioni di presentazione del titolo")
("title style" "stile del titolo")
("title suffix" "suffisso del titolo")
("titled block" "blocco intitolato")
("toggle cell wrapping mode" "attiva / disattiva modalità di avvolgimento cella")
("toggle here" "attiva / disattiva qui")
("toggle name" "attiva / disattiva nome")
("toggle numbering" "Attiva / disattiva numerazione")
("toggle off" "toggle off")
("toggle on" "attiva / disattiva")
("toggle specification" "Attiva / disattiva specifica")
("toggle titled" "Attiva / disattiva titolato")
("tolerant" "tollerante")
("top baseline" "linea di base superiore")
("top cell border" "bordo superiore della cella")
("top cell padding" "imbottitura cella superiore")
("top table border" "bordo del tavolo superiore")
("top table padding" "imbottitura tavolo superiore")
("transform" "trasforma")
("transform cell into subtable" "trasforma cella in sottotabella")
("translations" "traduzioni")
("translations loaded" "traduzioni caricate")
("transpose" "trasporre")
("traversal" "traversal")
("traverse" "traversa")
("triangle" "triangolo")
("triangularize" "triangolare")
("trigonometric" "trigonometrico")
("trigonometry" "trigonometria")
("turn off" "spegni")
("turn on" "accendi")
("turn on wallet" "attiva portafoglio")
("twice" "due volte")
("two columns" "due colonne")
("two dots" "due punti")
("type a latex command followed by return" "digitare un comando in lattice seguito da return")
("unchanged" "invariato")
("underbrace" "sottosuolo")
("underline" "sottolineato")
("underlined" "sottolineato")
("unevaluated argument" "argomento non valutato")
("unevaluated value" "valore non valutato")
("unextended" "non esteso")
("unfold" "spiegato")
("unfold all" "spiega tutto")
("unfold all fields" "spiega tutti i campi")
("unfolded" "spiegato")
("unit" "unità")
("unit length" "unità di lunghezza")
("unknown secret key fingerprint" "impronta digitale chiave segreta sconosciuta")
("unregistered file" "file non registrato")
("unroll" "srotolare")
("unsecure script refused" "rifiuto dello script non sicuro")
("unsupported link mode" "modalità di collegamento non supportata")
("until" "fino a")
("untitled block" "blocco senza titolo")
("up to date" "aggiornato")
("update buffer" "buffer di aggiornamento")
("update this buffer" "aggiorna questo buffer")
("update web site" "sito web di aggiornamento")
("upight" "upight")
("upload" "upload")
("upload file or directory" "carica file o directory")
("upright" "verticale")
("upwards" "verso l'alto")
("url" "url")
("use CSS for more advanced formatting" "usa CSS per una formattazione più avanzata")
("use MathML" "usa MathML")
("use as master" "usa come maestro")
("use extensible brackets" "usa parentesi estensibili")
("use high resolution fonts" "usa caratteri ad alta risoluzione")
("use high resolution icons" "usa icone ad alta risoluzione")
("use line wrapping for lines which are longer than 80 characters" "usa il ritorno a capo per righe che superano gli 80 caratteri")
("use margin kerning (protrusion)" "usa la crenatura del margine (sporgenza)")
("use print dialogue" "usa dialoghi di stampa")
("use protrusion" "usa sporgenza")
("use relative path" "usa percorso relativo")
("use retina fonts" "usa caratteri retina")
("use retina icons" "usa icone retina")
("use unified toolbars" "usa barre degli strumenti unificate")
("user interface" "interfaccia utente")
("user interface language" "lingua dell'interfaccia utente")
("user preferences" "preferenze dell'utente")
("users of Cyrillic languages" "utenti delle lingue cirilliche")
("users of oriental languages" "utenti di lingue orientali")
("utf-8 with inputenc" "utf-8 con inputenc")
("utf-8 with inputenc LaTeX package" "utf-8 con pacchetto LaTeX inputenc")
("utilities" "programmi di utilità")
("vanish" "svanire")
("verbose" "verboso")
("version" "versione")
("versioning tool" "strumento di versioning")
("vertical alignment" "allineamento verticale")
("vertical margins" "margini verticali")
("vertical space after" "spazio verticale dopo")
("vertical space before" "spazio verticale prima")
("vertical space stretchability" "estensibilità dello spazio verticale")
("visible except here" "visibile tranne qui")
("visible from here on" "visibile da qui in poi")
("visible only here" "visibile solo qui")
("visible until here" "visibile fino a qui")
("visited loci" "loci visitati")
("wallet" "portafoglio")
("wave" "onda")
("web" "web")
("weight" "peso")
("when line wrapping" "quando si avvolge la linea")
("when wrapping" "quando si avvolge")
("whitespace" "spazi bianchi")
("wide" "largo")
("wide bar" "barra larga")
("wide block" "blocco largo")
("wide colored" "wide coloured")
("wide float" "galleggiante largo")
("wide footnote" "nota a piè di pagina")
("wide tabular" "wide tabular")
("widescreen" "widescreen")
("with newer version" "con la versione più recente")
("with older version" "con versione precedente")
("wrap lines" "linee di avvolgimento")
("write a macro" "scrivi una macro")
("writing TeXmacs bibliography styles" "scrivere stili bibliografici di TeXmacs")
("writing documentation" "documentazione scritta")
("written with TeXmacs" "scritto con TeXmacs")
("wrong empty passphrase" "passphrase vuota errata")
("wrong passphrase" "passphrase errata")
("year" "anno")
("year, Name" "anno, nome")
("you are attempting to open an encrypted file while" "stai tentando di aprire un file crittografato mentre")
("you might consider enabling the experimental" "potresti considerare di abilitare l'esperimento")
("you must add a bibliography file" "devi aggiungere un file bibliografico")
("you should also make sure that GnuPG is installed" "dovresti anche assicurarti che GnuPG sia installato")
("your language" "la tua lingua")
("your personal dictionary has been modified" "il tuo dizionario personale è stato modificato")
("zebra" "zebra")
("zoom" "zoom")
("zoom in" "zoom in")
("zoom out" "zoom indietro")
("zoom/unzoom objects" "oggetti zoom / unzoom")
