("\"encryption\" features from the preference panel" "")
("(Re)Build autocompletion index" "")
("a.C.M. computing class" "")
("a.M.S. subject class" "")
("abbreviated authors" "")
("abreviated authors" "")
("accept during this pass" "")
("active link types" "")
("add" "")
("add abstract information" "")
("add author information" "")
("add title information" "")
("addition" "")
("adjust limits" "")
("advanced font customization" "")
("affiliation" "")
("align cell to the decimal comma" "")
("align cell to the decimal dot" "")
("align table at axis" "")
("alignment of balloon" "")
("all cells" "")
("all data attached to this identity will be lost" "")
("all saved passphrases will be lost forever" "")
("allowed page height extension" "")
("allowed page height reduction" "")
("allowed positions" "")
("allowed positions of floating object" "")
("alpha transparency" "")
("alter" "")
("alternate" "")
("alternate except here" "")
("alternate from here on" "")
("alternate only here" "")
("alternate until here" "")
("amplified" "")
("and perform casual settings from the \"Encryption\" tab" "")
("animate" "")
("animate folding" "")
("animate unfolding" "")
("animated" "")
("annotate" "")
("answer field" "")
("answer to question" "")
("answers only" "")
("any" "")
("appear" "")
("approximate" "")
("arc cosine" "")
("arc sine" "")
("arc tangent" "")
("are you sure you want to delete collected public keys" "")
("are you sure you want to delete selected public keys" "")
("are you sure you want to delete selected secret keys" "")
("are you sure you want to destroy the wallet" "")
("art frame" "")
("arxiv category" "")
("aspect" "")
("auto" "")
("auto-save file" "")
("automatic program brackets" "")
("automatically import bibliographies when opening files" "")
("automatically remember all passphrases in the wallet" "")
("backtrace errors" "")
("beamer formats" "")
("beamer theme" "")
("bench" "")
("bend bottom" "")
("bend corner" "")
("bend diagonal" "")
("bend in" "")
("bend out" "")
("bezier" "")
("bibTeX command" "")
("bidirectional" "")
("big environment box" "")
("big focus" "")
("binary operator" "")
("bitmap resolution (dpi)" "")
("black floral I" "")
("black floral II" "")
("blackboard embold" "")
("block" "")
("blur" "")
("bottom baseline" "")
("bottom tools" "")
("box" "")
("buffer management" "")
("buffer must be on disk" "")
("buffer must have a name" "")
("build buffer" "")
("build buffer in" "")
("build directory" "")
("build directory in" "")
("build link pages" "")
("build-all" "")
("bump" "")
("busy" "")
("cJK" "")
("cJK spacing" "")
("cancelled" "")
("cannot download directory to file" "")
("cannot rename across different servers" "")
("cannot upload directory to file" "")
("caps-lock key" "")
("carved wood" "")
("case-insensitive search" "")
("categories" "")
("category" "")
("cell properties" "")
("change default unit" "")
("change passphrase" "")
("change step-size" "")
("change the style of mathematical formulas" "")
("character contraction" "")
("character expansion" "")
("checkable field" "")
("cipher algorithm for passphrase encryption" "")
("classification" "")
("clean slate" "")
("clear local information" "")
("click Ok button twice to discard this warning" "")
("clip" "")
("clipboard image format" "")
("close animation tool" "")
("close program" "")
("close replace tool" "")
("close search tool" "")
("close spell tool" "")
("close translations to rebuild" "")
("closed bezier" "")
("closed curve" "")
("closed smooth" "")
("cluster by affiliation" "")
("collect garbage" "")
("collected keys" "")
("columns separation" "")
("commit file" "")
("common" "")
("commutative diagram" "")
("complete bibliographic reference" "")
("compound" "")
("compress into toolbar" "")
("compressed" "")
("conceal" "")
("configure look and feel" "")
("confirm database entry" "")
("confirm entry" "")
("confirm selected database entries" "")
("confirm selected entries" "")
("conservative conversion options" "")
("constellation" "")
("context aids" "")
("contextual hints" "")
("continue" "")
("continued fraction" "")
("contour" "")
("contract logarithms" "")
("convertible" "")
("copyright" "")
("cork charset with TeX catcode definition in preamble" "")
("correct" "")
("correct all" "")
("correct formula" "")
("correct manually" "")
("correct mathematical formulas" "")
("correction" "")
("cosine" "")
("create link" "")
("create remote directory" "")
("create remote file" "")
("create subprogram" "")
("create table macro" "")
("creating new account" "")
("crop marks" "")
("cross" "")
("crossed boxes" "")
("crossed circles" "")
("current user version" "")
("cursor" "")
("curve intersections" "")
("curve points" "")
("customizations" "")
("custum tab" "")
("data" "")
("database entry" "")
("dead" "")
("debugging console" "")
("decomposed" "")
("decorated" "")
("decorated wood" "")
("decrease size" "")
("decrypt" "")
("default size" "")
("degrade" "")
("degraded" "")
("delete entries" "")
("delete link" "")
("deleted" "")
("destroy" "")
("determine margins from text width" "")
("device" "")
("diamond" "")
("differentiate" "")
("dilate" "")
("direction of progression" "")
("direction of translation" "")
("disable coloring on paper" "")
("disable encryption" "")
("disappear" "")
("dissociate joined cells" "")
("distort" "")
("distorted" "")
("division" "")
("document font selector" "")
("document language" "")
("document page format" "")
("document paragraph format" "")
("document updates run" "")
("dragging" "")
("draw over" "")
("drop" "")
("due to" "")
("eRROR" "")
("edit animation" "")
("edit groups of objects" "")
("edit macros" "")
("edit preamble" "")
("effect pen" "")
("eigenvalues" "")
("eighth" "")
("embold" "")
("emboss" "")
("enable page breaking" "")
("encrypt" "")
("encryption" "")
("encryption facilities are not currently available" "")
("encryption facilities have not been enabled for TeXmacs" "")
("enforce brackets to match" "")
("engrave" "")
("enter graphics" "")
("enter graphics mode" "")
("enter new passphrase for encryption" "")
("enter passphrase for decryption" "")
("enter passphrase for identity" "")
("enter title information" "")
("entry up to date in database" "")
("enumerate|Alpha" "")
("enumerate|Roman" "")
("enumerate|alpha" "")
("enumerate|roman" "")
("environment variable" "")
("environments" "")
("erode" "")
("error output" "")
("error status report" "")
("error: bracket does not match" "")
("error: cyclic or missing chunks detected" "")
("error: file not found" "")
("error: ghostview does not seem to be installed on your system" "")
("error: one of the alternatives should be filled out" "")
("error: only one alternatives should be filled out" "")
("error: should fill out name for referencing" "")
("error: should fill out required field" "")
("evaluable field" "")
("evaluate fields in order" "")
("evaluate script" "")
("evaluation switch" "")
("evaluation tag" "")
("even page" "")
("even pages" "")
("events" "")
("execution of scripts" "")
("exit graphics" "")
("exit graphics mode" "")
("expand TeXmacs macros with no LaTeX equivalents" "")
("expand beamer slides" "")
("expand logarithms" "")
("expand trigonometric functions" "")
("expanded" "")
("experimental features (to be used with care)" "")
("explain" "")
("explanatory item" "")
("explicit keystroke" "")
("explicit margins" "")
("exponential" "")
("export bibliography" "")
("export entries in buffer" "")
("export file" "")
("export mathematical formulas as MathML" "")
("export mathematical formulas as images" "")
("export selected entries" "")
("export selection" "")
("export selections as" "")
("exported bibliographic entries" "")
("exported bibliographic references" "")
("extend" "")
("extended" "")
("extensible left arrow" "")
("extensible right arrow" "")
("extern" "")
("external" "")
("extra branch" "")
("extra interline space" "")
("extra name" "")
("extract" "")
("extract style file" "")
("extract style package" "")
("factor" "")
("fade" "")
("fade in" "")
("fade out" "")
("fast" "")
("fast decrease" "")
("fast environments" "")
("fast increase" "")
("field reference" "")
("fifth" "")
("file saved" "")
("fill out" "")
("filter" "")
("find file" "")
("finished collecting symbols documentation" "")
("first chunk" "")
("first error" "")
("first occurrence" "")
("five columns" "")
("flag is off" "")
("flag is on" "")
("flatten" "")
("floating phantom" "")
("fold all" "")
("fold back" "")
("follow external links" "")
("follow inverse links" "")
("font selector" "")
("for each" "")
("four columns" "")
("four dots" "")
("fourth" "")
("fraktur" "")
("framed" "")
("from" "")
("full" "")
("full author list" "")
("gap" "")
("garbage collection" "")
("gaussian" "")
("gcd" "")
("generated LaTeX document contains no errors" "")
("generated field" "")
("get arity" "")
("get label" "")
("get list with remote versions" "")
("glyphs" "")
("gnaw" "")
("gnawed" "")
("gnuPG command" "")
("gnuPG error: buffer encryption failed" "")
("gnuPG error: cannot find suitable secret key to decrypt" "")
("gnuPG requires name and email to have at least 5 characters" "")
("go to anchor" "")
("go to anchor or float" "")
("go to anchor or footnote" "")
("go to float" "")
("go to footnote" "")
("granite" "")
("graphical interface font scale" "")
("graphics geometry" "")
("graphics grids" "")
("greyed" "")
("grid curves" "")
("grid points" "")
("grid-curve intersections" "")
("group of objects" "")
("grouped" "")
("guarantee transparent source tracking" "")
("half wide" "")
("hand drawn" "")
("headers" "")
("homoglyph substitutions" "")
("horizontal collapse distance" "")
("horizontal margins" "")
("horizontal table alignment" "")
("hyphenate as" "")
("icon" "")
("ignore" "")
("impact" "")
("import bibliography" "")
("import database entry" "")
("import entries in buffer" "")
("import entry" "")
("import file" "")
("import selected database entries" "")
("import selected entries" "")
("import selections as" "")
("import sophisticated objects as pictures" "")
("imported bibliographic entries" "")
("inanimated" "")
("inch" "")
("incomplete entries found to be filled out" "")
("increase size" "")
("indent paragraphs" "")
("indication" "")
("initialize" "")
("ink here" "")
("ink in" "")
("ink out" "")
("inline" "")
("inline content" "")
("inner bottom" "")
("inner left" "")
("inner right" "")
("inner top" "")
("input command" "")
("input field" "")
("insert a gap" "")
("insert a multiple choice" "")
("insert a new entry" "")
("insert a prominent piece of text" "")
("insert a question" "")
("insert a root" "")
("insert a section block" "")
("insert a textual operation" "")
("insert abstract" "")
("insert an answer" "")
("insert an enunciation" "")
("insert annotation" "")
("insert copyright and license information" "")
("insert explanatory item" "")
("insert large delimiters" "")
("insert last name" "")
("insert missing invisible operators" "")
("insert more names" "")
("insert particle" "")
("insert similar above" "")
("insert similar below" "")
("insert similar block above" "")
("insert similar block below" "")
("insert subtable" "")
("insert symbol documentation" "")
("insert template" "")
("insert title after name" "")
("insert user interface related markup" "")
("inserting control points" "")
("integrate" "")
("intercharacter compression" "")
("intercharacter stretching" "")
("interrupted" "")
("invalid multi-paragraph selection" "")
("invalid renaming" "")
("invert" "")
("inverted breve" "")
("invisible ending" "")
("invisible newline" "")
("invisible opening" "")
("join selected cells" "")
("jump in" "")
("junior" "")
("keep evaluated expressions" "")
("keep local" "")
("keep remote" "")
("keep track of source code" "")
("keep unfolded" "")
("large cells" "")
("large displayed" "")
("large displayed fraction" "")
("large tables" "")
("last error" "")
("last name" "")
("last occurrence" "")
("lcm" "")
("left axis" "")
("left baseline" "")
("left bottom" "")
("left center" "")
("left click: add point; Right click: undo" "")
("left click: finish; Right click: undo" "")
("left click: new object" "")
("left click: operate" "")
("left down" "")
("left on even pages" "")
("left top" "")
("left up" "")
("left-right arrow" "")
("let the environment float" "")
("line breaking" "")
("line wrapping" "")
("linear 2D" "")
("lines around" "")
("link image and copies as" "")
("link image as" "")
("link mode" "")
("link to URL" "")
("live" "")
("live input-output" "")
("load help file" "")
("load remote file" "")
("loading" "")
("local entries" "")
("loci" "")
("locus" "")
("locus rendering" "")
("logarithm" "")
("logging in" "")
("logical and" "")
("logical implication" "")
("logical not" "")
("logical or" "")
("login" "")
("logout" "")
("long macro" "")
("long text" "")
("loops" "")
("macro argument" "")
("macro definition" "")
("macro name" "")
("magnify horizontally" "")
("magnify vertically" "")
("main presentation style" "")
("make a letter environment" "")
("make a multi-slide presentation" "")
("make floating" "")
("make link" "")
("make non floating" "")
("manila paper" "")
("map arguments" "")
("marginal note" "")
("margins from width" "")
("margins on paper" "")
("margins on screen" "")
("marked" "")
("material" "")
("matrices" "")
("maximal cell height" "")
("maximal clustering" "")
("maximal table height" "")
("maximal table width" "")
("maximum" "")
("meander" "")
("menu" "")
("merge lines into paragraphs unless separated by blank lines" "")
("messages" "")
("meta data" "")
("metal" "")
("middle baseline" "")
("minimal cell height" "")
("minimal cell width" "")
("minimal line separation" "")
("minimal table height" "")
("minimal table width" "")
("minimum" "")
("mirror" "")
("miscellanous" "")
("modify remote live document" "")
("module" "")
("monospaced" "")
("more information about GNU TeXmacs can be found in the Help->About menu" "")
("more information about GNU TeXmacs can be found in the help" "")
("motion" "")
("mouse over object" "")
("move objects" "")
("move over object on which to operate" "")
("multiline" "")
("multiple choice" "")
("multiplication" "")
("navigation options" "")
("new account" "")
("new bibliography dialogue" "")
("new entry" "")
("new identity" "")
("new locus" "")
("new macro" "")
("new passphrase" "")
("new remote directory" "")
("new remote file" "")
("new style fonts" "")
("new style page breaking" "")
("newer version" "")
("next chunk" "")
("next error" "")
("next occurrence" "")
("next screen" "")
("no clustering" "")
("no completions" "")
("no errors have been corrected" "")
("no new public key in document" "")
("no page numbers" "")
("no parent" "")
("no selection" "")
("no spelling errors" "")
("normal loci" "")
("not allowed to remove home directory" "")
("not connected to server" "")
("not yet implemented" "")
("notebook" "")
("numeric spreadsheet" "")
("odd page" "")
("odd pages" "")
("of fingerprint" "")
("older version" "")
("on your system and set it up from the \"Security\" tab" "")
("one error has been corrected" "")
("one lower case letter, one non alpha-numeric symbol" "")
("one numeric character, one upper case letter" "")
("only convert changes when re-importing" "")
("only convert changes with respect to imported version" "")
("only convert changes with respect to tracked version" "")
("only implemented for complete subtrees" "")
("only keep folded" "")
("only keep unfolded" "")
("only show semantic focus" "")
("open bibliography" "")
("open identities" "")
("open key manager" "")
("open licence agreement" "")
("open mailbox" "")
("open tool in separate window" "")
("or give the complete path to the \"gpg\" or \"gpg2\" command" "")
("order" "")
("ordinary symbol" "")
("ornamented" "")
("other login" "")
("outer bottom" "")
("outer left" "")
("outer right" "")
("outer top" "")
("outline" "")
("outlined" "")
("outlined emboss" "")
("outlined engrave" "")
("oval" "")
("overlap" "")
("overlay" "")
("overlays" "")
("overlined" "")
("padded" "")
("page background" "")
("page break after" "")
("page breaking algorithm" "")
("page number" "")
("page number rendering" "")
("page rendering" "")
("panorama" "")
("paragraphs" "")
("parenthesis" "")
("parenthesized" "")
("particle" "")
("passphrase encryption" "")
("passphrase wallet facilities are not currently available" "")
("passphrases are expected to have at least: 8 characters" "")
("passphrases mismatch" "")
("pastel" "")
("pattern" "")
("pause" "")
("pen width" "")
("permanently add to dictionary" "")
("permanently insert into dictionary" "")
("permissions" "")
("phantom" "")
("phantoms" "")
("physics and astronomy class" "")
("picture" "")
("pine" "")
("plain" "")
("plain boxes" "")
("plain circles" "")
("play" "")
("play animation" "")
("please install GnuPG software from https://www.gnupg.org" "")
("plural" "")
("pop server settings" "")
("position of marginal note" "")
("poster formats" "")
("poster theme" "")
("postfix" "")
("preferences for editing mathematical formulas" "")
("preferences for tag" "")
("prefix" "")
("preserve" "")
("preview with ghostview" "")
("previous error" "")
("previous occurrence" "")
("previous screen" "")
("primitive or macro" "")
("print to file" "")
("printer setup" "")
("program bracket matching" "")
("program bracket selections" "")
("program commands" "")
("provoke C++ error" "")
("provoke menu error" "")
("provoke scheme error" "")
("public key encryption" "")
("public keys" "")
("pulse" "")
("qt GUI only, sorry. Use \"Export selection\"" "")
("qt-widgets" "")
("quantifier" "")
("quasi" "")
("questions only" "")
("questions with answers" "")
("quick evaluation of formulas" "")
("rank" "")
("raw" "")
("really delete user identity" "")
("recipients" "")
("recognize" "")
("rectangular" "")
("reduce" "")
("reduce trigonometric functions" "")
("reduced margins" "")
("regenerate" "")
("register file" "")
("relate" "")
("relation" "")
("release left button: finish editing" "")
("remote controllers with keyboard simulation" "")
("remote directory" "")
("remote servers" "")
("remove database entry" "")
("remove entries" "")
("remove entry" "")
("remove folded" "")
("remove link" "")
("remove selected database entries" "")
("remove selected entries" "")
("remove superfluous invisible operators" "")
("remove unfolded" "")
("removed entries from database" "")
("removed entry from database" "")
("rename" "")
("rename section" "")
("replace TeXmacs styles with no LaTeX equivalents" "")
("replace all further occurrences" "")
("replace one occurrence" "")
("reset error counters" "")
("resize objects" "")
("restart TeXmacs in order to let changes take effect" "")
("restart in order to let the new look and feel take effect" "")
("retime" "")
("retina settings" "")
("retrieve email" "")
("retrieve remote live document" "")
("retrieved contents" "")
("reverse" "")
("reverse ordering" "")
("ridged paper" "")
("right baseline" "")
("right down" "")
("right on even pages" "")
("right up" "")
("rigid box" "")
("rotate objects" "")
("rough paper" "")
("round overbrace" "")
("round underbrace" "")
("run current file" "")
("same names" "")
("same screen margins as on paper" "")
("sample text" "")
("save auxiliary data" "")
("save entries" "")
("save entry" "")
("save image as" "")
("save position" "")
("save remote file" "")
("saved modifications in database" "")
("screen" "")
("screen rendering" "")
("screenshot" "")
("scripting language" "")
("search and replace" "")
("second" "")
("secret keys" "")
("sections" "")
("see documentation" "")
("select pen" "")
("select the action to be undertaken for each conflict" "")
("select view mode" "")
("senior" "")
("serif" "")
("server" "")
("set default" "")
("set difference" "")
("set intersection" "")
("set properties" "")
("set union" "")
("set user information" "")
("seventh" "")
("shadow" "")
("shadowed" "")
("shadowed raise" "")
("shift" "")
("show current focus" "")
("show full context" "")
("show key presses" "")
("show main document" "")
("show table cells" "")
("side tools" "")
("simple" "")
("simplified evaluation of formulas" "")
("simplify" "")
("sine" "")
("sixth" "")
("skew" "")
("skip all" "")
("slant" "")
("slashed fraction" "")
("slides" "")
("slow" "")
("slow decrease" "")
("slow increase" "")
("small capitals" "")
("small environment box" "")
("small focus" "")
("small inline" "")
("small inline fraction" "")
("smash" "")
("smooth" "")
("smooth end" "")
("smooth extremities" "")
("smooth start" "")
("snap" "")
("snap distance" "")
("snap to curves" "")
("snap to grid" "")
("snap to grid curve" "")
("snap to intersections of curves" "")
("snap to text borders" "")
("snap to text corners" "")
("solution to exercise" "")
("solution to problem" "")
("solutions" "")
("south" "")
("south east" "")
("space bar in math mode" "")
("space bar in text mode" "")
("space stretchability" "")
("span" "")
("span over all columns" "")
("special cell properties" "")
("special table properties" "")
("specific baseline" "")
("specify color alternation" "")
("specify how to traverse the manual" "")
("specify semantics of a symbol or formula" "")
("spell check" "")
("split program" "")
("square overbrace" "")
("square underbrace" "")
("standard Output" "")
("standard fraction" "")
("star" "")
("start server" "")
("statement" "")
("stop server" "")
("storage" "")
("store tracking information in LaTeX files" "")
("stretch factor" "")
("strict Ascii" "")
("strike through" "")
("structured variant" "")
("style options" "")
("style parameters" "")
("subject" "")
("submenu" "")
("subscript below" "")
("subsubmenu" "")
("subsubsubmenu" "")
("subsubsubsubmenu" "")
("subtraction" "")
("summarized" "")
("superscript above" "")
("supported plug-ins" "")
("swell" "")
("switch to buffer" "")
("symbol properties not found" "")
("symbols" "")
("synchronize" "")
("synchronize bibliographic references" "")
("synchronize with remote server" "")
("synopsis" "")
("tabbed" "")
("table breaking" "")
("table height" "")
("table properties" "")
("table width" "")
("tags with special rendering" "")
("tangent" "")
("teXmacs DTD" "")
("teXmacs buffer expected" "")
("teXmacs buffer on disk expected" "")
("teXmacs macro" "")
("teXmacs package" "")
("teXmacs plugins" "")
("teXmacs style" "")
("test routine" "")
("testing tree-view" "")
("text borders" "")
("text box style" "")
("text corners" "")
("textual" "")
("textual spreadsheet" "")
("theme parameters" "")
("these collected public keys will be definitely lost" "")
("these public keys will be definitely lost" "")
("these secret keys will be definitely lost" "")
("thicken" "")
("third" "")
("this" "")
("this page number" "")
("this style specifies page margins in the TeX way" "")
("three columns" "")
("three dots" "")
("through popup windows" "")
("through the menus" "")
("time evolution" "")
("timings" "")
("title presentation options" "")
("title style" "")
("title suffix" "")
("titled block" "")
("toggle cell wrapping mode" "")
("toggle here" "")
("toggle off" "")
("toggle on" "")
("tolerant" "")
("top baseline" "")
("transform cell into subtable" "")
("translations loaded" "")
("transpose" "")
("traversal" "")
("traverse" "")
("triangle" "")
("triangularize" "")
("trigonometric" "")
("turn off" "")
("turn on" "")
("two dots" "")
("type a latex command followed by return" "")
("underlined" "")
("unevaluated argument" "")
("unevaluated value" "")
("unfold all" "")
("unknown secret key fingerprint" "")
("unregistered file" "")
("unroll" "")
("unsecure script refused" "")
("unsupported link mode" "")
("until" "")
("untitled block" "")
("up to date" "")
("update buffer" "")
("upight" "")
("upload" "")
("use CSS for more advanced formatting" "")
("use MathML" "")
("use as master" "")
("use extensible brackets" "")
("use line wrapping for lines which are longer than 80 characters" "")
("use margin kerning (protrusion)" "")
("use protrusion" "")
("use relative path" "")
("user interface" "")
("utf-8 with inputenc LaTeX package" "")
("vanish" "")
("verbose" "")
("vertical margins" "")
("vertical space after" "")
("vertical space before" "")
("vertical space stretchability" "")
("vertical table alignment" "")
("visible except here" "")
("visible from here on" "")
("visible only here" "")
("visible until here" "")
("visited loci" "")
("wallet" "")
("wave" "")
("weight" "")
("when line wrapping" "")
("wide" "")
("wide block" "")
("wide colored" "")
("wide float" "")
("wide footnote" "")
("wide tabular" "")
("widescreen" "")
("wrong empty passphrase" "")
("wrong passphrase" "")
("year" "")
("you are attempting to open an encrypted file while" "")
("you might consider enabling the experimental" "")
("you must add a bibliography file" "")
("you should also make sure that GnuPG is installed" "")
("your personal dictionary has been modified" "")
