("\"encryption\" features from the preference panel" "\"funkce ²ifrování\" z panelu preferencí")
("(Re)Build autocompletion index" "(Re) Vytvo°ení indexu automatického dopl¬ování")
("a modifier" "modifikátor")
("a series" "série")
("a.C.M. computing class" "a.C.M. výpo£etní t°ída")
("a.M.S. subject class" "a.M.S. p°edm¥tová t°ída")
("abbreviated authors" "zkrácených autor·")
("abreviated authors" "zkrácených autor·")
("accent above" "p°ízvuk vý²e")
("accent below" "p°ízvuk níºe")
("accept during this pass" "p°ijmout b¥hem tohoto pr·chodu")
("acknowledgments" "potvrzení")
("activate hidden" "aktivovat skryté")
("activate once" "aktivovat jednou")
("activation" "aktivace")
("active link types" "aktivních typ· odkaz·")
("add" "p°idat")
("add abstract information" "p°idat abstraktní informace")
("add author information" "p°idat informace o autorovi")
("add branch after" "p°idat v¥tev po")
("add branch before" "p°idat v¥tve p°ed")
("add other package" "p°idat dal²í balí£ek")
("add package" "p°idat balí£ek")
("add style package" "p°idat balí£ek styl·")
("add title information" "p°idat informace o názvu")
("addition" "s£ítání")
("adjust" "upravit")
("adjust limits" "upravit limity")
("advanced font customization" "pokro£ilé úpravy písma")
("affiliation" "p°idruºení")
("align cell to the decimal comma" "zarovnat bu¬ku s desetinnou £árkou")
("align cell to the decimal dot" "zarovnat bu¬ku s desetinnou te£kou")
("align table at axis" "zarovnat tabulku na ose")
("aligned" "zarovnáno")
("alignment of balloon" "zarovnání balónu")
("all cells" "v²echny bu¬ky")
("all data attached to this identity will be lost" "v²echna data p°ipojená k této identit¥ budou ztracena")
("all saved passphrases will be lost forever" "v²echny uloºené p°ístupové fráze budou navºdy ztraceny")
("allow for macro definitions in preamble" "umoº¬ují definice maker v preambuli")
("allowed page height extension" "povolené roz²í°ení o vý²ku stránky")
("allowed page height reduction" "povolené sníºení vý²ky stránky")
("allowed positions" "povolených pozic")
("allowed positions of floating object" "povolené polohy plovoucího objektu")
("alpha transparency" "alfa pr·hlednost")
("also on paper" "také na papí°e")
("alter" "zm¥nit")
("alternate" "alternativní")
("alternate except here" "s výjimkou zde")
("alternate from here on" "st°ídav¥ odtud")
("alternate only here" "pouze zde")
("alternate until here" "aº dosud")
("alternative specification" "alternativní specifikace")
("always" "vºdy")
("american" "americký")
("amplified" "zesíleno")
("and perform casual settings from the \"Encryption\" tab" "a prove¤te náhodná nastavení na kart¥ \"²ifrování\"")
("angular" "úhlové")
("animate" "animovat")
("animate folding" "skládací animace")
("animate unfolding" "rozvíjející se animace")
("animated" "animovaných")
("animation" "animace")
("animation toolbar" "panel nástroj· pro animaci")
("annotate" "anotovat")
("answer" "odpov¥¤")
("answer field" "pole odpov¥di")
("answer to question" "odpov¥¤ na otázku")
("answers only" "Pouze odpov¥dí")
("any" "libovolných")
("appear" "Objeví se")
("apply macro" "pouºít makro")
("apply macro once" "pouºít makro jednou")
("approximate" "p°ibliºná")
("arc" "oblouk")
("arc cosine" "arc cosine")
("arc sine" "arc sine")
("arc tangent" "arc tangens")
("arch series" "oblouková °ada")
("are you sure you want to delete collected public keys" "Opravdu chcete smazat shromáºd¥né ve°ejné klí£e")
("are you sure you want to delete selected public keys" "jste si jisti, ºe chcete smazat vybrané ve°ejné klí£e")
("are you sure you want to delete selected secret keys" "Opravdu chcete smazat vybrané tajné klí£e")
("are you sure you want to destroy the wallet" "jste si jisti, ºe chcete zni£it pen¥ºenku")
("art frame" "um¥leckých rám·")
("arxiv category" "kategorie arxiv")
("as visual grid" "jako vizuální m°íºka")
("aspect" "aspekt")
("attach master" "p°ipojit master")
("auto" "auto")
("auto-save file" "automaticky ukládat soubor")
("automatic brackets" "automatických závorek")
("automatic content generation" "automatické generování obsahu")
("automatic program brackets" "automatické programové závorky")
("automatic quotes" "automatických nabídek")
("automatically close brackets" "automaticky zav°ít závorky")
("automatically import bibliographies when opening files" "automaticky importovat bibliografie p°i otevírání soubor·")
("automatically remember all passphrases in the wallet" "automaticky si pamatuje v²echna p°ístupová fráze v pen¥ºence")
("automatically save" "automaticky uloºit")
("autosave" "automatické ukládání")
("axis" "osa")
("b series" "Série b")
("back" "zp¥t")
("background evaluations" "hodnocení pozadí")
("backtrace errors" "chyb zp¥tného sledování")
("base" "základna")
("baseline" "základní linie")
("basic communication using pipes" "základní komunikace pomocí potrubí")
("beamer" "beamer")
("beamer formats" "beamer formát·")
("beamer theme" "beamerové téma")
("bench" "lavice")
("bend bottom" "ohnuté dno")
("bend corner" "roh ohybu")
("bend diagonal" "úhlop°í£ka")
("bend in" "ohyb")
("bend out" "ohnout")
("bezier" "bezier")
("bibTeX command" "p°íkaz bibTeX")
("bidirectional" "obousm¥rný")
("big environment box" "velký environmentální box")
("big focus" "velké zam¥°ení")
("binary operator" "binární operátor")
("bitmap resolution (dpi)" "bitmapové rozli²ení (dpi)")
("black floral I" "£erné kv¥tinové I")
("black floral II" "£erný kv¥tinový II")
("blackboard embold" "tabule se vyklopí")
("blank column" "prázdný sloupec")
("blank row" "prázdný °ádek")
("block" "blok")
("block content" "obsah bloku")
("block of code" "blok kódu")
("blur" "rozmazání")
("both versions" "ob¥ verze")
("bottom baseline" "spodní základní linie")
("bottom cell border" "dolní hranice bu¬ky")
("bottom cell padding" "výpl¬ spodní bu¬ky")
("bottom table border" "dolní okraj tabulky")
("bottom table padding" "výpl¬ spodní tabulky")
("bottom tools" "spodních nástroj·")
("box" "krabi£ka")
("broken white" "zlomená bílá")
("browse back" "procházet zp¥t")
("browse forward" "procházet vp°ed")
("browse modules documentation" "dokumentace k procházení modul·")
("buffer management" "správa vyrovnávacích pam¥tí")
("buffer must be on disk" "buffer musí být na disku")
("buffer must have a name" "buffer musí mít jméno")
("build buffer" "build buffer")
("build buffer in" "build buffer in")
("build directory" "build directory")
("build directory in" "build directory in")
("build link pages" "vytvo°it odkazové stránky")
("build-all" "build-all")
("bump" "rána")
("busy" "zaneprázdn¥n")
("cJK" "cJK")
("cJK spacing" "mezery cJK")
("calculus" "po£et")
("cancelled" "zru²eno")
("cannot download directory to file" "nelze stáhnout adresá° do souboru")
("cannot rename across different servers" "nelze p°ejmenovat na r·zných serverech")
("cannot upload directory to file" "nelze nahrát adresá° do souboru")
("cartesian" "karteziánský")
("carved wood" "vy°ezávané d°evo")
("case-insensitive search" "vyhledávání bez rozli²ování velkých a malých písmen")
("categories" "kategorií")
("category" "kategorie")
("cell properties" "vlastností bun¥k")
("cells" "bun¥k")
("change default unit" "zm¥nit výchozí jednotku")
("change passphrase" "zm¥nit p°ístupové fráze")
("change step-size" "zm¥nit velikost kroku")
("change tags" "zm¥nit zna£ky")
("change the TeXmacs preferences" "zm¥nit p°edvolby TeXmacs")
("change the border of the table" "zm¥nit okraj tabulky")
("change the style of mathematical formulas" "zm¥nit styl matematických vzorc·")
("character contraction" "kontrakce znak·")
("character encoding" "kódování znak·")
("character expansion" "roz²í°ení znak·")
("check for updates" "zkontrolovat aktualizace")
("checkable field" "za²krtnutelné pole")
("cipher algorithm for passphrase encryption" "²ifrovací algoritmus pro ²ifrování heslem")
("circle" "kruh")
("classification" "klasifikace")
("clean slate" "£istá b°idlice")
("clear all fields" "vymazat v²echna pole")
("clear local information" "jasné místní informace")
("clear menu" "jasné menu")
("clear undo history" "vymazat historii zp¥t")
("click Ok button twice to discard this warning" "dvojitým kliknutím na tla£ítko OK toto varování zru²íte")
("clip" "klip")
("clipboard image format" "formát obrazu schránky")
("close animation tool" "nástroj pro blízkou animaci")
("close document" "blízký dokument")
("close program" "blízký program")
("close replace tool" "nástroj pro vým¥nu zav°ít")
("close search tool" "nástroj pro blízké vyhledávání")
("close spell tool" "nástroj pro blízké kouzlo")
("close translations to rebuild" "úzkých p°eklad· k p°estavb¥")
("closed bezier" "uzav°ený bezier")
("closed curve" "uzav°ená k°ivka")
("closed smooth" "uzav°eno hladce")
("closed spline" "uzav°ená spline")
("closing style" "uzavírací styl")
("cluster by affiliation" "seskupení podle p°idruºení")
("collect garbage" "sbírat odpadky")
("color of the axes" "barva os")
("color of the subunits" "barva podjednotek")
("color of the units" "barva jednotek")
("colors" "barev")
("column to the left" "sloupec vlevo")
("column to the right" "sloupec vpravo")
("columns" "sloupc·")
("columns separation" "odd¥lení sloupc·")
("commit file" "soubor odevzdání")
("common" "spole£ných")
("common formats" "b¥ºné formáty")
("commutative diagram" "komutativní diagram")
("compact" "kompaktních")
("compactification" "kompaktizace")
("compactify" "kompaktizovat")
("complete bibliographic reference" "úplný bibliografický odkaz")
("completion" "dokon£ení")
("complex actions" "sloºitých akcí")
("compose" "sloºit")
("compound" "slou£enina")
("compress" "komprimovat")
("compress into toolbar" "komprimovat do panelu nástroj·")
("compressed" "komprimováno")
("conceal" "skrytí")
("configure look and feel" "Konfigurovat vzhled a dojem")
("confirm database entry" "potvrzení zadání databáze")
("confirm entry" "potvrzení zadání")
("confirm selected database entries" "potvrdit vybrané poloºky databáze")
("confirm selected entries" "potvrdit vybrané poloºky")
("conservative conversion options" "konzervativní moºnosti p°evodu")
("consoles" "konzolí")
("constellation" "souhv¥zdí")
("contact" "kontakt")
("content" "obsahu")
("context aids" "kontextové pom·cky")
("contextual hints" "kontextové rady")
("continue" "pokra£ovat")
("continued fraction" "pokra£ující zlomek")
("contour" "obrys")
("contract logarithms" "smluvní logaritmy")
("contribute" "p°isp¥t")
("control flow" "°ídicí tok")
("control the evaluation of expressions" "kontrola vyhodnocování výraz·")
("convert" "konverzí")
("converters" "p°evodník·")
("convertible" "konvertibilní")
("copyright" "autorských práv")
("cork charset with TeX catcode definition in preamble" "korek s znakem TeX catcode v preambuli")
("correct" "správný")
("correct all" "opravit v²e")
("correct formula" "správný vzorec")
("correct manually" "ru£n¥ opravit")
("correct mathematical formulas" "správné matematické vzorce")
("correction" "korekce")
("cosine" "kosinus")
("count characters" "po£et znak·")
("count lines" "po£et °ádk·")
("count words" "po£et slov")
("create a new document" "vytvo°it nový dokument")
("create link" "vytvo°it odkaz")
("create preamble" "vytvo°it preambuli")
("create remote directory" "vytvo°it vzdálený adresá°")
("create remote file" "vytvo°it vzdálený soubor")
("create subprogram" "vytvo°it podprogram")
("create subsession" "vytvo°it odb¥r")
("create table macro" "vytvo°it tabulkové makro")
("create web site" "vytvo°it web")
("creating new account" "vytvo°ení nového ú£tu")
("creating technical pictures" "vytvá°ení technických obrázk·")
("crop" "plodina")
("crop marks" "o°ezových zna£ek")
("cross" "k°íº")
("crossed boxes" "zk°íºených polí")
("crossed circles" "p°ek°íºených kruh·")
("current user version" "aktuální uºivatelská verze")
("current version" "aktuální verze")
("cursor" "kurzor")
("curve" "k°ivka")
("curve intersections" "k°iºovatek k°ivek")
("curve points" "bod· k°ivky")
("customizations" "p°izp·sobení")
("customizing and extending the user interface" "p°izp·sobení a roz²í°ení uºivatelského rozhraní")
("dark grey" "tmav¥ ²edá")
("data" "dat")
("database entry" "poloºka databáze")
("database tool" "databázový nástroj")
("database toolbar" "panel nástroj· databáze")
("deactivate once" "deaktivovat jednou")
("dead" "mrtvých")
("debug" "lad¥ní")
("debugging console" "ladicí konzole")
("debugging tool" "nástroj pro lad¥ní")
("decimal comma" "desetinná £árka")
("decimal dot" "desetinná te£ka")
("decomposed" "rozloºeno")
("decorated" "zdobené")
("decorated wood" "zdobené d°evo")
("decrease size" "zmen²it velikost")
("decrypt" "de²ifrovat")
("default size" "výchozí velikost")
("degrade" "degradovat")
("degraded" "degradováno")
("delete documentation cache" "vymazat mezipam¥´ dokumentace")
("delete entries" "smazat záznamy")
("delete link" "smazat odkaz")
("deleted" "smazáno")
("describe" "popsat")
("describe tag" "popsat zna£ku")
("destroy" "zni£it")
("detach master" "odpojit master")
("detailed" "podrobn¥")
("detailed menus" "podrobných nabídek")
("details in menus" "podrobnosti v nabídkách")
("determine margins from text width" "ur£it okraje od ²í°ky textu")
("developer" "vývojá°")
("developer tool" "vývojový nástroj")
("device" "za°ízení")
("diamond" "diamant")
("differentiate" "rozli²it")
("dilate" "dilate")
("direction of progression" "sm¥r postupu")
("direction of translation" "sm¥r p°ekladu")
("disable" "zakázat")
("disable coloring on paper" "zakázat barvení na papí°e")
("disable encryption" "zakázat ²ifrování")
("disappear" "zmizí")
("disk" "disk")
("display style" "styl zobrazení")
("displayed formula" "zobrazený vzorec")
("dissociate joined cells" "disociovat spojené bu¬ky")
("distort" "zkreslení")
("distorted" "zkreslené")
("division" "divize")
("do not remap" "nemapovat")
("document font selector" "selektor písma dokumentu")
("document language" "jazyk dokumentu")
("document page format" "formát stránky dokumentu")
("document paragraph format" "formát odstavce dokumentu")
("document updates run" "spu²t¥ní aktualizace dokument·")
("download" "stáhnout")
("downwards" "dol·")
("dragging" "p°etaºení")
("draw image" "nakreslit obrázek")
("draw over" "losování")
("draw over selection" "výb¥r p°es výb¥r")
("drop" "kapka")
("due to" "kv·li")
("dynamic" "dynamický")
("eRROR" "eRROR")
("edit animation" "upravit animaci")
("edit groups of objects" "editovat skupiny objekt·")
("edit macro" "upravit makro")
("edit macros" "upravit makra")
("edit preamble" "upravit preambuli")
("edit source" "upravit zdroj")
("edit source tree" "Upravit zdrojový strom")
("edit style" "styl úprav")
("edit translations file" "upravit p°ekladový soubor")
("education" "vzd¥lávání")
("effect pen" "efektové pero")
("eigenvalues" "vlastních £ísel")
("eighth" "osmý")
("embold" "embold")
("emboss" "reliéf")
("enable page breaking" "povolit p°eru²ení stránky")
("encoding" "kódování")
("encrypt" "²ifrování")
("encryption" "²ifrování")
("encryption facilities are not currently available" "²ifrovací za°ízení v sou£asné dob¥ nejsou k dispozici")
("encryption facilities have not been enabled for TeXmacs" "²ifrovací za°ízení nebyla pro TeXmacs povolena")
("enforce brackets to match" "vynutit závorky tak, aby odpovídaly")
("engrave" "rytina")
("enter data" "zadejte data")
("enter graphics" "zadejte grafiku")
("enter graphics mode" "vstoupit do grafického reºimu")
("enter new passphrase for encryption" "zadejte nové heslo pro ²ifrování")
("enter passphrase for decryption" "zadejte heslo pro de²ifrování")
("enter passphrase for identity" "zadejte heslo pro identifikaci")
("enter title information" "zadejte informace o názvu")
("entire table" "celá tabulka")
("entry up to date in database" "aktuální v databázi")
("enunciation" "výpov¥¤")
("environment variable" "prom¥nná prost°edí")
("environments" "prost°edí")
("erode" "erodování")
("error messages" "chybové zprávy")
("error output" "chybový výstup")
("error status report" "zpráva o stavu chyby")
("error: bracket does not match" "chyba: závorka se neshoduje")
("error: cyclic or missing chunks detected" "chyba: byly detekovány cyklické nebo chyb¥jící kousky")
("error: file not found" "chyba: soubor nebyl nalezen")
("error: ghostview does not seem to be installed on your system" "chyba: Zdá se, ºe ghostview není ve va²em systému nainstalován")
("error: one of the alternatives should be filled out" "chyba: m¥la by být vypln¥na jedna z alternativ")
("error: only one alternatives should be filled out" "chyba: m¥la by být vypln¥na pouze jedna alternativa")
("error: should fill out name for referencing" "chyba: m¥l by být uveden název pro odkazování")
("error: should fill out required field" "chyba: m¥lo by být vypln¥no povinné pole")
("evaluable field" "hodnotitelné pole")
("evaluate above" "vyhodnotit vý²e")
("evaluate all" "vyhodnotit v²e")
("evaluate below" "vyhodnotit níºe")
("evaluate fields" "vyhodnotit pole")
("evaluate fields in order" "vyhodnotit pole v po°ádku")
("evaluate script" "vyhodnotit skript")
("evaluation" "hodnocení")
("evaluation switch" "vyhodnocovací p°epína£")
("evaluation tag" "hodnotící zna£ka")
("even page" "sudá stránka")
("even page left margin" "levý okraj sudé stránky")
("even page shift" "rovnom¥rný posun stránky")
("even pages" "sudých stránek")
("events" "událostí")
("exact" "p°esných")
("execution of scripts" "provád¥ní skript·")
("exit graphics" "výstupní grafika")
("exit graphics mode" "ukon£it grafický reºim")
("exit left" "vlevo")
("exit right" "výjezd vpravo")
("exit tag on the left" "výstupní zna£ka vlevo")
("exit tag on the right" "výstupní zna£ka vpravo")
("expand TeXmacs macros with no LaTeX equivalents" "roz²í°it makra TeXmacs bez ekvivalent· LaTeX")
("expand beamer slides" "roz²í°it ²mýka£ky")
("expand inclusions" "roz²í°it inkluze")
("expand logarithms" "rozbalte logaritmy")
("expand trigonometric functions" "roz²í°it trigonometrické funkce")
("expand unrecognized macros" "rozbalení nerozpoznaných maker")
("expand user-defined macros" "rozbalte uºivatelská makra")
("expanded" "roz²í°eno")
("experimental features (to be used with care)" "experimentální funkce (je t°eba pouºívat opatrn¥)")
("explain" "vysv¥tlit")
("explanatory item" "vysv¥tlující poloºka")
("explicit keystroke" "explicitní stisknutí klávesy")
("explicit margins" "explicitní marºe")
("exponential" "exponenciální")
("export bibliographies as links" "exportovat bibliografie jako odkazy")
("export bibliography" "exportní bibliografie")
("export entries in buffer" "exportovat poloºky do vyrovnávací pam¥ti")
("export file" "exportní soubor")
("export formulas as images" "exportovat vzorce jako obrázky")
("export mathematical formulas as MathML" "exportovat matematické vzorce jako MathML")
("export mathematical formulas as images" "exportovat matematické vzorce jako obrázky")
("export selected entries" "exportovat vybrané poloºky")
("export selection" "výb¥r exportu")
("export selection as image" "exportovat výb¥r jako obrázek")
("export selections as" "exportních výb¥r· jako")
("export sessions" "vývozních relací")
("exported bibliographic entries" "exportované bibliografické záznamy")
("exported bibliographic references" "exportované bibliografické odkazy")
("extend" "prodlouºit")
("extended" "roz²í°eno")
("extensible left arrow" "roz²i°itelná ²ipka vlevo")
("extensible right arrow" "roz²i°itelná pravá ²ipka")
("extern" "vn¥")
("external" "externí")
("extra branch" "zvlá²tní v¥tev")
("extra interline space" "meziprostorový prostor")
("extra name" "extra jméno")
("extract" "extrakt")
("extract style file" "extrahovat soubor stylu")
("extract style package" "balí£ek styl· extrahování")
("factor" "faktor")
("fade" "vyblednutí")
("fade in" "vyblednutí")
("fade out" "vyblednutí")
("fast" "rychle")
("fast decrease" "rychlý pokles")
("fast environments" "rychlých prost°edí")
("fast increase" "rychlý nár·st")
("field reference" "reference na pole")
("fifth" "pátý")
("file saved" "soubor uloºen")
("fill color" "barva výpln¥")
("fill out" "vyplnit")
("filter" "filtr")
("find file" "najít soubor")
("finished collecting symbols documentation" "dokumentace pro dokon£ení shromaº¤ování symbol·")
("first" "první")
("first chunk" "první kus")
("first difference" "první rozdíl")
("first error" "první chyba")
("first field" "první pole")
("first occurrence" "první výskyt")
("first similar" "první podobné")
("fit to screen" "p°izp·sobeno obrazovce")
("fit to screen width" "p°izp·sobeno ²í°ce obrazovky")
("five columns" "p¥t sloupc·")
("fixed" "pevná")
("flag is off" "p°íznak je vypnutý")
("flag is on" "vlajka je zapnutá")
("flatten" "zplo²tit")
("floating algorithm" "plovoucí algoritmus")
("floating phantom" "plovoucí fantom")
("focus" "zam¥°ení")
("focus dependent icons" "ikon závislých na zaost°ení")
("fold all" "sloºit v²e")
("fold all fields" "sloºit v²echna pole")
("fold back" "záda zp¥t")
("fold input field" "sloºené vstupní pole")
("follow external links" "sledovat externí odkazy")
("follow inverse links" "sledovat inverzní odkazy")
("font effects" "fontové efekty")
("font selector" "selektor písma")
("font type" "typ písma")
("for each" "pro kaºdého")
("force reloading of translations" "vynucení p°ekladu p°eklad·")
("formatted and structured output" "formátovaný a strukturovaný výstup")
("formatting" "formátování")
("forward" "vp°ed")
("four columns" "£ty°i sloupce")
("four dots" "£ty°i te£ky")
("fourth" "£tvrtý")
("fraktur" "fraktur")
("framed" "zarámováno")
("from" "z")
("from center" "od st°edu")
("front matter" "p°ední £ást")
("full" "plný")
("full author list" "úplný seznam autor·")
("full screen mode" "reºim celé obrazovky")
("functional" "funk£ní")
("gap" "mezera")
("garbage collection" "sb¥r odpadu")
("gaussian" "gaussian")
("gcd" "gcd")
("general" "obecn¥")
("general note" "obecná poznámka")
("generated LaTeX document contains no errors" "vygenerovaný dokument LaTeX neobsahuje ºádné chyby")
("generated field" "generované pole")
("geometry" "geometrie")
("get arity" "získat arity")
("get label" "získat ²títek")
("get list with remote versions" "získat seznam se vzdálenými verzemi")
("glyphs" "glyf·")
("gnaw" "hlodat")
("gnawed" "nahlodaný")
("gnuPG command" "p°íkaz gnuPG")
("gnuPG error: buffer encryption failed" "chyba gnuPG: ²ifrování vyrovnávací pam¥ti selhalo")
("gnuPG error: cannot find suitable secret key to decrypt" "chyba gnuPG: nelze najít vhodný tajný klí£ k de²ifrování")
("gnuPG requires name and email to have at least 5 characters" "gnuPG vyºaduje, aby jméno a e-mail m¥ly alespo¬ 5 znak·")
("go to anchor" "jít do kotvy")
("go to anchor or float" "jít na kotvu nebo plavat")
("go to anchor or footnote" "P°ejít na kotvu nebo poznámku pod £arou")
("go to first similar tag" "p°ejít na první podobnou zna£ku")
("go to float" "go float")
("go to footnote" "p°ejd¥te na poznámku pod £arou")
("go to last similar tag" "p°ejít na poslední podobnou zna£ku")
("go to next similar tag" "p°ejít na dal²í podobnou zna£ku")
("go to previous similar tag" "p°ejít na p°edchozí podobnou zna£ku")
("go to section" "p°ejít do sekce")
("grain" "zrno")
("granite" "ºula")
("graphical effects" "grafické efekty")
("graphical interface font scale" "m¥°ítko písma grafického rozhraní")
("graphics" "grafika")
("graphics geometry" "grafická geometrie")
("graphics grids" "grafické sít¥")
("greyed" "²ed¥")
("grid" "m°íºka")
("grid curves" "m°íºkových k°ivek")
("grid points" "bod· sít¥")
("grid-curve intersections" "pr·se£íky k°ivek")
("group of objects" "skupina objekt·")
("group/ungroup" "skupina / ungroup")
("grouped" "seskupeno")
("guarantee transparent source tracking" "zaru£it transparentní sledování zdroje")
("h modifier" "Modifikátor h")
("half wide" "nap·l ²iroký")
("hand drawn" "ru£n¥ kreslenou")
("headers" "záhlaví")
("hidden" "skrytých")
("history" "historie")
("homepage" "domovská stránka")
("homoglyph substitutions" "substituce homoglyf·")
("horizontal alignment" "vodorovné zarovnání")
("horizontal collapse distance" "vodorovná vzdálenost sbalení")
("horizontal margins" "vodorovné okraje")
("hybrid command" "hybridní p°íkaz")
("hyphenate as" "spojovník jako")
("icon" "ikona")
("if hyphenated" "je-li spojovník")
("ignore" "ignorovat")
("impact" "dopad")
("import bibliography" "import bibliografie")
("import database entry" "import databáze")
("import entries in buffer" "importovat poloºky do vyrovnávací pam¥ti")
("import entry" "poloºka importu")
("import file" "importovat soubor")
("import selected database entries" "importovat vybrané poloºky databáze")
("import selected entries" "importovat vybrané poloºky")
("import selections as" "importovat výb¥r jako")
("import sessions" "relací importu")
("import sophisticated objects as pictures" "importovat sofistikované objekty jako obrázky")
("imported bibliographic entries" "importované bibliografické záznamy")
("in popup windows" "ve vyskakovacích oknech")
("inanimated" "inanimated")
("inch" "palce")
("incomplete entries found to be filled out" "neúplné záznamy byly shledány vypln¥ny")
("increase size" "zv¥t²it velikost")
("indent paragraphs" "odstavce odstavce")
("indentation" "odsazení")
("indication" "indikace")
("informative flags" "informativní vlajky")
("initialize" "inicializovat")
("ink here" "inkoust zde")
("ink in" "inkoust in")
("ink out" "inkoust do²el")
("inline" "inline")
("inline arguments" "vloºené argumenty")
("inline code" "vloºený kód")
("inline content" "vloºený obsah")
("inline formula" "vloºený vzorec")
("inner bottom" "vnit°ní dno")
("inner left" "vnit°ní vlevo")
("inner right" "vnit°ní právo")
("inner top" "vnit°ní vrchol")
("input command" "vstupní p°íkaz")
("input field" "vstupní pole")
("input mode" "vstupní reºim")
("input options" "moºnosti zadávání")
("insert a computer program" "vloºení po£íta£ového programu")
("insert a condition" "vloºte podmínku")
("insert a control flow instruction" "vloºení instrukce k regulaci toku")
("insert a gap" "vloºte mezeru")
("insert a list" "vloºit seznam")
("insert a multiple choice" "vloºte více moºností")
("insert a negation" "vloºte negaci")
("insert a new entry" "vloºit nový záznam")
("insert a note or a floating object" "vloºte poznámku nebo plovoucí objekt")
("insert a numerical operation" "vloºení £íselné operace")
("insert a prominent piece of text" "vloºte výrazný text")
("insert a question" "vloºte otázku")
("insert a root" "vloºte ko°en")
("insert a script" "vloºit skript")
("insert a section block" "vloºit blok sekce")
("insert a textual operation" "vloºte textovou operaci")
("insert a textual operator" "vloºit textový operátor")
("insert a wide symbol above" "vloºte ²iroký symbol vý²e")
("insert a wide symbol below" "vloºte ²iroký symbol níºe")
("insert above" "vloºit vý²e")
("insert abstract" "vloºit abstrakt")
("insert an answer" "vloºte odpov¥¤")
("insert an enunciation" "vloºit výpov¥¤")
("insert an operation on tuples" "vloºení operace na n-tice")
("insert annotation" "vloºit anotaci")
("insert author" "vloºit autora")
("insert below" "vloºit níºe")
("insert copyright and license information" "vloºte informace o autorských právech a licencích")
("insert explanatory item" "vloºit vysv¥tlující poloºku")
("insert field above" "vloºte pole nad")
("insert field below" "vloºte pole níºe")
("insert fields" "vloºte pole")
("insert input field above" "vloºte vstupní pole vý²e")
("insert input field below" "vloºte vstupní pole níºe")
("insert large delimiters" "vloºit velké odd¥lova£e")
("insert last name" "vloºte p°íjmení")
("insert left" "Vloºit vlevo")
("insert macro" "vloºit makro")
("insert missing invisible operators" "vloºte chyb¥jící neviditelné operátory")
("insert more names" "vloºte více jmen")
("insert particle" "vloºit £ástici")
("insert plain text" "vloºit prostý text")
("insert right" "vloºit vpravo")
("insert similar above" "vloºit podobné vý²e")
("insert similar below" "vloºit podobné níºe")
("insert similar block above" "vloºte podobný blok vý²e")
("insert similar block below" "vloºte podobný blok níºe")
("insert subtable" "insert subtable")
("insert symbol documentation" "vloºit dokumentaci symbol·")
("insert template" "vloºit ²ablonu")
("insert text field" "vloºte textové pole")
("insert text field above" "vloºte textové pole vý²e")
("insert text field below" "vloºte textové pole níºe")
("insert title" "vloºte název")
("insert title after name" "vloºte název za název")
("insert user interface related markup" "vloºit ozna£ení související s uºivatelským rozhraním")
("insert value" "vloºená hodnota")
("inserting control points" "vkládání kontrolních bod·")
("integrate" "integrovat")
("interactive command" "interaktivní p°íkaz")
("interactive questions" "interaktivních otázek")
("intercharacter compression" "komprimace mezi znaky")
("intercharacter stretching" "intercharacter streching")
("interrupted" "p°eru²eno")
("invalid multi-paragraph selection" "neplatný výb¥r z n¥kolika odstavc·")
("invalid renaming" "neplatné p°ejmenování")
("invert" "invertovat")
("inverted breve" "obrácená váha")
("invisible ending" "neviditelný konec")
("invisible newline" "neviditelný °ádek")
("invisible opening" "neviditelné otev°ení")
("join selected cells" "p°ipojit se k vybraným bu¬kám")
("jump in" "sko£it")
("junior" "junior")
("keep evaluated expressions" "zachovat hodnocené výrazy")
("keep local" "udrºujte místní")
("keep remote" "udrºet dálku")
("keep track of source code" "sledovat zdrojový kód")
("keep unfolded" "stále se rozvíjí")
("keyboard configuration" "konfigurace klávesnice")
("laptop presentations" "prezentací v notebooku")
("large cells" "velkých bun¥k")
("large displayed" "zobrazováno ve velkém")
("large displayed fraction" "velká zobrazená frakce")
("large tables" "velkých stol·")
("last" "poslední")
("last difference" "poslední rozdíl")
("last error" "poslední chyba")
("last field" "poslední pole")
("last name" "p°íjmení")
("last occurrence" "poslední výskyt")
("last similar" "last like")
("lcm" "lcm")
("left arrow" "²ipka vlevo")
("left axis" "levá osa")
("left baseline" "levá základní linie")
("left bottom" "vlevo dole")
("left cell border" "levý okraj bu¬ky")
("left cell padding" "výpl¬ levé bu¬ky")
("left center" "vlevo uprost°ed")
("left click: add point; Right click: undo" "klikn¥te levým tla£ítkem: p°idat bod; pravé kliknutí: vrátit zp¥t")
("left click: finish; Right click: undo" "levé kliknutí: dokon£ení; pravé kliknutí: zp¥t")
("left click: new object" "levé kliknutí: nový objekt")
("left click: operate" "kliknutí levým tla£ítkem: ovládání")
("left down" "vlevo dol·")
("left on even pages" "zbývá na sudých stránkách")
("left table border" "levý okraj tabulky")
("left table padding" "výpl¬ levého stolu")
("left top" "vlevo naho°e")
("left up" "vlevo nahoru")
("left-right arrow" "²ipka doleva a doprava")
("leftwards" "doleva")
("let the environment float" "nechte prost°edí plovoucí")
("light grey" "sv¥tle ²edá")
("line breaking" "p°eru²ení °ádku")
("line wrapping" "zalomení °ádku")
("linear 2D" "lineární 2D")
("linear algebra" "lineární algebra")
("lines around" "°ádk· kolem")
("link image and copies as" "propojit obrázek a kopírovat jako")
("link image as" "obrázek odkazu jako")
("link mode" "reºim propojení")
("link to URL" "odkaz na URL")
("linking tool" "propojovací nástroj")
("live" "ºiv¥")
("live input-output" "ºivý vstup-výstup")
("load help file" "na£íst soubor nápov¥dy")
("load remote file" "na£íst vzdálený soubor")
("loading" "na£ítání")
("local entries" "místních záznam·")
("loci" "loci")
("locus" "lokus")
("locus rendering" "vykreslování lokus·")
("logarithm" "logaritmus")
("logarithmic" "logaritmický")
("logarithmic base" "logaritmická základna")
("logarithms" "logaritmy")
("logging in" "p°ihlá²ení")
("logical and" "logicky a")
("logical implication" "logická implikace")
("logical not" "logicky ne")
("logical or" "logicky nebo")
("login" "p°ihlá²ení")
("logout" "odhlá²ení")
("long macro" "dlouhé makro")
("long text" "dlouhý text")
("look for more fonts" "hledat více písem")
("loops" "smy£ek")
("m modifier" "Modifikátor m")
("macro argument" "argument makro")
("macro definition" "definice makra")
("macro name" "název makra")
("macros" "maker")
("magnify horizontally" "horizontáln¥ zv¥t²it")
("magnify vertically" "vertikáln¥ zv¥t²it")
("main presentation style" "hlavní styl prezentace")
("make a letter environment" "vytvo°it prost°edí pro dopisy")
("make a multi-slide presentation" "vytvo°it vícenásobnou prezentaci")
("make floating" "plovoucí")
("make link" "vytvo°it odkaz")
("make non floating" "u£init neplovoucí")
("manila paper" "manilský papír")
("map arguments" "argumenty mapy")
("marginal note" "marginální nota")
("margins from width" "okraje od ²í°ky")
("margins on paper" "okraje na papí°e")
("margins on screen" "okraje na obrazovce")
("marked" "ozna£eno")
("material" "materiál")
("mathematical and customized input" "matematický a p°izp·sobený vstup")
("mathematical font" "matematické písmo")
("mathematical input" "matematický vstup")
("mathematical output" "matematický výstup")
("matrices" "matric")
("maximal" "maximální")
("maximal cell height" "maximální vý²ka bu¬ky")
("maximal clustering" "maximální shlukování")
("maximal table height" "maximální vý²ka stolu")
("maximal table width" "maximální ²í°ka stolu")
("maximum" "maximum")
("meander" "meandr")
("memory" "pam¥´")
("memory usage" "vyuºití pam¥ti")
("menu" "nabídka")
("merge lines into paragraphs unless separated by blank lines" "slou£it °ádky do odstavc·, pokud nejsou odd¥leny prázdnými °ádky")
("messages" "zpráv")
("meta data" "metadat")
("metadata" "metadat")
("metal" "kov")
("middle baseline" "st°ední základní linie")
("minimal" "minimální")
("minimal cell height" "minimální vý²ka bu¬ky")
("minimal cell width" "minimální ²í°ka bu¬ky")
("minimal line separation" "minimální odd¥lení £ar")
("minimal table height" "minimální vý²ka stolu")
("minimal table width" "minimální ²í°ka stolu")
("minimum" "minimum")
("mirror" "zrcadlo")
("miscellaneous features" "r·zné funkce")
("miscellanous" "r·zné")
("mode dependent icons" "ikon závislých na reºimu")
("modify remote live document" "úprava vzdáleného ºivého dokumentu")
("module" "modul")
("monospaced" "monospaced")
("more information about GNU TeXmacs can be found in the Help" "více informací o GNU TeXmacs naleznete v nápov¥d¥")
("more information about GNU TeXmacs can be found in the Help-<gtr>About menu" "")
("more information about GNU TeXmacs can be found in the Help-<less>gtr<gtr>About menu" "více informací o GNU TeXmacs najdete v nabídce Nápov¥da - <less>gtr<gtr>")
("motion" "pohyb")
("mouse over object" "mouse over object")
("move" "tah")
("move objects" "p°esouvat objekty")
("move over object on which to operate" "pohyb po objektu, na kterém se má pracovat")
("multiline" "multiline")
("multiline input" "více°ádkový vstup")
("multiple choice" "více moºností")
("multiple root" "více ko°en·")
("multiplication" "násobení")
("mutator tags" "zna£ek mutátor·")
("my documents" "moje dokumenty")
("navigation options" "moºností navigace")
("never" "nikdy")
("new account" "nový ú£et")
("new bibliography dialogue" "nový bibliografický dialog")
("new document" "nový dokument")
("new double page" "nová dvojitá stránka")
("new double page before" "nová dvojitá stránka p°ed")
("new entry" "nová poloºka")
("new identity" "nová identita")
("new locus" "nový lokus")
("new macro" "nové makro")
("new passphrase" "nové p°ístupové fráze")
("new remote directory" "nový vzdálený adresá°")
("new remote file" "nový vzdálený soubor")
("new style fonts" "nových styl· písem")
("new style page breaking" "nový styl stránky lámání")
("new version" "nová verze")
("new window" "nové okno")
("newer version" "nov¥j²í verze")
("next" "dal²í")
("next chunk" "dal²í kus")
("next difference" "dal²í rozdíl")
("next error" "dal²í chyba")
("next field" "dal²í pole")
("next occurrence" "dal²í výskyt")
("next screen" "dal²í obrazovka")
("next similar" "dal²í podobné")
("no clustering" "bez shlukování")
("no completions" "bez dokon£ení")
("no errors have been corrected" "nebyly opraveny ºádné chyby")
("no grid" "bez m°íºky")
("no matches found for" "nenalezeny ºádné výsledky pro")
("no new public key in document" "ºádný nový ve°ejný klí£ v dokumentu")
("no page break" "bez p°eru²ení stránky")
("no page numbers" "ºádná £ísla stránek")
("no parent" "ºádný rodi£")
("no selection" "bez výb¥ru")
("no spelling errors" "ºádné pravopisné chyby")
("normal loci" "normální loci")
("not allowed to remove home directory" "není dovoleno odebrat domovský adresá°")
("not connected to server" "není p°ipojen k serveru")
("not yet implemented" "dosud neimplementováno")
("notebook" "notebook")
("number of polar steps" "po£et polárních krok·")
("number of subunit steps" "po£et podjednotkových krok·")
("numbering" "£íslování")
("numeric spreadsheet" "numerická tabulka")
("odd page" "lichá stránka")
("odd page left margin" "lichý okraj liché stránky")
("odd page right margin" "pravý okraj liché stránky")
("odd page shift" "lichý posun stránky")
("odd pages" "lichých stránek")
("of fingerprint" "otisk· prst·")
("old version" "stará verze")
("older version" "star²í verze")
("on the footer" "na zápatí")
("on your system and set it up from the \"Security\" tab" "ve va²em systému a nastavte jej na kart¥ \"Zabezpe£ení\"")
("one column" "jeden sloupec")
("one error has been corrected" "jedna chyba byla opravena")
("one lower case letter, one non alpha-numeric symbol" "jedno malé písmeno, jeden nealfanumerický symbol")
("one numeric character, one upper case letter" "jeden £íselný znak, jedno velké písmeno")
("only convert changes when re-importing" "p°evést zm¥ny pouze p°i op¥tovném importu")
("only convert changes with respect to imported version" "p°evádí pouze zm¥ny s ohledem na importovanou verzi")
("only convert changes with respect to tracked version" "p°evádí pouze zm¥ny s ohledem na sledovanou verzi")
("only implemented for complete subtrees" "implementováno pouze pro úplné podstromy")
("only inline tags" "pouze vloºené zna£ky")
("only keep folded" "pouze udrºovat sloºené")
("only keep unfolded" "pouze rozloºte")
("only show semantic focus" "zobrazit pouze sémantické zam¥°ení")
("opacity" "nepr·hlednost")
("open bibliography" "otev°ená bibliografie")
("open identities" "otev°ených identit")
("open in new window" "otev°ít v novém okn¥")
("open licence agreement" "otev°ená licen£ní smlouva")
("open mailbox" "otev°ená po²tovní schránka")
("open module browser" "otev°ený prohlíºe£ modul·")
("open symbol browser" "prohlíºe£ otev°ených symbol·")
("open tool in separate window" "otev°ít nástroj v samostatném okn¥")
("operation mode" "provozní reºim")
("or give the complete path to the \"gpg\" or \"gpg2\" command" "nebo zadejte úplnou cestu k \"gpg\" nebo \"gpg2\" command")
("order" "objednávka")
("ordinary symbol" "oby£ejný symbol")
("ornamented" "ozdobený")
("other login" "jiné p°ihlá²ení")
("other package" "dal²í balí£ek")
("outer bottom" "vn¥j²í dno")
("outer left" "vlevo")
("outer right" "vn¥j²í pravý")
("outer top" "vn¥j²í vrchol")
("outline" "osnovy")
("outlined" "nastínil")
("outlined emboss" "nastínil reliéf")
("outlined engrave" "nastín¥né rytí")
("output options" "moºnosti výstupu")
("oval" "ovál")
("overbrace" "overbrace")
("overlap" "p°ekrývání")
("overlay" "p°ekrytí")
("overlays" "p°ekryvy")
("overline" "overline")
("overlined" "podtrºeno")
("overview of the scheme extension language" "p°ehled jazyka pro roz²í°ení schématu")
("padded" "polstrovaný")
("page background" "pozadí stránky")
("page break after" "konec stránky po")
("page breaking algorithm" "algoritmus p°eru²ení stránky")
("page number" "£íslo stránky")
("page number rendering" "vykreslování £ísla stránky")
("page rendering" "vykreslování stránky")
("page setup" "nastavení stránky")
("palette" "paleta")
("panorama" "panorama")
("paragraphs" "odstavc·")
("parametric curve" "parametrická k°ivka")
("parametric surface" "parametrická plocha")
("parenthesis" "závorka")
("parenthesized" "parenthesized")
("particle" "£ástice")
("passphrase encryption" "²ifrování pomocí p°ístupové fráze")
("passphrase wallet facilities are not currently available" "za°ízení pro pen¥ºenku p°ístupové fráze v sou£asné dob¥ nejsou k dispozici")
("passphrases are expected to have at least: 8 characters" "O£ekává se, ºe p°ístupové fráze budou mít alespo¬: 8 znak·")
("passphrases mismatch" "nesoulad p°ístupových frází")
("pastel" "pastel")
("pattern" "vzor")
("pause" "pauza")
("pen width" "²í°ka pera")
("permanent footer" "permanentní zápatí")
("permanent header" "trvalá záhlaví")
("permanently add to dictionary" "trvale p°idat do slovníku")
("permanently insert into dictionary" "trvale vloºit do slovníku")
("permissions" "oprávn¥ní")
("phantom" "p°ízrak")
("phantoms" "p°ízrak·")
("physics and astronomy class" "t°ída fyziky a astronomie")
("picture" "obrázek")
("pine" "borovice")
("plain" "holý")
("plain boxes" "oby£ejných krabic")
("plain circles" "prostých kruh·")
("play" "p°ehrávání")
("play animation" "p°ehrát animaci")
("please install GnuPG software from https://www.gnupg.org" "nainstalujte prosím software GnuPG z https://www.gnupg.org")
("plot" "spiknutí")
("plug-ins" "zásuvných modul·")
("plugin" "plugin")
("plugins" "plugin·")
("plural" "mnoºné £íslo")
("point" "bod")
("polar" "polární")
("polygon" "polygon")
("pop server settings" "nastavení popového serveru")
("position of marginal note" "pozice okrajové noty")
("poster formats" "plakátových formát·")
("poster theme" "plakátové téma")
("postfix" "postfix")
("preferences for editing mathematical formulas" "p°edvoleb pro úpravu matematických vzorc·")
("preferences for tag" "p°edvoleb pro zna£ku")
("prefix" "p°edpona")
("presentation" "prezentace")
("presentation tag" "prezenta£ní zna£ka")
("presentation tool" "prezenta£ní nástroj")
("preserve" "zachovat")
("preserve tags" "zachovat zna£ky")
("pretty tree output" "p¥kný stromový výstup")
("preview" "náhled")
("preview command" "p°íkaz pro náhled")
("previous" "p°edchozí")
("previous difference" "p°edchozí rozdíl")
("previous error" "p°edchozí chyba")
("previous field" "p°edchozí pole")
("previous occurrence" "p°edchozí výskyt")
("previous screen" "p°edchozí obrazovka")
("previous similar" "p°edchozí podobné")
("primitive or macro" "primitivních nebo makro")
("print buffer" "tiskový buffer")
("print buffer to file" "tiskový buffer do souboru")
("print to file" "tisk do souboru")
("printer setup" "nastavení tiskárny")
("program bracket matching" "shodování závorek programu")
("program bracket selections" "výb¥rových závorek")
("program commands" "programových p°íkaz·")
("program font" "programové písmo")
("program interface for buffer management" "programové rozhraní pro správu vyrovnávací pam¥ti")
("programming routines for editing documents" "programovací rutiny pro úpravy dokument·")
("prominent" "prominentních")
("prompts and default input" "výzvy a výchozí zadání")
("provoke C++ error" "provokuje chybu C ++")
("provoke menu error" "provokovat chybu v nabídce")
("provoke scheme error" "provokovat chybu schématu")
("pseudo code" "pseudokód")
("pulse" "puls")
("qt GUI only, sorry. Use \"Export selection\"" "Pouze qt GUI, promi¬te. Pouºijte \"Export selection\"")
("qt-widgets" "qt-widgets")
("quantifier" "kvantifikátor")
("quasi" "kvazi")
("question" "otázka")
("questions only" "pouze otázek")
("questions with answers" "otázek s odpov¥¤mi")
("quick evaluation of formulas" "rychlé vyhodnocení vzorc·")
("rank" "pozice")
("raw" "surových")
("really delete user identity" "opravdu smazat identitu uºivatele")
("really tiny" "opravdu mali£kých")
("rebuild translations file" "znovu sestavit p°ekladový soubor")
("recent" "nedávných")
("recent documents" "posledních dokument·")
("recipients" "p°íjemc·")
("recognize" "rozpoznat")
("recover autosave file" "obnovit automaticky uloºený soubor")
("rectangular" "obdélníkový")
("reduce" "zmen²it")
("reduce trigonometric functions" "sníºit trigonometrické funkce")
("reduced margins" "sníºené marºe")
("reference guide" "referen£ní p°íru£ka")
("reference guide for the TeXmacs primitives" "referen£ní p°íru£ka pro primitivy TeXmacs")
("reference guide for the standard TeXmacs styles" "referen£ní p°íru£ka pro standardní styly TeXmacs")
("regenerate" "regenerovat")
("register file" "registrovat soubor")
("relate" "souvisejí")
("relation" "vztah")
("release left button: finish editing" "uvoln¥te levé tla£ítko: dokon£ení úprav")
("remote" "vzdálených")
("remote connections" "vzdálených p°ipojení")
("remote control" "dálkové ovládání")
("remote directory" "vzdálený adresá°")
("remote servers" "vzdálených server·")
("remote tool" "vzdálený nástroj")
("remove" "odebrat")
("remove all output fields" "odebrat v²echna výstupní pole")
("remove banner" "odebrat banner")
("remove database entry" "odebrat poloºku databáze")
("remove downwards" "odstranit dol·")
("remove entries" "odebrat poloºky")
("remove entry" "odstranit záznam")
("remove field above" "odstranit pole vý²e")
("remove field below" "odebrat pole níºe")
("remove fields" "odebrat pole")
("remove folded" "odstranit sloºené")
("remove input field" "odebrat vstupní pole")
("remove input field above" "odstranit vstupní pole vý²e")
("remove last field" "odebrat poslední pole")
("remove leftwards" "odstranit doleva")
("remove link" "odebrat odkaz")
("remove next field" "odebrat dal²í pole")
("remove package" "odebrat balí£ek")
("remove previous field" "odebrat p°edchozí pole")
("remove rightwards" "odstranit doprava")
("remove selected database entries" "odebrat vybrané poloºky databáze")
("remove selected entries" "odebrat vybrané poloºky")
("remove superfluous invisible operators" "odstranit nadbyte£né neviditelné operátory")
("remove tag" "odebrat zna£ku")
("remove this branch" "odstranit tuto v¥tev")
("remove unfolded" "odstranit rozvinuté")
("remove upwards" "odstranit nahoru")
("removed entries from database" "odstran¥né poloºky z databáze")
("removed entry from database" "odstran¥ná poloºka z databáze")
("rename" "p°ejmenovat")
("rename section" "p°ejmenovat sekci")
("repeat" "opakování")
("replace TeXmacs styles with no LaTeX equivalents" "nahrazení styl· TeXmacs bez ekvivalent· LaTeX")
("replace all further occurrences" "nahradit v²echny dal²í výskyty")
("replace one occurrence" "nahradit jeden výskyt")
("replace toolbar" "nahradit panel nástroj·")
("replace unrecognized styles" "nahradit nerozpoznané styly")
("resize" "zm¥na velikosti")
("resize objects" "zm¥na velikosti objekt·")
("restart TeXmacs in order to let changes take effect" "restartujte TeXmacs, aby se zm¥ny projevily")
("restart in order to let the new look and feel take effect" "restartujte, aby se nový vzhled a dojem projevil")
("retain" "zachovat")
("retime" "retime")
("retina settings" "nastavení sítnice")
("retrieve email" "na£íst e-mail")
("retrieve remote live document" "na£íst vzdálený ºivý dokument")
("retrieved contents" "na£tený obsah")
("reverse" "obrácen¥")
("reverse ordering" "zp¥tné °azení")
("ridged paper" "rýhovaný papír")
("right arrow" "²ipka vpravo")
("right baseline" "pravá základní £ára")
("right cell border" "hranice pravé bu¬ky")
("right cell padding" "polstrování pravé bu¬ky")
("right down" "vpravo dol·")
("right on even pages" "p°ímo na sudých stránkách")
("right table border" "pravý okraj stolu")
("right table padding" "pravé polstrování stolu")
("right up" "nahoru")
("rightwards" "vpravo")
("rigid box" "tuhá krabice")
("rotate" "otá£et")
("rotate objects" "otá£et objekty")
("rough" "hrubý")
("rough paper" "surový papír")
("round" "kulatých")
("round overbrace" "kulatý overbrace")
("round underbrace" "kulatá spodní plocha")
("row above" "°ádek nad")
("row below" "°ádek níºe")
("rows" "°ádk·")
("run" "b¥h")
("run current file" "spustit aktuální soubor")
("same names" "stejných jmen")
("same screen margins as on paper" "stejné okraje obrazovky jako na papí°e")
("sample text" "ukázkový text")
("save auxiliary data" "uloºit pomocná data")
("save entries" "uloºit záznamy")
("save entry" "uloºit záznam")
("save image as" "uloºit obrázek jako")
("save position" "uloºit polohu")
("save remote file" "uloºit vzdálený soubor")
("saved modifications in database" "uloºené zm¥ny v databázi")
("scheme command" "p°íkazový °ádek")
("scheme developers guide" "p°íru£ka pro vývojá°e program·")
("scheme extensions" "roz²í°ení schémat")
("scheme interface for the graphical mode" "rozhraní schématu pro grafický reºim")
("screen" "obrazovka")
("screen rendering" "vykreslování obrazovky")
("screens" "obrazovek")
("screenshot" "screenshot")
("scripting language" "skriptovací jazyk")
("scripts" "skript·")
("search and replace" "hledat a nahradit")
("search results for" "výsledk· vyhledávání")
("search toolbar" "panel nástroj· vyhledávání")
("search words in my documents" "hledat slova v mých dokumentech")
("search words in the documentation" "hledat slova v dokumentaci")
("search words in the source code" "hledat slova ve zdrojovém kódu")
("second" "sekund")
("sections" "sekcí")
("see documentation" "viz dokumentace")
("select pen" "select pen")
("select the action to be undertaken for each conflict" "vyberte akci, která má být provedena pro kaºdý konflikt")
("select view mode" "reºim výb¥ru zobrazení")
("semantic correctness" "sémantická správnost")
("semantic editing" "sémantická úprava")
("semantic selections" "sémantických výb¥r·")
("semantics" "sémantika")
("sending commands to TeXmacs" "posílání p°íkaz· TeXmacs")
("senior" "senior")
("serif" "serif")
("server" "server")
("session commands" "p°íkaz· relace")
("set default" "nastavit výchozí")
("set difference" "nastavit rozdíl")
("set intersection" "nastavit pr·nik")
("set number of columns" "nastavit po£et sloupc·")
("set number of rows" "nastavit po£et °ádk·")
("set or get environment variables" "nastavit nebo získat prom¥nné prost°edí")
("set properties" "nastavit vlastnosti")
("set union" "set union")
("set user information" "nastavit informace o uºivateli")
("seventh" "sedmý")
("several equations" "n¥kolik rovnic")
("shadow" "stín")
("shadowed" "stínované")
("shadowed raise" "stínované zvý²ení")
("shift" "posun")
("short" "krátký")
("show all parts" "zobrazit v²echny £ásti")
("show current focus" "zobrazit aktuální zam¥°ení")
("show full context" "zobrazit plný kontext")
("show hidden" "zobrazit skryté")
("show key presses" "zobrazit stisknutí kláves")
("show main document" "zobrazit hlavní dokument")
("show memory usage" "zobrazit vyuºití pam¥ti")
("show one part" "zobrazit jednu £ást")
("show panorama" "zobrazit panorama")
("show preamble" "zobrazit preambuli")
("show several parts" "zobrazit n¥kolik £ástí")
("show subunits" "zobrazit podjednotky")
("show table cells" "zobrazit bu¬ky tabulky")
("show timings" "zobrazit £asování")
("side tools" "bo£ní nástroje")
("simple" "jednoduchých")
("simplification" "zjednodu²ení")
("simplified evaluation of formulas" "zjednodu²ené hodnocení vzorc·")
("simplified menus" "zjednodu²ených nabídek")
("simplify" "zjednodu²it")
("sine" "sine")
("sixth" "²estý")
("size tag" "velikostní zna£ka")
("skew" "zkosení")
("skip all" "p°esko£it v²e")
("slant" "²ikmo")
("slashed fraction" "sekaná frakce")
("slides" "diapozitiv·")
("slovene" "slovinsky")
("slow" "pomalu")
("slow decrease" "pomalý pokles")
("slow increase" "pomalý nár·st")
("small capitals" "malých m¥st")
("small environment box" "malý ekologický box")
("small focus" "malé zaost°ení")
("small inline" "malý inline")
("small inline fraction" "malý vloºený zlomek")
("smash" "rozbít")
("smooth" "hladký")
("smooth end" "hladký konec")
("smooth extremities" "hladkých kon£etin")
("smooth start" "hladký start")
("snap" "snap")
("snap distance" "vzdálenost")
("snap to curves" "zaklapnutí do k°ivek")
("snap to grid" "snap to grid")
("snap to grid curve" "k°ivka snap to grid")
("snap to intersections of curves" "zaklapnutí na pr·se£íky k°ivek")
("snap to text borders" "ohrani£ení na text")
("snap to text corners" "zaklapnout do textových roh·")
("solution" "°e²ení")
("solution to exercise" "°e²ení cvi£ení")
("solution to problem" "°e²ení problému")
("solutions" "°e²ení")
("sound" "zvuk")
("source" "zdroj")
("source macros tool" "nástroj zdrojových maker")
("source tags" "zdrojových zna£ek")
("south" "jih")
("south east" "jihovýchodn¥")
("space bar in math mode" "mezerník v matematickém reºimu")
("space bar in text mode" "mezerník v textovém reºimu")
("space stretchability" "roztaºitelnost prostoru")
("span" "rozp¥tí")
("span over all columns" "rozp¥tí ve v²ech sloupcích")
("special functions" "zvlá²tních funkcí")
("special properties" "zvlá²tních vlastností")
("specific baseline" "specifická základní linie")
("specify color alternation" "uve¤te st°ídání barev")
("specify how to traverse the manual" "ur£it, jak procházet manuálem")
("specify semantics of a symbol or formula" "uve¤te sémantiku symbolu nebo vzorce")
("specify the size of the table" "uve¤te velikost tabulky")
("spell check" "kontrola pravopisu")
("spline" "spline")
("split program" "split program")
("split session" "rozd¥lená relace")
("square" "£tvere£ních")
("square overbrace" "£tvercový overbrace")
("square underbrace" "£tvercové spodní plochy")
("stack" "stack")
("standard" "standard")
("standard Output" "standardní výstup")
("standard TeXmacs styles" "standardních styl· TeXmacs")
("standard environment variables" "standardní prom¥nné prost°edí")
("standard formats" "standardních formát·")
("standard fraction" "standardní zlomek")
("star" "hv¥zd")
("start server" "start server")
("statement" "prohlá²ení")
("statistics" "statistik")
("status" "status")
("stop server" "stop server")
("storage" "úloºi²t¥")
("store tracking information in LaTeX files" "ukládat informace o sledování do soubor· LaTeX")
("stretch" "úsek")
("stretch factor" "faktor roztaºení")
("stretched" "nataºený")
("strict Ascii" "p°ísná Ascii")
("strike through" "protáhnout")
("structured insert above" "strukturovaná vloºka vý²e")
("structured insert at the left" "strukturovaná vloºka vlevo")
("structured insert at the right" "strukturovaná vloºka vpravo")
("structured insert below" "strukturovaná vloºka níºe")
("structured remove downwards" "strukturované odstran¥ní dol·")
("structured remove leftwards" "strukturované odstran¥ní doleva")
("structured remove rightwards" "strukturované odstran¥ní vpravo")
("structured remove upwards" "strukturované odstran¥ní nahoru")
("structured variant" "strukturovaná varianta")
("style options" "moºností stylu")
("style parameters" "parametr· stylu")
("stylesheet language" "jazyk styl·")
("subject" "p°edm¥t")
("submenu" "podnabídka")
("subscript below" "dolní index")
("subsubmenu" "subsubmenu")
("subsubsubmenu" "subsubsubmenu")
("subsubsubsubmenu" "subsubsubsubmenu")
("subtable" "subtable")
("subtitle" "podtitul")
("subtraction" "od£ítání")
("summarized" "shrnuto")
("superscript above" "horní index")
("supported plug-ins" "podporovaných dopl¬k·")
("surface" "povrch")
("swell" "bobtnat")
("swiss" "²výcarský")
("switch to buffer" "p°epnout do vyrovnávací pam¥ti")
("symbol properties not found" "nebyly nalezeny vlastnosti symbolu")
("symbols" "symbol·")
("synchronize" "synchronizovat")
("synchronize bibliographic references" "synchronizovat bibliografické odkazy")
("synchronize with remote server" "synchronizovat se vzdáleným serverem")
("synopsis" "synopse")
("system command" "p°íkaz systému")
("tab-completion" "dokon£ení karty")
("tabbed" "tabbed")
("table breaking" "lámání stolu")
("table height" "vý²ka stolu")
("table properties" "vlastnosti tabulky")
("table width" "²í°ka stolu")
("tags with special rendering" "zna£ek se zvlá²tním vykreslením")
("tangent" "tangens")
("teXmacs DTD" "teXmacs DTD")
("teXmacs buffer expected" "O£ekává se TeXmacs buffer")
("teXmacs buffer on disk expected" "O£ekává se vyrovnávací pam¥ti teXmacs na disku")
("teXmacs extensions to scheme and utilities" "roz²í°ení teXmacs o schéma a obsluºné programy")
("teXmacs macro" "makro teXmacs")
("teXmacs package" "balí£ek teXmacs")
("teXmacs plugins" "zásuvných modul· teXmacs")
("teXmacs primitives" "primitiv teXmacs")
("teXmacs style" "stylu teXmacs")
("test routine" "testovací rutina")
("testing tree-view" "testování stromového zobrazení")
("text borders" "ohrani£ení textu")
("text box style" "styl textového pole")
("text corners" "textových roh·")
("textual" "textový")
("textual operator" "textový operátor")
("textual spreadsheet" "textových tabulek")
("the TeXmacs format" "formát TeXmacs")
("the TeXmacs plug-in system" "zásuvný systém TeXmacs")
("the document has not been saved" "dokument nebyl uloºen")
("theme parameters" "parametry motivu")
("these collected public keys will be definitely lost" "tyto shromáºd¥né ve°ejné klí£e budou definitivn¥ ztraceny")
("these public keys will be definitely lost" "tyto ve°ejné klí£e budou definitivn¥ ztraceny")
("these secret keys will be definitely lost" "tyto tajné klí£e budou definitivn¥ ztraceny")
("thicken" "zahu²´ovat")
("third" "t°etí")
("this" "toto")
("this column" "tento sloupec")
("this page footer" "zápatí této stránky")
("this page header" "tato záhlaví stránky")
("this page number" "toto £íslo stránky")
("this row" "tento °ádek")
("this style specifies page margins in the TeX way" "tento styl ur£uje okraje stránky zp·sobem TeX")
("three columns" "t°í sloupc·")
("three dots" "t°i te£ky")
("through popup windows" "p°es vyskakovací okna")
("through the menus" "v nabídkách")
("thumbnails" "miniatur")
("time evolution" "evoluce £asu")
("timings" "na£asování")
("title presentation options" "moºnosti prezentace titul·")
("title style" "styl nadpisu")
("title suffix" "p°ípona názvu")
("titled block" "s názvem blok")
("toggle cell wrapping mode" "reºim p°epínání bun¥k")
("toggle here" "p°epnout sem")
("toggle off" "vypnout")
("toggle on" "p°epnout na")
("tolerant" "tolerantní")
("top baseline" "horní základní linie")
("top cell border" "horní hranice bu¬ky")
("top cell padding" "výpl¬ horní bu¬ky")
("top table border" "ohrani£ení horní tabulky")
("top table padding" "polstrování stolu")
("transform" "transformace")
("transform cell into subtable" "transformovat bu¬ku do podoblasti")
("translations" "p°eklad·")
("translations loaded" "na£tených p°eklad·")
("transpose" "transponovat")
("traversal" "traversal")
("traverse" "traverza")
("triangle" "trojúhelník")
("triangularize" "triangularize")
("trigonometric" "trigonometrický")
("trigonometry" "trigonometrie")
("turn off" "vypnout")
("turn on" "zapnout")
("two columns" "dva sloupce")
("two dots" "dv¥ te£ky")
("type a latex command followed by return" "zadejte p°íkaz latex následovaný návratem")
("underbrace" "podtrºení")
("underline" "podtrºení")
("underlined" "podtrºeno")
("unevaluated argument" "neocen¥ný argument")
("unevaluated value" "nevyhodnocená hodnota")
("unfold" "rozvinout")
("unfold all" "rozvinout v²e")
("unfold all fields" "rozloºte v²echna pole")
("unit" "jednotka")
("unit length" "délka jednotky")
("unknown secret key fingerprint" "neznámý otisk tajného klí£e")
("unregistered file" "neregistrovaný soubor")
("unroll" "unroll")
("unsecure script refused" "nezabezpe£ený skript byl odmítnut")
("unsupported link mode" "nepodporovaný reºim propojení")
("until" "do")
("untitled block" "nepojmenovaný blok")
("up to date" "aktuální")
("update buffer" "aktualizace buffer")
("update this buffer" "aktualizovat tento buffer")
("update web site" "aktualizovat web")
("upight" "vzestupn¥")
("upload" "nahrát")
("upright" "vzp°ímen¥")
("upwards" "nahoru")
("use CSS for more advanced formatting" "pouºití CSS pro pokro£ilej²í formátování")
("use MathML" "pouºijte MathML")
("use as master" "pouºití jako master")
("use extensible brackets" "pouºijte roz²i°itelné závorky")
("use line wrapping for lines which are longer than 80 characters" "pouºít zalomení °ádk· pro °ádky del²í neº 80 znak·")
("use margin kerning (protrusion)" "pouºít vyrovnání okraj· (výstupek)")
("use protrusion" "pouºijte vý£n¥lek")
("use relative path" "pouºít relativní cestu")
("user interface" "uºivatelské rozhraní")
("user interface language" "jazyk uºivatelského rozhraní")
("user preferences" "uºivatelských preferencí")
("users of Cyrillic languages" "uºivatelé azbuky")
("users of oriental languages" "uºivatelé orientálních jazyk·")
("utf-8 with inputenc LaTeX package" "utf-8 s balí£kem inputenc LaTeX")
("utilities" "nástroje")
("vanish" "zmizet")
("verbose" "podrobných")
("version" "verze")
("versioning tool" "nástroj pro vytvá°ení verzí")
("vertical alignment" "svislé zarovnání")
("vertical margins" "svislé okraje")
("vertical space after" "po svislém prostoru")
("vertical space before" "p°ed svislým prostorem")
("vertical space stretchability" "vertikální roztaºitelnost prostoru")
("visible except here" "viditelné krom¥ zde")
("visible from here on" "odtud viditelné")
("visible only here" "viditelné pouze zde")
("visible until here" "Do té doby viditelné")
("visited loci" "nav²tívených loci")
("wallet" "pen¥ºenka")
("wave" "vlna")
("web" "web")
("weight" "hmotnost")
("when line wrapping" "p°i zalamování °ádk·")
("whitespace" "bílé znaky")
("wide" "²iroký")
("wide bar" "²iroká li²ta")
("wide block" "²iroký blok")
("wide colored" "²iroko zbarvená")
("wide float" "²iroký plovák")
("wide footnote" "²iroká poznámka pod £arou")
("wide tabular" "²iroká tabulka")
("widescreen" "²irokoúhlý")
("wrap lines" "zalomených °ádk·")
("write a macro" "napsat makro")
("writing TeXmacs bibliography styles" "psaní styl· bibliografie TeXmacs")
("writing documentation" "písemná dokumentace")
("written with TeXmacs" "psáno s TeXmacs")
("wrong empty passphrase" "nesprávné prázdné heslo")
("wrong passphrase" "nesprávná p°ístupová fráze")
("year" "roku")
("you are attempting to open an encrypted file while" "Pokou²íte se otev°ít ²ifrovaný soubor, zatímco")
("you might consider enabling the experimental" "m·ºete zváºit povolení experimentu")
("you must add a bibliography file" "musíte p°idat bibliografický soubor")
("you should also make sure that GnuPG is installed" "m¥li byste se také ujistit, ºe je nainstalován GnuPG")
("your language" "vá² jazyk")
("your personal dictionary has been modified" "vá² osobní slovník byl zm¥n¥n")
("zoom" "zoom")
("zoom in" "p°iblíºit")
("zoom out" "oddálit")
