
###############################################################################
# MODULE     : Make file for maple plugin
# BY         : Joris van der Hoeven
# COPYRIGHT  : This software falls under the GNU general public license;
#              see the file 'LICENSE', which is provided with this package.
###############################################################################

CC = gcc

#TEXMACS_HOME_PATH = $(HOME)/.TeXmacs
#TEXMACS_MAPLE_DIR = $(shell realpath `which maple` | sed -e 's%/bin/maple$$%%')

MAPLECPPFLAGS = -I$(TEXMACS_MAPLE_DIR)/extern/include
MAPLELDFLAGS = -L$(TEXMACS_MAPLE_DIR)/bin.IBM_INTEL_LINUX -Wl,-rpath,$(TEXMACS_MAPLE_DIR)/bin.IBM_INTEL_LINUX -lmaplec

all: $(TEXMACS_HOME_PATH)/bin/tm_maple_9.sh $(TEXMACS_HOME_PATH)/bin/tm_maple_9

$(TEXMACS_HOME_PATH)/bin/tm_maple_9.sh: $(TEXMACS_MAPLE_DIR)/bin/maple
	cat $(TEXMACS_MAPLE_DIR)/bin/maple | sed 's%$${MAPLE}/$$MAPLE_SYS_BIN/cmaple%$${HOME}/.TeXmacs/bin/tm_maple_9%' | sed 's%$${MAPLE}/$$MAPLE_SYS_BIN/maplew%$${HOME}/.TeXmacs/bin/tm_maple_9%' > $(TEXMACS_HOME_PATH)/bin/tm_maple_9.sh
	chmod a+x $(TEXMACS_HOME_PATH)/bin/tm_maple_9.sh

$(TEXMACS_HOME_PATH)/bin/tm_maple_9: src/tm_maple_9.c
	$(CC) $(MAPLELDFLAGS) $(MAPLECPPFLAGS) src/tm_maple_9.c -o $(TEXMACS_HOME_PATH)/bin/tm_maple_9
