("a modifier" "A Modifier")
("GNU" "GNU")
("h modifier" "H Modifier")
("LaTeX" "LaTeX")
("m modifier" "M Modifier")
("Save as LaTeX" "als LaTeX sichern")
("Save as TeX" "als TeX sichern")
("TeX" "TeX")
("abbreviation" "Abkürzung")
("about" "über TeXmacs")
("about menu" "über Menü finden")
("above" "oben")
("abstract" "Zusammenfassung")
("accent" "Akzent")
("accept" "akzeptieren")
("accept all scripts" "alle Scripts akzeptieren")
("accept no scripts" "keine Scripts akzeptieren")
("accept script" "Script akzeptieren")
("acknowledgment" "Danksagung")
("acronym" "Akronym")
("action" "Aktion")
("activate" "aktivieren")
("acute" "nach rechts")
("add switch after" "Ebene danach einfügen")
("add switch before" "Ebene davor einfügen")
("address" "Adresse")
("address block" "Adressblock")
("advanced" "fortgeschritten")
("advanced layout features" "fortgeschrittene Layout-Eigenschaften")
("after" "nach")
("algorithm" "Algorithmus")
("align cell to the bottom" "Zelle nach unten ausrichten")
("align cell to the left" "Zelle nach links ausrichten")
("align cell to the right" "Zelle nach rechts ausrichten")
("align cell to the top" "Zelle nach oben ausrichten")
("align table at base of left column" "Tabelle an der Grundlinie der linkesn Spalte ausrichten")
("align table at base of middle column" "Tabelle an der Grundlinie der mittleren Spalte ausrichten")
("align table at base of origin column" "Tabelle an der Grundlinie der Ursprungsspalte ausrichten")
("align table at base of right column" "Tabelle an Grundlinie der rechten Spalte ausrichten")
("align table at fraction bar height" "Tabelle an der Höhe des Bruchstriches ausrichten")
("align table at the base of bottom row" "Tabelle an der Grundlinie der untersten Reihe ausrichten")
("align table at the base of middle row" "Tabelle an der Grundlinie der mittleren Reihe ausrichten")
("align table at the base of origin row" "Tabelle an der Grundlinie der Ursprungsreihe ausrichten")
("align table at the base of top row" "Tabelle an der Grundlinie der obersten Reihe ausrichten")
("align table at the bottom" "Tabelle nach unten ausrichten")
("align table at the center" "Tabelle an der Mitte ausrichten")
("align table at the horizontal center" "Tabelle an der horizontalen Mitte ausrichten")
("align table at the left" "Tabelle nach links ausrichten")
("align table at the top" "Tabelle nach oben ausrichten")
("align table to the right" "Tabelle nach rechts ausrichten")
("align text to the left" "Text linksbündig ausrichten")
("align text to the right" "Text rechtsbündig ausrichten")
("alignment" "Ausrichtung")
("all" "alles")
("allow" "erlauben")
("allowed extension" "erlaubte Verlängerung")
("allowed reduction" "erlaubte Verkürzung")
("alpha release" "Alpha Version")
("alt key" "Alt-Taste")
("american" "amerikanisch")
("and" "und")
("appendix" "Anhang")
("apply" "anwenden")
("april" "April")
("arab" "arabisch")
("archaic" "archaisch")
("architecture" "Architektur")
("argument" "Argument")
("arithmetic" "arithmetisch")
("armenian" "armenisch")
("arrow" "Pfeil")
("arrows" "Pfeile")
("article" "Artikel")
("as on paper" "wie auf dem Papier")
("assign" "ändern")
("at fraction bar height" "in der Höhe des Bruchstriches")
("at the baseline" "an der Grundlinie")
("at the bottom" "an der Unterseite")
("at the left" "auf der linken Seite")
("at the middle" "in der Mitte")
("at the right" "auf der rechten Seite")
("at the top" "an der Oberseite")
("attach" "beifügen")
("attach buffer to which project" "Puffer an welches Project anbinden")
("august" "August")
("author" "Autor")
("authorize" "erlauben")
("automatic" "automatisch")
("automatically generated content" "automatisch generierter Inhalt")
("axiom" "Axiom")
("background" "Hintergrund")
("background color" "Hintergrundfarbe")
("backward replace" "rückwärts ersetzen")
("backward search" "rückwärts suchen")
("bad data format" "falsches Dateiformat")
("bar" "Strich")
("bard" "bard")
("base level" "Grundniveau")
("bashkirian" "bashkirisch")
("basic" "Basis")
("basic data types" "grundlegende Datentypen")
("basic types" "Basistypen")
("be useful" "seien Sie nützlich")
("become a TeXmacs developer" "werde ein TeXmacs-Entwickler")
("before" "vor")
("begin" "Anfang")
("below" "unten")
("beta release" "Beta Version")
("bibliography" "Literaturverzeichnis")
("bibliography file" "Datei des Literaturverzeichnisses")
("bibliography style" "Stil des Literaturverzeichnisses")
("big" "groÿ")
("big figure" "groÿe Figur")
("big operator" "groÿer Operator")
("big skip" "groÿer Abstand")
("big table" "groÿe Tabelle")
("binary operation" "binäre Operation")
("binary relation" "binäre Beziehung")
("black" "schwarz")
("blackboard bold" "Blackboard fett")
("blackboard math" "Blackboard Math")
("blackletter" "schwarze Buchstaben")
("blue" "blau")
("body" "Körper")
("bold" "fett")
("book" "Buch")
("border" "Begrenzung")
("both" "beide")
("bottom" "ganz unten")
("bottom border" "untere Begrenzung")
("bottom margin" "unterer Rand")
("bottom padding" "untere Auffüllung")
("branch" "Ast")
("break" "Umbruch")
("breaking" "Umbruch")
("breve" "Breve")
("british" "britisch")
("brown" "braun")
("browse" "durchsuchen")
("browse web" "Internet durchsuchen")
("browser" "Browser")
("buffer" "Puffer")
("bullet" "Punkt")
("bullets" "Punkte")
("by" "von")
("by typing" "über Tastatur")
("bytes free" "Bytes frei")
("bytes used" "Bytes benutzt")
("calligraphic" "kalligraphisch")
("cancel" "abbrechen")
("caps-lock key" "Hochstell-Taste")
("case" "falls")
("cc" "Durchschlag")
("cell" "Zelle")
("cell background color" "Hintergrundfarbe")
("cell border" "Zellenumrandung")
("cell height" "Zellenhöhe")
("cell operation mode" "Zellenbearbeitungsmodus")
("cell width" "Zellenbreite")
("center" "zentriert")
("center text" "Text zentrieren")
("centered" "zentriert")
("centered block" "zentrierter Block")
("centered tabular" "zentrierter Tabulatormodus")
("change border of cell" "Zellenumrandung ändern")
("change cell operation mode" "Zellenbearbeitungsmodus ändern")
("change log" "Protokoll der Veränderungen")
("changes" "Änderungen")
("chapter" "Kapitel")
("check" "Haken")
("check text for spelling errors" "Text auf Schreibfehler überprüfen")
("chinese" "Chinesisch")
("choice" "Auswahl")
("citation" "Zitat")
("cite" "Zitat")
("class" "Klasse")
("clear" "leer")
("clear selection" "Auswahl löschen")
("clipped" "abgeschnitten")
("clipped and magnified" "abgeschnitten und vergröÿert")
("clipped and resized" "abgeschnitten und gestreckt")
("clone" "klonen")
("clone window" "Fenster klonen")
("close" "schlieÿen")
("close TeXmacs" "TeXmacs schlieÿen")
("close buffer" "Puffer schlieÿen")
("close session" "Sitzung schlieÿen")
("close window" "Fenster schlieÿen")
("closing" "Schlussformel")
("code" "Kode")
("color" "Farbe")
("column" "Spalte")
("column contains glued items" "Spalte enthält zusammengeklebte Teile")
("compatibility with other formats" "Kompatibilität mit anderen Formaten")
("compile article" "Artikel kompilieren")
("compile book" "Buch kompilieren")
("compile buffer" "Puffer kompilieren")
("compile project" "Projekt kompilieren")
("complex" "komplex")
("concrete" "concrete")
("condensed" "dicht")
("condition" "Bedingung")
("configuration" "Konfiguration")
("content tag" "Inhaltliche Auszeichnung")
("context dependent icons" "Kontextabhängige Symbole")
("continuation of" "Fortsetzung von")
("convention" "Konvention")
("converters to other data formats" "Konverter in andere Formate")
("copy" "kopieren")
("copy text" "Text kopieren")
("copy to" "kopieren nach")
("copying" "kopieren")
("corollary" "Folgerung")
("correct text" "Text korrigieren")
("cursors" "Cursors")
("custom tab" "gewöhnlicher Tabulator")
("customizing TeXmacs" "TeXmacs anpassen")
("customizing the TeXmacs styles" "TeXmacs-Stil anpassen")
("custum tab" "gewöhnlicher Tabulator")
("cut" "ausschneiden")
("cut text" "Text ausschneiden")
("cut to" "ausschneiden nach")
("cypriot" "zypriotisch")
("cyrillic" "Kyrillisch")
("cyrillic input method" "kyrillische Eingabemethode")
("cyrillic italic right" "Kyrillisch Italic aber senkrecht")
("czech" "tschechisch")
("dancers" "Tänzer")
("dash" "Gedankenstrich")
("dashes" "Striche")
("data conversion" "Datenkonvertierung")
("data format" "Datenformat")
("date" "Datum")
("deactivate" "ausschalten")
("deactivate table" "Tabelle deaktivieren")
("december" "Dezember")
("decorate atoms" "decorate atoms")
("default" "voreingestellt")
("default padding" "Standardwert der Auffüllung")
("definition" "Definition")
("delete" "löschen")
("delete column" "Spalte löschen")
("delete row" "Zeile löschen")
("denominator" "Nenner")
("description" "Beschreibung")
("destination" "Bestimmung")
("detach" "ablösen")
("determinant" "Determinante")
("devangari" "Devangari")
("developers guide" "Einführung für Entwickler")
("directory" "Verzeichnis")
("disable first indentation" "erste Einrückung verhindern")
("disable first indentation after" "nachher erste Einrückung verhindern")
("disable first indentation before" "vorher erste Einrückung verhindern")
("disable indentation" "Einrückung verhindern")
("disable indentation after" "nachher Einrückung verhindern")
("disable indentation before" "vorher Einrückung verhindern")
("disable last indentation" "letzte Einrückung verhindern")
("disable last indentation after" "nachher letzte Einrückung verhindern")
("disable last indentation before" "vorher letzte Einrückung verhindern")
("disallow" "verbieten")
("distribute unused space" "den nicht benutzten Freiraum verteilen")
("div" "div")
("document" "Dokument")
("document format" "Dokumentenformat")
("document style" "Dokumentenstil")
("document styles" "Dokumentenstil")
("documentation" "Dokumentation")
("documents are trees" "Dokumente sind strukturiert")
("dot" "Punkt")
("dots" "Punkte")
("double stroke" "Doppelstrich")
("down" "runter")
("dpi" "Punkte pro Zoll (dpi)")
("duplicate" "doppelt")
("dutch" "niederländisch")
("dynamic libraries" "Dynamische Bibliotheken")
("edit" "bearbeiten")
("editing tools" "Bearbeitungswerkzeuge")
("email" "E-Mail")
("emphasize" "hervorheben")
("emphasize text" "Text hervorheben")
("empty box" "leere Box")
("enable first indentation" "erste Einrückung ermöglichen")
("enable first indentation after" "nachher erste Einrückung ermöglichen")
("enable first indentation before" "vorher erste Einrückung ermöglichen")
("enable indentation" "Einrückung ermöglichen")
("enable indentation after" "nachher Einrückung ermöglichen")
("enable indentation before" "vorher Einrückung ermöglichen")
("enable last indentation" "letzte Einrückung ermögliichen")
("enable last indentation after" "nachher letzte Einrückung ermöglichen")
("enable last indentation before" "vorher letzte Einrückung ermöglichen")
("encl" "Anlage")
("end" "Ende")
("english" "englisch")
("enter a title" "einen Titel eingeben")
("enumerate" "aufzählen")
("enumerate|Alpha" "Groÿbuchstaben")
("enumerate|Roman" "Römisch")
("enumerate|alpha" "Kleinbuchstaben")
("enumerate|roman" "römisch")
("env" "Umgebung")
("environment" "Umgebung")
("epilogue" "Nachwort")
("equal" "gleich")
("equation" "Gleichung")
("equations" "Gleichungen")
("equivalent for" "äquivalent für")
("error" "Fehler")
("etruscan" "etruskisch")
("evaluate" "auswerten")
("evaluate scheme expression" "Scheme Ausdruck ausführen")
("even page footer" "Fuÿ für gerade Seiten")
("even page header" "Kopf für gerade Seiten")
("even page margin" "Rand für gerade Seiten")
("even page text" "Text für gerade Seiten")
("exact horizontal" "horizontal exakt")
("exact mode" "genauer Modus")
("exam" "Examensarbeit")
("example" "Beispiel")
("exclusive" "exklusiv")
("exclusive or" "exklusives Oder")
("executable" "ausführbar")
("execute" "ausführen")
("execute a TeXmacs command" "TeXmacs Kommando ausführen")
("execute system command" "Systemkommando ausführen")
("executive" "Executive")
("exercise" "Aufgabe")
("expand" "ausdehnen")
("explained" "mit Erklärung")
("export" "exportieren")
("export as" "exportieren als")
("extend or normal" "'extend' oder 'normal'")
("extern " "extern")
("extra" "extra")
("extract format" "Format herausziehen")
("family" "Familie")
("february" "Februar")
("figure" "Abbildung")
("file" "Datei")
("file name" "Dateiname")
("file not found" "Datei nicht gefunden")
("find next match" "nächsten Treffer suchen")
("find text" "Text suchen")
("finnish" "finnländisch")
("first contact" "erster Kontakt")
("first indentation" "erste Einrückung")
("first item" "erster Spiegelstrich")
("first margin" "erster Rand")
("first page" "erste Seite")
("first start" "erster Start")
("flat" "flach")
("flexibility" "Flexibilität")
("flexibility factor for vertical spacing" "vertikaler Flexibilitätsfaktor")
("floating figure" "treibende Figur")
("floating object" "treibendes Objekt")
("floating table" "treibende Tabelle")
("fold" "zusammenfalten")
("folded" "zusammengefaltet")
("font" "Schriftart")
("font base size" "Buchstabenbasisgröÿe")
("font dpi" "Punkte pro Zoll (dpi)")
("font family" "Schriftfamilie")
("font name" "Schriftart")
("font series" "Schriftserie")
("font shape" "Schriftform")
("font size" "Schriftgröÿe")
("font variant" "Schriftvariante")
("fonts" "Schriftarten")
("footer" "Fuÿzeile")
("footnote" "Fuÿnote")
("for" "für")
("foreground" "Vordergrund")
("foreign" "ausländisch")
("format" "Formate")
("formatted date" "formatiertes Datum")
("formula" "Formel")
("formula style" "Formelstil")
("forward replace" "nach vorne ersetzen")
("forward search" "nach vorne suchen")
("fraction" "Bruch")
("french" "französisch")
("full manuals" "komplette Anleitung")
("function" "Funktion")
("further customization" "weitere Anpassungen")
("future changes" "zukünftige Änderungen")
("gNU TeXmacs comes without any form of legal warranty" "GNU TeXmacs kommt ohne rechtlich verbindliche Garantie")
("gNU TeXmacs falls under the GNU general public license" "GNU TeXmacs fällt unter die ``GNU general public license''")
("general architecture of TeXmacs" "allgemeiner Aufbau von TeXmacs")
("general negation" "allgemeine Verneinung")
("generating font file" "erzeuge Font-Datei")
("generic" "allgemein")
("georgian" "georgisch")
("german" "deutsch")
("getting started" "anfangen")
("glossary" "Glossar")
("glossary entry" "Glossareintrag")
("glue" "kleben")
("glue decorations" "Dekorierung ankleben")
("go" "nach")
("gothic" "gotisch")
("graphical interface" "Grafikschnittstelle")
("grave" "nach links")
("greater" "gröÿer")
("greater or equal" "gröÿer oder gleich")
("greek" "griechisch")
("greek letter" "griechischer Buchstabe")
("green" "grün")
("grey" "grau")
("group" "Gruppe")
("happy typing" "viel Spaÿ beim Tippen")
("has been aborted" "ist abgebrochen worden")
("has completed its task" "hat seine Arbeit beendet")
("hat" "Hut")
("header" "Kopfzeile")
("header and footer" "Seitenkopf und -fuÿ")
("hebrew" "hebräisch")
("height" "Höhe")
("height is exactly the specified height" "Höhe ist genau die spezifizierte Höhe")
("height is maximum of specified height and box height" "Höhe ist das Maximum von spezifizierter Höhe und Boxenhöhe")
("height is minimum of specified height and box height" "Höhe ist das Minimum von spezifizierter Höhe und Boxenhöhe")
("height magnification" "Höhenvergröÿerung")
("help" "Hilfe")
("help me" "Helfen Sie mir")
("help us" "Helfen Sie uns")
("here" "hier")
("home" "Heimverzeichnis")
("horizontal" "horizontal")
("horizontal cell alignment" "horizontale Zellenausrichtung")
("horizontal ink separation" "horizontale Tintentrennung")
("horizontal part" "horizontaler Teil")
("horizontal position" "horizontale Position")
("horizontal space" "horizontales Leerzeichen")
("horizontal table alignment" "horizontale Tabellenausrichtung")
("horizontally align cell to the base" "Zelle horizontal an der Grundlinie ausrichten")
("horizontally center the cell" "Zelle horizontal zentrieren")
("how much longer may pages become" "Wieviel länger dürfen die Seiten werden")
("how much shorter may pages become" "Wieviel kürzer dürfen die Seiten werden")
("huge" "riesig")
("hungarian" "ungarisch")
("hyperlink" "Hyperlink")
("hyphenation" "Trennung")
("icelandic" "isländisch")
("if" "wenn")
("image" "Bild")
("image links" "Bildverbindungen")
("implementation" "Implementation")
("import" "importieren")
("improving the current implementation" "aktuelle Implementation verbessern")
("inactive" "nicht aktiv")
("include" "einfügen")
("include a document" "ein Dokument einfügen")
("include file" "Datei einfügen")
("inclusion into TeXmacs" "Aufnahme in TeXmacs")
("inclusions" "eingefügte Dokumente")
("indent" "einrücken")
("indentation flag" "Einrückmarke")
("index" "Index")
("index entry" "Indexeintrag")
("index level" "Indexniveau")
("insert" "einfügen")
("insert Pr" "Pr einfügen")
("insert a TeXmacs symbol" "TeXmacs Symbol einfügen")
("insert a big operator" "einen groÿen Operator einfügen")
("insert a binary operation" "einen binären Operator einfügen")
("insert a binary relation" "ein binäres Relationszeichen einfügen")
("insert a blackboard bold character" "fetten Tafelschrift-Buchstaben einfügen")
("insert a bold calligraphic character" "fettes kalligrafisches Zeichen einfügen")
("insert a bold character" "fettes Zeichen einfügen")
("insert a calligraphic character" "kalligrafisches Zeichen einfügen")
("insert a fraction" "einen Bruch einfügen")
("insert a fraktur character" "Frakturzeichen einfügen")
("insert a greek character" "einen griechischen Buchstaben einfügen")
("insert a large left delimiter" "eine groÿe linke Klammer einfügen")
("insert a large right delimiter" "eine groÿe rechte Klammer einfügen")
("insert a large separator" "einen groÿen Separator einfügen")
("insert a left subscript" "linken Index einfügen")
("insert a link" "Beziehung einfügen")
("insert a miscellaneous symbol" "ein Symbol einfügen")
("insert a new branch" "neuen Zweig einfügen")
("insert a new item" "ein neues Element einfügen")
("insert a picture" "ein Bild einfügen")
("insert a square root" "eine Quadratwurzel einfügen")
("insert a table" "Tabelle einfügen")
("insert a table or a matrix" "eine Tabelle oder eine Matrix einfügen")
("insert an" "einfügen:")
("insert an accent" "einen Akzent einfügen")
("insert an arrow" "einen Pfeil einfügen")
("insert an environment" "eine Umgebung einfügen")
("insert an n" "einfügen: n")
("insert appendix" "Anhang einfügen")
("insert arccos" "arccos einfügen")
("insert arcsin" "arcsin einfügen")
("insert arctan" "arctan einfügen")
("insert arg" "arg einfügen")
("insert argument" "neues Argument einfügen")
("insert automatically generated content" "automatisch generierten Inhalt einfügen")
("insert big contour integral" "groÿes Kreisintegral einfügen")
("insert big coproduct" "groÿes Koprodukt einfügen")
("insert big direct sum" "groÿe direkte Summe einfügen")
("insert big dotted point" "groÿen Kreispunkt einfügen")
("insert big integral" "groÿes Integral einfügen")
("insert big intersection" "groÿen Durchschnitt einfügen")
("insert big logical and" "groÿes logisches Und einfügen")
("insert big logical or" "groÿes logisches Oder einfügen")
("insert big product" "groÿes Produkt einfügen")
("insert big square union" "groÿe rechte Vereinigung einfügen")
("insert big summation" "groÿe Summe einfügen")
("insert big tensor product" "groÿes Tensorprodukt einfügen")
("insert big union" "groÿe Vereinigung einfügen")
("insert big union sum" "groÿe Vereinigungssumme einfügen")
("insert big vertical space" "groÿes vertikales Leerzeichen einfügen")
("insert chapter" "Kapitel einfügen")
("insert column" "Spalte einfügen")
("insert column to the left" "Spalte links einfügen")
("insert column to the right" "Spalte rechts einfügen")
("insert cos" "cos einfügen")
("insert cosh" "cosh einfügen")
("insert cot" "cot einfügen")
("insert coth" "coth einfügen")
("insert csc" "csc einfügen")
("insert deg" "deg einfügen")
("insert det" "det einfügen")
("insert dim" "dim einfügen")
("insert dollar" "Dollar einfügen")
("insert equation" "Gleichung einfügen")
("insert executable markup" "ausführbaren Inhalt einfügen")
("insert exp" "exp einfügen")
("insert footnote" "Fuÿnote einfügen")
("insert formula" "Formel einfügen")
("insert gcd" "gcd einfügen")
("insert hom" "hom einfügen")
("insert horizontal interword space" "horizontales Leerzeichen einfügen")
("insert image" "Bild einfügen")
("insert inactive markup" "inaktiven Inhalt einfügen")
("insert inf" "inf einfügen")
("insert ker" "ker einfügen")
("insert lg" "lg einfügen")
("insert lim" "lim einfügen")
("insert liminf" "liminf einfügen")
("insert limsup" "limsup einfügen")
("insert ln" "ln einfügen")
("insert log" "log einfügen")
("insert mathematics" "Mathematik einfügen")
("insert max" "max einfügen")
("insert medium horizontal space" "mittleres horizontales Leerzeichen einfügen")
("insert medium vertical space" "vertikales Leerzeichen einfügen")
("insert min" "min einfügen")
("insert negative horizontal space" "kleines negatives horizontales Leerzeichen einfügen")
("insert new item or number" "neues Element oder Nummer einfügen")
("insert new rows or columns" "neue Zeilen oder Spalten einfügen")
("insert or delete rows or columns" "Zeilen oder Spalten einfügen oder löschen")
("insert row" "Zeile einfügen")
("insert row above" "Reihe oberhalb einfügen")
("insert row below" "Reihe unterhalb einfügen")
("insert sec" "sec einfügen")
("insert section" "Abschnitt einfügen")
("insert sharp" "Kreuz einfügen")
("insert sin" "sin einfügen")
("insert sinh" "sinh einfügen")
("insert small horizontal space" "kleines horizontales Leerzeichen einfügen")
("insert small vertical space" "kleines vertikales Leerzeichen einfügen")
("insert structural markup" "strukturellen Inhalt einfügen")
("insert subsection" "Unterabschnitt einfügen")
("insert subsubsection" "Unterunterabschnitt einfügen")
("insert sup" "sup einfügen")
("insert tan" "tan einfügen")
("insert tanh" "tanh einfügen")
("insert thick horizontal space" "dickes horizontales Leerzeichen einfügen")
("interface" "Schnittstelle")
("interfacing" "Schnittstellen")
("interfacing TeXmacs with other systems" "Schnittstellen von TeXmacs mit anderen Systemen")
("interjection" "Interjektion")
("interline separation" "Trennung zwischen Zeilen")
("interline space" "Zeilenabstand")
("internationalization" "Internationalisierung")
("interparagraph space" "Absatzabstand")
("interrupt execution" "Ausführung unterbrechen")
("introduction" "Einführung")
("invisible" "unsichtbar")
("invisible citation" "unsichtbares Zitat")
("irish" "irisch")
("is running" "läuft")
("is tuple" "ist Tupel")
("ispell does not respond" "ispell antwortet nicht")
("ispell is already busy" "ispell ist schon beschäftigt")
("italian" "italienish")
("italic" "kursiv")
("italic right" "kursiv aber senkrecht")
("itemize" "auflisten")
("january" "Januar")
("japanese" "japanisch")
("july" "Juli")
("june" "Juni")
("justified" "ausgerichtet")
("justify text" "Text ausrichten")
("key" "Taste")
("keyboard" "Tastatur")
("keyboard equivalent" "Tastenkombination")
("keyboard modifiers" "Tastatur-Modifier")
("keyboard shorthand" "Tastenkombination")
("keymaps" "Tastatur Mappings")
("keyword" "Stichwort")
("keywords" "Stichworte")
("kill" "vernichten")
("known bugs" "Bekannte Fehler")
("label" "Textmarke")
("landscape" "quer")
("language" "Sprache")
("large" "groÿ")
("large closing bracket" "groÿe schlieÿende eckige Klammer")
("large delimiter" "groÿer Begrenzer")
("large opening bracket" "groÿe öffnende eckige Klammer")
("large separator" "groÿes Trennzeichen")
("last indentation" "lezte Einrückung")
("last page" "lezte Seite")
("latex command" "LaTeX Befehl")
("latin" "lateinisch")
("layout" "Layout")
("left" "links")
("left border" "linker Rand")
("left margin" "linker Rand")
("left padding" "linke Auffüllung")
("left prime" "linker Strich")
("left ragged" "linksbündig")
("left slanted" "geneigt nach links")
("left subscript" "linker Index")
("left superscript" "linker Exponent")
("left surrounding" "linkes Umfeld")
("legal" "Legal")
("lemma" "Lemma")
("length" "Länge")
("less" "kleiner")
("less or equal" "kleiner oder gleich")
("letter" "Brief")
("license" "Lizenz")
("light" "dünn")
("limitations" "Einschränkungen")
("limits" "Grenzen")
("line" "Linie")
("line break" "Zeilenumbruch")
("line stretch" "Dehnbarkeit der Zeilen")
("link" "Verknüpfung")
("link image" "Bild verbinden")
("list" "Liste")
("list of figures" "Abbildungsverzeichnis")
("list of tables" "Tabellenverzeichnis")
("load" "laden")
("load LaTeX file" "LaTeX Datei laden")
("load TeX file" "TeX Datei laden")
("load TeXmacs file" "TeXmacs Datei laden")
("load TeXmacs style file" "TeXmacs Stildatei laden")
("load a file" "Datei laden")
("load buffer" "Puffer laden")
("load file" "Datei laden")
("load html file" "HTML-Datei laden")
("load image" "Bild laden")
("load in new window" "in neuem Fenster laden")
("load latex file" "LaTeX-Datei laden")
("load more recent autosave file" "neuere Sicherheitskopie laden")
("load tex file" "TeX-Datei laden")
("load verbatim file" "Text-Datei laden")
("loaded" "geladen")
("long" "lang")
("look and feel" "Aussehen")
("look up" "suche")
("lower border" "unterer Rand")
("macro" "Makro")
("magenta" "violett")
("magic" "magisch")
("magnification" "Vergröÿerungsfaktor")
("magnified" "vergröÿert")
("main" "Haupt-")
("main icon bar" "Hauptsymbolleiste")
("major changes" "Wichtige Veränderungen")
("make a page insertion" "Seiteneinfügung machen")
("make a subscript" "einen Index machen")
("make a superscript" "eine Potenz machen")
("make acute" "Akzent nach rechts machen")
("make bar" "Balken machen")
("make check" "Haken machen")
("make fraction" "Bruch machen")
("make grave" "Akzent nach links machen")
("make hat" "Hut machen")
("make label" "Textmarke einfügen")
("make negation" "Verneinung machen")
("make page reference" "Seitenverweis machen")
("make reference" "Verweis machen")
("make square root" "Quadratwurzel machen")
("make tilde" "Tilde machen")
("make title" "Titel erzeugen")
("make vector" "Vektor machen")
("making donations" "Spenden")
("manual" "Anleitung")
("map to" "legen auf")
("march" "März")
("margins" "Ränder")
("margins as on paper" "Ränder wie auf dem Papier")
("master" "Meister")
("master file" "Meisterdatei")
("math" "Math")
("math font" "Math Schriftart")
("math font family" "Math Schriftfamilie")
("math font series" "Math Schriftserie")
("math font shape" "Math Schriftform")
("mathematical" "mathematisch")
("mathematical formulas" "mathematische Formeln")
("mathematical typesetting" "mathematischer Schriftsatz")
("mathematics" "Mathematik")
("matrix" "Matrix")
("maximal number of columns" "Maximale Anzahl von Spalten")
("maximal number of rows" "Maximale Anzahl von Zeilen")
("maximum mode" "maximaler Modus")
("may" "Mai")
("medium" "mittel")
("medium skip" "mittlerer Abstand")
("meminfo" "Speicher-Info")
("merge" "zusammenfügen")
("messy" "komisch")
("meta key" "Meta-Taste")
("middle" "Mitte")
("minimal number of columns" "Minimale anzahl von Spalten")
("minimal number of rows" "Minimale Anzahl von Zeilen")
("minimum mode" "minimaler Modus")
("minus" "Minus")
("miscellaneous" "verschiedenes")
("mod" "mod")
("mode" "Modus")
("modifier" "Modifier")
("modify cell alignment" "Zellenausrichtung ändern")
("modify cell border" "Zellenumrandung ändern")
("modify cell padding" "Zellenauffüllung ändern")
("modify cell size" "Zellenbreite ändern")
("modify table border" "Tabellenumrandung ändern")
("modify table padding" "Tabellenauffüllung ändern")
("mongolian" "mongolisch")
("more information about GNU TeXmacs can be found in the help" "weitere Informationen über GNU TeXmacs finden Sie unter Hilfe")
("mosaic" "Mosaik")
("move down" "nach unten bewegen")
("move object" "Objekt verschieben")
("move to the right when finished" "zum Schluss nach rechts bewegen")
("move up" "nach oben bewegen")
("n-th" "n-te")
("n-th root" "n-te Wurzel")
("name" "Name")
("negation" "Verneinung")
("new" "neu")
("new buffer" "neuer Puffer")
("new column" "neue Spalte")
("new item" "neuer Spiegelstrich")
("new line" "neue Zeile")
("new number" "neue Nummer")
("new page" "neue Seite")
("new page before" "neue Seite davor")
("new paragraph" "neuer Absatz")
("new roman" "New Roman")
("new row" "neue Zeile")
("new table" "neue Tabelle")
("next line" "nächste Zeile")
("no changes need to be saved" "keine Änderungen brauchen gesichert zu werden")
("no dictionary for" "kein Wörterbuch für")
("no dictionnary for" "kein Wörterbuch für")
("no first indentation" "keine erste Einrückung")
("no indentation" "keine Einrückung")
("no line break" "kein Zeilenumbruch")
("no matches found" "nichts gefunden")
("no more matches for" "es gibt keine anderen Fundstellen von")
("no more redo information available" "es gibt keine weitere Information für ``wiederholen''")
("no more undo information available" "es gibt keine weitere Information um zurückzugehen")
("no name" "ohne Name")
("no page break after" "danach kein Seitenumbruch")
("no page break before" "davor kein Seitenumbruch")
("no spelling errors found in text" "keine Schreibfehler im Text entdeckt")
("no style" "kein Stil")
("none" "keiner")
("normal" "normal")
("not" "nicht")
("not equal" "ungleich")
("not found" "nicht gefunden")
("notation" "Notierung")
("note" "Anmerkung")
("november" "November")
("number" "Zahl")
("number of columns" "Spaltenanzahl")
("numbered equation" "nummerierte Gleichung")
("numbered equations" "nummerierte Gleichungen")
("numerator" "Zähler")
("numeric" "numerisch")
("objectives" "Ziele")
("occurrences" "Vorkommen ersetzt")
("october" "Oktober")
("odd page footer" "Fuÿ für ungerade Seiten")
("odd page header" "Kopf für ungerade Seiten")
("odd page margin" "Rand für ungerade Seiten")
("odd page text" "Text für ungerade Seiten")
("off" "aus")
("ok" "ok")
("old english" "altenglish")
("old slavonic" "altslawisch")
("old style" "alter Stil")
("on" "an")
("on cells" "auf Zellen")
("on columns" "auf Spalten")
("on entire table" "auf die gesamte Tabelle")
("on rows" "auf Zeilen")
("one spelling error has been corrected" "ein Schreibfehler wurde korrigiert")
("online documentation" "Online-Dokumentation")
("online help" "Online-Hilfe")
("open" "öffnen")
("open a new buffer" "neuen Puffer öffnen")
("open new window" "neues Fenster öffnen")
("opening" "Eröffnung")
("operation on named selection" "Operation auf Auswahl mit Namen")
("operation on primary selection" "Operation auf erstee Auswahl")
("operation on secondary selection" "Operation auf zweitee Auswahl")
("operation on ternary selection" "Operation auf drittee Auswahl")
("optical" "optisch")
("option" "Option")
("options" "Optionen")
("or" "oder")
("orange" "orange")
("orientation" "Orientierung")
("origin" "Ursprung")
("original welcome message" "originale Begrüÿungsbotschaft")
("other" "anders")
("other pages" "andere Seiten")
("other projects" "andere Projekte")
("other style" "anderer Stil")
("outlined roman" "Roman Outlined")
("over" "über")
("padding" "Auffüllung")
("page" "Seite")
("page bottom margin" "unterer Seitenrand")
("page break" "Seitenumbruch")
("page break before" "Seitenumbruch vorher")
("page height" "Seitenhöhe")
("page insertion" "Seiteneinfügung")
("page layout" "Seitenlayout")
("page reference" "Seitenverweis")
("page right margin" "rechter Seitenrand")
("page top margin" "oberer Seitenrand")
("page type" "Seitentyp")
("page width" "Seitenbreite")
("paper" "Papier")
("paper type" "Papiertyp")
("papyrus" "Papyrus")
("paragraph" "Absatz")
("paragraph mode" "Absatztyp")
("paragraph width" "Absatzbreite")
("pari" "Pari")
("part" "Teil")
("past changes" "frühere Änderungen")
("paste" "einfügen")
("paste from" "einfügen aus")
("paste text" "Text einfügen")
("path" "Weg")
("perform operations on cells" "Operationen auf Zellen anwenden")
("perform operations on columns" "Operationen auf Spalten anwenden")
("perform operations on entire table" "Operationen auf der gesamten Tabelle anwenden")
("perform operations on rows" "Operationen auf Reihen anwenden")
("permanent" "permanent")
("person" "Person")
("personal dictionary has been modified" "Ihr persönliches Wörterbuch ist geändert worden")
("phantasy" "Fantasie")
("philosophy" "Philosophie")
("phoenician" "phönizisch")
("phonetic" "phonetisch")
("pink" "rosa")
("plain block" "normaler Block")
("plain tabular" "normaler Tabulatormodus")
("planned changes" "Geplante Änderungen")
("plans for the future" "Zukünftspläne")
("please" "bitte")
("please wait" "ein Augenblick bitte")
("plus" "plus")
("polish" "Polnisch")
("porting TeXmacs to other platforms" "TeXmacs auf andere Plattformen portieren")
("portrait" "hochkant")
("portuguese" "portugiesisch")
("position" "Position")
("position float" "Treiber positionieren")
("position floating object" "treibendes Objekt positionieren")
("position the table" "Tabelle positionieren")
("postscript" "Postscript")
("postscript image" "Postscript-Bild")
("pre-alpha release" "Vor-Alpha Version")
("preamble" "Präambel")
("preamble mode" "Präambel-Modus")
("preferences" "Einstellungen")
("presentation mode" "Präsentationsmodus")
("preview before printing" "Druckvorschau")
("preview with ghostview" "Druckvorschau mit Ghostview")
("primary" "erste")
("prime" "Strich")
("print" "drucken")
("print all" "alles drucken")
("print all to file" "alles in Datei drucken")
("print page selection" "Ausgewählte Seiten drucken")
("print page selection to file" "Ausgewählte Seiten in Datei drucken")
("print to postscript file" "drucken in Postscript-Datei")
("printer" "Drucker")
("printer dpi" "Druckerauflösung in Punkten pro Zoll (dpi)")
("printing command" "Druckkommando")
("problem" "Problem")
("professional" "professionell")
("prog" "Prog")
("prog font" "Prog Schriftart")
("prog font family" "Prog Schriftfamilie")
("prog font series" "Prog Schriftserie")
("prog font shape" "Prog Schriftform")
("program" "Programm")
("program mode" "Programmmodus")
("programming" "Programmieren")
("progressive" "fortschrittlich")
("project" "Projekt")
("projects" "Projekte")
("prologue" "Vorwort")
("prompt on scripts" "bei jedem Script nachfragen")
("proof" "Beweis")
("proportional" "proportional")
("proportional typewriter" "proportionale Schreibmachinenschrift")
("proposition" "Proposition")
("query replace" "ersetzen mit Rückfragen")
("quit" "verlassen")
("quotation" "Zitat")
("quote" "zitieren")
("range" "Bereich")
("really huge" "riesengroÿ")
("really quit" "wollen Sie wirklich beenden")
("red" "rot")
("redo" "wieder")
("redo undone changes" "stornierte Änderungen wiederherstellen")
("reduce bottom margin by" "unteren Rand reduzieren um")
("reduce left margin by" "linken Rand reduzieren um")
("reduce margins" "Ränder reduzieren")
("reduce right margin by" "rechten Rand reduzieren um")
("reduce top margin by" "oberen Rand reduzieren um")
("reduction even page margin" "Randreduktion für gerade Seiten")
("reduction odd page margin" "Randreduktion für ungerade Seiten")
("reduction page bottom margin" "Reduktion des unteren Seitenrandes")
("reduction page right margin" "Reduktion des rechten Seitenrandes")
("reduction page top margin" "Reduktion des oberen Seitenrandes")
("reference" "Verweis")
("references" "Verweise")
("regular" "normal")
("release" "Version")
("reload" "wieder laden")
("remark" "Bemerkung")
("remove this switch" "entferne diese Ebene")
("repeat object" "Objekt wiederholen")
("replace" "ersetzen")
("replace by" "ersetzen durch")
("replaced" "ich habe")
("replaced one occurrence" "ich habe ein Vorkommen ersetzt")
("reset" "zurücksetzen")
("resize object" "Objektgröÿe ändern")
("resized" "gestreckt")
("return" "return")
("revert" "wieder laden")
("revert buffer" "wieder laden")
("right" "aufrecht")
("right border" "rechter Rand")
("right margin" "rechter Rand")
("right padding" "rechte Auffüllung")
("right ragged" "rechtsbündig")
("right subscript" "rechter Index")
("right superscript" "rechter Exponent")
("right surrounding" "rechtes Umfeld")
("rigid" "unveränderlich")
("rigid horizontal" "unveränderlich horizontal")
("rigid space" "unveränderliches Leerzeichen")
("roman" "Roman")
("roman right" "Roman senkrecht")
("romanian" "rumänisch")
("root" "Wurzel")
("rotate backward" "rotiere rückwärts")
("rotate forward" "rotiere vorwärts")
("row" "Zeile")
("row contains glued items" "Zeile enthält aneinandergeklebte Teile")
("rumanian" "rumänisch")
("runic" "runisch")
("running author" "laufender Autor")
("running title" "laufender Titel")
("russian" "russisch")
("russian and Ukrainian users" "russische und ukrainische Benutzer")
("sample" "Beispiel")
("sans serif" "ohne Serifen")
("save" "sichern")
("save TeXmacs file" "TeXmacs Datei sichern")
("save TeXmacs style file" "TeXmacs Stil-Datei sichern")
("save as" "sichern als")
("save as LaTeX" "als LaTeX sichern")
("save as TeX" "als TeX sichern")
("save buffer" "Puffer sichern")
("save buffer as" "Puffer sichern als")
("save file" "Datei sichern")
("save html file" "HTML-Datei sichern")
("save image" "Bild sichern")
("save latex file" "LaTeX-Datei sichern")
("save tex file" "TeX-Datei sichern")
("save this buffer" "Puffer sichern")
("save verbatim file" "Text-Datei sichern")
("saved" "gesichert")
("scheme" "Schema")
("screen layout" "Layout auf dem Bildschirm")
("screen margins" "Ränder auf dem Bildschirm")
("script" "Index")
("script above" "Index oben")
("script below" "Index unten")
("script script size" "Untenindexgröÿe")
("script size" "Indexgröÿe")
("scripts not accepted" "Scripts werden nie akzeptiert")
("search" "suchen")
("searching" "suche")
("secondary" "zweite")
("section" "Abschnitt")
("security" "Sicherheit")
("see" "sehen")
("select a document style" "einen Dokumentenstil auswählen")
("select a foreground color" "eine Vordergrundfarbe auswählen")
("select a language" "eine Sprache auswählen")
("selected region" "ausgewählter Bereich")
("selection" "Auswahl")
("selections" "Auswahlen")
("seminar" "Seminar")
("separation between lines" "Zeilenabstand")
("separation between paragraphs" "Abstand zwischen Absätzen")
("separator" "Trennzeichen")
("september" "September")
("series" "Serie")
("series|right" "senkrecht")
("session" "Sitzung")
("session name" "Name der Sitzung")
("session type" "Sitzungstyp")
("sessions" "Sitzungen")
("set" "einstellen")
("set background color of cell" "Zellenhintergrundfarbe einstellen")
("set cell mode" "Zellenmodus einstellen")
("set extension center" "Ausweitungszentrum festlegen")
("set height" "Höhe einstellen")
("set height of cell" "Zellenhöhe einstellen")
("set margins" "Ränder ändern")
("set n" "n eingeben")
("set paragraph margins" "Absatzränder einstellen")
("set paragraph mode" "Absatztyp einstellen")
("set printer dpi" "Druckerauflösung festlegen")
("set printing command" "Druckkommando festlegen")
("set span" "setze Spanne")
("set special cell properties" "spezielle Zelleneigenschaften einstellen")
("set special table properties" "spezielle Tabelleneigenschaften einstellen")
("set text width" "Textbreite ändern")
("set width" "Breite einstellen")
("set width of cell" "Zellenbreite einstellen")
("settings" "Einstellungen")
("setup printer" "Drucker einstellen")
("shape" "Form")
("shell" "Shell")
("shift-down" "shift-unten")
("shift-right" "shift-rechts")
("show" "zeigen")
("show header and footer" "Seitenkopf und Seitenfuÿ zeigen")
("show on screen" "auf dem Bildschirm zeigen")
("shrinking factor" "Reduktionsfaktor")
("signature" "Unterschrift")
("size" "Gröÿe")
("size limits" "Gröÿenbegrenzungen")
("slanted" "geneigt")
("sloppy" "nachlässig")
("small" "klein")
("small caps" "kleine Groÿbuchstaben")
("small figure" "kleine Figur")
("small skip" "kleiner Abstand")
("small table" "kleine Tabelle")
("source code" "Quellcode")
("space" "Leerzeichen")
("space between lines" "Zeilenabstand")
("space between paragraphs" "Abstand zwischen Absätzen")
("spacing" "Abstände")
("spanish" "spanisch")
("special" "speziell")
("special cell properties" "spezielle Zelleneigenschaften")
("special table properties" "spezielle Tabelleneigenschaften")
("specific" "spezifisch")
("spell" "Rechtschreibprüfung")
("spell checking complete" "Rechtschreibprüfung beendet")
("spelling error" "Schreibfehler")
("spelling errors have been corrected" "Schreibfehler im Text korrigiert")
("split" "Aufteilung")
("square root" "Quadratwurzel")
("start" "Start")
("start a new chapter" "ein neues Kapitel beginnen")
("start a new section" "einen neuen Abschnitt beginnen")
("start an interactive session" "eine interaktive Sitzung beginnen")
("status bar" "Statusbalken")
("stretchable" "dehnbar")
("stretchable horizontal" "horizontal dehnbar")
("stretchable vertical" "vertikal dehnbar")
("stroke" "Strich")
("strokes" "Striche")
("strong" "stark")
("structural" "strukturell")
("style" "Stil")
("styles" "Stile")
("sub" "Unter-")
("subparagraph" "Unterabsatz")
("subscript" "Index")
("subsection" "Unterabschnitt")
("subsub" "Unter-Unter-")
("subsubsection" "Unterunterabschnitt")
("summary" "Zusammenfassung")
("superpose" "überlagern")
("superposed" "überlagert")
("superscript" "Exponent")
("swedish" "schwedisch")
("switch" "Ebene")
("switch to first" "Erste Ebene")
("switch to formula style" "Formelstil benutzen")
("switch to last" "Letzte Ebene")
("switch to next" "Nächste Ebene")
("switch to previous" "Vorherige Ebene")
("switching and folding" "Umschalten und Falten")
("symbol" "Symbol")
("system environment variables" "Umgebungsvariablen des Systems")
("tab" "tab")
("table" "Tabelle")
("table command" "Tabellenkommando")
("table of contents" "Inhaltsverzeichnis")
("tables" "Tabellen")
("tabular" "tabulieren")
("tabular material" "Tabulatormaterial")
("teXmacs as an interface" "TeXmacs als Benutzerschnittstelle")
("teXmacs fonts" "TeXmacs Zeichensätze")
("teXmacs notice" "TeXmacs Notiz")
("ternary" "dritte")
("test" "test")
("tex" "TeX")
("text" "Text")
("text font" "Text Schriftart")
("text height correction" "Texthöhenkorrektur")
("text width" "Textbreite")
("texts" "Texte")
("th century bc" "te Jahrhundert v.u.Z.")
("th root" "-te Wurzel")
("thai" "thailändish")
("the TeXmacs authors" "die TeXmacs-Autoren")
("the application did not send its usual startup banner" "das Programm hat nicht die normale Willkommensbotschaft geschickt")
("the application does not reply" "das Programm antwortet nicht")
("the application is already running" "das Programm läuft schon")
("the boxes produced by the typesetter" "die Boxen, die vom Satzprogramm erzeugt werden")
("the graphical user interface" "die grafische Benutzerschnittstelle")
("the leaves of TeXmacs trees" "die Zweige eines TeXmacs-Baumes")
("the mycas example" "das mycas-Beispiel")
("the primitive TeXmacs constructs" "der grundlegende TeXmacs-Aufbau")
("the standard TeXmacs styles" "die Standardstile von TeXmacs")
("theorem" "Satz")
("there are unsaved files" "nicht alle Dateien sind gesichert")
("this document has been produced using" "Dieses Dokument wurde erzeugt mit")
("this line" "diese Zeile")
("this page" "diese Seite")
("tilda" "Tilde")
("tilde" "Tilde")
("times" "mal")
("tiny" "winzig")
("title" "Titel")
("to the left" "nach links")
("to the right" "nach rechts")
("today" "heute")
("tools" "Werkzeuge")
("top" "ganz oben")
("top border" "obere Begrenzung")
("top level" "oberes Niveau")
("top margin" "oberer Rand")
("top padding" "obere Auffüllung")
("translate" "Übersetzen")
("tree" "Baum")
("tuple" "Tupel")
("turkish" "türkisch")
("tutorial" "Tutorial")
("type" "Typ")
("type a latex command followed by" "LaTeX-Befehl tippen und dann")
("type body" "Körper eingeben")
("type denominator" "Nenner eingeben")
("type numerator" "Zähler eingeben")
("type script" "Index eingeben")
("typesetted boxes" "Typographierte Boxen")
("typewriter" "Schreibmaschinenschrift")
("typewriter small caps" "Schreibmachinenschrift mit kleinen Groÿbuchstaben")
("typing a simple text" "einfachen Text tippen")
("typing simple texts" "einfache Texte tippen")
("ugaritic" "ugaritisch")
("ukrainian" "ukrainisch")
("undo" "zurück")
("undo last changes" "letzte Änderungen stornieren")
("up" "hoch")
("update" "aktualisieren")
("update from web" "aktualisiere aus dem Internet")
("update image links" "Bildverbindungen aktualisieren")
("upper border" "oberer Rand")
("use TeXmacs" "benutze TeXmacs")
("use a black color" "schwarze Farbe benutzen")
("use a blue color" "blaue Farbe benutzen")
("use a bold font" "benutze einen fetten Zeichensatz")
("use a brown color" "braune Farbe benutzen")
("use a calligraphic font" "eine kalligraphische Schriftart benutzen")
("use a green color" "grüne Farbe benutzen")
("use a grey color" "graue Farbe benutzen")
("use a magenta color" "violette Farbe benutzen")
("use a orange color" "orange Farbe benutzen")
("use a pink color" "rosa Farbe benutzen")
("use a red color" "rote Farbe benutzen")
("use a sans serif font" "Schriftart ohne Serifen benutzen")
("use a typewriter font" "Schreibmachinenschriftart benutzen")
("use a white color" "weiÿe Farbe benutzen")
("use a yellow color" "gelbe Farbe benutzen")
("use blackboard bold font" "Fette Tafel-Schriftart benutzen")
("use bold font series" "fette Buchstaben benutzen")
("use calligraphic font" "kalligrafische Schriftart benutzen")
("use calligraphical font" "kalligrafische Schriftart nützen")
("use footnote font size" "sehr kleine Buchstaben benutzen")
("use fraktur font" "gotische Schriftart benutzen")
("use huge font size" "riesige Buchstaben benutzen")
("use italic font shape" "kursive Buchstaben benutzen")
("use large font size" "groÿe Buchstaben benutzen")
("use left hand column as border" "linke Spalte als Begrenzung benutzen")
("use medium font series" " Buchstaben mit normaler Dicke benutzen")
("use normal font size" "Buchstaben mit normaler Gröÿe benutzen")
("use package" "Paket benutzen")
("use paragraph width" "Absatzbreite benutzen")
("use really huge font size" "riesengroÿe Buchstaben benutzen")
("use right font shape" "aufrechte Buchstaben benutzen")
("use right hand column as border" "rechte Spalte als Begrenzung benutzen")
("use roman font family" "romanische Schriftart benutzen")
("use row above as border" "obere Zeile als Begrenzung benutzen")
("use row below as border" "untere Zeile als Begrenzung benutzen")
("use sans serif font family" "Schriftart ohne Serifen benutzen")
("use script font size" "sehr kleine Buchstaben benutzen")
("use slanted font shape" "schräge Buchstaben benutzen")
("use small capitals" "kleine Groÿbuchstaben benutzen")
("use small font size" "kleine Buchstaben benutzen")
("use small-caps font shape" "kleine Groÿbuchstaben benutzen")
("use the blackboard bold font" "die Schriftart Blackboard fett benutzen")
("use the fraktur font" "die Fraktur-Schriftart benutzen")
("use tiny font font size" "winzige Buchstaben benutzen")
("use typewriter font family" "Schreibmachinenschriftart benutzen")
("use very large font size" "sehr groÿe Buchstaben benutzen")
("user manual" "Benutzeranleitung")
("user provided icons" "Anwendersymbole")
("value" "Wert")
("variable" "Variable")
("variant" "Variante")
("vector" "Vektor")
("verbatim" "Text")
("verse" "Vers")
("vertical" "vertikal")
("vertical after" "vertikal nach")
("vertical before" "vertikal vor")
("vertical cell alignment" "vertikale Zellenausrichtung")
("vertical part" "vertikaler Teil")
("vertical position" "vertikale Position")
("vertical space" "vertikales Leerzeichen")
("vertical table alignment" "vertikale Tabellenausrichtung")
("vertically align cell to the base" "Zelle vertikal an der Grundlinie ausrichten")
("vertically center the cell" "Zelle vertikal zentrieren")
("very large" "sehr groÿ")
("very small" "sehr klein")
("vietnamese" "vietnamesisch")
("view" "Ansicht")
("visible" "sichtbar")
("warning" "Warnung")
("welcome" "Willkommen")
("welcome to GNU TeXmacs" "Herzlich Willkommen zu GNU TeXmacs")
("what is new" "Was ist neu")
("when finished" "zum Schluss")
("while" "solang")
("white" "weiÿ")
("wide accent" "breiter Akzent")
("width" "Breite")
("width is exactly the specified width" "Breite ist genau die spezifizierte Breite")
("width is maximum of specified width and box width" "Breite ist das Maximum von spezifizierter Breite und Boxenbreite")
("width is minimum of specified width and box width" "Breite ist das Minimum von spezifizierter Breite und Boxenbreite")
("width magnification" "Breitenvergröÿerung")
("window" "Fenster")
("window height" "Fensterhöhe")
("window width" "Fensterbreite")
("windows key" "Windows-Taste")
("with" "mit")
("write a name" "einen Namen schreiben")
("write bold mathematics" "fette Mathematik schreiben")
("write bold text" "fetten Text schreiben")
("write italic text" "kursiven Text schreiben")
("write sample text" "Beispieltext schreiben")
("write strong text" "kräftigen Text schreiben")
("write typewriter text" "Schreibmachinentext schreiben")
("write verbatim text" "wörtlichen Text schreiben")
("writing data converters" "Datenkonverter schreiben")
("writing your own style files" "Ihren ersten eigenen Stil schreiben")
("yellow" "gelb")
("you can also obtain" "Sie können")
("your document is back in its original state" "Ihr Dokument ist wieder in seinem Originalzustand")
("your first interface" "Ihre erste Schnittstelle")
("your language" "Ihre Sprache")
