;; Conversions between TeXmacs symbols and Unicode: the ones
;; the symbol tables are missing
;;
;; Generated by tests/opentype/missing-symbols.py from the symbol list of
;; unicode-math, and meant to be reviewed and then wired in: the tables are
;; loaded by name in src/Data/String/converter.cpp, so a line
;;   hashtree_from_dictionary (dic, "tmuniversaltounicode-extra", ...)
;; next to each one for tmuniversaltounicode, in both directions, is what
;; puts these symbols into service.
;;
;; Every entry here is one that no table names, whose name is free, and
;; whose glyph at least half of the math fonts TeXmacs ships draw. The
;; names come from unicode-math and are candidates, not decisions: TeXmacs
;; names are shape-based and compositional. The comment gives the Unicode
;; description and the number of fonts.
;;
;; The class of a symbol, which is what gives it its spacing, does not live
;; here but in progs/language/std-symbols.scm; the same script drafts those
;; groups with --emit.


;;; Punctuation

("<mathhyphen>"		"#2010")	; hyphen [12 fonts]
("<horizbar>"		"#2015")	; horizontal bar [10 fonts]
("<twolowline>"		"#2017")	; double low line (spacing) [9 fonts]
("<dprime>"		"#2033")	; double prime or second, not superscripted [10 fonts]
("<trprime>"		"#2034")	; triple prime (not superscripted) [10 fonts]
("<backdprime>"		"#2036")	; double reverse prime, not superscripted [9 fonts]
("<backtrprime>"	"#2037")	; triple reverse prime, not superscripted [9 fonts]
("<tieconcat>"		"#2040")	; character tie, z notation sequence concatenation [6 fonts]
("<fracslash>"		"#2044")	; fraction slash [12 fonts]
("<qprime>"		"#2057")	; quadruple prime, not superscripted [9 fonts]

;;; Currency

("<euro>"		"#20AC")	; euro sign [12 fonts]

;;; Letterlike

("<Eulerconst>"		"#2107")	; euler constant [10 fonts]
("<Planckconst>"	"#210E")	; planck constant [12 fonts]
("<Angstrom>"		"#212B")	; angstrom capital a, ring [10 fonts]
("<Finv>"		"#2132")	; turned capital f [6 fonts]
("<Bbbgamma>"		"#213D")	; double-struck small gamma [9 fonts]
("<BbbGamma>"		"#213E")	; double-struck capital gamma [9 fonts]
("<BbbPi>"		"#213F")	; double-struck capital pi [9 fonts]
("<Bbbsum>"		"#2140")	; double-struck n-ary summation [10 fonts]
("<Game>"		"#2141")	; turned sans-serif capital g [6 fonts]
("<mitBbbD>"		"#2145")	; double-struck italic capital d [9 fonts]
("<mitBbbd>"		"#2146")	; double-struck italic small d [9 fonts]
("<mitBbbe>"		"#2147")	; double-struck italic small e [9 fonts]
("<mitBbbi>"		"#2148")	; double-struck italic small i [9 fonts]
("<mitBbbj>"		"#2149")	; double-struck italic small j [9 fonts]
("<upand>"		"#214B")	; turned ampersand [6 fonts]

;;; Arrows

("<twoheaduparrow>"	"#219F")	; up two-headed arrow [11 fonts]
("<twoheaddownarrow>"	"#21A1")	; down two-headed arrow [11 fonts]
("<mapsup>"		"#21A5")	; maps to, upward [11 fonts], shape checked
("<mapsdown>"		"#21A7")	; maps to, downward [11 fonts], shape checked
("<Ldsh>"		"#21B2")	; left down angled arrow [10 fonts]
("<Rdsh>"		"#21B3")	; right down angled arrow [10 fonts]
("<linefeed>"		"#21B4")	; rightwards arrow with corner downwards [10 fonts]
("<carriagereturn>"	"#21B5")	; downwards arrow with corner leftward = carriage return [10 fonts]
("<updownarrows>"	"#21C5")	; up arrow, down arrow [11 fonts]
("<Nwarrow>"		"#21D6")	; nw pointing double arrow [12 fonts]
("<Nearrow>"		"#21D7")	; ne pointing double arrow [12 fonts]
("<Searrow>"		"#21D8")	; se pointing double arrow [12 fonts]
("<Swarrow>"		"#21D9")	; sw pointing double arrow [12 fonts]
("<leftdasharrow>"	"#21E0")	; leftwards dashed arrow [6 fonts]
("<rightdasharrow>"	"#21E2")	; rightwards dashed arrow [6 fonts]
("<leftwhitearrow>"	"#21E6")	; leftwards white arrow [10 fonts]
("<upwhitearrow>"	"#21E7")	; upwards white arrow [10 fonts]
("<rightwhitearrow>"	"#21E8")	; rightwards white arrow [10 fonts]
("<downwhitearrow>"	"#21E9")	; downwards white arrow [10 fonts]
("<downuparrows>"	"#21F5")	; downwards arrow leftwards of upwards arrow [11 fonts]
("<rightthreearrows>"	"#21F6")	; three rightwards arrows [11 fonts]

;;; Mathematical operators

("<increment>"		"#2206")	; laplacian (delta; nabla\string^2) [12 fonts]
("<smallin>"		"#220A")	; set membership (small set membership) [10 fonts]
("<smallni>"		"#220D")	; /ni /owns r: contains (small contains as member) [10 fonts]
("<QED>"		"#220E")	; end of proof [12 fonts]
("<divslash>"		"#2215")	; division slash [12 fonts]
("<vysmblkcircle>"	"#2219")	; bullet operator [12 fonts]
("<rightangle>"		"#221F")	; right (90 degree) angle [11 fonts]
("<intclockwise>"	"#2231")	; clockwise integral [10 fonts]
("<varointclockwise>"	"#2232")	; contour integral, clockwise [11 fonts]
("<ointctrclockwise>"	"#2233")	; contour integral, anticlockwise [11 fonts]
("<mathratio>"		"#2236")	; ratio [12 fonts]
("<Colon>"		"#2237")	; two colons [12 fonts]
("<dotminus>"		"#2238")	; minus sign, dot above [11 fonts], shape checked
("<dashcolon>"		"#2239")	; excess (-:) [12 fonts]
("<dotsminusdots>"	"#223A")	; minus with four dots, geometric properties [11 fonts]
("<kernelcontraction>"	"#223B")	; homothetic [11 fonts]
("<invlazys>"		"#223E")	; most positive [inverted lazy s] [10 fonts]
("<sinewave>"		"#223F")	; sine wave [10 fonts]
("<simneqq>"		"#2246")	; similar, not equals [vert only for 9573 entity] [11 fonts]
("<approxident>"	"#224B")	; approximately identical to [11 fonts]
("<backcong>"		"#224C")	; all equal to [11 fonts]
("<eqcolon>"		"#2255")	; equals, colon [12 fonts]
("<arceq>"		"#2258")	; arc, equals; corresponds to [9 fonts]
("<wedgeq>"		"#2259")	; corresponds to (wedge, equals) [9 fonts]
("<veeeq>"		"#225A")	; logical or, equals [9 fonts]
("<stareq>"		"#225B")	; star equals [9 fonts]
("<eqdef>"		"#225D")	; equals by definition [9 fonts]
("<measeq>"		"#225E")	; measured by (m over equals) [9 fonts]
("<questeq>"		"#225F")	; equal with questionmark [9 fonts]
("<Equiv>"		"#2263")	; strict equivalence (4 lines) [11 fonts]
("<nlesssim>"		"#2274")	; not less, similar [12 fonts], shape checked
("<ngtrsim>"		"#2275")	; not greater, similar [12 fonts], shape checked
("<nlessgtr>"		"#2278")	; not less, greater [12 fonts]
("<ngtrless>"		"#2279")	; not greater, less [12 fonts]
("<cupleftarrow>"	"#228C")	; multiset [11 fonts]
("<cupdot>"		"#228D")	; union, with dot [11 fonts]
("<circledequal>"	"#229C")	; equal in circle [11 fonts]
("<assert>"		"#22A6")	; assertion (vertical, short dash) [11 fonts]
("<VDash>"		"#22AB")	; double vert, double dash [11 fonts], shape checked
("<origof>"		"#22B6")	; original of [11 fonts]
("<imageof>"		"#22B7")	; image of [11 fonts]
("<hermitmatrix>"	"#22B9")	; hermitian conjugate matrix [9 fonts]
("<barvee>"		"#22BD")	; bar, vee (large vee) [10 fonts]
("<measuredrightangle>"	"#22BE")	; right angle-measured [with arc] [9 fonts]
("<varlrtriangle>"	"#22BF")	; right triangle [9 fonts]
("<equalparallel>"	"#22D5")	; parallel, equal; equal or parallel [10 fonts]
("<eqless>"		"#22DC")	; equal-or-less [11 fonts]
("<eqgtr>"		"#22DD")	; equal-or-greater [11 fonts]
("<sqsubsetneq>"	"#22E4")	; square subset, not equals [11 fonts], shape checked
("<sqsupsetneq>"	"#22E5")	; square superset, not equals [11 fonts], shape checked

;;; Miscellaneous technical

("<turnednot>"		"#2319")	; turned not sign [10 fonts]
("<inttop>"		"#2320")	; top half integral [8 fonts]
("<intbottom>"		"#2321")	; bottom half integral [8 fonts]
("<obar>"		"#233D")	; circle with vertical bar [4 fonts], shape checked
("<lparenuend>"		"#239B")	; left parenthesis upper hook [11 fonts]
("<lparenextender>"	"#239C")	; left parenthesis extension [11 fonts]
("<lparenlend>"		"#239D")	; left parenthesis lower hook [11 fonts]
("<rparenuend>"		"#239E")	; right parenthesis upper hook [11 fonts]
("<rparenextender>"	"#239F")	; right parenthesis extension [11 fonts]
("<rparenlend>"		"#23A0")	; right parenthesis lower hook [11 fonts]
("<lbrackuend>"		"#23A1")	; left square bracket upper corner [11 fonts]
("<lbrackextender>"	"#23A2")	; left square bracket extension [11 fonts]
("<lbracklend>"		"#23A3")	; left square bracket lower corner [11 fonts]
("<rbrackuend>"		"#23A4")	; right square bracket upper corner [11 fonts]
("<rbrackextender>"	"#23A5")	; right square bracket extension [11 fonts]
("<rbracklend>"		"#23A6")	; right square bracket lower corner [11 fonts]
("<lbraceuend>"		"#23A7")	; left curly bracket upper hook [11 fonts]
("<lbracemid>"		"#23A8")	; left curly bracket middle piece [11 fonts]
("<lbracelend>"		"#23A9")	; left curly bracket lower hook [11 fonts]
("<vbraceextender>"	"#23AA")	; curly bracket extension [11 fonts]
("<rbraceuend>"		"#23AB")	; right curly bracket upper hook [11 fonts]
("<rbracemid>"		"#23AC")	; right curly bracket middle piece [11 fonts]
("<rbracelend>"		"#23AD")	; right curly bracket lower hook [11 fonts]
("<intextender>"	"#23AE")	; integral extension [7 fonts]
("<sumtop>"		"#23B2")	; summation top [8 fonts]
("<sumbottom>"		"#23B3")	; summation bottom [8 fonts]
("<sqrtbottom>"		"#23B7")	; radical symbol bottom [8 fonts]
("<obrbrak>"		"#23E0")	; top tortoise shell bracket (mathematical use) [9 fonts]
("<ubrbrak>"		"#23E1")	; bottom tortoise shell bracket (mathematical use) [9 fonts]

;;; Miscellaneous symbols

("<blanksymbol>"	"#2422")	; blank symbol [8 fonts]
("<mathvisiblespace>"	"#2423")	; open box [9 fonts]
("<blockfull>"		"#2588")	; full block [10 fonts]
("<blockqtrshaded>"	"#2591")	; 25\% shaded block [9 fonts]
("<blockhalfshaded>"	"#2592")	; 50\% shaded block [9 fonts]
("<blockthreeqtrshaded>"	"#2593")	; 75\% shaded block [9 fonts]
("<smblksquare>"	"#25AA")	; /blacksquare - sq bullet, filled [12 fonts]
("<smwhtsquare>"	"#25AB")	; white small square [12 fonts]
("<hrectangleblack>"	"#25AC")	; black rectangle [12 fonts]
("<hrectangle>"		"#25AD")	; horizontal rectangle, open [10 fonts]
("<bigblacktriangleup>"	"#25B2")	; black up-pointing triangle [12 fonts]
("<bigblacktriangledown>"	"#25BC")	; big down triangle, filled [12 fonts]
("<mdlgblkdiamond>"	"#25C6")	; black diamond [7 fonts]
("<smwhtcircle>"	"#25E6")	; white bullet [11 fonts]
("<boxbar>"		"#25EB")	; vertical bar in box [7 fonts], shape checked
("<mdwhtsquare>"	"#25FB")	; white medium square [6 fonts]
("<mdblksquare>"	"#25FC")	; black medium square [6 fonts]
("<varspadesuit>"	"#2664")	; spade, white (card suit) [11 fonts]
("<varclubsuit>"	"#2667")	; club, white (card suit) [11 fonts]
("<mdwhtcircle>"	"#26AA")	; medium white circle [6 fonts]
("<mdblkcircle>"	"#26AB")	; medium black circle [6 fonts]
("<mdsmwhtcircle>"	"#26AC")	; medium small white circle [6 fonts]

;;; Miscellaneous mathematical A

("<lbag>"		"#27C5")	; left s-shaped bag delimiter [6 fonts]
("<rbag>"		"#27C6")	; right s-shaped bag delimiter [6 fonts]
("<diamondcdot>"	"#27D0")	; white diamond with centred dot [6 fonts]
("<bigbot>"		"#27D8")	; large up tack [9 fonts]
("<bigtop>"		"#27D9")	; large down tack [9 fonts]
("<DashVDash>"		"#27DA")	; left and right double turnstile [10 fonts]
("<dashVdash>"		"#27DB")	; left and right tack [10 fonts]
("<multimapinv>"	"#27DC")	; left multimap [11 fonts]
("<vlongdash>"		"#27DD")	; long left tack [10 fonts]
("<lozengeminus>"	"#27E0")	; lozenge divided by horizontal rule [9 fonts]
("<concavediamond>"	"#27E1")	; white concave-sided diamond [9 fonts]
("<concavediamondtickleft>"	"#27E2")	; white concave-sided diamond with leftwards tick [9 fonts]
("<concavediamondtickright>"	"#27E3")	; white concave-sided diamond with rightwards tick [9 fonts]
("<lgroup>"		"#27EE")	; mathematical left flattened parenthesis [10 fonts]
("<rgroup>"		"#27EF")	; mathematical right flattened parenthesis [10 fonts]

;;; Supplemental arrows A

("<rightarrowonoplus>"	"#27F4")	; right arrow with circled plus [10 fonts]
("<Longmapsfrom>"	"#27FD")	; long leftwards double arrow from bar [12 fonts]
("<Longmapsto>"		"#27FE")	; long rightwards double arrow from bar [12 fonts]
("<longrightsquigarrow>"	"#27FF")	; long rightwards squiggle arrow [10 fonts]

;;; Supplemental arrows B

("<Mapsfrom>"		"#2906")	; leftwards double arrow from bar [12 fonts]
("<Mapsto>"		"#2907")	; rightwards double arrow from bar [12 fonts]

;;; Miscellaneous mathematical B

("<mdsmblkcircle>"	"#2981")	; z notation spot [6 fonts]
("<olessthan>"		"#29C0")	; circled less-than [6 fonts]
("<ogreaterthan>"	"#29C1")	; circled greater-than [6 fonts]
("<dualmap>"		"#29DF")	; double-ended multimap [6 fonts]

;;; Supplemental operators

("<bigcupdot>"		"#2A03")	; n-ary union operator with dot [10 fonts]
("<bigtimes>"		"#2A09")	; n-ary times operator [11 fonts]
("<fint>"		"#2A0F")	; integral average with slash [6 fonts]
("<awint>"		"#2A11")	; anticlockwise integration [9 fonts]
("<sqint>"		"#2A16")	; quaternion integral operator [6 fonts]
("<vectimes>"		"#2A2F")	; vector or cross product [10 fonts]
("<dottimes>"		"#2A30")	; multiplication sign with dot above [4 fonts], shape checked
("<btimes>"		"#2A32")	; semidirect product with bottom closed [4 fonts], shape checked
("<Coloneq>"		"#2A74")	; double colon equal [6 fonts]
("<precneq>"		"#2AB1")	; precedes above single-line not equal to [5 fonts], shape checked
("<succneq>"		"#2AB2")	; succeeds above single-line not equal to [5 fonts], shape checked
("<preceqq>"		"#2AB3")	; precedes above equals sign [6 fonts], shape checked
("<succeqq>"		"#2AB4")	; succeeds above equals sign [6 fonts], shape checked
("<dashV>"		"#2AE3")	; double vertical bar left turnstile [4 fonts], shape checked
("<Dashv>"		"#2AE4")	; vertical bar double left turnstile [4 fonts], shape checked
("<DashV>"		"#2AE5")	; double vertical bar double left turnstile [4 fonts], shape checked
("<barV>"		"#2AEA")	; double down tack [6 fonts]
("<Vbar>"		"#2AEB")	; double up tack [6 fonts]
("<leqqslant>"		"#2AF9")	; double-line slanted less-than or equal to [6 fonts]
("<geqqslant>"		"#2AFA")	; double-line slanted greater-than or equal to [6 fonts]

;;; Miscellaneous symbols and arrows

("<dottedsquare>"	"#2B1A")	; dotted square [9 fonts]
("<lgblkcircle>"	"#2B24")	; black large circle [6 fonts]
("<mdblkdiamond>"	"#2B25")	; black medium diamond [6 fonts]
("<mdwhtdiamond>"	"#2B26")	; white medium diamond [6 fonts]
("<mdwhtlozenge>"	"#2B28")	; white medium lozenge [6 fonts]
("<leftthreearrows>"	"#2B31")	; three leftwards arrows [11 fonts]
("<longleftsquigarrow>"	"#2B33")	; long leftwards squiggle arrow [10 fonts]






