;; Conversions between TeXmacs symbols and Unicode: the ones
;; that need a decision
;;
;; Generated by tests/opentype/missing-symbols.py, companion of
;; tmuniversaltounicode-extra.scm. Every line here is commented out and
;; says why: the name may already mean something else, the symbol may be an
;; accent rather than a symbol, or the fonts may not draw it. Nothing reads
;; this file; it is the backlog.
;;
;; The entries worth looking at first are the ones marked "already a
;; TeXmacs symbol": TeXmacs draws those today but has no Unicode for them,
;; so they degrade on export, and the name coming out of unicode-math is
;; the same one TeXmacs uses, which is a good sign that the shape agrees.


;;; Punctuation

;("<enleadertwodots>"	"#2025")	; double baseline dot (en leader) [4 fonts], few fonts draw it
;("<caretinsert>"	"#2038")	; caret (insertion mark) [4 fonts], few fonts draw it
;("<Exclam>"		"#203C")	; double exclamation mark [4 fonts], few fonts draw it
;("<hyphenbullet>"	"#2043")	; rectangle, filled (hyphen bullet) [4 fonts], few fonts draw it
;("<Question>"		"#2047")	; double question mark [4 fonts], few fonts draw it
;("<closure>"		"#2050")	; close up [4 fonts], few fonts draw it

;;; Currency


;;; Letterlike

;("<turnediota>"		"#2129")	; turned iota [4 fonts], few fonts draw it
;("<sansLturned>"	"#2142")	; turned sans-serif capital l [4 fonts], few fonts draw it
;("<sansLmirrored>"	"#2143")	; reversed sans-serif capital l [4 fonts], few fonts draw it
;("<Yup>"		"#2144")	; turned sans-serif capital y [4 fonts], few fonts draw it
;("<PropertyLine>"	"#214A")	; property line [4 fonts], few fonts draw it

;;; Arrows

;("<updownarrowbar>"	"#21A8")	; up down arrow with base (perpendicular) [4 fonts], few fonts draw it
;("<barovernorthwestarrow>"	"#21B8")	; north west arrow to long bar [4 fonts], few fonts draw it
;("<barleftarrowrightarrowbar>"	"#21B9")	; leftwards arrow to bar over rightwards arrow to bar [4 fonts], few fonts draw it
;("<leftsquigarrow>"	"#21DC")	; leftwards squiggle arrow [11 fonts], the name already means U+219C
;("<rightsquigarrow>"	"#21DD")	; rightwards squiggle arrow [11 fonts], the name already means U+219D
;("<nHuparrow>"		"#21DE")	; upwards arrow with double stroke [4 fonts], few fonts draw it
;("<nHdownarrow>"	"#21DF")	; downwards arrow with double stroke [4 fonts], few fonts draw it
;("<updasharrow>"	"#21E1")	; upwards dashed arrow [5 fonts], few fonts draw it
;("<downdasharrow>"	"#21E3")	; downwards dashed arrow [5 fonts], few fonts draw it
;("<barleftarrow>"	"#21E4")	; leftwards arrow to bar [4 fonts], few fonts draw it
;("<rightarrowbar>"	"#21E5")	; rightwards arrow to bar [4 fonts], few fonts draw it
;("<whitearrowupfrombar>"	"#21EA")	; upwards white arrow from bar [4 fonts], few fonts draw it
;("<circleonrightarrow>"	"#21F4")	; right arrow with small circle [4 fonts], few fonts draw it
;("<nvleftarrow>"	"#21F7")	; leftwards arrow with vertical stroke [4 fonts], few fonts draw it
;("<nvrightarrow>"	"#21F8")	; rightwards arrow with vertical stroke [4 fonts], few fonts draw it
;("<nvleftrightarrow>"	"#21F9")	; left right arrow with vertical stroke [4 fonts], few fonts draw it
;("<nVleftarrow>"	"#21FA")	; leftwards arrow with double vertical stroke [4 fonts], few fonts draw it
;("<nVrightarrow>"	"#21FB")	; rightwards arrow with double vertical stroke [4 fonts], few fonts draw it
;("<nVleftrightarrow>"	"#21FC")	; left right arrow with double vertical stroke [4 fonts], few fonts draw it

;;; Mathematical operators

;("<cuberoot>"		"#221B")	; cube root [5 fonts], few fonts draw it
;("<fourthroot>"		"#221C")	; fourth root [5 fonts], few fonts draw it
;("<prurel>"		"#22B0")	; element precedes under relation [4 fonts], few fonts draw it
;("<scurel>"		"#22B1")	; succeeds under relation [4 fonts], few fonts draw it
;("<disin>"		"#22F2")	; element of with long horizontal stroke [4 fonts], few fonts draw it
;("<varisins>"		"#22F3")	; element of with vertical bar at end of horizontal stroke [4 fonts], few fonts draw it
;("<isins>"		"#22F4")	; small element of with vertical bar at end of horizontal stroke [4 fonts], few fonts draw it
;("<isindot>"		"#22F5")	; element of with dot above [4 fonts], few fonts draw it
;("<varisinobar>"	"#22F6")	; element of with overbar [4 fonts], few fonts draw it
;("<isinobar>"		"#22F7")	; small element of with overbar [4 fonts], few fonts draw it
;("<isinvb>"		"#22F8")	; element of with underbar [4 fonts], few fonts draw it
;("<isinE>"		"#22F9")	; element of with two horizontal strokes [4 fonts], few fonts draw it
;("<nisd>"		"#22FA")	; contains with long horizontal stroke [4 fonts], few fonts draw it
;("<varnis>"		"#22FB")	; contains with vertical bar at end of horizontal stroke [4 fonts], few fonts draw it
;("<nis>"		"#22FC")	; small contains with vertical bar at end of horizontal stroke [4 fonts], few fonts draw it
;("<varniobar>"		"#22FD")	; contains with overbar [4 fonts], few fonts draw it
;("<niobar>"		"#22FE")	; small contains with overbar [4 fonts], few fonts draw it
;("<bagmember>"		"#22FF")	; z notation bag membership [4 fonts], few fonts draw it

;;; Miscellaneous technical

;("<house>"		"#2302")	; house [5 fonts], few fonts draw it
;("<sqlozenge>"		"#2311")	; square lozenge [4 fonts], few fonts draw it
;("<profline>"		"#2312")	; profile of a line [4 fonts], few fonts draw it
;("<profsurf>"		"#2313")	; profile of a surface [4 fonts], few fonts draw it
;("<viewdata>"		"#2317")	; viewdata square [4 fonts], few fonts draw it
;("<varhexagonlrbonds>"	"#232C")	; six carbon ring, corner down, double bonds lower right etc [4 fonts], few fonts draw it
;("<conictaper>"		"#2332")	; conical taper [4 fonts], few fonts draw it
;("<topbot>"		"#2336")	; top and bottom [4 fonts], few fonts draw it
;("<APLnotslash>"	"#233F")	; solidus, bar through (apl functional symbol slash bar) [4 fonts], few fonts draw it
;("<APLnotbackslash>"	"#2340")	; apl functional symbol backslash bar [4 fonts], few fonts draw it
;("<APLboxupcaret>"	"#2353")	; boxed up caret [4 fonts], few fonts draw it
;("<APLboxquestion>"	"#2370")	; boxed question mark [4 fonts], few fonts draw it
;("<rangledownzigzagarrow>"	"#237C")	; right angle with downwards zigzag arrow [4 fonts], few fonts draw it
;("<hexagon>"		"#2394")	; horizontal benzene ring [hexagon flat open] [4 fonts], few fonts draw it
;("<harrowextender>"	"#23AF")	; horizontal line extension (used to extend arrows) [4 fonts], few fonts draw it
;("<lmoustache>"		"#23B0")	; upper left or lower right curly bracket section [3 fonts], few fonts draw it
;("<rmoustache>"		"#23B1")	; upper right or lower left curly bracket section [3 fonts], few fonts draw it
;("<overbracket>"	"#23B4")	; top square bracket [11 fonts], an accent or a radical, not a plain symbol
;("<underbracket>"	"#23B5")	; bottom square bracket [11 fonts], an accent or a radical, not a plain symbol
;("<bbrktbrk>"		"#23B6")	; bottom square bracket over top square bracket [4 fonts], few fonts draw it
;("<lvboxline>"		"#23B8")	; left vertical box line [3 fonts], few fonts draw it
;("<rvboxline>"		"#23B9")	; right vertical box line [3 fonts], few fonts draw it
;("<varcarriagereturn>"	"#23CE")	; return symbol [4 fonts], few fonts draw it
;("<overparen>"		"#23DC")	; top parenthesis (mathematical use) [12 fonts], an accent or a radical, not a plain symbol
;("<underparen>"		"#23DD")	; bottom parenthesis (mathematical use) [12 fonts], an accent or a radical, not a plain symbol
;("<overbrace>"		"#23DE")	; top curly bracket (mathematical use) [12 fonts], an accent or a radical, not a plain symbol
;("<underbrace>"		"#23DF")	; bottom curly bracket (mathematical use) [12 fonts], an accent or a radical, not a plain symbol
;("<trapezium>"		"#23E2")	; white trapezium [4 fonts], few fonts draw it
;("<benzenr>"		"#23E3")	; benzene ring with circle [4 fonts], few fonts draw it
;("<strns>"		"#23E4")	; straightness [4 fonts], few fonts draw it
;("<fltns>"		"#23E5")	; flatness [4 fonts], few fonts draw it
;("<accurrent>"		"#23E6")	; ac current [4 fonts], few fonts draw it
;("<elinters>"		"#23E7")	; electrical intersection [4 fonts], few fonts draw it

;;; Miscellaneous symbols

;("<bdtriplevdash>"	"#2506")	; doubly broken vert [4 fonts], few fonts draw it
;("<blockuphalf>"	"#2580")	; upper half block [5 fonts], few fonts draw it
;("<blocklowhalf>"	"#2584")	; lower half block [5 fonts], few fonts draw it
;("<blocklefthalf>"	"#258C")	; left half block [5 fonts], few fonts draw it
;("<blockrighthalf>"	"#2590")	; right half block [5 fonts], few fonts draw it
;("<squoval>"		"#25A2")	; white square with rounded corners [5 fonts], few fonts draw it
;("<blackinwhitesquare>"	"#25A3")	; white square containing black small square [5 fonts], few fonts draw it
;("<squarehfill>"	"#25A4")	; square, horizontal rule filled [4 fonts], few fonts draw it
;("<squarevfill>"	"#25A5")	; square, vertical rule filled [4 fonts], few fonts draw it
;("<squarehvfill>"	"#25A6")	; square with orthogonal crosshatch fill [4 fonts], few fonts draw it
;("<squarenwsefill>"	"#25A7")	; square, nw-to-se rule filled [4 fonts], few fonts draw it
;("<squareneswfill>"	"#25A8")	; square, ne-to-sw rule filled [4 fonts], few fonts draw it
;("<squarecrossfill>"	"#25A9")	; square with diagonal crosshatch fill [4 fonts], few fonts draw it
;("<vrectangleblack>"	"#25AE")	; black vertical rectangle [5 fonts], few fonts draw it
;("<parallelogramblack>"	"#25B0")	; black parallelogram [4 fonts], few fonts draw it
;("<parallelogram>"	"#25B1")	; parallelogram, open [4 fonts], few fonts draw it
;("<blacktriangleright>"	"#25B6")	; (large) right triangle, filled [12 fonts], the name already means U+25B8
;("<triangleright>"	"#25B7")	; (large) right triangle, open; z notation range restriction [11 fonts], the name already means U+25B9
;("<blackpointerright>"	"#25BA")	; black right-pointing pointer [5 fonts], few fonts draw it
;("<whitepointerright>"	"#25BB")	; white right-pointing pointer [4 fonts], few fonts draw it
;("<blacktriangleleft>"	"#25C0")	; (large) left triangle, filled [12 fonts], the name already means U+25C2
;("<triangleleft>"	"#25C1")	; (large) left triangle, open; z notation domain restriction [11 fonts], the name already means U+25C3
;("<blackpointerleft>"	"#25C4")	; black left-pointing pointer [5 fonts], few fonts draw it
;("<whitepointerleft>"	"#25C5")	; white left-pointing pointer [4 fonts], few fonts draw it
;("<blackinwhitediamond>"	"#25C8")	; white diamond containing black small diamond [4 fonts], few fonts draw it
;("<fisheye>"		"#25C9")	; fisheye [5 fonts], few fonts draw it
;("<dottedcircle>"	"#25CC")	; dotted circle [4 fonts], few fonts draw it
;("<circlevertfill>"	"#25CD")	; circle with vertical fill [4 fonts], few fonts draw it
;("<bullseye>"		"#25CE")	; bullseye [5 fonts], few fonts draw it
;("<circlebottomhalfblack>"	"#25D2")	; circle, filled bottom half [5 fonts], few fonts draw it
;("<circletophalfblack>"	"#25D3")	; circle, filled top half [5 fonts], few fonts draw it
;("<circleurquadblack>"	"#25D4")	; circle with upper right quadrant black [4 fonts], few fonts draw it
;("<blackcircleulquadwhite>"	"#25D5")	; circle with all but upper left quadrant black [5 fonts], few fonts draw it
;("<inversebullet>"	"#25D8")	; inverse bullet [4 fonts], few fonts draw it
;("<inversewhitecircle>"	"#25D9")	; inverse white circle [5 fonts], few fonts draw it
;("<invwhiteupperhalfcircle>"	"#25DA")	; upper half inverse white circle [5 fonts], few fonts draw it
;("<invwhitelowerhalfcircle>"	"#25DB")	; lower half inverse white circle [5 fonts], few fonts draw it
;("<ularc>"		"#25DC")	; upper left quadrant circular arc [5 fonts], few fonts draw it
;("<urarc>"		"#25DD")	; upper right quadrant circular arc [5 fonts], few fonts draw it
;("<lrarc>"		"#25DE")	; lower right quadrant circular arc [5 fonts], few fonts draw it
;("<llarc>"		"#25DF")	; lower left quadrant circular arc [5 fonts], few fonts draw it
;("<topsemicircle>"	"#25E0")	; upper half circle [5 fonts], few fonts draw it
;("<botsemicircle>"	"#25E1")	; lower half circle [5 fonts], few fonts draw it
;("<lrblacktriangle>"	"#25E2")	; lower right triangle, filled [5 fonts], few fonts draw it
;("<llblacktriangle>"	"#25E3")	; lower left triangle, filled [5 fonts], few fonts draw it
;("<ulblacktriangle>"	"#25E4")	; upper left triangle, filled [5 fonts], few fonts draw it
;("<urblacktriangle>"	"#25E5")	; upper right triangle, filled [5 fonts], few fonts draw it
;("<squareleftblack>"	"#25E7")	; square, filled left half [5 fonts], few fonts draw it
;("<squarerightblack>"	"#25E8")	; square, filled right half [5 fonts], few fonts draw it
;("<squareulblack>"	"#25E9")	; square, filled top left corner [5 fonts], few fonts draw it
;("<squarelrblack>"	"#25EA")	; square, filled bottom right corner [5 fonts], few fonts draw it
;("<trianglecdot>"	"#25EC")	; triangle with centered dot [4 fonts], few fonts draw it
;("<triangleleftblack>"	"#25ED")	; up-pointing triangle with left half black [4 fonts], few fonts draw it
;("<trianglerightblack>"	"#25EE")	; up-pointing triangle with right half black [4 fonts], few fonts draw it
;("<squareulquad>"	"#25F0")	; white square with upper left quadrant [5 fonts], few fonts draw it
;("<squarellquad>"	"#25F1")	; white square with lower left quadrant [5 fonts], few fonts draw it
;("<squarelrquad>"	"#25F2")	; white square with lower right quadrant [5 fonts], few fonts draw it
;("<squareurquad>"	"#25F3")	; white square with upper right quadrant [5 fonts], few fonts draw it
;("<circleulquad>"	"#25F4")	; white circle with upper left quadrant [5 fonts], few fonts draw it
;("<circlellquad>"	"#25F5")	; white circle with lower left quadrant [5 fonts], few fonts draw it
;("<circlelrquad>"	"#25F6")	; white circle with lower right quadrant [5 fonts], few fonts draw it
;("<circleurquad>"	"#25F7")	; white circle with upper right quadrant [5 fonts], few fonts draw it
;("<ultriangle>"		"#25F8")	; upper left triangle [4 fonts], few fonts draw it
;("<urtriangle>"		"#25F9")	; upper right triangle [4 fonts], few fonts draw it
;("<lltriangle>"		"#25FA")	; lower left triangle [4 fonts], few fonts draw it
;("<mdsmblksquare>"	"#25FE")	; black medium small square [4 fonts], few fonts draw it
;("<lrtriangle>"		"#25FF")	; lower right triangle [4 fonts], few fonts draw it
;("<bigwhitestar>"	"#2606")	; star, open [4 fonts], few fonts draw it
;("<danger>"		"#2621")	; dangerous bend (caution sign) [4 fonts], few fonts draw it
;("<heartsuit>"		"#2661")	; heart suit symbol [11 fonts], the name already means U+2665
;("<diamondsuit>"	"#2662")	; diamond suit symbol [11 fonts], the name already means U+2666
;("<acidfree>"		"#267E")	; permanent paper sign [4 fonts], few fonts draw it
;("<circledrightdot>"	"#2686")	; white circle with dot right [4 fonts], few fonts draw it
;("<circledtwodots>"	"#2687")	; white circle with two dots [4 fonts], few fonts draw it
;("<blackcircledrightdot>"	"#2688")	; black circle with white dot right [4 fonts], few fonts draw it
;("<blackcircledtwodots>"	"#2689")	; black circle with two white dots [4 fonts], few fonts draw it
;("<Hermaphrodite>"	"#26A5")	; male and female sign [4 fonts], few fonts draw it
;("<neuter>"		"#26B2")	; neuter [4 fonts], few fonts draw it
;("<circledstar>"	"#272A")	; circled white star [4 fonts], few fonts draw it
;("<varstar>"		"#2736")	; six pointed black star [4 fonts], few fonts draw it
;("<dingasterisk>"	"#273D")	; heavy teardrop-spoked asterisk [4 fonts], few fonts draw it
;("<lbrbrak>"		"#2772")	; light left tortoise shell bracket ornament [4 fonts], few fonts draw it
;("<rbrbrak>"		"#2773")	; light right tortoise shell bracket ornament [4 fonts], few fonts draw it
;("<draftingarrow>"	"#279B")	; right arrow with bold head (drafting) [4 fonts], few fonts draw it

;;; Miscellaneous mathematical A

;("<threedangle>"	"#27C0")	; three dimensional angle [4 fonts], few fonts draw it
;("<whiteinwhitetriangle>"	"#27C1")	; white triangle containing small white triangle [4 fonts], few fonts draw it
;("<perp>"		"#27C2")	; perpendicular [12 fonts], the name already means U+22A5
;("<subsetcirc>"		"#27C3")	; open subset [4 fonts], few fonts draw it
;("<supsetcirc>"		"#27C4")	; open superset [4 fonts], few fonts draw it
;("<veedot>"		"#27C7")	; or with dot inside [4 fonts], few fonts draw it
;("<bsolhsub>"		"#27C8")	; reverse solidus preceding subset [4 fonts], few fonts draw it
;("<suphsol>"		"#27C9")	; superset preceding solidus [4 fonts], few fonts draw it
;("<longdivision>"	"#27CC")	; long division [4 fonts], few fonts draw it
;("<wedgedot>"		"#27D1")	; and with dot [4 fonts], few fonts draw it
;("<upin>"		"#27D2")	; element of opening upwards [4 fonts], few fonts draw it
;("<pullback>"		"#27D3")	; lower right corner with dot [4 fonts], few fonts draw it
;("<pushout>"		"#27D4")	; upper left corner with dot [4 fonts], few fonts draw it
;("<leftouterjoin>"	"#27D5")	; left outer join [4 fonts], few fonts draw it
;("<rightouterjoin>"	"#27D6")	; right outer join [4 fonts], few fonts draw it
;("<fullouterjoin>"	"#27D7")	; full outer join [4 fonts], few fonts draw it
;("<longdashv>"		"#27DE")	; long right tack [10 fonts], already a TeXmacs symbol, check that the shape agrees
;("<cirbot>"		"#27DF")	; up tack with circle above [4 fonts], few fonts draw it
;("<whitesquaretickleft>"	"#27E4")	; white square with leftwards tick [4 fonts], few fonts draw it
;("<whitesquaretickright>"	"#27E5")	; white square with rightwards tick [4 fonts], few fonts draw it
;("<Lbrbrak>"		"#27EC")	; mathematical left white tortoise shell bracket [4 fonts], few fonts draw it
;("<Rbrbrak>"		"#27ED")	; mathematical right white tortoise shell bracket [4 fonts], few fonts draw it

;;; Supplemental arrows A

;("<UUparrow>"		"#27F0")	; upwards quadruple arrow [4 fonts], few fonts draw it
;("<DDownarrow>"		"#27F1")	; downwards quadruple arrow [4 fonts], few fonts draw it
;("<acwgapcirclearrow>"	"#27F2")	; anticlockwise gapped circle arrow [4 fonts], few fonts draw it
;("<cwgapcirclearrow>"	"#27F3")	; clockwise gapped circle arrow [4 fonts], few fonts draw it

;;; Supplemental arrows B

;("<nvtwoheadrightarrow>"	"#2900")	; rightwards two-headed arrow with vertical stroke [4 fonts], few fonts draw it
;("<nVtwoheadrightarrow>"	"#2901")	; rightwards two-headed arrow with double vertical stroke [4 fonts], few fonts draw it
;("<nvLeftarrow>"	"#2902")	; leftwards double arrow with vertical stroke [4 fonts], few fonts draw it
;("<nvRightarrow>"	"#2903")	; rightwards double arrow with vertical stroke [4 fonts], few fonts draw it
;("<nvLeftrightarrow>"	"#2904")	; left right double arrow with vertical stroke [4 fonts], few fonts draw it
;("<twoheadmapsto>"	"#2905")	; rightwards two-headed arrow from bar [4 fonts], few fonts draw it
;("<downarrowbarred>"	"#2908")	; downwards arrow with horizontal stroke [4 fonts], few fonts draw it
;("<uparrowbarred>"	"#2909")	; upwards arrow with horizontal stroke [4 fonts], few fonts draw it
;("<Uuparrow>"		"#290A")	; upwards triple arrow [4 fonts], few fonts draw it
;("<Ddownarrow>"		"#290B")	; downwards triple arrow [4 fonts], few fonts draw it
;("<leftbkarrow>"	"#290C")	; leftwards double dash arrow [4 fonts], few fonts draw it
;("<rightbkarrow>"	"#290D")	; rightwards double dash arrow [4 fonts], few fonts draw it
;("<leftdbkarrow>"	"#290E")	; leftwards triple dash arrow [4 fonts], few fonts draw it
;("<dbkarrow>"		"#290F")	; rightwards triple dash arrow [4 fonts], few fonts draw it
;("<drbkarrow>"		"#2910")	; rightwards two-headed triple dash arrow [4 fonts], few fonts draw it
;("<rightdotarrow>"	"#2911")	; rightwards arrow with dotted stem [4 fonts], few fonts draw it
;("<baruparrow>"		"#2912")	; upwards arrow to bar [4 fonts], few fonts draw it
;("<downarrowbar>"	"#2913")	; downwards arrow to bar [4 fonts], few fonts draw it
;("<nvrightarrowtail>"	"#2914")	; rightwards arrow with tail with vertical stroke [4 fonts], few fonts draw it
;("<nVrightarrowtail>"	"#2915")	; rightwards arrow with tail with double vertical stroke [4 fonts], few fonts draw it
;("<twoheadrightarrowtail>"	"#2916")	; rightwards two-headed arrow with tail [4 fonts], few fonts draw it
;("<nvtwoheadrightarrowtail>"	"#2917")	; rightwards two-headed arrow with tail with vertical stroke [4 fonts], few fonts draw it
;("<nVtwoheadrightarrowtail>"	"#2918")	; rightwards two-headed arrow with tail with double vertical stroke [4 fonts], few fonts draw it
;("<lefttail>"		"#2919")	; leftwards arrow-tail [4 fonts], few fonts draw it
;("<righttail>"		"#291A")	; rightwards arrow-tail [4 fonts], few fonts draw it
;("<leftdbltail>"	"#291B")	; leftwards double arrow-tail [4 fonts], few fonts draw it
;("<rightdbltail>"	"#291C")	; rightwards double arrow-tail [4 fonts], few fonts draw it
;("<diamondleftarrow>"	"#291D")	; leftwards arrow to black diamond [4 fonts], few fonts draw it
;("<rightarrowdiamond>"	"#291E")	; rightwards arrow to black diamond [4 fonts], few fonts draw it
;("<diamondleftarrowbar>"	"#291F")	; leftwards arrow from bar to black diamond [4 fonts], few fonts draw it
;("<barrightarrowdiamond>"	"#2920")	; rightwards arrow from bar to black diamond [4 fonts], few fonts draw it
;("<nwsearrow>"		"#2921")	; north west and south east arrow [4 fonts], few fonts draw it
;("<neswarrow>"		"#2922")	; north east and south west arrow [4 fonts], few fonts draw it
;("<hknwarrow>"		"#2923")	; north west arrow with hook [4 fonts], few fonts draw it
;("<hknearrow>"		"#2924")	; north east arrow with hook [4 fonts], few fonts draw it
;("<hksearrow>"		"#2925")	; south east arrow with hook [4 fonts], few fonts draw it
;("<hkswarrow>"		"#2926")	; south west arrow with hook [4 fonts], few fonts draw it
;("<tona>"		"#2927")	; north west arrow and north east arrow [4 fonts], few fonts draw it
;("<toea>"		"#2928")	; north east arrow and south east arrow [4 fonts], few fonts draw it
;("<tosa>"		"#2929")	; south east arrow and south west arrow [4 fonts], few fonts draw it
;("<towa>"		"#292A")	; south west arrow and north west arrow [4 fonts], few fonts draw it
;("<rdiagovfdiag>"	"#292B")	; rising diagonal crossing falling diagonal [4 fonts], few fonts draw it
;("<fdiagovrdiag>"	"#292C")	; falling diagonal crossing rising diagonal [4 fonts], few fonts draw it
;("<seovnearrow>"	"#292D")	; south east arrow crossing north east arrow [4 fonts], few fonts draw it
;("<neovsearrow>"	"#292E")	; north east arrow crossing south east arrow [4 fonts], few fonts draw it
;("<fdiagovnearrow>"	"#292F")	; falling diagonal crossing north east arrow [4 fonts], few fonts draw it
;("<rdiagovsearrow>"	"#2930")	; rising diagonal crossing south east arrow [4 fonts], few fonts draw it
;("<neovnwarrow>"	"#2931")	; north east arrow crossing north west arrow [4 fonts], few fonts draw it
;("<nwovnearrow>"	"#2932")	; north west arrow crossing north east arrow [4 fonts], few fonts draw it
;("<rightcurvedarrow>"	"#2933")	; wave arrow pointing directly right [4 fonts], few fonts draw it
;("<uprightcurvearrow>"	"#2934")	; arrow pointing rightwards then curving upwards [4 fonts], few fonts draw it
;("<downrightcurvedarrow>"	"#2935")	; arrow pointing rightwards then curving downwards [4 fonts], few fonts draw it
;("<leftdowncurvedarrow>"	"#2936")	; arrow pointing downwards then curving leftwards [4 fonts], few fonts draw it
;("<rightdowncurvedarrow>"	"#2937")	; arrow pointing downwards then curving rightwards [4 fonts], few fonts draw it
;("<cwrightarcarrow>"	"#2938")	; right-side arc clockwise arrow [4 fonts], few fonts draw it
;("<acwleftarcarrow>"	"#2939")	; left-side arc anticlockwise arrow [4 fonts], few fonts draw it
;("<acwoverarcarrow>"	"#293A")	; top arc anticlockwise arrow [4 fonts], few fonts draw it
;("<acwunderarcarrow>"	"#293B")	; bottom arc anticlockwise arrow [4 fonts], few fonts draw it
;("<curvearrowrightminus>"	"#293C")	; top arc clockwise arrow with minus [4 fonts], few fonts draw it
;("<curvearrowleftplus>"	"#293D")	; top arc anticlockwise arrow with plus [4 fonts], few fonts draw it
;("<cwundercurvearrow>"	"#293E")	; lower right semicircular clockwise arrow [4 fonts], few fonts draw it
;("<ccwundercurvearrow>"	"#293F")	; lower left semicircular anticlockwise arrow [4 fonts], few fonts draw it
;("<rightarrowshortleftarrow>"	"#2942")	; rightwards arrow above short leftwards arrow [4 fonts], few fonts draw it
;("<leftarrowshortrightarrow>"	"#2943")	; leftwards arrow above short rightwards arrow [4 fonts], few fonts draw it
;("<shortrightarrowleftarrow>"	"#2944")	; short rightwards arrow above leftwards arrow [4 fonts], few fonts draw it
;("<rightarrowplus>"	"#2945")	; rightwards arrow with plus below [4 fonts], few fonts draw it
;("<leftarrowplus>"	"#2946")	; leftwards arrow with plus below [4 fonts], few fonts draw it
;("<rightarrowx>"	"#2947")	; rightwards arrow through x [4 fonts], few fonts draw it
;("<leftrightarrowcircle>"	"#2948")	; left right arrow through small circle [4 fonts], few fonts draw it
;("<twoheaduparrowcircle>"	"#2949")	; upwards two-headed arrow from small circle [4 fonts], few fonts draw it
;("<leftrightharpoonupdown>"	"#294A")	; left barb up right barb down harpoon [4 fonts], few fonts draw it
;("<leftrightharpoondownup>"	"#294B")	; left barb down right barb up harpoon [4 fonts], few fonts draw it
;("<updownharpoonrightleft>"	"#294C")	; up barb right down barb left harpoon [4 fonts], few fonts draw it
;("<updownharpoonleftright>"	"#294D")	; up barb left down barb right harpoon [4 fonts], few fonts draw it
;("<leftrightharpoonupup>"	"#294E")	; left barb up right barb up harpoon [4 fonts], few fonts draw it
;("<updownharpoonrightright>"	"#294F")	; up barb right down barb right harpoon [4 fonts], few fonts draw it
;("<leftrightharpoondowndown>"	"#2950")	; left barb down right barb down harpoon [4 fonts], few fonts draw it
;("<updownharpoonleftleft>"	"#2951")	; up barb left down barb left harpoon [4 fonts], few fonts draw it
;("<barleftharpoonup>"	"#2952")	; leftwards harpoon with barb up to bar [4 fonts], few fonts draw it
;("<rightharpoonupbar>"	"#2953")	; rightwards harpoon with barb up to bar [4 fonts], few fonts draw it
;("<barupharpoonright>"	"#2954")	; upwards harpoon with barb right to bar [4 fonts], few fonts draw it
;("<downharpoonrightbar>"	"#2955")	; downwards harpoon with barb right to bar [4 fonts], few fonts draw it
;("<barleftharpoondown>"	"#2956")	; leftwards harpoon with barb down to bar [4 fonts], few fonts draw it
;("<rightharpoondownbar>"	"#2957")	; rightwards harpoon with barb down to bar [4 fonts], few fonts draw it
;("<barupharpoonleft>"	"#2958")	; upwards harpoon with barb left to bar [4 fonts], few fonts draw it
;("<downharpoonleftbar>"	"#2959")	; downwards harpoon with barb left to bar [4 fonts], few fonts draw it
;("<leftharpoonupbar>"	"#295A")	; leftwards harpoon with barb up from bar [4 fonts], few fonts draw it
;("<barrightharpoonup>"	"#295B")	; rightwards harpoon with barb up from bar [4 fonts], few fonts draw it
;("<upharpoonrightbar>"	"#295C")	; upwards harpoon with barb right from bar [4 fonts], few fonts draw it
;("<bardownharpoonright>"	"#295D")	; downwards harpoon with barb right from bar [4 fonts], few fonts draw it
;("<leftharpoondownbar>"	"#295E")	; leftwards harpoon with barb down from bar [4 fonts], few fonts draw it
;("<barrightharpoondown>"	"#295F")	; rightwards harpoon with barb down from bar [4 fonts], few fonts draw it
;("<upharpoonleftbar>"	"#2960")	; upwards harpoon with barb left from bar [4 fonts], few fonts draw it
;("<bardownharpoonleft>"	"#2961")	; downwards harpoon with barb left from bar [4 fonts], few fonts draw it
;("<leftharpoonsupdown>"	"#2962")	; leftwards harpoon with barb up above leftwards harpoon with barb down [4 fonts], few fonts draw it
;("<upharpoonsleftright>"	"#2963")	; upwards harpoon with barb left beside upwards harpoon with barb right [4 fonts], few fonts draw it
;("<rightharpoonsupdown>"	"#2964")	; rightwards harpoon with barb up above rightwards harpoon with barb down [4 fonts], few fonts draw it
;("<downharpoonsleftright>"	"#2965")	; downwards harpoon with barb left beside downwards harpoon with barb right [4 fonts], few fonts draw it
;("<leftrightharpoonsup>"	"#2966")	; leftwards harpoon with barb up above rightwards harpoon with barb up [4 fonts], few fonts draw it
;("<leftrightharpoonsdown>"	"#2967")	; leftwards harpoon with barb down above rightwards harpoon with barb down [4 fonts], few fonts draw it
;("<rightleftharpoonsup>"	"#2968")	; rightwards harpoon with barb up above leftwards harpoon with barb up [4 fonts], few fonts draw it
;("<rightleftharpoonsdown>"	"#2969")	; rightwards harpoon with barb down above leftwards harpoon with barb down [4 fonts], few fonts draw it
;("<leftharpoonupdash>"	"#296A")	; leftwards harpoon with barb up above long dash [4 fonts], few fonts draw it
;("<dashleftharpoondown>"	"#296B")	; leftwards harpoon with barb down below long dash [4 fonts], few fonts draw it
;("<rightharpoonupdash>"	"#296C")	; rightwards harpoon with barb up above long dash [4 fonts], few fonts draw it
;("<dashrightharpoondown>"	"#296D")	; rightwards harpoon with barb down below long dash [4 fonts], few fonts draw it
;("<updownharpoonsleftright>"	"#296E")	; upwards harpoon with barb left beside downwards harpoon with barb right [5 fonts], few fonts draw it
;("<downupharpoonsleftright>"	"#296F")	; downwards harpoon with barb left beside upwards harpoon with barb right [5 fonts], few fonts draw it
;("<rightimply>"		"#2970")	; right double arrow with rounded head [4 fonts], few fonts draw it
;("<equalrightarrow>"	"#2971")	; equals sign above rightwards arrow [4 fonts], few fonts draw it
;("<similarrightarrow>"	"#2972")	; tilde operator above rightwards arrow [4 fonts], few fonts draw it
;("<leftarrowsimilar>"	"#2973")	; leftwards arrow above tilde operator [4 fonts], few fonts draw it
;("<rightarrowsimilar>"	"#2974")	; rightwards arrow above tilde operator [4 fonts], few fonts draw it
;("<rightarrowapprox>"	"#2975")	; rightwards arrow above almost equal to [4 fonts], few fonts draw it
;("<ltlarr>"		"#2976")	; less-than above leftwards arrow [4 fonts], few fonts draw it
;("<leftarrowless>"	"#2977")	; leftwards arrow through less-than [4 fonts], few fonts draw it
;("<gtrarr>"		"#2978")	; greater-than above rightwards arrow [4 fonts], few fonts draw it
;("<subrarr>"		"#2979")	; subset above rightwards arrow [4 fonts], few fonts draw it
;("<leftarrowsubset>"	"#297A")	; leftwards arrow through subset [4 fonts], few fonts draw it
;("<suplarr>"		"#297B")	; superset above leftwards arrow [4 fonts], few fonts draw it
;("<leftfishtail>"	"#297C")	; left fish tail [4 fonts], few fonts draw it
;("<rightfishtail>"	"#297D")	; right fish tail [4 fonts], few fonts draw it
;("<upfishtail>"		"#297E")	; up fish tail [4 fonts], few fonts draw it
;("<downfishtail>"	"#297F")	; down fish tail [4 fonts], few fonts draw it

;;; Miscellaneous mathematical B

;("<Vvert>"		"#2980")	; triple vertical bar delimiter [5 fonts], few fonts draw it
;("<typecolon>"		"#2982")	; z notation type colon [4 fonts], few fonts draw it
;("<lBrace>"		"#2983")	; left white curly bracket [4 fonts], few fonts draw it
;("<rBrace>"		"#2984")	; right white curly bracket [4 fonts], few fonts draw it
;("<lParen>"		"#2985")	; left white parenthesis [4 fonts], few fonts draw it
;("<rParen>"		"#2986")	; right white parenthesis [4 fonts], few fonts draw it
;("<llangle>"		"#2989")	; z notation left binding bracket [4 fonts], the name already means U+27EA
;("<rrangle>"		"#298A")	; z notation right binding bracket [4 fonts], the name already means U+27EB
;("<lbrackubar>"		"#298B")	; left square bracket with underbar [4 fonts], few fonts draw it
;("<rbrackubar>"		"#298C")	; right square bracket with underbar [4 fonts], few fonts draw it
;("<lbrackultick>"	"#298D")	; left square bracket with tick in top corner [4 fonts], few fonts draw it
;("<rbracklrtick>"	"#298E")	; right square bracket with tick in bottom corner [4 fonts], few fonts draw it
;("<lbracklltick>"	"#298F")	; left square bracket with tick in bottom corner [4 fonts], few fonts draw it
;("<rbrackurtick>"	"#2990")	; right square bracket with tick in top corner [4 fonts], few fonts draw it
;("<langledot>"		"#2991")	; left angle bracket with dot [4 fonts], few fonts draw it
;("<rangledot>"		"#2992")	; right angle bracket with dot [4 fonts], few fonts draw it
;("<lparenless>"		"#2993")	; left arc less-than bracket [4 fonts], few fonts draw it
;("<rparengtr>"		"#2994")	; right arc greater-than bracket [4 fonts], few fonts draw it
;("<Lparengtr>"		"#2995")	; double left arc greater-than bracket [4 fonts], few fonts draw it
;("<Rparenless>"		"#2996")	; double right arc less-than bracket [4 fonts], few fonts draw it
;("<lblkbrbrak>"		"#2997")	; left black tortoise shell bracket [4 fonts], few fonts draw it
;("<rblkbrbrak>"		"#2998")	; right black tortoise shell bracket [4 fonts], few fonts draw it
;("<fourvdots>"		"#2999")	; dotted fence [4 fonts], few fonts draw it
;("<vzigzag>"		"#299A")	; vertical zigzag line [4 fonts], few fonts draw it
;("<measuredangleleft>"	"#299B")	; measured angle opening left [4 fonts], few fonts draw it
;("<rightanglesqr>"	"#299C")	; right angle variant with square [4 fonts], few fonts draw it
;("<rightanglemdot>"	"#299D")	; measured right angle with dot [4 fonts], few fonts draw it
;("<angles>"		"#299E")	; angle with s inside [4 fonts], few fonts draw it
;("<angdnr>"		"#299F")	; acute angle [5 fonts], few fonts draw it
;("<gtlpar>"		"#29A0")	; spherical angle opening left [5 fonts], few fonts draw it
;("<sphericalangleup>"	"#29A1")	; spherical angle opening up [5 fonts], few fonts draw it
;("<turnangle>"		"#29A2")	; turned angle [5 fonts], few fonts draw it
;("<revangle>"		"#29A3")	; reversed angle [5 fonts], few fonts draw it
;("<angleubar>"		"#29A4")	; angle with underbar [4 fonts], few fonts draw it
;("<revangleubar>"	"#29A5")	; reversed angle with underbar [4 fonts], few fonts draw it
;("<wideangledown>"	"#29A6")	; oblique angle opening up [5 fonts], few fonts draw it
;("<wideangleup>"	"#29A7")	; oblique angle opening down [5 fonts], few fonts draw it
;("<measanglerutone>"	"#29A8")	; measured angle with open arm ending in arrow pointing up and right [4 fonts], few fonts draw it
;("<measanglelutonw>"	"#29A9")	; measured angle with open arm ending in arrow pointing up and left [4 fonts], few fonts draw it
;("<measanglerdtose>"	"#29AA")	; measured angle with open arm ending in arrow pointing down and right [4 fonts], few fonts draw it
;("<measangleldtosw>"	"#29AB")	; measured angle with open arm ending in arrow pointing down and left [4 fonts], few fonts draw it
;("<measangleurtone>"	"#29AC")	; measured angle with open arm ending in arrow pointing right and up [4 fonts], few fonts draw it
;("<measangleultonw>"	"#29AD")	; measured angle with open arm ending in arrow pointing left and up [4 fonts], few fonts draw it
;("<measangledrtose>"	"#29AE")	; measured angle with open arm ending in arrow pointing right and down [4 fonts], few fonts draw it
;("<measangledltosw>"	"#29AF")	; measured angle with open arm ending in arrow pointing left and down [4 fonts], few fonts draw it
;("<revemptyset>"	"#29B0")	; reversed empty set [5 fonts], few fonts draw it
;("<emptysetobar>"	"#29B1")	; empty set with overbar [4 fonts], few fonts draw it
;("<emptysetocirc>"	"#29B2")	; empty set with small circle above [4 fonts], few fonts draw it
;("<emptysetoarr>"	"#29B3")	; empty set with right arrow above [4 fonts], few fonts draw it
;("<emptysetoarrl>"	"#29B4")	; empty set with left arrow above [4 fonts], few fonts draw it
;("<circledparallel>"	"#29B7")	; circled parallel [4 fonts], few fonts draw it
;("<operp>"		"#29B9")	; circled perpendicular [4 fonts], few fonts draw it
;("<obot>"		"#29BA")	; circle divided by horizontal bar and top half divided by vertical bar [4 fonts], few fonts draw it
;("<olcross>"		"#29BB")	; circle with superimposed x [4 fonts], few fonts draw it
;("<odotslashdot>"	"#29BC")	; circled anticlockwise-rotated division sign [4 fonts], few fonts draw it
;("<uparrowoncircle>"	"#29BD")	; up arrow through circle [4 fonts], few fonts draw it
;("<circledwhitebullet>"	"#29BE")	; circled white bullet [4 fonts], few fonts draw it
;("<circledbullet>"	"#29BF")	; circled bullet [4 fonts], few fonts draw it
;("<cirscir>"		"#29C2")	; circle with small circle to the right [4 fonts], few fonts draw it
;("<cirE>"		"#29C3")	; circle with two horizontal strokes to the right [4 fonts], few fonts draw it
;("<boxonbox>"		"#29C9")	; two joined squares [4 fonts], few fonts draw it
;("<triangleodot>"	"#29CA")	; triangle with dot above [4 fonts], few fonts draw it
;("<triangleubar>"	"#29CB")	; triangle with underbar [4 fonts], few fonts draw it
;("<triangles>"		"#29CC")	; s in triangle [4 fonts], few fonts draw it
;("<triangleserifs>"	"#29CD")	; triangle with serifs at bottom [4 fonts], few fonts draw it
;("<rtriltri>"		"#29CE")	; right triangle above left triangle [4 fonts], few fonts draw it
;("<ltrivb>"		"#29CF")	; left triangle beside vertical bar [4 fonts], few fonts draw it
;("<vbrtri>"		"#29D0")	; vertical bar beside right triangle [4 fonts], few fonts draw it
;("<lfbowtie>"		"#29D1")	; left black bowtie [4 fonts], few fonts draw it
;("<rfbowtie>"		"#29D2")	; right black bowtie [4 fonts], few fonts draw it
;("<fbowtie>"		"#29D3")	; black bowtie [4 fonts], few fonts draw it
;("<lftimes>"		"#29D4")	; left black times [4 fonts], few fonts draw it
;("<rftimes>"		"#29D5")	; right black times [4 fonts], few fonts draw it
;("<hourglass>"		"#29D6")	; white hourglass [4 fonts], few fonts draw it
;("<blackhourglass>"	"#29D7")	; black hourglass [4 fonts], few fonts draw it
;("<lvzigzag>"		"#29D8")	; left wiggly fence [4 fonts], few fonts draw it
;("<rvzigzag>"		"#29D9")	; right wiggly fence [4 fonts], few fonts draw it
;("<Lvzigzag>"		"#29DA")	; left double wiggly fence [4 fonts], few fonts draw it
;("<Rvzigzag>"		"#29DB")	; right double wiggly fence [4 fonts], few fonts draw it
;("<iinfin>"		"#29DC")	; incomplete infinity [4 fonts], few fonts draw it
;("<tieinfty>"		"#29DD")	; tie over infinity [4 fonts], few fonts draw it
;("<nvinfty>"		"#29DE")	; infinity negated with vertical bar [4 fonts], few fonts draw it
;("<laplac>"		"#29E0")	; square with contoured outline [4 fonts], few fonts draw it
;("<lrtriangleeq>"	"#29E1")	; increases as [4 fonts], few fonts draw it
;("<shuffle>"		"#29E2")	; shuffle product [4 fonts], few fonts draw it
;("<eparsl>"		"#29E3")	; equals sign and slanted parallel [4 fonts], few fonts draw it
;("<smeparsl>"		"#29E4")	; equals sign and slanted parallel with tilde above [4 fonts], few fonts draw it
;("<eqvparsl>"		"#29E5")	; identical to and slanted parallel [4 fonts], few fonts draw it
;("<gleichstark>"	"#29E6")	; gleich stark [4 fonts], few fonts draw it
;("<thermod>"		"#29E7")	; thermodynamic [4 fonts], few fonts draw it
;("<downtriangleleftblack>"	"#29E8")	; down-pointing triangle with left half black [4 fonts], few fonts draw it
;("<downtrianglerightblack>"	"#29E9")	; down-pointing triangle with right half black [4 fonts], few fonts draw it
;("<blackdiamonddownarrow>"	"#29EA")	; black diamond with down arrow [4 fonts], few fonts draw it
;("<circledownarrow>"	"#29EC")	; white circle with down arrow [4 fonts], few fonts draw it
;("<blackcircledownarrow>"	"#29ED")	; black circle with down arrow [4 fonts], few fonts draw it
;("<errbarsquare>"	"#29EE")	; error-barred white square [4 fonts], few fonts draw it
;("<errbarblacksquare>"	"#29EF")	; error-barred black square [4 fonts], few fonts draw it
;("<errbardiamond>"	"#29F0")	; error-barred white diamond [4 fonts], few fonts draw it
;("<errbarblackdiamond>"	"#29F1")	; error-barred black diamond [4 fonts], few fonts draw it
;("<errbarcircle>"	"#29F2")	; error-barred white circle [4 fonts], few fonts draw it
;("<errbarblackcircle>"	"#29F3")	; error-barred black circle [4 fonts], few fonts draw it
;("<ruledelayed>"	"#29F4")	; rule-delayed [4 fonts], few fonts draw it
;("<setminus>"		"#29F5")	; reverse solidus operator [6 fonts], the name already means U+2216
;("<dsol>"		"#29F6")	; solidus with overbar [4 fonts], few fonts draw it
;("<rsolbar>"		"#29F7")	; reverse solidus with horizontal stroke [4 fonts], few fonts draw it
;("<xsol>"		"#29F8")	; big solidus [4 fonts], few fonts draw it
;("<xbsol>"		"#29F9")	; big reverse solidus [4 fonts], few fonts draw it
;("<doubleplus>"		"#29FA")	; double plus [4 fonts], few fonts draw it
;("<tripleplus>"		"#29FB")	; triple plus [4 fonts], few fonts draw it
;("<lcurvyangle>"	"#29FC")	; left pointing curved angle bracket [4 fonts], few fonts draw it
;("<rcurvyangle>"	"#29FD")	; right pointing curved angle bracket [4 fonts], few fonts draw it
;("<tplus>"		"#29FE")	; tiny [4 fonts], few fonts draw it
;("<tminus>"		"#29FF")	; miny [4 fonts], few fonts draw it

;;; Supplemental operators

;("<disjquant>"		"#2A08")	; two logical or operator [4 fonts], few fonts draw it
;("<modtwosum>"		"#2A0A")	; modulo two sum [4 fonts], few fonts draw it
;("<sumint>"		"#2A0B")	; summation with integral [4 fonts], few fonts draw it
;("<intbar>"		"#2A0D")	; finite part integral [4 fonts], few fonts draw it
;("<intBar>"		"#2A0E")	; integral with double stroke [4 fonts], few fonts draw it
;("<cirfnint>"		"#2A10")	; circulation function [4 fonts], few fonts draw it
;("<rppolint>"		"#2A12")	; line integration with rectangular path around pole [4 fonts], few fonts draw it
;("<scpolint>"		"#2A13")	; line integration with semicircular path around pole [4 fonts], few fonts draw it
;("<npolint>"		"#2A14")	; line integration not including the pole [4 fonts], few fonts draw it
;("<pointint>"		"#2A15")	; integral around a point operator [4 fonts], few fonts draw it
;("<intlarhk>"		"#2A17")	; integral with leftwards arrow with hook [4 fonts], few fonts draw it
;("<intx>"		"#2A18")	; integral with times sign [4 fonts], few fonts draw it
;("<intcap>"		"#2A19")	; integral with intersection [4 fonts], few fonts draw it
;("<intcup>"		"#2A1A")	; integral with union [4 fonts], few fonts draw it
;("<upint>"		"#2A1B")	; integral with overbar [4 fonts], the name already means U+222B
;("<lowint>"		"#2A1C")	; integral with underbar [4 fonts], few fonts draw it
;("<bigtriangleleft>"	"#2A1E")	; large left triangle operator [4 fonts], few fonts draw it
;("<zcmp>"		"#2A1F")	; z notation schema composition [4 fonts], few fonts draw it
;("<zpipe>"		"#2A20")	; z notation schema piping [4 fonts], few fonts draw it
;("<zproject>"		"#2A21")	; z notation schema projection [4 fonts], few fonts draw it
;("<ringplus>"		"#2A22")	; plus sign with small circle above [4 fonts], few fonts draw it
;("<plushat>"		"#2A23")	; plus sign with circumflex accent above [4 fonts], few fonts draw it
;("<simplus>"		"#2A24")	; plus sign with tilde above [4 fonts], few fonts draw it
;("<plusdot>"		"#2A25")	; plus sign with dot below [4 fonts], few fonts draw it
;("<plussim>"		"#2A26")	; plus sign with tilde below [4 fonts], few fonts draw it
;("<plussubtwo>"		"#2A27")	; plus sign with subscript two [4 fonts], few fonts draw it
;("<plustrif>"		"#2A28")	; plus sign with black triangle [4 fonts], few fonts draw it
;("<commaminus>"		"#2A29")	; minus sign with comma above [4 fonts], few fonts draw it
;("<minusdot>"		"#2A2A")	; minus sign with dot below [4 fonts], few fonts draw it
;("<minusfdots>"		"#2A2B")	; minus sign with falling dots [4 fonts], few fonts draw it
;("<minusrdots>"		"#2A2C")	; minus sign with rising dots [4 fonts], few fonts draw it
;("<opluslhrim>"		"#2A2D")	; plus sign in left half circle [4 fonts], few fonts draw it
;("<oplusrhrim>"		"#2A2E")	; plus sign in right half circle [4 fonts], few fonts draw it
;("<timesbar>"		"#2A31")	; multiplication sign with underbar [4 fonts], few fonts draw it
;("<smashtimes>"		"#2A33")	; smash product [4 fonts], few fonts draw it
;("<otimeslhrim>"	"#2A34")	; multiplication sign in left half circle [4 fonts], few fonts draw it
;("<otimesrhrim>"	"#2A35")	; multiplication sign in right half circle [4 fonts], few fonts draw it
;("<otimeshat>"		"#2A36")	; circled multiplication sign with circumflex accent [4 fonts], few fonts draw it
;("<Otimes>"		"#2A37")	; multiplication sign in double circle [4 fonts], few fonts draw it
;("<odiv>"		"#2A38")	; circled division sign [4 fonts], few fonts draw it
;("<triangleplus>"	"#2A39")	; plus sign in triangle [4 fonts], few fonts draw it
;("<triangleminus>"	"#2A3A")	; minus sign in triangle [4 fonts], few fonts draw it
;("<triangletimes>"	"#2A3B")	; multiplication sign in triangle [4 fonts], few fonts draw it
;("<intprod>"		"#2A3C")	; interior product [4 fonts], few fonts draw it
;("<intprodr>"		"#2A3D")	; righthand interior product [4 fonts], few fonts draw it
;("<fcmp>"		"#2A3E")	; z notation relational composition [4 fonts], few fonts draw it
;("<capdot>"		"#2A40")	; intersection with dot [4 fonts], few fonts draw it
;("<uminus>"		"#2A41")	; union with minus sign [4 fonts], few fonts draw it
;("<barcup>"		"#2A42")	; union with overbar [4 fonts], few fonts draw it
;("<barcap>"		"#2A43")	; intersection with overbar [4 fonts], few fonts draw it
;("<capwedge>"		"#2A44")	; intersection with logical and [4 fonts], few fonts draw it
;("<cupvee>"		"#2A45")	; union with logical or [4 fonts], few fonts draw it
;("<cupovercap>"		"#2A46")	; union above intersection [4 fonts], few fonts draw it
;("<capovercup>"		"#2A47")	; intersection above union [4 fonts], few fonts draw it
;("<cupbarcap>"		"#2A48")	; union above bar above intersection [4 fonts], few fonts draw it
;("<capbarcup>"		"#2A49")	; intersection above bar above union [4 fonts], few fonts draw it
;("<twocups>"		"#2A4A")	; union beside and joined with union [4 fonts], few fonts draw it
;("<twocaps>"		"#2A4B")	; intersection beside and joined with intersection [4 fonts], few fonts draw it
;("<closedvarcup>"	"#2A4C")	; closed union with serifs [4 fonts], few fonts draw it
;("<closedvarcap>"	"#2A4D")	; closed intersection with serifs [4 fonts], few fonts draw it
;("<Sqcap>"		"#2A4E")	; double square intersection [4 fonts], few fonts draw it
;("<Sqcup>"		"#2A4F")	; double square union [4 fonts], few fonts draw it
;("<closedvarcupsmashprod>"	"#2A50")	; closed union with serifs and smash product [4 fonts], few fonts draw it
;("<wedgeodot>"		"#2A51")	; logical and with dot above [4 fonts], few fonts draw it
;("<veeodot>"		"#2A52")	; logical or with dot above [4 fonts], few fonts draw it
;("<Wedge>"		"#2A53")	; double logical and [4 fonts], few fonts draw it
;("<Vee>"		"#2A54")	; double logical or [4 fonts], few fonts draw it
;("<wedgeonwedge>"	"#2A55")	; two intersecting logical and [4 fonts], few fonts draw it
;("<veeonvee>"		"#2A56")	; two intersecting logical or [4 fonts], few fonts draw it
;("<bigslopedvee>"	"#2A57")	; sloping large or [4 fonts], few fonts draw it
;("<bigslopedwedge>"	"#2A58")	; sloping large and [4 fonts], few fonts draw it
;("<veeonwedge>"		"#2A59")	; logical or overlapping logical and [4 fonts], few fonts draw it
;("<wedgemidvert>"	"#2A5A")	; logical and with middle stem [4 fonts], few fonts draw it
;("<veemidvert>"		"#2A5B")	; logical or with middle stem [4 fonts], few fonts draw it
;("<midbarwedge>"	"#2A5C")	; ogical and with horizontal dash [4 fonts], few fonts draw it
;("<midbarvee>"		"#2A5D")	; logical or with horizontal dash [4 fonts], few fonts draw it
;("<doublebarwedge>"	"#2A5E")	; logical and with double overbar [6 fonts], the name already means U+2306
;("<wedgebar>"		"#2A5F")	; logical and with underbar [5 fonts], few fonts draw it
;("<wedgedoublebar>"	"#2A60")	; logical and with double underbar [4 fonts], few fonts draw it
;("<varveebar>"		"#2A61")	; small vee with underbar [4 fonts], few fonts draw it
;("<doublebarvee>"	"#2A62")	; logical or with double overbar [4 fonts], few fonts draw it
;("<veedoublebar>"	"#2A63")	; logical or with double underbar [4 fonts], few fonts draw it
;("<dsub>"		"#2A64")	; z notation domain antirestriction [4 fonts], few fonts draw it
;("<rsub>"		"#2A65")	; z notation range antirestriction [4 fonts], few fonts draw it
;("<eqdot>"		"#2A66")	; equals sign with dot below [4 fonts], few fonts draw it
;("<dotequiv>"		"#2A67")	; identical with dot above [4 fonts], few fonts draw it
;("<equivVert>"		"#2A68")	; triple horizontal bar with double vertical stroke [4 fonts], few fonts draw it
;("<equivVvert>"		"#2A69")	; triple horizontal bar with triple vertical stroke [4 fonts], few fonts draw it
;("<dotsim>"		"#2A6A")	; tilde operator with dot above [4 fonts], few fonts draw it
;("<simrdots>"		"#2A6B")	; tilde operator with rising dots [4 fonts], few fonts draw it
;("<simminussim>"	"#2A6C")	; similar minus similar [4 fonts], few fonts draw it
;("<congdot>"		"#2A6D")	; congruent with dot above [4 fonts], few fonts draw it
;("<asteq>"		"#2A6E")	; equals with asterisk [4 fonts], few fonts draw it
;("<hatapprox>"		"#2A6F")	; almost equal to with circumflex accent [4 fonts], few fonts draw it
;("<approxeqq>"		"#2A70")	; approximately equal or equal to [4 fonts], few fonts draw it
;("<eqqplus>"		"#2A71")	; equals sign above plus sign [4 fonts], few fonts draw it
;("<pluseqq>"		"#2A72")	; plus sign above equals sign [4 fonts], few fonts draw it
;("<eqqsim>"		"#2A73")	; equals sign above tilde operator [4 fonts], few fonts draw it
;("<eqeq>"		"#2A75")	; two consecutive equals signs [4 fonts], few fonts draw it
;("<eqeqeq>"		"#2A76")	; three consecutive equals signs [4 fonts], few fonts draw it
;("<ddotseq>"		"#2A77")	; equals sign with two dots above and two dots below [4 fonts], few fonts draw it
;("<equivDD>"		"#2A78")	; equivalent with four dots above [4 fonts], few fonts draw it
;("<ltcir>"		"#2A79")	; less-than with circle inside [4 fonts], few fonts draw it
;("<gtcir>"		"#2A7A")	; greater-than with circle inside [4 fonts], few fonts draw it
;("<ltquest>"		"#2A7B")	; less-than with question mark above [4 fonts], few fonts draw it
;("<gtquest>"		"#2A7C")	; greater-than with question mark above [4 fonts], few fonts draw it
;("<lesdot>"		"#2A7F")	; less-than or slanted equal to with dot inside [4 fonts], few fonts draw it
;("<gesdot>"		"#2A80")	; greater-than or slanted equal to with dot inside [4 fonts], few fonts draw it
;("<lesdoto>"		"#2A81")	; less-than or slanted equal to with dot above [4 fonts], few fonts draw it
;("<gesdoto>"		"#2A82")	; greater-than or slanted equal to with dot above [4 fonts], few fonts draw it
;("<lesdotor>"		"#2A83")	; less-than or slanted equal to with dot above right [4 fonts], few fonts draw it
;("<gesdotol>"		"#2A84")	; greater-than or slanted equal to with dot above left [4 fonts], few fonts draw it
;("<lsime>"		"#2A8D")	; less-than above similar or equal [4 fonts], few fonts draw it
;("<gsime>"		"#2A8E")	; greater-than above similar or equal [4 fonts], few fonts draw it
;("<lsimg>"		"#2A8F")	; less-than above similar above greater-than [4 fonts], few fonts draw it
;("<gsiml>"		"#2A90")	; greater-than above similar above less-than [4 fonts], few fonts draw it
;("<lgE>"		"#2A91")	; less-than above greater-than above double-line equal [4 fonts], few fonts draw it
;("<glE>"		"#2A92")	; greater-than above less-than above double-line equal [4 fonts], few fonts draw it
;("<lesges>"		"#2A93")	; less-than above slanted equal above greater-than above slanted equal [4 fonts], few fonts draw it
;("<gesles>"		"#2A94")	; greater-than above slanted equal above less-than above slanted equal [4 fonts], few fonts draw it
;("<elsdot>"		"#2A97")	; slanted equal to or less-than with dot inside [4 fonts], few fonts draw it
;("<egsdot>"		"#2A98")	; slanted equal to or greater-than with dot inside [4 fonts], few fonts draw it
;("<eqqless>"		"#2A99")	; double-line equal to or less-than [4 fonts], few fonts draw it
;("<eqqgtr>"		"#2A9A")	; double-line equal to or greater-than [4 fonts], few fonts draw it
;("<eqqslantless>"	"#2A9B")	; double-line slanted equal to or less-than [4 fonts], few fonts draw it
;("<eqqslantgtr>"	"#2A9C")	; double-line slanted equal to or greater-than [4 fonts], few fonts draw it
;("<simless>"		"#2A9D")	; similar or less-than [4 fonts], few fonts draw it
;("<simgtr>"		"#2A9E")	; similar or greater-than [4 fonts], few fonts draw it
;("<simlE>"		"#2A9F")	; similar above less-than above equals sign [4 fonts], few fonts draw it
;("<simgE>"		"#2AA0")	; similar above greater-than above equals sign [4 fonts], few fonts draw it
;("<Lt>"			"#2AA1")	; double nested less-than [4 fonts], few fonts draw it
;("<Gt>"			"#2AA2")	; double nested greater-than [4 fonts], few fonts draw it
;("<partialmeetcontraction>"	"#2AA3")	; double less-than with underbar [4 fonts], few fonts draw it
;("<glj>"		"#2AA4")	; greater-than overlapping less-than [4 fonts], few fonts draw it
;("<gla>"		"#2AA5")	; greater-than beside less-than [4 fonts], few fonts draw it
;("<lescc>"		"#2AA8")	; less-than closed by curve above slanted equal [4 fonts], few fonts draw it
;("<gescc>"		"#2AA9")	; greater-than closed by curve above slanted equal [4 fonts], few fonts draw it
;("<smt>"		"#2AAA")	; smaller than [4 fonts], few fonts draw it
;("<lat>"		"#2AAB")	; larger than [4 fonts], few fonts draw it
;("<smte>"		"#2AAC")	; smaller than or equal to [4 fonts], few fonts draw it
;("<late>"		"#2AAD")	; larger than or equal to [4 fonts], few fonts draw it
;("<bumpeqq>"		"#2AAE")	; equals sign with bumpy above [4 fonts], few fonts draw it
;("<Prec>"		"#2ABB")	; double precedes [4 fonts], few fonts draw it
;("<Succ>"		"#2ABC")	; double succeeds [4 fonts], few fonts draw it
;("<subsetdot>"		"#2ABD")	; subset with dot [4 fonts], few fonts draw it
;("<supsetdot>"		"#2ABE")	; superset with dot [4 fonts], few fonts draw it
;("<subsetplus>"		"#2ABF")	; subset with plus sign below [4 fonts], already a TeXmacs symbol, check that the shape agrees
;("<supsetplus>"		"#2AC0")	; superset with plus sign below [4 fonts], already a TeXmacs symbol, check that the shape agrees
;("<submult>"		"#2AC1")	; subset with multiplication sign below [4 fonts], few fonts draw it
;("<supmult>"		"#2AC2")	; superset with multiplication sign below [4 fonts], few fonts draw it
;("<subedot>"		"#2AC3")	; subset of or equal to with dot above [4 fonts], few fonts draw it
;("<supedot>"		"#2AC4")	; superset of or equal to with dot above [4 fonts], few fonts draw it
;("<subsim>"		"#2AC7")	; subset of above tilde operator [4 fonts], few fonts draw it
;("<supsim>"		"#2AC8")	; superset of above tilde operator [4 fonts], few fonts draw it
;("<subsetapprox>"	"#2AC9")	; subset of above almost equal to [4 fonts], few fonts draw it
;("<supsetapprox>"	"#2ACA")	; superset of above almost equal to [4 fonts], few fonts draw it
;("<lsqhook>"		"#2ACD")	; square left open box operator [4 fonts], few fonts draw it
;("<rsqhook>"		"#2ACE")	; square right open box operator [4 fonts], few fonts draw it
;("<csub>"		"#2ACF")	; closed subset [4 fonts], few fonts draw it
;("<csup>"		"#2AD0")	; closed superset [4 fonts], few fonts draw it
;("<csube>"		"#2AD1")	; closed subset or equal to [4 fonts], few fonts draw it
;("<csupe>"		"#2AD2")	; closed superset or equal to [4 fonts], few fonts draw it
;("<subsup>"		"#2AD3")	; subset above superset [4 fonts], few fonts draw it
;("<supsub>"		"#2AD4")	; superset above subset [4 fonts], few fonts draw it
;("<subsub>"		"#2AD5")	; subset above subset [4 fonts], few fonts draw it
;("<supsup>"		"#2AD6")	; superset above superset [4 fonts], few fonts draw it
;("<suphsub>"		"#2AD7")	; superset beside subset [4 fonts], few fonts draw it
;("<supdsub>"		"#2AD8")	; superset beside and joined by dash with subset [4 fonts], few fonts draw it
;("<forkv>"		"#2AD9")	; element of opening downwards [4 fonts], few fonts draw it
;("<topfork>"		"#2ADA")	; pitchfork with tee top [4 fonts], few fonts draw it
;("<mlcp>"		"#2ADB")	; transversal intersection [4 fonts], few fonts draw it
;("<forks>"		"#2ADC")	; forking [4 fonts], few fonts draw it
;("<forksnot>"		"#2ADD")	; nonforking [4 fonts], few fonts draw it
;("<shortlefttack>"	"#2ADE")	; short left tack [4 fonts], few fonts draw it
;("<shortdowntack>"	"#2ADF")	; short down tack [4 fonts], few fonts draw it
;("<shortuptack>"	"#2AE0")	; short up tack [4 fonts], few fonts draw it
;("<perps>"		"#2AE1")	; perpendicular with s [4 fonts], few fonts draw it
;("<vDdash>"		"#2AE2")	; vertical bar triple right turnstile [4 fonts], few fonts draw it
;("<varVdash>"		"#2AE6")	; long dash from left member of double vertical [4 fonts], few fonts draw it
;("<Barv>"		"#2AE7")	; short down tack with overbar [4 fonts], few fonts draw it
;("<vBar>"		"#2AE8")	; short up tack with underbar [4 fonts], few fonts draw it
;("<vBarv>"		"#2AE9")	; short up tack above short down tack [4 fonts], few fonts draw it
;("<Not>"		"#2AEC")	; double stroke not sign [4 fonts], few fonts draw it
;("<bNot>"		"#2AED")	; reversed double stroke not sign [4 fonts], few fonts draw it
;("<revnmid>"		"#2AEE")	; does not divide with reversed negation slash [4 fonts], few fonts draw it
;("<cirmid>"		"#2AEF")	; vertical line with circle above [4 fonts], few fonts draw it
;("<midcir>"		"#2AF0")	; vertical line with circle below [4 fonts], few fonts draw it
;("<topcir>"		"#2AF1")	; down tack with circle below [4 fonts], few fonts draw it
;("<nhpar>"		"#2AF2")	; parallel with horizontal stroke [4 fonts], few fonts draw it
;("<parsim>"		"#2AF3")	; parallel with tilde operator [4 fonts], few fonts draw it
;("<nhVvert>"		"#2AF5")	; triple vertical bar with horizontal stroke [4 fonts], few fonts draw it
;("<threedotcolon>"	"#2AF6")	; triple colon operator [4 fonts], few fonts draw it
;("<lllnest>"		"#2AF7")	; stacked very much less-than [4 fonts], few fonts draw it
;("<gggnest>"		"#2AF8")	; stacked very much greater-than [4 fonts], few fonts draw it
;("<trslash>"		"#2AFB")	; triple solidus binary relation [4 fonts], few fonts draw it
;("<biginterleave>"	"#2AFC")	; large triple vertical bar operator [4 fonts], few fonts draw it
;("<sslash>"		"#2AFD")	; double solidus operator [4 fonts], few fonts draw it
;("<talloblong>"		"#2AFE")	; white vertical bar [4 fonts], the name already means U+2338
;("<bigtalloblong>"	"#2AFF")	; n-ary white vertical bar [4 fonts], few fonts draw it

;;; Miscellaneous symbols and arrows

;("<squaretopblack>"	"#2B12")	; square with top half black [4 fonts], few fonts draw it
;("<squarebotblack>"	"#2B13")	; square with bottom half black [4 fonts], few fonts draw it
;("<squareurblack>"	"#2B14")	; square with upper right diagonal half black [4 fonts], few fonts draw it
;("<squarellblack>"	"#2B15")	; square with lower left diagonal half black [4 fonts], few fonts draw it
;("<diamondleftblack>"	"#2B16")	; diamond with left half black [4 fonts], few fonts draw it
;("<diamondrightblack>"	"#2B17")	; diamond with right half black [4 fonts], few fonts draw it
;("<diamondtopblack>"	"#2B18")	; diamond with top half black [4 fonts], few fonts draw it
;("<diamondbotblack>"	"#2B19")	; diamond with bottom half black [4 fonts], few fonts draw it
;("<lgblksquare>"	"#2B1B")	; black large square [4 fonts], few fonts draw it
;("<lgwhtsquare>"	"#2B1C")	; white large square [4 fonts], few fonts draw it
;("<vysmblksquare>"	"#2B1D")	; black very small square [5 fonts], few fonts draw it
;("<vysmwhtsquare>"	"#2B1E")	; white very small square [5 fonts], few fonts draw it
;("<pentagonblack>"	"#2B1F")	; black pentagon [4 fonts], few fonts draw it
;("<pentagon>"		"#2B20")	; white pentagon [4 fonts], few fonts draw it
;("<varhexagon>"		"#2B21")	; white hexagon [4 fonts], few fonts draw it
;("<varhexagonblack>"	"#2B22")	; black hexagon [4 fonts], few fonts draw it
;("<hexagonblack>"	"#2B23")	; horizontal black hexagon [4 fonts], few fonts draw it
;("<mdblklozenge>"	"#2B27")	; black medium lozenge [4 fonts], few fonts draw it
;("<smblkdiamond>"	"#2B29")	; black small diamond [4 fonts], few fonts draw it
;("<smblklozenge>"	"#2B2A")	; black small lozenge [4 fonts], few fonts draw it
;("<smwhtlozenge>"	"#2B2B")	; white small lozenge [4 fonts], few fonts draw it
;("<blkhorzoval>"	"#2B2C")	; black horizontal ellipse [4 fonts], few fonts draw it
;("<whthorzoval>"	"#2B2D")	; white horizontal ellipse [4 fonts], few fonts draw it
;("<blkvertoval>"	"#2B2E")	; black vertical ellipse [4 fonts], few fonts draw it
;("<whtvertoval>"	"#2B2F")	; white vertical ellipse [4 fonts], few fonts draw it
;("<circleonleftarrow>"	"#2B30")	; left arrow with small circle [4 fonts], few fonts draw it
;("<leftarrowonoplus>"	"#2B32")	; left arrow with circled plus [4 fonts], few fonts draw it
;("<nvtwoheadleftarrow>"	"#2B34")	; leftwards two-headed arrow with vertical stroke [4 fonts], few fonts draw it
;("<nVtwoheadleftarrow>"	"#2B35")	; leftwards two-headed arrow with double vertical stroke [4 fonts], few fonts draw it
;("<twoheadmapsfrom>"	"#2B36")	; leftwards two-headed arrow from bar [4 fonts], few fonts draw it
;("<twoheadleftdbkarrow>"	"#2B37")	; leftwards two-headed triple-dash arrow [4 fonts], few fonts draw it
;("<leftdotarrow>"	"#2B38")	; leftwards arrow with dotted stem [4 fonts], few fonts draw it
;("<nvleftarrowtail>"	"#2B39")	; leftwards arrow with tail with vertical stroke [4 fonts], few fonts draw it
;("<nVleftarrowtail>"	"#2B3A")	; leftwards arrow with tail with double vertical stroke [4 fonts], few fonts draw it
;("<twoheadleftarrowtail>"	"#2B3B")	; leftwards two-headed arrow with tail [4 fonts], few fonts draw it
;("<nvtwoheadleftarrowtail>"	"#2B3C")	; leftwards two-headed arrow with tail with vertical stroke [4 fonts], few fonts draw it
;("<nVtwoheadleftarrowtail>"	"#2B3D")	; leftwards two-headed arrow with tail with double vertical stroke [4 fonts], few fonts draw it
;("<leftarrowx>"		"#2B3E")	; leftwards arrow through x [4 fonts], few fonts draw it
;("<leftcurvedarrow>"	"#2B3F")	; wave arrow pointing directly left [4 fonts], few fonts draw it
;("<equalleftarrow>"	"#2B40")	; equals sign above leftwards arrow [4 fonts], few fonts draw it
;("<bsimilarleftarrow>"	"#2B41")	; reverse tilde operator above leftwards arrow [4 fonts], few fonts draw it
;("<leftarrowbackapprox>"	"#2B42")	; leftwards arrow above reverse almost equal to [4 fonts], few fonts draw it
;("<rightarrowgtr>"	"#2B43")	; rightwards arrow through greater-than [4 fonts], few fonts draw it
;("<rightarrowsupset>"	"#2B44")	; rightwards arrow through subset [4 fonts], few fonts draw it
;("<LLeftarrow>"		"#2B45")	; leftwards quadruple arrow [4 fonts], few fonts draw it
;("<RRightarrow>"	"#2B46")	; rightwards quadruple arrow [4 fonts], few fonts draw it
;("<bsimilarrightarrow>"	"#2B47")	; reverse tilde operator above rightwards arrow [4 fonts], few fonts draw it
;("<rightarrowbackapprox>"	"#2B48")	; rightwards arrow above reverse almost equal to [4 fonts], few fonts draw it
;("<similarleftarrow>"	"#2B49")	; tilde operator above leftwards arrow [4 fonts], few fonts draw it
;("<leftarrowapprox>"	"#2B4A")	; leftwards arrow above almost equal to [4 fonts], few fonts draw it
;("<leftarrowbsimilar>"	"#2B4B")	; leftwards arrow above reverse tilde operator [4 fonts], few fonts draw it
;("<rightarrowbsimilar>"	"#2B4C")	; righttwards arrow above reverse tilde operator [4 fonts], few fonts draw it
;("<medwhitestar>"	"#2B50")	; white medium star [4 fonts], few fonts draw it
;("<medblackstar>"	"#2B51")	; black medium star [4 fonts], few fonts draw it
;("<smwhitestar>"	"#2B52")	; white small star [4 fonts], few fonts draw it
;("<rightpentagonblack>"	"#2B53")	; black right-pointing pentagon [4 fonts], few fonts draw it
;("<rightpentagon>"	"#2B54")	; white right-pointing pentagon [4 fonts], few fonts draw it

;;; Other

;("<postalmark>"		"#3012")	; postal mark [4 fonts], few fonts draw it
;("<hzigzag>"		"#3030")	; zigzag [4 fonts], few fonts draw it

;;; Mathematical alphanumerics

;("<imath>"		"#1D6A4")	; mathematical italic small dotless i [12 fonts], the name already means U+0131
;("<jmath>"		"#1D6A5")	; mathematical italic small dotless j [12 fonts], already a TeXmacs symbol, check that the shape agrees
;("<mbfDigamma>"		"#1D7CA")	; mathematical bold capital digamma [3 fonts], few fonts draw it
;("<mbfdigamma>"		"#1D7CB")	; mathematical bold small digamma [3 fonts], few fonts draw it

;;; Arabic mathematical

;("<arabicmaj>"		"#1EEF0")	; arabic mathematical operator meem with hah with tatweel [3 fonts], few fonts draw it
;("<arabichad>"		"#1EEF1")	; arabic mathematical operator hah with dal [3 fonts], few fonts draw it
