("A modifier" "Modifikátor A")
("GNU" "GNU")
("H modifier" "Modifikátor H")
("LaTeX" "LaTeX")
("M modifier" "Modifikátor M")
("TeX" "TeX")
("abbreviation" "zkratka")
("about" "o programu")
("apropos" "o programu")
("about menu" "o programu")
("above" "nad")
("abstract" "abstrakt")
("accent" "akcent")
("accept" "akceptovat")
("accept all scripts" "povolit v²echny skripty")
("accept no scripts" "nepovolit ºádné skripty")
("accept script" "povolit skript")
("acknowledgment" "pod¥kování")
("acronym" "akronym")
("action" "akce")
("activate" "aktivovat")
("acute" "£árka")
("add switch after" "vloºit p°epína£ za")
("add switch before" "vloºit p°epína£ p°ed")
("address" "adresa")
("address block" "blok adresy")
("advanced" "pokro£ilé")
("advanced layout features" "pokro£ilé vlastnosti rozloºení")
("after" "po")
("albanian" "albánskı")
("algorithm" "algoritmus")
("align cell to the bottom" "zarovnat bu¬ku dol·")
("align cell to the left" "zarovnat bu¬ku doleva")
("align cell to the right" "zarovnat bu¬ku doprava")
("align cell to the top" "zarovnat bu¬ku nahoru")
("align table at base of left column" "zarovnat tabulku podle sloupku vlevo")
("align table at base of middle column" "zarovnat tabulku podle sloupku uprost°ed")
("align table at base of origin column" "zarovnat tabulku podle p·vodního sloupku")
("align table at base of right column" "zarovnat tabulku podle p·vodního sloupku vpravo")
("align table at fraction bar height" "zarovnat tabulku")
("align table at the base of bottom row" "zarovnat tabulku podle °ádku dole")
("align table at the base of middle row" "zarovnat tabulku podle °ádku uprost°ed")
("align table at the base of origin row" "zarovnat tabulku podle p·vodního °ádku")
("align table at the base of top row" "zarovnat tabulku podle °ádku naho°e")
("align table at the bottom" "zarovnat tabulku dol·")
("align table at the center" "zarovnat tabulku na st°ed")
("align table at the horizontal center" "zarovnat tabulku doprost°ed")
("align table at the left" "zarovnat tabulku nalevo")
("align table at the top" "zarovnat tabulku nahoru")
("align table to the right" "zarovnat tabulku doprava")
("align text to the left" "zarovnat text doleva")
("align text to the right" "zarovnat text doprava")
("alignment" "zarovnání")
("all" "v²e")
("allow" "povolit")
("allowed extension" "povolit roz²í°ení")
("allowed reduction" "povolit redukci")
("alpha release" "alpha release")
("alt key" "klávesa alt")
("and" "a")
("appendix" "dodatek")
("apply" "pouºij")
("april" "duben")
("arab" "arab²tina")
("archaic" "archaickı")
("architecture" "architektura")
("argument" "argument")
("arithmetic" "aritmetickı")
("armenian" "arménskı")
("arrow" "²ipka")
("arrows" "²ipky")
("article" "£lánek")
("as on paper" "jako na papí°e")
("assign" "p°i°adit")
("at fraction bar height" "na zlomkovou £áru")
("at the baseline" "na ú£a°í")
("at the bottom" "dol·")
("at the left" "doleva")
("at the middle" "doprost°ed")
("at the right" "doprava")
("at the top" "nahoru")
("attach" "p°ipojit")
("attach buffer to which project" "p°ipojit snímek k projektu")
("august" "srpen")
("author" "autor")
("authorize" "autorizovat")
("automatic" "automatickı")
("automatically generated content" "automaticky generovanı obsah")
("axiom" "axióm")
("background" "pozadí")
("background color" "barva pozadí")
("backward replace" "nahrazovat dozadu")
("backward search" "hledat dozadu")
("bad data format" "²patnı formát dat")
("bar" "pruh")
("bard" "bard")
("base level" "základní úrove¬")
("bashkirian" "bashkrian")
("basic" "základní")
("basic data types" "základní datové typy")
("basic types" "základní typy")
("be useful" "bu¤te uºite£nı")
("become a TeXmacs developer" "sta¬te se vıvojá°em TeXmacsu")
("before" "p°ed")
("begin" "za£átek")
("below" "pod")
("beta release" "beta release")
("bibliography" "literatura")
("bibliography file" "soubor s literaturou")
("bibliography style" "styl pro literaturu")
("big" "velkı")
("big figure" "velkı obrázek")
("big operator" "velkı operátor")
("big skip" "velkı odstup")
("big table" "velká tabulka")
("binary operation" "binární operace")
("binary relation" "binární relace")
("black" "£erná")
("blackboard bold" "blackboard tu£nı")
("blackboard math" "blackboard matematickı")
("blackletter" "blackletter")
("blue" "modrá")
("body" "t¥lo")
("bold" "tu£n¥")
("book" "kniha")
("border" "okraj")
("both" "oba")
("bottom" "spodek")
("bottom border" "spodní okraj")
("bottom margin" "dolní okraj")
("bottom padding" "spodní odskok")
("branch" "v¥tev")
("break" "zalomení")
("breaking" "zalamování")
("breve" "kulatı há£ek")
("british" "britskı")
("brown" "hn¥dá")
("browse" "procházet")
("browse web" "procházet web")
("browser" "prohlíºe£")
("buffer" "snímek")
("bulgarian" "bulharskı")
("bullet" "odráºka")
("bullets" "odráºky")
("by" "vytvo°il")
("by typing" "psaním")
("bytes free" "volnıch byt·")
("bytes used" "obsazenıch byt·")
("calligraphic" "kaligrafickı")
("cancel" "zru²it")
("caps-lock key" "klávesa caps-lock")
("case" "case")
("cc" "slepá kopie")
("cell" "bu¬ka")
("cell background color" "barva pozadí bu¬ky")
("cell border" "okraj bu¬ky")
("cell height" "vı²ka bu¬ky")
("cell operation mode" "opera£ní reºim bu¬ky")
("cell width" "²í°ka bu¬ky")
("center" "doprost°ed")
("center text" "vyst°edit text")
("centered" "doprost°ed")
("centered block" "vyst°ed¥nı blok")
("centered tabular" "vyst°ed¥ná tabulka")
("change border of cell" "zm¥nit okraj bu¬ky")
("change cell operation mode" "zm¥nit opera£ní reºim bu¬ky")
("change log" "záznam zm¥n")
("changes" "zm¥ny")
("chapter" "kapitola")
("check" "há£ek")
("check text for spelling errors" "otestovat pravopis textu")
("chinese" "£ín²tina")
("choice" "vıb¥r")
("citation" "citace")
("cite" "citát")
("class" "t°ída")
("clear" "smazat")
("clear selection" "smazat schránku")
("clipped" "o°ezáno")
("clipped and magnified" "o°ezáno a zv¥t²eno")
("clipped and resized" "o°ezáno a zm¥n¥ny rozm¥ry")
("clone" "duplikovat")
("clone window" "duplikovat okno")
("close" "zav°ít")
("close TeXmacs" "zav°ít TeXmacs")
("close buffer" "zav°ít snímek")
("close session" "uzav°ít sezení")
("close window" "zav°ít okno")
("closing" "uzav°ení")
("code" "zdrojovı kód")
("color" "barva")
("column" "sloupe£ek")
("column contains glued items" "sloupec obsahuje p°ilepené poloºky")
("compatibility with other formats" "kompatibilita s jinımi formáty")
("compile article" "p°eloºit £lánek")
("compile book" "p°eloºit knihu")
("compile buffer" "p°eloºit snímek")
("compile project" "p°eloºit projekt")
("complex" "komplexní")
("concrete" "concrete")
("condensed" "zúºené")
("condition" "podmínka")
("configuration" "nastavení")
("content tag" "zna£ka obsahu")
("context dependent icons" "kontextov¥ závislé ikony")
("continuation of" "obnovení £innosti")
("convention" "konvence")
("converters to other data formats" "p°evad¥£e do jinıch datovıch formát·")
("copy" "kopírovat")
("copy text" "kopírovat text")
("copy to" "kopírovat do schránky")
("copying" "kopírování")
("corollary" "korolár")
("correct text" "opravit text")
("cursors" "kurzor")
("custom tab" "vlastní tabulátor")
("customizing TeXmacs" "p°izp·sobení TeXmacsu")
("customizing the TeXmacs styles" "p°izp·sobení styl· TeXmacsu")
("custum tab" "vlastní tabulátor")
("cut" "vyjmout")
("cut text" "vyjmout text")
("cut to" "vyjmout do")
("cypriot" "cypriot")
("cyrillic" "azbuka")
("cyrillic input method" "metoda vstupu cyrilice")
("cyrillic italic right" "kurzívní azbuka")
("czech" "£e²tina")
("dancers" "dancers")
("danish" "dánskı")
("dash" "poml£ka")
("dashes" "poml£ky")
("data conversion" "p°evod dat")
("data format" "formát dat")
("date" "datum")
("deactivate" "deaktivovat")
("deactivate table" "deaktivovat tabulku")
("december" "prosinec")
("decorate atoms" "ozdobné atomy")
("default" "standardní")
("default padding" "standardní odskakování")
("definition" "definice")
("delete" "smazat")
("delete column" "smazat sloupec")
("delete row" "smazat °ádek")
("denominator" "jmenovatel")
("description" "popis")
("destination" "cíl")
("detach" "odpojit")
("determinant" "determinant")
("devangari" "devangari")
("developers guide" "pr·vodce vıvojá°e")
("directory" "adresá°")
("disable first indentation" "zakázat odsazení prvního")
("disable first indentation after" "zakázat odsazení prvního p°ed")
("disable first indentation before" "zakázat odsazení prvního p°ed")
("disable indentation" "zakázat odsazení")
("disable indentation after" "zakázat odsazení za")
("disable indentation before" "zakázat odsazení p°ed")
("disable last indentation" "zakázat odsazení posledního")
("disable last indentation after" "zakázat odsazení posledního")
("disable last indentation before" "zakázat odsazení posledního")
("disallow" "nepovolit")
("distribute unused space" "rozloºit nepouºité mezery")
("div" "podíl")
("document" "dokument")
("document format" "formát dokumentu")
("document style" "styl dokumentu")
("document styles" "styly dokument·")
("documentation" "dokumentace")
("documents are trees" "dokumenty jsou stromov¥")
("dot" "te£ka")
("dots" "te£ky")
("double stroke" "dvakrát p°e²krtnutı")
("down" "dol·")
("dpi" "dpi")
("duplicate" "duplikovat")
("dutch" "holand²tina")
("dynamic libraries" "dynamické knihovny")
("edit" "úpravy")
("editing tools" "edita£ní nástroje")
("email" "email")
("emphasize" "zvırazn¥ní")
("emphasize text" "zd·raznit text")
("empty box" "práznı box")
("enable first indentation" "povolit odsazení prvního")
("enable first indentation after" "povolit odsazení prvního")
("enable first indentation before" "povolit odsazení prvního")
("enable indentation" "povolit odsazení")
("enable indentation after" "povolit odsazení za")
("enable indentation before" "povolit odsazení p°ed")
("enable last indentation" "povolit odsazení posledního")
("enable last indentation after" "povolit odsazení posledního p°ed")
("enable last indentation before" "povolit odsazení posledního p°ed")
("encl" "p°ílohy")
("end" "konec")
("english" "angli£tina")
("enter a title" "vloºit titulek")
("enumerate" "£íslovanı seznam")
("enumerate|Alpha" "£íslování|Abecední")
("enumerate|Roman" "£íslování|ímské")
("enumerate|alpha" "£íslování|abecední")
("enumerate|roman" "£íslování|°ímské")
("env" "prost°edí")
("environment" "prost°edí")
("epilogue" "epilog")
("equal" "rovno")
("equation" "rovnice")
("equations" "soustava rovnic")
("equivalent for" "ekvivalent pro")
("error" "chyba")
("esperanto" "esperanto")
("etruscan" "etruskı")
("evaluate" "vyhodnotit")
("evaluate scheme expression" "vyhodnotit vıraz scheme")
("even page footer" "zápatí sudé stránky")
("even page header" "záhlaví sudé stránky")
("even page margin" "okraj sudé stránky")
("even page text" "text sudé stránky")
("exact horizontal" "p°esná vodorovná")
("exact mode" "p°esnı reºim")
("exam" "zkou²ka")
("example" "p°íklad")
("exclusive" "vyjma")
("exclusive or" "nonekvivalence")
("executable" "spustitelnı")
("execute" "spustit")
("execute a TeXmacs command" "vykonat p°íkaz TeXmacsu")
("execute system command" "vykonat systémovı p°íkaz")
("executive" "executive")
("exercise" "cvi£ení")
("expand" "expandovat")
("explained" "vysv¥tlenı")
("export" "export")
("export as" "exportovat do")
("extend or normal" "roz²í°ené nebo normální")
("extern " "externí")
("extra" "extra")
("extract format" "získej formát")
("family" "rodina")
("february" "únor")
("figure" "obrázek")
("file" "soubor")
("file name" "jméno souboru")
("file not found" "soubor nenalezen")
("find next match" "hledat dal²í")
("find text" "hledat text")
("finnish" "dokon£it")
("first contact" "první seznámení")
("first indentation" "první odsazení")
("first item" "první poloºka")
("first page" "první strana")
("first start" "za£ít od")
("flat" "zplo²t¥né")
("flexibility" "flexiblita")
("flexibility factor for vertical spacing" "£initel flexibility pro svislé mezery")
("floating figure" "plovoucí obrázek")
("floating object" "plovoucí objekt")
("floating table" "plovoucí tabulka")
("fold" "balení")
("folded" "sbaleno")
("font" "písmo")
("font base size" "základní velikost písma")
("font dpi" "dpi písma")
("font family" "rodina písma")
("font name" "jméno písma")
("font series" "série písma")
("font shape" "tvar písma")
("font size" "velikost písma")
("font variant" "varianta písma")
("fonts" "písma")
("footer" "zápatí")
("footnote" "poznámka pod £arou")
("for" "for")
("foreground" "pop°edí")
("foreign" "cizí")
("format" "formát")
("formatted date" "formátované datum")
("formula" "vzorec")
("formula style" "reºim vzorce")
("forward replace" "nahrazovat dop°edu")
("forward search" "hledat dop°edu")
("fraction" "zlomek")
("french" "francouz²tina")
("full manuals" "p°íru£ky v plném zn¥ní")
("function" "funkce")
("further customization" "dal²í p°izp·sobení")
("future changes" "budoucí zm¥ny")
("gNU TeXmacs comes without any form of legal warranty" "na gNU TeXmacs se nevztahují ºádné právní nároky")
("gNU TeXmacs falls under the GNU general public license" "gNU TeXmacs spadá pod licenci GNU")
("general architecture of TeXmacs" "celková architektura TeXmacsu")
("general negation" "obecná negace")
("generating font file" "generuji font")
("generic" "obecnı")
("georgian" "georgian")
("german" "n¥m£ina")
("getting started" "za£ínáme")
("glossary" "glosá°")
("glossary entry" "poloºka glosá°e")
("glue" "slepit")
("glue decorations" "slepit dekorace")
("go" "Jdi na")
("gothic" "gotickı")
("graphical interface" "grafické rozhraní")
("grave" "obrácená £árka")
("greater" "v¥t²í")
("greater or equal" "v¥t²í nebo rovno")
("greek" "°eckı")
("greek letter" "°ecké písmeno")
("green" "zelená")
("grey" "²edá")
("group" "skupina")
("happy typing" "p°íjemné psaní")
("has been aborted" "byl p°eru²en")
("has completed its task" "ukon£il £innost")
("hat" "st°í²ka")
("header" "hlavi£ka")
("header and footer" "záhlaví a zápatí")
("hebrew" "hebrejskı")
("height" "vı²ka")
("height is exactly the specified height" "vı²ka je p°esn¥ dle zadání")
("height is maximum of specified height and box height" "vı²ka je maximum ze zadání a vı²ky boxu")
("height is minimum of specified height and box height" "vı²ka je minimum ze zadání a vı²ky boxu")
("height magnification" "prodlouºení")
("help" "nápov¥da")
("help me" "pomozte mi")
("help us" "pomozte nám")
("here" "zde")
("home" "domovskı adresá°")
("horizontal" "vodorovná")
("horizontal cell alignment" "vodorovné zarovnání bu¬ky")
("horizontal ink separation" "vodorovné odd¥lení barvy")
("horizontal part" "vodorovná £ást")
("horizontal position" "vodorovná pozice")
("horizontal space" "vodorvná mezera")
("horizontal table alignment" "vodorovné zarovnání tabulky")
("horizontally align cell to the base" "zarovnat bu¬ku vodorovn¥ k základn¥")
("horizontally center the cell" "vycentrovat bu¬ku")
("how much longer may pages become" "o kolik mohou bıt stránky del²í")
("how much shorter may pages become" "o kolik mohou bıt stránky krat²í")
("huge" "obrovskı")
("hungarian" "ma¤arskı")
("hyperlink" "hyperodkaz")
("hyphenation" "d¥lení slov")
("icelandic" "islandskı")
("if" "if")
("image" "obrázek")
("image links" "odkazy obrázku")
("implementation" "implementace")
("import" "import")
("improving the current implementation" "zlep²ování sou£asné implementace")
("inactive" "neaktivní")
("include" "vloºit")
("include a document" "vloºit dokument")
("include file" "vloºit soubor")
("inclusion into TeXmacs" "zahrnutí do TeXmacsu")
("inclusions" "vloºení")
("indent" "odsazení")
("indentation flag" "nastavení odsazení")
("index" "rejst°ík")
("index entry" "poloºka rejst°íku")
("index level" "úrove¬ indexu")
("insert" "vloºit")
("insert Pr" "vloºit Pr")
("insert a TeXmacs symbol" "vloºit symbol TeXmacsu")
("insert a big operator" "vloºit velkı operátor")
("insert a binary operation" "vloºit binární operaci")
("insert a binary relation" "vloºit binární relaci")
("insert a blackboard bold character" "vloºit velmi tu£nı znak")
("insert a bold calligraphic character" "vloºit tu£nı kaligrafickı znak")
("insert a bold character" "vloºit tu£nı znak")
("insert a calligraphic character" "vloºit kaligrafickı znak")
("insert a fraction" "vloºit zlomek")
("insert a fraktur character" "vloºit znak fraktur")
("insert a greek character" "vloºit °ecké písmeno")
("insert a large left delimiter" "vloºit velkı levı omezova£")
("insert a large right delimiter" "vloºit velkı pravı omezova£")
("insert a large separator" "vloºit velkı odd¥lova£")
("insert a left subscript" "vloºit levı dolní index")
("insert a link" "vloºte odkaz")
("insert a miscellaneous symbol" "vloºit jinı symbol")
("insert a new branch" "vloºte novou v¥tev")
("insert a new item" "vloºit novou poloºku")
("insert a picture" "vloºit obrázek")
("insert a square root" "vloºit odmocninu")
("insert a table" "vloºit tabulku")
("insert a table or a matrix" "vloºit tabulku nebo matici")
("insert an" "vloºit")
("insert an accent" "vloºit £árku")
("insert an arrow" "vloºit ²ipku")
("insert an environment" "vloºit prost°edí")
("insert an n" "vloºit n")
("insert appendix" "vloºit dodatek")
("insert arccos" "vloºit arccos")
("insert arcsin" "vloºit arcsin")
("insert arctan" "vloºit arctan")
("insert arg" "vloºit arg")
("insert argument" "vloºte argument")
("insert automatically generated content" "vloºit automaticky generovanı obsah")
("insert big contour integral" "vloºit integrál po k°ivce")
("insert big coproduct" "vloºit velkı coproduct")
("insert big direct sum" "vloºit velké plus v kole£ku")
("insert big dotted point" "vloºit velkou te£ku v kole£ku")
("insert big integral" "vloºit velkı integrál")
("insert big intersection" "vloºit velkı pr·nik")
("insert big logical and" "vloºit velkou konjunkci")
("insert big logical or" "vloºit velkou disjunkci")
("insert big product" "vloºit velkı sou£in")
("insert big square union" "vloºit velké hranaté sjednocení")
("insert big summation" "vloºit velkou sumu")
("insert big tensor product" "vloºit velkı sou£in tenzor·")
("insert big union" "vloºit velké sjednocení")
("insert big union sum" "vloºit velkı sjednocující sou£et")
("insert big vertical space" "vloºit velkou svislou mezeru")
("insert chapter" "vloºit kapitolu")
("insert column" "vloºit sloupec")
("insert column to the left" "vloºit sloupec nalevo")
("insert column to the right" "vloºit sloupec napravo")
("insert cos" "vloºit cos")
("insert cosh" "vloºit cosh")
("insert cot" "vloºit cot")
("insert coth" "vloºit coth")
("insert csc" "vloºit csc")
("insert deg" "vloºit deg")
("insert det" "vloºit det")
("insert dim" "vloºit dim")
("insert dollar" "vloºit dolar")
("insert equation" "vloºit rovnici")
("insert executable markup" "vloºit spustitelnou zna£ku")
("insert exp" "vloºit exp")
("insert footnote" "vloºit poznámku pod £arou")
("insert formula" "vloºit vzorec")
("insert gcd" "vloºit gcd")
("insert hom" "vloºit hom")
("insert horizontal interword space" "vloºit vodorovnou mezislovní mezeru")
("insert image" "vloºit obrázek")
("insert inactive markup" "vloºit neaktivní zna£ku")
("insert inf" "vloºit inf")
("insert ker" "vloºit ker")
("insert lg" "vloºit lg")
("insert lim" "vloºit lim")
("insert liminf" "vloºit liminf")
("insert limsup" "vloºit limsup")
("insert ln" "vloºit ln")
("insert log" "vloºit log")
("insert mathematics" "vloºit matematiku")
("insert max" "vloºit max")
("insert medium horizontal space" "vloºit st°ední vodorovnou mezeru")
("insert medium vertical space" "vloºit st°ední svislou mezeru")
("insert min" "vloºit min")
("insert negative horizontal space" "vloºit zápornou vodorovnou mezeru")
("insert new item or number" "vloºit novou poloºku")
("insert new rows or columns" "voºit nové °ádky nebo sloupce")
("insert or delete rows or columns" "vloºit nebo smazat °ádky nebo sloupce")
("insert row" "vloºit °ádek")
("insert row above" "vloºit °ádek nad")
("insert row below" "vloºit °ádek pod")
("insert sec" "vloºit sec")
("insert section" "vloºit sekci")
("insert sharp" "vloºit k°íºek")
("insert sin" "vloºit sin")
("insert sinh" "vloºit sinh")
("insert small horizontal space" "vloºit malou vodorovnou mezeru")
("insert small vertical space" "vloºit malou svislou mezeru")
("insert structural markup" "vloºit strukturovanou zna£ku")
("insert subsection" "vloºit podsekci")
("insert subsubsection" "vloºit podpodsekci")
("insert sup" "vloºit sup")
("insert tan" "vloºit tan")
("insert tanh" "vloºit tanh")
("insert thick horizontal space" "vloºit velkou vodorovnou mezeru")
("interfacing" "rozhraní")
("interfacing TeXmacs with other systems" "rozhraní TeXmacsu s jinımi systémy")
("interjection" "citoslovce")
("interline separation" "odd¥lené °ádk·")
("interline space" "mezera mezi °ádky")
("internationalization" "lokalizace")
("interparagraph space" "mezera mezi odstavci")
("interrupt execution" "p°eru²it spu²t¥ní")
("introduction" "úvod")
("invisible" "neviditelnı")
("invisible citation" "neviditelná citace")
("irish" "irskı")
("is running" "je spu²t¥n")
("is tuple" "je n-tice")
("ispell does not respond" "ispell neodpovídá")
("ispell is already busy" "ispell jiº pracuje")
("italian" "ital²tina")
("italic" "kurzíva")
("italic right" "kurzíva vpravo")
("itemize" "ne£íslovanı seznam")
("january" "leden")
("japanese" "japon²tina")
("july" "£ervenec")
("june" "£erven")
("justified" "zarovnání")
("justify text" "p°eformátovat text")
("key" "klávesa")
("keyboard" "klávesnice")
("keyboard equivalent" "klávesová zkratka")
("keyboard modifiers" "klávesové modifikátory")
("keyboard shortcut" "klávesová zkratka")
("keymaps" "mapování kláves")
("keyword" "klí£ové slovo")
("keywords" "klí£ová slova")
("kill" "zabít")
("known bugs" "známé chyby")
("label" "popisek")
("landscape" "na ²í°ku")
("language" "jazyk")
("large" "v¥t²í")
("large closing bracket" "velká uzavírací závorka")
("large delimiter" "velkı omezova£ znak·")
("large opening bracket" "velké otevírací závorka")
("large separator" "velkı odd¥lova£")
("last indentation" "poslední odsazení")
("last page" "poslední strana")
("latex command" "p°íkaz pro latex")
("latin" "latinka")
("layout" "vzhled")
("left" "levı")
("left border" "levı okraj")
("left margin" "levı okraj")
("left padding" "levé odsko£ení")
("left prime" "levá £árka")
("left aligned" "zarovnání doleva")
("left slanted" "sklon¥né doleva")
("left subscript" "dolní index vlevo")
("left superscript" "horní index vlevo")
("left surrounding" "levé okolí")
("legal" "legal")
("lemma" "lemma")
("length" "délka")
("less" "men²í")
("less or equal" "men²í nebo rovno")
("letter" "dopis")
("license" "licence")
("light" "jemné")
("limitations" "omezení")
("limits" "limity")
("line" "°ádek")
("line break" "zalomení °ádku")
("line stretch" "roztáhnutí °ádky")
("link" "odkaz")
("link image" "propojit obrázek")
("list" "seznam")
("list of figures" "seznam obrázk·")
("list of tables" "seznam tabulek")
("load" "otev°ít")
("load LaTeX file" "otev°ít soubor LaTeX")
("load TeX file" "otev°ít soubor TeX")
("load TeXmacs file" "otev°ít soubor TeXmacs")
("load TeXmacs style file" "otev°ít soubor stylu TeXmacs")
("load a file" "otev°ít soubor")
("load buffer" "otev°ít snímek")
("load file" "otev°ít soubor")
("load html file" "otev°ít soubor html")
("load image" "otev°ít obrázek")
("load in new window" "nahrát do nového okna")
("load latex file" "otev°ít soubor LaTeX")
("load more recent autosave file" "otev°ít nov¥j²í soubor automatické zálohy")
("load tex file" "otev°ít soubor TeX")
("load verbatim file" "otev°ít soubor verbatim")
("loaded" "otev°eno")
("long" "protaºené")
("look and feel" "vzhled a chování")
("look up" "vyhledat")
("lower border" "dolní okraj")
("macro" "makro")
("magenta" "fialová")
("magic" "kouzelnı")
("magnification" "zv¥t²ení")
("magnified" "zv¥t²eno")
("main" "hlavní")
("main icon bar" "hlavní panel nástroj·")
("major changes" "hlavní zm¥ny")
("make a page insertion" "vloºení stránky")
("make a subscript" "dolní index")
("make a superscript" "horní index")
("make acute" "vloºit £árku")
("make bar" "vloºit pruh")
("make check" "vloºit há£ek")
("make fraction" "vloºit zlomek")
("make grave" "vloºit obrácenou £árku")
("make hat" "vloºit st°í²ka")
("make label" "vytvo°it náv¥²tí")
("make negation" "vloºit negaci")
("make page reference" "vytvo°it odkaz na stranu")
("make reference" "vytvo°it odkaz")
("make square root" "vloºit odmocninu")
("make tilde" "vloºit vlnka")
("make title" "vytvo°it titul")
("make vector" "vloºit vektor")
("making donations" "finan£ní podpora")
("manual" "p°íru£ka")
("map to" "p°i°azení k")
("march" "b°ezen")
("margins" "okraje")
("margins as on paper" "okraje jako na papí°e")
("master" "hlavní")
("master file" "hlavní soubor")
("math" "matika")
("math font" "písmo pro matematiku")
("math font family" "rodina písma pro matematiku")
("math font series" "série písma pro matematiku")
("math font shape" "tvar písma pro matematiku")
("mathematical" "matematickı")
("mathematical formulas" "matematické vzorce")
("mathematical typesetting" "matematická sazba")
("mathematics" "matematika")
("matrix" "matice")
("maximal number of columns" "nejvy²²í po£et sloupc·")
("maximal number of rows" "nejvy²²í po£et °ádk·")
("maximum mode" "nejvy²²í reºim")
("may" "kv¥ten")
("medium" "st°ední")
("medium skip" "st°ední odstup")
("meminfo" "informace o pam¥ti")
("merge" "spojit")
("messy" "messy")
("meta key" "meta klávesa")
("middle" "prost°edek")
("minimal number of columns" "nejmen²í po£et sloupc·")
("minimal number of rows" "nejmen²í po£et °ádk·")
("minimum mode" "nejmen²í reºim")
("minus" "mínus")
("miscellaneous" "r·zné")
("mod" "modulo")
("mode" "reºim")
("modifier" "modifikátor")
("modify cell alignment" "zm¥nit zarovnání bu¬ky")
("modify cell border" "zm¥nit okraj bu¬ky")
("modify cell padding" "zm¥nit odskok bu¬ky")
("modify cell size" "zm¥nit velikost bu¬ky")
("modify table border" "zm¥nit okraj tabulky")
("modify table padding" "zm¥nit rozestup bun¥k")
("mongolian" "mongolskı")
("more information about GNU TeXmacs can be found in the help" "Více informací o GNU TeXmacs m·ºete najít v nápov¥d¥")
("mosaic" "mozaika")
("move down" "p°esunout dol·")
("move object" "p°esun objektu")
("move to the right when finished" "p°esunout vpravo po ukon£ení")
("move up" "p°esunout nahoru")
("n-th" "n-tá")
("n-th root" "n-tá odmocnina")
("name" "jméno")
("negation" "negace")
("new" "novı")
("new buffer" "novı snímek")
("new column" "novı sloupec")
("new item" "nová poloºka")
("new line" "novı °ádek")
("new number" "nové £íslo")
("new page" "nová stránka")
("new page before" "nová strana p°ed")
("new paragraph" "novı odstavec")
("new roman" "new roman")
("new row" "novı °ádek")
("new table" "nová tabulka")
("next line" "dal²í °ádek")
("no" "ne")
("no changes need to be saved" "ºádné zm¥ny pro uloºení")
("no dictionary for" "chybí slovník")
("no first indentation" "neodsazovat první")
("no indentation" "bez odsazení")
("no last indentation" "neodsazovat poslední")
("no line break" "nezalamovat °ádek")
("no matches found" "nic nenalezeno")
("no more matches for" "nelze nalézt dal²í")
("no more redo information available" "není moºné provést akci 'znovu'")
("no more undo information available" "není moºné provést akci 'zp¥t'")
("no name" "bezejména")
("no page break after" "nezalamovat stránku za")
("no page break before" "nezalamovat stránku p°ed")
("no spelling errors found in text" "nebyly nalezeny pravopisné chyby")
("no style" "ºádnı styl")
("none" "ºádné")
("normal" "normální")
("norwegian" "norskı")
("not" "non")
("not equal" "nerovno")
("not found" "nenalezen")
("notation" "notace")
("note" "poznámka")
("november" "listopad")
("number" "£íslo")
("number equation" "£íslovat rovnice")
("number of columns" "po£et sloupc·")
("numbered equation" "£íslovaná rovnice")
("numbered equations" "£íslovaná soustava rovnic")
("numerator" "£itatel")
("numeric" "£íselné")
("objectives" "cíle")
("occurrences" "vıskyt·")
("october" "°íjen")
("odd page footer" "zápatí liché stránky")
("odd page header" "záhlaví liché stránky")
("odd page margin" "okraj liché stránky")
("odd page text" "text liché stránky")
("off" "vypnuto")
("ok" "ok")
("old english" "staroanglickı")
("old slavonic" "staroslov¥nskı")
("old style" "starı styl")
("on" "zapnuto")
("on cells" "na bu¬ky")
("on columns" "na sloupce")
("on entire table" "na celou tabulku")
("on rows" "na °ádky")
("one spelling error has been corrected" "jedna pravopisná chyba opravena")
("online documentation" "online dokumentace")
("online help" "online nápov¥da")
("open" "otev°ít")
("open a new buffer" "otev°ít novı snímek")
("open new window" "otev°ít nové okno")
("opening" "otevírání")
("operation on named selection" "operace s pojmenovanım vıb¥rem")
("operation on primary selection" "operace s primárním vıb¥rem")
("operation on secondary selection" "operace se sekundárním vıb¥rem")
("operation on ternary selection" "operace s terciárním vıb¥rem")
("optical" "optical")
("option" "nastavení")
("options" "nastavení")
("or" "nebo")
("orange" "oranºová")
("orientation" "orientace")
("origin" "p·vod")
("original welcome message" "p·vodní p°ivítací hlá²ka")
("other" "jinı")
("other pages" "jiné stránky")
("other projects" "jiné projekty")
("other style" "jinı styl")
("outlined roman" "roman obrysovı")
("over" "nad")
("padding" "odskakování")
("page" "strana")
("page bottom margin" "dolní okraj stránky")
("page break" "zalomení stránky")
("page break before" "zlom strany p°ed")
("page height" "vı²ka stránky")
("page insertion" "vloºení stránky")
("page layout" "vzhled stránky")
("page number text" "text pro £íslování stran")
("page numbering" "£íslování stránek")
("page reference" "odkaz na stránku")
("page right margin" "pravı okraj stránky")
("page top margin" "horní okraj stránky")
("page type" "typ stránky")
("page width" "²í°ka stránky")
("paper" "papír")
("paper type" "velikost papíru")
("papyrus" "papyrus")
("paragraph" "odstavec")
("paragraph mode" "reºim odstavce")
("paragraph width" "²í°ka odstavce")
("part" "£ást")
("past changes" "minulé zm¥ny")
("paste" "vloºit")
("paste from" "vloºit ze schránky")
("paste text" "vloºit text")
("path" "cesta")
("perform operations on cells" "provést operace na bu¬kách")
("perform operations on columns" "provést operace na sloupcích")
("perform operations on entire table" "provést operace na celé tabulce")
("perform operations on rows" "provést operace na °ádcích")
("permanent" "permanentní")
("person" "osoba")
("personal dictionary has been modified" "osobní slovník byl zm¥n¥n")
("phantasy" "fantazie")
("philosophy" "filosofie")
("phoenician" "fénickı")
("phonetic" "fonetickı")
("pink" "r·ºová")
("plain block" "prostı blok")
("plain tabular" "prostá tabulka")
("planned changes" "plánované zm¥ny")
("plans for the future" "plány do budoucna")
("please" "prosím")
("please wait" "£ekejte, prosím")
("plus" "plus")
("polish" "pol²tina")
("porting TeXmacs to other platforms" "portace TeXmacsu na dal²í platformy")
("portrait" "portrét")
("portuguese" "portugal²tina")
("position" "pozice")
("position float" "umístit plovoucí")
("position floating object" "umístit plovoucí objekt")
("position the table" "umístit tabulku")
("postscript" "postscript")
("postscript image" "postscriptovı obrázek")
("pre-alpha release" "pre-alpha release")
("preamble" "preambule")
("preamble mode" "reºim preambule")
("preferences" "nastavení")
("presentation mode" "reºim prezentace")
("preview before printing" "náhled p°ed tiskem")
("preview with ghostview" "náhled p°es ghostview")
("primary" "první")
("prime" "£árka")
("print" "tisknout")
("print all" "tisknout v²e")
("print all to file" "tisknout do souboru")
("print page selection" "tisknout vıb¥r stran")
("print page selection to file" "tisknout vıb¥r stran do souboru")
("print to postscript file" "tisknout do postscriptového souboru")
("printer" "tiskárna")
("printer dpi" "dpi tiskárny")
("printing command" "p°íkaz pro tisk")
("problem" "p°íklad")
("professional" "profesionální")
("prog" "prog")
("prog font" "písmo pro programy")
("prog font family" "rodina písma pro programy")
("prog font series" "série písma pro programy")
("prog font shape" "tvar písma pro programy")
("program" "program")
("program mode" "reºim programu")
("programming" "programování")
("progressive" "progresívní")
("project" "projekt")
("projects" "projekty")
("prologue" "prolog")
("prompt on scripts" "dotázat se p°i skriptu")
("proof" "d·kaz")
("proportional" "proporcionální")
("proportional typewriter" "proporcionální psací stroj")
("proposition" "tvrzení")
("query replace" "dotázat se p°ed náhradou")
("quit" "konec")
("quotation" "citát")
("quote" "uvozovky")
("range" "rozsah")
("really close it" "opravdu uzav°ít")
("really huge" "vskutku velkı")
("really quit" "opravdu ukon£it")
("red" "£ervená")
("redo" "znovu")
("redo undone changes" "znovu poslední úpravy")
("reduce bottom margin by" "zmen²it dolní okraj o")
("reduce left margin by" "zmen²it levı okraj o")
("reduce margins" "zmen²it okraje")
("reduce right margin by" "zmen²it pravı okraj o")
("reduce top margin by" "zmen²it horní okraj o")
("reduction even page margin" "zmen²ení okraje sudé stránky")
("reduction odd page margin" "zmen²ení okraje liché stránky")
("reduction page bottom margin" "zmen²ení dolního okraje stránky")
("reduction page right margin" "zmen²ení pravého okraje stránky")
("reduction page top margin" "zmen²ení horního okraje stránky")
("reference" "reference")
("references" "odkazy")
("regular" "regulární")
("release" "release")
("reload" "znova nahrát")
("remark" "anotace")
("remove number" "odebrat £íslo")
("remove this switch" "odebrat p°epína£")
("renumber this page" "znovu o£íslovat tuto stranu")
("repeat object" "zopakovat objekt")
("replace" "nahradit")
("replace by" "nahradit")
("replaced" "nahrazeno")
("replaced one occurrence" "nahrazen jeden vıskyt")
("reset" "reset")
("resize object" "zm¥na rozm¥r· objektu")
("resized" "zm¥n¥ny rozm¥ry")
("return" "return")
("revert" "zp¥t")
("revert buffer" "obnovit snímek")
("right" "pravı")
("right border" "pravı okraj")
("right margin" "pravı okraj")
("right padding" "odskakování vpravo")
("right aligned" "zarovnání doprava")
("right subscript" "dolní index vpravo")
("right superscript" "horní index vpravo")
("right surrounding" "pravé okolí")
("rigid" "pevná")
("rigid horizontal" "pevnı ")
("rigid space" "pevná mezera")
("romanian" "rumun²tina")
("root" "ko°en")
("rotate backward" "p°eto£it nazp¥t")
("rotate forward" "p°eto£it dop°edu")
("row" "°ádek")
("row contains glued items" "°ádek obsahuje p°ilepené poloºky")
("runic" "runy")
("running author" "autor")
("running title" "titul (název)")
("russian" "ru²tina")
("russian and Ukrainian users" "uºivatelé z Ruska a Ukrajiny")
("sample" "p°íklad")
("sans serif" "bez patek")
("save" "uloºit")
("save TeXmacs file" "uloºit soubor TeXmacs")
("save TeXmacs style file" "uloºit soubor stylu TeXmacs")
("save as" "uloºit jako")
("save as LaTeX" "uloºit jako LaTeX")
("save as TeX" "uloºit jako TeX")
("save buffer" "uloºit snímek")
("save buffer as" "uloºit snímek jako")
("save file" "uloºit soubor")
("save html file" "uloºit soubor html")
("save image" "uloºit obrázek")
("save latex file" "uloºit soubor LaTeX")
("save tex file" "uloºit soubor TeX")
("save this buffer" "uloºit tento snímek")
("save verbatim file" "uloºit soubor verbatim")
("saved" "uloºeno")
("screen layout" "rozvrºení obrazovky")
("screen margins" "okraje na obrazovce")
("script" "indexy")
("script above" "index nad")
("script below" "index pod")
("script script size" "velikost indexu indexu")
("script size" "velikost indexu")
("scripts not accepted" "skripty nejsou povoleny")
("search" "hledat")
("searching" "hledám")
("secondary" "druhá")
("section" "sekce")
("security" "zabezpe£ení")
("see" "viz")
("select a document style" "vyberte styl dokumentu")
("select a foreground color" "vybrat barvu pop°edí")
("select a language" "vyberte jazyk")
("selected region" "vybraná oblast")
("selection" "vıb¥r")
("selections" "vıb¥ry")
("seminar" "seminá°")
("separation between lines" "odd¥lení °ádk·")
("separation between paragraphs" "odd¥lení odstavc·")
("separator" "odd¥lova£")
("september" "zá°í")
("serb" "srbskı")
("series" "série")
("series|right" "série|right")
("session" "sezení")
("session name" "jméno sezení")
("session type" "typ sezení")
("sessions" "sezení")
("set" "nastavit")
("set background color of cell" "nastavit barvu pozadí bu¬ky")
("set cell mode" "nastavit reºim bu¬ky")
("set extension center" "nastavit st°ed roz²í°ení")
("set height" "nastavit vı²ku")
("set height of cell" "nastavit vı²ku bu¬ky")
("set margins" "nastavit okraje")
("set n" "nastavte n")
("set paragraph margins" "nastavit okraje odstavce")
("set paragraph mode" "nastavit reºim odstavce")
("set printer dpi" "nastavení dpi tiskárny")
("set printing command" "nastavení tiskového p°íkazu")
("set span" "nastavit rozp¥tí")
("set special cell properties" "nastavit spec. vlastnosti bu¬ky")
("set special table properties" "nastavit spec. vlastnosti tabulky")
("set text width" "nastavit ²í°ku textu")
("set width" "nastavit ²í°ku")
("set width of cell" "nastavit ²í°ku bu¬ky")
("settings" "nastavení")
("setup printer" "nastavení tiskárny")
("shape" "tvar")
("shift-down" "shift-dol·")
("shift-right" "shift-doprava")
("show" "ukázat")
("show header and footer" "ukazovat záhlaví a zápatí")
("show on screen" "na obrazovku")
("shrinking factor" "zmen²ení")
("signature" "podpis")
("size" "velikost")
("size limits" "omezení velikosti")
("slanted" "sklon¥né")
("sloppy" "nedbalı")
("small" "men²í")
("small caps" "kapitálky")
("small figure" "malı obrázek")
("small skip" "malı odstup")
("small table" "malá tabulka")
("source code" "zdrojovı kód")
("space" "mezera")
("space between lines" "mezery mezi °ádky")
("space between paragraphs" "mezery mezi odstavci")
("spacing" "prokládání")
("spanish" "²pan¥l²tina")
("special" "speciální")
("special cell properties" "spec. vlastnosti bu¬ky")
("special table properties" "spec. vlastnosti tabulky")
("specific" "specifickı")
("spell" "pravopis")
("spell checking complete" "kontrolo pravopisu dokon£ena")
("spelling error" "pravopisná chyba")
("spelling errors have been corrected" "pravopisné chyby byly opraveny")
("split" "odd¥lit")
("square root" "odmocnina")
("start" "za£átek")
("start a new chapter" "za£ít novou kapitolu")
("start a new section" "za£ít novou sekci")
("start an interactive session" "spustit interaktivní sezení")
("status bar" "stavovı °ádek")
("stretchable" "zv¥t²itelná")
("stretchable horizontal" "vodorovn¥ roz²i°itelná")
("stretchable vertical" "svisle prodlouºitelná")
("stroke" "p°e²krtnutí")
("strokes" "p°e²krtnutí")
("strong" "siln¥")
("structural" "strukturovan¥")
("style" "styl")
("styles" "styly")
("sub" "pod-")
("subparagraph" "pododstavec")
("subscript" "dolní index")
("subsection" "podsekce")
("subsub" "podpod-")
("subsubsection" "podposekce")
("summary" "souhrn")
("summary of the principal TeXmacs tags" "souhrn hlavních teg· TeXmacsu")
("superpose" "superpozice")
("superposed" "superponován")
("superscript" "horní index")
("swedish" "²véd²tina")
("switch" "p°epína£")
("switch to first" "první p°epína£")
("switch to formula style" "p°epnout do stylu vzorc·")
("switch to last" "poslední p°epína£")
("switch to next" "dal²í p°epína£")
("switch to previous" "p°edchozí p°epína£")
("switching and folding" "p°epínání a balení")
("symbol" "symbol")
("system environment variables" "systémové prom¥nné")
("tab" "tab")
("table" "tabulka")
("table command" "p°íkaz tabulky")
("table of contents" "obsah")
("tables" "tabulky")
("tabular" "tabulovat")
("tabular material" "tabelární materiál")
("teXmacs as an interface" "TeXmacs jako rozhraní")
("teXmacs fonts" "fonty TeXmacsu")
("teXmacs notice" "poznámka TeXmacsu")
("teXmacs style files" "soubory se styly TeXmacsu")
("ternary" "t°etí")
("test" "test")
("tex" "TeX")
("text" "text")
("text font" "písmo pro text")
("text height correction" "oprava vı²ky textu")
("text width" "²í°ka textu")
("texts" "texty")
("th century bc" "th century bc")
("th root" "-tá odmocnina")
("thai" "thai")
("the TeXmacs authors" "auto°i TeXmacsu")
("the application did not send its usual startup banner" "aplikace nezaslala obvyklou startovací zprávu")
("the application does not reply" "aplikace neodpovídá")
("the application is already running" "aplikace je jiº spu²t¥na")
("the boxes produced by the typesetter" "boxy produkované saze£em")
("the graphical user interface" "grafické uºivatelské rozhraní")
("the leaves of TeXmacs trees" "listy stromu TeXmacsu")
("the mycas example" "p°íklad mycas")
("the primitive TeXmacs constructs" "primitivní konstrukty TeXmacsu")
("the standard TeXmacs styles" "standardní styly TeXmacsu")
("theorem" "teorém")
("there are unsaved documents" "n¥které soubory nejsou uloºeny")
("this document has not been saved" "tento snímek nebyl uloºen")
("this document has been produced using" "tento dokumenty byl vytvo°en pouºitím")
("this line" "tento °ádek")
("this page" "tato stránka")
("tilda" "tilda")
("tilde" "vlnka")
("times" "times")
("tiny" "mr¬avı")
("title" "titul")
("to the left" "nalevo")
("to the right" "napravo")
("today" "dnes")
("tools" "nástroje")
("top" "vrch")
("top border" "horní okraj")
("top level" "nejvy²²í úrove¬")
("top margin" "horní okraj")
("top padding" "horní odskok")
("translate" "p°eloºit")
("tree" "strom")
("tuple" "n-tice")
("turkish" "tureckı")
("tutorial" "pr·vodce za£áte£níka")
("type" "typ")
("type a latex command followed by" "napi²t¥ p°íkaz pro latex následovanı")
("type body" "napi²te t¥lo")
("type denominator" "napi²t¥ jmenovatel")
("type numerator" "napi²t¥ £itatel")
("type script" "napi²te skript")
("typesetted boxes" "sázení box·")
("typewriter" "psací stroj")
("typewriter small caps" "psací stroj kapitálky")
("typing a simple text" "psaní jednoduchého textu")
("typing simple texts" "psaní jednoduchıch text·")
("ugaritic" "ugaritic")
("ukrainian" "ukrajin²tina")
("undo" "zp¥t")
("undo last changes" "zp¥t poslední úpravy")
("up" "nahoru")
("update" "obnovit")
("update from web" "aktualizace z webu")
("update image links" "aktualizovat odkazy obrázk·")
("upper border" "horní okraj")
("use TeXmacs" "pouºívejte TeXmacs")
("use a black color" "pouºít £ernou barvu")
("use a blue color" "pouºít modrou barvu")
("use a bold font" "pouºít tu£né písmo")
("use a brown color" "pouºít hn¥dou barvu")
("use a calligraphic font" "pouºít kaligrafické písmo")
("use a green color" "pouºít zelenou barvu")
("use a grey color" "pouºít ²edou barvu")
("use a magenta color" "pouºít fialovou barvu")
("use a orange color" "pouºít oranºovou barvu")
("use a pink color" "pouºít r·ºovou barvu")
("use a red color" "pouºít £ervenou barvu")
("use a sans serif font" "pouºít bezpatkové písmo")
("use a typewriter font" "pouºít písmo psacího stroje")
("use a white color" "pouºít bílou barvu")
("use a yellow color" "pouºít ºlutou barvu")
("use blackboard bold font" "pouºít písmo blackboard")
("use bold font series" "pouºít tu£né písmo")
("use calligraphical font" "pouºít kaligrafické písmo")
("use footnote font size" "pouºít velikost písma poznámky pod £arou")
("use fraktur font" "pouºít písmo fraktur")
("use huge font size" "pouºít obrovské písmo")
("use italic font shape" "pouºít kurzívní písmo")
("use large font size" "pouºít v¥t²í písmo")
("use left hand column as border" "pouºít levı sloupec jako okraj")
("use medium font series" "pouºít polotu£né písmo")
("use normal font size" "pouºít st°ední písmo")
("use package" "pouºití balí£ku")
("use paragraph width" "pouºít ²í°ku odstavce")
("use really huge font size" "pouºít vskutku obrovské písmo")
("use right font shape" "pouºít písmo kurzívní vpravo")
("use right hand column as border" "pouºít pravı sloupec jako okraj")
("use roman font family" "pouºít písmo roman")
("use row above as border" "pouºít horní °ádek jako okraj")
("use row below as border" "pouºít spodní °ádek jako okraj")
("use sans serif font family" "pouºít bezpatkové písmo")
("use script font size" "pouºít velikost písma indexu")
("use slanted font shape" "pouºít sklon¥né písmo")
("use small capitals" "pouºít kapitálky")
("use small font size" "pouºít malé písmo")
("use small-caps font shape" "pouºít kapitálky")
("use the blackboard bold font" "pouºít tu£né písmo blackboard")
("use the fraktur font" "pouºít písmo fraktur")
("use tiny font font size" "pouºít mr¬avé písmo")
("use typewriter font family" "pouºít písmo psacího stroje")
("use very large font size" "pouºít velké písmo")
("user manual" "uºivatelská p°íru£ka")
("user provided icons" "uºivatelské ikony")
("value" "hodnota")
("variable" "prom¥nná")
("variant" "variant")
("vector" "vektor")
("verbatim" "verbatim")
("verse" "ver²")
("vertical" "svislá")
("vertical after" "svislá za")
("vertical before" "svislá p°ed")
("vertical cell alignment" "svislé zarovnání bu¬ky")
("vertical part" "svislá £ást")
("vertical position" "svislá pozice")
("vertical space" "svislá mezera")
("vertical table alignment" "svislé zarovnání tabulky")
("vertically align cell to the base" "zarovnat bu¬ku svisle na základnu")
("vertically center the cell" "vyst°edit bu¬ku svisle")
("very large" "velkı")
("very small" "malı")
("vietnamese" "vietnamskı")
("view" "pohled")
("visible" "viditelnı")
("warning" "varování")
("welcome" "vítejte")
("welcome to GNU TeXmacs" "Vítejte v GNU TeXmacs")
("what is new" "co je nového")
("when finished" "po ukon£ení")
("while" "while")
("white" "bílá")
("wide accent" "²irokı akcent")
("width" "²í°ka")
("width is exactly the specified width" "²í°ka je p°esn¥ podle zadání")
("width is maximum of specified width and box width" "²í°ka je maximum zadané ²í°ky a ²í°ky boxu")
("width is minimum of specified width and box width" "²í°ka je minimum zadané ²í°ky a ²í°ky boxu")
("width magnification" "roz²í°ení")
("window" "okno")
("window height" "vı²ka okna")
("window width" "²í°ka okna")
("windows key" "klávesa windows")
("with" "s")
("write a name" "pouºít kapitálky")
("write bold mathematics" "pouºít tu£né matematické písmo")
("write bold text" "pouºít tu£né písmo")
("write italic text" "pouºít kurzívní písmo")
("write sample text" "pouºít bezpatkové písmo")
("write strong text" "pouºít silné písmo")
("write typewriter text" "pouºít písmo psacího stroje")
("write verbatim text" "pouºít reºim verbatim")
("writing data converters" "tvorba konvertor· dat")
("writing your own style files" "tvorba va²ich vlastních soubor· styl·")
("yellow" "ºlutá")
("yes" "ano")
("you can also obtain" "m·ºe také získat")
("your document is back in its original state" "vá² dokument je op¥t v p·vodní stavu")
("your first interface" "va²e první rozhraní")
