("A modifier" "modificatore A")
("GNU" "GNU")
("H modifier" "modificatore H")
("LaTeX" "LaTeX")
("M modifier" "modificatore M")
("(Re)Build autocompletion index" "(Ri)Crea indice di completamento automatico")
("TeX" "TeX")
("a modifier" "modificatore A")
("a series" "serie a")
("a.C.M. computing class" "classe informatica A.C.M.")
("a.M.S. subject class" "classe tematica A.M.S.")
("abbreviated authors" "autori abbreviati")
("abbreviation" "abbreviazione")
("about" "informazioni su TeXmacs")
("about menu" "menu informazioni")
("above" "sopra")
("abstract" "riassunto")
("accent" "accento")
("accent above" "accento sopra")
("accent below" "accento sotto")
("accept" "accetta")
("accept all scripts" "accetta tutti gli script")
("accept during this pass" "accetta in questo passaggio")
("accept no scripts" "non accettare gli scripts")
("accept script" "accetta script")
("acknowledgment" "riconoscimento")
("acknowledgments" "riconoscimenti")
("acronym" "acronimo")
("action" "azione")
("activate" "attiva")
("activate hidden" "attiva nascosto")
("activate once" "attiva una volta")
("activation" "attivazione")
("active link types" "tipi di link attivi")
("acute" "acuto")
("add" "aggiungi")
("add abstract information" "aggiungi informazioni sul riassunto")
("add author information" "aggiungi informazioni sull'autore")
("add branch after" "aggiungi ramo dopo")
("add branch before" "aggiungi ramo prima")
("add other package" "aggiungi altro pacchetto")
("add package" "aggiungi pacchetto")
("add style package" "aggiungi pacchetto di stile")
("add switch after" "aggiungi switch dopo")
("add switch before" "aggiungi switch prima")
("add title information" "aggiungi informazioni sul titolo")
("addition" "aggiunta")
("address" "indirizzo")
("address block" "blocco indirizzo")
("adjust" "regola")
("adjust limits" "regola i limiti")
("advanced" "avanzato")
("advanced font customization" "personalizzazione avanzata dei caratteri")
("advanced layout features" "caratteristiche di impaginazione avanzate")
("affiliation" "affiliazione")
("after" "dopo")
("albanian" "albanese")
("algorithm" "algoritmo")
("algorithms" "algoritmi")
("align cell to the bottom" "allinea la cella sul fondo")
("align cell to the decimal comma" "allinea la cella alla virgola decimale")
("align cell to the decimal dot" "allinea la cella al punto decimale")
("align cell to the left" "allinea la cella a sinistra")
("align cell to the right" "allinea la cella a destra")
("align cell to the top" "alinea la cella in alto")
("align table at axis" "allinea tabella all'asse")
("align table at base of left column" "allinea la tabella alla base della colonna sinistra")
("align table at base of middle column" "allinea la tabella alla base della colonna centrale")
("align table at base of origin column" "allinea la tabella alla base della colonna d'origine")
("align table at base of right column" "allinea la tabella alla base della colonna di destra")
("align table at fraction bar height" "allinea la tabella all'altezza della linea di frazione")
("align table at the base of bottom row" "allinea la tabella alla base della riga inferiore")
("align table at the base of middle row" "allinea la tabella alla base della riga centrale")
("align table at the base of origin row" "allinea la tabella alla base della riga d'origine")
("align table at the base of top row" "allinea la tabella alla base della riga superiore")
("align table at the bottom" "allinea la tabella al fondo")
("align table at the center" "allinea la tabella al centro")
("align table at the horizontal center" "allinea la tabella al centro orizzontale")
("align table at the left" "allinea la tabella a sinistra")
("align table at the top" "allinea la tabella in alto")
("align table to the right" "allinea la tabella a destra")
("align text to the left" "allinea il testo a sinistra")
("align text to the right" "allinea il testo a destra")
("aligned" "allineato")
("alignment" "allineamento")
("all" "tutto")
("all cells" "tutte le celle")
("all data attached to this identity will be lost" "tutti i dati associati a questa identità andranno persi")
("all saved passphrases will be lost forever" "tutte le passphrase salvate andranno perse per sempre")
("allow" "permetti")
("allow for macro definitions in preamble" "permetti le definizioni di macro nel preambolo")
("allow multiple spaces" "permetti più spazi")
("allow spurious spaces" "permetti spazi spuri")
("allowed extension" "estensione permessa")
("allowed page height extension" "estensione permessa dell'altezza della pagina")
("allowed page height reduction" "riduzione permessa dell'altezza della pagina")
("allowed positions" "posizioni permesse")
("allowed reduction" "riduzione permessa")
("alpha release" "versione alfa")
("alpha transparency" "trasparenza alfa")
("also on paper" "anche su carta")
("alt key" "tasto Alt")
("alter" "altera")
("alternate" "alternativa")
("alternate except here" "alternativa tranne qui")
("alternate from here on" "alternativa da qui in poi")
("alternate only here" "alternativa solo qui")
("alternate until here" "alternativa fino a qui")
("alternative colors" "colori alternativi")
("alternative specification" "specifica alternativa")
("always" "sempre")
("american" "americano")
("amplified" "amplificato")
("ancient" "antico")
("and" "e")
("angular" "angolare")
("animate" "anima")
("animate object" "anima oggetto")
("animate objects" "anima oggetti")
("animated" "animato")
("animation" "animazione")
("animation toolbar" "barra degli strumenti animazione")
("annotate" "annota")
("answer" "risposta")
("answer field" "campo di risposta")
("answer to question" "risposta alla domanda")
("answers only" "solo risposte")
("any" "qualsiasi")
("appear" "fai apparire")
("appendix" "appendice")
("apply" "applica")
("apply macro" "applica macro")
("apply macro once" "applica macro una volta")
("approximate" "approssima")
("april" "aprile")
("arab" "arabo")
("arc" "arco")
("arc cosine" "arcocoseno")
("arc sine" "arcoseno")
("arc tangent" "arcotangente")
("archaic" "arcaico")
("architecture" "architettura")
("are you sure you want to delete collected public keys" "sei sicuro di voler eliminare le chiavi pubbliche raccolte")
("are you sure you want to delete selected public keys" "sei sicuro di voler eliminare le chiavi pubbliche selezionate")
("are you sure you want to delete selected secret keys" "sei sicuro di voler eliminare le chiavi segrete selezionate")
("are you sure you want to destroy the wallet" "sei sicuro di voler distruggere il portafoglio")
("argument" "argomento")
("arithmetic" "aritmetica")
("armenian" "armeno")
("arrow" "freccia")
("arrows" "frecce")
("article" "articolo")
("arxiv category" "categoria arxiv")
("as on paper" "come sul foglio")
("as visual grid" "come griglia visuale")
("aspect" "aspetto")
("assign" "assegna")
("at fraction bar height" "all'altezza della linea di frazione")
("at the baseline" "in linea con la base")
("at the bottom" "sul fondo")
("at the left" "a sinistra")
("at the middle" "al centro")
("at the right" "a destra")
("at the top" "in alto")
("attach" "collega")
("attach buffer to which project" "collega il buffer a quale progetto")
("attach master" "collega master")
("attached" "allegato")
("august" "agosto")
("author" "autore")
("authorize" "autorizza")
("auto" "auto")
("auto-save file" "file di salvataggio automatico")
("automatic" "automatico")
("automatic brackets" "parentesi automatiche")
("automatic content generation" "generazione automatica di contenuti")
("automatic program brackets" "parentesi automatiche nei programmi")
("automatic quotes" "virgolette automatiche")
("automatically close brackets" "chiudi automaticamente le parentesi")
("automatically generated content" "contenuto generato in modo automatico")
("automatically import bibliographies when opening files" "importa automaticamente le bibliografie all'apertura dei file")
("automatically remember all passphrases in the wallet" "ricorda automaticamente tutte le passphrase nel portafoglio")
("automatically save" "salva automaticamente")
("autosave" "salvataggio automatico")
("avoid spurious spaces" "evita spazi spuri")
("axiom" "assioma")
("axioms" "assiomi")
("axis" "asse")
("b series" "serie b")
("back" "indietro")
("background" "sfondo")
("background color" "colore di sfondo")
("background picture selector" "selettore di immagini di sfondo")
("backtrace errors" "errori di backtrace")
("backward replace" "sostituisci all'indietro")
("backward search" "cerca all'indietro")
("bad data format" "formato dei dati errato")
("bar" "barra")
("bard" "bardo")
("base" "base")
("base level" "livello della base")
("bashkirian" "bashkiriano")
("basic" "fondamentale")
("basic communication using pipes" "comunicazione di base tramite pipe")
("basic data types" "tipi fondamentali di dati")
("basic types" "tipi fondamentali")
("be useful" "rendersi utile")
("beamer formats" "formati beamer")
("beamer theme" "tema del proiettore")
("become a TeXmacs developer" "diventa uno sviluppatore TeXmacs")
("before" "prima")
("begin" "inizio")
("below" "sotto")
("beta release" "versione beta")
("bibTeX command" "comando bibTeX")
("bibliography" "bibliografia")
("bibliography file" "file della bibliografia")
("bibliography style" "stile della bibliografia")
("bidirectional" "bidirezionale")
("big" "grande")
("big figure" "figura grande")
("big operator" "operatore grande")
("big skip" "salto grande")
("big table" "tabella grande")
("binary operation" "operazione binaria")
("binary operator" "operatore binario")
("binary relation" "relazione binaria")
("bitmap resolution (dpi)" "risoluzione bitmap (dpi)")
("black" "nero")
("black floral I" "nero floreale I")
("black floral II" "nero floreale II")
("blackboard bold" "grassetto da lavagna")
("blackboard math" "matematica da lavagna")
("blackletter" "blackletter")
("blank column" "colonna vuota")
("blank row" "riga vuota")
("block" "blocco")
("block content" "contenuto del blocco")
("block of code" "blocco di codice")
("blue" "blu")
("blur" "sfoca")
("body" "corpo")
("bold" "grassetto")
("book" "libro")
("border" "bordo")
("both" "entrambi")
("both versions" "entrambe le versioni")
("bottom" "inferiore")
("bottom baseline" "linea di base inferiore")
("bottom border" "bordo inferiore")
("bottom cell border" "bordo inferiore della cella")
("bottom cell padding" "spaziatura inferiore della cella")
("bottom margin" "margine inferiore")
("bottom padding" "spaziatura inferiore")
("bottom table border" "bordo inferiore della tabella")
("bottom table padding" "spaziatura inferiore della tabella")
("box" "scatola")
("branch" "ramo")
("break" "interrompi")
("breaking" "interruzioni")
("breve" "breve")
("british" "britannico")
("brown" "marrone")
("browse" "naviga")
("browse back" "sfoglia indietro")
("browse forward" "sfoglia in avanti")
("browse modules documentation" "sfoglia la documentazione dei moduli")
("browse web" "naviga sul web")
("browser" "browser")
("buffer" "buffer")
("buffer management" "gestione buffer")
("buffer must be on disk" "il buffer deve essere su disco")
("buffer must have a name" "il buffer deve avere un nome")
("build directory" "crea directory")
("build directory in" "crea directory in")
("build link pages" "crea pagine di link")
("bulgarian" "bulgaro")
("bullet" "puntina")
("bullets" "puntine")
("busy" "occupato")
("by" "di")
("by typing" "scrivendo")
("bytes free" "byte liberi")
("bytes used" "byte usati")
("cJK spacing" "spaziatura cJK")
("calculus" "calcolo")
("calligraphic" "calligrafico")
("cancel" "cancella")
("cancelled" "cancellato")
("cannot download directory to file" "impossibile scaricare la directory nel file")
("cannot rename across different servers" "impossibile rinominare tra server diversi")
("cannot upload directory to file" "impossibile caricare la directory nel file")
("caps-lock key" "tasto Caps-lock")
("cartesian" "cartesiano")
("carved wood" "legno intagliato")
("case" "caso")
("case-insensitive search" "ricerca senza distinzione tra maiuscole e minuscole")
("categories" "categorie")
("category" "categoria")
("cc" "p.c.")
("cell" "cella")
("cell background color" "colore di sfondo della cella")
("cell border" "bordo della cella")
("cell height" "altezza della cella")
("cell operation mode" "modo operativo della cella")
("cell properties" "proprietà della cella")
("cell width" "larghezza della cella")
("cells" "celle")
("center" "centro")
("center text" "centra il testo")
("centered" "centrato")
("centered block" "blocco centrato")
("centered tabular" "tabella centrata")
("chalk" "gesso")
("change border of cell" "modifica il bordo della cella")
("change cell operation mode" "cambia il modo operativo della cella")
("change default unit" "cambia unitÃČÂă predefinita")
("change log" "change log")
("change passphrase" "cambia passphrase")
("change permissions" "modifica autorizzazioni")
("change step-size" "modifica lunghezza dell'incremento")
("change tags" "cambia tag")
("change the TeXmacs preferences" "modifica le preferenze di TeXmacs")
("change the border of the table" "cambia il bordo della tabella")
("change the style of mathematical formulas" "cambia lo stile delle formule matematiche")
("change wallet passphrase" "cambia passphrase del portafoglio")
("changes" "cambiamenti")
("chapter" "capitolo")
("character contraction" "contrazione del carattere")
("character encoding" "codifica dei caratteri")
("character expansion" "espansione del carattere")
("check" "controlla")
("check exported Pdf files for correctness" "controlla la correttezza dei file Pdf esportati")
("check for automatic updates" "controlla aggiornamenti automatici")
("check for updates" "controlla aggiornamenti")
("check text for spelling errors" "controllo ortografico")
("chinese" "cinese")
("choice" "scelta")
("choose background" "scegli sfondo")
("choose color" "scegli il colore")
("cipher algorithm for passphrase encryption" "algoritmo di cifratura per crittare la passphrase")
("circle" "cerchio")
("citation" "citazione")
("cite" "cita")
("class" "classe")
("classification" "classificazione")
("clean slate" "tabula rasa")
("clear" "elimina")
("clear all fields" "cancella tutti i campi")
("clear local information" "cancella le informazioni locali")
("clear menu" "cancella menu")
("clear selection" "elimina selezione")
("clear undo history" "cancella cronologia annullamenti")
("click Ok button twice to discard this warning" "fai clic due volte sul pulsante OK per eliminare questo avviso")
("clip" "ancora")
("clipboard image format" "formato immagine degli appunti")
("clipped" "ancorato")
("clipped and magnified" "ancorato e ampliato")
("clipped and resized" "ancorato e ridimensionato")
("clone" "duplica")
("clone window" "duplica la finestra")
("close" "chiudi")
("close TeXmacs" "chiudi TeXmacs")
("close animation tool" "chiudi lo strumento di animazione")
("close buffer" "chiudi il buffer")
("close document" "chiudi il documento")
("close program" "chiudi il programma")
("close replace tool" "chiudi lo strumento di sostituzione")
("close search tool" "chiudi lo strumento di ricerca")
("close session" "chiudi la sessione")
("close spell tool" "strumento il controllo ortografico")
("close translations to rebuild" "chiudi le traduzioni per ricostruire")
("close window" "chiudi la finestra")
("closed bezier" "bezier chiusa")
("closed curve" "curva chiusa")
("closed smooth" "chiusa liscia")
("closed spline" "spline chiusa")
("closing" "chiusura")
("closing style" "stile di chiusura")
("cluster by affiliation" "raggruppa per affiliazione")
("code" "codice")
("collected keys" "chiavi raccolte")
("color" "colore")
("color of the axes" "colore degli assi")
("color of the subunits" "colore delle subunità")
("color of the units" "colore delle unità")
("colors" "colori")
("column" "colonna")
("column contains glued items" "la colonna contiene elementi appiccicati")
("column to the left" "colonna a sinistra")
("column to the right" "colonna a destra")
("columns" "colonne")
("column separation" "separazione delle colonne")
("commit file" "file di commit")
("common" "comune")
("common formats" "formati comuni")
("commutative diagram" "diagramma commutativo")
("compact" "compatto")
("compactification" "compattificazione")
("compactify" "compatta")
("compare" "confronta")
("compare with" "confronta con")
("compatibility with other formats" "compatibilità con altri formati")
("compile article" "compila articolo")
("compile book" "compila libro")
("compile buffer" "compila il buffer")
("compile project" "compila il progetto")
("complete bibliographic reference" "riferimento bibliografico completo")
("completion" "completamento")
("complex" "complesso")
("complex actions" "azioni complesse")
("compose" "componi")
("compound" "composto")
("compress" "comprimi")
("compress into toolbar" "comprimi nella barra degli strumenti")
("compressed" "compresso")
("conceal" "nascondi")
("concrete" "concreto")
("condensed" "condensato")
("condition" "condizione")
("configuration" "configurazione")
("configure look and feel" "configura aspetto grafico")
("confirm collected public key deletion" "conferma l'eliminazione della chiave pubblica raccolta")
("confirm database entry" "conferma immissione database")
("confirm entry" "conferma immissione")
("confirm public key deletion" "conferma l'eliminazione della chiave pubblica")
("confirm secret key deletion" "conferma cancellazione chiave segreta")
("confirm selected database entries" "conferma voci di database selezionate")
("confirm selected entries" "conferma voci selezionate")
("confirm wallet destruction" "conferma la distruzione del portafoglio")
("conjecture" "congettura")
("conjectures" "congetture")
("conservative conversion options" "opzioni di conversione conservativa")
("consoles" "console")
("constellation" "costellazione")
("contact" "contatto")
("content" "contenuto")
("content tag" "content tag")
("context aids" "aiuti contestuali")
("context dependent icons" "icone dipendenti dal contesto")
("contextual hints" "suggerimenti contestuali")
("continuation of" "continuazione di")
("continue" "continua")
("continued fraction" "frazione continua")
("contour" "contorno")
("contract logarithms" "semplifica i logaritmi")
("contribute" "contribuisci")
("control flow" "flusso di controllo")
("control the evaluation of expressions" "controlla la valutazione delle espressioni")
("convention" "convenzione")
("conventions" "convenzioni")
("convert" "converti")
("converters" "convertitori")
("converters to other data formats" "convertitori per altri formati")
("convertible" "convertibile")
("copy" "copia")
("copy new objects to all frames" "copia nuovi oggetti in tutti i frame")
("copy new objects to previous frames" "copia nuovi oggetti nei frame precedenti")
("copy new objects to subsequent frames" "copia nuovi oggetti nei frame successivi")
("copy text" "copia testo")
("copy to" "copia in")
("copy to all frames after" "copia in tutti i frame successivi")
("copy to all frames before" "copia in tutti i frame precedenti")
("copy to all other frames" "copia in tutti gli altri frame")
("copying" "copiando")
("copyright" "copyright")
("cork charset with TeX catcode definition in preamble" "caratteri Cork (T1) con definizione del catcode TeX nel preambolo")
("cork with catcodes" "Cork (T1) con catcode")
("corollaries" "corollari")
("corollary" "corollario")
("correct" "correggi")
("correct all" "correggi tutto")
("correct formula" "correggi formula")
("correct manually" "correggi manualmente")
("correct mathematical formulas" "correggi formule matematiche")
("correct text" "correggi il testo")
("correction" "correzione")
("cosine" "coseno")
("count characters" "conta i caratteri")
("count lines" "conta le righe")
("count words" "conta le parole")
("create a new document" "crea un nuovo documento")
("create link" "crea collegamento")
("create preamble" "crea preambolo")
("create remote account" "crea account remoto")
("create remote directory" "crea directory remota")
("create remote file" "crea file remoto")
("create subprogram" "crea sottoprogramma")
("create subsession" "crea sottosessione")
("create table macro" "crea macro tabella")
("create web site" "crea sito web")
("creating new account" "creazione di un nuovo account")
("creating technical pictures" "creazione di immagini tecniche")
("crop" "ritaglio")
("crop marks" "crocini di registro")
("cross" "croce")
("crossed boxes" "scatole incrociate")
("crossed circles" "cerchi incrociati")
("current user version" "versione dell'utente attuale")
("current version" "versione attuale")
("cursor" "cursore")
("cursors" "cursori")
("curve" "curva")
("curve intersections" "intersezioni della curva")
("curve points" "punti della curva")
("custom tab" "tabulazione personalizzata")
("customizations" "personalizzazioni")
("customizing TeXmacs" "personalizzare TeXmacs")
("customizing and extending the user interface" "personalizzazione ed estensione dell'interfaccia utente")
("customizing the TeXmacs styles" "personalizzare gli stili di TeXmacs")
("cut" "taglia")
("cut text" "taglia testo")
("cut to" "taglia in")
("cyan" "ciano")
("cypriot" "cipriota")
("cyrillic" "cirillico")
("cyrillic input method" "metodo di input cirillico")
("cyrillic italic right" "cirillico corsivo a destra")
("czech" "ceco")
("dancers" "ballerini")
("danish" "danese")
("dark grey" "grigio scuro")
("dash" "trattino")
("dashes" "trattini")
("data" "dati")
("data conversion" "conversione di dati")
("data format" "formato dei dati")
("database entry" "voce del database")
("database tool" "strumento database")
("database toolbar" "barra degli strumenti database")
("date" "data")
("deactivate" "disattiva")
("deactivate once" "disattiva una volta")
("deactivate table" "disattiva tabella")
("dead" "morto")
("debugging console" "console di debug")
("debugging tool" "strumento di debug")
("december" "dicembre")
("decimal comma" "virgola decimale")
("decimal dot" "punto decimale")
("decomposed" "decomposto")
("decorate atoms" "decora atomi")
("decorated" "decorato")
("decorated wood" "legno decorato")
("decorative" "decorativo")
("decrease size" "riduci dimensioni")
("decrypt" "decritta")
("decrypted" "decrittato")
("decryption" "deccrittazione")
("default" "predefinito")
("default padding" "spaziatura predefinita")
("default size" "dimensione predefinita")
("definition" "definizione")
("definitions" "definizioni")
("degrade" "degrada")
("degraded" "degradato")
("delete" "cancella")
("delete column" "cancella colonna")
("delete documentation cache" "svuota cache documentazione")
("delete entries" "elimina voci")
("delete link" "elimina collegamento")
("delete row" "cancella riga")
("delete selected entries in wallet" "elimina le voci selezionate nel portafoglio")
("delete user identity" "elimina identità utente")
("deleted" "cancellato")
("denominator" "denominatore")
("describe" "descrivi")
("describe tag" "descrivi tag")
("description" "descrizione")
("destination" "destinazione")
("destroy" "distruggi")
("detach" "scollega")
("detach master" "scollega master")
("detailed" "dettagliato")
("detailed menus" "menu dettagliati")
("details in menus" "dettagli nei menu")
("determinant" "determinante")
("determine margins from text width" "determina i margini dalla larghezza del testo")
("devangari" "devanagari")
("developer" "sviluppatore")
("developer tool" "strumento per gli sviluppatori")
("developers guide" "guida per gli sviluppatori")
("device" "dispositivo")
("diamond" "diamante")
("differentiate" "differenzia")
("digital" "digitale")
("dilate" "dilata")
("direction of progression" "direzione della progressione")
("direction of translation" "direzione della traslazione")
("directory" "directory")
("disable" "disabilita")
("disable coloring on paper" "disabilita colorazione su carta")
("disable encryption" "disabilita crittografia")
("disable first indentation" "disabilita prima indentazione")
("disable first indentation after" "disabilita prima indentazione successiva")
("disable first indentation before" "disabilita prima indentazione precedente")
("disable indentation" "disabilita indentazione")
("disable indentation after" "disabilita indentazione successiva")
("disable indentation before" "disabilita indentazione precedente")
("disable last indentation" "disabilita l'ultima indentazione")
("disable last indentation after" "disabilita l'ultima indentazione successiva")
("disable last indentation before" "disabilita l'ultima indentazione precedente")
("disabled" "disabilitato")
("disallow" "proibisci")
("disappear" "fai sparire")
("disk" "disco")
("display style" "stile di visualizzazione")
("displayed formula" "formula visualizzata")
("dissociate joined cells" "separa celle unite")
("distill encapsulated Pdf files" "distilla file Pdf incapsulati")
("distort" "distorci")
("distorted" "distorto")
("distribute unused space" "distribuisci spazio inutilizzato")
("div" "div")
("division" "divisione")
("do not remap" "non rimappare")
("document" "documento")
("document colors" "colori del documento")
("document font selector" "selettore font del documento")
("document format" "formato del documento")
("document language" "lingua del documento")
("document metadata" "metadati del documento")
("document page format" "formato pagina del documento")
("document paragraph format" "formato paragrafo del documento")
("document source tree preferences" "preferenze dell'albero sorgente del documento")
("document style" "stile del documento")
("document styles" "stili di documento")
("document updates run" "aggiorna il documento")
("documentation" "documentazione")
("documents are trees" "i documenti sono alberi")
("documents in separate windows" "documenti in finestre separate")
("dot" "punto")
("dots" "puntini")
("double stroke" "tratto doppio")
("down" "sotto")
("download" "scarica")
("download file or directory" "scarica file o directory")
("downwards" "verso il basso")
("dpi" "dpi")
("dragging" "trascinamento")
("draw" "disegna")
("draw graphics" "disegna grafici")
("draw image" "disegna immagine")
("draw over" "disegna sopra")
("draw over selection" "disegna sopra la selezione")
("due to" "dovuto a")
("duplicate" "duplica")
("dutch" "olandese")
("dynamic" "dinamico")
("dynamic libraries" "librerie dinamiche")
("edit" "modifica")
("editing tools" "strumenti di editing")
("email" "email")
("emphasize" "enfatizza")
("emphasize text" "scrivi testo enfatizzato")
("empty box" "box vuoto")
("enable first indentation" "abilita prima indentazione")
("enable first indentation after" "abilita prima indentazione successiva")
("enable first indentation before" "abilita prima indentazione precedente")
("enable indentation" "abilita indentazione")
("enable indentation after" "abilita indentazione precedente")
("enable indentation before" "abilita indentazione successiva")
("enable last indentation" "abilita l'ultima indentazione")
("enable last indentation after" "abilita l'ultima indentazione successiva")
("enable last indentation before" "abilita l'ultima indentazione precedente")
("encl" "encl")
("end" "fine")
("english" "inglese")
("enter a title" "inserisci un titolo")
("enumerate" "lista numerata")
("enumerate|Alpha" "numerazione|Alfa")
("enumerate|Roman" "numerazione|Romano")
("enumerate|alpha" "numerazione|alfa")
("enumerate|roman" "numerazione|romano")
("env" "env")
("environment" "ambiente")
("epilogue" "epilogo")
("equal" "uguale")
("equation" "equazione")
("equations" "equazioni")
("equivalent for" "equivalente per")
("error" "errore")
("esperanto" "esperanto")
("etruscan" "etrusco")
("evaluate" "valuta")
("evaluate scheme expression" "valuta espressione scheme")
("even page footer" "piè di pagina (pagine pari)")
("even page header" "intestazione (pagine pari)")
("even page margin" "margine pagine pari")
("even page text" "testo (pagine pari)")
("exact horizontal" "orizzontale esatta")
("exact mode" "modo esatto")
("exam" "esame")
("example" "esempio")
("exclusive" "esclusivo")
("exclusive or" "o esclusivo")
("executable" "eseguibile")
("execute" "esegui")
("execute a TeXmacs command" "esegui un comando TeXmacs")
("execute system command" "esegui un comando di sistema")
("executive" "esecutivo")
("exercise" "esercizio")
("expand" "espandi")
("explained" "spiegato")
("export" "esporta")
("export as" "esporta come")
("extend or normal" "esteso o normale")
("extern" "esterno")
("extra" "extra")
("extract format" "estrai formato")
("family" "famiglia")
("february" "febbraio")
("figure" "figura")
("file" "file")
("file name" "nome del file")
("file not found" "file non trovato")
("find next match" "trova la prossima occorrenza")
("find text" "trova testo")
("finnish" "finlandese")
("first contact" "primo contatto")
("first indentation" "prima indentazione")
("first item" "primo elemento")
("first page" "prima pagina")
("first start" "primo avvio")
("flat" "piatto")
("flexibility" "flessibilità")
("flexibility factor for vertical spacing" "fattore di flessibilità per la spaziatura verticale")
("floating figure" "figura fluttuante")
("floating object" "oggetto fluttuante")
("floating table" "tabella fluttuante")
("fold" "arrotola")
("folded" "arrotolato")
("font" "carattere")
("font base size" "dimensione di base del carattere")
("font dpi" "risoluzione del carattere (dpi)")
("font family" "famiglia del carattere")
("font name" "nome del carattere")
("font series" "serie del carattere")
("font shape" "forma del carattere")
("font size" "dimensione del carattere")
("font variant" "variante del carattere")
("fonts" "tipi di carattere")
("footer" "piè di pagina")
("footnote" "nota a piè di pagina")
("for" "per")
("foreground" "primo piano")
("foreign" "straniero")
("format" "formato")
("formatted date" "data formattata")
("formula" "formula")
("formula style" "stile della formula")
("forward replace" "sostituisci in avanti")
("forward search" "cerca in avanti")
("fraction" "frazione")
("french" "francese")
("full manuals" "manuali completi")
("function" "funzione")
("further customization" "ulteriore personalizzazione")
("future changes" "cambiamenti futuri")
("gNU TeXmacs comes without any form of legal warranty" "gNU TeXmacs viene distribuito senza alcuna forma di garanzia legale")
("gNU TeXmacs falls under the GNU general public license" "gNU TeXmacs è distribuito sotto i termini della GNU general public license (GNU GPL)")
("general architecture of TeXmacs" "architettura generale di TeXmacs")
("general negation" "negazione generale")
("generating font file" "sto generando il file del font")
("generic" "generico")
("georgian" "georgiano")
("german" "tedesco")
("getting started" "primi passi")
("glossary" "glossario")
("glossary entry" "voce del glossario")
("glue" "appiccica")
("glue decorations" "appiccica le decorazioni")
("go" "vai")
("gothic" "gotico")
("graphical interface" "interfaccia grafica")
("grave" "grave")
("greater" "maggiore")
("greater or equal" "maggiore o uguale")
("greek" "greco")
("greek letter" "lettera greca")
("green" "verde")
("grey" "grigio")
("group" "gruppo")
("happy typing" "buona scrittura")
("has been aborted" "è stato interrotto")
("has completed its task" "ha completato il suo compito")
("hat" "cappello")
("header" "intestazione")
("header and footer" "intestazione e piè di pagina")
("hebrew" "ebraico")
("height" "altezza")
("height is exactly the specified height" "l'altezza è esattamente quella specificata")
("height is maximum of specified height and box height" "l'altezza è la massima tra l'altezza specificata e l'altezza del box")
("height is minimum of specified height and box height" "l'altezza è la minima tra l'altezza specificata e l'altezza del box")
("height magnification" "moltiplicatore dell'altezza")
("help" "aiuto")
("help me" "aiutami")
("help us" "aiutaci")
("here" "qui")
("home" "inizio")
("horizontal" "orizzontale")
("horizontal cell alignment" "allineamento orizzontale della cella")
("horizontal ink separation" "separazione orizzontale dell'inchiostro")
("horizontal part" "parte orizzontale")
("horizontal position" "posizione orizzontale")
("horizontal space" "spazio orizzontale")
("horizontal table alignment" "allineamento orizzontale della tabella")
("horizontally align cell to the base" "allinea la cella orizzontalmente con la base")
("horizontally center the cell" "centra la cella orizzontalmente")
("how much longer may pages become" "quanto più lunghe potrebbero diventare le pagine")
("how much shorter may pages become" "quanto più corte potrebbero diventare le pagine")
("huge" "enorme")
("hungarian" "ungherese")
("hyperlink" "collegamento ipertestuale")
("hyphenation" "sillabazione")
("icelandic" "islandese")
("if" "se")
("image" "immagine")
("image links" "inserisci un'immagine (collegamento)")
("implementation" "implementazione")
("import" "importa")
("improving the current implementation" "migliorare l'implementazione attuale")
("inactive" "inattivo")
("include" "includi")
("include a document" "includi un documento")
("include a file" "includi un file")
("include file" "includi file")
("inclusion into TeXmacs" "inclusione in TeXmacs")
("inclusions" "inclusioni")
("indent" "indenta")
("indentation flag" "simbolo di indentazione")
("index" "indice analitico")
("index entry" "voce dell'indice analitico")
("index level" "livello dell'indice analitico")
("insert" "inserisci")
("insert Pr" "inserisci Pr")
("insert a TeXmacs symbol" "inserisci un simbolo di TeXmacs")
("insert a big operator" "inserisci un operatore grande")
("insert a binary operation" "inserisci un'operazione binaria")
("insert a binary relation" "inserisci una relazione binaria")
("insert a blackboard bold character" "inserisci un carattere lavagna grassetto")
("insert a bold calligraphic character" "inserisci un carattere calligrafico grassetto")
("insert a bold character" "inserisci un carattere grassetto")
("insert a calligraphic character" "inserisci un carattere calligrafico")
("insert a fraction" "inserisci una frazione")
("insert a fraktur character" "inserisci un carattere fraktur")
("insert a greek character" "inserisci un carattere greco")
("insert a large left delimiter" "inserisci un delimitatore sinistro grande")
("insert a large right delimiter" "inserisci un delimitatore destro grande")
("insert a large separator" "inserisci un separatore grande")
("insert a left subscript" "inserisci pedice sinistro")
("insert a link" "inserisci un collegamento")
("insert a miscellaneous symbol" "inserisci un simbolo (altro...)")
("insert a new branch" "inserisci un nuovo ramo")
("insert a new item" "inserisci un nuovo elemento")
("insert a picture" "inserisci un'immagine")
("insert a square root" "inserisci una radice quadrata")
("insert a table" "inserisci una tabella")
("insert a table or a matrix" "inserisci una tabella o una matrice")
("insert an" "inserisci un/a")
("insert an accent" "inserisci un accento")
("insert an arrow" "inserisci una freccia")
("insert an environment" "inserisci un nuovo ambiente")
("insert an n" "inserisci un/a n")
("insert appendix" "inserisci appendice")
("insert arccos" "inserisci arccos")
("insert arcsin" "inserisci arcsin")
("insert arctan" "inserisci arctan")
("insert arg" "inserisci arg")
("insert argument" "inserisci argomento")
("insert automatically generated content" "inserisci contenuto generato automaticamente")
("insert big contour integral" "inserisci integrale curvilineo grande")
("insert big coproduct" "inserisci coproduttoria grande")
("insert big direct sum" "inserisci somma diretta grande")
("insert big dotted point" "inserisci punto-prodotto grande")
("insert big integral" "inserisci integrale grande")
("insert big intersection" "inserisci intersezione grande")
("insert big logical and" "inserisci AND logico grande")
("insert big logical or" "inserisci OR logico grande")
("insert big product" "inserisci produttoria grande")
("insert big square union" "inserisci unione quadrata grande")
("insert big summation" "inserisci grande sommatoria")
("insert big tensor product" "inserisci prodotto tensoriale grande")
("insert big union" "inserisci unione grande")
("insert big union sum" "inserisci somma unione grande")
("insert big vertical space" "inserisci spazio verticale grande")
("insert chapter" "inserisci capitolo")
("insert column" "inserisci colonna")
("insert column to the left" "inserisci colonna a sinistra")
("insert column to the right" "inserisci colonna a destra")
("insert cos" "inserisci cos")
("insert cosh" "inserisci cosh")
("insert cot" "inserisci cot")
("insert coth" "inserisci coth")
("insert csc" "inserisci csc")
("insert deg" "inserisci deg")
("insert det" "inserisci det")
("insert dim" "inserisci dim")
("insert dollar" "inserisci dollaro")
("insert equation" "inserisci equazione")
("insert executable markup" "inserisci marcatura eseguibile")
("insert exp" "inserisci exp")
("insert footnote" "inserisci nota a piè di pagina")
("insert formula" "inserisci formula")
("insert gcd" "inserisci mcd")
("insert hom" "inserisci hom")
("insert horizontal interword space" "inserisci spazio orizzontale tra le parole")
("insert image" "inserisci immagine")
("insert inactive markup" "inserisci marcatura inattiva")
("insert inf" "inserisci inf")
("insert ker" "inserisci ker")
("insert lg" "inserisci lg")
("insert lim" "inserisci lim")
("insert liminf" "inserisci liminf")
("insert limsup" "inserisci limsup")
("insert ln" "inserisci ln")
("insert log" "inserisci log")
("insert mathematics" "inserisci matematica")
("insert max" "inserisci max")
("insert medium horizontal space" "inserisci spazio orizzontale medio")
("insert medium vertical space" "inserisci spazio verticale medio")
("insert min" "inserisci min")
("insert negative horizontal space" "inserisci spazio orizzontale negativo")
("insert new item or number" "inserisci nuovo elemento o numero")
("insert new rows or columns" "inserisci nuove righe o colonne")
("insert or delete rows or columns" "inserisci o cancella righe o colonne")
("insert row" "inserisci riga")
("insert row above" "inserisci riga sopra")
("insert row below" "inserisci riga sotto")
("insert sec" "inserisci sec")
("insert section" "inserisci sezione")
("insert sharp" "inserisci diesis")
("insert sin" "inserisci sin")
("insert sinh" "inserisci sinh")
("insert small horizontal space" "inserisci spazio orizzontale piccolo")
("insert small vertical space" "inserisci spazio verticale piccolo")
("insert structural markup" "inserisci marcatura strutturale")
("insert subsection" "inserisci sotto-sezione")
("insert subsubsection" "inserisci sotto-sotto-sezione")
("insert sup" "inserisci sup")
("insert tan" "inserisci tan")
("insert tanh" "inserisci tanh")
("insert thick horizontal space" "inserisci spazio orizzontale spesso")
("interfacing" "interfacciare")
("interfacing TeXmacs with other systems" "interfacciare TeXmacs con altri sistemi")
("interjection" "interiezione")
("interline separation" "separazione interlinea")
("interline space" "spaziatura interlinea")
("internationalization" "internazionalizzazione")
("interparagraph space" "spaziatura tra paragrafi")
("interrupt execution" "interrompi esecuzione")
("introduction" "introduzione")
("invisible" "invisibile")
("invisible citation" "citazione invisibile")
("irish" "irlandese")
("is running" "è in esecuzione")
("is tuple" "è una tupla")
("ispell does not respond" "ispell non risponde")
("ispell is already busy" "ispell è già in esecuzione")
("italian" "italiano")
("italic" "corsivo")
("italic right" "corsivo a destra")
("itemize" "lista puntata")
("january" "gennaio")
("japanese" "giapponese")
("july" "luglio")
("june" "giugno")
("justified" "giustificato")
("justify text" "giustifica il testo")
("key" "chiave")
("keyboard" "tastiera")
("keyboard equivalent" "equivalente da tastiera")
("keyboard modifiers" "modificatori da tastiera")
("keyboard shortcut" "scorciatoia da tastiera")
("keymaps" "mappe di tastiera")
("keyword" "parola chiave")
("keywords" "parole chiave")
("kill" "uccidi")
("known bugs" "bug noti")
("label" "etichetta")
("landscape" "orizzontale")
("language" "lingua")
("large" "grande")
("large closing bracket" "parentesi chiusa grande")
("large delimiter" "delimitatore grande")
("large opening bracket" "parentesi aperta grande")
("large separator" "separatore grande")
("last indentation" "ultima indentazione")
("last page" "ultima pagina")
("latex command" "comando LaTeX")
("latin" "latino")
("layout" "impaginazione")
("left" "sinistra")
("left border" "bordo sinistro")
("left margin" "margine sinistro")
("left padding" "spaziatura sinistra")
("left prime" "primo a sinistra")
("left aligned" "allineato a sinistra")
("left slanted" "inclinato a sinistra")
("left subscript" "pedice a sinistra")
("left superscript" "apice a sinistra")
("left surrounding" "surrounding a sinistra")
("legal" "legale")
("lemma" "lemma")
("length" "lunghezza")
("less" "minore")
("less or equal" "minore o uguale")
("letter" "lettera")
("license" "licenza")
("light" "leggero")
("limitations" "limitazioni")
("limits" "limiti")
("line" "linea")
("line break" "interruzione di riga")
("line stretch" "elasticità della linea")
("link" "collegamento")
("link image" "inserisci immagine (collegamento)")
("list" "lista")
("list of figures" "lista delle figure")
("list of tables" "lista delle tabelle")
("load" "carica")
("load LaTeX file" "carica file LaTeX")
("load TeX file" "carica file TeX")
("load TeXmacs file" "carica file TeXmacs")
("load TeXmacs style file" "carica file di stile di TeXmacs")
("load a file" "carica un file")
("load buffer" "carica buffer")
("load file" "carica file")
("load html file" "carica file html")
("load image" "carica immagine")
("load in new window" "carica in una nuova finestra")
("load latex file" "carica file latex")
("load more recent autosave file" "carica ultimo file salvato automaticamente")
("load tex file" "carica file tex")
("load verbatim file" "carica file di testo semplice")
("loaded" "caricato")
("long" "lungo")
("look and feel" "aspetto")
("look up" "cerca")
("lower border" "bordo inferiore")
("macro" "macro")
("magenta" "magenta")
("magic" "magico")
("magnification" "ingrandimento")
("magnified" "ingrandito")
("main" "principale")
("main icon bar" "barra delle icone principale")
("major changes" "cambiamenti principali")
("make a page insertion" "fai un inserimento di pagina")
("make a subscript" "crea un pedice")
("make a superscript" "crea un apice")
("make acute" "crea un acuto")
("make bar" "crea una barra")
("make check" "crea controllo")
("make fraction" "crea frazione")
("make grave" "crea grave")
("make hat" "crea cappello")
("make label" "crea etichetta")
("make negation" "crea negazione")
("make page reference" "crea referenza ad una pagina")
("make reference" "crea referenza")
("make square root" "crea radice quadrata")
("make tilde" "crea tilde")
("make title" "crea titolo")
("make vector" "crea vettore")
("making donations" "come fare donazioni")
("manual" "manuale")
("map to" "rimappa in")
("march" "marzo")
("margins" "margini")
("margins as on paper" "margini come sul foglio")
("master" "master")
("master file" "file master")
("math" "matematica")
("math font" "carattere matematico")
("math font family" "famiglia del carattere matematico")
("math font series" "serie del carattere matematico")
("math font shape" "forma del carattere matematico")
("mathematical" "matematico")
("mathematical formulas" "formule matematiche")
("mathematical typesetting" "composizione tipografica matematica")
("mathematics" "matematica")
("matrix" "matrice")
("maximal number of columns" "numero massimo di colonne")
("maximal number of rows" "numero massimo di righe")
("maximum mode" "modo massimo")
("may" "maggio")
("medium" "medio")
("medium skip" "salto medio")
("meminfo" "meminfo")
("merge" "unisci")
("messy" "confusa")
("meta key" "tasto Meta")
("middle" "mediano")
("minimal number of columns" "numero minimo di colonne")
("minimal number of rows" "numero minimo di righe")
("minimum mode" "modo minimo")
("minus" "meno")
("miscellaneous" "miscellanea")
("mod" "mod")
("mode" "modo")
("modifier" "modificatore")
("modify cell alignment" "modifica l'allineamento della cella")
("modify cell border" "modifica il bordo della cella")
("modify cell padding" "modifica la spaziatura della cella")
("modify cell size" "modifica le dimensioni della cella")
("modify table border" "modifica il bordo della tabella")
("modify table padding" "modifica la spaziatura della tabella")
("mongolian" "mongolo")
("more information about GNU TeXmacs can be found in the help" "maggiori informazioni su GNU TeXmacs possono essere trovate nel menu aiuto")
("mosaic" "mosaico")
("move down" "sposta in basso")
("move object" "sposta oggetto")
("move to the right when finished" "muovi a destra quando hai finito")
("move up" "muovi in alto")
("n-th" "ennesima")
("n-th root" "radice ennesima")
("name" "nome")
("negation" "negazione")
("new" "nuovo")
("new buffer" "nuovo buffer")
("new column" "nuova colonna")
("new item" "nuovo elemento")
("new line" "nuova linea")
("new number" "nuovo numero")
("new page" "nuova pagina")
("new page before" "nuova pagina prima")
("new paragraph" "nuovo paragrafo")
("new roman" "new roman")
("new row" "nuova riga")
("new table" "nuova tabella")
("next line" "prossima linea")
("no" "no")
("no changes need to be saved" "non ci sono cambiamenti da salvare")
("no dictionary for" "non c'è un dizionario per")
("no first indentation" "nessuna prima indentazione")
("no indentation" "nessuna indentazione")
("no last indentation" "nessuna ultima indentazione")
("no line break" "nessuna interruzione di riga")
("no matches found" "non sono stati trovati risultati")
("no more matches for" "non ci sono altri risultati per la ricerca di")
("no more redo information available" "non ci sono più informazioni per rifare")
("no more undo information available" "non ci sono più informazioni per annullare'")
("no name" "senza nome")
("no page break after" "nessuna interruzione di pagina dopo")
("no page break before" "nessuna interruzione di pagina prima")
("no spelling errors found in text" "non sono stati trovati errori di ortografia nel testo")
("no style" "nessuno stile")
("none" "nessuno")
("normal" "normale")
("norwegian" "norvegese")
("not" "no")
("not equal" "non uguale")
("not found" "non trovato")
("notation" "notazione")
("note" "nota")
("november" "novembre")
("number" "numero")
("number equation" "equazione numerata")
("number of columns" "numero di colonne")
("numbered equation" "equazione numerata")
("numbered equations" "equazioni numerate")
("numerator" "numeratore")
("numeric" "numerico")
("objectives" "obiettivi")
("occurrences" "occorrenze")
("october" "ottobre")
("odd page footer" "piè di pagina (pagine dispari)")
("odd page header" "intestazione (pagine dispari)")
("odd page margin" "margine di pagine dispari")
("odd page text" "testo (pagine dispari)")
("off" "disattivato")
("ok" "ok")
("old english" "inglese antico")
("old slavonic" "slavo antico")
("old style" "vecchio stile")
("on" "attivato")
("on cells" "sulle celle")
("on columns" "sulle colonne")
("on entire table" "su tutta la tabella")
("on rows" "sulle righe")
("one spelling error has been corrected" "un errore di ortografia è stato corretto")
("online documentation" "documentazione in linea")
("online help" "aiuto in linea")
("open" "apri")
("open a new buffer" "apri un nuovo buffer")
("open new window" "apri una nuova finestra")
("opening" "apertura")
("operation on named selection" "operazione sulla selezione indicata")
("operation on primary selection" "operazione sulla selezione primaria")
("operation on secondary selection" "operazione sulla selezione secondaria")
("operation on ternary selection" "operazione sulla selezione terziaria")
("optical" "ottica")
("option" "opzione")
("options" "opzioni")
("or" "o")
("orange" "arancione")
("orientation" "orientazione")
("origin" "origine")
("original welcome message" "messaggio originale di benvenuto")
("other" "altro")
("other pages" "altre pagine")
("other projects" "altri progetti")
("other style" "altri stili")
("outlined roman" "outlined roman")
("over" "diviso")
("padding" "spaziatura")
("page" "pagina")
("page bottom margin" "margine inferiore di pagina")
("page break" "interruzione di pagina")
("page break before" "interruzione di pagina prima")
("page height" "altezza della pagina")
("page insertion" "inserimento di pagina")
("page layout" "imaginazione della pagina")
("page number text" "testo del numero di pagina")
("page numbering" "numerazione di pagina")
("page reference" "referenza di pagina")
("page right margin" "margine destro della pagina")
("page top margin" "margine superiore della pagina")
("page type" "tipo di pagina")
("page width" "larghezza della pagina")
("paper" "foglio")
("paper type" "tipo di foglio")
("papyrus" "papiro")
("paragraph" "paragrafo")
("paragraph mode" "modo del paragrafo")
("paragraph width" "larghezza del paragrafo")
("part" "parte")
("past changes" "cambiamenti precedenti")
("paste" "incolla")
("paste from" "incolla da")
("paste text" "incolla testo")
("path" "percorso")
("perform operations on cells" "esegui operazioni sulle celle")
("perform operations on columns" "esegui operazioni sulle colonne")
("perform operations on entire table" "esegui operazioni sull'intera tabella")
("perform operations on rows" "esegui operazioni sulle righe")
("permanent" "permanente")
("person" "persona")
("personal dictionary has been modified" "il dizionario personale è stato modificato")
("phantasy" "fantasia")
("philosophy" "filosofia")
("phoenician" "fenicio")
("phonetic" "fonetico")
("pink" "rosa")
("plain block" "blocco normale")
("plain tabular" "tabella normale")
("planned changes" "cambiamenti previsti")
("plans for the future" "programmi per il futuro")
("please" "per favore")
("please wait" "per favore, attendi")
("plus" "più")
("polish" "polacco")
("porting TeXmacs to other platforms" "porting di TeXmacs ad altre piattaforme")
("portrait" "verticale")
("portuguese" "portoghese")
("position" "posizione")
("position float" "posiziona fluttuante")
("position floating object" "posiziona oggetto fluttuante")
("position the table" "posiziona la tabella")
("postscript" "postscript")
("postscript image" "immagine postscript")
("pre-alpha release" "versione pre-alfa")
("preamble" "preambolo")
("preamble mode" "modo preambolo")
("preferences" "preferenze")
("presentation mode" "modo presentazione")
("preview before printing" "anteprima prima di stampare")
("preview with ghostview" "anteprima con ghostview")
("primary" "primario")
("prime" "primo")
("print" "stampa")
("print all" "stampa tutto")
("print all to file" "stampa tutto su file")
("print page selection" "stampa le pagine selezionate")
("print page selection to file" "stampa le pagine selezionate su file")
("print to postscript file" "stampa su file postscript")
("printer" "stampante")
("printer dpi" "risoluzione della stampante (dpi)")
("printing command" "comando di stampa")
("problem" "problema")
("professional" "professionale")
("prog" "prog")
("prog font" "carattere prog")
("prog font family" "famiglia del carattere prog")
("prog font series" "stile del carattere prog")
("prog font shape" "forma del carattere prog")
("program" "programma")
("program mode" "modo programma")
("programming" "programmazione")
("progressive" "progressivo")
("project" "progetto")
("projects" "progetti")
("prologue" "prologo")
("prompt on scripts" "chiedi per script")
("proof" "dimostrazione")
("proportional" "proporzionale")
("proportional typewriter" "macchina da scrivere proporzionale")
("proposition" "proposizione")
("query replace" "sostituisci")
("quit" "esci")
("quotation" "citazione (più paragrafi)")
("quote" "citazione")
("range" "rango")
("really close it" "chiudi per davvero")
("really huge" "gigante")
("really quit" "sicuro di voler uscire")
("red" "rosso")
("redo" "rifai")
("redo undone changes" "rifai azioni annullate")
("reduce bottom margin by" "riduci il margine superiore di")
("reduce left margin by" "riduci il margine sinistro di")
("reduce margins" "riduci i margini")
("reduce right margin by" "riduci il margine destro di")
("reduce top margin by" "riduci il margine superiore di")
("reduction even page margin" "riduci il margine delle pagine pari")
("reduction odd page margin" "riduci il margine delle pagine dispari")
("reduction page bottom margin" "riduci il margine inferiore della pagina")
("reduction page right margin" "riduci il margine destro della pagina")
("reduction page top margin" "riduci il margine superiore della pagina")
("reference" "referenza")
("references" "referenze")
("regular" "regolare")
("release" "versione")
("reload" "ricarica")
("remark" "osservazione")
("remove number" "rimuovi numero")
("remove this switch" "rimuovi questo switch")
("renumber this page" "rinumera questa pagina")
("repeat object" "ripeti oggetto")
("replace" "sostituisci")
("replace by" "sostituisci con")
("replaced" "sostituito")
("replaced one occurrence" "un'occorrenza è stata sostituita")
("reset" "azzera")
("resize object" "ridimensiona oggetto")
("resized" "oggetto ridimensionato")
("return" "invio")
("revert" "ritorna all'originale")
("revert buffer" "ripristina il buffer")
("right" "destra")
("right border" "bordo destro")
("right margin" "margine destro")
("right padding" "spaziatura destra")
("right aligned" "allineato a destra")
("right subscript" "pedice a destra")
("right superscript" "apice a destra")
("right surrounding" "surrounding a destra")
("rigid" "rigido")
("rigid horizontal" "orizzontale rigida")
("rigid space" "spazio rigido")
("romanian" "rumeno")
("root" "radice")
("rotate backward" "ruota all'indietro")
("rotate forward" "ruota in avanti")
("row" "riga")
("row contains glued items" "la riga contiene elementi appiccicati")
("runic" "runico")
("running author" "autore attuale")
("running title" "titolo attuale")
("russian" "russo")
("russian and Ukrainian users" "utenti russi ed ucraini")
("sample" "campione")
("sans serif" "sans serif")
("save" "salva")
("save TeXmacs file" "salva file TeXmacs")
("save TeXmacs style file" "salva file di stile TeXmacs")
("save as" "salva come")
("save as LaTeX" "salva come LaTeX")
("save as TeX" "salva come TeX")
("save buffer" "salva buffer")
("save buffer as" "salva il buffer come")
("save file" "salva file")
("save html file" "salva file html")
("save image" "salva immagine")
("save latex file" "salva file latex")
("save tex file" "salva file tex")
("save this buffer" "salva questo buffer")
("save verbatim file" "salva file di testo semplice")
("saved" "salvato")
("screen layout" "impaginazione su schermo")
("screen margins" "margini dello schermo")
("script" "script")
("script above" "script sopra")
("script below" "script sotto")
("script script size" "script script size")
("script size" "dimensione dello script")
("scripts not accepted" "gli script non sono accettati")
("search" "cerca")
("searching" "cercando")
("secondary" "secondario")
("section" "sezione")
("security" "sicurezza")
("see" "vedi")
("select a document style" "seleziona uno stile di documento")
("select a foreground color" "seleziona un colore di primo piano")
("select a language" "seleziona una lingua")
("selected region" "regione selezionata")
("selection" "selezione")
("selections" "selezioni")
("seminar" "seminario")
("separation between lines" "separazione tra le righe")
("separation between paragraphs" "separazione tra i paragrafi")
("separator" "separatore")
("september" "settembre")
("serb" "serbo")
("series" "serie")
("series|right" "serie|destra")
("session" "sessione")
("session name" "nome della sessione")
("session type" "tipo di sessione")
("sessions" "sessioni")
("set" "imposta")
("set background color of cell" "imposta colore di sfondo della cella")
("set cell mode" "imposta il modo della cella")
("set extension center" "imposta il centro dell'estensione")
("set height" "imposta altezza")
("set height of cell" "imposta l'altezza della cella")
("set margins" "imposta i margini")
("set n" "imposta n")
("set paragraph margins" "imposta i margini del paragrafo")
("set paragraph mode" "imposta il modo del paragrafo")
("set printer dpi" "imposta la risoluzione della stampante (dpi)")
("set printing command" "imposta il comando di stampa")
("set span" "imposta span")
("set special cell properties" "imposta proprietà speciali della cella")
("set special table properties" "imposta proprietà speciali della tabella")
("set text width" "imposta la larghezza del testo")
("set width" "imposta larghezza")
("set width of cell" "imposta la larghezza della cella")
("settings" "impostazioni")
("setup printer" "configura la stampante")
("shape" "forma")
("shift-down" "shift-giù")
("shift-right" "shift-destra")
("show" "mostra")
("show header and footer" "mostra intestazione e piè di pagina")
("show on screen" "mostra sullo schermo")
("shrinking factor" "fattore di riduzione")
("signature" "firma")
("size" "dimensioni")
("size limits" "limiti delle dimensioni")
("slanted" "inclinata")
("sloppy" "sloppy")
("small" "piccolo")
("small caps" "maiuscoletto")
("small figure" "figura piccola")
("small skip" "salto piccolo")
("small table" "tabella piccola")
("source code" "codice sorgente")
("space" "spazio")
("space between lines" "spazio tra le righe")
("space between paragraphs" "spazio tra i paragrafi")
("spacing" "spaziatura")
("spanish" "spagnolo")
("special" "speciale")
("special cell properties" "proprietà speciali della cella")
("special table properties" "proprietà speciali della tabella")
("specific" "specifico")
("spell" "ortografia")
("spell checking complete" "controllo ortografico completato")
("spelling error" "errore ortografico")
("spelling errors have been corrected" "gli errori ortografici sono stati corretti")
("split" "dividi")
("square root" "radice quadrata")
("start" "inizio")
("start a new chapter" "inizia un nuovo capitolo")
("start a new section" "inizia una nuova sezione")
("start an interactive session" "inizia una sessione interattiva")
("status bar" "barra di stato")
("stretchable" "estensibile")
("stretchable horizontal" "estensibile orizzontalmente")
("stretchable vertical" "estensibile verticalmente")
("stroke" "tratto")
("strokes" "tratti")
("strong" "enfatizzato")
("structural" "strutturale")
("style" "stile")
("styles" "stili")
("sub" "secondo livello")
("subparagraph" "sotto-paragrafo")
("subscript" "pedice")
("subsection" "sotto-sezione")
("subsub" "terzo livello")
("subsubsection" "sotto-sotto-sezione")
("summary" "sommario")
("summary of the principal TeXmacs tags" "sommario dei principali tag di TeXmacs")
("superpose" "sovrapponi")
("superposed" "sovrapposto")
("superscript" "apice")
("swedish" "svedese")
("switch" "switch")
("switch to first" "passa al primo")
("switch to formula style" "passa allo stile formula")
("switch to last" "passa all'ultimo")
("switch to next" "passa al successivo")
("switch to previous" "passa al precedente")
("switching and folding" "switch e arrotolamento")
("symbol" "simbolo")
("system environment variables" "variabili ambientali di sistema")
("tab" "tab")
("table" "tabella")
("table command" "comando di tabella")
("table of contents" "indice")
("tables" "tabelle")
("tabular" "tabellare")
("tabular material" "materiale tabellare")
("teXmacs as an interface" "TeXmacs come un'interfaccia")
("teXmacs fonts" "font di TeXmacs")
("teXmacs notice" "avviso di TeXmacs")
("teXmacs style files" "fogli di stile di TeXmacs")
("ternary" "ternario")
("test" "provare")
("tex" "tex")
("text" "testo")
("text font" "carattere del testo")
("text height correction" "correzione dell'altezza del testo")
("text width" "larghezza del testo")
("texts" "testi")
("th century bc" "-esimo secolo A.C.")
("th root" "radice -esima")
("thai" "tailandese")
("the TeXmacs authors" "gli autori di TeXmacs")
("the application did not send its usual startup banner" "l'applicazione non ha inviato il suo solito banner iniziale")
("the application does not reply" "l'applicazione non risponde")
("the application is already running" "l'applicazione è già in esecuzione")
("the boxes produced by the typesetter" "i box prodotti dal sistema di composizione")
("the graphical user interface" "l'interfaccia grafica utente")
("the leaves of TeXmacs trees" "le foglie dell'albero di TeXmacs")
("the mycas example" "l'esempio di mycas")
("the primitive TeXmacs constructs" "i costrutti primitivi di TeXmacs")
("the standard TeXmacs styles" "gli stili standard di TeXmacs")
("theorem" "teorema")
("there are unsaved documents" "ci sono documenti non salvati")
("this document has not been saved" "questo documento non è stato salvato")
("this document has been produced using" "questo documento è stato realizzato usando")
("this line" "questa linea")
("this page" "questa pagina")
("tilda" "tilda")
("tilde" "tilde")
("times" "per")
("tiny" "diminuito")
("title" "titolo")
("to the left" "a sinistra")
("to the right" "a destra")
("today" "oggi")
("tools" "strumenti")
("top" "superiore")
("top border" "bordo superiore")
("top level" "livello superiore")
("top margin" "margine superiore")
("top padding" "spaziatura superiore")
("translate" "traduci")
("tree" "albero")
("tuple" "tupla")
("turkish" "turco")
("tutorial" "tutorial")
("type" "tipo")
("type a latex command followed by" "scrivi un comando latex seguito da")
("type body" "scrivi il corpo")
("type denominator" "scrivi il denominatore")
("type numerator" "scrivi il numeratore")
("type script" "scrivi l'indice")
("typesetted boxes" "composizione tipografica dei box")
("typewriter" "macchina da scrivere")
("typewriter small caps" "maiuscoletto macchina da scrivere")
("typing a simple text" "comporre un semplice testo")
("typing simple texts" "comporre semplici testi")
("ugaritic" "ugaritico")
("ukrainian" "ucraino")
("undo" "annulla")
("undo last changes" "annulla gli ultimi cambiamenti")
("up" "su")
("update" "aggiorna")
("update from web" "aggiorna dal web")
("update image links" "aggiorna i collegamenti alle immagini")
("upper border" "bordo superiore")
("use TeXmacs" "usa TeXmacs")
("use a black color" "usa colore nero")
("use a blue color" "usa colore blu")
("use a bold font" "usa un font grassetto")
("use a brown color" "usa colore marrone")
("use a calligraphic font" "usa un carattere calligrafico")
("use a green color" "usa colore verde")
("use a grey color" "usa colore grigio")
("use a magenta color" "usa colore magenta")
("use a orange color" "usa colore arancione")
("use a pink color" "usa colore rosa")
("use a red color" "usa colore rosso")
("use a sans serif font" "usa un carattere sans serif")
("use a typewriter font" "usa un carattere macchina da scrivere")
("use a white color" "usa colore bianco")
("use a yellow color" "usa colore giallo")
("use blackboard bold font" "usa carattere lavagna grassetto")
("use bold font series" "usa serie di caratteri grassetto")
("use calligraphical font" "usa carattere calligrafico")
("use footnote font size" "usa dimensione del carattere piè di pagina")
("use fraktur font" "usa carattere fraktur")
("use huge font size" "usa un carattere enorme")
("use italic font shape" "usa un carattere di forma corsiva")
("use large font size" "usa un carattere grande")
("use left hand column as border" "usa la colonna di sinistra come bordo")
("use medium font series" "usa serie di caratteri medio")
("use normal font size" "usa carattere di dimensioni normali")
("use package" "usa pacchetto")
("use paragraph width" "usa larghezza di paragrafo")
("use really huge font size" "usa un carattere gigante")
("use right font shape" "usa forma del carattere di destra")
("use right hand column as border" "usa la colonna di destra come bordo")
("use roman font family" "usa famiglia di caratteri roman")
("use row above as border" "usa la riga superiore come bordo")
("use row below as border" "usa la riga inferiore come bordo")
("use sans serif font family" "usa famiglia di caratteri sans serif")
("use script font size" "usa dimensione del carattere script")
("use slanted font shape" "usa forma di carattere inclinata")
("use small capitals" "usa maiuscoletto")
("use small font size" "usa carattere piccolo")
("use small-caps font shape" "usa forma di carattere maiuscoletto")
("use the blackboard bold font" "usa carattere lavagna grassetto")
("use the fraktur font" "usa il carattere fraktur")
("use tiny font font size" "usa dimensione del carattere piccolo")
("use typewriter font family" "usa famiglia di caratteri macchina da scrivere")
("use very large font size" "usa un carattere molto grande")
("user manual" "manuale utente")
("user provided icons" "icone definite dall'utente")
("value" "valore")
("variable" "variabile")
("variant" "variante")
("vector" "vettore")
("verbatim" "testo semplice")
("verse" "verso")
("vertical" "verticale")
("vertical after" "verticale dopo")
("vertical before" "verticale prima")
("vertical cell alignment" "allineamento verticale della cella")
("vertical part" "parte verticale")
("vertical position" "posizione verticale")
("vertical space" "spazio verticale")
("vertical table alignment" "alineamento verticale della tabella")
("vertically align cell to the base" "allinea verticalmente la cella alla base")
("vertically center the cell" "centra verticalmente la cella")
("very large" "molto grande")
("very small" "molto piccolo")
("vietnamese" "vietnamita")
("view" "visualizza")
("visible" "visibile")
("warning" "avviso")
("welcome" "benvenuto")
("welcome to GNU TeXmacs" "benvenuto in GNU TeXmacs")
("what is new" "che c'è di nuovo")
("when finished" "una volta terminato")
("while" "mentre")
("white" "bianco")
("wide accent" "accento largo")
("width" "larghezza")
("width is exactly the specified width" "la larghezza è esattamente la larghezza specificata")
("width is maximum of specified width and box width" "la larghezza è la massimo tra quella specificata e quella del box")
("width is minimum of specified width and box width" "la larghezza è la minima tra quella specificata e quella del box")
("width magnification" "ingrandimento della larghezza")
("window" "finestra")
("window height" "altezza della finestra")
("window width" "larghezza della finestra")
("windows key" "tasto Windows")
("with" "con")
("write a name" "scrivi un nome")
("write bold mathematics" "scrivi matematica in grassetto")
("write bold text" "scrivi in grassetto")
("write italic text" "scrivi in corsivo")
("write sample text" "scrivi esempio")
("write strong text" "scrivi testo marcato")
("write typewriter text" "scrivi testo macchina da scrivere")
("write verbatim text" "scrivi testo a larghezza fissa")
("writing data converters" "scrivere convertitori di formato")
("writing your own style files" "scrivere il proprio file di stile")
("yellow" "giallo")
("yes" "sì")
("you can also obtain" "puoi anche ottenere")
("your document is back in its original state" "il documento è stato riportato allo stato originale")
("your first interface" "la tua prima interfaccia")
