("a modifier" "τροποποιητής a")
("a series" "σειρά a")
("abbreviation" "συντομογραφία")
("abbreviation" " συντομογραφία ")
("about" "σχετικά με το TeXmacs")
("about menu" "σχετικά με το μενού")
("above" "πάνω")
("above" "παραπάνω")
("abstract" "περίληψη")
("accent" "τόνος")
("accept" "αποδοχή")
("accept all scripts" "αποδοχή όλων των scripts")
("accept no scripts" "μη αποδοχή των scripts")
("accept script" "αποδοχή του scripts")
("acknowledgment" "ευχαριστία")
("acknowledgment" "επιβεβαίωση")
("acknowledgments" "ευχαριστίες")
("acronym" "ακρωνύμιο")
("action" "ενέργεια")
("activate" "ενεργοποίησε")
("activate hidden" "ενεργοποίηση  των κρυμμένων")
("activate hidden" "ενεργοποίησε  τα κρυμμένα")
("activate once" "ενεργοποίηση μια φορά")
("activate once" "ενεργοποίησε μια φορά")
("activation" "ενεργοποίηση")
("acute" "οξεία")
("add package" "πρόσθεση πακέτου")
("add package" "πρόσθεσε το πακέτο")
("add style package" "προσθήκη πακέτου στυλ")
("add switch after" "τοποθέτηση διακόπτη μετά")
("add switch after" "πρόσθεσε τον διακόπτη μετά")
("add switch before" "τοποθέτηση διακόπτη πριν")
("add switch before" "πρόσθεσε τον διακόπτη πριν")
("address" "διεύθυνση")
("address block" "μπλοκ με διευθύνσεις")
("address block" "τμήμα διεύθυνσης")
("adjust" "προσαρμογή")
("advanced" "για προχωρημένους")
("advanced layout features" "προηγμένες λειτουργίες διάταξης")
("after" "μετά")
("albanian" "αλβανικά")
("algorithm" "αλγόριθμος")
("align cell to the bottom" "στοίχιση κελιού κάτω")
("align cell to the left" "στοίχιση κελιού αριστερά")
("align cell to the right" "στοίχιση κελιού δεξιά")
("align cell to the top" "στοίχιση κελιού πάνω")
("align table at base of left column" "στοίχιση πίνακα στην βάση της αριστερής στήλης")
("align table at base of middle column" "στοίχιση πίνακα στην βάση της μεσαίας στήλης")
("align table at base of origin column" "στοίχιση πίνακα στην βάση της αρχικής στήλης")
("align table at base of right column" "στοίχιση πίνακα στην βάση της δεξιάς στήλης")
("align table at fraction bar height" "στοίχιση πίνακα στο ύψος της γραμμής κλάσματος")
("align table at the base of bottom row" "στοίχιση πίνακα στην βάση της κάτω σειράς")
("align table at the base of middle row" "στοίχιση πίνακα στην βάση της μεσαίας σειράς")
("align table at the base of origin row" "στοίχιση πίνακα στην βάση της αρχικής σειράς")
("align table at the base of top row" "στοίχιση πίνακα στην βάση της πάνω σειράς")
("align table at the bottom" "στοίχιση πίνακα κάτω")
("align table at the center" "στοίχιση πίνακα στο κέντρο")
("align table at the horizontal center" "στοίχιση πίνακα στο κέντρο οριζοντίως")
("align table at the left" "στοίχιση πίνακα αριστερά")
("align table at the top" "στοίχιση πίνακα πάνω")
("align table to the right" "στοίχιση πίνακα δεξιά")
("align text to the left" "στοίχιση κειμένου αριστερά")
("align text to the right" "στοίχιση κειμένου δεξιά")
("aligned" "στοιχισμένο")
("alignment" "στοίχιση")
("all" "όλα")
("allow" "αποδοχή")
("allow for macro definitions in preamble" "αποδοχή ορισμού μακροεντολών στο προοίμιο")
("allowed extension" "επιτρεπτή επέκταση")
("allowed reduction" "επιτρεπτή μείωση")
("allowed reduction" "επιτρεπτή αναγωγή")
("alpha release" "δοκιμαστική έκδοση alpha")
("alt key" "πλήκτρο Alt")
("alternate" "εναλλακτικά")
("alternative specification" "εναλλακτική προδιαγραφή")
("always" "πάντα")
("american" "αμερικανικά")
("and" "και")
("angular" "γωνιακή")
("animation" "κινησιοδότηση")
("animation" "κινησιοδότηση")
("answer" "απάντηση")
("answer" "απάντηση")
("appendix" "παράρτημα")
("apply" "εφαρμογή")
("apply macro" "εφαρμογή μακροεντολής")
("apply macro" "εφαρμογή μακροεντολών")
("apply macro once" "εφαρμογή μακροεντολής μια φορά")
("apply macro once" "εφαρμογή μακροεντολών μια φορά")
("april" "απρίλιος")
("arab" "αραβικά")
("arc cosine" "τόξο συνημιτόνου")
("arc sine" "τόξο ημιτόνου")
("arc tangent" "τόξο εφαπτομένης")
("arch series" "σειρά αψίδων")
("archaic" "αρχαϊκό")
("archaic" "αρχαϊκός")
("architecture" "αρχιτεκτωνική")
("architecture" "αρχιτεκτωνική")
("argument" "όρισμα")
("argument" "παράμετρος")
("arithmetic" "αριθμητικό")
("armenian" "αρμενικά")
("arrow" "βέλος")
("arrows" "βέλη")
("article" "άρθρο")
("as on paper" "όπως στο χαρτί")
("assign" "ανάθεση")
("at fraction bar height" "στο ύψος της γραμμής κλάσματος")
("at the baseline" "στη γραμμή βάσης")
("at the bottom" "κάτω")
("at the left" "αριστερά")
("at the middle" "στη μέση")
("at the right" "δεξιά")
("at the top" "πάνω")
("attach" "επισύναψη")
("attach buffer to which project" "επισύναψη προσωρινής αποθήκευσης σε ποιο έργο")
("attach buffer to which project" "επισύναψη buffer στο έργο")
("august" "αύγουστος")
("author" "συγγραφέας")
("authorize" "εξουσιοδότηση")
("automatic" "αυτόματα")
("automatic quotes" "αυτόματα  εισαγωγικά")
("automatically close brackets" "αυτόματο κλείσιμο παρενθέσεων")
("automatically generated content" "αυτόματη δημιουργία περιεχομένου")
("autosave" "αυτόματη αποθήκευση")
("axiom" "αξίωμα")
("axis" "άξονας")
("b series" "σειρά b")
("background" "φόντο")
("background color" "χρώμα του φόντου")
("background evaluations" "αξιολογήσεις ιστορικού")
("backward replace" "αντικατάσταση προς τα πίσω")
("backward search" "αναζήτηση προς τα πίσω")
("bad data format" "λανθασμένη μορφή δεδομένων")
("bar" "γραμμή")
("bar" " μπάρα ")
("bard" "bard")
("bard" "βάρδος")
("base level" "επίπεδο βάσης")
("baseline" "αρχική τιμή")
("bashkirian" "bashkirian")
("basic" "βασικό")
("basic communication using pipes" "βασικές επικοινωνία με τη χρήση σωλήνων")
("basic data types" "βασικοί τύποι δεδομένων")
("basic types" "βασικοί τύποι")
("be useful" "γίνε χρήσιμος")
("become a TeXmacs developer" "γίνε ένας προγραμματιστής του TeXmacs")
("before" "πριν")
("begin" "αρχή")
("below" "από κάτω")
("beta release" "δοκιμαστική έκδοση beta")
("bibliography" "βιβλιογραφία")
("bibliography file" "αρχείο βιβλιογραφίας")
("bibliography style" "στυλ βιβλιογραφίας")
("big" "μεγάλο")
("big figure" "μεγάλο σχήμα")
("big operator" "μεγάλος τελεστής")
("big skip" "μεγάλο κενό")
("big table" "μεγάλος πίνακας")
("binary operation" "δυαδική πράξη")
("binary relation" "δυαδική σχέση")
("black" "μαύρο")
("blackboard bold" "blackboard bold")
("blackboard bold" "γραμματοσειρά blackboard bold")
("blackboard math" "blackboard math")
("blackboard math" "γραμματοσειρά blackboard math")
("blackletter" "blackletter")
("blackletter" "γραφή blackletter")
("blank column" "κενή στήλη")
("blank row" "κενή γραμμή")
("block content" "μπλοκ περιεχομένου")
("block of code" "μπλοκ κώδικα")
("blue" "μπλε")
("body" "σώμα")
("bold" "έντονο")
("book" "βιβλίο")
("book" "βιβλίο")
("border" "περίγραμμα")
("both" "και τα δύο")
("bottom" "κάτω")
("bottom" "κάτω")
("bottom border" "κάτω περίγραμμα")
("bottom cell border" "περίγραμμα του κάτω κελιού")
("bottom cell border" "κάτω περίγραμμα του κελιού")
("bottom cell padding" "αναπλήρωση του κάτω κελιού")
("bottom cell padding" "κάτω γέμισμα του κελιού")
("bottom margin" "κάτω περιθώριο")
("bottom padding" "αναπλήρωση κάτω")
("bottom padding" "κάτω γέμισμα")
("bottom table border" "περίγραμμα του κάτω πίνακα")
("bottom table border" "κάτω περίγραμμα του πίνακα")
("bottom table padding" "αναπλήρωση του κάτω πίνακα")
("bottom table padding" "κάτω γέμισμα του πίνακα")
("branch" "κλάδος")
("break" "χωρισμός")
("break" "αλλαγή γραμμής")
("breaking" "αλλαγή γραμμής")
("breve" "breve")
("breve" "βραχύ")
("british" "βρετανικά")
("broken white" "σπασμένο λευκό")
("brown" "καφέ")
("browse" "περιήγηση")
("browse web" "περιήγηση ιστού")
("browser" "φυλλομετρητής")
("buffer" "προσωρινή αποθήκευση")
("buffer" "ενδιάμεσος χώρος (buffer)")
("bulgarian" "βουλγαρικά")
("bullet" "παχιά κουκίδα")
("bullet" "κουκίδα")
("bullets" "παχιές κουκίδες")
("bullets" "κουκίδες")
("busy" "απασχολημένος")
("by" "από")
("by typing" "πληκτρολογώντας")
("bytes free" "ελεύθερα bytes")
("bytes used" "bytes που χρησιμοποιούνται")
("calculus" "λογισμός")
("calligraphic" "καλλιγραφικά")
("cancel" "ακύρωση")
("caps-lock key" "πλήκτρο caps-lock")
("case" "πεζά/κεφαλαία")
("cc" "αντίγραφο")
("cc" "αντίγραφο/cc")
("cell" "κελί")
("cell background color" "χρώμα του φόντου στο κελί")
("cell border" "περίγραμμα κελιού")
("cell height" "ύψος κελιού")
("cell operation mode" "λειτουργία κελιού")
("cell width" "πλάτος κελιού")
("cells" "κελιά")
("center" "κέντρο")
("center text" "κεντράρισμα κειμένου")
("centered" "κεντραρισμένο")
("centered" "κεντραρισμένο")
("centered block" "κεντραρισμένο μπλοκ")
("centered block" "κεντραρισμένο τμήμα")
("centered tabular" "κεντραρισμένος πίνακας δεδομένων")
("centered tabular" "κεντrαρισμένος πίνακας δεδομένων")
("change border of cell" "αλλαγή περιγράμματος κελιού")
("change cell operation mode" "αλλαγή λειτουργίας κελιού")
("change log" "καταγραφή αλλαγών ")
("change the border of the table" "αλλαγή του περιγράμματος πίνακα")
("changes" "αλλαγές")
("chapter" "κεφάλαιο")
("check" "check")
("check" "έλεγχος")
("check text for spelling errors" "ορθογραφικός έλεγχος κειμένου")
("chinese" "κινέζικα")
("choice" "επιλογή")
("citation" "παραπομπή")
("cite" "αναφορά")
("class" "κλάση")
("clear" "εκκαθάριση")
("clear all fields" "καθαρισμός όλων των πεδίων")
("clear selection" "εκκαθάριση επιλογής")
("clip" "ψαλίδισμα")
("clipped" "αποκομμένο")
("clipped and magnified" "αποκομμένο και μεγεθυμένο")
("clipped and resized" "αποκομμένο και με αλλαγμένο μέγεθος")
("clone" "κλωνοποίηση")
("clone window" "κλωνοποίηση παραθύρου")
("close" "κλείσιμο")
("close TeXmacs" "κλείσιμο TeXmacs")
("close buffer" "κλείσιμο προσωρινής αποθήκευσης")
("close buffer" "κλείσιμο buffer")
("close document" "κλείσιμο  εγγράφου")
("close session" "κλείσιμο συνεδρίας")
("close window" "κλείσιμο παραθύρου")
("closing" "κλείσιμο")
("closing style" "στυλ κλεισίματος")
("code" "code")
("code" "κώδικας")
("color" "χρώμα")
("colors" "χρώματα")
("column" "στήλη")
("column contains glued items" "η στήλη περιέχει εφαπτόμενα στοιχεία")
("column to the left" "στήλη προς τα αριστερά")
("column to the right" "στήλη προς τα δεξιά")
("columns" "στήλες")
("common formats" "συνηθισμένες μορφές")
("compact" "συμπαγές")
("compact" "συμπαγής")
("compactification" "συμπαγοποίηση")
("compactify" "συμπαγοποίησε")
("compatibility with other formats" "συμβατότητα με άλλες μορφές")
("compile article" "μεταγλώττιση άρθρου")
("compile book" "μεταγλώττιση βιβλίου")
("compile buffer" "μεταγλώττιση προσωρινής αποθήκευσης")
("compile buffer" "μεταγλώττιση του buffer")
("compile project" "μεταγλώττιση του project")
("completion" "περάτωση")
("complex" "σύμπλοκο")
("complex" "μιγαδικός")
("compose" "σύνθεση")
("compressed" "συμπιεσμένη")
("concrete" "concrete")
("condensed" "συμπυκνωμένο")
("condition" "προϋπόθεση")
("configuration" "ρύθμιση")
("contact" "επαφή")
("content" "περιεχόμενο")
("content tag" "είδος γραμματοσειράς")
("content tag" "ετικέτα περιεχομένου")
("context dependent icons" "εικονίδια εξαρτόμενα από τα συμφραζόμενα")
("continuation of" "συνέχεια")
("contract logarithms" "συστολή λογαρίθμων")
("contribute" "συνεισφορά")
("control the evaluation of expressions" "έλεγχος αποτίμησης παραστάσεων")
("convention" "σύμβαση")
("converters" "μετατροπείς")
("converters to other data formats" "μετατροπείς σε άλλη μορφή δεδομένων")
("convertible" "μετατρέψιμη")
("copy" "αντιγραφή")
("copy text" "αντιγραφή κειμένου")
("copy to" "αντιγραφή σε")
("copying" "αντιγραφή")
("cork charset with TeX catcode definition in preamble" "χαρακτήρες Cork με TeX catcode ορισμούς στο προοίμιο")
("corollary" "πόρισμα")
("correct text" "διόρθωση κειμένου")
("cosine" "συνημίτονο")
("count characters" "μέτρημα χαρακτήρων")
("count lines" "μέτρημα γραμμών")
("count words" "μέτρημα λέξεων")
("create a new document" "δημιουργία νέου εγγράφου")
("create preamble" "δημιουργία προοιμίου")
("create subsession" "δημιουργία υποσυνεδρίας")
("create web site" "δημιουργία ιστοσελίδας")
("cursors" "δείκτες")
("curve" "καμπύλη")
("custom tab" "προσαρμοσμένη καρτέλα")
("customizing TeXmacs" "προσαρμογή του TeXmacs")
("customizing the TeXmacs styles" "προσαρμόζοντας τις μορφές TeXmacs")
("custum tab" "custum tab")
("custum tab" "προσαρμοσμένη καρτέλα")
("cut" "αποκοπή")
("cut text" "αποκοπή κειμένου")
("cut to" "αποκοπή μέχρι")
("cypriot" "κυπριακά")
("cyrillic" "κυριλλικά")
("cyrillic input method" "μέθοδος εισαγωγής κυριλλικών")
("cyrillic italic right" "κυριλλικά κεκλιμένα δεξιά")
("cyrillic italic right" "κυριλλικά κεκλιμένα")
("czech" "τσέχικα")
("dancers" "χορευτές")
("danish" "δανικά")
("dark grey" "σκούρο γκρι")
("dash" "παύλα")
("dashes" "παύλες")
("data conversion" "μετατροπή δεδομένων")
("data format" "μορφή δεδομένων")
("date" "ημερομηνία")
("deactivate" "απενεργοποίηση")
("deactivate" "απενεργοποίηση")
("deactivate once" "απενεργοποίηση μια φορά")
("deactivate table" "απενεργοποίηση πίνακα")
("dead" "νεκρό(ς)")
("december" "δεκέμβριος")
("decimal comma" "δεκαδικό κόμμα")
("decimal dot" "δεκαδικό στίγμα (κουκίδα)")
("decorate atoms" "decorate atoms")
("default" "προεπιλεγμένο")
("default padding" "προεπιλεγμένη αναπλήρωση")
("default padding" "προεπιλεγμένο γέμισμα")
("definition" "ορισμός")
("delete" "διαγραφή")
("delete column" "διαγραφή στήλης")
("delete row" "διαγραφή σειράς")
("deleted" "διαγραμμένο")
("denominator" "παρονομαστής")
("describe" "περιγραφή")
("description" "περιγραφή")
("destination" "προορισμός")
("detach" "απόσπαση")
("detailed" "λεπτομερής")
("detailed" "λεπτομερής (-είς)")
("detailed menus" "λεπτομερή μενού")
("details in menus" "λεπτομέρειες στα μενού")
("determinant" "προσδιοριστικός")
("devangari" "devangari")
("developers guide" "οδηγός για προγραμματιστές")
("differentiate" "διαφοροποίηση")
("directory" "κατάλογος")
("disable" "απενεργοποίηση")
("disable first indentation" "απενεργοποίηση πρώτης εσοχής")
("disable first indentation after" "απενεργοποίηση πρώτης εσοχής μετά")
("disable first indentation before" "απενεργοποίηση πρώτης εσοχής πριν")
("disable indentation" "απενεργοποίηση εσοχής")
("disable indentation after" "απενεργοποίηση πρώτης εσοχής μετά")
("disable indentation before" "απενεργοποίηση πρώτης εσοχής πριν")
("disallow" "απαγόρευση")
("displayed formula" "αυτοτελής τύπος")
("distribute unused space" "διανομή αχρησιμοποίητου χώρου")
("div" "div")
("do not remap" "μην ξανα-απεικονίζεις")
("document" "έγγραφο")
("document format" "μορφοποίηση εγγράφου")
("document style" "στυλ εγγράφου")
("document styles" "στυλ εγγράφου")
("documentation" "τεκμηρίωση")
("documents are trees" "τα έγγραφα είναι δενδρα")
("dot" "κουκκίδα")
("dots" "κουκκίδες")
("double stroke" "διπλή γραμμή")
("down" "κάτω")
("download" "λήψη")
("downwards" "προς τα κάτω")
("dpi" "dpi")
("draw image" "σχεδιασμός εικόνας")
("draw over selection" "σχεδιασμός πάνω από την επιλογή")
("duplicate" "αντίτυπο")
("duplicate" "διπλασιασμός")
("dutch" "ολανδικά")
("dynamic libraries" "δυναμικές βιβλιοθήκες")
("edit" "επεξεργασία")
("edit macros" "επεξεργασία μακροεντολής")
("edit preamble" "επεξεργασία προοιμίου")
("edit source tree" "επεξεργασία πηγαίου δέντρου")
("editing tools" "εργαλεία επεξεργασίας")
("editing tools" "εργαλία επεξεργασίας")
("education" "εκπαίδευση")
("eigenvalues" "ιδιοτιμές")
("email" "ηλεκτρονικό ταχυδρομείο")
("emphasize" "έμφαση")
("emphasize text" "έμφαση στο κείμενο")
("emphasize text" "έμφαση στο κείμενό")
("empty box" "άδειο κουτί")
("enable first indentation" "ενεργοποίηση πρώτης εσοχής")
("enable first indentation after" "ενεργοποίηση πρώτης εσοχής μετά")
("enable first indentation before" "ενεργοποίηση πρώτης εσοχής πριν")
("enable indentation" "ενεργοποίηση εσοχής")
("enable indentation after" "ενεργοποίηση εσοχής μετά")
("enable indentation before" "ενεργοποίηση εσοχής πριν")
("encl" "συνημμένο")
("encl" "συν")
("encoding" "κωδικοποίηση")
("end" "τέλος")
("english" "αγγλικά")
("enter a title" "εισαγωγή τίτλου")
("enter data" "εισαγωγή δεδομένων")
("entire table" "όλον τον πίνακα")
("enumerate" "απαρίθμηση")
("enumerate|Alpha" "απαρίθμηση|Alpha")
("enumerate|Roman" "απαρίθμηση|Roman")
("enumerate|alpha" "απαρίθμηση|alpha")
("enumerate|roman" "απαρίθμηση|roman")
("enunciation" "διατύπωση")
("env" "env")
("environment" "περιβάλλον")
("epilogue" "επίλογος")
("equal" "ίσον")
("equation" "εξίσωση")
("equations" "εξισώσεις")
("equivalent for" "ισοδύναμο για")
("error" "σφάλμα")
("esperanto" "εσπεράντο")
("etruscan" "ετρουσκικά")
("evaluate" "αποτίμηση")
("evaluate above" "αποτίμηση πάνω")
("evaluate all" "αποτίμηση όλων")
("evaluate below" "αποτίμηση κάτω")
("evaluate fields in order" "αποτίμηση των πεδίων με την σειρά")
("evaluate scheme expression" "αποτίμηση παράστασης scheme")
("evaluation switch" "διακόπτης αποτίμησης")
("evaluation tag" "καρτέλα αποτίμησης")
("even page footer" "υποσέλιδο σελίδας με άρτιο αριθμό")
("even page header" "κεφαλίδα σελίδας με άρτιο αριθμό")
("even page left margin" "αριστερό περιθώριο σελίδας με άρτιο αριθμό")
("even page margin" "περιθώριο σελίδας με άρτιο αριθμό")
("even page shift" "μετατόπιση σελίδας με άρτιο αριθμό")
("even page text" "κείμενο σελίδας με άρτιο αριθμό")
("exact horizontal" "ακριβής οριζόντιος")
("exact mode" "ακριβής τρόπος λειτουργίας")
("exam" "τεστ")
("exam" "εξέταση")
("example" "παράδειγμα")
("exclusive" "αποκλειστικό")
("exclusive or" "αποκλειστικό ή")
("executable" "εκτελέσιμο")
("execute" "εκτέλεση")
("execute a TeXmacs command" "εκτέλεση εντολής TeXmacs")
("execute system command" "εκτέλεση εντολής συστήματος")
("executive" "εκτελεστικός")
("exercise" "άσκηση")
("exit left" "έξοδος αριστερά")
("exit right" "έξοδος δεξιά")
("expand" "ανάπτυγμα")
("expand logarithms" "ανάπτυγμα λογαρίθμων")
("expand trigonometric functions" "ανάπτυγμα τριγωνομετρικών συναρτήσεων")
("expand unrecognized macros" "ανάπτυγμα μη αναγνωρίσιμων μακροεντολών")
("expand user-defined macros" "ανάπτυγμα μακροεντολών ορισμένων από τον χρήστη")
("expanded" "αναπτυγμένη")
("explained" "εξηγήθηκε")
("explained" "εξηγημένο")
("exponential" "εκθετική")
("export" "εξαγωγή")
("export as" "εξαγωγή ως")
("export formulas as images" "εξαγωγή βιβλιογραφιών σαν σύνδεσμοι")
("extend" "επέκταση")
("extend or normal" "επέκταση ή κανονικό")
("extern " "extern")
("extra" "επιπλέον")
("extract format" "εξαγωγή μορφής")
("extract style file" "εξαγωγή αρχείου στυλ")
("extract style package" "εξαγωγή πακέτου στυλ")
("factor" "συντελεστής")
("factor" "παράγοντας")
("family" "οικογένεια")
("february" "Φεβρουάριος")
("figure" "σχήμα")
("figure" "εικόνα")
("file" "αρχείο")
("file name" "όνομα αρχείου")
("file not found" "το αρχείο δεν βρέθηκε")
("fill out" "συμπληρωμένο")
("find next match" "εύρεση επόμενου")
("find next match" "εύρεση επόμενης αντιστοιχίας")
("find text" "εύρεση κειμένου")
("finnish" "φινλανδικά")
("first contact" "πρώτη επαφή")
("first field" "πρώτο πεδίο")
("first indentation" "πρώτη εσοχή")
("first item" "πρώτο αντικείμενο")
("first page" "πρώτη σελίδα")
("first similar" "πρώτο παρόμοιο")
("first start" "πρώτη εκκίνηση")
("fit to screen" "προσαρμογή στην οθόνη")
("fit to screen width" "προσαρμογή στο πλάτος της οθόνης")
("fixed" "σταθερή")
("flat" "επίπεδο")
("flexibility" "προσαρμοστικότητα")
("flexibility factor for vertical spacing" "συντελεστής προσαρμοστικότητας για κατακόρυφο διάστημα")
("flexibility factor for vertical spacing" "συντελεστής προσαρμοστικότητας για τα κάθετα περιθώρια")
("floating algorithm" "μετακινούμενος αλγόριθμος")
("floating figure" "μετακινούμενο σχήμα")
("floating object" "μετακινούμενο αντικείμενο")
("floating table" "μετακινούμενος πίνακας")
("focus" "εστίαση")
("focus dependent icons" "εικονίδια εξαρτώμενα από την εστίαση")
("fold" "αναδίπλωση")
("fold" "fold")
("fold all fields" "αναδίπλωση όλων των πεδίων")
("fold back" "αναδίπλωση προς τα πίσω")
("fold input field" "αναδίπλωση πεδίου εισαγωγής")
("fold input field" "fold πεδίο εισαγωγής")
("folded" "διπλωμένη")
("folded" "folded")
("font" "γραμματοσειρά")
("font base size" "βασικό μέγεθος γραμματοσειράς")
("font dpi" "dpi γραμματοσειράς")
("font family" "οικογένεια γραμματοσειράς")
("font name" "όνομα γραμματοσειράς")
("font series" "σειρά γραμματοσειράς")
("font shape" "σχήμα γραμματοσειράς")
("font size" "μέγεθος γραμματοσειράς")
("font type" "τύπος γραμματοσειράς")
("font variant" "παραλλαγή γραμματοσειράς")
("fonts" "γραμματοσειρές")
("footer" "υποσέλιδο")
("footnote" "υποσημείωση")
("for" "for")
("foreground" "προσκήνιο")
("foreign" "ξένες")
("format" "μορφή")
("formatted and structured output" "μορφοποιημένη και δομημένη έξοδος")
("formatted date" "μορφοποιημένη ημερομηνία")
("formatting" "μορφοποίηση")
("formula" "μαθηματικός τύπος")
("formula style" "στυλ μαθηματικού τύπου")
("forward replace" "αντικατάσταση προς τα εμπρός")
("forward search" "αναζήτηση προς τα εμπρός")
("forward search" "εύρεση προς τα εμπρός")
("fraction" "κλάσμα")
("framed" "πλαισιωμένο")
("french" "γαλλικά")
("from center" "από το κέντρο")
("full manuals" "πλήρη εγχειρίδια")
("full screen mode" "λειτουργία πλήρους οθόνης")
("function" "συνάρτηση")
("functional" "συναρτησιακή")
("further customization" "περαιτέρω προσαρμογή")
("future changes" "μελλοντικές αλλαγές")
("gNU TeXmacs comes without any form of legal warranty" "το gNU TeXmacs δεν καλύπτεται από κάποια νόμιμη εγγύηση")
("gNU TeXmacs falls under the GNU general public license" "το gNU TeXmacs υπόκειται στην GNU general public license")
("gcd" "μκδ")
("general architecture of TeXmacs" "γενική αρχιτεκτονική του TeXmacs")
("general negation" "γενική άρνηση")
("general note" "γενική σημείωση")
("generating font file" "δημιουργία αρχείου γραμματοσειράς")
("generic" "γενικός")
("georgian" "γεωργιανά")
("german" "γερμανικά")
("getting started" "τα πρώτα βήματα")
("getting started" "αρχίζοντας...")
("glossary" "γλωσσάρι")
("glossary entry" "όρος γλωσσαρίου")
("glue" "κόλληση")
("glue decorations" "διακοσμήσης επικόλησης")
("go" "μετάβαση")
("go" "go")
("gothic" "γοτθικά")
("graphical interface" "γραφικό περιβάλλον")
("grave" "βαρεία")
("greater" "μεγαλύτερο")
("greater or equal" "μεγαλύτερο ή ίσο")
("greek" "ελληνικά")
("greek letter" "ελληνικό γράμμα")
("green" "πράσινο")
("grey" "γκρι")
("greyed" "γκριζα")
("group" "ομάδα")
("grouped" "ομαδοποιημένη")
("h modifier" "τροποποιητής h")
("happy typing" "καλή πληκτρολόγηση")
("has been aborted" "έχει ακυρωθεί")
("has completed its task" "έχει ολοκληρώσει την εργασία του")
("hat" "καρρέ")
("header" "κεφαλίδα")
("header and footer" "κεφαλίδα και υποσέλιδο")
("hebrew" "εβραϊκά")
("height" "ύψος")
("height is exactly the specified height" "το ύψος ταυτίζεται με το δοσμένο")
("height is maximum of specified height and box height" "το ύψος είναι το μέγιστο από: δοσμένο και ύψος πλαισίου")
("height is minimum of specified height and box height" "το ύψος είναι το ελάχιστο από: δοσμένο και ύψος πλαισίου")
("height magnification" "αύξηση ύψους")
("help" "βοήθεια")
("help me" "βοήθησέ με")
("help us" "βοήθησέ μας")
("here" "εδώ")
("hidden" "κρυμμένο")
("home" "αρχική θέση δρομέα")
("homepage" "αρχική σελίδα")
("horizontal" "οριζόντιο")
("horizontal alignment" "οριζόντια στοίχιση")
("horizontal cell alignment" "στοίχιση κελιού οριζοντίως")
("horizontal ink separation" "διαχωρισμός ink οριζοντίως")
("horizontal part" "οριζόντιο τμήμα")
("horizontal position" "οριζόντια θέση")
("horizontal space" "οριζόντιος κενός χώρος")
("horizontal table alignment" "στοίχιση πίνακα οριζοντίως")
("horizontally align cell to the base" "στοίχιση κελιού οριζοντίως στη βάση")
("horizontally center the cell" "κεντράρισμα κελιού οριζοντίως")
("how much longer may pages become" "δυνατότητα επιμήκυνσης σελιδών")
("how much shorter may pages become" "δυνατότητα σμίκρυνσης σελιδών")
("huge" "τεράστιο")
("hungarian" "ουγγρικά")
("hybrid command" "υβριδική εντολή")
("hyperlink" "υπερσύνδεσμος")
("hyperlink" "υπερδεσμός")
("hyphenation" "συλλαβισμός")
("icelandic" "ισλανδικά")
("if" "αν")
("if" "if")
("if hyphenated" "αν συλλαβίζεται")
("image" "εικόνα")
("image links" "σύνδεσμοι με εικόνα")
("implementation" "υλοποίηση")
("import" "εισαγωγή")
("improving the current implementation" "βελτίωση της τρέχουσας υλοποίησης")
("in popup windows" "σε αναδυόμενα παράθυρα")
("inactive" "ανενεργό")
("include" "προσθήκη")
("include" "επισύναψη")
("include" "συμπερίληψη")
("include a document" "προσθήκη εγγράφου")
("include a document" "συμπερίληψη εγγράφου")
("include file" "προσθήκη αρχείου")
("include file" "συμπερίληψη αρχείου")
("inclusion into TeXmacs" "προσθήκη στο TeXmacs")
("inclusion into TeXmacs" "συμπερίληψη στο TeXmacs")
("inclusions" "προσθήκες")
("inclusions" "συμπεριλήψεις")
("indent" "εσοχή")
("indentation" "εσοχή")
("indentation flag" "σημαία εσοχής")
("index" "ευρετήριο")
("index entry" "λήμμα ευρετηρίου")
("index level" "επίπεδο ευρετηρίου")
("informative flags" "ενημερωτικές σημαίες")
("inline arguments" "εμβόλιμοι παράμετροι")
("inline code" "ενσωματωμένος κώδικας")
("inline formula" "ενσωματωμένος τύπος")
("input mode" "τρόπος εισαγωγής")
("input options" "επιλογές εισόδου")
("insert" "εισαγωγή")
("insert Pr" "εισαγωγή Pr")
("insert a TeXmacs symbol" "εισαγωγή συμβόλου του TeXmacs")
("insert a big operator" "εισαγωγή μεγάλου τελεστή")
("insert a binary operation" "εισαγωγή δυαδικής πράξης")
("insert a binary relation" "εισαγωγή δυαδικής σχέσης")
("insert a blackboard bold character" "εισαγωγή χαρακτήρα σε blackboard bold")
("insert a blackboard bold character" "εισαγωγή χαρακτήρα blackboard bold")
("insert a bold calligraphic character" "εισαγωγή χαρακτήρα σε bold calligraphic")
("insert a bold calligraphic character" "εισαγωγή χαρακτήρα bold calligraphic")
("insert a bold character" "εισαγωγή χαρακτήρα σε bold")
("insert a bold character" "εισαγωγή έντονου χαρακτήρα (bold)")
("insert a calligraphic character" "εισαγωγή χαρακτήρα σε calligraphic")
("insert a calligraphic character" "εισαγωγή χαρακτήρα calligraphic")
("insert a condition" "εισαγωγή συνθήκης")
("insert a control flow instruction" "εισαγωγή εντολής ελέγχου ροής")
("insert a fraction" "εισαγωγή κλάσματος")
("insert a fraktur character" "εισαγωγή χαρακτήρα σε fraktur")
("insert a fraktur character" "εισαγωγή χαρακτήρα fraktur")
("insert a greek character" "εισαγωγή ελληνικού χαρακτήρα")
("insert a large left delimiter" "εισαγωγή μεγάλου αριστερού οροθέτη")
("insert a large right delimiter" "εισαγωγή μεγάλου δεξιού οροθέτη")
("insert a large separator" "εισαγωγή μεγάλου διαχωριστικού")
("insert a left subscript" "εισαγωγή αριστερού κάτω δείκτη")
("insert a left subscript" "εισαγωγή αριστερού δείκτη")
("insert a link" "εισαγωγή συνδέσμου")
("insert a miscellaneous symbol" "εισαγωγή συμβόλου σε miscellaneous")
("insert a miscellaneous symbol" "εισαγωγή συμβόλου από τα διάφορα")
("insert a new branch" "εισαγωγή νέου κλάδου")
("insert a new item" "εισαγωγή νέου αντικειμένου")
("insert a numerical operation" "εισαγωγή αριθμητικής πράξης")
("insert a picture" "εισαγωγή εικόνας")
("insert a square root" "εισαγωγή τετραγωνικής ρίζας")
("insert a table" "εισαγωγή πίνακα")
("insert a table or a matrix" "εισαγωγή πίνακα ή μαθηματικού πίνακα (μήτρας)")
("insert a textual operation" "εισαγωγή λειτουργίας κειμένου")
("insert a wide symbol above" "εισαγωγή συμβόλου σε wide πάνω")
("insert a wide symbol above" "εισαγωγή ευρέος συμβόλου πάνω")
("insert a wide symbol below" "εισαγωγή συμβόλου σε wide κάτω")
("insert a wide symbol below" "εισαγωγή ευρέος συμβόλου κάτω")
("insert an" "εισαγωγή")
("insert an accent" "εισαγωγή τόνου")
("insert an arrow" "εισαγωγή βέλους")
("insert an environment" "εισαγωγή περιβάλλοντος")
("insert an n" "εισαγωγή ν")
("insert appendix" "εισαγωγή παραρτήματος")
("insert arccos" "εισαγωγή arccos")
("insert arcsin" "εισαγωγή arcsin")
("insert arctan" "εισαγωγή arctan")
("insert arg" "εισαγωγή arg")
("insert argument" "εισαγωγή ορίσματος")
("insert argument" "εισαγωγή παραμέτρου")
("insert author" "εισαγωγή συγγραφέα")
("insert automatically generated content" "εισαγωγή αυτοματοποιημένου περιεχομένου")
("insert big contour integral" "εισαγωγή μεγάλου επικαμπύλιου ολοκληρώματος")
("insert big coproduct" "εισαγωγή μεγάλου συγγινομένου")
("insert big coproduct" "εισαγωγή μεγάλου εσωτερικού συγγινομένου")
("insert big direct sum" "εισαγωγή μεγάλου ευθέος αθροίσματος")
("insert big dotted point" "εισαγωγή μεγάλου διάστικτου κύκλου")
("insert big dotted point" "εισαγωγή μεγάλου σημείου")
("insert big integral" "εισαγωγή μεγάλου ολοκληρώματος")
("insert big intersection" "εισαγωγή μεγάλης διχοτόμησης")
("insert big logical and" "εισαγωγή μεγάλου λογικού και")
("insert big logical or" "εισαγωγή μεγάλου λογικού ή")
("insert big product" "εισαγωγή μεγάλου γινομένου")
("insert big square union" "εισαγωγή μεγάλης τετραγωνική ένωσης")
("insert big summation" "εισαγωγή μεγάλου αθροίσματος")
("insert big tensor product" "εισαγωγή μεγάλου τανυστικού γινομένου")
("insert big union" "εισαγωγή μεγάλης ένωσης")
("insert big union sum" "εισαγωγή μεγάλου αθροίσματος ενώσεων")
("insert big vertical space" "εισαγωγή μεγάλου κατακόρυφου κενού")
("insert chapter" "εισαγωγή κεφαλαίου")
("insert column" "εισαγωγή στήλης")
("insert column to the left" "εισαγωγή στήλης αριστερά")
("insert column to the right" "εισαγωγή στήλης δεξιά")
("insert cos" "εισαγωγή cos")
("insert cosh" "εισαγωγή cosh")
("insert cot" "εισαγωγή cot")
("insert coth" "εισαγωγή coth")
("insert csc" "εισαγωγή csc")
("insert deg" "εισαγωγή deg")
("insert det" "εισαγωγή det")
("insert dim" "εισαγωγή dim")
("insert dollar" "εισαγωγή συμβόλου δολλαρίου")
("insert equation" "εισαγωγή εξίσωσης")
("insert executable markup" "εισαγωγή εκτελέσιμης σήμανσης (markup)")
("insert exp" "εισαγωγή exp")
("insert field above" "εισαγωγή πεδίου πάνω")
("insert field below" "εισαγωγή πεδίου κάτω")
("insert fields" "εισαγωγή πεδίων")
("insert footnote" "εισαγωγή υποσημείωσης")
("insert formula" "εισαγωγή μαθηματικού τύπου")
("insert gcd" "εισαγωγή gcd")
("insert hom" "εισαγωγή hom")
("insert horizontal interword space" "εισαγωγή οριζόντιου κενού μεταξύ των λέξεων")
("insert image" "εισαγωγή εικόνας")
("insert inactive markup" "εισαγωγή ανενεργής σήμανσης (markup)")
("insert inf" "εισαγωγή inf")
("insert input field above" "εισαγωγή πεδίου εισόδου πάνω")
("insert input field below" "εισαγωγή πεδίου εισόδου κάτω")
("insert ker" "εισαγωγή ker")
("insert lg" "εισαγωγή lg")
("insert lim" "εισαγωγή lim")
("insert liminf" "εισαγωγή liminf")
("insert limsup" "εισαγωγή limsup")
("insert ln" "εισαγωγή ln")
("insert log" "εισαγωγή log")
("insert macro" "εισαγωγή μακροεντολής")
("insert mathematics" "εισαγωγή μαθηματικών")
("insert max" "εισαγωγή μεγίστου")
("insert medium horizontal space" "εισαγωγή οριζόντιου κενού μεσαίου μεγέθους")
("insert medium horizontal space" "εισαγωγή οριζόντιου κενού μεσαίου μεγέθους")
("insert medium horizontal space" "εισαγωγή μέσου οριζόντιου κενού")
("insert medium vertical space" "εισαγωγή κατακόρυφου κενού μεσαίου μεγέθους")
("insert medium vertical space" "εισαγωγή κατακόρυφου κενού μεσαίου μεγέθους")
("insert medium vertical space" "εισαγωγή μέσου κατακόρυφου κενού")
("insert min" "εισαγωγή ελαχίστου")
("insert negative horizontal space" "εισαγωγή αρνητικού οριζόντιου κενού")
("insert new item or number" "εισαγωγή νέου στοιχείου ή αριθμού")
("insert new rows or columns" "εισαγωγή νέων σειρών ή στηλών")
("insert or delete rows or columns" "εισαγωγή ή διαγραφή σειρών ή στηλών")
("insert row" "εισαγωγή σειράς")
("insert row above" "εισαγωγή σειράς πάνω")
("insert row below" "εισαγωγή σειράς κάτω")
("insert sec" "εισαγωγή sec")
("insert section" "εισαγωγή ενότητας")
("insert sharp" "εισαγωγή δίεσης")
("insert sin" "εισαγωγή sin")
("insert sinh" "εισαγωγή sinh")
("insert small horizontal space" "εισαγωγή οριζόντιου κενού μικρού μεγέθους")
("insert small horizontal space" "εισαγωγή μικρού οριζόντιου κενού")
("insert small vertical space" "εισαγωγή κατακόρυφου κενού μικρού μεγέθους")
("insert small vertical space" "εισαγωγή μικρού κατακόρυφου κενού")
("insert structural markup" "εισαγωγή δομημένης σήμανσης (structural markup)")
("insert subsection" "εισαγωγή υποενότητας")
("insert subsubsection" "εισαγωγή υπό-υποενότητας")
("insert sup" "εισαγωγή sup")
("insert tan" "εισαγωγή tan")
("insert tanh" "εισαγωγή tanh")
("insert text field" "εισαγωγή πεδίου κειμένου")
("insert text field above" "εισαγωγή πεδίου κειμένου πάνω")
("insert text field below" "εισαγωγή πεδίου κειμένου κάτω")
("insert thick horizontal space" "εισαγωγή παχιού οριζοντίου κενού")
("insert title" "εισαγωγή τίτλου")
("insert value" "εισαγωγή τιμής")
("integrate" "ολοκλήρωση")
("interactive command" "διαδραστική εντολή")
("interactive questions" "διαδραστικές ερωτήσεις")
("interfacing" "διασύνδεση")
("interfacing TeXmacs with other systems" "διασύνδεση του TeXmacs με άλλα συστήματα")
("interjection" "παρέμβαση")
("interjection" "παρεμβολή")
("interline separation" "διάστιχο")
("interline space" "απόσταση γραμμών")
("internationalization" "διεθνοποίηση")
("interparagraph space" "απόσταση παραγράφων")
("interrupt execution" "διακοπή εκτέλεσης")
("interrupted" "διακόπηκε")
("introduction" "εισαγωγή")
("invert" "αντιστροφή")
("invisible" "αόρατο")
("invisible citation" "αόρατη παραπομπή")
("irish" "ιρλανδικά")
("is running" "εκτελείται")
("is running" "τρέχει")
("is tuple" "είναι πλειάδα")
("ispell does not respond" "το ispell δεν ανταποκρίνεται")
("ispell is already busy" "το ispell είναι απασχολημένο")
("italian" "ιταλικά")
("italic" "πλάγια")
("italic right" "πλάγια δεξιά")
("itemize" "σημειακή απαρίθμηση")
("january" "ιανουάριος")
("japanese" "ιαπωνικά")
("july" "ιούλιος")
("jump in" "μεταπήδηση")
("june" "ιούνιος")
("justified" "πλήρως ευθυγραμισμένο")
("justify text" "πλήρης ευθυγράμμιση κειμένου")
("keep evaluated expressions" "διατήρηση αποτιμημένων παραστάσεων")
("keep unfolded" "κρατήστε το ξεδιπλωμένο")
("key" "κλειδί")
("keyboard" "πληκτρολόγιο")
("keyboard equivalent" "αντίστοιχο πλήκτρο")
("keyboard modifiers" "τροποποιητές πληκτρολογίου")
("keyboard shortcut" "πλήκτρο συντόμευσης")
("keymaps" "αντιστοιχίσεις πληκτρολογίου")
("keymaps" "keymaps")
("keyword" "λέξη-κλειδί")
("keywords" "λέξεις-κλειδιά")
("kill" "εξουδετέρωση")
("known bugs" "γνωστά σφάλματα")
("label" "ετικέτα")
("landscape" "τοπίο")
("language" "γλώσσα")
("large" "μεγάλο")
("large closing bracket" "μεγάλη δεξιά αγκύλη")
("large delimiter" "μεγάλος οροθέτης")
("large opening bracket" "μεγάλη αριστερή αγκύλη")
("large separator" "μεγάλο διαχωριστικό")
("last field" "τελευταίο πεδίο")
("last page" "τελευταία σελίδα")
("last similar" "τελευταίο παρόμοιο")
("latex command" "εντολή latex")
("latin" "latin")
("layout" "διάταξη")
("layout" "προσχέδιο/διάταξη")
("lcm" "εκπ (lcm)")
("left" "αριστερά")
("left aligned" "με αριστερή στοίχιση")
("left aligned" "τραβηγμένο αριστερά")
("left aligned" "τραβηγμένη αριστερά")
("left arrow" "αριστερό βέλος")
("left border" "αριστερό περίγραμμα")
("left cell border" "περίγραμμα αριστερού κελιού")
("left cell border" "αριστερό περίγραμμα κελιού")
("left cell padding" "αναπλήρωση αριστερού κελιού")
("left cell padding" "αριστερό γέμισμα κελιού")
("left margin" "αριστερό περιθώριο")
("left padding" "αναπλήρωση αριστερά")
("left padding" "αριστερό γέμισμα")
("left prime" "left prime")
("left slanted" "κεκλιμένο αριστερά")
("left slanted" "κλίση προς αριστερά")
("left subscript" "αριστερός κάτω δείκτης")
("left subscript" "αριστερός δείκτης")
("left superscript" "αριστερός πάνω δείκτης")
("left superscript" "αριστερός εκθέτης")
("left surrounding" "αριστερό περιστοίχισμα")
("left surrounding" "αριστερό περιστοίχισμα")
("left table border" "περίγραμμα αριστερού πίνακα")
("left table border" "αριστερό περίγραμμα πίνακα")
("left table padding" "αναπλήρωση αριστερού πίνακα")
("left table padding" "αριστερό γέμισμα πίνακα")
("leftwards" "προς τα αριστερά")
("legal" "legal")
("lemma" "λήμμα")
("length" "μήκος")
("less" "μικρότερο")
("less or equal" "μικρότερο ή ίσο")
("letter" "επιστολή")
("letter" "letter")
("license" "άδεια")
("light" "ανοιχτό")
("light" "ελαφρύ")
("light grey" "ανοιχτό γκρι")
("light grey" "ελαφρύ γκρι")
("limitations" "περιορισμοί")
("limits" "όρια")
("line" "γραμμή")
("line break" "αλλαγή γραμμής")
("line stretch" "επέκταση γραμμής")
("linear algebra" "γραμμική άλγεβρα")
("lines around" "γραμμές γύρω-γύρω")
("link" "σύνδεσμος")
("link image" "σύνδεσμος με εικόνα")
("list" "λίστα")
("list of figures" "λίστα σχημάτων")
("list of figures" "λίστα με εικόνες")
("list of tables" "λίστα πίνακων")
("list of tables" "λίστα με πίνακες")
("load" "φόρτωση")
("load" "φόρτωμα")
("load LaTeX file" "φόρτωμα αρχείου LaTeX")
("load TeX file" "φόρτωμα αρχείου TeX")
("load TeXmacs file" "φόρτωμα αρχείου TeXmacs")
("load TeXmacs style file" "φόρτωμα αρχείου στυλ TeXmacs")
("load a file" "φόρτωμα αρχείου")
("load buffer" "φόρτωμα προσωρινής αποθήκευσης")
("load buffer" "φόρτωμα buffer")
("load file" "φόρτωμα αρχείου")
("load html file" "φόρτωμα αρχείου html")
("load image" "φόρτωμα εικόνας")
("load in new window" "φόρτωμα σε νέο παράθυρο")
("load latex file" "φόρτωμα αρχείου latex")
("load more recent autosave file" "φόρτωμα πιο πρόσφατου αυτοαποθηκευμένου αρχείου")
("load tex file" "φόρτωμα αρχείου tex")
("load verbatim file" "φόρτωμα αρχείου verbatim")
("loaded" "φορτωμένο")
("loaded" "φορτώθηκε")
("logarithm" "λογάριθμος")
("logarithms" "λογάριθμοι")
("long" "μακρύς")
("long" "μακρύ")
("look and feel" "look and feel")
("look up" "αναζήτηση")
("look up" "ανεύρεση")
("lower border" "κάτω περίγραμμα")
("m modifier" "τροποποιητής m")
("macro" "μακροεντολή")
("macros" "μακροεντολές")
("magenta" "μωβ")
("magic" "μαγικό")
("magnification" "μεγένθυση")
("magnification" "μεγένθυση")
("magnification" "magnification")
("magnified" "μεγεθυμένο")
("main" "κύριο")
("main icon bar" "κύρια γραμμή εικονιδίων")
("main icon bar" "κύρια εργαλειοθήκη")
("major changes" "σημαντικές αλλαγές")
("make a page insertion" "δημιουργία εισαγωγής σελίδας")
("make a page insertion" "εισαγωγή σελίδας")
("make a subscript" "δημιουργία κάτω δείκτη")
("make a subscript" "εισαγωγή δείκτη")
("make a superscript" "δημιουργία πάνω δείκτη")
("make a superscript" "εισαγωγή εκθέτη")
("make acute" "δημιουργία οξείας")
("make acute" "εισαγωγή οξείας")
("make bar" "δημιουργία γραμμής")
("make bar" "εισαγωγή μπάρας")
("make check" "δημιουργία check")
("make check" "έλεγχος")
("make fraction" "δημιουργία κλάσματος")
("make fraction" "εισαγωγή κλάσματος")
("make grave" "δημιουργία βαρείας")
("make grave" "εισαγωγή βαρείας")
("make hat" "δημιουργία καρρέ")
("make hat" "εισαγωγή καρρέ")
("make label" "δημιουργία ετικέτας")
("make label" "εισαγωγή ετικέτας")
("make negation" "δημιουργία άρνησης")
("make negation" "εισαγωγή άρνησης")
("make page reference" "δημιουργία αναφοράς σε σελίδα")
("make page reference" "αναφορά σε σελίδα")
("make reference" "δημιουργία αναφοράς")
("make reference" "αναφορά")
("make square root" "δημιουργία τετραγωνικής ρίζας")
("make square root" "εισαγωγή τετραγωνικής ρίζας")
("make tilde" "δημιουργία περισπωμένης")
("make tilde" "εισαγωγή περισπωμένης")
("make title" "δημιουργία τίτλου")
("make title" "εισαγωγή τίτλου")
("make vector" "δημιουργία διανύσματος")
("make vector" "εισαγωγή διανύσματος")
("making donations" "δωρεές")
("making donations" "για δωρεές")
("manual" "εγχειρίδιο")
("map to" "απεικόνιση στο")
("march" "μάρτιος")
("marginal note" "παρατήρηση")
("margins" "περιθώρια")
("margins as on paper" "περιθώρια όπως στο χαρτί")
("margins as on paper" "περιθώρια όπως στο άρθρο")
("marked" "με επισήμανση")
("master" "κύριο")
("master file" "κύριο αρχείο")
("math" "μαθηματικά")
("math font" "μαθηματική γραμματοσειρά")
("math font family" "οικογένεια μαθηματικής γραμματοσειράς")
("math font series" "σειρά μαθηματικής γραμματοσειράς")
("math font shape" "σχήμα μαθηματικής γραμματοσειράς")
("mathematical" "μαθηματικό")
("mathematical and customized input" "μαθηματική και προσαρμοσμένη είσοδος")
("mathematical font" "μαθηματική γραμματοσειρά")
("mathematical formulas" "μαθηματικοί τύποι")
("mathematical input" "μαθηματική είσοδος")
("mathematical typesetting" "μαθηματική στοιχειοθεσία")
("mathematics" "μαθηματικά")
("matrices" "μαθηματικοί πίνακες (μήτρες)")
("matrix" "μαθηματικός πίνακας (μήτρα)")
("maximal" "μέγιστο")
("maximal cell height" "μέγιστο ύψος κελιού")
("maximal number of columns" "μέγιστος αριθμός στηλών")
("maximal number of rows" "μέγιστος αριθμός σειρών")
("maximal table height" "μέγιστο ύψος πίνακα")
("maximal table width" "μέγιστο πλάτος πίνακα")
("maximal table width" "μέγιστο πλάτος πίνακα")
("maximum mode" "μέγιστη λειτουργία")
("may" "μάιος")
("medium" "μεσαίο μέγεθος")
("medium" "μεσαίο")
("medium skip" "κενό μεσαίου μεγέθους")
("meminfo" "meminfo")
("merge" "συγχώνευση")
("messy" "ακατάστατος")
("meta key" "μετα-κλειδί")
("middle" "μεσαίο")
("minimal" "ελάχιστο")
("minimal cell height" "ελάχιστο ύψος κελιού")
("minimal cell width" "ελάχιστο πλάτος κελιού")
("minimal number of columns" "ελάχιστος αριθμός στηλών")
("minimal number of rows" "ελάχιστος αριθμός σειρών")
("minimal table height" "ελάχιστο ύψος πίνακα")
("minimal table width" "ελάχιστο πλάτος πίνακα")
("minimum mode" "ελάχιστη λειτουργία")
("minus" "μείον")
("miscellaneous" "miscellaneous")
("miscellaneous" "διάφορα")
("miscellaneous features" "διάφορα χαρακτηριστικά")
("mod" "mod")
("mode" "λειτουργία")
("mode dependent icons" "εικονίδια εξαρτώμενα από την λειτουργία")
("modifier" "τροποποιητής")
("modify cell alignment" "τροποποίηση στοίχισης κελιού")
("modify cell border" "τροποποίηση περιγράμματος κελιού")
("modify cell padding" "τροποποίηση γεμίσματος κελιού")
("modify cell size" "τροποποίηση μεγέθους κελιού")
("modify table border" "τροποποίηση περιγράμματος πίνακα")
("modify table padding" "τροποποίηση γεμίσματος πίνακα")
("mongolian" "μογγολικά")
("more information about GNU TeXmacs can be found in the help" "περισσότερες πληροφορίες για το GNU TeXmacs βρίσκονται στην βοήθεια")
("more information about GNU TeXmacs can be found in the help" "περισσότερες πληροφορίες για το GNU TeXmacs στην βοήθεια")
("mosaic" "mosaic")
("move" "μετακίνηση")
("move down" "μετακίνηση κάτω")
("move object" "μετακίνηση αντικειμένου")
("move to the right when finished" "στο τέλος μετακίνηση δεξιά")
("move to the right when finished" "μετακίνηση δεξιά μετά την ολοκλήρωση")
("move up" "μετακίνηση πάνω")
("multiline input" "εισόδος πολλαπλών γραμμών")
("multiline input" "εισόδος πολλών γραμμών")
("mutator tags" "ετικέτες mutator")
("my documents" "τα έγγραφά μου")
("n-th" "νιοστή")
("n-th" "ν-οστή")
("n-th root" "νιοστή ρίζα")
("n-th root" "ν-οστή ρίζα")
("name" "όνομα")
("negation" "άρνηση")
("never" "ποτέ")
("new" "νέο")
("new buffer" "νέα προσωρινή αποθήκευση")
("new buffer" "νέος buffer")
("new column" "νέα στήλη")
("new document" "νέο έγγραφο")
("new double page" "νέα διπλή σελίδα")
("new double page before" "νέα διπλή σελίδα πριν")
("new item" "νέο στοιχείο")
("new line" "νέα γραμμή")
("new macro" "νέα μακροεντολή")
("new number" "νέος αριθμός")
("new page" "νέα σελίδα")
("new page before" "νέα σελίδα πριν")
("new paragraph" "νέα παράγραφος")
("new roman" "new roman")
("new row" "νέα σειρά")
("new table" "νέος πίνακας")
("next" "επόμενος")
("next" "επόμενος / (-η)")
("next field" "επόμενο πεδίο")
("next line" "επόμενη γραμμή")
("next similar" "επόμενο παρόμοιο")
("no changes need to be saved" "καμμία αλλαγή προς αποθήκευση")
("no dictionary for" "απουσία λεξικού για")
("no first indentation" "χωρίς πρώτη εσοχή")
("no indentation" "χωρίς εσοχή")
("no line break" "χωρίς αλλαγή γραμμής")
("no matches found" "δεν βρέθηκαν αντιστοιχίες")
("no matches found for" "δεν βρέθηκαν αντιστοιχίες για")
("no more matches for" "δεν βρέθηκαν περισσότερες αντιστοιχίες για")
("no more redo information available" "το ιστορικό επαναλήψεων εξαντλήθηκε")
("no more undo information available" "το ιστορικό αναιρέσεων εξαντλήθηκε")
("no name" "χωρίς όνομα")
("no page break" "χωρίς αλλαγή σελίδας")
("no page break after" "χωρίς αλλαγή σελίδας μετά")
("no page break before" "χωρίς αλλαγή σελίδας πριν")
("no spelling errors found in text" "δεν βρέθηκαν ορθογραφικά λάθη στο κείμενο")
("no style" "χωρίς στυλ")
("none" "κανένα")
("normal" "κανονικό")
("norwegian" "νορβηγικά")
("not" "όχι")
("not equal" "μη ίσο")
("not equal" "όχι ίσο")
("not found" "δεν βρέθηκε")
("notation" "σημειογραφία")
("note" "σημείωση")
("november" "νοέμβριος")
("number" "αριθμός")
("number equation" "αρίθμηση εξίσωσης")
("number of columns" "αριθμός στηλών")
("numbered equation" "αριθμημένη εξίσωση")
("numbered equations" "αριθμημένες εξισώσεις")
("numerator" "αριθμητής")
("numeric" "αριθμητικό")
("objectives" "στόχοι")
("occurrences" "εμφανίσεις")
("october" "οκτώβριος")
("odd page footer" "υποσέλιδο σελίδας με περιττό αριθμό")
("odd page header" "κεφαλίδα σελίδας με περιττό αριθμό")
("odd page left margin" "αριστερό περιθώριο σελίδας με περιττό αριθμό")
("odd page margin" "περιθώριο σελίδας με περιττό αριθμό")
("odd page right margin" "δεξιό περιθώριο σελίδας με περιττό αριθμό")
("odd page shift" "μετατόπιση σελίδας με περιττό αριθμό")
("odd page text" "κείμενο σελίδας με περιττό αριθμό")
("off" "μη ενεργό")
("ok" "ok")
("ok" "εντάξει")
("old english" "αρχαία αγγλικά")
("old slavonic" "αρχαία σλαβικά")
("old style" "παλιό στυλ")
("on" "ενεργό")
("on cells" "στα κελιά")
("on columns" "στις στήλες")
("on entire table" "σε όλο τον πίνακα")
("on rows" "στις σειρές")
("on the footer" "στο υποσέλιδο")
("one column" "μία στήλη")
("one spelling error has been corrected" "ένα ορθογραφικό λάθος διορθώθηκε")
("online documentation" "ηλεκτρονική τεκμηρίωση")
("online help" "ηλεκτρονική βοήθεια")
("only inline tags" "μόνο εμβόλιμες ετικέτες")
("open" "άνοιγμα")
("open a new buffer" "άνοιγμα νέας προσωρινής αποθήκευσης")
("open a new buffer" "άνοιγμα νέας προσωρινής αποθήκευσης")
("open a new buffer" "νέο buffer")
("open new window" "άνοιγμα νέου παράθυρου")
("open new window" "νέο παράθυρο")
("opening" "άνοιγμα")
("operation mode" "τρόπος λειτουργίας")
("operation on named selection" "λειτουργία επί καθορισμένης επιλογής")
("operation on primary selection" "λειτουργία επί πρωτεύουσας επιλογής")
("operation on secondary selection" "λειτουργία επί δευτερεύουσας επιλογής")
("operation on ternary selection" "λειτουργία επί τριτεύουσας επιλογής")
("optical" "οπτικό")
("option" "επιλογή")
("options" "επιλογές")
("or" "ή")
("orange" "πορτοκαλί")
("orientation" "προσανατολισμός")
("origin" "προέλευση")
("original welcome message" "αρχικό μήνυμα καλωσορίσματος")
("ornamented" "διακοσμημένο")
("other" "άλλο")
("other package" "άλλο πακέτο")
("other pages" "άλλες σελίδες")
("other projects" "άλλα projects")
("other style" "άλλο στυλ")
("outlined roman" "outlined roman")
("output options" "επιλογές εξόδου")
("over" "επί")
("overbrace" "βραχίονας από πάνω")
("overlay" "επικάλυψη")
("overline" "επιγράμμιση")
("overline" "overline")
("overlined" "ανωγραμμισμένο")
("padded" "συμπληρωμένο")
("padding" "γέμισμα")
("page" "σελίδα")
("page bottom margin" "κάτω περιθώριο σελίδας")
("page break" "αλλαγή σελίδας")
("page break after" "αλλαγή σελίδας μετά")
("page break before" "αλλαγή σελίδας πριν")
("page height" "ύψος σελίδας")
("page insertion" "εισαγωγή σελίδας")
("page layout" "διάταξη σελίδας")
("page layout" "μορφή σελίδας")
("page number text" "κειμένο αριθμού σελίδας")
("page numbering" "αρίθμηση των σελίδων")
("page reference" "αναφορά σε σελίδα")
("page right margin" "δεξί περιθώριο σελίδας")
("page setup" "ρύθμιση σελίδας ")
("page top margin" "πάνω περιθώριο σελίδας")
("page type" "τύπος σελίδας")
("page width" "πλάτος σελίδας")
("paper" "χαρτί")
("paper type" "τύπος χαρτιού")
("papyrus" "πάπυρος")
("paragraph" "παράγραφος")
("paragraph mode" "λειτουργία παραγράφου")
("paragraph width" "πλάτος παραγράφου")
("paragraphs" "παράγραφοι")
("parametric curve" "παραμετρική καμπύλη")
("parametric surface" "παραμετρική επιφάνεια")
("part" "μέρος")
("past changes" "προηγούμενες αλλαγές")
("paste" "επικόλληση")
("paste from" "επικόλληση από")
("paste text" "επικόλληση κειμένου")
("path" "διαδρομή ")
("path" "path")
("perform operations on cells" "εκτέλεση λειτουργιών στα κελιά")
("perform operations on cells" "εφαρμογή τροποποιήσεων στα κελιά")
("perform operations on columns" "εκτέλεση λειτουργιών στις στήλες")
("perform operations on columns" "εφαρμογή τροποποιήσεων στις στήλες")
("perform operations on entire table" "εκτέλεση λειτουργιών σε όλο τον πίνακα")
("perform operations on entire table" "εφαρμογή τροποποιήσεων σε όλο τον πίνακα")
("perform operations on rows" "εκτέλεση λειτουργιών στις σειρές")
("perform operations on rows" "εφαρμογή τροποποιήσεων στις σειρές")
("permanent" "μόνιμο")
("person" "πρόσωπο")
("personal dictionary has been modified" "το προσωπικό σας λεξικό τροποποιήθηκε")
("phantasy" "phantasy")
("phantoms" "ανύπακτα αντικείμενα")
("philosophy" "φιλοσοφία")
("phoenician" "phoenician")
("phonetic" "phonetic")
("pink" "ροζ")
("plain" "απλή")
("plain block" "απλό μπλοκ")
("plain block" "απλό πλαίσιο/τμήμα")
("plain tabular" "απλός πίνακας δεδομένων")
("planned changes" "προβλεπόμενες αλλαγές")
("plans for the future" "σχέδια για το μέλλον")
("please" "παρακαλώ")
("please wait" "παρακαλώ περιμένετε")
("plot" "plot")
("plugin" "plugin")
("plugins" "plugins")
("plus" "συν")
("polish" "πολωνικά")
("porting TeXmacs to other platforms" "μεταφορά του TeXmacs σε άλλες πλατφόρμες")
("portrait" "πορτραίτο")
("portuguese" "πορτογαλικά")
("position" "θέση")
("position float" "τοποθέτηση μετακινούμενου")
("position floating object" "τοποθέτηση μετακινούμενου αντικειμένου")
("position the table" "τοποθέτηση του πίνακα")
("postscript" "postscript")
("postscript image" "εικόνα postscript")
("pre-alpha release" "δοκιμαστική έκδοση pre-alpha")
("preamble" "προοίμιο")
("preamble mode" "λειτουργία προοιμίου")
("preferences" "προτιμήσεις")
("presentation" "παρουσίαση")
("presentation mode" "λειτουργία παρουσίασης")
("presentation tag" "παρουσίαση γραμματοσειράς")
("presentation tag" "ετικέτα παρουσίασης")
("preview" "προεπισκόπηση")
("preview before printing" "προεπισκόπηση εκτύπωσης")
("preview command" "εντολή προεπισκόπησης")
("preview with ghostview" "προεπισκόπηση μέσω ghostview")
("previous" "προηγούμενο")
("previous field" "προηγούμενο πεδίο")
("previous similar" "προηγούμενο παρόμοιο")
("primary" "πρωτεύον")
("prime" "πρώτο")
("print" "εκτύπωση")
("print all" "εκτύπωση όλων")
("print all to file" "εκτύπωση όλων σε αρχείο")
("print page selection" "εκτύπωση επιλεγμένων σελίδων")
("print page selection to file" "εκτύπωση επιλεγμένων σελίδων στο αρχείο")
("print to postscript file" "εκτύπωση σε αρχείο postscript")
("printer" "εκτυπωτής")
("printer dpi" "ανάλυση εκτυπωτή σε dpi")
("printing command" "εντολή εκτύπωσης")
("problem" "πρόβλημα")
("professional" "επαγγελματικό")
("prog" "prog")
("prog font" "γραμματοσειρά prog")
("prog font family" "οικογένεια γραμματοσειράς prog")
("prog font series" "σειρά γραμματοσειράς prog")
("prog font shape" "σχήμα γραμματοσειράς prog")
("program" "πρόγραμμα")
("program font" "γραμματοσειρά προγράμματος")
("program mode" "λειτουργία προγράμματος")
("programming" "προγραμματισμός")
("progressive" "προοδευτικά")
("progressive" "προοδευτικό")
("project" "project")
("projects" "projects")
("prologue" "πρόλογος")
("prominent" "εξέχον")
("prompt on scripts" "προτροπή για την εκτέλεση scripts")
("prompts and default input" "προτροπές και προεπιλογή εισόδου")
("proof" "απόδειξη")
("proportional" "ανάλογο")
("proportional typewriter" "proportional typewriter")
("proposition" "πρόταση")
("pseudo code" "ψευτοκώδικας")
("query replace" "αντικατάσταση ερωτήματος")
("question" "ερώτηση")
("quit" "έξοδος")
("quotation" "παράθεμα")
("quote" "παράθεση")
("range" "εύρος")
("rank" "βαθμός/τάξη")
("really close it" "επιβεβαίωση κλεισίματος")
("really huge" "πραγματικά τεράστιο")
("really huge" "τεράστιο")
("really quit" "επιβεβαίωση εξόδου")
("really tiny" "πολύ μικροσκοπικό")
("recent" "πρόσφατα")
("recent" "πρόσφατος")
("recover autosave file" "ανάκτηση αρχείου αυτόματης αποθήκευσης")
("red" "κόκκινο")
("redo" "επανάληψη ενέργειας")
("redo undone changes" "επανάληψη μη γενόμενων αλλαγών")
("reduce" "μείωση")
("reduce bottom margin by" "μείωση κάτω περιθωρίου κατά")
("reduce left margin by" "μείωση αριστερού περιθωρίου κατά")
("reduce margins" "μείωση περιθωρίων")
("reduce right margin by" "μείωση δεξιού περιθωρίου κατά")
("reduce top margin by" "μείωση πάνω περιθωρίου κατά")
("reduce trigonometric functions" "αναγωγή τριγωνομετρικών συναρτήσεων")
("reduction even page margin" "μείωση περιθωρίου άρτιων σελίδων")
("reduction odd page margin" "μείωση περιθωρίου περιττών σελίδων")
("reduction page bottom margin" "μείωση κάτω περιθωρίου σελίδας")
("reduction page right margin" "μείωση δεξιού περιθωρίου σελίδας")
("reduction page top margin" "μείωση πάνω περιθωρίου σελίδας")
("reference" "αναφορά")
("reference guide" "οδηγός αναφοράς")
("reference guide for the TeXmacs primitives" "οδηγός αναφοράς για τα αρχέτυπα του TeXmacs")
("reference guide for the standard TeXmacs styles" "οδηγός αναφοράς για τα τυπικά στυλ του ΤeXmacs")
("reference guide for the standard TeXmacs styles" "οδηγός αναφοράς για τα βασικά στυλ του TeXmacs")
("references" "αναφορές")
("regular" "κανονικό")
("release" "έκδοση")
("reload" "επαναφόρτωση")
("remark" "σχόλιο")
("remote control" "τηλεχειρισμός")
("remove" "κατάργηση")
("remove" "αφαίρεση")
("remove all output fields" "κατάργηση όλων των πεδίων εξόδου")
("remove all output fields" "αφαίρεση όλων των πεδίων εξόδου")
("remove banner" "κατάργηση αρχικού λογότυπου")
("remove fields" "κατάργηση πεδίων")
("remove fields" "αφαίρεση πεδίων")
("remove input field" "κατάργηση του πεδίου εισόδου")
("remove input field" "αφαίρεση του πεδίου εισόδου")
("remove input field above" "κατάργηση του πεδίου εισόδου πάνω")
("remove input field above" "αφαίρεση του πεδίου εισόδου πάνω")
("remove last field" "κατάργηση τελευταίου πεδίου")
("remove next field" "κατάργηση επόμενου πεδίου")
("remove number" "κατάργηση αριθμού")
("remove number" "αφαίρεση αριθμού")
("remove package" "κατάργηση πακέτου")
("remove package" "αφαίρεση πακέτου")
("remove previous field" "κατάργηση προηγούμενου πεδίου")
("remove this switch" "κατάργηση αυτού του διακόπτη")
("remove this switch" "αφαίρεση αυτού του διακόπτη")
("renumber this page" "επαναρίθμηση αυτής της σελίδας")
("repeat" "επανάληψη")
("repeat object" "επανάληψη αντικειμένου")
("replace" "αντικατάσταση")
("replace by" "αντικατάσταση από")
("replace unrecognized styles" "αντικατάσταση μη αναγνωρίσιμων στυλ")
("replaced" "αντικαταστάθηκε")
("replaced one occurrence" "αντικαταστάθηκε μια εμφάνιση")
("reset" "επαναφορά")
("resize" "αλλαγή μεγέθους")
("resize object" "αναπροσδιορισμός μεγέθους αντικειμένου")
("resized" "αναπροσδιορίστηκε το μέγεθος")
("return" "επιστροφή")
("revert" "επαναφορά")
("revert buffer" "επαναφορά προσωρινής αποθήκευσης")
("revert buffer" "επαναφορά buffer")
("right" "δεξιά")
("right aligned" "με δεξιά στοίχιση")
("right aligned" "τραβηγμένο δεξιά")
("right arrow" "δεξιό βέλος")
("right border" "δεξί περίγραμμα")
("right cell border" "δεξί περίγραμμα κελιού")
("right cell padding" "δεξί γέμισμα κελιού")
("right margin" "δεξί περιθώριο")
("right padding" "αναπλήρωση δεξιά")
("right padding" "δεξί γέμισμα")
("right subscript" "δεξιός κάτω δείκτης")
("right subscript" "δεξιός δείκτης")
("right superscript" "δεξιός πάνω δείκτης")
("right superscript" "δεξιός εκθέτης")
("right surrounding" "δεξί περιστοίχισμα")
("right surrounding" "δεξί περιστοίχισμα")
("right table border" "περίγραμμα δεξιού πίνακα")
("right table border" "δεξί περίγραμμα πίνακα")
("right table padding" "αναπλήρωση δεξιού πίνακα")
("right table padding" "δεξί γέμισμα πίνακα")
("rightwards" "προς τα δεξιά")
("rigid" "άκαμπτο")
("rigid box" "άκαμπτο πλαίσιο")
("rigid horizontal" "άκαμπτο οριζόντια")
("rigid space" "άκαμπτο κενό")
("romanian" "ρουμανικά")
("root" "ρίζα")
("rotate backward" "περιστροφή προς τα πίσω")
("rotate forward" "περιστροφή προς τα εμπρός")
("row" "σειρά")
("row above" "σειρά πάνω")
("row below" "σειρά κάτω")
("row contains glued items" "η σειρά περιέχει εφαπτόμενα αντικείμενα")
("rows" "σειρές")
("run" "εκτέλεση")
("runic" "ρουνικά")
("running author" "τρέχων συγγραφέας")
("running title" "τρέχων τίτλος")
("russian" "ρωσικά")
("sample" "δείγμα")
("sans serif" "sans serif")
("save" "αποθήκευση")
("save TeXmacs file" "αποθήκευση αρχείου TeXmacs")
("save TeXmacs style file" "αποθήκευση αρχείου στυλ TeXmacs")
("save as" "αποθήκευση ως")
("save as LaTeX" "αποθήκευση ως LaTeX")
("save as TeX" "αποθήκευση ως TeX")
("save buffer" "αποθήκευση προσωρινής αποθήκευσης")
("save buffer" "αποθήκευση buffer")
("save buffer as" "αποθήκευση προσωρινής αποθήκευσης ως")
("save buffer as" "αποθήκευση buffer ως")
("save file" "αποθήκευση αρχείου")
("save html file" "αποθήκευση αρχείου html")
("save image" "αποθήκευση εικόνας")
("save latex file" "αποθήκευση αρχείου latex")
("save tex file" "αποθήκευση αρχείου tex")
("save this buffer" "αποθήκευση αυτής της προσωρινής αποθήκευσης")
("save this buffer" "αποθήκευση buffer")
("save verbatim file" "αποθήκευση αρχείου verbatim")
("saved" "αποθηκεύτηκε")
("scheme command" "εντολή scheme")
("screen layout" "διάταξη οθόνης")
("screen layout" "εμφάνιση οθόνης")
("screen margins" "περιθώρια οθόνης")
("script" "script")
("script above" "script πάνω")
("script below" "script κάτω")
("script script size" "script script size")
("script size" "μέγεθος script")
("scripts not accepted" "μη αποδοχή scripts")
("search" "αναζήτηση")
("search results for" "αποτελέσματα αναζήτησης για")
("search words in my documents" "αναζήτηση λέξεων στα έγγραφά μου")
("search words in the documentation" "αναζήτηση λέξεων στην τεκμηρίωση")
("search words in the source code" "αναζήτηση λέξεων στον πηγαίο κώδικα")
("searching" "αναζήτηση...")
("secondary" "δευτερεύον")
("section" "ενότητα")
("security" "ασφάλεια")
("see" "βλέπε")
("select a document style" "επιλογή στυλ εγγράφου")
("select a document style" "στυλ εγγράφου")
("select a foreground color" "επιλογή χρώματος προσκηνίου")
("select a language" "επιλογή γλώσσας")
("selected region" "επιλεγμένη περιοχή")
("selection" "επιλογή")
("selections" "επιλογές")
("seminar" "σεμινάριο")
("sending commands to TeXmacs" "αποστολή εντολών στο TeXmacs")
("separation between lines" "διαχωρισμός γραμμών")
("separation between paragraphs" "διαχωρισμός παραγράφων")
("separator" "διαχωριστικό")
("september" "Σεπτέμβριος")
("serb" "σερβικά")
("series" "σειρά")
("series|right" "σειρά|δεξιά")
("session" "συνεδρία")
("session name" "όνομα συνεδρίας")
("session type" "τύπος συνεδρίας")
("set" "ρύθμιση")
("set background color of cell" "ρύθμιση χρώματος παρασκηνίου κελιού")
("set cell mode" "ρύθμιση λειτουργίας κελιού")
("set extension center" "ρύθμιση του κέντρου επέκτασης (extension center)")
("set height" "ρύθμιση ύψους")
("set height of cell" "ρύθμιση ύψους κελιού")
("set margins" "ρύθμιση περιθωρίων")
("set n" "τιμή του ν")
("set or get environment variables" "ορισμός ή λήψη μεταβλητών περιβάλλοντος")
("set paragraph margins" "ρύθμιση περιθωρίων παραγράφου")
("set paragraph mode" "ρύθμιση λειτουργίας παραγράφου")
("set paragraph mode" "λειτουργία ρύθμιση παραγράφου")
("set paragraph mode" "ρύθμιση μορφήw παραγράφου")
("set printer dpi" "ρύθμιση dpi εκτυπωτή")
("set printing command" "ρύθμιση εντολής εκτύπωσης")
("set printing command" "ρύθμιση εντολήw εκτύπωσης")
("set span" "ρύθμιση ανοίγματος")
("set special cell properties" "ρύθμιση ειδικών ιδιοτήτων κελιού")
("set special table properties" "ρύθμιση ειδικών ιδιοτήτων πίνακα")
("set text width" "ρύθμιση πλάτους κειμένου")
("set width" "ρύθμιση πλάτους")
("set width of cell" "ρύθμιση πλάτους κελιού")
("settings" "ρυθμίσεις")
("setup printer" "ρύθμιση εκτυπωτή")
("several equations" "διάφορες εξισώσεις")
("shape" "σχήμα")
("shift" "μετατόπιση")
("shift-down" "shift-κάτω")
("shift-down" "shift-down")
("shift-right" "shift-δεξιά")
("shift-right" "shift-right")
("short" "σύντομο")
("show" "προβολή")
("show" "εμφάνιση")
("show all parts" "προβολή όλων των μερών")
("show header and footer" "προβολή κεφαλίδας και υποσέλιδου")
("show header and footer" "εμφάνιση κεφαλίδας και υποσέλιδου")
("show hidden" "προβολή κρυμμένων")
("show hidden" "εμφάνιση κρυμμένων")
("show on screen" "προβολή στην οθόνη")
("show one part" "προβολή ενός μέρους")
("show several parts" "προβολή  διαφόρων μερών")
("show timings" "προβολή χρόνου εκτέλεσης")
("shrinking factor" "παράγοντας σμίκρυνσης")
("signature" "υπογραφή")
("simplification" "απλοποίηση")
("simplified evaluation of formulas" "απλοποιημένη αποτίμηση των τύπων")
("simplified menus" "απλουστευμένα μενού")
("simplify" "απλοποίηση")
("sine" "ημίτονο")
("size" "μέγεθος")
("size limits" "όρια μεγέθους")
("size tag" "μεγέθος γραμματοσειράς")
("size tag" "ετικέτα μεγέθους γυρτά")
("slanted" "κεκλιμένο")
("slanted" "γυρτά")
("slides" "διαφάνειες")
("sloppy" "ατημέλητα")
("slovene" "σλοβενικά")
("small" "μικρό μέγεθος")
("small" "μικρό")
("small caps" "καπιταλάκια")
("small figure" "μικρό σχήμα")
("small figure" "μικρή εικόνα")
("small skip" "μικρό κενό")
("small table" "μικρός πίνακας")
("smash" "συντριβή")
("solution" "λύση")
("sound" "ήχος")
("source" "πηγαίο")
("source code" "πηγαίος κώδικας")
("source tags" "πηγαίες ετικέτες")
("space" "διάστημα")
("space between lines" "διάστημα γραμμών")
("space between paragraphs" "διάστημα παραγράφων")
("spacing" "διάστημα")
("spanish" "ισπανικά")
("special" "ειδικό")
("special cell properties" "ειδικές ιδιότητες κελιού")
("special functions" "ειδικές συναρτήσεις")
("special properties" "ειδικές ιδιότητες")
("special table properties" "ειδικές ιδιότητες πίνακα")
("specific" "συγκεκριμένο")
("specify the size of the table" "ορισμός του μεγέθους πίνακα")
("spell" "ορθογραφία")
("spell checking complete" "ο ορθογραφικός έλεγχος ολοκληρώθηκε")
("spelling error" "ορθογραφικό λάθος")
("spelling errors have been corrected" "τα ορθογραφικά λάθη διορθώθηκαν")
("split" "διαίρεση")
("split" "χωρισμός")
("split session" "διαίρεση συνεδρίας")
("split session" "χωρισμένη συνεδρία")
("square root" "τετραγωνική ρίζα")
("standard" "τυπικό")
("standard TeXmacs styles" "τυπικά στυλ του TeXmacs")
("standard TeXmacs styles" "συνήθη στυλ")
("standard environment variables" "μεταβλητές τυπικού περιβάλλοντος")
("standard environment variables" "συνήθεις μεταβλητές περιβάλλοντος")
("standard formats" "τυπικές μορφές")
("standard formats" "συνήθεις μορφές")
("start" "έναρξη")
("start a new chapter" "έναρξη νέου κεφαλαίου")
("start a new section" "έναρξη νέας ενότητας")
("start an interactive session" "έναρξη αλληλεπίδρασης")
("statistics" "στατιστικά")
("status bar" "γραμμή κατάστασης")
("status bar" "γραμμή κατάστασης ")
("stretch" "τάνυσμα")
("stretch" "τέντωμα")
("stretchable" "τανυόμενο")
("stretchable horizontal" "τανυόμενο οριζόντια")
("stretchable horizontal" "τανυόμενο οριζοντίως")
("stretchable vertical" "τανυόμενο κατακόρυφα")
("stretchable vertical" "τανυόμενο κατακορύφως")
("stretched" "τεντωμένο")
("strict Ascii" "αυστηρά Ascii")
("strike through" "μεσογραμμισμένο")
("stroke" "παύλα")
("stroke" "πλήγμα")
("strokes" "παύλες")
("strokes" "πλήγματα")
("strong" "strong")
("strong" "ισχυρό")
("structural" "structural")
("style" "στυλ")
("styles" "στυλ")
("stylesheet language" "γλώσσα stylesheet")
("sub" "υπό")
("subparagraph" "υποπαράγραφος")
("subscript" "κάτω δείκτης")
("subscript" "δείκτης")
("subsection" "υποενότητα")
("subsub" "υπό-υπό")
("subsubsection" "υπό-υποενότητα")
("subtable" "υποπίνακας")
("subtitle" "υπότιτλος")
("summarized" "συνοψισμένο")
("summary" "περίληψη")
("summary of the principal TeXmacs tags" "περίληψη των κύριων ετικέτων στο TeXmacs")
("superpose" "υπέρθεση")
("superposed" "υπερτεθειμένο")
("superscript" "πάνω δείκτης")
("superscript" "εκθέτης")
("surface" "επιφάνεια")
("swedish" "σουηδικά")
("swell" "διόγκωση")
("swiss" "ελβετικά")
("switch" "εναλλαγή")
("switch" "αλλαγή")
("switch to first" "αλλαγή στο πρώτο")
("switch to formula style" "αλλαγή σε στυλ μαθηματικού τύπου")
("switch to last" "αλλαγή στο τελευταίο")
("switch to next" "αλλαγή στο επόμενο")
("switch to previous" "αλλαγή στο προηγούμενο")
("switching and folding" "εναλλαγή και δίπλωση")
("switching and folding" "switching and folding")
("symbol" "σύμβολο")
("system command" "εντολή του συστήματος")
("system environment variables" "μεταβλητές περιβάλλοντος του συστήματος")
("tab" "tab")
("tabbed" "στηλοθετημένο")
("table" "πίνακας")
("table command" "εντολή πίνακα")
("table height" "ύψος πίνακα")
("table of contents" "πίνακας περιεχομένων")
("table width" "πλάτος πίνακα")
("tables" "πίνακες")
("tabular" "πίνακας δεδομένων")
("tabular material" "υλικό σε μορφή πίνακα")
("tangent" "εφαπτομένη")
("teXmacs as an interface" "το teXmacs ως διεπαφή")
("teXmacs fonts" "γραμματοσειρές του teXmacs")
("teXmacs notice" "ανακοίνωση του teXmacs")
("teXmacs plugins" "plugins του teXmacs")
("teXmacs style files" "αρχεία στυλ του teXmacs")
("ternary" "τριτεύον")
("test" "δοκιμή")
("tex" "tex")
("text" "κείμενο")
("text font" "γραμματοσειρά κειμένου")
("text height correction" "διόρθωση ύψους κειμένου")
("text width" "πλάτος κειμένου")
("texts" "κείμενα")
("th century bc" "ος αιώνας πχ")
("th root" "-οστή ρίζα")
("thai" "ταϋλανδικά")
("the TeXmacs authors" "οι συγγραφείς του TeXmacs")
("the TeXmacs format" "η μορφή του TeXmacs")
("the application did not send its usual startup banner" "η εφαρμογή δεν έστειλε το συνηθισμένο αρχικό λογότυπο")
("the application did not send its usual startup banner" "η εφαρμογή δεν έστειλε το συνηθισμένο banner εκκίνησης")
("the application does not reply" "η εφαρμογή δεν ανταποκρίνεται")
("the application is already running" "η εφαρμογή είναι ήδη σε λειτουργία")
("the boxes produced by the typesetter" "τα πλαίσια που παράγονται από τον στοιχειοθέτη")
("the buffer has not been saved" "η προσωρινή αποθήκευση δεν έχει αποθηκευτεί")
("the buffer has not been saved" "το buffer δεν έχει αποθηκευτεί")
("the graphical user interface" "η γραφική διεπαφή με τον χρήστη")
("the leaves of TeXmacs trees" "τα φύλλα του δένδρου του TeXmacs")
("the mycas example" "το παράδειγμα του mycas")
("the primitive TeXmacs constructs" "οι αρχέτυπες δομές του TeXmacs")
("the standard TeXmacs styles" "τα τυπικά στυλ του ΤeXmacs")
("the standard TeXmacs styles" "τα συνήθη στυλ του TeXmacs")
("theorem" "θεώρημα")
("there are unsaved files" "υπάρχουν μη αποθηκευμένα αρχεία")
("this buffer has not been saved" "αυτη η προσωρινή αποθήκευση δεν έχει αποθηκευθεί")
("this buffer has not been saved" "αυτός ο buffer δεν έχει αποθηκευθεί")
("this column" "αυτή η στήλη")
("this document has been produced using" "αυτό το έγγραφο έχει παραχθεί με")
("this document has been produced using" "αυτό το έγγραφο έχει παραχθεί με την χρησιμοποίηση του")
("this line" "αυτή η γραμμή")
("this page" "αυτή η σελίδα")
("this page footer" "το υποσέλιδο αυτής της σελίδας")
("this page header" "η κεφαλίδα αυτής της σελίδας")
("this row" "αυτή η σειρά")
("thumbnails" "μικρογραφίες")
("tilda" "tilda")
("tilde" "περισπωμένη")
("times" "times")
("times" "επί")
("tiny" "μικροσκοπικό")
("title" "τίτλος")
("to the left" "στα αριστερά")
("to the right" "στα δεξιά")
("today" "σήμερα")
("tools" "εργαλεία")
("top" "πάνω")
("top" "κορυφή")
("top border" "ανώτερο περίγραμμα")
("top border" "πάνω περίγραμμα")
("top cell border" "περίγραμμα πάνω κελιού")
("top cell border" "πάνω περίγραμμα κελιού")
("top cell padding" "αναπλήρωση πάνω κελιού")
("top cell padding" "πάνω γέμισμα κελιού")
("top level" "πάνω επίπεδο")
("top level" "πρώτο επίπεδο")
("top margin" "πάνω περιθώριο")
("top margin" "πάνω περιθώριο")
("top padding" "πάνω αναπλήρωση")
("top padding" "πάνω γέμισμα")
("top table border" "περίγραμμα πάνω πίνακα")
("top table border" "πάνω περίγραμμα πίνακα")
("top table padding" "αναπλήρωση πάνω πίνακα")
("top table padding" "πάνω γέμισμα πίνακα")
("translate" "μετάφραση")
("transpose" "transpose")
("traversal" "διέλευση")
("tree" "δένδρο")
("triangularize" "τριγωνοποιώ")
("trigonometric" "τριγωνομετρική")
("trigonometry" "τριγωνομετρία")
("tuple" "πλειάδα")
("turkish" "τουρκικά")
("tutorial" "οδηγός εκμάθησης")
("tutorial" "φροντιστηριακό")
("two columns" "δύο στήλες")
("type" "τύπος")
("type" "πληκτρολόγηση")
("type a latex command followed by" "εισαγωγή εντολής latex και μετά")
("type a latex command followed by" "πληκτρολόγηση εντολής latex ακολουθούμενης από")
("type body" "εισαγωγή σώματος")
("type body" "πληκτρολόγηση σώματος")
("type denominator" "εισαγωγή παρονομαστή")
("type denominator" "πληκτρολόγηση παρονομαστή")
("type numerator" "εισαγωγή ονομαστή")
("type numerator" "πληκτρολόγηση ονομαστή")
("type script" "εισαγωγή script")
("type script" "πληκτρολόγηση script")
("typesetted boxes" "στοιχειοθετημένα πλαίσια")
("typewriter" "typewriter")
("typewriter" "typewriter")
("typewriter" "γραφομηχανή")
("typewriter small caps" "καπιταλάκια σε typewriter")
("typewriter small caps" "καπιταλάκια σε typewriter")
("typewriter small caps" "καπιταλάκια γραφομηχανής")
("typing a simple text" "πληκτρολόγηση απλού κειμένου")
("typing simple texts" "πληκτρολόγηση απλών κειμένων")
("ugaritic" "ugaritic")
("ukrainian" "ουκρανικά")
("underbrace" "αγκύλη έκτασης από κάτω")
("underbrace" "βραχίονας από κάτω")
("underline" "υπογράμμιση")
("underlined" "υπογραμμισμένο")
("undo" "αναίρεση ενέργειας")
("undo last changes" "αναίρεση τελευταίων αλλαγών")
("unfold all fields" "ξεδίπλωμα όλων των πεδίων")
("unroll" "ξετύλιγμα")
("up" "πάνω")
("update" "ανανέωση")
("update from web" "ανανέωση από το διαδίκτυο")
("update image links" "ανανέωση συνδέσμων με εικόνες")
("update image links" "ανανέωση συνδέσμων σε εικόνες")
("update web site" "ενημέρωση ιστοσελίδας")
("upper border" "ανώτερο περίγραμμα")
("upright" "όρθια")
("upwards" "προς τα πάνω")
("use MathML" "χρήση MathML")
("use TeXmacs" "χρήση TeXmacs")
("use a black color" "χρήση μαύρου χρώματος")
("use a blue color" "χρήση μπλε χρώματος")
("use a bold font" "χρήση γραμματοσειράς σε bold")
("use a bold font" "χρήση έντονης γραμματοσειράς")
("use a brown color" "χρήση καφέ χρώματος")
("use a calligraphic font" "χρήση καλλιγραφικής γραμματοσειράς")
("use a green color" "χρήση πράσινου χρώματος")
("use a grey color" "χρήση γκρι χρώματος")
("use a magenta color" "χρήση μωβ χρώματος")
("use a orange color" "χρήση πορτοκαλί χρώματος")
("use a orange color" "χρήση πορτοκαλιού χρώματος")
("use a pink color" "χρήση ροζ χρώματος")
("use a red color" "χρήση κόκκινου χρώματος")
("use a sans serif font" "χρήση γραμματοσειράς sans serif")
("use a typewriter font" "χρήση γραμματοσειράς typewriter")
("use a white color" "χρήση λευκού χρώματος")
("use a yellow color" "χρήση κίτρινου χρώματος")
("use blackboard bold font" "χρήση γραμματοσειράς blackboard bold")
("use bold font series" "χρήση γραμματοσειράς σε bold")
("use bold font series" "χρήση έντονης γραμματοσειράς")
("use calligraphical font" "χρήση καλλιγραφικής γραμματοσειράς")
("use footnote font size" "χρήση μεγέθους γραμματοσειράς για υποσημειώσεις")
("use footnote font size" "χρήση μεγέθους γραμματοσειράς υποσημείωσης")
("use fraktur font" "χρήση γραμματοσειράς fraktur")
("use huge font size" "χρήση τεράστιου μεγέθους της γραμματοσειράς")
("use huge font size" "χρήση γραμματοσειράς τεράστιου μεγέθους")
("use italic font shape" "χρήση πλάγιου σχήματος της γραμματοσειράς")
("use italic font shape" "χρήση γραμματοσειράς πλάγιου σχήματος")
("use large font size" "χρήση μεγάλου μεγέθους της γραμματοσειράς")
("use large font size" "χρήση γραμματοσειράς μεγάλου μεγέθους")
("use left hand column as border" "χρήση αριστερής στήλης ως περίγραμμα")
("use medium font series" "χρήση μεσαίου μεγέθους της γραμματοσειράς")
("use medium font series" "χρήση γραμματοσειράς μεσαίου μεγέθους")
("use normal font size" "χρήση κανονικού μεγέθους της γραμματοσειράς")
("use normal font size" "χρήση γραμματοσειράς κανονικού μεγέθους")
("use package" "χρήση πακέτου")
("use paragraph width" "χρήση πλάτους παραγράφου")
("use really huge font size" "χρήση πραγματικά τεραστίου μεγέθους της γραμματοσειράς")
("use really huge font size" "χρήση γραμματοσειράς τεραστίου μεγέθους")
("use right font shape" "χρήση ορθού σχήματος της γραμματοσειράς")
("use right font shape" "χρήση γραμματοσειράς ορθού σχήματος")
("use right hand column as border" "χρήση δεξιάς στήλης ως περίγραμμα")
("use roman font family" "χρήση γραμματοσειράς οικογένειας roman")
("use row above as border" "χρήση παραπάνω σειράς ως περίγραμμα")
("use row below as border" "χρήση παρακάτω σειράς ως περίγραμμα")
("use sans serif font family" "χρήση γραμματοσειράς οικογένειας sans serif")
("use script font size" "χρήση μεγέθους script της γραμματοσειράς")
("use script font size" "χρήση γραμματοσειράς μεγέθους script")
("use slanted font shape" "χρήση κεκλιμένου σχήματος της γραμματοσειράς")
("use slanted font shape" "χρήση γραμματοσειράς λοξού σχήματος")
("use small capitals" "χρήση μικρών κεφαλαίων")
("use small font size" "χρήση μικρού μεγέθους της γραμματοσειράς")
("use small font size" "χρήση γραμματοσειράς μικρού μεγέθους")
("use small-caps font shape" "χρήση μορφής καπιταλάκια της γραμματοσειράς")
("use small-caps font shape" "χρήση γραμματοσειράς σχήματος καπιταλάκια")
("use the blackboard bold font" "χρήση γραμματοσειράς blackboard bold")
("use the fraktur font" "χρήση γραμματοσειράς fraktur")
("use tiny font font size" "χρήση μικροσκοπικού μεγέθους της γραμματοσειράς")
("use tiny font font size" "χρήση γραμματοσειράς μικροσκοπικού μεγέθους")
("use typewriter font family" "χρήση γραμματοσειράς οικογένειας typewriter")
("use very large font size" "χρήση πολύ μεγάλου μεγέθους της γραμματοσειράς")
("use very large font size" "χρήση γραμματοσειράς πολύ μεγάλου μεγέθους")
("user manual" "εγχειρίδιο χρήσης")
("user provided icons" "εικονίδια που παρέχονται από τον χρήστη")
("users of Cyrillic languages" "χρήστες κυριλλικών γλωσσών")
("utf-8 with inputenc LaTeX package" "πακέτο LaTeX Utf-8 με inputenc")
("value" "τιμή")
("variable" "variable")
("variable" "μεταβλητή")
("variant" "παραλλαγή")
("vector" "διάνυσμα")
("verbatim" "verbatim")
("verse" "εδάφιο")
("vertical" "κατακόρυφα")
("vertical" "κάθετα")
("vertical after" "κατακόρυφα μετά")
("vertical after" "κάθετα μετά")
("vertical alignment" "κατακόρυφη στοίχιση")
("vertical alignment" "κάθετη στοίχιση")
("vertical before" "κατακόρυφα πριν")
("vertical before" "κάθετα πριν")
("vertical cell alignment" "κατακόρυφη στοίχιση κελιού")
("vertical cell alignment" "κάθετη στοίχιση κελιού")
("vertical part" "κατακόρυφο τμήμα")
("vertical part" "κάθετο τμήμα")
("vertical position" "κατακόρυφη θέση")
("vertical position" "κάθετη θέση")
("vertical space" "κατακόρυφο διάστημα")
("vertical space" "κάθετο διάστημα")
("vertical space after" "κατακόρυφο διάστημα μετά")
("vertical space before" "κατακόρυφο διάστημα πριν")
("vertical table alignment" "κατακόρυφη στοίχιση πίνακα")
("vertical table alignment" "καθετη στοίχιση πίνακα")
("vertically align cell to the base" "κατακόρυφη στοίχιση κελιού στη βάση")
("vertically align cell to the base" "κάθετη στοίχιση κελιού στη βάση")
("vertically center the cell" "κατακόρυφο κεντράρισμα του κελιού")
("vertically center the cell" "κάθετο κεντράρισμα του κελιού")
("very large" "πολύ μεγάλο")
("very small" "πολύ μικρό")
("vietnamese" "βιετναμέζικα")
("view" "επισκόπηση")
("visible" "ορατό")
("warning" "προειδοποίηση")
("web" "διαδίκτυο")
("welcome" "καλωσήλθατε")
("welcome to GNU TeXmacs" "καλωσήλθατε στο GNU TeXmacs")
("what is new" "τι νέο")
("when finished" "όταν τελείωσει")
("while" "while")
("white" "λευκό")
("whitespace" "κενό διάστημα")
("wide accent" "πλατύς τόνος")
("wide bar" "πλατιά γραμμή")
("wide bar" "πλατιά μπάρα")
("width" "πλάτος")
("width is exactly the specified width" "το πλάτος είναι ακριβώς το καθορισμένο")
("width is maximum of specified width and box width" "το πλάτος είναι το μέγιστο από: το καθορισμένο και το πλάτος πλαισίου")
("width is minimum of specified width and box width" "το πλάτος είναι το ελάχιστο από: το καθορισμένο και το πλάτος πλαισίου")
("width magnification" "μεγέθυνση πλάτους")
("window" "παράθυρο")
("window height" "ύψος παραθύρου")
("window width" "πλάτος παραθύρου")
("windows key" "πλήκτρο των Windows")
("windows key" "κλειδί των Windows")
("with" "με")
("wrap lines" "αναδίπλωση γραμμών")
("write a macro" "γράψτε μια μακροεντολή")
("write a macro" "γράψτε μια μακροεντολή")
("write a name" "γράψτε ένα όνομα")
("write a name" "γράψτε ένα όνομα")
("write bold mathematics" "γραφή μαθηματικών σε bold")
("write bold mathematics" "γράψτε μαθηματικά bold")
("write bold text" "γράψτε κείμενο σε bold")
("write bold text" "γράψτε κείμενο bold")
("write italic text" "γράψτε κείμενο σε italic")
("write italic text" "γράψτε κείμενο italic")
("write sample text" "γράψτε δείγμα κειμένου")
("write sample text" "γράψτε δείγμα κειμένου")
("write strong text" "γράψτε κείμενο σε strong")
("write strong text" "γράψτε κείμενο strong")
("write typewriter text" "γράψτε κείμενο σε typewriter")
("write typewriter text" "γράψτε κείμενο typewriter")
("write verbatim text" "γράψτε κείμενο σε verbatim")
("write verbatim text" "γράψτε κείμενο verbatim")
("writing data converters" "γράφοντας μετατροπείς δεδομένων")
("writing data converters" "γράφοντας μετατροπείς δεδομένων")
("writing your own style files" "γράφοντας τα δικά σας αρχεία στυλ")
("written with TeXmacs" "γραμμένο με το TeXmacs")
("yellow" "κίτρινο")
("you can also obtain" "μπορείτε επίσης να αποκτήσετε")
("your document is back in its original state" "το έγγραφό σας επανήλθε στην αρχική του κατάσταση")
("your first interface" "η πρώτη σας διεπαφή")
("your language" "η γλώσσα σας")
("zoom" "ζουμ")
("zoom in" "μεγέθυνση")
("zoom out" "σμίκρυνση")
