("\"encryption\" features from the preference panel" "fonctions de cryptage du panneau de préférences")
("(Re)Build autocompletion index" "(Re)Construire indexe d'autocomplétion")
("Bibtex command" "commande Bibtex")
("GNU" "GNU")
("LaTeX" "LaTeX")
("TeX" "TeX")
("a modifier" "modificateur A")
("a series" "série A")
("a.C.M. computing class" "classification ACM")
("a.M.S. subject class" "classification MSC")
("abbreviated authors" "auteurs abrégés")
("abbreviation" "abréviation")
("about" "à propos de")
("about menu" "à propos de")
("above" "en haut")
("abreviated authors" "auteurs abrégés")
("abstract" "résumé")
("accent" "accent")
("accent above" "accent au-dessus")
("accent below" "accent en dessous")
("accept" "accepter")
("accept all scripts" "accepter tous les scripts")
("accept during this pass" "accepter pendant cette passe")
("accept no scripts" "ne jamais accepter de scripts")
("accept script" "accepter script")
("account" "compte")
("acknowledgment" "remerciements")
("acknowledgments" "remerciements")
("acronym" "sigle")
("action" "action")
("activate" "activer")
("activate hidden" "activer et cacher")
("activate once" "activer une fois")
("activation" "activation")
("active link types" "types de lien actifs")
("acute" "aigu")
("add" "ajouter")
("add abstract information" "ajouter information de résumé")
("add author information" "ajouter information d'auteur")
("add branch after" "ajouter une branche avant")
("add branch before" "ajouter une branche après")
("add other package" "ajouter un autre paquetage")
("add package" "ajouter paquetage")
("add style package" "ajouter style")
("add switch after" "ajouter commutateur après")
("add switch before" "ajouter commutateur avant")
("add title information" "ajouter information de titre")
("addition" "addition")
("address" "adresse")
("address block" "bloc d'adresse")
("adjust" "ajuster")
("adjust limits" "ajuster les limites")
("advanced" "avancée")
("advanced font customization" "personnalisation avancée de police")
("advanced layout features" "mise en page avancée")
("affiliation" "affiliation")
("after" "après")
("albanian" "albanais")
("algorithm" "algorithme")
("align cell to the bottom" "aligner la cellule en bas")
("align cell to the decimal comma" "aligner sur la virgule décimale")
("align cell to the decimal dot" "aligner sur le point décimal")
("align cell to the left" "aligner la cellule à gauche")
("align cell to the right" "aligner la cellule à droite")
("align cell to the top" "aligner la cellule en haut")
("align table at axis" "aligner sur l'axe")
("align table at base of left column" "aligner tableau à la base de la colonne à gauche")
("align table at base of middle column" "aligner tableau à la base de la colonne au centre")
("align table at base of origin column" "aligner tableau à la base de la colonne d'origine")
("align table at base of right column" "aligner tableau à la base de la colonne à droite")
("align table at fraction bar height" "aligner tableau à la hauteur des barres des fractions")
("align table at the base of bottom row" "aligner tableau à la base de la ligne du bas")
("align table at the base of middle row" "aligner tableau à la base de la ligne du milieu")
("align table at the base of origin row" "aligner tableau à la base de la ligne d'origine")
("align table at the base of top row" "aligner tableau à la base de la ligne du haut")
("align table at the bottom" "aligner tableau en bas")
("align table at the center" "aligner tableau au centre")
("align table at the horizontal center" "aligner tableau au centre horizontal")
("align table at the left" "aligner tableau à gauche")
("align table at the top" "aligner tableau en haut")
("align table to the right" "aligner tableau à droite")
("align text to the left" "aligner le texte à gauche")
("align text to the right" "aligner le texte à droite")
("aligned" "aligné")
("alignment" "alignement")
("alignment of balloon" "alignement du ballon")
("all" "le tout")
("all cells" "toutes les cellules")
("all data attached to this identity will be lost" "toutes les données associées à cette identité seront perdues")
("all saved passphrases will be lost forever" "toutes les phrases secrètes enregistrées seront perdues à jamais")
("allow" "permettre")
("allow for macro definitions in preamble" "permettre des définitions de macros dans le préambule")
("allowed extension" "extension permise")
("allowed page height extension" "extension de hauteur de page autorisée")
("allowed page height reduction" "réduction de hauteur de page autorisée")
("allowed positions" "positions autorisées")
("allowed positions of floating object" "positions autorisées de l'objet flottant")
("allowed reduction" "réduction permise")
("alpha release" "version alpha")
("alpha transparency" "transparence alpha")
("also on paper" "drapeaux à l'impression")
("alt key" "touche alt")
("alter" "alterner")
("alternate" "alternatif")
("alternate except here" "alterner sauf ici")
("alternate from here on" "alterner à partir d'ici")
("alternate only here" "alterner seulement ici")
("alternate until here" "alterner jusqu'à ici")
("alternative specification" "spécification alternative")
("always" "toujours")
("american" "américain")
("amplified" "amplifié")
("and" "et")
("and perform casual settings from the \"Encryption\" tab" "et effectuez des réglages occasionnels à partir de l'onglet «Cryptage»")
("angular" "angulaire")
("animate" "animer")
("animate folding" "animer pliage")
("animate unfolding" "animer dépliage")
("animated" "animé")
("animation" "animation")
("animation toolbar" "barre d'animation")
("annotate" "annoter")
("answer" "réponse")
("answer field" "champ de réponse")
("answer to question" "réponse à la question")
("answers only" "réponses seulement")
("any" "tous")
("appear" "apparaître")
("appendix" "annexe")
("apply" "appliquer")
("apply macro" "appliquer la macro")
("apply macro once" "appliquer la macro une fois")
("approximate" "approximatif")
("april" "avril")
("arab" "arabe")
("arc" "arc")
("arc cosine" "arc cosinus")
("arc sine" "arc sinus")
("arc tangent" "arc tangente")
("arch series" "série arch")
("archaic" "archaïque")
("architecture" "architecture")
("are you sure you want to delete collected public keys" "êtes-vous sûr de vouloir supprimer les clés publiques collectées")
("are you sure you want to delete selected public keys" "êtes-vous sûr de vouloir supprimer les clés publiques sélectionnées")
("are you sure you want to delete selected secret keys" "êtes-vous sûr de vouloir supprimer les clés secrètes sélectionnées")
("are you sure you want to destroy the wallet" "êtes-vous sûr de vouloir détruire le portefeuille")
("argument" "argument")
("arithmetic" "arithmétique")
("armenian" "arménien")
("arrow" "flèche")
("arrows" "flèches")
("art frame" "cadre artistique")
("article" "article")
("arxiv category" "catégorie ArXiv")
("as on paper" "comme sur le papier")
("as visual grid" "comme grille visuelle")
("aspect" "aspect")
("assign" "changer")
("at fraction bar height" "à la hauteur des barres des fractions")
("at the baseline" "à la ligne de base")
("at the bottom" "en bas")
("at the left" "à gauche")
("at the middle" "au milieu")
("at the right" "à droite")
("at the top" "en haut")
("attach" "attacher")
("attach buffer to which project" "attacher le tampon à un projet")
("attach master" "attacher un document maître")
("august" "août")
("author" "auteur")
("authorize" "authoriser")
("auto" "auto")
("auto-save file" "sauvegarde automatique")
("automatic" "automatique")
("automatic brackets" "parenthèses automatiques")
("automatic content generation" "génération automatique de contenu")
("automatic correction" "correction automatique")
("automatic program brackets" "parenthèses automatiques dans des programmes")
("automatic quotes" "guillemets automatiques")
("automatically close brackets" "fermer automatiquement les parenthèses")
("automatically generated content" "génération automatique de contenu")
("automatically import bibliographies when opening files" "importer automatiquement des bibliographies lors de l'ouverture de fichiers")
("automatically remember all passphrases in the wallet" "se souvenir automatiquement de toutes les phrases secrètes du portefeuille")
("automatically save" "sauvegarde automatique")
("autosave" "sauvegarde automatique")
("axiom" "axiome")
("axis" "axe")
("b series" "série B")
("back" "précédent")
("background" "arrière-plan")
("background color" "couleur de fond")
("background evaluations" "évaluations en arrière-plan")
("backtrace errors" "montrer pile des erreurs")
("backward replace" "remplacement en arrière")
("backward search" "recherche en arrière")
("bad data format" "mauvais format de fichier")
("bar" "barre")
("bard" "bard")
("base" "base")
("base level" "niveau inférieur")
("baseline" "ligne de base")
("bashkirian" "bashkirien")
("basic" "base")
("basic communication using pipes" "communication de base par tubes")
("basic data types" "types de base")
("basic types" "types de base")
("be useful" "soyez utile")
("beamer" "beamer")
("beamer formats" "formats de vidéoprojecteur")
("beamer theme" "thème de présentation")
("become a TeXmacs developer" "devenez un développeur TeXmacs")
("before" "avant")
("begin" "début")
("below" "en bas")
("bench" "chronométrer")
("bend bottom" "plier en bas")
("bend corner" "plier le coin")
("bend diagonal" "plier coins opposés")
("bend in" "plier")
("bend out" "plier")
("beta release" "version bêta")
("bezier" "bézier")
("bibTeX command" "commande BibTeX")
("bibliography" "bibliographie")
("bibliography file" "fichier de bibliographie")
("bibliography style" "style de bibliographie")
("bidirectional" "bidirectionnel")
("big" "grand")
("big environment box" "grande boîte d'environnement")
("big figure" "grande figure")
("big focus" "grand focus")
("big operator" "grand opérateur")
("big skip" "grand saut")
("big table" "grand tableau")
("binary operation" "opération binaire")
("binary operator" "opérateur binaire")
("binary relation" "relation binaire")
("bitmap resolution (dpi)" "résolution bitmap (points par pouce)")
("black" "noir")
("black floral I" "floral noir I")
("black floral II" "floral noir II")
("blackboard bold" "tableau noir gras")
("blackboard embold" "tableau noir gras")
("blackboard math" "tableau noir math")
("blackletter" "lettre noir")
("blank column" "colonne vide")
("blank row" "ligne vide")
("block" "bloc")
("block content" "contenu de bloc")
("block of code" "bloc de code")
("blue" "bleu")
("blur" "flouter")
("body" "corps")
("bold" "gras")
("book" "livre")
("border" "bordure")
("both" "les deux")
("both versions" "les deux versions")
("bottom" "en bas")
("bottom baseline" "ligne de base en bas")
("bottom border" "bordure du bas")
("bottom cell border" "bordure du bas de la cellule")
("bottom cell padding" "espacement du bas de la cellule")
("bottom margin" "marge du bas")
("bottom padding" "espacement du bas")
("bottom table border" "bordure du bas du tableau")
("bottom table padding" "espacement du bas du tableau")
("bottom tools" "outils en bas de fenêtre")
("box" "case")
("branch" "branche")
("break" "saut")
("breaking" "sauts")
("breve" "demi-cercle")
("british" "britannique")
("broken white" "blanc cassé")
("brown" "brun")
("browse" "naviguer")
("browse back" "naviguer vers précédent")
("browse forward" "naviguer vers suivant")
("browse modules documentation" "documentation des modules")
("browse web" "naviguer sur le réseau")
("browser" "navigateur")
("buffer" "tampon")
("buffer management" "gestion des tampons")
("buffer must be on disk" "le tampon doit être sur le disque")
("buffer must have a name" "le tampon doit avoir un nom")
("build buffer" "reconstruire tampon")
("build buffer in" "reconstruire tampon dans")
("build directory" "reconstruire répertoire")
("build directory in" "reconstruire répertoire dans")
("build link pages" "construire les pages de liens")
("build-all" "tout construire")
("bulgarian" "bulgare")
("bullet" "puce")
("bullets" "puces")
("bump" "bosse")
("busy" "en cours")
("by" "par")
("by typing" "en tapant")
("bytes free" "octets libres")
("bytes used" "octets utilisés")
("cJK" "cJK")
("cJK spacing" "espacement CJK")
("calculus" "calcul différentiel")
("calligraphic" "calligraphique")
("cancel" "annuler")
("cancelled" "annulé")
("cannot download directory to file" "impossible de télécharger le répertoire dans le fichier")
("cannot rename across different servers" "renommage impossible à travers différents serveurs")
("cannot upload directory to file" "impossible de télécharger le répertoire dans le fichier")
("caps-lock key" "touche majuscules")
("cartesian" "cartésien")
("carved wood" "bois sculpté")
("case" "choisir")
("case-insensitive search" "recherche insensible à la casse")
("categories" "catégories")
("category" "catégorie")
("cc" "copies à")
("cell" "cellule")
("cell background color" "couleur de la cellule")
("cell border" "bordure de la cellule")
("cell height" "hauteur de la cellule")
("cell operation mode" "mode d'opération sur les cellules")
("cell properties" "propriétés des cellules")
("cell width" "largeur de la cellule")
("cells" "cellules")
("center" "centré")
("center text" "centrer le texte")
("centered" "centré")
("centered block" "bloc centré")
("centered tabular" "tableau centré")
("change border of cell" "changer bordure de la cellule")
("change cell operation mode" "changer mode d'opération")
("change default unit" "changer l'unité par défaut")
("change log" "tous les changements")
("change passphrase" "changer le mot de passe")
("change step-size" "changer la taille des pas")
("change tags" "changer les balises")
("change the TeXmacs preferences" "changer les préférences de TeXmacs")
("change the border of the table" "changer la bordure du tableau")
("change the style of mathematical formulas" "changer le style des formules mathématiques")
("changes" "changements")
("chapter" "chapitre")
("character contraction" "contraction des caractères")
("character encoding" "encodage de caractères")
("character expansion" "expansion des caractères")
("check" "tchèche")
("check for updates" "vérifier les mises à jour")
("check text for spelling errors" "vérifier le texte pour des fautes d'orthographe")
("checkable field" "champs vérifiables")
("chinese" "chinois")
("choice" "choix")
("cipher algorithm for passphrase encryption" "algorithme de chiffrement pour le chiffrement par phrase secrète")
("circle" "cercle")
("citation" "citation")
("cite" "citer")
("class" "classe")
("classification" "classification")
("clean slate" "feuille vierge")
("clear" "effacer")
("clear all fields" "effacer tous les champs")
("clear local information" "effacer les informations locales")
("clear menu" "effacer le menu")
("clear selection" "effacer la sélection")
("clear undo history" "effacer l'historique des modifications")
("click Ok button twice to discard this warning" "cliquez deux fois sur le bouton OK pour supprimer cet avertissement")
("clip" "rogner")
("clip object" "rogner l'objet")
("clipboard image format" "format d'image pour presse-papier")
("clipped" "tronqué")
("clipped and magnified" "tronqué et agrandi")
("clipped and resized" "tronqué et redimensionné")
("clone" "cloner")
("clone window" "cloner la fenêtre")
("close" "fermer")
("close TeXmacs" "fermer TeXmacs")
("close animation tool" "fermer l'outil d'animation")
("close buffer" "fermer le tampon")
("close document" "fermer le document")
("close program" "fermer le programme")
("close replace tool" "fermer l'outil de remplacement")
("close search tool" "fermer l'outil de recherche")
("close session" "fermer la session")
("close spell tool" "fermer l'outil de correction d'orthographe")
("close translations to rebuild" "fermer les traductions à reconstruire")
("close window" "fermer la fenêtre")
("closed bezier" "courbe de bézier fermée")
("closed curve" "courbe fermée")
("closed smooth" "courbe lisse fermée")
("closed spline" "spline fermée")
("closing" "fermeture")
("closing style" "style de fermeture")
("cluster by affiliation" "grouper par affiliation")
("code" "code")
("collect garbage" "ramasse-miettes")
("collected keys" "clés collectées")
("color" "couleur")
("color of the axes" "couleur des axes")
("color of the subunits" "couleur des sous-unités")
("color of the units" "couleur des unités")
("colors" "couleurs")
("column" "colonne")
("column contains glued items" "la colonne contient des parties collées")
("column to the left" "colonne vers la gauche")
("column to the right" "colonne vers la droite")
("columns" "colonnes")
("columns separation" "séparation entre les colonnes")
("commit file" "faire le «commit» du fichier")
("common" "commun")
("common formats" "formats courants")
("commutative diagram" "diagramme commutatif")
("compact" "compact")
("compactification" "compactification")
("compactify" "compactifier")
("compatibility with other formats" "compatibilité avec les autres formats")
("compile article" "compiler un article")
("compile book" "compiler un livre")
("compile buffer" "compiler tampon")
("compile project" "compiler projet")
("complete bibliographic reference" "compléter référence bibliographique")
("completion" "complétion")
("complex" "complexe")
("complex actions" "actions complexes")
("compose" "composer")
("compound" "composé")
("compress" "comprimer")
("compress into toolbar" "compresser dans la barre d'outils")
("compressed" "comprimé")
("conceal" "dissimuler")
("concrete" "concret")
("condensed" "condensé")
("condition" "condition")
("configuration" "configuration")
("configure look and feel" "configurer l'apparence")
("confirm database entry" "confirmer la saisie dans la base de données")
("confirm entry" "confirmer l'entrée")
("confirm selected database entries" "confirmer les entrées sélectionnées dans la base de données")
("confirm selected entries" "confirmer les entrées sélectionnées")
("connect" "connexion")
("conservative conversion options" "options de conversion conservatrices")
("consoles" "consoles")
("constellation" "constellation")
("contact" "contact")
("content" "contenu")
("content tag" "balise")
("context aids" "aide contextuelle")
("context dependent icons" "icônes dépendantes du contexte")
("contextual hints" "indications contextuelles")
("continuation of" "continuation de")
("continue" "continue")
("continued fraction" "fraction continue")
("contour" "contour")
("contract logarithms" "contracter les logarithmes")
("contribute" "contribuer")
("control flow" "flot de contrôle")
("control the evaluation of expressions" "contrôler l'évaluation des expressions")
("convention" "convention")
("convert" "convertir")
("converters" "convertisseurs")
("converters to other data formats" "convertisseurs pour d'autres formats")
("convertible" "convertibles")
("copy" "copier")
("copy text" "copier du texte")
("copy to" "copier vers")
("copying" "copier")
("copyright" "copyright")
("cork charset with TeX catcode definition in preamble" "Cork avec définition des catcodes dans le préambule")
("corollary" "corollaire")
("correct" "corriger")
("correct all" "corriger tout")
("correct formula" "corriger la formule")
("correct manually" "corriger manuellement")
("correct mathematical formulas" "corriger les formules mathématiques")
("correct text" "corrige texte")
("correction" "correction")
("cosine" "cosinus")
("count characters" "compter le nombre de caractères")
("count lines" "compter le nombre de lignes")
("count words" "compter le nombre de mots")
("create a new document" "créer un nouveau document")
("create link" "créer un lien")
("create preamble" "créer un préambule")
("create remote directory" "créer un répertoire distant")
("create remote file" "créer un fichier distant")
("create subprogram" "créer un sous-programme")
("create subsession" "créer une sous-session")
("create table macro" "créer une macro de tableau")
("create web site" "création d'un site web")
("creating new account" "créer un nouveau compte")
("creating technical pictures" "création d'images techniques")
("crop" "rogner")
("crop marks" "repères de coupe")
("cross" "croix")
("crossed boxes" "cases avec croix")
("crossed circles" "cercles avec croix")
("current user version" "version utilisateur actuelle")
("current version" "version actuelle")
("cursor" "curseur")
("cursors" "curseurs")
("curve" "courbe")
("curve intersections" "intersections de courbes")
("curve points" "points de courbe")
("custom tab" "tabulation personnalisée")
("customizations" "personnalisations")
("customizing TeXmacs" "personnalisation")
("customizing and extending the user interface" "personnalisation et extension de l'interface utilisateur")
("customizing the TeXmacs styles" "personnaliser les styles TeXmacs")
("custum tab" "tabulation personnalisée")
("cut" "couper")
("cut text" "couper du texte")
("cut to" "couper vers")
("cypriot" "cypriote")
("cyrillic" "cyrillique")
("cyrillic input method" "cyrillique par le clavier")
("cyrillic italic right" "cyrillique italique droit")
("czech" "tchèque")
("dancers" "danseurs")
("danish" "danois")
("dark grey" "gris foncé")
("dash" "tiret")
("dashes" "tirets")
("data" "données")
("data conversion" "conversion des données")
("data format" "format des données")
("database entry" "entrée de base de données")
("database tool" "outil pour les bases des données")
("database toolbar" "barre des données")
("date" "date")
("deactivate" "désactiver")
("deactivate once" "désactiver une fois")
("deactivate table" "désactiver tableau")
("dead" "mort")
("debug" "débogage")
("debugging console" "console de débogage")
("debugging tool" "outil de débogage")
("december" "décembre")
("decimal comma" "virgule décimal")
("decimal dot" "point décimal")
("decomposed" "décomposés")
("decorate atoms" "décorations atomiques")
("decorated" "décorés")
("decorated wood" "bois décoré")
("decrease size" "réduire la taille")
("decrypt" "décrypter")
("default" "valeur par défaut")
("default padding" "espacement par défaut")
("default size" "taille par défaut")
("definition" "définition")
("degrade" "dégrader")
("degraded" "dégradé")
("delete" "supprimer")
("delete column" "supprimer colonne")
("delete documentation cache" "supprimer le cache de la documentation")
("delete entries" "supprimer les entrées")
("delete link" "supprimer le lien")
("delete row" "supprimer ligne")
("deleted" "supprimé")
("denominator" "dénominateur")
("describe" "décrire")
("describe tag" "décrire la balise")
("description" "description")
("destination" "destination")
("destroy" "détruire")
("detach" "détacher")
("detach master" "détacher le document maître")
("detailed" "détaillé")
("detailed menus" "menus détaillés")
("details in menus" "détails dans les menus")
("determinant" "déterminant")
("determine margins from text width" "déterminer les marges à partir de la largeur du texte")
("devangari" "dévangari")
("developer" "développeur")
("developer tool" "outil de développement")
("developers guide" "guide du développeur")
("device" "support")
("diamond" "diamant")
("differentiate" "dériver")
("dilate" "dilater")
("direction of progression" "sens de progression")
("direction of translation" "sens de la translation")
("directory" "répertoire")
("disable" "désactiver")
("disable coloring on paper" "désactiver la coloration sur le papier")
("disable encryption" "désactiver le cryptage")
("disable first indentation" "désactiver première indentation")
("disable first indentation after" "désactiver première indentation après")
("disable first indentation before" "désactiver première indentation avant")
("disable indentation" "désactiver indentation")
("disable indentation after" "désactiver indentation après")
("disable indentation before" "désactiver indentation avant")
("disable last indentation" "désactiver dernière indentation")
("disable last indentation after" "désactiver dernière indentation après")
("disable last indentation before" "désactiver dernière indentation avant")
("disallow" "interdire")
("disappear" "disparaître")
("disk" "disque")
("display style" "style d'affichage")
("displayed formula" "formule centrée")
("dissociate joined cells" "séparer les cellules jointes")
("distort" "distorsion")
("distorted" "déformé")
("distribute unused space" "distribuer espace non utilisé")
("div" "div")
("division" "division")
("do not remap" "ne pas renvoyer")
("document" "document")
("document font selector" "sélection de la police du document")
("document format" "format de document")
("document language" "langue du document")
("document page format" "format de page du document")
("document paragraph format" "format de paragraphe du document")
("document style" "style de document")
("document styles" "styles de document")
("document updates run" "nombre de tours sur réactualisation")
("documentation" "documentation")
("documents are trees" "les documents sont des arbres")
("dot" "rond")
("dots" "ronds")
("dotted line" "pointillés")
("double stroke" "lignes doubles")
("down" "en bas")
("download" "télécharger")
("downwards" "vers le bas")
("downwards..." "de haut en bas...")
("dpi" "points par pouce")
("dragging" "glisser")
("draw image" "dessiner image")
("draw over" "dessiner sur")
("draw over selection" "dessiner sur sélection")
("due to" "due à")
("duplicate" "en double")
("duration" "durée")
("dutch" "néerlandais")
("dynamic" "dynamique")
("dynamic libraries" "librairies dynamiques")
("eRROR" "eRREUR")
("edit" "éditer")
("edit animation" "modifier l'animation")
("edit groups of objects" "éditer des groupes d'objets")
("edit macro" "éditer la macro")
("edit macros" "éditer les macros")
("edit preamble" "éditer la préambule")
("edit source" "éditer le code source")
("edit source tree" "éditer l'arbre source")
("edit style" "éditer le style")
("edit translations file" "modifier le fichier de traduction")
("editing tools" "outils d'édition")
("edition" "edition")
("editor" "éditeur")
("editors" "éditeurs")
("education" "éducation")
("eigenvalues" "valeurs propres")
("eighth" "huitième")
("email" "email")
("email address" "adresse email")
("embold" "rendre gras")
("emboss" "bossu")
("emphasize" "mise en relief")
("emphasize text" "mettre en relief du texte")
("empty box" "boîte vide")
("enable" "activer")
("enable first indentation" "activer première indentation")
("enable first indentation after" "activer première indentation après")
("enable first indentation before" "activer première indentation avant")
("enable indentation" "activer indentation")
("enable indentation after" "activer indentation après")
("enable indentation before" "activer indentation avant")
("enable last indentation" "activer dernière indentation")
("enable last indentation after" "activer dernière indentation après")
("enable last indentation before" "activer dernière indentation avant")
("enable page breaking" "activer les sauts de page")
("encl" "inclus")
("encoding" "encodage")
("encrypt" "crypter")
("encryption" "cryptage")
("encryption facilities are not currently available" "les installations de cryptage ne sont pas disponibles actuellement")
("encryption facilities have not been enabled for TeXmacs" "Les fonctions de cryptage n'ont pas été activées pour TeXmacs")
("end" "fin")
("enforce brackets to match" "forcer les parenthèses à coincider")
("english" "anglais")
("engrave" "graver")
("enter a title" "entrer un titre")
("enter data" "entrer des données")
("enter graphics" "entrer des graphiques")
("enter graphics mode" "entrer en mode graphique")
("enter new passphrase for encryption" "entrer une nouvelle phrase secrète pour le cryptage")
("enter passphrase for decryption" "entrer la phrase secrète pour le déchiffrement")
("enter passphrase for identity" "entrer la phrase secrète pour l'identité")
("enter title information" "entrer les informations de titre")
("entire table" "tableau entier")
("enumerate" "énumération")
("enumerate|Alpha" "Lettres")
("enumerate|Roman" "Romain")
("enumerate|alpha" "lettres")
("enumerate|roman" "romain")
("enunciation" "énonciation")
("env" "environnement")
("environment" "environnement")
("epilogue" "épilogue")
("equal" "égal à")
("equation" "équation")
("equations" "équations")
("equivalent for" "équivalent pour")
("erode" "éroder")
("error" "erreur")
("esperanto" "espéranto")
("etruscan" "étrusque")
("evaluate" "évaluer")
("evaluate scheme expression" "évaluer expression scheme")
("evaluation switch" "commutateur d'évaluation")
("evaluation tag" "balise d'évaluation")
("even page" "page paire")
("even page footer" "au bas des pages paires")
("even page header" "en-tête des pages paires")
("even page left margin" "marge à gauche des pages paires")
("even page margin" "marge des pages paires")
("even page shift" "décalage pour les pages paires")
("even page text" "texte pour les pages paires")
("even pages" "pages paires")
("exact horizontal" "horizontal exact")
("exact mode" "mode exact")
("exam" "examen")
("example" "exemple")
("exclusive" "exclusif")
("exclusive or" "ou exclusif")
("executable" "exécutable")
("execute" "exécuter")
("execute a TeXmacs command" "executer une commande TeXmacs")
("execute system command" "executer commande système")
("executive" "exécutif")
("exercise" "exercice")
("exit left" "sortir à gauche")
("exit right" "sortir à droite")
("exit tag on the left" "sortir à gauche de la balise")
("exit tag on the right" "sortir à droite de la balise")
("expand" "développer")
("expand inclusions" "développer les documents inclus")
("expand logarithms" "développer les logarithmes")
("expand trigonometric functions" "développer les fonctions trigonométriques")
("expand unrecognized macros" "développer les macros non reconnus")
("expand user-defined macros" "développer les macros des utilisateurs")
("expand w.r.t." "développer suivant")
("expanded" "développé")
("explained" "détaillé")
("exponential" "exponentielle")
("export" "exporter")
("export as" "exporter en tant que")
("export bibliographies as links" "exporter les bibliographies comme des liens")
("export current file" "exporter le fichier courant")
("export formulas as images" "exporter les formules comme des images")
("export mathematical formulas as MathML" "exporter les formules vers du MathML")
("export mathematical formulas as images" "exporter les formules comme des images")
("export selection as image" "exporter la sélection comme image")
("export selections as" "exporter les sélections comme")
("export to remote server" "exporter vers le serveur distant")
("extend" "étendre")
("extend or normal" "'extend' ou 'normal'")
("extended" "étendu")
("extern " "externe")
("extra" "extra")
("extract format" "extraire format")
("extract style file" "extraire fichier de style")
("extract style package" "extraire paquetage de style")
("extras" "extra")
("factor" "factoriser")
("fade" "fondre")
("family" "famille")
("february" "février")
("figure" "figure")
("file" "fichier")
("file name" "nom de fichier")
("file not found" "fichier non trouvé")
("files" "fichiers")
("fill out" "rempli")
("filter" "filtres")
("find next match" "chercher l'occurrence suivante")
("find text" "chercher du texte")
("finnish" "finlandais")
("first" "premier")
("first contact" "premier contact")
("first indentation" "première indentation")
("first item" "premier élément")
("first page" "première page")
("first similar" "premier similaire")
("first start" "démarrage")
("fit to screen" "ajuster à l'écran")
("fit to screen width" "ajuster à la largeur")
("five columns" "cinq colonnes")
("fixed" "fixe")
("flat" "plat")
("flexibility" "flexibilité")
("flexibility factor for vertical spacing" "facteur de flexibilité pour l'espacement vertical")
("floating algorithm" "algorithme flottant")
("floating figure" "figure flottante")
("floating object" "objet flottant")
("floating phantom" "fantôme flottant")
("floating table" "tableau flottant")
("focus" "focus")
("focus dependent icons" "icônes dépendantes du focus")
("fold" "plier")
("fold back" "replier")
("fold input field" "plier champ d'entrée")
("folded" "plié")
("font" "police")
("font base size" "taille de police de base")
("font dpi" "points par pouce")
("font effects" "effets de police")
("font family" "famille de police")
("font name" "nom de police")
("font selector" "sélection de police")
("font series" "espèce de police")
("font shape" "forme de police")
("font size" "taille de police")
("font type" "type de police")
("font variant" "variante de police")
("fonts" "polices")
("footer" "pied de page")
("footnote" "note en bas de page")
("for" "pour")
("foreground" "premier-plan")
("foreign" "étranger")
("format" "format")
("formatted and structured output" "sorties formattées et structurées")
("formatted date" "date formatée")
("formatting" "formatage")
("formula" "formule")
("formula style" "style formules")
("forward" "suivant")
("forward replace" "remplacement en avant")
("forward search" "recherche en avant")
("four columns" "quatre colonnes")
("fraction" "fraction")
("framed" "encadré")
("french" "français")
("full manuals" "manuels complets")
("full name" "nom complet")
("full screen mode" "mode plein écran")
("function" "fonction")
("functional" "fonctionnel")
("further customization" "personnalisation")
("future changes" "changements à venir")
("gNU TeXmacs comes without any form of legal warranty" "GNU TeXmacs n'offre aucune garantie juridique")
("gNU TeXmacs falls under the GNU general public license" "GNU TeXmacs tombe sous la ``GNU general public license''")
("gap" "trou")
("gcd" "pgcd")
("general" "général")
("general architecture of TeXmacs" "architecture générale de TeXmacs")
("general negation" "négation générale")
("general note" "note générale")
("generating font file" "Génération du fichier de police")
("generic" "générique")
("georgian" "géorgien")
("german" "allemand")
("getting started" "commencer")
("glossary" "glossaire")
("glossary entry" "entrée dans le glossaire")
("glue" "coller")
("glue decorations" "coller décorations")
("glyphs" "glyphes")
("gnawed" "grignoté")
("go" "aller")
("go to first similar tag" "aller vers la première balise similaire")
("go to last similar tag" "aller vers la dernière balise similaire")
("go to next similar tag" "aller vers la balise suivante de même type")
("go to previous similar tag" "aller vers la balise précédente de même type")
("go to section" "aller vers section")
("gothic" "gothique")
("graphical effects" "effets graphiques")
("graphical interface" "interface graphique")
("grave" "grave")
("greater" "supérieur à")
("greater or equal" "supérieur ou égal à")
("greek" "grecque")
("greek letter" "lettre grecque")
("green" "vert")
("grey" "gris")
("greyed" "grisé")
("group" "groupe")
("grouped" "groupé")
("h modifier" "modificateur H")
("hang up" "raccrocher")
("happy typing" "bonne rédaction")
("has been aborted" "a été arrêtée")
("has completed its task" "a effectué sa tâche")
("hat" "circonflexe")
("header" "en-tête")
("header and footer" "en-tête et pied de page")
("hebrew" "hébreu")
("height" "hauteur")
("height is exactly the specified height" "utiliser la hauteur spécifiée")
("height is maximum of specified height and box height" "utiliser maximum de la hauteur spécifiée et la hauteur de la boîte")
("height is minimum of specified height and box height" "utiliser minimum de la hauteur spécifiée et la hauteur de la boîte")
("height magnification" "agrandissement de la hauteur")
("help" "aide")
("help me" "aidez-moi")
("help us" "aidez-nous")
("here" "ici")
("hidden" "caché")
("hide TeXmacs" "cacher TeXmacs")
("hide others" "cacher le reste")
("home" "racine")
("homepage" "page d'acceuil")
("horizontal" "horizontal")
("horizontal alignment" "alignement horizontal")
("horizontal cell alignment" "alignement horizontal de la cellule")
("horizontal ink separation" "séparation d'encre horizontale")
("horizontal part" "partie horizontale")
("horizontal position" "position horizontale")
("horizontal rule" "ligne horizontale")
("horizontal space" "espace horizontal")
("horizontal table alignment" "alignement horizontal du tableau")
("horizontally align cell to the base" "alignement horizontale de la cellule sur la base")
("horizontally center the cell" "centrer la cellule horizontalement")
("how much longer may pages become" "de combien les pages peuvent-elles se rallonger")
("how much shorter may pages become" "de combien les pages peuvent-elles se raccourcir")
("huge" "énorme")
("hungarian" "hongrois")
("hybrid command" "commande hybride")
("hyperlink" "hyperlien")
("hyphenate as" "couper comme")
("hyphenation" "césure")
("icelandic" "islandais")
("if" "si")
("if hyphenated" "en mode césure")
("image" "image")
("image links" "images liées")
("implementation" "implantation")
("import" "importer")
("import current file" "importer le fichier courant")
("import selections as" "importer les sélections comme")
("import sophisticated objects as pictures" "importer des objets sophistiqués sous forme d'images")
("improving the current implementation" "amélioration de l'implantation présente")
("in" "dans")
("in popup windows" "dans des fenêtres à part")
("inactive" "inactif")
("include" "inclure")
("include a document" "inclure un document")
("include file" "inclure un fichier")
("inclusion into TeXmacs" "inclusion dans TeXmacs")
("inclusions" "inclusions")
("indent" "en retrait")
("indent paragraphs" "indenter les paragraphes")
("indentation" "indentation")
("indentation flag" "indentation")
("index" "index")
("index entry" "entrée dans l'index")
("index level" "niveau d'indices")
("informative flags" "drapeaux informatifs")
("ink here" "encrer ici")
("inline" "en ligne")
("inline arguments" "arguments en ligne")
("inline code" "code incorporé")
("inline content" "contenu en ligne")
("inline formula" "formule en ligne")
("input mode" "mode des entrées")
("insert" "insérer")
("insert Pr" "insérer Pr")
("insert a TeXmacs symbol" "insérer un symbole TeXmacs")
("insert a big operator" "insérer un grand opérateur")
("insert a binary operation" "insérer une opération binaire")
("insert a binary relation" "insérer une relation binaire")
("insert a blackboard bold character" "insérer un caractère gras de tableau noir")
("insert a bold calligraphic character" "insérer un caractère calligraphique gras")
("insert a bold character" "insérer un caractère gras")
("insert a calligraphic character" "insérer un caractère calligraphique")
("insert a computer program" "insérer un programme d'ordinateur")
("insert a condition" "insérer une condition")
("insert a control flow instruction" "insérer une instruction de flux de contrôle")
("insert a fraction" "insérer une fraction")
("insert a fraktur character" "insérer un caractère gothique")
("insert a gap" "insérer un trou")
("insert a greek character" "insérer un caractère grec")
("insert a large left delimiter" "insérer un grand délimiteur à gauche")
("insert a large right delimiter" "insérer un grand délimiteur à droite")
("insert a large separator" "insérer un grand séparateur")
("insert a left subscript" "insérer un indice à gauche")
("insert a link" "insérer un lien")
("insert a list" "insérer une liste")
("insert a miscellaneous symbol" "insérer un symbole divers")
("insert a multiple choice" "insérer un choix multiple")
("insert a new branch" "insère une nouvelle branche")
("insert a new item" "insérer un nouvel élément")
("insert a note or a floating object" "insérer une note ou un objet flottant")
("insert a numerical operation" "insérer une opération numérique")
("insert a picture" "insérer une image")
("insert a prominent piece of text" "insérer du texte prominent")
("insert a question" "insérer une question")
("insert a square root" "insérer une racine carrée")
("insert a table" "insérer un tableau")
("insert a table or a matrix" "insérer un tableau ou une matrice")
("insert a textual operation" "insérer une opération textuelle")
("insert a wide symbol above" "insérer un accent large au dessus")
("insert a wide symbol below" "insérer un accent large en dessous")
("insert above" "insérer vers le haut")
("insert an" "insérer un")
("insert an accent" "insérer un accent")
("insert an answer" "insérer une réponse")
("insert an arrow" "insérer une flèche")
("insert an enunciation" "insérer un énoncé")
("insert an environment" "insérer un environnement")
("insert an n" "insérer une racine n")
("insert an operation on tuples" "insérer une opération sur des tuples")
("insert appendix" "insérer appendice")
("insert arccos" "insérer arccos")
("insert arcsin" "insérer arcsin")
("insert arctan" "insérer arctan")
("insert arg" "insérer arg")
("insert argument" "insérer argument")
("insert author" "insérer auteur")
("insert automatically generated content" "insérer du contenu automatiquement engendré")
("insert below" "insérer vers le bas")
("insert big contour integral" "insérer une grande intégrale de contour ")
("insert big coproduct" "insérer un grand coproduit")
("insert big direct sum" "insérer une grande somme directe")
("insert big dotted point" "insérer un grand point dans un cercle")
("insert big integral" "insérer une grande intégrale")
("insert big intersection" "insérer une grande intersection")
("insert big logical and" "insérer un grand et logique")
("insert big logical or" "insérer un grand ou logique")
("insert big product" "insérer un grand produit")
("insert big square union" "insérer une grande réunion angulaire")
("insert big summation" "insérer une grande somme")
("insert big tensor product" "insérer un grand produit tensoriel")
("insert big union" "insérer une grande réunion")
("insert big union sum" "insérer une grande union somme")
("insert big vertical space" "insérer une grande espace verticale")
("insert chapter" "insérer chapitre")
("insert column" "insérer colonne")
("insert column to the left" "insérer colonne vers la gauche")
("insert column to the right" "insérer colonne vers la droite")
("insert cos" "insérer cos")
("insert cosh" "insérer cosh")
("insert cot" "insérer cot")
("insert coth" "insérer coth")
("insert csc" "insérer csc")
("insert deg" "insérer deg")
("insert det" "insérer det")
("insert dim" "insérer dim")
("insert dollar" "insérer dollar")
("insert equation" "insérer équation")
("insert executable markup" "insérer du contenu exécutable")
("insert exp" "insérer exp")
("insert fields" "insérer des champs")
("insert footnote" "insérer note en bas de page")
("insert formula" "insérer une formule")
("insert gcd" "insérer gcd")
("insert hom" "insérer hom")
("insert horizontal interword space" "insérer une espace")
("insert image" "insérer une image")
("insert inactive markup" "insérer du contenu inactif")
("insert inf" "insérer inf")
("insert input field above" "insérer champ d'entrée au dessus")
("insert input field below" "insérer champ d'entrée en dessous")
("insert ker" "insérer ker")
("insert large" "insérer un grand")
("insert left" "insérer vers la gauche")
("insert lg" "insérer lg")
("insert lim" "insérer lim")
("insert liminf" "insérer liminf")
("insert limsup" "insérer limsup")
("insert ln" "insérer ln")
("insert log" "insérer log")
("insert macro" "insérer macro")
("insert mathematics" "insérer des mathématiques")
("insert max" "insérer max")
("insert medium horizontal space" "insérer une espace horizontale moyenne")
("insert medium vertical space" "insérer une espace verticale moyenne")
("insert min" "insérer min")
("insert negative horizontal space" "insérer une petite espace négative")
("insert new item or number" "insérer un nouvel élément ou numéro")
("insert new rows or columns" "insérer nouvelles lignes ou colonnes")
("insert or delete rows or columns" "insérer ou supprimer lignes ou colonnes")
("insert right" "insérer vers la droite")
("insert row" "insérer ligne")
("insert row above" "insérer ligne au dessus")
("insert row below" "insérer ligne en dessous")
("insert sec" "insérer sec")
("insert section" "insérer section")
("insert sharp" "insérer dièse")
("insert sin" "insérer sin")
("insert sinh" "insérer sinh")
("insert small horizontal space" "insérer une petite espace horizontale")
("insert small vertical space" "insérer une petite espace verticale")
("insert structural markup" "insérer du contenu structurel")
("insert subsection" "insérer sous-section")
("insert subsubsection" "insérer sous-sous-section")
("insert subtable" "insérer sous-tableau")
("insert sup" "insérer sup")
("insert tan" "insérer tan")
("insert tanh" "insérer tanh")
("insert text field" "insérer champ de texte")
("insert thick horizontal space" "insérer une espace horizontale épaisse")
("insert title" "insérer titre")
("insert value" "insérer valeur")
("inside mathematics" "en mode mathématique")
("integrate" "intégrer")
("interactive command" "commande interactive")
("interactive questions" "questions interactives")
("interfacing" "interfaçage")
("interfacing TeXmacs with other systems" "interfaçage de TeXmacs avec d'autres systèmes")
("interjection" "interjection")
("interline separation" "séparation entre les lignes")
("interline space" "espace d'interligne")
("internationalization" "internationalisation")
("interparagraph space" "espace d'interparagraphe")
("interrupt execution" "interrompre l'exécution")
("interrupted" "interrompu")
("introduction" "introduction")
("invert" "inverser")
("invisible" "invisible")
("invisible citation" "citation invisible")
("irish" "irlandais")
("is running" "est en marche")
("is tuple" "est tuplet")
("ispell does not respond" "ispell ne répond pas")
("ispell is already busy" "ispell a déjà été lancé")
("italian" "italien")
("italic" "italique")
("italic right" "italique droit")
("itemize" "liste")
("january" "janvier")
("japanese" "japonais")
("join selected cells" "unir les cellules sélectionnées")
("july" "juillet")
("jump in" "retrait après la première ligne")
("june" "juin")
("justified" "justifié")
("justify text" "justifier le texte")
("keep evaluated expressions" "garder les expressions évaluées")
("keep unfolded" "garder déplié")
("key" "touche")
("keyboard" "clavier")
("keyboard configuration" "configuration du clavier")
("keyboard equivalent" "raccourci clavier")
("keyboard modifiers" "modificateurs de clavier")
("keyboard shortcut" "raccourci clavier")
("keymaps" "claviers")
("keyword" "mot-clef")
("keywords" "mots-clefs")
("kill" "tuer")
("known bugs" "bogues connus")
("label" "étiquette")
("landscape" "paysage")
("language" "langue")
("laptop presentations" "présentations")
("large" "grand")
("large cells" "grandes cellules")
("large closing bracket" "grande parenthèse fermante")
("large delimiter" "grand délimiteur")
("large opening bracket" "grande parenthèse ouvrante")
("large separator" "grand séparateur")
("last" "dernier")
("last indentation" "dernière indentation")
("last page" "dernière page")
("last similar" "dernier similaire")
("latex command" "commande latex")
("latin" "latin")
("layout" "mise en page")
("lcm" "ppcm")
("left" "à gauche")
("left aligned" "aligné à gauche")
("left arrow" "flèche vers la gauche")
("left border" "limite à gauche")
("left cell border" "bordure de la cellule à gauche")
("left margin" "marge à gauche")
("left padding" "espacement à gauche")
("left prime" "prime à gauche")
("left slanted" "italique vers la gauche")
("left subscript" "indice à gauche")
("left superscript" "exposant à gauche")
("left surrounding" "entourage à gauche")
("left table border" "bordure du tableau à gauche")
("leftwards..." "de droite à gauche...")
("legal" "légal")
("lemma" "lemme")
("length" "longueur")
("less" "inférieur à")
("less or equal" "inférieur ou égal à")
("letter" "lettre")
("license" "licence")
("light" "léger")
("light grey" "gris clair")
("limitations" "limitations")
("limits" "limites")
("line" "droite")
("line break" "saut de ligne")
("line stretch" "étirabilité des lignes")
("line wrapping" "passage à la ligne automatique")
("linear 2D" "linéaire 2D")
("linear algebra" "algèbre linéaire")
("lines around" "entre deux lignes")
("link" "lien")
("link image" "lier image")
("link to URL" "lien vers URL")
("linking tool" "outil de liens")
("list" "liste")
("list all commands" "liste de toutes les commandes")
("list of figures" "liste de figures")
("list of tables" "liste de tableaux")
("load" "charger")
("load LaTeX file" "charger fichier LaTeX")
("load TeX file" "charger fichier TeX")
("load TeXmacs file" "charger fichier TeXmacs")
("load TeXmacs style file" "charger fichier de style TeXmacs")
("load a file" "charger un fichier")
("load buffer" "charger tampon")
("load file" "charger fichier")
("load html file" "charger fichier html")
("load image" "charger image")
("load in new window" "charger dans nouvelle fenêtre")
("load latex file" "charger fichier latex")
("load more recent autosave file" "charger le fichier plus récent de sauvegarde automatique")
("load tex file" "charger fichier tex")
("load verbatim file" "charger fichier verbatim")
("loaded" "chargé")
("logarithm" "logarithme")
("logarithms" "logarithmes")
("long" "long")
("look and feel" "aspect de l'interface")
("look for more fonts" "rechercher de nouvelles polices")
("look up" "rechercher")
("lower border" "limite en bas")
("m modifier" "modificateur M")
("macro" "macro")
("magenta" "mauve")
("magic" "magique")
("magnification" "agrandissement")
("magnified" "agrandi")
("magnify horizontally" "magnifier horizontalement")
("magnify vertically" "magnifier verticalement")
("main" "principal")
("main icon bar" "icônes principales")
("major changes" "changements majeurs")
("make a page insertion" "créer une insertion de page")
("make a subscript" "insérer un indice")
("make a superscript" "insérer un exposant")
("make acute" "créer un accent aigu")
("make bar" "créer une barre")
("make check" "créer un tchèche")
("make fraction" "créer une fraction")
("make grave" "créer un accent grave")
("make hat" "créer un accent circonflexe")
("make label" "créer une étiquette")
("make negation" "créer une négation")
("make page reference" "créer une référence de page")
("make reference" "créer une référence")
("make slides" "créer des diapositives")
("make square root" "créer une racine carrée")
("make tilde" "créer un tilde")
("make title" "construire titre")
("make vector" "créer un vecteur")
("making donations" "effectuer des dons")
("manual" "manuel")
("manual correction" "correction manuelle")
("map to" "envoyer vers")
("march" "mars")
("marginal note" "note marginale")
("margins" "marges")
("margins as on paper" "marges comme sur le papier")
("margins on paper" "marges sur le papier")
("margins on screen" "marges sur l'écran")
("marked" "marqué")
("master" "maître")
("master file" "fichier maître")
("master's thesis" "mémoire de master")
("math" "maths")
("math font" "police mathématique")
("math font family" "famille de police mathématique")
("math font series" "espèce de police mathématique")
("math font shape" "forme de police mathématique")
("mathematical" "mathématique")
("mathematical and customized input" "entrées mathématiques et personnalisées")
("mathematical font" "police mathématique")
("mathematical formulas" "formules mathématiques")
("mathematical input" "entrées sous forme mathématique")
("mathematical typesetting" "mise en page mathématique")
("mathematics" "mathématiques")
("matrices" "matrices")
("matrix" "matrice")
("maximal" "maximal")
("maximal cell height" "hauteur maximale de la cellule")
("maximal cell width" "largeur maximale de la cellule")
("maximal number of columns" "nombre minimal de colonnes")
("maximal number of rows" "nombre maximal de lignes")
("maximal table height" "hauteur maximale du tableau")
("maximal table width" "largeur maximale du tableau")
("maximum mode" "mode maximum")
("may" "mai")
("medium" "moyen")
("medium skip" "saut moyen")
("meminfo" "info mémoire")
("merge" "fusion")
("messy" "embrouillé")
("meta key" "touche meta")
("metadata" "métadonnées")
("metafont and available type 1" "metafont et type 1 disponible")
("metafont bitmaps only" "metafont bitmaps seulement")
("middle" "au milieu")
("minimal" "minimal")
("minimal cell height" "hauteur minimale de la cellule")
("minimal cell width" "largeur minimale de la cellule")
("minimal number of columns" "nombre minimal de colonnes")
("minimal number of rows" "nombre minimal de lignes")
("minimal table height" "hauteur minimale du tableau")
("minimal table width" "largeur minimale du tableau")
("minimum mode" "mode minimum")
("minus" "moins")
("miscellaneous" "divers")
("miscellaneous features" "fonctionnalités diverses")
("mod" "mod")
("mode" "mode")
("mode dependent icons" "icônes dépendantes du mode")
("modifier" "modificateur")
("modify cell alignment" "modifier alignement de la cellule")
("modify cell border" "bordure de la cellule")
("modify cell padding" "espacement autour de la cellule")
("modify cell size" "modifier taille de la cellule")
("modify table border" "bordure du tableau")
("modify table padding" "espacement autour du tableau")
("mongolian" "mongol")
("monospaced" "mono-espacé")
("more information about GNU TeXmacs can be found in the Help" "pour plus de renseignements sur GNU TeXmacs, veuillez consulter le menu Aide")
("mosaic" "mosaïque")
("move" "aller")
("move down" "aller vers le bas")
("move object" "déplacer objet")
("move to the right when finished" "aller à droite pour terminer")
("move up" "aller en haut")
("multiline" "multi-lignes")
("multiline input" "entrées multi-lignes")
("multiple choice" "choix multiple")
("mutator tags" "balises mutantes")
("my documents" "mes documents")
("n-th" "n-ième")
("n-th root" "racine n-ième")
("name" "nom")
("negation" "négation")
("never" "jamais")
("new" "nouveau")
("new account" "nouveau compte")
("new buffer" "nouveau tampon")
("new column" "nouvelle colonne")
("new document" "nouveau document")
("new double page" "nouvelle page double")
("new double page before" "nouvelle page double avant")
("new item" "nouvel élément")
("new line" "nouvelle ligne")
("new macro" "nouvelle macro")
("new number" "nouveau nombre")
("new page" "nouvelle page")
("new page before" "nouvelle page avant")
("new paragraph" "nouveau paragraphe")
("new roman" "nouveau romain")
("new row" "nouvelle ligne")
("new table" "nouveau tableau")
("new window" "nouvelle fenêtre")
("next" "suivant")
("next line" "ligne suivante")
("next match" "suivant")
("next similar" "suivant similaire")
("nickname" "surnom")
("no" "non")
("no changes need to be saved" "il n'y a pas de changements à sauvegarder")
("no dictionary for" "pas de dictionnaire pour")
("no errors have been corrected" "aucune erreur n'a été corrigée")
("no first indentation" "pas de première indentation")
("no indentation" "pas d'indentation")
("no line break" "pas de saut de ligne")
("no matches found" "je n'ai pas trouvé d'occurrences")
("no matches found for" "pas d'occurrences pour")
("no more matches for" "pas d'autres occurrences de")
("no more redo information available" "tout a déjà été refait")
("no more undo information available" "les renseignements pour défaire ont été épuisés")
("no name" "sans nom")
("no page break" "pas de saut de page")
("no page break after" "pas de saut de page après")
("no page break before" "pas de saut de page avant")
("no page numbers" "enlever les numéros de page")
("no spelling errors found in text" "le texte ne contient pas de fautes d'orthographe")
("no style" "sans style")
("none" "néant")
("normal" "normal(e)")
("norwegian" "norvégien")
("not" "non")
("not equal" "différent de")
("not found" "non trouvé")
("notation" "notation")
("note" "note")
("november" "novembre")
("number" "nombre")
("number equation" "numéroter l'équation")
("number of columns" "nombre de colonnes")
("numbered" "numéroté")
("numbered equation" "équation numérotée")
("numbered equations" "équations numérotées")
("numbering" "numérotation")
("numerator" "numérateur")
("numeric" "numérique")
("objectives" "objectifs")
("occurrences" "occurrences")
("october" "octobre")
("odd page" "page impaire")
("odd page footer" "au bas des pages impaires")
("odd page header" "en-tête des pages impaires")
("odd page left margin" "marge à gauche des pages impaires")
("odd page margin" "marge des pages impaires")
("odd page right margin" "marge à droite des pages impaires")
("odd page shift" "décalage pour les pages impaires")
("odd page text" "texte pour les pages impaires")
("odd pages" "pages impaires")
("of" "de")
("off" "désactiver")
("ok" "ok")
("old english" "vieil anglais")
("old slavonic" "vieux slave")
("old style" "ancien style")
("on" "activer")
("on cells" "par cellules")
("on columns" "par colonnes")
("on entire table" "par tableau entier")
("on rows" "par lignes")
("on the footer" "sur la barre d'état")
("one column" "une colonne")
("one spelling error has been corrected" "une faute d'orthographe a été corrigée")
("online documentation" "documentation en ligne")
("online help" "aide en ligne")
("only inline tags" "balises en ligne seulement")
("opacity" "opacité")
("open" "ouvrir")
("open a new buffer" "ouvrir un nouveau tampon")
("open in new window" "ouvrir dans une nouvelle fenêtre")
("open new window" "ouvrir nouvelle fenêtre")
("opening" "ouverture")
("operation mode" "mode d'opération")
("operation on named selection" "opération sur sélection à spécifier")
("operation on primary selection" "opération sur sélection primaire")
("operation on secondary selection" "opération sur sélection secondaire")
("operation on ternary selection" "opération sur sélection ternaire")
("optical" "optique")
("option" "option")
("options" "options")
("or" "ou")
("orange" "orange")
("orientation" "orientation")
("origin" "origine")
("original welcome message" "message original de bienvenue")
("ornamented" "orné")
("other" "autre")
("other package" "autre paquetage")
("other pages" "autres pages")
("other projects" "autres projets")
("other style" "autre style")
("outlined" "dédoubler")
("outlined emboss" "bossu dédoublé")
("outlined engrave" "gravé dédoublé")
("outlined roman" "romain dédoublé")
("over" "sur")
("overbrace" "accolade au dessus")
("overline" "surligner")
("overlined" "surligné")
("owner" "possesseur")
("padded" "entre espaces verticales")
("padding" "espacement")
("page" "page")
("page bottom margin" "marge de page en bas")
("page break" "saut de page")
("page break before" "saut de page avant")
("page height" "hauteur de page")
("page insertion" "insertion de page")
("page layout" "mise en page")
("page number" "numéro de page")
("page number text" "texte pour les numéros de page")
("page numbering" "numérotation des pages")
("page reference" "référence de page")
("page right margin" "marge de page à droite")
("page setup" "paramètres d'impression")
("page top margin" "marge de page en haut")
("page type" "type de page")
("page width" "largeur de page")
("pages" "pages")
("paper" "papier")
("paper type" "type de papier")
("papyrus" "papyrus")
("paragraph" "paragraphe")
("paragraph mode" "type de paragraphe")
("paragraph width" "largeur du paragraphe")
("paragraphs" "paragraphes")
("parametric curve" "courbe paramétrée")
("parametric surface" "surface paramétrée")
("part" "partie")
("passphrase encryption" "cryptage par phrase secrète")
("past changes" "changements effectués")
("paste" "coller")
("paste from" "coller de")
("paste text" "coller du texte")
("path" "chemin")
("pattern" "motif")
("pen width" "épaisseur du trait")
("perform operations on cells" "opérer cellule par cellule")
("perform operations on columns" "opérer sur des colonnes")
("perform operations on entire table" "opérer sur le tableau entier")
("perform operations on rows" "opérer sur des lignes")
("permanent" "permanent")
("permanent footer" "pied de page permanent")
("permanent header" "en-tête permanent")
("permanently insert into dictionary" "rajouter de façon permanente au dictionnaire")
("person" "personne")
("personal dictionary has been modified" "votre dictionnaire personnel a été modifié")
("phantasy" "fantaisie")
("phantoms" "fantômes")
("phd thesis" "thèse de doctorat")
("philosophy" "philosophie")
("phoenician" "phénicien")
("phonetic" "phonétique")
("pink" "rose")
("plain" "simple")
("plain block" "bloc standard")
("plain boxes" "cases remplies")
("plain circles" "cercles remplis")
("plain tabular" "tableau standard")
("planned changes" "changements prévus")
("plans for the future" "projets pour l'avenir")
("play" "jouer")
("please" "de grâce")
("please wait" "patientez un instant s.v.p.")
("plot" "graphique")
("plugin" "greffon")
("plugins" "greffons")
("plural" "pluriel")
("plus" "plus")
("polish" "polonais")
("porting TeXmacs to other platforms" "porter TeXmacs vers d'autres plate-formes")
("portrait" "portrait")
("portuguese" "portugais")
("position" "position")
("position float" "positionner flottant")
("position floating object" "positionner l'objet flottant")
("position the table" "positionner le tableau")
("postscript" "postscript")
("postscript image" "image postscript")
("pre-alpha release" "version pré-alpha")
("preamble" "préambule")
("preamble mode" "mode de préambule")
("preferences" "préférences")
("preferences for tag" "préférences pour la balise")
("presentation" "présentation")
("presentation mode" "mode de présentation")
("presentation tag" "balise de présentation")
("presentation tool" "outil de présentation")
("preserve tags" "préserver les balises")
("preview" "aperçu")
("preview before printing" "aperçu avant l'impression")
("preview command" "commande de prévisualisation")
("preview with ghostview" "prévisualiser avec ghostview")
("previous" "précédent")
("previous match" "précédent")
("previous similar" "précédent similaire")
("primary" "primaire")
("prime" "prime")
("print" "imprimer")
("print all" "imprimer le tout")
("print all to file" "imprimer le tout vers un fichier")
("print buffer" "imprimer le document")
("print buffer to file" "imprimer le document vers un fichier")
("print page selection" "imprimer sélection de pages")
("print page selection to file" "imprimer sélection de pages vers un fichier")
("print to postscript file" "imprimer vers fichier postscript")
("printer" "imprimante")
("printer dpi" "résolution de l'imprimante en points par pouce")
("printing command" "commande pour imprimer")
("problem" "problème")
("professional" "professionnel")
("prog" "prog")
("prog font" "police pour programmer")
("prog font family" "famille de police de programmation")
("prog font series" "espèce de police de programmation")
("prog font shape" "forme de police de programmation")
("program" "programme")
("program font" "police de programmation")
("program mode" "mode de programmation")
("programming" "programmation")
("progressive" "progressif")
("project" "projet")
("projects" "projets")
("prologue" "prologue")
("prominent" "mise en valeur")
("prompt on scripts" "demander l'acceptation de chaque script")
("prompts and default input" "prompts et entrées par défaut")
("proof" "démonstration")
("properties" "propriétés")
("proportional" "proportionnel")
("proportional typewriter" "proportionnel machine à écrire")
("proposition" "proposition")
("public key encryption" "chiffrement à clé publique")
("query replace" "remplacement contrôlé")
("question" "question")
("questions only" "questions seulement")
("questions with answers" "questions et réponses")
("quick evaluation of formulas" "évaluation rapide des formules")
("quit" "quitter")
("quit TeXmacs" "quitter TeXmacs")
("quotation" "citation")
("quote" "citer")
("range" "partie")
("rank" "rang")
("read" "lecture")
("really close it" "vraiment fermer")
("really huge" "vraiment énorme")
("really quit" "voulez-vous vraiment quitter")
("really tiny" "vraiment minuscule")
("recent" "récent")
("recent documents" "documents récents")
("recover autosave file" "recupérer fichier de sauvegarde automatique")
("red" "rouge")
("redo" "répéter")
("redo undone changes" "refaire des changements annulés")
("reduce" "réduire")
("reduce bottom margin by" "réduire marge en bas de")
("reduce left margin by" "réduire marge à gauche de")
("reduce margins" "réduire les marges")
("reduce right margin by" "réduire marge à droite de")
("reduce top margin by" "réduire marge en haut de")
("reduce trigonometric functions" "réduire les fonctions trigonométriques")
("reduced margins" "marges réduites")
("reduction bottom margin" "réduction marge en bas")
("reduction even page margin" "réduction marge de page impaire")
("reduction odd page margin" "réduction marge de page paire")
("reduction page bottom margin" "réduction de la marge de page en bas")
("reduction page right margin" "réduction de la marge de page à droite")
("reduction page top margin" "réduction de la marge de page en haut")
("reduction right margin" "réduction marge à droite")
("reduction top margin" "réduction marge en haut")
("reference" "référence")
("reference guide" "guide de référence")
("reference guide for the TeXmacs primitives" "guide de référence pour les primitives TeXmacs")
("reference guide for the standard TeXmacs styles" "guide de référence pour les styles standards de TeXmacs")
("references" "références")
("regular" "normal")
("release" "version")
("reload" "recharger")
("remark" "remarque")
("remote" "distant")
("remote connections" "connexions à distance")
("remote control" "commande à distance")
("remote controllers with keyboard simulation" "télécommandes avec simulation
du clavier")
("remote tool" "outil de connections distantes")
("remove" "enlever")
("remove all output fields" "enlever tous les champs de sortie")
("remove downwards" "supprimer vers le bas")
("remove fields" "enlever des champs")
("remove input field" "enlever champ d'entrée")
("remove input field above" "enlever champ d'entrée au dessus")
("remove leftwards" "supprimer vers la gauche")
("remove number" "enlever le numéro")
("remove package" "supprimer paquetage")
("remove rightwards" "supprimer vers la droite")
("remove tag" "supprimer la balise")
("remove this switch" "enlever ce commutateur")
("remove upwards" "supprimer vers le haut")
("renumber this page" "renuméroter cette page")
("repeat" "répéter")
("repeat object" "répéter objet")
("replace" "remplacer")
("replace by" "remplacer par")
("replace toolbar" "barre de remplacement")
("replace unrecognized styles" "remplacer des styles non reconnus")
("replaced" "j'ai remplacé")
("replaced one occurrence" "j'ai remplacé une occurrence")
("reset" "remettre")
("resize" "redimensionner")
("resize object" "redimensionner objet")
("resized" "redimensionné")
("retime" "transformer le temps")
("retina settings" "paramètres d'écran rétina")
("return" "entrée")
("revert" "réactualiser")
("revert buffer" "actualiser tampon")
("right" "à droite")
("right aligned" "aligné à droite")
("right arrow" "flèche vers la droite")
("right border" "limite à droite")
("right cell border" "bordure de la cellule à droite")
("right margin" "marge à droite")
("right padding" "espacement à droite")
("right page margin" "marge de page à droite")
("right subscript" "indice à droite")
("right superscript" "exposant à droite")
("right surrounding" "entourage à droite")
("right table border" "bordure du tableau à droite")
("rightwards..." "de gauche à droite...")
("rigid" "fixe")
("rigid box" "boîte fixe")
("rigid horizontal" "horizontal fixe")
("rigid space" "espace fixe")
("roman" "romain")
("romanian" "roumain")
("root" "racine")
("rotate" "tourner")
("rotate backward" "tourner en arrière")
("rotate forward" "tourner en avant")
("row" "ligne")
("row above" "ligne au dessus")
("row below" "ligne en dessous")
("row contains glued items" "la ligne contient des parties collées")
("rows" "lignes")
("run" "exécuter")
("runic" "runes")
("running author" "auteur courant")
("running title" "titre courant")
("russian" "russe")
("russian and Ukrainian users" "utilisateurs Russes et Ukrainiens")
("same screen margins as on paper" "mêmes marges sur l'écran et sur le papier")
("sample" "échantillon")
("sample text" "échantillon de texte")
("sans serif" "sans sérifs")
("save" "sauvegarder")
("save TeXmacs file" "sauvegarder fichier TeXmacs")
("save TeXmacs style file" "sauvegarder fichier de style TeXmacs")
("save as" "sauvegarder sous")
("save as LaTeX" "sauvegarder comme LaTeX")
("save as TeX" "sauvegarder comme TeX")
("save auxiliary data" "sauvegarder les données auxiliaires")
("save buffer" "sauvegarder tampon")
("save buffer as" "sauvegarder tampon sous")
("save file" "sauvegarder fichier")
("save html file" "sauvegarder fichier html")
("save image" "sauvegarder image")
("save latex file" "sauvegarder fichier latex")
("save position" "retenir la position")
("save tex file" "sauvegarder fichier tex")
("save this buffer" "sauvegarder ce tampon")
("save verbatim file" "sauvegarder fichier verbatim")
("saved" "sauvegardé")
("scheme command" "commande scheme")
("scheme developers guide" "guide pour développeurs en Scheme")
("scheme extensions" "extensions scheme")
("screen" "écran")
("screen layout" "apparence sur l'écran")
("screen margins" "marges sur l'écran")
("screen rendering" "rendu sur écran")
("screens" "écrans")
("script" "indice")
("script above" "indice en haut")
("script below" "indice en bas")
("script script size" "taille d'indices d'indices")
("script size" "taille d'indices")
("scripting language" "langage de scripts")
("scripts not accepted" "les scripts ne sont jamais acceptés")
("search" "chercher")
("search and replace" "chercher et remplacer")
("search results for" "resultats de la recherche pour")
("search toolbar" "barre de recherche")
("search words in my documents" "chercher des mots dans mes documents")
("search words in the documentation" "chercher des mots dans la documentation")
("search words in the source code" "chercher des mots dans le code source")
("searching" "cherche")
("secondary" "secondaire")
("section" "section")
("security" "sécurité")
("see" "voir")
("select a document style" "sélectionner un style de document")
("select a foreground color" "sélectionner une couleur")
("select a language" "sélectionner une langue")
("select view mode" "mode de visualisation")
("selected region" "région sélectionnée")
("selection" "sélection")
("selections" "sélections")
("seminar" "séminaire")
("sending commands to TeXmacs" "envoi de commandes à TeXmacs")
("separation between lines" "espacement entre les lignes")
("separation between paragraphs" "espacement entre les paragraphes")
("separator" "séparateur")
("september" "septembre")
("serb" "serbe")
("series" "espèce")
("series|right" "droit")
("session" "session")
("session name" "nom de la session")
("session type" "type de la session")
("sessions" "sessions")
("set" "mettre")
("set background color of cell" "changer la couleur de la cellule")
("set cell mode" "mode d'opération sur les cellules")
("set extension center" "centre d'extension")
("set height" "changer hauteur")
("set height of cell" "changer la hauteur de la cellule")
("set margins" "changer indentations")
("set n" "entrer n")
("set or get environment variables" "changer ou obtenir des variables d'environnement")
("set paragraph margins" "changer les marges du paragraphe")
("set paragraph mode" "changer le mode d'alignement du paragraphe")
("set printer dpi" "spécifier résolution de l'imprimante")
("set printing command" "commande pour imprimer")
("set span" "changer portée")
("set special cell properties" "changer propriétés spéciales de la cellule")
("set special table properties" "changer propriétés spéciales du tableau")
("set text width" "changer largeur du texte")
("set width" "changer largeur")
("set width of cell" "changer la largeur de la cellule")
("settings" "réglage")
("setup printer" "configurer imprimante")
("several equations" "plusieurs équations")
("shadow" "ombre")
("shadowed" "ombre")
("shadowed raise" "élever avec ombre")
("shape" "forme")
("shift" "décaler")
("shift-down" "shift-bas")
("shift-right" "shift-droite")
("short" "court")
("show" "afficher")
("show all" "tout afficher")
("show all parts" "montrer toutes les parties")
("show header and footer" "afficher en-tête et pied de page")
("show hidden" "montrer partie cachée")
("show key presses" "montrer les frappes sur le clavier")
("show on screen" "montrer sur l'écran")
("show one part" "montrer une partie")
("show panorama" "mode de panorama")
("show several parts" "montrer plusieurs parties")
("shrinking factor" "facteur de réduction")
("signature" "signature")
("simplification" "simplification")
("simplified evaluation of formulas" "évaluation simplifiée de formules")
("simplified menus" "menus simplifiés")
("simplify" "simplifier")
("sine" "sinus")
("size" "taille")
("size limits" "limitations de taille")
("size tag" "balise de taille")
("skew" "tordre")
("slant" "pente")
("slanted" "oblique")
("slides" "diapositives")
("sloppy" "relâché")
("slovene" "slovène")
("small" "petit")
("small caps" "petites majuscules")
("small figure" "petite figure")
("small skip" "petit saut")
("small table" "petit tableau")
("smash" "écraser")
("solution" "solution")
("solve" "résoudre")
("solve in" "résoudre en")
("solving equations" "résolution d'équations")
("sound..." "son...")
("source code" "code source")
("source macros tool" "outil pour les macros des sources")
("source tags" "balises du code source")
("space" "espace")
("space bar in math mode" "barre d'espace en mode math")
("space bar in text mode" "barre d'espace en mode texte")
("space between lines" "espace d'interligne")
("space between paragraphs" "espace d'interparagraphe")
("spacing" "espacement")
("span" "portée")
("spanish" "espagnol")
("special" "spécial")
("special cell properties" "propriétés spéciales de la cellule")
("special functions" "fonctions spéciales")
("special properties" "propriétés spéciales")
("special table properties" "propriétés spéciales du tableau")
("specific" "spécifique")
("specify the size of the table" "spécifier la taille du tableau")
("spell" "orthographe")
("spell check" "correction d'orthographe")
("spelling error" "faute d'orthographe")
("spelling errors have been corrected" "les fautes d'orthographe ont été corrigées")
("split" "division")
("split session" "diviser la session")
("square root" "racine carrée")
("standard TeXmacs styles" "styles TeXmacs standards")
("standard environment variables" "variables d'environnement standards")
("standard formats" "formats standards")
("start" "début")
("start a new chapter" "commencer un nouveau chapitre")
("start a new section" "commencer une nouvelle section")
("start an interactive session" "commencer une session interactive")
("statistics" "statistiques")
("status bar" "barre d'état")
("stretch" "étirer")
("stretch factor" "facteur d'étirement")
("stretchable" "étirable")
("stretchable horizontal" "horizontal étirable")
("stretchable vertical" "vertical étirable")
("stretched" "étiré")
("strict Ascii" "Ascii strict")
("strike through" "barrer")
("stroke" "tiret")
("strokes" "tirets")
("strong" "important")
("structural" "structurel")
("structured insert above" "insertion structurée vers le haut")
("structured insert at the left" "insertion structurée vers la gauche")
("structured insert at the right" "insertion structurée vers la droite")
("structured insert below" "insertion structurée vers le bas")
("structured remove downwards" "suppression structurée vers le bas")
("structured remove leftwards" "suppression structurée vers la gauche")
("structured remove rightwards" "suppression structurée vers la droite")
("structured remove upwards" "suppression structurée vers le haut")
("structured variant" "variante structurée")
("style" "style")
("styles" "styles")
("stylesheet language" "langage des feuilles de style")
("sub" "sous")
("subject" "sujet")
("subparagraph" "sous-paragraphe")
("subscript" "indice")
("subsection" "sous-section")
("subsub" "sous-sous")
("subsubsection" "sous-sous-section")
("subtable" "sous-tableau")
("subtitle" "sous-titre")
("summarized" "résumé")
("summary" "résumé")
("summary of the principal TeXmacs tags" "les principaux marqueurs de contenu")
("superpose" "superposer")
("superposed" "superposé")
("superscript" "exposant")
("surface" "surface")
("swedish" "suédois")
("swell" "gonfler")
("swiss" "suisse")
("switch" "commutateur")
("switch to first" "passer au premier")
("switch to formula style" "basculer vers le style de formules")
("switch to last" "passer au dernier")
("switch to next" "passer au suivant")
("switch to previous" "passer au précédant")
("switching and folding" "commuter et plier")
("symbol" "symbole")
("system command" "commande système")
("system environment variables" "variables d'environnement système")
("tab" "tabulation")
("tabbed" "tabulé")
("table" "tableau")
("table command" "commande de tableau")
("table height" "hauteur du tableau")
("table of contents" "table des matières")
("table properties" "propriétés du tableau")
("table width" "largeur du tableau")
("tables" "tableaux")
("tabular" "tabuler")
("tabular material" "tableaux")
("tangent" "tangente")
("teXmacs as an interface" "teXmacs en tant qu'interface")
("teXmacs fonts" "les polices TeXmacs")
("teXmacs notice" "avis sur TeXmacs")
("teXmacs primitives" "primitives de TeXmacs")
("teXmacs style files" "fichiers de style TeXmacs")
("technical report" "rapport technique")
("ternary" "tertiaire")
("test" "test")
("tex" "tex")
("text" "texte")
("text font" "police en mode texte")
("text height correction" "correction de la hauteur du texte")
("text width" "largeur du texte")
("texts" "textes")
("th century bc" "ième siècle avant J.C.")
("th root" "ième racine")
("thai" "thaï")
("the TeXmacs authors" "les auteurs de TeXmacs")
("the TeXmacs format" "le format TeXmacs")
("the application did not send its usual startup banner" "l'application n'a pas envoyé son message habituel de lancement")
("the application does not reply" "l'application ne répond pas")
("the application is already running" "l'application tourne déjà")
("the boxes produced by the typesetter" "les boîtes produites par le metteur en page")
("the document has not been saved" "ce document n'a pas été sauvegardé")
("the graphical user interface" "interface graphique d'utilisateur")
("the leaves of TeXmacs trees" "les feuilles des arbres TeXmacs")
("the mycas example" "l'exemple 'mycas'")
("the primitive TeXmacs constructs" "constructeurs TeXmacs primitifs")
("the standard TeXmacs styles" "les styles TeXmacs standards")
("the texmacs plugin system" "le système de plugins de texmacs")
("theorem" "théorème")
("there are unsaved documents" "tous les fichiers n'ont pas été sauvegardés")
("thicken" "épaissir")
("this column" "cette colonne")
("this document has been produced using" "ce document a été conçu avec")
("this document has not been saved" "ce document n'a pas été sauvegardé")
("this line" "cette ligne")
("this page" "cette page")
("this page footer" "au bas de cette page")
("this page header" "en-tête de cette page")
("this row" "cette ligne")
("three columns" "trois colonnes")
("through popup windows" "dans des fenêtres popup")
("through the menus" "via les menus")
("thumbnails" "onglets d'images")
("tilda" "tilde")
("tilde" "tilde")
("times" "fois")
("tiny" "minuscule")
("title" "titre")
("to the left" "vers la gauche")
("to the right" "vers la droite")
("today" "aujourd'hui")
("toggle cell wrapping mode" "passage automatique à la ligne")
("tools" "outils")
("top" "en haut")
("top border" "bordure en haut")
("top cell border" "bordure en haut de la cellule")
("top cell padding" "espacement en haut de la cellule")
("top level" "niveau supérieur")
("top margin" "marge en haut")
("top padding" "espacement en haut")
("top table border" "bordure en haut du tableau")
("top table padding" "espacement en haut du tableau")
("transfer" "transférer")
("transform" "transformations")
("translate" "traduire")
("transpose" "transposer")
("traversal" "traversée")
("tree" "arbre")
("triangularize" "trianguler")
("trigonometric" "trigonométrique")
("trigonometry" "trigonométrie")
("tuple" "tuplet")
("turkish" "turque")
("tutorial" "tutoriel")
("two columns" "deux colonnes")
("type" "type")
("type 1 only" "type 1 seulement")
("type 1 with metafont fallback" "type")
("type a latex command followed by" "tapez une commande latex, puis")
("type body" "entrer corps")
("type denominator" "entrer dénominateur")
("type numerator" "entrer numérateur")
("type script" "entrer indice")
("typesetted boxes" "boîtes typographiées")
("typewriter" "machine à écrire")
("typewriter small caps" "petites majuscules machine à écrire")
("typing a simple text" "saisie d'un texte simple")
("typing simple texts" "saisie de textes simples")
("ugaritic" "ougaritique")
("ukrainian" "ukrainien")
("underbrace" "accolade en dessous")
("underline" "souligner")
("underlined" "souligné")
("undo" "annuler")
("undo last changes" "annuler les derniers changements")
("unfold" "déplier")
("unroll" "déroulé")
("up" "en haut")
("update" "actualiser")
("update from web" "réactualiser à partir du réseau")
("update image links" "mise à jour des images liées")
("update this buffer" "réactualiser le document")
("update web site" "mise à jour du site web")
("upgrade" "mise à jour")
("upper border" "limite en haut")
("upright" "droit")
("upwards..." "de bas en haut...")
("use CSS for more advanced formatting" "utiliser CSS pour améliorer la mise en page")
("use MathML" "utiliser MathML")
("use TeXmacs" "utilisez TeXmacs")
("use a black color" "utiliser une couleur noire")
("use a blue color" "utiliser une couleur bleue")
("use a bold font" "utiliser une police grasse")
("use a brown color" "utiliser une couleur brune")
("use a calligraphic font" "utiliser une police calligraphique")
("use a green color" "utiliser une couleur verte")
("use a grey color" "utiliser une couleur grise")
("use a magenta color" "utiliser une couleur mauve")
("use a orange color" "utiliser une couleur orange")
("use a pink color" "utiliser une couleur rose")
("use a red color" "utiliser une couleur rouge")
("use a sans serif font" "utiliser une police sans sérifs")
("use a typewriter font" "utiliser une police de machine à écrire")
("use a white color" "utiliser une couleur blanche")
("use a yellow color" "utiliser une couleur jaune")
("use as master" "utiliser comme document maître")
("use blackboard bold font" "utiliser la police pour tableau noir")
("use bold font series" "utiliser une police grasse")
("use calligraphic font" "utiliser la police calligraphique")
("use calligraphical font" "utiliser une police calligraphique")
("use catcode definitions in preamble" "utiliser des catcodes dans la préambule")
("use extensible brackets" "parenthèses extensibles")
("use footnote font size" "utiliser une très petite police")
("use fraktur font" "utiliser la police Gothique")
("use huge font size" "utiliser une police énorme")
("use italic font shape" "utiliser une police italique")
("use large font size" "utiliser une grande police")
("use left hand column as border" "utiliser colonne à gauche comme bordure")
("use medium font series" "utiliser une police d'épaisseur normale")
("use normal font size" "utiliser une police de taille normale")
("use package" "utiliser paquetage")
("use paragraph width" "utiliser largeur du paragraphe")
("use really huge font size" "utiliser une police vraiment énorme")
("use right font shape" "utiliser une police droite")
("use right hand column as border" "utiliser colonne à droite comme bordure")
("use roman font family" "utiliser la police romain")
("use row above as border" "utiliser ligne en haut comme bordure")
("use row below as border" "utiliser ligne en bas comme bordure")
("use sans serif font family" "utiliser la police sans sérifs")
("use script font size" "utiliser une très petite police")
("use slanted font shape" "utiliser une police oblique")
("use small capitals" "utiliser des petites majuscules")
("use small font size" "utiliser une petite police")
("use small-caps font shape" "utiliser une police de petites majuscules")
("use the blackboard bold font" "utiliser la police de tableau noir gras")
("use the fraktur font" "utiliser la police fraktur")
("use tiny font font size" "utiliser une police minuscule")
("use typewriter font family" "utiliser la police machine à écrire")
("use very large font size" "utiliser une très grande police")
("user interface language" "langue de l'interface utilisateur")
("user manual" "manuel d'utilisation")
("user preferences" "préférences de l'utilisateur")
("user provided icons" "icônes définies par l'utilisateur")
("users of Cyrillic languages" "utilisateurs de langues cyrilliques")
("users of oriental languages" "utilisateurs de langues orientales")
("utf-8 with inputenc LaTeX package" "Utf-8 avec le paquet LaTeX inputenc")
("utilities" "utilitaires")
("value" "valeur")
("vanish" "disparaître")
("variable" "variable")
("variant" "variante")
("vector" "vecteur")
("verbatim" "verbatim")
("verse" "vers")
("versioning tool" "outil de gestion des versions")
("vertical" "vertical")
("vertical after" "vertical après")
("vertical alignment" "alignement vertical")
("vertical before" "vertical avant")
("vertical cell alignment" "alignement vertical de la cellule")
("vertical part" "partie verticale")
("vertical position" "position verticale")
("vertical space" "espace vertical")
("vertical space after" "espace vertical après")
("vertical space before" "espace vertical avant")
("vertical table alignment" "alignmement vertical du tableau")
("vertically align cell to the base" "alignement verticale de la cellule à la base")
("vertically center the cell" "centrer la cellule verticalement")
("very large" "très grand")
("very small" "très petit")
("vietnamese" "vietnamien")
("view" "vue")
("visible" "visible")
("volume" "volume")
("w.r.t." "suivant")
("warning" "avertissement")
("web" "toile")
("weight" "graisse")
("welcome" "bienvenue")
("welcome to GNU TeXmacs" "bienvenue à GNU TeXmacs")
("what is new" "nouveautés")
("when finished" "pour terminer")
("when line wrapping" "si passage à la ligne automatique")
("while" "tant que")
("white" "blanc")
("whitespace" "espace")
("wide" "large")
("wide accent" "accent large")
("wide bar" "barre large")
("wide block" "Bloc en largeur")
("wide colored" "large colorié")
("wide tabular" "Tableau en largeur")
("width" "largeur")
("width is exactly the specified width" "utiliser la largeur spécifiée")
("width is maximum of specified width and box width" "utiliser maximum de la largeur spécifiée et la largeur de la boîte")
("width is minimum of specified width and box width" "utiliser minimum de la largeur spécifiée et la largeur de la boîte")
("width magnification" "agrandissement de la largeur")
("window" "fenêtre")
("window height" "hauteur de fenêtre")
("window width" "largeur de fenêtre")
("windows key" "touche windows")
("with" "avec")
("wrap lines" "couper les lignes")
("write" "écriture")
("write a macro" "écrire un macro")
("write a name" "écrire un nom")
("write bold mathematics" "écrire des mathématiques en gras")
("write bold text" "écrire en gras")
("write italic text" "écrire en italique")
("write sample text" "écrire du texte illustratif")
("write strong text" "écrire du texte important")
("write typewriter text" "écrire du texte de machine à écrire")
("write verbatim text" "écrire en verbatim")
("writing data converters" "écrire des convertisseurs de données")
("writing documentation" "pour écrire de la documentation")
("writing your own style files" "écrire vos propres feuilles de style")
("written with TeXmacs" "conçu avec TeXmacs")
("yellow" "jaune")
("yes" "oui")
("you can also obtain" "vous pouvez également obtenir")
("your document is back in its original state" "votre document est revenu dans son état original")
("your first interface" "votre première interface")
("your language" "votre langue")
("zoom" "zoomer")
("zoom in" "agrandir")
("zoom out" "réduire")
