#!/bin/sh
# Program to make the documentation of the Scheme interface to TeXmacs
#
#   build-auto-doc [scheme-bin]      (see build-glue)

SCHEME_BIN=${GUILE_BIN:-guile}
if test $# = 1 -a -n "$1"; then
  SCHEME_BIN=$1
fi

generate () {
  # only replace the output when the generator succeeded
  $SCHEME_BIN -l $1 -c "(quit)" > $2.tmp && test -s $2.tmp \
    && mv $2.tmp $2 || { rm -f $2.tmp; echo "build-auto-doc: failed to generate $2"; exit 1; }
}

generate make-apidoc-module.scm ../../../TeXmacs/progs/prog/glue-symbols.scm
generate make-apidoc-doc.scm ../../../TeXmacs/doc/devel/scheme/api/glue-auto-doc.en.tm
