#!/bin/sh
# Program to make Guile interface to TeXmacs

GUILE_BIN=${GUILE_BIN:-guile}
if test $# = 3; then
  GUILE_BIN=$3
fi

./build-auto-doc "$GUILE_BIN"

if test $# -ne 2 -a $# -ne 3; then
  echo "Usage: build-glue <input.scm> <output.cpp> [guile-bin]"
  exit 1
fi

$GUILE_BIN -l build-glue.scm -l $1 -c "(quit)" | cat > $2
$GUILE_BIN -l build-glue.scm -l $1 -c "(quit)" | cat > $2
$GUILE_BIN -l build-glue.scm -l $1 -c "(quit)" | cat > $2
$GUILE_BIN -l build-glue.scm -l $1 -c "(quit)" | cat > $2
