
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : math-speech-fr.scm
;; DESCRIPTION : mathematical editing using French speech
;; COPYRIGHT   : (C) 2022  Joris van der Hoeven
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (math math-speech-fr)
  (:use (math math-speech)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sanitize input
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-table french-numbers
  ("0" "zéro") ("1" "un") ("2" "deux") ("3" "trois") ("4" "quatre")
  ("5" "cinq") ("6" "six") ("7" "sept") ("8" "huit") ("9" "neuf"))

(define-table french-ambiguate
  ("deux" "2/de"))

(define (string-table-replace s t)
  (with repl (lambda (x) (with y (ahash-ref t x) (if y (car y) x)))
    (with l (string-decompose s " ")
      (string-recompose (map repl l) " "))))

(tm-define (speech-pre-sanitize lan s)
  (:require (== lan 'french))
  (set! s (clean-quotes s))
  s)

(define (rewrite-/ s)
  (with l (string-decompose s "/")
    (if (and (== (length l) 2)
             (string-number? (car l))
             (string-number? (cadr l)))
        (string-replace s "/" " @sur ")
        s)))

(tm-define (speech-sanitize lan mode s)
  (:require (and (== lan 'french) (== mode 'math)))
  (set! s (locase-all s))
  (set! s (letterize s))
  (set! s (list->tmstring (clean-letter-digit (tmstring->list s))))
  (set! s (string-recompose (map rewrite-/ (string-decompose s " ")) " "))
  (set! s (clean-quotes s))
  (set! s (string-replace s "+" " plus "))
  (set! s (string-replace-trailing s "-" " moins "))
  (set! s (string-replace s "<times>" " fois "))
  (set! s (string-replace-trailing s "." " point "))
  (set! s (string-replace s "=" " égal "))
  (set! s (string-replace s "," " virgule "))
  (set! s (string-replace s ":" " double points "))
  (set! s (string-replace s ";" " point virgule "))
  (set! s (string-replace s "^" " chapeau "))
  (set! s (string-replace s "~" " tilde "))
  (set! s (string-replace s "(" " ( "))
  (set! s (string-replace s ")" " ) "))
  (set! s (string-replace s "[" " [ "))
  (set! s (string-replace s "]" " ] "))
  (set! s (string-replace s "{" " { "))
  (set! s (string-replace s "}" " } "))
  (set! s (string-replace s "<ldots>" " points "))
  (set! s (string-replace s "<cdots>" " points "))
  (set! s (string-table-replace s french-numbers))
  (set! s (string-table-replace s french-ambiguate))
  (set! s (string-replace s "  " " "))
  (set! s (string-replace s "  " " "))
  (set! s (tm-string-trim-both s))
  (set! s (french-normalize 'math s))
  s)

(speech-collection dont-break french
  "ah" "ai" "an" "ar" "as" "at" "au"
  "el" "en" "es" "et" "eu" "ex" "ét"
  "il" "oh" "ok" "on" "os" "ou" "un" "ye" "yo"

  "la" "ma" "ta" "za" "de" "he" "je" "le" "ne" "se" "te"
  "bi" "hi" "ji" "pi" "si" "ti" "xi"
  "ho" "no" "to" "du" "mu" "nu" "tu" "sy")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Normalization of French text (singular/plural, masculin/feminin, etc.)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (french-resuffix* mode s suf1 suf2)
  (and (string-ends? s suf1)
       (let* ((l1 (string-length s))
              (l2 (string-length suf1))
              (r  (string-append (substring s 0 (- l1 l2)) suf2)))
         (and (>= l1 (+ l2 3))
              (raw-speech-accepts? 'french mode r)
              r))))

(define (french-resuffix mode s suf1 suf2)
  (or (french-resuffix* mode s suf1 suf2)
      (french-resuffix* mode s suf2 suf1)))

(define (french-normalize-one mode s)
  (or (and (raw-speech-accepts? 'french mode s) s)
      (french-resuffix mode s "e" "")
      (french-resuffix mode s "s" "")
      (french-resuffix mode s "es" "")
      (french-resuffix mode s "x" "")
      (french-resuffix mode s "aux" "al")
      (french-resuffix mode s "ère" "er")
      (french-resuffix mode s "ères" "ers")
      (french-resuffix mode s "ères" "er")
      (french-resuffix mode s "ve" "f")
      (french-resuffix mode s "ves" "f")
      (french-resuffix mode s "ves" "fs")
      (french-resuffix mode s "er" "")
      (french-resuffix mode s "er" "e")
      (french-resuffix mode s "er" "es")
      (french-resuffix mode s "er" "ent")
      (french-resuffix mode s "er" "é")
      (french-resuffix mode s "er" "ée")
      (french-resuffix mode s "er" "és")
      (french-resuffix mode s "er" "ées")
      (french-resuffix mode s "ir" "")
      (french-resuffix mode s "ir" "e")
      (french-resuffix mode s "ir" "es")
      (french-resuffix mode s "ir" "ent")
      (french-resuffix mode s "tir" "s")
      (french-resuffix mode s "re" "")
      (french-resuffix mode s "re" "s")
      (french-resuffix mode s "re" "ent")
      (french-resuffix mode s "qu'" "que")
      s))

(define (french-normalize-compute mode s)
  (let* ((l (string-decompose s " "))
         (r (map (cut french-normalize-one mode <>) l)))
    (string-recompose r " ")))

(define french-normal-table (make-ahash-table))

(tm-define (french-normalize mode s)
  (with key (list mode s)
    (when (not (ahash-ref french-normal-table key))
      (ahash-set! french-normal-table key (french-normalize-compute mode s)))
    (ahash-ref french-normal-table key)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Entering mathematical symbols via French speech
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(speech-symbols french
  ("zéro" "0")
  ("un" "1")
  ("deux" "2")
  ("trois" "3")
  ("quatre" "4")
  ("cinq" "5")
  ("six" "6")
  ("sept" "7")
  ("huit" "8")
  ("neuf" "9")
  ("dix" "10")
  ("cent" "100")
  ("mille" "1000")
  ("million" "1000000")
  ("milliard" "1000000000")

  ("a" "a")
  ("à" "a")
  ("b" "b")
  ("c" "c")
  ("d" "d")
  ("e" "e")
  ("f" "f")
  ("g" "g")
  ("h" "h")
  ("i" "i")
  ("j" "j")
  ("k" "k")
  ("l" "l")
  ("m" "m")
  ("n" "n")
  ("o" "o")
  ("p" "p")
  ("q" "q")
  ("r" "r")
  ("s" "s")
  ("t" "t")
  ("u" "u")
  ("v" "v")
  ("w" "w")
  ("x" "x")
  ("y" "y")
  ("z" "z")

  ("alpha" "<alpha>")
  ("beta" "<beta>")
  ("gamma" "<gamma>")
  ("delta" "<delta>")
  ("epsilon" "<epsilon>")
  ("zeta" "<zeta>")
  ("eta" "<eta>")
  ("theta" "<theta>")
  ("iota" "<iota>")
  ("kappa" "<kappa>")
  ("lambda" "<lambda>")
  ("mu" "<mu>")
  ("nu" "<nu>")
  ("xi" "<xi>")
  ("omicron" "<omicron>")
  ("pi" "<pi>")
  ("rho" "<rho>")
  ("sigma" "<sigma>")
  ("tau" "<tau>")
  ("upsilon" "<upsilon>")
  ("phi" "<phi>")
  ("psi" "<psi>")
  ("chi" "<chi>")
  ("omega" "<omega>")

  ("constante e" "<mathe>")
  ("constante i" "<mathi>")
  ("constante pi" "<mathpi>")
  ("constante gamma" "<mathgamma>")
  ("constante d'euler" "<mathgamma>")
  ("nombre e" "<mathe>")
  ("nombre i" "<mathi>")
  ("nombre pi" "<mathpi>")
  ("nombre gamma" "<mathgamma>")

  ("infini" "<infty>")
  ("complexes" "<bbb-C>")
  ("entiers positifs" "<bbb-N>")
  ("rationnels" "<bbb-Q>")
  ("réels" "<bbb-R>")
  ("entiers" "<bbb-Z>")

  ("plus" "+")
  ("moins" "-")
  ("fois" "*")
  ("croix" "<times>")
  ("appliquer" " ")
  ("espace" " ")
  ("rond" "<circ>")
  ("tenseur" "<otimes>")
  ("factoriel" "!")

  ("égal" "=")
  ("non égal" "<neq>")
  ("inférieur" "<less>")
  ("inférieur égal" "<leqslant>")
  ("supérieur" "<gtr>")
  ("supérieur égal" "<geqslant>")
  ("dans" "<in>")
  ("contient" "<ni>")
  ("inclus dans" "<subset>")
  ("inclut" "<supset>")

  ("similaire" "<sim>")
  ("asymptotique" "<asymp>")
  ;;("approx" "<approx>")
  ("isomorphe" "<cong>")
  ("négligeable" "<prec>")
  ("dominé" "<preccurlyeq>")
  ("domine" "<succcurlyeq>")
  ("domine strictement" "<succ>")

  ("flèche" "<rightarrow>")
  ("longue flèche" "<rightarrow>")

  ("pour tout" "<forall>")
  ("existe" "<exists>")
  ("ou" "<vee>")
  ("et" "<wedge>")
  ("implique" "<Rightarrow>")
  ("équivaut" "<Leftrightarrow>")

  ("point" ".")
  ("virgule" ",")
  ("double point" ":")
  ("point virgule" ";")
  ("point d'exclamation" "!")
  ("point d'interrogation" "?")
  ("." ".")
  ("," ",")
  (":" ":")
  (";" ";")
  ("!" "!")
  ("?" "?")
  ("tel que" "<suchthat>")
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; More complex mathematical speech commands
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(speech-map french math
  ("grand" (speech-alter-letter :big))
  ("petit" (speech-alter-letter :small))
  ("majuscule" (speech-alter-letter* :big))
  ("minuscule" (speech-alter-letter* :small))
  ("gras" (speech-alter-letter* :bold))
  ("medium" (speech-alter-letter* :medium))
  ("droit" (speech-alter-letter* :up))
  ("italique" (speech-alter-letter* :it))
  ("calligraphique" (speech-alter-letter* :cal))
  ("fraktur" (speech-alter-letter* :frak))
  ("tableau noir gras" (speech-alter-letter* :bbb))
  ("double" (speech-alter-letter* :bbb))
  ("normal" (speech-alter-letter* :normal))
  ("sans serif" (speech-alter-letter* :ss))
  ("machine à écrire" (speech-alter-letter* :tt))
  ("opérateur" (speech-operator))

  ("facteur" (speech-factor))
  ("inverse" (speech-insert-superscript "-1"))
  ("carré" (speech-insert-superscript "2"))
  ("cube" (speech-insert-superscript "3"))
  ("transpose" (speech-insert-superscript "<top>"))
  ("indice" (speech-short-subscript))
  ("grand indice" (speech-subscript))
  ("puissance" (speech-short-superscript))
  ("exposant" (speech-superscript))
  ("début indice" (make 'rsub))
  ("début exposant" (make 'rsup))
  ("fin indice" (speech-end 'rsub))
  ("fin exposant" (speech-end 'rsup))

  ("prime" (make-rprime "'"))
  ("double prime" (make-rprime "'") (make-rprime "'"))
  ("triple prime" (make-rprime "'") (make-rprime "'") (make-rprime "'"))
  ("adjoint" (make-rprime "<asterisk>"))

  ("chapeau" (speech-accent "^"))
  ("tilde" (speech-accent "~"))
  ("barre" (speech-accent "<bar>"))
  ("large chapeau" (speech-wide "^"))
  ("large tilde" (speech-wide "~"))
  ("large barre" (speech-wide "<bar>"))
  ("dessous" (speech-under))

  ("de" (speech-of))
  ("ouvrir" (speech-open "(" ")"))
  ("fermer" (speech-close))
  ("parenthèses" (speech-brackets "(" ")"))
  ("crochets" (speech-brackets "[" "]"))
  ("accolades" (speech-brackets "{" "}"))
  ("chevrons" (speech-brackets "<langle>" "<rangle>"))
  ("partie entière" (speech-brackets "<lfloor>" "<rfloor>"))
  ("ouvrir parenthèses" (speech-open "(" ")"))
  ("ouvrir crochets" (speech-open "[" "]"))
  ("ouvrir accolades" (speech-open "{" "}"))
  ("ouvrir chevrons" (speech-open "<langle>" "<rangle>"))
  ("ouvrir partie entière" (speech-open "<lfloor>" "<rfloor>"))

  ("(" (speech-open "(" ")"))
  ("[" (speech-open "[" "]"))
  ("{" (speech-open "{" "}"))
  (")" (speech-close))
  ("]" (speech-close))
  ("}" (speech-close))
  
  ("arc cos" (speech-insert-operator "arccos"))
  ("arc sin" (speech-insert-operator "arcsin"))
  ("arc tan" (speech-insert-operator "arctan"))
  ("arg" (speech-insert-operator "arg"))
  ("cos" (speech-insert-operator "cos"))
  ("deg" (speech-insert-operator "deg"))
  ("det" (speech-insert-operator "det"))
  ("dim" (speech-insert-operator "dim"))
  ("exp" (speech-insert-operator "exp"))
  ("gcd" (speech-insert-operator "gcd"))
  ("log" (speech-insert-operator "log"))
  ("hom" (speech-insert-operator "hom"))
  ("inf" (speech-insert-operator "inf"))
  ("ker" (speech-insert-operator "ker"))
  ("lcm" (speech-insert-operator "lcm"))
  ("lim" (speech-insert-operator "lim"))
  ("lim inf" (speech-insert-operator "liminf"))
  ("lim sup" (speech-insert-operator "limsup"))
  ("ln" (speech-insert-operator "ln"))
  ("log" (speech-insert-operator "log"))
  ("max" (speech-insert-operator "max"))
  ("min" (speech-insert-operator "min"))
  ("Pr" (speech-insert-operator "Pr"))
  ("sin" (speech-insert-operator "sin"))
  ("supremum" (speech-insert-operator "sup"))
  ("tan" (speech-insert-operator "tan"))
  
  ("plus points plus" (speech-dots "+" "<cdots>"))
  ("moins points moins" (speech-dots "-" "<cdots>"))
  ("fois points fois" (speech-dots "*" "<cdots>"))
  ("virgule points virgule" (speech-dots "," "<ldots>"))
  ("et points et" (speech-dots "<wedge>" "<cdots>"))
  ("ou points ou" (speech-dots "<vee>" "<cdots>"))
  ("égal points égal" (speech-dots "=" "<cdots>"))
  ("similaire points similaire" (speech-dots "<sim>" "<cdots>"))
  ("inférieur points inférieur" (speech-dots "<less>" "<cdots>"))
  ("inférieur égal points inférieur égal" (speech-dots "<leqslant>" "<cdots>"))
  ("supérieur points supérieur" (speech-dots "<gtr>" "<cdots>"))
  ("supérieur égal points supérieur égal" (speech-dots "<geqslant>" "<cdots>"))
  ("rond points rond" (speech-dots "<circ>" "<cdots>"))
  ("tenseur points tenseur" (speech-dots "<otimes>" "<cdots>"))

  ("somme" (math-big-operator "sum"))
  ("produit" (math-big-operator "prod"))
  ("intégrale" (math-big-operator "int"))
  ("intégrale de contours" (math-big-operator "oint"))
  ("intégrale double" (math-big-operator "iint"))
  ("intégrale triple" (math-big-operator "iiint"))
  ("double intégrale" (math-big-operator "iint"))
  ("triple intégrale" (math-big-operator "iiint"))
  ("pour" (speech-for))
  ("jusqu'à" (speech-until))

  ("racine carrée" (speech-sqrt-of))
  ("racine carrée de" (speech-sqrt-of))
  ("racine carrée 2/de" (speech-sqrt-of))
  ("début racine carrée" (speech-sqrt))
  ("fin racine carrée" (speech-end 'sqrt))
  ("sur" (speech-over))
  ("@sur" (speech-short-over))
  ("fraction" (speech-fraction))
  ("début fraction" (speech-fraction))
  ("numérateur" (go-to-fraction :numerator))
  ("dénominateur" (go-to-fraction :denominator))
  ("fin fraction" (speech-end 'frac))

  ("matrice" (make 'matrix))
  ("déterminant" (make 'det))
  ("choix" (make 'choice))
  ("points horizontaux" (insert "<cdots>"))
  ("points verticaux" (insert "<vdots>"))
  ("points diagonaux" (insert "<ddots>"))
  ("points montants" (insert "<udots>"))

  ;;("more" "var")
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Speech reductions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(speech-reduce french math
  ("lettre a" "a")
  ("lettre b" "b")
  ("lettre c" "c")
  ("lettre d" "d")
  ("lettre e" "e")
  ("lettre f" "f")
  ("lettre g" "g")
  ("lettre h" "h")
  ("lettre i" "i")
  ("lettre j" "j")
  ("lettre k" "k")
  ("lettre l" "l")
  ("lettre m" "m")
  ("lettre n" "n")
  ("lettre o" "o")
  ("lettre p" "p")
  ("lettre q" "q")
  ("lettre r" "r")
  ("lettre s" "s")
  ("lettre t" "t")
  ("lettre u" "u")
  ("lettre v" "v")
  ("lettre w" "w")
  ("lettre x" "x")
  ("lettre y" "y")
  ("lettre z" "z")

  ("le nombre" "nombre")
  ("la constante" "constante")
  ("la lettre" "lettre")

  ("les complexes" "complexes")
  ("les entiers positifs" "entiers positifs")
  ("les rationnels" "rationnels")
  ("les réels" "réels")
  ("les entiers" "entiers")
  ("nombres complexes" "complexes")
  ("nombres entiers positifs" "entiers positifs")
  ("nombres rationnels" "rationnels")
  ("nombres réels" "réels")
  ("nombres entiers" "entiers")

  ("partie entière de" "partie entière")
  ("partie entière 2/de" "partie entière")
  ("fermer parenthèses" "fermer")
  ("fermer crochets" "fermer")
  ("fermer accolades" "fermer")
  ("fermer chevrons" "fermer")
  ("fermer partie entière" "fermer")

  ("ouvrir le" "ouvrir")
  ("ouvrir la" "ouvrir")
  ("ouvrir les" "ouvrir")
  ("ouvrir un" "ouvrir")
  ("ouvrir une" "ouvrir")
  ("ouvrir des" "ouvrir")
  ("fermer le" "fermer")
  ("fermer la" "fermer")
  ("fermer les" "fermer")
  ("fermer un" "fermer")
  ("fermer une" "fermer")
  ("fermer des" "fermer")

  ("ensemble" "accolades")
  ("ensemble de" "accolades")
  ("ensemble 2/de" "accolades")
  ("ensemble des" "accolades")
  ("l'ensemble" "accolades")
  ("l'ensemble de" "accolades")
  ("l'ensemble 2/de" "accolades")
  ("l'ensemble des" "accolades")

  ("débuter" "début")
  ("démarrer" "commencer")
  ("terminer" "finir")
  ("un indice" "indice")
  ("l'indice" "indice")
  ("de l'indice" "indice")
  ("un exposant" "exposant")
  ("l'exposant" "exposant")
  ("de l'exposant" "exposant")
  ("une racine carrée" "racine carrée")
  ("la racine carrée" "racine carrée")
  ("de la racine carrée" "racine carrée")
  ("une fraction" "fraction")
  ("la fraction" "fraction")
  ("de la fraction" "fraction")
  ("commencer indice" "début indice")
  ("commencer exposant" "début exposant")
  ("commencer racine carrée" "début racine carrée")
  ("commencer fraction" "début fraction")
  ("insérer indice" "début indice")
  ("insérer exposant" "début exposant")
  ("insérer racine carrée" "début racine carrée")
  ("insérer fraction" "début fraction")
  ("finir indice" "fin indice")
  ("finir exposant" "fin exposant")
  ("finir racine carrée" "fin racine carrée")
  ("finir fraction" "fin fraction")
  ("sortir indice" "fin indice")
  ("sortir exposant" "fin exposant")
  ("sortir racine carrée" "fin racine carrée")
  ("sortir fraction" "fin fraction")
  ("sortir de l'indice" "fin indice")
  ("sortir de l'exposant" "fin exposant")
  ("sortir de l' indice" "fin indice")
  ("sortir de l' exposant" "fin exposant")
  ("sortir de la racine carrée" "fin racine carrée")
  ("sortir de la fraction" "fin fraction")
  ("transposé" "transpose")

  ("égal à" "égal")
  ("est égal à" "égal")

  ("pas égal" "non égal")
  ("pas égal à" "non égal")
  ("n'est pas égal à" "non égal")
  ("différent" "non égal")
  ("différent de" "non égal")
  ("différent 2/de" "non égal")
  ("est différent de" "non égal")
  ("est différent 2/de" "non égal")

  ("plus petit" "inférieur")
  ("plus petit que" "inférieur")
  ("est plus petit" "inférieur")
  ("est plus petit que" "inférieur")
  ("est inférieur" "inférieur")
  ("inférieur à" "inférieur")
  ("inférieur ou égal" "inférieur égal")

  ("plus grand" "supérieur")
  ("plus grand que" "supérieur")
  ("est plus grand" "supérieur")
  ("est plus grand que" "supérieur")
  ("est supérieur" "supérieur")
  ("supérieur à" "supérieur")
  ("supérieur ou égal" "supérieur égal")

  ("est dans" "dans")
  ("est inclus dans" "inclus dans")
  ("partie de" "inclus dans")
  ("est une partie de" "inclus dans")
  ("sous ensemble" "inclus dans")
  ("sous-ensemble" "sous ensemble")
  ("un sous ensemble" "sous ensemble")
  ("sous ensemble de" "inclus dans")
  ("sous ensemble 2/de" "inclus dans")
  ("sur ensemble" "inclut")
  ("sur-ensemble" "sur ensemble")
  ("un sur ensemble" "sur ensemble")
  ("sur ensemble de" "inclut")
  ("sur ensemble 2/de" "inclut")
  ("vers" "flèche")

  ("il existe" "existe")
  ("existe un" "existe")
  ("si et seulement si" "équivaut")

  ("appliquer à" "appliquer")
  ("la racine carrée" "racine carrée")

  ("arc cosinus" "arc cos")
  ("arc sinus" "arc sin")
  ("arc tangente" "arc tan")
  ("arccosinus" "arc cos")
  ("arcsinus" "arc sin")
  ("arctangente" "arc tan")
  ("argument" "arg")
  ("cosinus" "cos")
  ("degré" "deg")
  ("dimension" "dim")
  ("exponentielle" "exp")
  ("noyau" "ker")
  ("limite" "lim")
  ("limite inférieure" "lim inf")
  ("limite supérieure" "lim sup")
  ("lim inférieure" "lim inf")
  ("lim supérieure" "lim sup")
  ("logarithme naturel" "ln")
  ("logarithme naturels" "ln")
  ("logarithme népérien" "ln")
  ("logarithme" "log")
  ("maximum" "max")
  ("minimum" "min")
  ("probabilité" "Pr")
  ("sinus" "sin")
  ("tangente" "tan")

  ("l'arg" "arg")
  ("l'argument" "arg")
  ("le cos" "cos")
  ("le deg" "deg")
  ("le det" "det")
  ("la dim" "dim")
  ("la dimension" "dim")
  ("l'exp" "exp")
  ("l'exponentielle" "exp")
  ("le gcd" "gcd")
  ("le ker" "ker")
  ("le lcm" "lcm")
  ("la lim" "lim")
  ("la lim inf" "lim inf")
  ("la lim sup" "lim sup")
  ("la limite" "limite")
  ("la limite inférieure" "lim inf")
  ("la limite supérieure" "lim sup")
  ("le ln" "ln")
  ("le log" "log")
  ("le max" "max")
  ("le min" "min")
  ("la Pr" "Pr")
  ("la pr" "Pr")
  ("la probabilité" "Pr")
  ("le sin" "sin")
  ("la tan" "tan")
  ("la tangente" "tan")

  ("etc." "points")
  ("petit point" "points")
  ("petits points" "points")
  ("trois petits points" "points")
  ("point point point" "points")
  ("plus plus" "plus points plus")
  ("fois fois" "fois points fois")
  ("virgule virgule" "virgule points virgule")
  ("rond rond" "rond points rond")
  ("tenseur tenseur" "tenseur points tenseur")
  ("plus jusqu'à" "plus points plus")
  ("fois jusqu'à" "fois points fois")
  ("virgule jusqu'à" "virgule points virgule")
  ("et jusqu'à" "et points et")
  ("ou jusqu'à" "ou points ou")
  ("égal jusqu'à" "égal points égal")
  ("similaire jusqu'à" "similaire points similaire")
  ("inférieur jusqu'à" "inférieur points inférieur")
  ("inférieur égal jusqu'à" "inférieur égal points inférieur égal")
  ("supérieur jusqu'à" "supérieur points supérieur")
  ("supérieur égal jusqu'à" "supérieur égal points supérieur égal")
  ("rond jusqu'à" "rond points rond")
  ("tenseur jusqu'à" "tenseur points tenseur")

  ("similaire à" "similaire")
  ("est similaire à" "similaire")
  ("équivalent" "similaire")
  ("équivalent à" "similaire")
  ("est équivalent" "similaire")
  ("est équivalent à" "similaire")
  ("asymptotique à" "asymptotique")
  ("est asymptotique à" "asymptotique")
  ("isomorphe à" "isomorphe")
  ("est isomorphe à" "isomorphe")
  
  ("négligeable devant" "négligeable")
  ("négligeable par rapport à" "négligeable")
  ("strictement dominé par" "négligeable")
  ("est strictement dominé par" "négligeable")
  ("dominé par" "dominé")
  ("est dominé par" "dominé")

  ("la somme" "somme")
  ("le produit" "produit")
  ("l'intégral" "intégrale")
  ("l'intégrale" "intégrale")
  ("l'infini" "infini")

  ("grand chapeau" "large chapeau")
  ("grand tilde" "large tilde")
  ("grand barre" "large barre")
  ("en dessous" "dessous")
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Disambiguation
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (french-de s)
  (with prev (expr-before-cursor)
    (cond ((not prev) (speech-insert-symbol s))
          ((or (and (string? prev) (== (math-symbol-type prev) "symbol"))
               (tm-in? prev '(math-ss math-tt wide wide*))
	       (tm-is? prev 'big)
	       (editing-big-operator?))
           (cond ((or (stats-role? `(concat ,prev (rsub ,s)))
                      (stats-role? `(concat ,prev (rsup ,s)))
                      (stats-role? `(concat ,prev (around "(" ,s ")")))
                      (stats-role? `(concat ,prev (around* "(" ,s ")"))))
                  (speech-insert-symbol s))
                 ((or (== s "2")
                      (stats-role? `(concat ,prev (around "(" "" ")")))
                      (stats-role? `(concat ,prev (around* "(" "" ")"))))
                  (speech-of))
                 (else (speech-insert-symbol s))))
          (else (speech-insert-symbol s)))))

(speech-map french math
  ;; psi/xi/6 ambiguity
  ("psi/xi" (speech-insert-best "<psi>" "<xi>"))
  ("psi/xi/6" (speech-best-letter "<psi>" "<xi>" "6"))
  ("psi/xi/6 chapeau" (speech-best-accent "^" "<psi>" "<xi>"))
  ("psi/xi/6 tilde" (speech-best-accent "~" "<psi>" "<xi>"))
  ("psi/xi/6 barre" (speech-best-accent "<bar>" "<psi>" "<xi>"))

  ;; nu/9 ambiguity
  ("nu/9" (speech-best-letter "<nu>" "9"))
  ("nu/9 chapeau" (speech-best-accent "^" "<nu>"))
  ("nu/9 tilde" (speech-best-accent "~" "<nu>"))
  ("nu/9 barre" (speech-best-accent "<bar>" "<nu>"))

  ;; 2/de and related ambiguities
  ("2/de" (french-de "2"))
  ("d/de" (french-de "d"))
  ("t/de" (french-de "t"))

  ;; 4/k ambiguity
  ("k/4" (speech-best-letter "k" "4"))

  ;; a/e ambiguity
  ("a/a" (speech-insert-best "a")) ;; prevent problems with "a n", "a p", ...
  ("a/e" (speech-insert-best "a" "e"))

  ;; b/d/p/t and related ambiguities
  ("b/d" (speech-insert-best "b" "d"))
  ("b/d/p" (speech-insert-best "b" "d" "p"))
  ("d/b" (speech-insert-best "d" "b"))
  ("p/b" (speech-insert-best "p" "b"))
  ("p/t" (speech-insert-best "p" "t"))
  ("t/d" (speech-insert-best "t" "d"))
  
  ;; g/j ambiguity
  ("g/j" (speech-insert-best "g" "j"))

  ;; m/n ambiguity
  ("m/n" (speech-insert-best "m" "n"))
  )

(speech-reduce french math
  ("psi/xi/6 de" "psi/xi de")
  ("nu/9 de" "nu de")
  ("psi/xi/6 prime" "psi/xi prime")
  ("nu/9 prime" "nu prime")
  ("psi/xi/6 rond" "psi/xi rond")
  ("nu/9 rond" "nu rond")
  ("rond psi/xi/6" "rond psi/xi")
  ("rond nu/9" "rond nu")

  ("une" "un")
  ("en" "un")
  ("si" "psi/xi")
  )

(speech-adjust french math
  ("qu'à" "k")
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Adjust wrongly recognized words
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(speech-adjust french math
  ;; Adjust latin letters
  ("ah" "a")
  ("a-ha" "a")
  ("bae" "b")
  ("bébé" "b")
  ("ben" "b")
  ("bye" "b")
  ("c'est" "c")
  ("say" "c")
  ("day" "d")
  ("des" "d/de")
  ("dès" "d")
  ("eux" "e")
  ("œuf" "f")
  ("j'ai" "g")
  ("j'est" "g")
  ("gay" "g")
  ("âge" "h")
  ("ashe" "h")
  ("hache" "h")
  ("aïe" "i")
  ("il" "i")
  ("ils" "i")
  ("caca" "k")
  ("car" "k")
  ("cara" "k")
  ("cas" "k")
  ("casse" "k")
  ("kaaris" "k")
  ("j'y" "j")
  ("aile" "l")
  ("ailes" "l")
  ("el" "l")
  ("elle" "l")
  ("aime" "m")
  ("aisne" "n")
  ("haine" "n")
  ("and" "n")
  ("au" "o")
  ("beau" "o")
  ("eau" "o")
  ("eaux" "o")
  ("haut" "o")
  ("homepod" "o")
  ("oh" "o")
  ("os" "o")
  ("paye" "p")
  ("pays" "p")
  ("cul" "q")
  ("her" "r")
  ("air" "r")
  ("est-ce" "s")
  ("stay" "t")
  ("t'es" "t")
  ("taille" "t")
  ("tes" "t")
  ("eu" "u")
  ("hue" "u")
  ("û" "u")
  ("vais" "v")
  ("vay" "v")
  ("value" "v")
  ("vert" "v")
  ("vii" "v")
  ("that" "z")

  ;; Adjust greek letters
  ("bâtard" "beta")
  ("beata" "beta")
  ("bertin" "beta")
  ("bêta" "beta")
  ("bête un" "beta")
  ("bête a" "beta")
  ("bête à" "beta")
  ("betta" "beta")
  ("d'état" "beta")
  ("camas" "gamma")
  ("gama" "gamma")
  ("gamard" "gamma")
  ("gamin" "gamma")
  ("kama" "gamma")
  ("k ma" "gamma")
  ("epsylon" "epsilon")
  ("silone" "epsilon")
  ("si l'homme" "epsilon")
  ("vous êtes a" "zeta")
  ("vous êtes à" "zeta")
  ("za" "zeta")
  ("zaatar" "zeta")
  ("zelda" "zeta")
  ("zêta" "zeta")
  ("atteint" "eta")
  ("est un" "eta")
  ("est a" "eta")
  ("est à" "eta")
  ("est tard" "eta")
  ("et ta" "eta")
  ("et t'as" "eta")
  ("êta" "eta")
  ("état" "eta")
  ("éteins" "eta")
  ("êtes a" "eta")
  ("êtes à" "eta")
  ("insta" "eta")
  ("greta" "eta")
  ("pétard" "theta")
  ("tata" "theta")
  ("teta" "theta")
  ("tête a" "theta")
  ("tête à" "theta")
  ("têtard" "theta")
  ("thêta" "theta")
  ("tintin" "theta")
  ("t'es a" "theta")
  ("t'es à" "theta")
  ("t'es pas" "theta")
  ("t'es t'as" "theta")
  ("ciotat" "iota")
  ("yo t'as" "iota")
  ("yota" "iota")
  ("cap a" "kappa")
  ("cap à" "kappa")
  ("capa" "kappa")
  ("qu'à pas" "kappa")
  ("lakhdar" "lambda")
  ("lanta" "lambda")
  ("lampe a" "lambda")
  ("lampe à" "lambda")
  ("lampe ta" "lambda")
  ("lampe tard" "lambda")
  ("lampe torche" "lambda")
  ("lampe t'as" "lambda")
  ("lent a" "lambda")
  ("lent à" "lambda")
  ("lomepal" "lambda")
  ("mieux" "mu")
  ("mou" "mu")
  ("mur" "mu")
  ("mûr" "mu")
  ("mubi" "mu")
  ("mumu" "mu")
  ("mus" "mu")
  ("nue" "nu")
  ("nul" "nu")
  ;;("si" "xi")
  ("au micro" "omicron")
  ("au micro en" "omicron")
  ("aux migrants" "omicron")
  ("haut microns" "omicron")
  ("pie" "pi")
  ("pile" "pi")
  ("pis" "pi")
  ("pipi" "pi")
  ("euro" "rho")
  ("euros" "rho")
  ("raux" "rho")
  ("raw" "rho")
  ("rhô" "rho")
  ("robe" "rho")
  ("robot" "rho")
  ("rock" "rho")
  ("roh" "rho")
  ("rome" "rho")
  ("rose" "rho")
  ("roue" "rho")
  ("rouge" "rho")
  ("row" "rho")
  ("c'est ma" "sigma")
  ("chic ma" "sigma")
  ("cinéma" "sigma")
  ("cite-moi" "sigma")
  ("cite-moi un" "sigma")
  ("si ma" "sigma")
  ("site ma" "sigma")
  ("sigmar" "sigma")
  ("sixma" "sigma")
  ("auto" "tau")
  ("taux" "tau")
  ("to" "tau")
  ("toe" "tau")
  ("tony" "tau")
  ("tôt" "tau")
  ("town" "tau")
  ("options" "upsilon")
  ("upside down" "upsilon")
  ("ypsilon" "upsilon")
  ("fille" "phi")
  ("fit" "phi")
  ("psy" "psi")
  ;;("si" "psi")
  ("qui" "chi")
  ("oméga" "omega")

  ;; Adjust letter combinations
  ("assez" "a c")
  ("a f" "a/e f")
  ("ah oui" "a i")
  ("ai" "a i")
  ("aie" "a i")
  ("aïe" "a i")
  ("haï" "a i")
  ("haïti" "a i")
  ("agit" "a i")
  ("a j" "a/e j")
  ("ak" "a/e k")
  ("aka" "a/a k")
  ("al" "a/e l")
  ("a m" "a/e m")
  ("a n" "a/e n")
  ("an" "a/e n")
  ("agen" "a/a n")
  ("arènes" "a n")
  ("la haine" "a n")
  ("août" "a o")
  ("a p" "a/e p")
  ("app" "a/a p")
  ("apple" "a/a p")
  ("appeler" "a/a p")
  ("appelle" "a/a p")
  ("happer" "a/a p")
  ("a q" "a/e q")
  ("a r" "a/e r")
  ("ar" "a/a r")
  ("a s" "a/e s")
  ("as" "a/a s")
  ("maes" "a s")
  ("a t" "a/e t")
  ("athée" "a/a t")
  ("avez" "a v")
  ("a w" "a/e w")
  ("a y" "a/e y")
  ("a z" "a/e z")
  ("béa" "b a")
  ("béat" "b a")
  ("léa" "b a")
  ("bébé" "b/d b")
  ("baisser" "b c")
  ("bédé" "b d")
  ("bid" "b d")
  ("bide" "b d")
  ("b f" "b/d f")
  ("b h" "b/d h")
  ("baby" "b i")
  ("bailey" "b i")
  ("benji" "b j")
  ("b b l" "b l")
  ("b p" "b/d p")
  ("mets q" "b q")
  ("b t/de s" "b s")
  ("becter" "b t")
  ("mets u" "b/d/p u")
  ("b m w" "b v")
  ("b x" "b/d x")
  ("c'est des" "c d")
  ("c'est des" "c d")
  ("c d/de i" "c i")
  ("c'est aime" "c m/n")
  ("c'est où" "c o")
  ("c'était" "c t")
  ("dis à" "d a")
  ("dis siri" "d c")
  ("des œuf" "d/b e")
  ("des œufs" "d/b e")
  ("d f" "d/b f")
  ("daily" "d/b i")
  ("dave" "d i")
  ("d k" "d/b k")
  ("déca" "d k")
  ("d l" "d/b l")
  ("des ailes" "d/b l")
  ("d m" "d m/n")
  ("d s" "d/b s")
  ("déesse" "d s")
  ("d'été" "d t")
  ("gaité" "d t")
  ("des v" "d/b v")
  ("dévé" "d v")
  ("dévérrouiller" "d v")
  ("div" "d v")
  ("mets x" "d xOuais")
  ("d y" "d/b y")
  ("ea" "e a")
  ("ee" "e e")
  ("ei" "e i")
  ("eij" "e i j")
  ("ek" "e k")
  ("eo" "e o")
  ("es" "e s")
  ("e.t." "e t")
  ("ex" "e x")
  ("f.a." "f a")
  ("f g" "f g/j")
  ("f.i." "f i")
  ("f.o." "f o")
  ("f.u." "f u")
  ("j'ai des" "g d")
  ("gie" "g e")
  ("gégé" "g g")
  ("gigi" "g j")
  ("j'ai quatre" "g 4/k")
  ("gen" "g n")
  ("géhenne" "g n")
  ("jay-z" "g z")
  ("h e" "h e")
  ("h a h" "h h")
  ("hi" "h i")
  ("machika" "h k")
  ("rachel" "h l")
  ("aachen" "h n")
  ("ho" "h o")
  ("sache que" "h q")
  ("acheter" "h t")
  ("achevé" "h v")
  ("ah je vais" "h v")
  ("hiv" "h v")

  ("p d" "p/t d")
  ("p s" "p/b s")
  ("p y" "p/b y")

  ("t h" "t/d h")
  ("t k" "t/d k")
  ("t p" "t/d p")
  ("t s" "t/d s")
  ("t t" "d/t t")
  ("t v" "t/d v")

  ;; Adjust miscellaneous symbols and constants
  ("constante dans une heure" "constante d'euler")
  ("constante de eyelar" "constante d'euler")

  ;; Adjust addition 'plus'
  ("capucel" "k plus l")
  ("en plus" "n plus")
  ("au plus" "o plus")
  ("au plus près" "o plus p")
  ("en haut plus" "o plus")
  ("opus" "o plus")
  ("pute plus cul" "p plus q")
  ("pupuce" "q plus")
  ("que plus" "q plus")
  ("t plus plus" "t plus u")
  ("d' plus" "delta plus")
  ("mets plus" "mu plus")
  ("ne plus" "nu plus")
  ("neuf plus" "nu/9 plus")
  ("gros plus" "rho plus")
  ("si plus" "psi/xi plus")
  ("six plus" "psi/xi/6 plus")
  ("youssef" "plus f")
  ("plusi" "plus i")
  ("plus cher" "plus r")
  ("plus spée" "plus p")
  ("plus d'" "plus delta")
  ("plus mieux" "plus mu")
  ("plus neuf" "plus nu/9")
  ("plus si" "plus psi/xi")
  ("plus six" "plus psi/xi/6")
  
  ;; Adjust subtraction 'moins'
  ("moi" "moins")
  ("dis-moi" "d moins")
  ("e-moi" "e moins")
  ("f-moi" "f moins")
  ("j'ai-moi" "g moins")
  ("h-moi" "h moins")
  ("i-moi" "i moins")
  ("k-moi" "k moins")
  ("l-moi" "l moins")
  ("elle-moi" "l moins")
  ("m-moi" "m moins")
  ("aime-moi" "m moins")
  ("o-moi" "o moins")
  ("au-moi" "o moins")
  ("au mois" "o moins")
  ("r-moi" "r moins")
  ("est-ce-moi" "s moins")
  ("témoin" "t moins")
  ("allume moi" "u moins")
  ("allume-moi" "u moins")
  ("du moins" "u moins")
  ("fais-moi" "v moins")
  ("w-moi" "w moins")
  ("y-moi" "y moins")
  ("z-moi" "z moins")
  ("delta-moi" "delta moins")
  ("epsilon-moi" "delta moins")
  ("faites moi" "theta moins")
  ("faites-moi" "theta moins")
  ("pète-moi" "theta moins")
  ("pétard-moi" "theta moins")
  ("theta-moi" "theta moins")
  ("thêta-moi" "theta moins")
  ("iota-moi" "iota moins")
  ("kappa-moi" "kappa moins")
  ("lambda-moi" "lambda moins")
  ("mets-moi" "mu moins")
  ("mu-moi" "mu moins")
  ("neuf moins" "nu/9 moins")
  ("omicron-moi" "omicron moins")
  ("rho-moi" "rho moins")
  ("rose-moi" "rho moins")
  ("sigma one" "sigma moins")
  ("tau-moi" "tau moins")
  ("toe-moi" "tau moins")
  ("file-moi" "phi moins")
  ("fille-moi" "phi moins")
  ("film-moi" "phi moins")
  ("si moins" "psi/xi moins")
  ("six moins" "psi/xi/6 moins")
  ("qui-moi" "qui moins")
  ("oméga-moi" "omega moins")
  ("moinsi" "moins i")
  ("moinsi-moi" "moins i moins")
  ("monter" "moins t")
  ("moinsw" "moins w")
  ("moinsy" "moins y")
  ("moins aide" "moins z")
  ("moins bête" "moins beta")
  ("moins bête a" "moins beta")
  ("moins bête à" "moins beta")
  ("noisette" "moins zeta")
  ("moins ai pas" "moins eta")
  ("moins êtes" "moins eta")
  ("moins êtes a" "moins eta")
  ("moins êtes à" "moins eta")
  ("mon tel éteint" "moins theta")
  ("moins de tête" "moins theta")
  ("moins de tête a" "moins theta")
  ("moins de tête à" "moins theta")
  ("moins tête" "moins theta")
  ("moins tête a" "moins theta")
  ("moins tête à" "moins theta")
  ("moins neuf" "moins nu/9")
  ("moins un pays" "moins pi")
  ("moins gros" "moins rho")
  ("moins un rot" "moins rho")
  ("manteau" "moins tau")
  ("moins si" "moins psi/xi")
  ("moins six" "moins psi/xi/6")
  ("monkey" "moins chi")
  ("moins un chi" "moins chi")

  ;; Adjust multiplication 'fois'
  ("foie" "fois")
  ("fort" "fois")
  ("à chaque fois" "h fois")
  ("hey fois" "p fois")
  ("t une fois" "t fois")
  ("t'es une fois" "t fois")
  ("rue fois" "u fois")
  ("lampe tafua" "lambda fois")
  ("mets fois" "mu fois")
  ("meuf à" "mu fois")
  ("meuf fois" "mu fois")
  ("neuf fois" "nu/9 fois")
  ("rho de fois" "rho fois")
  ("si fois" "psi/xi fois")
  ("six fois" "psi/xi/6 fois")
  ("foisa" "fois i")
  ("fois 10" "fois d")
  ("fois deux" "fois d")
  ("fois 2/de" "fois d")
  ("fois quatre" "fois k")
  ("foisi" "fois i")
  ("fois on" "fois o")
  ("fois où" "fois o")
  ("foiso" "fois o")
  ("foisu" "fois u")
  ("fadel tard" "fois delta")
  ("fois neuf" "fois nu/9")
  ("fois si" "fois psi/xi")
  ("fois six" "fois psi/xi")
  ("fois zéro" "fois rho")
  ("photo" "fois tau")
  ("photos" "fois tau")

  ;; Adjust multiplication 'croix'
  ("croisette" "fois zeta")

  ;; Adjust composition operator 'rond'
  ("rang" "rond")
  ("rend" "rond")
  ("ron" "rond")
  ("run" "rond")
  ("aaron" "a rond")
  ("beyoncé" "b rond c")
  ("irons" "i rond")
  ("giron" "j rond")
  ("caron" "k rond")
  ("aileron" "l rond")
  ("huron" "u rond")
  ("véron" "v rond")
  ("verrons" "v rond")
  ("rondé" "rond d")
  ("ranger" "rond g")
  ("ronger" "rond g")
  ("ron ginny" "rond j")
  ("rongie" "rond j")
  ("ronca" "rond k")
  ("rompez" "rond p")
  ("remonter" "rond t")
  ("ranvée" "rond v")
  ("ranger z" "rond z")

  ;; Adjust predicates 'égal'
  ("égale" "égal")
  ("égal à jusqu'à" "égal un jusqu'à")
  ("fais gaffe" "f égal")
  ("quatre égal" "k égal")
  ("elle est égal" "l égal")
  ("ou égal" "u égal")
  ("je v égal" "v égal")
  ("bête égal" "beta égal")
  ("vous êtes égal" "zeta égal")
  ("tête égal" "theta égal")
  ("ferme ta égal" "lambda égal")
  ("neuf égal" "nu/9 égal")
  ("si égal" "psi/xi égal")
  ("six égal" "psi/xi/6 égal")
  ("qui est égal" "chi égal")
  ("égalité" "égal t")
  ("égal bête à" "égal beta")
  ("égal bête a" "égal beta")
  ("égal bête" "égal beta")
  ("égal tête à" "égal theta")
  ("égal tête a" "égal theta")
  ("égal tête" "égal theta")
  ("également" "égal mu")
  ("égal neuf" "égal nu/9")
  ("est galaxie" "égal xi")
  ("et galaxie" "égal xi")
  ("égal si" "égal psi/xi")
  ("égal six" "égal psi/xi/6")

  ;; Adjust punctuation
  ("telle" "tel")
  ("tel qu'" "tel que")
  ("a-t-elle" "a tel")
  (". diagonaux" "points diagonaux")
  (". montant" "points montants")

  ;; Adjust operators
  ("dette" "det")
  
  ;; Adjust function applications using the word 'de'
  ("the" "de")
  ("bédé" "b de")
  ("belle des" "b de")
  ("c'est des" "c de")
  ("d'aider" "d de")
  ("j'ai des" "g de")
  ("j'ai des aide" "g de z")
  ("j'aide" "g de")
  ("j'ai dit" "g de")
  ("j'ai w w" "g de w")
  ("idée" "i de")
  ("i de ée" "i de")
  ("j'y d" "j de")
  ("qu'à de" "k de")
  ("qu'à 2/de" "k de")
  ("elle d" "l d/de")
  ("un d" "n de")
  ("cul des" "q de")
  ("que des" "q de")
  ("est-ce d" "s de")
  ("ac/dc" "s de c")
  ("u d x" "u de x")
  ("wylix" "w de x")
  ("qu'à mad" "gamma de")
  ("gamin d" "gamma d/de")
  ("epsilon d" "epsilon d/de")
  ("zeta d" "zeta d/de")
  ("iota a de" "iota de")
  ("iota d" "iota d/de")
  ("kappa d" "kappa d/de")
  ("lambda d" "lambda d/de")
  ("medics" "mu de x")
  ("mieux des aides" "mu de z")
  ("mu d" "mu d/de")
  ("nu d" "nu d/de")
  ("omicron d" "omicron d/de")
  ("au micro-ondes" "omicron de")
  ("road" "rho de")
  ("rodè" "rho de")
  ("rodé" "rho de")
  ("rho de 2/de" "rho de")
  ("site mad" "sigma de")
  ("upsilon d" "upsilon d/de")
  ("chi d" "chi d/de")
  ("omega d" "omega d/de")
  ("décès" "de c")
  ("dédé" "de d")
  ("ducat" "de k")
  ("du cul" "de q")
  ("dévé" "de v")
  ("des aides" "de z")
  ("de êtes" "de eta")
  ("décapas" "de kappa")
  ("the road" "de rho")

  ;; Adjust subscripts
  ("un 10" "indice")
  ("un dix" "indice")

  ;; Adjust powers and superscripts
  ("au carré" "carré")
  ("est carré" "carré")
  ("chaos carré" "k carré")
  ("the contours" "de contour")

  ;; Adjust fractions
  ("sûr" "sur")
  ("assure" "a sur")
  ("belle sur" "b sur")
  ("dis sur" "d sur")
  ("bref sur" "f sur")
  ("qu'à sur" "k sur")
  ("bien sûr" "n sur")
  ("ou sûr" "o sur")
  ("où sûr" "o sur")
  ("culture" "q sur")
  ("bus sur" "u sur")
  ("zappe sur" "z sur")
  ("tête sur" "theta sur")
  ("je t'assure" "zeta sur")
  ("but sur" "mu sur")
  ("mesure" "mu sur")
  ("mets sur" "mu sur")
  ("nous sur" "nu sur")
  ("neuf sur" "nu/9 sur")
  ("si sur" "xi sur")
  ("omicron de sur" "omicron sur")
  ("rond sur" "rho sur")
  ("site massures" "sigma sur")
  ("autosur" "tau sur")
  ("chaussures" "tau sur")
  ("si sur" "psi/xi sur")
  ("six sur" "psi/xi/6 sur")
  ("ok sur" "chi sur")
  ("sur ces" "sur c")
  ("sur ses" "sur c")
  ("sur siri" "sur c")
  ("surgé" "sur g")
  ("sur elle" "sur l")
  ("sur aisne" "sur n")
  ("sur on" "sur o")
  ("sur où" "sur o")
  ("sur que" "sur q")
  ("sur terre" "sur r")
  ("sur veille" "sur v")
  ("surveille" "sur v")
  ("suzette" "sur zeta")
  ("sur neuf" "sur nu/9")
  ("sur que si" "sur xi")
  ("sûr que si" "sur xi")
  ("sur tilles" "sur pi")
  ("sureau" "sur rho")
  ("surtout" "sur tau")
  ("sur si" "sur psi/xi")
  ("sur six" "sur psi/xi/6")

  ;; Adjust wide hats
  ("chapo" "chapeau")
  ("chapeaux" "chapeau")
  ("quatre chapeau" "k chapeau")
  ("ou chapeau" "u chapeau")
  ("veille chapeau" "v chapeau")
  ("vieille chapeau" "v chapeau")
  ("six chapeau" "psi chapeau")

  ;; Adjust wide tildas
  ("bathilde" "b tilde")
  ("the tilde" "e tilde")
  ("ou tilde" "o tilde")
  ("est tilde" "s tilde")
  ("ti tilde" "t tilde")
  ("utile" "u tilde")
  ("utilité" "u tilde")
  ("veille tilde" "v tilde")
  ("vieille tilde" "v tilde")
  ("gars mathilde" "gamma tilde")

  ;; Adjust wide bars
  ("bars" "barre")
  ("bar" "barre")
  ("bahr" "barre")
  ("var" "barre")
  ("ibar" "i barre")
  ("gibard" "j barre")
  ("khabar" "k barre")
  ("mbar" "m barre")
  ("au bar" "o barre")
  ("herbart" "r barre")
  ("esbart" "s barre")
  ("hubbard" "u barre")
  ("vieil bar" "w barre")
  ("lampe tabar" "lambda barre")
  ("bibar" "pi barre")
  ("bibard" "pi barre")
  ("tibar" "pi barre")
  ("tibard" "pi barre")
  ("pivar" "pi barre") 
  ("pivard" "pi barre")
  ("robar" "rho barre")
  ("robart" "rho barre")
  )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Further, more dangerous adjustments
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(speech-adjust french math
  ("six barre" "psi barre")
  ("d' sur" "delta sur")
  )
